eclipse-omr/omr

- .gitignore
- .jazzignore
> Add .gitignore and .jazzignore

- .gitignore
- fvtest/gctest/GCConfigTest.cpp
- fvtest/gctest/gcTestHelpers.cpp
- fvtest/gctest/gcTestHelpers.hpp
- fvtest/porttest/omrfileTest.cpp
- fvtest/porttest/omrmmapTest.cpp
- fvtest/porttest/testHelpers.cpp
- fvtest/porttest/testHelpers.hpp
- fvtest/rastest/subscriberAgent.c
- fvtest/rastest/subscriberAgentWithJ9thread.c
- fvtest/rastest/traceLogTest.cpp
- perftest/gctest/verboseGCLogParser.cpp
- perftest/omrperftest.mk
- added untracked test files into .gitignore
- added code for test file clean up for gctest, gcperftest, rastest and porttest
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>
> Fix for issue 18

- include_core/AtomicSupport.hpp
Signed-off-by: Aaron Rocha <aaronr@ca.ibm.com>
> FIX #40 : issue memory barriers on ARM

- doc/CodingStandard.md
Signed-off-by: Angela Lin <angela_lin@ca.ibm.com>
> FIX #25 : Add OMR coding standard

- fvtest/porttest/omrstrTest.cpp
- fvtest/porttest/testProcessHelpers.cpp
- include_core/omrport.h
- port/common/omrstr.c
- port/unix/omrsyslog.c
- port/zos390/omrgetjobid.c
Issue: #41
Signed-off-by: Peter Bain <pdbain@ca.ibm.com>
> Split J9STR_CODE_PLATFORM into _PLATFORM_RAW and _PLATFORM_OMR_INTERNAL

- CONTRIBUTING.md
In addition to the relatively simple commits outlined in the commit messages, I also restructured the document a bit to move the commit and pull request suggestions closer to the top.
> Issue #53 updates to contribution guidelines

- omrsigcompat/omrsig.cpp
The BSD signal API, sigvec, has been removed from GLIBC since version
2.21.
Issue: #3
> FIX #3 Test GLIBC version for sigvec macros

- example/glue/EnvironmentLanguageInterfaceImpl.cpp
- glue/EnvironmentLanguageInterfaceImpl.cpp
> Fix #76: Fix recursive exclusive vm access count

- gc/base/standard/ConcurrentGC.cpp
> Fix #80: Always run concurrent root tracing phase 4

- .gitignore
- GNUmakefile
- INSTALL
- configure
- configure.ac
- ddr_artifacts.mk
- omrmakefiles/configure.mk.in
- omrmakefiles/rules.linux.mk
- omrmakefiles/rules.mk
- port/port_objects.mk
> Fix #82 configure and makefile support for ddrgen tool

- gc/startup/omrgcstartup.cpp
> Fix #84: Shutdown GlobalCollector properly

- omr/startup/omrvmstartup.cpp
> Fix #93 by changing the thread name to "Main Thread"

- gc/verbose/VerboseHandlerOutput.cpp
> Add missing format specifier

- port/unix/omrintrospect.c
* close_wrapper() now properly handles EINTR.
* The return value of setup_native_thread() is now used properly.
* The workaround for an ancient scheduler bug is no longer used on Linux.
> fix issue #106

- gc/base/standard/CopyScanCacheList.cpp
- gc/base/standard/CopyScanCacheList.hpp
- gc/base/standard/Scavenger.cpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
#90 update CopyScanCacheList implementation to increase the size incrementally as the required or heap expansion.
> #90 reduce scanCache initial native footprint

- gc/base/MemoryPoolLargeObjects.hpp
#100 Signed-off-by: Lin Hu <linhu@ca.ibm.com>
> new public API to access ratio of LOA

- thread/common/threadhelpers.cpp
Signed-off-by: Bjørn Vårdal <bjornvar@ca.ibm.com>
> Resolve #136: Test lock value before acquiring

- port/unix/omrintrospect.c
The previous workaround is still necessary for Linux kernel releases
2.x, but not for the reasons described by the original comment in the
code. Instead, signals are either being lost or some threads are
chosen to receive more than one. Either way, not all other threads
have reached the signal handler before the controller starts waiting
for client threads to trace their stacks. Sending additional signals
(and yielding) while the controller is waiting for a client thread
to trace its stack deals with both kinds of problems.
> issue #106, take 2

- gc/base/standard/ConcurrentOverflow.cpp
update overflow correspondent states and increment overflow counter in concurrent overflow case
> Issue#144: update overflow correspondent states and increment overflow counter

- fvtest/gctest/GCConfigTest.cpp
- fvtest/gctest/GCConfigTest.hpp
- fvtest/gctest/StartupManagerTestExample.cpp
- fvtest/gctest/StartupManagerTestExample.hpp
- fvtest/gctest/gcTestHelpers.cpp
- fvtest/gctest/gcTestHelpers.hpp
- fvtest/threadextendedtest/threadExtendedTestHelpers.hpp
- fvtest/util/testEnvironment.hpp
- create a simple logger
- change gctest to use logger
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>
> Issue #163: add simple logger for fvtest

- compiler/z/codegen/OMRCodeGenerator.cpp
Several if blocks querying for OOL can be merged into nested ifs to
simplify logic. In addition to this there are two unused CS2 arrays
being created which can be removed.
> Merge several OOL blocks into one and remove unused CS2 tables

- compiler/z/codegen/OMRTreeEvaluator.cpp
A common scenario in object-oriented languages is to copy a field from
one object to another. In OMR this is translated into indirect loads and
stores. If the indirect load of the field we are loading is not
referenced anywhere but the store we can use a memory-memory copy
instruction to carry out the load-store sequence.
This path is currently implemented for direct loads. This commit adds
support for indirect loads. The MVC instruction is preferred to the L +
ST instruction sequence as it is one instruction less to decode, it has
smaller path length (6 bytes vs 8 bytes), and in the worst case scenario
the local register allocator may choose to HPR upgrade the L + ST
sequence to a LFH + STFH instruction sequence which is 12 bytes of path
length.
In addition to the above points the MVC …
> Reduce indirect memory-memory copies on System Z

- compiler/optimizer/OMRDeadTreesElimination.hpp
- compiler/optimizer/ValuePropagation.hpp
Add documentation for dead trees elimination and
local value propagation.
> Add more documentation for optimizations

- compiler/optimizer/InductionVariable.cpp
- compiler/optimizer/InductionVariable.hpp
De-duplicate code from `TR_LoopStrider::examineTreeForInductionVariableUse()` and create the function `TR_LoopStrider::examineOpCodesForInductionVariableUse()` for it.
> De-duplicate code within InductionVariable.cpp

- fvtest/compilertest/README.md
Document how to build and run the test compiler.
[ci skip] Documentation change.
Issue #221
> Starting documentation of the Test compiler

- compiler/codegen/ScratchRegisterManager.hpp
This comment wasn't written by me, but has existed outside the source
code for quite some time now. By injecting it into the code, we give it
the opportunity to be maintained and discovered near the subject of
documentation.
[ci skip] Documentation change.
> Contribute internal Scratch Register Manager docs

- compiler/compile/OMRCompilation.hpp
This macro is a key part of the Testarossa compiler technology's
servicability story, but it has only been documented externally to the
code base prior to this commit.
This contributes internal documentation to the external codebase so that
it can be maintained and modified along with the codebase.
[ci skip] Documentation Change.
> Contribute documentation of performTransformation

- thread/linux/omrthreadnuma.c
Use the "cpumap" file if possible instead of parsing every entry in the
"node" directory.
Signed-off-by: Peter Bain <pdbain@ca.ibm.com>
> Issue #173 Rewrite NUMA CPU affinity parsing code for speed

- compiler/optimizer/GeneralLoopUnroller.hpp
- compiler/optimizer/InductionVariable.hpp
- compiler/optimizer/LoopCanonicalizer.hpp
- compiler/optimizer/LoopReducer.hpp
- compiler/optimizer/LoopVersioner.hpp
- compiler/optimizer/RedundantAsyncCheckRemoval.hpp
- compiler/optimizer/ValuePropagation.hpp
Add documentation to loop canonicalizer, loop inverter, loop unroller,
loop strider, loop reducer, loop versioner, loop specializer, and
redundant async check removal.
> Add documentation to loop optimizations

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
> Revert "Remove the deprecated Compilation::removeTree"

- port/unix/omrsysinfo.c
omrsysinfo_get_number_CPUs_by_type(OMRPORT_CPU_BOUND) fails on
machines with large numbers of cpus due to the fixed sized
stack allocated cpu_set_t structure.  This change adds a fall
back path that allows the sched_getaffinity call to succeed
by using a dynamically allocated cpu_set_t.
issue #311 
> Handle sched_getaffinity for > 1024 cpus

- compiler/optimizer/VPHandlers.cpp
VP (value propagation) attempts in `constrainIaload()` to constrain the
class that results from an `aloadi` of the array component type from a
known class. Care must be taken to ensure that the known class really
represents an array type, since it might be a non-array type in cases
where VP is looking at a dead path.
Signed-off-by: Devin Papineau <devinmp@ca.ibm.com>
> Check array element type loads in constrainIaload

- doc/compiler/ProblemDetermination.md
This guide provide tips and tricks for debugging the compiler component,
along with a recommended methodology for ensuring you have identified a
compiler bug.
[skip ci] Documentation only.
> Initial draft of problem determination guide.

- fvtest/threadextendedtest/processTimeTest.cpp
- Disable TestThreadCpuTime by default. It's run time is too long. Fixes
issue #181, where we are timing out on Travis-CI.
- Write simpler, shorter tests for monotonic CPU time.
- Make better use of the gtest assertions.
- Fix broken application CPU time test.
- Format in the WebKit style.
> Simplify and shorten process time tests

- compiler/codegen/OutOfLineCodeSection.hpp
Add high-level documentation of what benefits can be achieved by using
an OOL code section and how such benefits are achieved.
[ci skip] Documentation only.
> Document TR_OutOfLineCodeSection

- compiler/optimizer/CatchBlockRemover.cpp
- compiler/optimizer/FieldPrivatizer.cpp
- compiler/optimizer/LocalDeadStoreElimination.cpp
- compiler/optimizer/LocalDeadStoreElimination.hpp
- compiler/optimizer/OMRLocalCSE.cpp
- compiler/optimizer/OMRLocalCSE.hpp
- compiler/optimizer/PartialRedundancy.hpp
Also clean up documentation for other optimizations
Signed-off-by: Xiaoli Liang xsliang@ca.ibm.com
> Add documentation for Partial Redundancy Elimination

- doc/compiler/optimizer/Inliner.md
This is mostly introduction and skeleton as @mstoodle suggested. 
Basically, my plan here is to keep resolving **TODOs** until they are all fixed and PR is in a decent shape to be merged. 
fyi: 
@vijaysun-omr @cathyzhyi @andrewcraik
> Inliner documentation

- example/main.cpp
The _vmAccessMutex should be initialized before use.  Or else, there would be
an exception thrown from libpthread.so.  This fix include the initialization of exampleVM._vmAccessMutex when startup and also include the destroy of it when system is shutdown.
Issue: #458
Signed-off-by: Gavin Zhang <zheddie@163.com>
> Initialize the vmAccessMutex before use

- compiler/optimizer/Inliner.cpp
Some experimental support was added to the inliner to do special guard generation in HCR mode when OSR is enabled. This experimental code is not enabled by default and is no longer useful so this commit removes this code - HCR guards should always be generated the same way.
> Cleanup inliner OSR HCR code

- example/main.cpp
- Switch the example to use the OMR_Initialize_VM/OMR_Shutdown_VM APIs
to reduce the amount of code for a simple example
- Call the OMR_GC_AllocateNoGC and OMR_GC_Allocate APIs to allocate
objects as this is preferred over using the internal allocation APIs
which require a deeper understanding of how the GC works
> Clean up of GC example

- jitbuilder/release/.gitignore
> Ignore conststring executable

- compiler/il/OMRILOps.hpp
- compiler/ilgen/IlBuilder.cpp
- compiler/ilgen/IlBuilder.hpp
Signed-off-by: Shuyu Li <shuyuli@ca.ibm.com>
> Add UnsignedAddWithOverFlow in IlBuilder

- compiler/optimizer/InductionVariable.cpp
IVA (induction variable analysis) has been rejecting primary induction
variable candidates whenever the loop test is expressed as a comparison
against a load of the variable, and the load has reference count 1. Such
loop tests would be subjected to the requirements for non-load
expressions: that there be a store to the variable earlier in the same
extended block, and that the expression tested be the right-hand side of
the last such store. But the load can't possibly appear directly under a
store, because if it did, it would have reference count >=2.
When analyzing the loop test, IVA now determines whether a load could
possibly be evaluated earlier than the loop test tree, based on the
reference count of the load, and the reference count of its parent
conversion operation if any. If a …
> Stop IVA rejecting tests of loads with refcount 1

- compiler/z/codegen/OMRInstruction.cpp
The isInternalControlFlowOneEntryOneExit helper function in the z
version of OMRInstruction.cpp uses a CS2::ArrayOf local to accumulate
known labels for use in determining whether or not branch instructions'
targets are either local or non-local.  This change set replaces that
container with a TR::deque, and changes the iteration of the container
from using an integer index to using iterators.  Finally, this change
adds a break statement if we find a matching label to avoid needlessly
continuing through the container after we have a confirmed match.
> Use a deque for collecting internal labels

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/il/OMRILOps.hpp
- compiler/ilgen/IlBuilder.cpp
- compiler/ilgen/IlBuilder.hpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
- compiler/z/codegen/SystemLinkage.cpp
- jitbuilder/release/src/Call.cpp
- jitbuilder/release/src/Call.hpp
> Add IndirectCall service to JITBuilder

- compiler/optimizer/ValuePropagation.cpp
When transforming throw into goto, VP (value propagation) now passes the
exception object to the predicted handler in `ExceptionMeta`, rather
than in an auto. This avoids problems in case the handler reads
`ExceptionMeta` more than once, or in case it overwrites the auto.
Additionally, the transformation can now succeed for every predicted
handler, regardless of the code within the handler.
The two calls to `performTransformation()` are now collapsed into a
single call. Previously the second call could have caused the
transformation to be abandoned when it was already partially done.
When `specializedDesyncCatchBlock` is set, VP now transforms the throw
unconditionally, instead of using `performTransformation()` to ask
permission. Previously an assertion would fail if permission were …
> Fix throw to goto transformation

- port/zos390/j9csrsi_wrp.s
Avoid loading the CSRSI module on z/OS.
Loading the CSRSI module on z/OS may lead to one or more of the following error messages.
* BPXP014I ENVIRONMENT MUST BE CONTROLLED FOR DAEMON (BPX.DAEMON) PROCESSING.
* BPXP014I ENVIRONMENT MUST BE CONTROLLED FOR SERVER (BPX.SERVER) PROCESSING.
* ICH420I PROGRAM CSRSI FROM LIBRARY SYS1.CSSLIB CAUSED THE ENVIRONMENT TO BECOME UNCONTROLLED.
This change adopts the second technique as described in first reference below.
Fixes issue #590.
References:
* CSRSI Module:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.ieaa700/CSRSI_Description.htm
* About Permissions:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.icha700/padchk.htm
* Tech-note for RDz Product: …
> Avoid loading the CSRSI module on z/OS

- doc/compiler/extensible_classes/Extensible_Classes.md
- doc/compiler/extensible_classes/Extensible_Classes_in_OMR.md
This rephrases and extends the current documentation. New documentation is also added, including extensible enums, comparisons to other approaches, and connector guards.
> Add more documentation to extensible classes

- compiler/il/OMRIL.cpp
- compiler/il/OMRIL.hpp
- compiler/ilgen/IlBuilder.cpp
- compiler/ilgen/IlBuilder.hpp
- compiler/ilgen/MethodBuilder.cpp
- jitbuilder/release/src/Simple.hpp
Collection of minor improvements and fixes for JitBuilder services
> Miscellaneous JitBuilder fixes

- compiler/compile/OMRCompilation.cpp
- compiler/compile/VirtualGuard.cpp
- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/ras/Debug.cpp
A couple of small tweaks to support inlining for Ruby 2.4 branch
> Updates to support Inlining for Ruby 2.4

- compiler/optimizer/RematTools.cpp
The RematTools server to allow you to try and recompute a store on a different control flow path. This is used in the inliner to do privatized inliner argument rematerialization in the blocks on the taken side of virtual guards. The RematTools include a bunch of safety checking logic to ensure it is safe to remat a store. There is a bug in this remat logic that could cause some nodes that should be checked to be skipped. This patch fixes this problem and adds additional helpful trace to the RematTools.
> Fix bug in rematerialization safety logic

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/optimizer/OptimizationPolicy.hpp
All changes to comments and whitespace.
> Small cleanup items for the Inliner

- compiler/x/codegen/DivideCheckSnippet.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRInstruction.cpp
- compiler/x/codegen/OMRInstruction.hpp
- compiler/x/codegen/RestartSnippet.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Ops.hpp
De-duplicate logics related to opcode length calculation and binary generation.
> Consolidate logics related to opcode generation

- compiler/il/AliasSetInterface.hpp
The previous implementation of `TR_AliasSetInterface` was rather
confusing due to the nature of its class hierarchy. This commit changes
the code to use the CRTP, making the class hierarchy easier to read and
understand, since the CRTP is a well known C++ pattern.
Fixes #715 
Signed-off-by: Leonardo Banderali <leob@linux.vnet.ibm.com>
> Re-architect TR_AliasSetInterface to use the CRTP

- port/linux/omrosdump_helpers.c
- Add support for the %E,%i,%I,%P core specifier in Linux (see core(5)).
%I and %P use wildcard matching since it is impossible to determine
PID/TID value in the root namespace.
- Existing wild card matching only supports 1 wildcard field per core
file. Added check to ensure that only 1 is specified in core_pattern.
Task: 121414
> Add support for new core specifiers on Linux

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
> Add JIT Option for live monitor analysis tracing

- compiler/x/codegen/OMRInstruction.cpp
- compiler/x/codegen/X86Ops.hpp
ADDMemImms
ADDMemImm4
ADDMemReg
SUBMemImms
> Introduce additional register opcode functions

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
This was previously done for the RS overflow case but also needs to
be done in non-RS overflow backout. This fix covers both cases. The
boolean backOutFlag member has been extended to 3 states to distinguish
backOutFlagsRaised and backOutStarted conditions. Array splitting is 
inhibited only in backOutStarted state.
> Inhibit array splitting in Scavenger backout

- compiler/z/codegen/ControlFlowEvaluator.cpp
RXSBG is not supported on z9. The generation of this instruction must be
guarded with an architecture check.
Issue: #667
> Add architecture guard for RXSBG

- compiler/z/codegen/OMRTreeEvaluator.cpp
Exploit vector instructions to implement 256 bit multiply operation.
> Exploit additional vector instructions

- compiler/ilgen/BytecodeBuilder.cpp
- compiler/ilgen/BytecodeBuilder.hpp
- compiler/ilgen/IlBuilder.cpp
- compiler/ilgen/IlBuilder.hpp
- jitbuilder/release/.gitignore
- jitbuilder/release/Makefile
- jitbuilder/release/src/Conditionals.cpp
- jitbuilder/release/src/Conditionals.hpp
Add all IlBuilder IfCmp* conditionals to BytecodeBuilder
Add Unsigned varieties for all conditional services
Create IfAnd and IfOr services to help to create short-circuit conjunction/disjunctions
Create jitbuilder/release/src/Conditionals code sample
Issue: #833
> Enhance JitBuilder conditional services

- doc/compiler/extensible_classes/Extensible_Classes.md
- doc/compiler/extensible_classes/Extensible_Classes_in_OMR.md
Clarify the use of the TR:: namespace, and reformat the width of the extensible class documentation.
> Modify documentation on extensible classes. 

- compiler/x/codegen/OMRInstruction.hpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
De-duplicate logics related to instruction binary generation.
> Consolidate logics related to binary generation

- compiler/optimizer/ValuePropagation.cpp
When adding a block constraint, VP (value propagation) may attempt to
propagate it through any relative constraints on the same value number.
For this purpose VP now looks at relative global constraints in addition
to block constraints, which helps it to constrain the value of an
induction variable based on a comparison against its previous value.
Signed-off-by: Devin Papineau <devinmp@ca.ibm.com>
> Propagate through relative global constraints in VP

- tools/ddrgen/src/blob_generation/java/genBinaryBlob.cpp
- tools/ddrgen/src/blob_generation/java/genBlobJava.cpp
- tools/ddrgen/src/blob_generation/java/genSuperset.hpp
- tools/ddrgen/src/cmdline_tool/main.cpp
- tools/ddrgen/src/macros/MacroTool.cpp
- tools/ddrgen/src/scanners/dwarf/DwarfScanner.cpp
- tools/ddrgen/src/scanners/dwarf/DwarfScanner.hpp
- tools/ddrgen/src/scanners/pdb/PdbScanner.cpp
Made changes to DDRgen code so that it compiles properly on z/OS.
I also fixed the path to blackList.txt for the Windows pdb scanner.
> Changes to make DDRgen compile

- tools/ddrgen/makefile
- tools/ddrgen/src/scanners/dwarf/DwarfScanner.cpp
- tools/ddrgen/src/scanners/dwarf/DwarfScanner.hpp
Fixed the path to toolconfigure.mk in ddrgen makefile
Signed-off-by: Tony Wang <twlogger@gmail.com>
> Fixed duplicate subUDT bug in DwarfScanner

- compiler/z/codegen/FPTreeEvaluator.cpp
When dynamic literal pool is enabled we must make sure to stop using the
register within an evaluator when we no longer need it. This makes sure
the register does not "escape" and end up being kept alive throughout
the entire compilation.
> Stop using dynamic literal pool register

- gc/base/SlotObject.hpp
- gc/base/standard/Scavenger.cpp
This is a bug fix for atomic reference slot fixup. The previous
implementation was picking up the old value too late (after the copy
attempt, but it should be before).
> Atomic slot fixup by GC thread in Concurrent Scavenger

- compiler/x/codegen/OMRTreeEvaluator.cpp
Add the allocation of XMM3, which was used and but not allocated before.
Remove the allocation of termChar in OT case, as it is not used in the
new helper
Signed-off-by: Jingge Fu <jingge@ca.ibm.com>
> Update register dependencies of arraytranslate

- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/XMMBinaryArithmeticAnalyser.cpp
* Remove forceX87/forceSSE2 logic from CodeGenerator
* Remove deprecated ENABLE_FULL_STRICTFP code
> Remove some obsolete x87 code

- compiler/optimizer/Inliner.cpp
Virtual calls for inlined calls are moved to the taken side of
their guards. In OSR, however, it is necessary to also ensure
the necessary pending push temps are present. This change
ensures the call result is stored into the necessary pending
push temp slot, as this is the only change to stack that should
occur. Other pending push temps should be located before the
guard.
> Ensure virtual calls for inlined calls have PP

- Notice.html
- about.html
- asl-v20.text
- epl-v1.0.html
- longabout.html
> Add required files for Eclipse

- compiler/compile/OMRCompilation.cpp
This prohibition will be sunk into downstream projects where it makes
sense. While OMR code still needs to use the correct allocators for
memory management, this particular method of prohibition is too leaky
and broad to stand in the OMR project as a whole.
> Remove the prohibition on operator new and delete

- compiler/z/codegen/OMRCodeGenerator.cpp
With the distinction between reference arraycopy and primitive arraycopy
available we can now enable primitive arraycopy under concurrent
scavenge and disable reference arraycopy under concurrent scavenge.
A TODO is left to explain why this restriction is imposed. We plan on
addressing this restriction in a future PR.
> Disable ref. array copy for concurrent scavenge

- gc/base/standard/Scavenger.cpp
Inhibit array splitting in MM_Scavenger remembered set processing when
remembered set is in overflow state.
Also removed check for backout condition in scavenger getObjectScanner()
inline method as the flag to inhibit array splitting is applied in any
case in shouldRememberObject(), so this check is now redundant. The 
only calls to shouldRemeberObject() are from contexts where backout 
flag is set or rememebered set is in overflow state.
> Inhibit array splitting in Scavenger RS overflow

- compiler/runtime/OMRCodeCache.cpp
- compiler/runtime/OMRCodeCache.hpp
- compiler/runtime/OMRCodeCacheManager.cpp
- compiler/runtime/OMRCodeCacheManager.hpp
Remove functions specific to J9's CodeCache and CodeCacheManager from OMR.
> Remove project-specific functions

- omrmakefiles/jitinclude.mk
Signed-off-by: Joe Dekoning <joe_dekoning@ca.ibm.com>
> Addition to the include path to support future work.

- example/glue/CMakeLists.txt
> Build MarkingDelegate.cpp

- compiler/optimizer/OSRDefAnalysis.cpp
Anchored pending push loads may be placed within an OSR point's
collection of related treetops to mitigate the impact of using
pending push loads in place of the original stack contents.
This change corrects behaviour in OSR liveness analysis to identify
these anchored loads and update the liveness accordingly. It also
extends behaviour here to remove these loads once they have served
their purpose and are not commoned elsewhere.
> Support pending push loads in OSR liveness

- compiler/x/codegen/X86Ops.hpp
- compiler/x/codegen/X86Ops_inlines.hpp
Eliminated compilation warnings related to X86 binary encoding.
> Code cleanup - reduce compilation warnings

- compiler/il/symbol/OMRResolvedMethodSymbol.cpp
Under NextGenHCR, it may be necessary to transition from
the start of the method, in the event that an assumption
was invalidated during the method prologue. Therefore,
it is necessary to always add OSR infrastructure for
the outermost method with an edge to the catch block
from the start.
> Add OSR infra for NextGenHCR in outermost method

- compiler/il/symbol/OMRResolvedMethodSymbol.cpp
Under NextGenHCR, it may be necessary to transition from
the start of the method, in the event that an assumption
was invalidated during the method prologue. A prior change
added exceptions edges to handle this, however, parts
of the OSR API require an OSR point to also be present. This
change adds the OSR point, with the correct bytecode index.
> Add OSR point for NextGenHCR in outermost method

- fvtest/compilertest/README.md
Update Test Compiler documentation.
add "Contributing to Test Compiler" section.
add basic knowledge about Test Compiler
Signed-off-by: Tianyu Zuo <tianyu@ca.ibm.com>
> Update Test Compiler documentation

- compiler/runtime/Trampoline.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- scripts/build-on-travis.sh
Contains the following:
- Fixes for lint errors in p and z specific code
- Build jobs for running linter for p and z targets on Travis CI
Signed-off-by: Sajid Ahmed <Syed.Sajid.Ahmed23@ibm.com>
> Lint error fixes and travis integration

- compiler/optimizer/OSRDefAnalysis.cpp
The method entry may become an OSR point, however,
it will not be treated as an OSR point by OSR
liveness and usedef analysis. This change ensures
that it is correctly identified.
> WIP: Add OSR data for method entry

- port/zos390/omrvmem.c
Fixes #1109
Make omrvmem_reserve_memory_ex use moservices to allocate the memory above the
bar, regardless if its 4K pageable or not
Signed-off-by: <pdbain@ca.ibm.com>
> Use moservices for all allocations above bar

- CMakeLists.txt
- tools/CMakeLists.txt
A couple small improvements to the CMakeLists.
> Small CMake Improvements

- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRMachine.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRRegisterDependency.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCDebug.cpp
- compiler/p/codegen/PPCInstruction.cpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/p/codegen/PPCTableOfConstants.cpp
Code that was commented out was removed.
> Removed dead PPC code

- gc/base/MemorySubSpaceGeneric.cpp
- gc/base/standard/ConcurrentGC.cpp
> Reset GCExtensionBase fields on shutdown

- compiler/z/codegen/OMRTreeEvaluator.cpp
iu2l was not evaluated and resulted in incorrect array indexing in
BigInteger Multiplication operations.
This is fixed by calling generic load helper if the input is unsigned; and
we skip the node evaluations only if the nodes are signed and already
sign exnended.
> Fix iu2l not being evaluated on z systems

- compiler/cs2/arrayof.h
- compiler/cs2/bitvectr.h
- compiler/cs2/tableof.h
- compiler/infra/BitVector.hpp
- compiler/infra/OMRCfg.cpp
- compiler/optimizer/BitVectorAnalysis.cpp
- compiler/optimizer/Dominators.cpp
- compiler/optimizer/RegisterCandidate.cpp
- compiler/optimizer/StructuralAnalysis.cpp
- compiler/optimizer/StructuralAnalysis.hpp
Attempt to fix potential for crashes if resource acquisition fails during an operation on CS2::TableOf
> Exception safety

- compiler/control/OMROptions.cpp
Introduce an option disableRMODE64 to allow the user to override the
RMODE64 option and disable it. In addition enable code cache
consolidation on z/OS 64-bit by default and disable it on z/OS 64-bit if
RMODE64 is disabled.
> Allow RMODE64 to be disabled via an option

- compiler/p/codegen/OMRCodeGenerator.cpp
Power processors aren't optimized for storing values and then fetching
them back, so the compiler optimizes away redundant loads after
stores. In some cases, lwz was used to clear the high 32 bits of a
variable, but the compiler optimized it away regardless. Replacing it
with rlwinm, which will clear the high 32 bits, solves this.
> Replace redundant lwz with rlwinm

- fvtest/tril/.gitignore
- fvtest/tril/CMakeLists.txt
- fvtest/tril/README.md
- fvtest/tril/ast.c
- fvtest/tril/ast.h
- fvtest/tril/ilgen.cpp
- fvtest/tril/ilgen.hpp
- fvtest/tril/main.cpp
- fvtest/tril/mandelbrot.tril
- fvtest/tril/test.tril
- fvtest/tril/tril.l
- fvtest/tril/tril.y
Tril is a small language/tool for generating Testarossa IL (Intermediate Language). This change adds a prototype for the trilc compiler that reads, compiles, and executes Tril code.
Eventually, Tril should evolve into a tool for testing Testarossa. For now, only a very simple implementation of the compiler as well as some documentation and examples are contributed.
> Add implementation of Tril

- compiler/optimizer/OSRDefAnalysis.cpp
Accidental processing of removed pending push trees
resulted in pending push temps remaining live to method
entry and other OSR points when they should not have.
Moreover, any loads with a reference count greater than 1 
are not loads specific to this OSR point's shortcut and should 
be ignored.
> Fix pending push liveness shortcut

- compiler/optimizer/LoopVersioner.cpp
If all yield points have been removed from a loop,
for example, the removal of asyncchecks, it is possible
to version out any OSR guards that have been left behind.
A single OSR guard will be added, which will patch to the
slow version of the loop.
> Version OSR guards out of loops

- fvtest/tril/examples/incordec/CMakeLists.txt
- fvtest/tril/examples/incordec/incordec.tril
- fvtest/tril/examples/incordec/main.cpp
- fvtest/tril/examples/mandelbrot/CMakeLists.txt
- fvtest/tril/examples/mandelbrot/main.cpp
- fvtest/tril/examples/mandelbrot/mandelbrot.tril
- fvtest/tril/test/CMakeLists.txt
- fvtest/tril/test/IlGenTest.cpp
- fvtest/tril/test/JitTest.hpp
- fvtest/tril/test/MethodHandlerTest.cpp
- fvtest/tril/test/ParserTest.cpp
- fvtest/tril/tril/CMakeLists.txt
- fvtest/tril/tril/ast.c
- fvtest/tril/tril/ast.h
- fvtest/tril/tril/ilgen.cpp
- fvtest/tril/tril/ilgen.hpp
- fvtest/tril/tril/method_handler.cpp
- fvtest/tril/tril/method_handler.hpp
- fvtest/tril/tril/tril.l
- fvtest/tril/tril/tril.y
These commits add various improvements to Tril, including:
* code clean up
* added documentation
* added tests
[ci skip] since Tril has not been added to continuous integration
> More Tril Improvements

- .appveyor.yml
- scripts/Appveyor-ProcessTests.ps1
Upload results from testing to the Appveyor test dashboard.
> Appveyor: Update test dashboard

- compiler/p/codegen/OMRCodeGenerator.cpp
In some cases the compiler was optimizing away lwz, which was being used
to clear the high 32 bits of a variable, resulting in garbage values.
Replacing lwz with rlwinm solves this.
> Replace lwz with rlwinm instead of mr

- compiler/x/codegen/OMRTreeEvaluator.cpp
Remove the J9-specific parts of OMR::X86::TreeEvaluator::directCallEvaluator
as they will be handled downstream.
> Remove project code from x86 directCallEvaluator

- compiler/ilgen/IlValue.cpp
IlValue::storeOver does not handle the incoming parameter "value"
properly, in that it does not ensure that it has been stored to
an auto symbol if it's computed in a different block. This mistake
can result in illegal IL in the form of node references that cross
basic block boundaries.
The fix ensures that value has been written to an auto if necessary,
and also leaves the IlValue in a more consistent state (earlier
version would update _nodeThatComputesValue without also updating
_blockThatComputesValue; really neither of these should be updated).
Fixes: #1305
> Store value to auto in IlValue::storeOver

- port/common/omrstr.c
Unsigned subtraction (bufLen - count) isn't useful when (count > bufLen).
fixes #1316
> Fix overflow detection in omrstr_subst_time

- compiler/codegen/FrontEnd.cpp
- compiler/codegen/FrontEnd.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/runtime/OMRCodeCacheManager.cpp
- compiler/runtime/OMRCodeCacheManager.hpp
- fvtest/compilertest/env/FrontEnd.hpp
- jitbuilder/env/FrontEnd.hpp
* Relocate FrontEnd setHasFailedCodeCacheAllocation
* Cleanup/removal of FE functions now in VMMethodEnv
> more cleanup for VMMethodEnv usage

- compiler/ilgen/BytecodeBuilder.cpp
- jitbuilder/optimizer/JBOptimizer.cpp
Allow BytecodeBuilders to recognize more loops and add the loopCanonicalization optimization to JBOptimizer.
> JitBuilder loop improvements

- compiler/optimizer/LoopVersioner.cpp
If there are no canGCandReturn or canGCandExcept
nodes in a loop, any HCR guards within it
can be versioned out. This is similar to the OSR
guard versioning, however, an individual HCR
guard must be created for each that is removed
due to the runtime assumptions varying between
them.
> Version HCR guards out of loops

- fvtest/tril/examples/incordec/incordec.tril
- fvtest/tril/examples/incordec/main.cpp
- fvtest/tril/examples/mandelbrot/main.cpp
- fvtest/tril/examples/mandelbrot/mandelbrot.tril
- fvtest/tril/test/ASTTest.cpp
- fvtest/tril/test/CMakeLists.txt
- fvtest/tril/test/CompileTest.cpp
- fvtest/tril/test/MethodInfoTest.cpp
- fvtest/tril/test/ParserTest.cpp
- fvtest/tril/tril/ast.c
- fvtest/tril/tril/ast.h
- fvtest/tril/tril/ilgen.cpp
- fvtest/tril/tril/ilgen.hpp
- fvtest/tril/tril/method_info.hpp
- fvtest/tril/tril/tril.l
- fvtest/tril/tril/tril.y
Various improvements to Tril:
* Added lists as possible values for ASTNode arguments
* Improved some printing/debugging code
* Added arguments to some ASTNode types
* Made specifying fall-though edges optional
* Implemented a way of commoning Tril nodes
[ci skip] because Tril is not part of continuous integration
> Another batch of Tril improvements

- doc/compiler/il/SymbolsSymrefsAliasing.md
Add some initial documentation for:
* Symbols
* Symbol references
* Aliasing
[ci skip] documentation change only
Signed-off-by: Leonardo Banderali <leob@linux.vnet.ibm.com>
> Add some compiler documentation

- glue/configure_includes/configure_linux_ztpf_390.mk
- include_core/AtomicSupport.hpp
- include_core/unix/thrdsup.h
- omrmakefiles/rules.mk
- omrmakefiles/rules.ztpf.mk
- port/port_objects.mk
- port/unix/omrsyslog.c
- port/unix/protect_helpers.c
- port/ztpf/omrsysinfo_helpers.h
- run_configure.mk
- thread/linux/omrthreadnuma.c
- thread/linux/priority.c
- thread/unix/rasthrsup.c
- tools/tracegen/Port.cpp
- tools/tracegen/TDFParser.cpp
- tools/tracegen/TraceHeaderWriter.cpp
This commit contains further updates for z/TPF OMR support.
The commit contains both build related updates and single 
source related updates.
> z/TPF Port updates for OMR Part III

- compiler/optimizer/Inliner.cpp
Disable fsd guards for now to investigate the issue exposed in tests.
> Disable fsd guard temporarily

- gc/base/OMRVMThreadInterface.cpp
- gc/base/standard/EnvironmentStandard.cpp
- gc/base/standard/EnvironmentStandard.hpp
/cc: @ktbriggs @charliegracie 
> Add missing scavenger ifdefs

- CONTRIBUTING.md
- scripts/commit-msg
Fix #1356 and encourage people to keep their script up to date.
> Update commit message hook script

- cmake/platform.cmake
- fvtest/omrGtestGlue/CMakeLists.txt
> Revert "Link and compile with -pthread"

- .travis.yml
This will be an important step towards productizing our CMakeLists
> Fail Travis builds if CMake builds fail

- example/glue/CollectorLanguageInterfaceImpl.cpp
- example/glue/CollectorLanguageInterfaceImpl.hpp
- gc/base/CollectorLanguageInterface.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/standard/CompactScheme.cpp
- gc/base/standard/Scavenger.cpp
- glue/CollectorLanguageInterfaceImpl.cpp
- glue/CollectorLanguageInterfaceImpl.hpp
While looking through code I found some unused APIs and code that I am
cleaning up.
> Cleanup dead code

- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilertriltest/JitTest.hpp
- fvtest/compilertriltest/JitTestUtilitiesTest.cpp
- fvtest/compilertriltest/OpCodeTest.hpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TreeVerifierTest.cpp
This change set makes some general improvements to the Tril-based compiler tests.
> Improvements to Tril-based compiler tests

- compiler/optimizer/LoopVersioner.cpp
When the aggressive loop versioner option is set (PR #1369) this
change prevents calls to detectInvariantTrees and
buildNullCheckComparisonsTree based on opt level.
> LoopVersioner tuning changes

- compiler/optimizer/LoopVersioner.cpp
In TR_LoopVersioner::loopIsWorthVersioning we currently only
run the test for unimportantLoopCount for optlevels <= warm. It is
likely to be beneficial in many circumstances to run this test at
all optlevels.
This change is currently guarded by the Xjit option added in
PR #1369 until such time as the behaviour is tested accross a broad
set of applications.
> Run the unimportantLoopCount at all optlevels

- compiler/optimizer/Inliner.cpp
Reenable this since the problems exposed are fixed.
> Enable fsdguard by default

- include_core/omrport.h
Provide the five required arguments.
fixes #1445
> Correct definition of omrnls_lookup_message

- fvtest/porttest/CMakeLists.txt
- port/CMakeLists.txt
Fix typos in cuda related source file names
> CMake: Fix names of cuda sources

- cmake/Assert.cmake
- cmake/caches/Appveyor.cmake
- cmake/caches/Travis.cmake
> Add missing copyright

- README.md
You can check out the render [here](https://github.com/eclipse/omr/tree/c7d1e54f29162a5500f6d2e7802b8a390ee56fe3).
> Add appveyor status badge

- compiler/il/symbol/OMRResolvedMethodSymbol.cpp
IL (intermediate language) generation sometimes assumed that the IL for a method has OSR (on-stack replacement) code and catch blocks whenever `getOSRPoints()` is nonempty for that method. However, it's possible that all OSR points for the method belong to other inlined call sites, since the set of OSR points can differ when IL is generated for a single method repeatedly. For instance, symbol references that are unresolved when first inlining a method may be resolved when later inlining the same method again.
This commit changes IL generation to determine the presence or absence of the OSR code and catch block based on the OSR method info for the current inlined site index, without consulting `getOSRPoints()`.
> Use OSR method info to check for OSR blocks

- compiler/x/codegen/SIMDTreeEvaluator.cpp
The child of a vsplats node can return either a TR_GPR or TR_FPR register
on evaluation. Only the TR_FPR case was being handled correctly.
This change adds a MOVD / MOVQ instuction to transfer the data from the
TR_GPR register into a TR_VRF register which is compatible with the
pshufd instruction used to perform the actual splating.
Issue: #1465
> Fix child handling in SIMDsplatsEvaluator on x86

- compiler/optimizer/CopyPropagation.cpp
- compiler/optimizer/CopyPropagation.hpp
PR #1490 left a debug printf in the change request. This will remove it and
correct indentation.
> Remove debug printf in Copy Propagation

- .travis.yml
- scripts/build-on-travis.sh
* Parameterize the cmake generator
* Disable all osx/cmake builds
* Use cmake to build the project
> Cmake: add Unix Makefile CMake builds

- compiler/optimizer/PartialRedundancy.cpp
When profiling with HCR enabled, the extra blocks
and temps required in this configuration can result
in PRE taking up a significant amount of compile
time and memory. This can often result in the
compilation running out of scratch space during
or soon after PRE, degrading performance.
Disabling this opt in these conditions has been
verified on several benchmarks, with no evident
regression, as the following recompile will still
include the opt.
> Disable PartialRedundancyElimination when profiling

- compiler/compile/OSRData.cpp
The OSR shared slot map can be compressed by representing
a continuous set of entries that share the same mapping
with the first. This was implemented by walking the
map and removing any duplicates that were identified,
however, TR_Array implements remove by copying all remaining
elements forward by one index.
The new implementation builds up a compressed list as it goes
along, rather than removing in place. This will not always be
cheaper, but will reduce overall usage due to the high frequency
of entries that can be removed.
> Reduce OSR shared slot map memory usage

- compiler/z/CMakeLists.txt
Signed-off-by: Alexey Zhikhartsev <alexey.zhikhartsev@ibm.com>
> Add cmake file lists for compiler on Z

- cmake/compiler_support.cmake
- compiler/p/CMakeLists.txt
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertest/p/codegen/Evaluator.cpp
- fvtest/jitbuildertest/CMakeLists.txt
- jitbuilder/CMakeLists.txt
- jitbuilder/release/CMakeLists.txt
As well as miscellaneous refactoring derived from said work.
> Compiler CMake support for POWER platforms

- fvtest/compilertriltest/ILValidatorTest.cpp
Ensure that the IlValidator is capabable of catching invalid commoning
by creating an example of invalid commoning.
> Add CommoningAcrossBlockTest

- compiler/optimizer/CopyPropagation.cpp
- compiler/optimizer/CopyPropagation.hpp
The treetop containing a use node is often required
in CopyProp. The prior approach was to repeatedly
search the CFG for the corresponding treetop, however,
this was costly. Instead, a mapping is generated
early in copy prop and used throughout.
> Stash use node to tree mapping in CopyProp

- compiler/optimizer/VirtualGuardHeadMerger.cpp
VirtualGuardHeadMerger will rearrange privarg stores
and monitor stores between virtual guards. However,
it did not correctly uncommon nodes between these
two types of stores, resulting in loads of
uninitialized values.
> Fix VirtualGuardHeadMerger to uncommon correctly

- compiler/ras/Debug.cpp
Removing code in compiler/ras/Debug.cpp that is not
being used by any downstream projects.
This change was tested by running: `TR_Options='debugBeforeCompile' ./testjit`
This option ensures that the function modified in Debug.cpp (TR_Debug::setupDebugger) works. The function should simply start gdb, and it does. 
> Remove deprecated debugger setup code

- compiler/codegen/NodeEvaluation.cpp
remove PLX related comments that mentions restricted registers.
[ci skip]
Signed-off-by: Yixiao Zhu <zhuyixiao@gmail.com>
> Remove PLX related comments

- compiler/infra/OMRCfg.hpp
- compiler/optimizer/OMRLocalCSE.cpp
- compiler/optimizer/OMRLocalCSE.hpp
- compiler/optimizer/RegisterCandidate.cpp
- compiler/ras/Tree.cpp
> Remove unused cs2/tableof.h includes

- port/port_objects.mk
- port/unix/omrsysinfo.c
- port/ztpf/omrintrospect.c
- port/ztpf/omrosbacktrace_impl.c
- port/ztpf/omrosdump_helpers.h
- port/ztpf/omrsignal_context.c
This Commit contains several updates related to getting a clean
compilations for the z/TPF platform.
> z/TPF Port Clean-Build Updates for eclipse omr Part II

- compiler/z/runtime/VirtualGuardRuntime.cpp
Stores to locationAddr in _patchVirtualGuard should not be reordered by
the compiler as they could be potentially patching asynchronously with
the application executing the patch location. Marking this parameter as
volatile ensures this does not happen.
> Mark locationAddr volatile in _patchVirtualGuard

- compiler/optimizer/VirtualGuardHeadMerger.cpp
This change includes two fixes to virtual guard head merger. The first adjusts its
behaviour to detect cases where it is moving a privarg, whose temp has
been recycled and is live in the outer call site's cold path.
The second adjusts the optimization's behaviour to treat OSR guards as stop the
world and prevents it from moving them if the destination is not a valid OSR
point.
> Fixes to virtual guard head merger

- omrmakefiles/rules.mk
- omrmakefiles/rules.ztpf.mk
- omrsigcompat/omrsig.cpp
- port/port_objects.mk
- port/unix/omrsysinfo.c
- port/ztpf/omrmmap.c
- port/ztpf/omrsignal.c
- util/omrutil/j9memclr.c
Various updates to resolve runtime issues during JVM initilization.
> z/TPF OMR updates for a clean z/TPF JVM Initialization.

- cmake/modules/OmrDetectSystemInformation.cmake
- cmake/modules/platform/os/win.cmake
- Fix whitespace issues
- Modify the toolchain detection logic to no longer assume toolchain based on OS
> Toolconfig changes.

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/VirtualGuard.cpp
- compiler/env/OMRIO.hpp
- compiler/il/Aliases.cpp
- compiler/ilgen/IlInjector.cpp
- compiler/infra/InterferenceGraph.cpp
- compiler/optimizer/FieldPrivatizer.cpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/LoopCanonicalizer.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/RedundantAsyncCheckRemoval.cpp
- compiler/optimizer/RegisterCandidate.cpp
- compiler/optimizer/VPConstraint.cpp
- compiler/optimizer/VirtualGuardCoalescer.cpp
- compiler/ras/ILValidator.cpp
- compiler/ras/Tree.cpp
The compiler component has a lot of compiler warnings.  This PR will resolve some of the simple ones.  There will be a follow on Issue/PR for some of the more complicated ones.
> Fix omr/compiler warnings

- compiler/env/OMRDebugEnv.hpp
- compiler/optimizer/InductionVariable.cpp
- compiler/optimizer/Inliner.cpp
- compiler/x/codegen/OMRLinkage.cpp
- Correct the constness of DebugEnv::extraAssertMessage
- Address -Wparentheses warnings in compiler
Both of these are only resolving the issues in the current CI builds
> More compiler warning fixes

- README.md
[ci skip]
FYI eclipse/openj9#86
> Add license badges for EPLv2 & APLv2 to the README.md

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/VirtualGuard.cpp
- compiler/compile/VirtualGuard.hpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/il/OMRNode.cpp
- compiler/runtime/OMRRuntimeAssumptions.cpp
- compiler/runtime/OMRRuntimeAssumptions.hpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
Back out this change for a depending changeset.
> Revert "Add support for nopable breakpoint guard"

- gc/CMakeLists.txt
- omr/CMakeLists.txt
Small misc cmake fixes. See individual commit messages for details
> Cmake fixes

- compiler/z/codegen/FPTreeEvaluator.cpp
Function floatRemHelper is used to generate code for node drem/frem.
Generated assembly uses divide-to-integer instructions DIxBR to get
remainder of two floating point numbers. In rare case there is a
call-out to helper function to get the result. This commit uses
system linkage to call the fast-path helper function in OOL section.
> Refactor double/float remainder helper

- gc/base/MemoryManager.cpp
Virtual Memory might return memory for heap shorter by a region.
So compensate this for Concurrent Scavenger over-allocation. Such
over-allocation is required to guarantee proper Nursery alignment in
Concurrent Scavenger Page.
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>
> Increase size of over-allocate for CS

- compiler/compile/OSRData.cpp
In voluntary OSR, OSR shared slot information will
be generated for all OSR points initially, but only
a limited set of these eventually have to be
commited to the OSR instruction table. This change
adds a condition to eliminate a majority of these,
cutting footprint and compile time overhead.
> Ignore OSR shared slot info under voluntary OSR

- compiler/optimizer/StructuralAnalysis.cpp
Structure analysis was recently changed to use
TR_BitVectors rather than their CS2 equivalent.
However, the iterators were not updated. Instead,
TR_BitVector relied on a wrapper to match the
CS2 BitVector implementation. This changes
structural analysis to use the iterator directly.
> Use direct TR_BitVector iterator

- cmake/modules/OmrTracegen.cmake
- cmake/modules/OmrUtility.cmake
See individual commit messages for details
> CMake: Add tracemerge functionality

- gc/base/MemorySubSpaceSemiSpace.cpp
Increase Nursery alignment in Subspace logic to 2 regions (from 1
region). Later in PhysicalSubArena code, the 2 region alignment is enforced
anyway. Hence attempts to resize with less than two regions would be
ignored. Since region is rather large in CS, most of attempts,
especially early ones, would be ignored.
Also, adding very rudimental adjustment to sizing heuristics, to
accommodate for the low number of background GC threads used.
> Concurrent Scavenger Nursery resizing

- doc/compiler/extensible_classes/Extensible_Classes.md
- doc/compiler/extensible_classes/Extensible_Classes_in_OMR.md
> Fix spelling mistakes

- cmake/modules/OmrCompilerSupport.cmake
- fvtest/compilertest/CMakeLists.txt
- jitbuilder/CMakeLists.txt
> Convert Compiler Support CMake file to Module

- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/VPHandlers.cpp
isArray test should be testing a flag from RAM class instead of ROM
class to save us one indirect load. The folding optimization needs
modification as well to detect the right tree. This change also remove
current limitation where folding only happens to isArray test generated
by LoopVersioner, it will work for isArray test generated by ilgen and
any optimization.
> isArray test on a class flag from RAM class

- cmake/modules/OmrTracegen.cmake
> Fix broken include guard in OmrTracegen

- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
Add enum and name string for initializeStatusFromClassSymbol.
> Add initializeStatusFromClassSymbol

- README.md
> Add badges for Eclipse OMR CI builds

- port/linux/omrvmem.c
In newer versions of glibc (2.24 onwards) function `readdir_r()` has been deprecated. I have replaced it with function `readdir()` which should thread safe on Linux port (compiling with glibc). 
According to `readdir_r()` documentation: 
> In  the current POSIX.1 specification (POSIX.1-2008), readdir(3) is not required to be thread-safe. However, in modern implementations (including the glibc implementation), concurrent calls to readdir(3) that specify different directory streams are thread-safe. Therefore,  the  use  of readdir_r() is generally unnecessary in multithreaded programs.  
**Tests**
On my system 198 tests ran successfully before and after making these changes.
Issue: #305 
Signed-off-by: Varun Garg <varun.10@live.com>
> Replaced deprecated function readdir_r()

- compiler/optimizer/IsolatedStoreElimination.cpp
- compiler/optimizer/UseDefInfo.cpp
As PALI and related product is not part of the project, remove these
comments.
Signed-off-by: Yixiao Zhu <zhuyixiao@gmail.com>
> Remove PALI comments

- .travis.yml
- scripts/build-on-travis.sh
- Improve travis.yml matrix
- Improve Travis Linux build times
> Travis build improvements

- fvtest/threadextendedtest/processTimeTest.cpp
- fvtest/threadextendedtest/threadCpuTimeTest.cpp
- fvtest/threadextendedtest/threadExtendedTestHelpers.hpp
- fvtest/threadextendedtest/threadExtendedTestMain.cpp
> Shorten threadextendedtest without losing coverage

- compiler/optimizer/UseDefInfo.cpp
- compiler/optimizer/UseDefInfo.hpp
Issue: #1582
Signed-off-by: Arkady Siuris <arss860@gmail.com>
> Fixed a typo in the name of the function

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
* Remove deprecated get/setFirstColdInstruction from OMR::Compilation
* Remove unused getDeFactoHotness from Compilation
> Remove deprecated compiler code

- compiler/optimizer/LoopReplicator.cpp
Add static debug counters for different type of loop replication failures.
Fixed minor logic bug to return proper values in heuristics() functions.
Signed-off-by: Yan Luo <yan_luo@ca.ibm.com>
> Add static debug counters for loop replicator

- compiler/optimizer/OSRDefAnalysis.cpp
If OSR exception edge removal is run sufficiently
late, blocks may have been added between OSR
catch and code blocks. In this situation, the
assumptions made by DeadStoreCleanup may be
invalid, so it should stop.
Moreover, OSR exception edge removal should not
run if infrastructure has already been removed.
> Manage additional blocks in OSR infrastructure

- fvtest/threadtest/CMakeLists.txt
> CMake: Add missing thread tests

- fvtest/tril/examples/incordec/main.cpp
> Replace missed nullptr with NULL

- compiler/optimizer/DeadTreesElimination.cpp
An earlier attempt to prevent `fixUpTree()` taking exponential time was previously reverted (via commenting) due to a functional issue.
The problem with the original fix is the early return when `(node->getVisitCount() <= oldCompVisitCount)`. This condition will tend to hold not only for nodes evaluated in earlier treetops, but also for nodes that haven't been encountered yet by the current pass of dead trees elimination, resulting in a failure to anchor.
Anchoring should often be unnecessary because of advance analysis by `isSafeToReplaceNode()`, but in some cases the child of treetop is exempted from that analysis, most notably when it has reference count 1. In these cases it's necessary to anchor any previously unevaluated children that might occur below. For example, consider the …
> Fix exponential walk in dead trees elimination

- compiler/optimizer/VPHandlers.cpp
This commit contains the following changes
1) Early return in VPHandlers if addKnownObjectConstraints has created
a constraint. This change will save compilation time in each pass
of VP.
2) Create KnownObject constraints for newly folded references so that
the folding can benefit current pass of VP.
> Fixes to ValuePropagation

- compiler/optimizer/VPHandlers.cpp
addKnownObjectConstraint should be addKnownObjectConstraints
> Fix compilation issue

- doc/ddr.md
Signed-off-by: Kabir Islam kaislam1@in.ibm.com
> Change 'Data Dump Reader' to 'Direct Dump Reader'

- gc/base/standard/ConfigurationStandard.cpp
> GC: Don't get the extensions if we don't use them

- compiler/codegen/CodeGenRA.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRLinkage.hpp
- compiler/codegen/StorageInfo.cpp
- compiler/il/OMRNode.cpp
- compiler/il/symbol/OMRResolvedMethodSymbol.cpp
- compiler/optimizer/Inliner.cpp
- compiler/optimizer/OMROptimization.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Remove unused functions.
Closes #1926, closes #1929, closes #1931, closes #1932, closes #1933, closes #1934, closes #1935, closes #1936
> Remove and fold unused code

- compiler/ras/LogTracer.hpp
Issue: #1692
Signed-off-by: Chandrakala <chandra-ms@in.ibm.com>
> Use do/while pattern in trace macros

- CONTRIBUTING.md
Starts trying to address Issue #1953
> Preliminary label documentation

- doc/compiler/tril/TrilLanguageReference.md
- fvtest/tril/examples/incordec/incordec.tril
[ci skip] documentation only change.
> Add a preliminary language reference for Tril

- gc/base/MemorySubSpaceSemiSpace.cpp
After Percolate Global GC due to aborted Concurrent Scavenger, rely on
the last free entry (out of which a new Survivor space will be created)
only if it is at the very end of SemiSpace (no objects after it). 
> lastFreeEntry only at the end

- compiler/optimizer/DeadTreesElimination.cpp
where n is the number of nodes in the subtree, and k is the number of nodes found by getLongestPathOfDAG() in the same extended block.
The previous implementation was O(n^2 logn) because it allowed each node to be queued multiple times, up to the max path length.
> Memoize getLongestPathOfDAG() to run in O(nlogk)

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
> Remove and fold fixedPointOverflowExceptionEnabled

- compiler/x/codegen/OMRCodeGenerator.cpp
GRA does not properly assign xmm real registers to TR_VRF virtual
registers on 32bit x86. This can lead to code that produces an incorrect
result. GRA for vector registers is temporarily being disabled on 32bit
x86 until this issue is resolved.
The removal of GRA may cause a performance problem in autosimd reductions
so reductions have also been disabled. This was done by temporarily
disabling the use of getvelem in autosimd on 32bit x86 which is needed
for reduction.
Issue: #2035
> Disable vector register GRA and reduction on 32bit x86

- compiler/compile/OMRCompilation.hpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/InductionVariable.cpp
> Remove and fold isPinningNeeded

- compiler/codegen/OMRCodeGenPhase.cpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/optimizer/BitVectorAnalysis.cpp
- compiler/optimizer/LoadExtensions.cpp
- compiler/optimizer/OMROptimizer.cpp
- compiler/optimizer/OSRDefAnalysis.cpp
- compiler/optimizer/UseDefInfo.cpp
- compiler/optimizer/ValueNumberInfo.cpp
> Remove unused printMemStats functions

- compiler/codegen/OMRCodeGenerator.hpp
> Remove doInlineAllocate from CodeGenerator

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/VPHandlers.cpp
Signed-off-by: Yan Luo <yan_luo@ca.ibm.com>
> NOP-ing of check involving the static StringCompression field

- compiler/codegen/FrontEnd.cpp
- compiler/codegen/FrontEnd.hpp
- compiler/control/CompileMethod.cpp
- compiler/env/FEBase.hpp
- compiler/env/FEBase_t.hpp
* remove FrontEnd unreservedCodeCache()
* remove FrontEnd implementation of needsMethodTrampolines()
> Remove FrontEnd CodeCache API methods

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/optimizer/OMRLocalCSE.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Eliminate and fold disableCommoningOfVolatiles query that only returns false.
> Eliminate and fold disableCommoningOfVolatiles

- compiler/x/codegen/OMRTreeEvaluator.cpp
Use REP MOVSD to copy 16-bit primitives instead of REP MOVSW.
> Enhance ArrayCopy for 16-bit primitives on X86

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/ras/Debug.cpp
> Use populationCount instead of bitCount32

- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.hpp
- compiler/x/i386/codegen/TreeEvaluatorTable.hpp
Optimized X86 minmaxEvaluator using CMOVcc instructions.
> Optimize X86 minmaxEvaluator

- compiler/ras/LimitFile.cpp
Currently if the JIT is unable to read the inline or limit file
supplied, it simply prints a warning and carries on. This is very
easy to miss with automated testing, and the whole purpose of
these files is for debugging and narrowing down a problem, so
there is no point to continue if the file isn't being picked up,
and worse it can lead one to false conclusions. Additionally,
the inlinefileOption accepts a range but does nothing with it.
This is obviously bad, but it makes no sense to have a range
for an inlinefile because there can easily be dependencies i.e.
one method needs to be inlined for another one to be. Therefore
the range code was removed. Doxygen documentation was also added.
Signed-off-by: Simon Hirst <shirst@ca.ibm.com>
> Fail to initialize on bad limit or inline file

- omrsigcompat/omrsig.cpp
Recover our previous behaviour of omrsig_primary_sigaction():
When SIG_IGN/SIG_DFL has been registered for a signal, user should be able
to query such actions via omrsig_primary_sigaction().
omrsig_primary_sigaction() always calls omrsig_sigaction_internal() with
primary=true, in the case of SIG_IGN/SIG_DFL, the cached
sigData[signum].primaryAction might not be the same as sigaction registered
with the OS. 
Fixes #2076
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
> Call omrsig_signalOS_internal() on SIG_IGN/SIG_DFL

- fvtest/threadtest/abortTest.cpp
This code adds extra asserts and debugging to help track down an
occasional hang on Linux 390.
Issue: #2113
> Add debug code and asserts

- compiler/compile/OMRSymbolReferenceTable.cpp
> Remove OpenJ9-specific code from createParameterSymbol

- example/glue/CompactDelegate.hpp
- example/glue/ConcurrentMarkingDelegate.cpp
- example/glue/ConcurrentMarkingDelegate.hpp
Fix files that have incorrect copyright headers.
> Update copyright headers for EPLv2

- compiler/z/codegen/ConstantDataSnippet.cpp
- compiler/z/codegen/ConstantDataSnippet.hpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRSnippet.cpp
- compiler/z/codegen/OMRSnippet.hpp
* `S390DeclTrampSnippet`
* `S390SortJumpTrampSnippet`
Closes: #2137
> Remove unused trampoline snippets

- fvtest/threadtest/abortTest.cpp
> Fix compiler warning on older compilers

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/S390Instruction.cpp
> Move isStopTheWorldGuard to OMR::Node

- compiler/x/codegen/OMRTreeEvaluator.cpp
Although X86 has a new optimized ArrayCopy implementation,
the deprecated ones are still default. Enabling the new ones.
> Enable optimized ArrayCopy as default on X86

- compiler/arm/codegen/TreeEvaluatorTable.hpp
> Implement ARM non-equality address comparisons

- port/unix/omrsysinfo.c
Change structure member name by which z/TPF picks-up
I-Stream count for System because of new features
added to z/TPF Operating System. 
> z/TPF Update for I-Stream Determination

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/codegen/OMRInstruction.cpp
- compiler/codegen/OMRInstruction.hpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/OMRInstruction.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
Migrate requiresAtomicPatching and other related functions from
CodeGenerator to Instruction class.
Closes: #2071
> Move requiresAtomicPatching and related functions

- compiler/optimizer/VirtualGuardHeadMerger.cpp
- compiler/runtime/CodeCacheTypes.cpp
> Add missing directory stem prefix to some #include directives

- compiler/compile/OSRData.hpp
> Revert "Give DefiningMap a const key"

- doc/GuideForCommitters.md
Describe general committer guidelines and provide a checklist to follow
prior to merging pull requests.
> Provide documentation for committer tasks

- compiler/x/codegen/BinaryEvaluator.cpp
- fvtest/compilertest/tests/X86OpCodesTest.cpp
* disable ludiv constant divisor strength reduction
* re-enable ludiv fvtests
Closes: #2218
> disable ludiv constant division optimization

- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/ras/Debug.cpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Debug.cpp
- compiler/x/runtime/X86Runtime.hpp
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/tril/test/CMakeLists.txt
- fvtest/tril/tril/CMakeLists.txt
The changes fix a lot of the compiler warnings on OS X.
> Resolve compiler warnings on OS X

- compiler/optimizer/DataFlowAnalysis.hpp
- compiler/optimizer/LiveVariableInformation.cpp
OSRUses under prepareForOSR prolong the live range of autos and
pending push temps. Especially, those fake uses can cause many
autos and temps appear to be alive at the method entry and requires
zero initialization in the method prologue which is big overhead.
A way to solve this problem is to find out the real uses
of those autos and pending push temps at each OSRPoint and use them
during liveness analysis. The real uses can be found by figuring
out which symbols are needed to calculate the auto or temps at each
prepareForOSRCall and combining this with the liveness information
for the autos and temps from original bytecode.
This changeset changes liveness analysis to consider real uses at
each OSRPoint.
> Build liveness with real uses on OSR points

- omrsigcompat/omrsig.cpp
Fix intializer which clang 5 doesn't like.
> An additonal tweak for Clang/Win

- port/ztpf/omrosdump_helpers.c
This failure occurs when z/TPF writes out static storage
area for each of the shared objects in the VM.  z/TPF
failed to check a return code and assumed a pointer
would be valid when it wasn't.  Additionally the program
being processed no longer is loaded on z/TPF so that was
removed as well.
> z/TPF system dumps segfaulting while writing system dumps.

- doc/GuideForCommitters.md
* remind committers to examine each commit title/message individually
* squash commits where appropriate
> Update Committer guidelines documentation

- compiler/compile/Method.cpp
- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/il/symbol/OMRParameterSymbol.cpp
- compiler/il/symbol/OMRParameterSymbol.hpp
- compiler/il/symbol/ParameterSymbol.hpp
- fvtest/compilertest/compile/Method.cpp
- jitbuilder/compile/Method.cpp
> Remove isUnsigned parameter from ParameterSymbol

- compiler/x/codegen/X86Debug.cpp
Provide a meaningful register name when its size is unknown.
> Provide a meaningful x86 register debug name

- compiler/runtime/OMRRuntimeAssumptions.hpp
Allows for marking assumptions which will be removed later.
Used in OpenJ9 to speed up removal of assumptions during
class unloading.
> Facility for marking assumptions for later removal

- fvtest/threadtest/abortTest.cpp
This issue has happened a few more times in the CI testing so I
am able to improve the debugging code by enabling more asserts.
Also I removed some code from the test which should never be
executed. I added another assert to make sure the expected code
path would always happen.
> Improve debugging code for Issue #2113

- ddr/lib/ddr-scanner/Scanner.cpp
Removed redundant local variable.
> Changes requested during review of #2271

- CONTRIBUTING.md
Describe the process of handling dependent changes in downstream
projects and the coordination expected from contributor and committer.
Fixes: #2303
> Add downstream dependency section

- include_core/AtomicSupport.hpp
> Fix typo in comment: "asn" -> "as"

- port/unix/omrsignal.c
> Fix comments in OMR Signal code

- include_core/omrutilbase.h
Doxygen documentation has been added for existing API in
"omrutilbase.h".
> Add Doxygen documentation for existing API

- port/unix/omrsignal.c
Focus is on properly initializing variables.
> Improve OMR signal code [Unix variant]

- gc/base/j9mm.tdf
- provide more trace detail information for calculatePGCCompactionRate
> Update tracepoint information for calculatePGCCompactionRate

- ddr/lib/ddr-ir/Macro.cpp
* a type must be one or more C identifiers
* assume casts to unknown types can be safely ignored (e.g. `UDATA`)
> Improve support for cast expressions

- README.md
> [ci skip] Update the README.md to include the AIX build badge

- omrmakefiles/rules.win.mk
OpenJ9 PR: https://github.com/eclipse/openj9/pull/1494
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Enable Windows stack protection (/GS flag)

- port/win32/omrintrospect.c
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Fix GS compile error by removing inline asm

- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/Scavenger.cpp
Fix for Issue https://github.com/eclipse/omr/issues/2404
> Fix CMake build fails on ParallelGlobalGC.cpp / Scavenger.cpp compilation

- compiler/optimizer/ValuePropagationTable.hpp
- compiler/ras/Tree.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
Remove the obsolete pddivSelect opCode.
> Clean up obsolete pddivSelect

- compiler/optimizer/DeadTreesElimination.cpp
Dead trees elimination removes indirect loads under compressedRefs
anchors when they have reference count 1, i.e. when their results are
unused. But when the result of such a load is used anywhere, its anchor
is left in place. So far this determination has been made only when the
pass encounters the anchor, which means that it counts later uses even
if those uses are themselves about to be removed.
Dead trees elimination now revisits compressedRefs anchors for loads at
the end of the pass, in order to determine whether the anchored loads
have become unused, and remove any that have.
> Remove unused compressedRefs anchors in dead trees

- port/unix/omrsignal.c
Reverts eclipse/omr#2432
OpenJ9 hangs during compilation - https://github.com/eclipse/openj9/issues/1711
[skip ci] 
Signed-off-by: Babneet Singh sbabneet@ca.ibm.com
> Revert "Fix signal issues unix"

- compiler/optimizer/VPHandlers.cpp
> Add non-null constraint for indirect load of this$0 field from trusted classes

- compiler/arm/codegen/OMRCodeGenerator.cpp
- compiler/arm/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Un-used Register Assignment Queries Removed
Signed-off-by: vignesh <mvignesh240@gmail.com>
> Register Assignment Direction Queries Removed

- cmake/modules/OmrTracegen.cmake
> CMake: make all depend on run_tracemerge

- ddr/tools/ddrgen/ddrgen.cpp
When wildcards are used, it isn't always obvious which types are effectively blacklisted; this introduces options (`-sb` or `--show-blacklisted`) to request that set be shown.
The parameter list to `getOptions` was already very long; rather than add to it, I refactored option management into a new class.
> Refactor options; add option to print blacklisted type names

- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
This commit implements the initial version of OMRMachine files for
aarch64.
This is a part of #2465.
> AArch64: Initial version of OMRMachine files

- ddr/lib/ddr-scanner/pdb/PdbScanner.cpp
Makes diagnosing problems due to missing or unregistered msdia*.dll libraries easier.
> Add more detailed messages creating IDiaDataSource

- .appveyor.yml
- cmake/modules/OmrDetectSystemInformation.cmake
> AppVeyor build now tests 32bit build

- config.guess
- config.sub
Update config.guess and config.sub to the Latest Versions to Include new Platforms
(e.g. AArch64)
For Issue #2538
> Update config.guess and config.sub to the Latest Versions

- glue/configure_includes/configure_linux_x86.mk
> Remove incorrect trailing slash

- fvtest/porttest/omrstrTest.cpp
- port/common/omrstr.c
- additional test for this case
- cleanup of code / comment error in nearby code
Created for https://github.com/eclipse/openj9/pull/1655 compatibility on zos
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Convert mutf8 to latin1

- .travis.yml
- scripts/build-on-travis.sh
Add in Travis CI Build Cross-Compile for AArch64
Part of: #2446
> AArch64: Setup Travis CI Cross Compile Build

- gc/base/MemoryPoolSplitAddressOrderedListBase.cpp
- gc/base/MemoryPoolSplitAddressOrderedListBase.hpp
- gc/base/PacketList.cpp
- gc/base/PacketList.hpp
- gc/base/ParallelSweepChunk.hpp
- port/unix/omrintrospect.c
Most of the the changes are related to improper initialization of non-trivial classes with `memset(buf, 0, ..)`.
Can you review @rwy0717?
> Code fixes discovered from using new gcc

- README.md
> Improve presentation of CI status in README file

- example/glue/VerboseManagerImpl.cpp
- gc/base/standard/CopyScanCacheList.cpp
- gc/base/standard/CopyScanCacheList.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
- glue/VerboseManagerImpl.cpp
- port/unix/j9nlshelpers.c
- thread/common/omrthreadmem.cpp
- tools/hookgen/HookGen.cpp
- tools/tracegen/TDFParser.cpp
Mostly fixing usages of `strncpy`, and some improper initialization of class instances.
> Fix more warnings and errors

- gc/CMakeLists.txt
- gc/base/MarkingScheme.cpp
- gc/base/MarkingScheme.hpp
- missing scavenger ifdef
- missing link libraries for GC
/cc @charliegracie
> Two small compile fixes for the GC

- compiler/il/OMRNode.cpp
> Remove unused buffer in the createConstOne API

- doc/compiler/il/SymbolsSymrefsAliasing.md
1. Add high-level overview on aliasing infrastructure;
2. Provide detailed information on five kinds of bit vectors
we maintain in the context of Java.
[skip ci]
Signed-off-by: Xiaoli Liang <xliang6@gmail.com>
> Add aliasing documentation

- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
- compiler/aarch64/codegen/OMRRegisterDependencyStruct.hpp
- compiler/aarch64/codegen/RegisterDependency.hpp
This commit implements the RegisterDependency files for aarch64.
> AArch64: Implement RegisterDependency files

- gc/base/standard/Scavenger.cpp
In MM_Scavenger::clearCache() handling of Scan Cache reminder can be
skipped if it's size is zero. It should prevent calling
abandonHeapChunk() unnecessary.
> Skip handling of Scan Cache reminder size zero

- doc/compiler/debug/DebugCounters.md
Add documentation for JIT debug counters. 
> Add documentation for Debug Counters

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
Signed-off-by: Noah Weninger <noah.weninger@ibm.com>
> Add JITaaS vlog option

- compiler/control/OMROptions.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/OMRRegisterDependency.cpp
- compiler/z/codegen/OMRSnippet.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/S390Debug.cpp
* Fold code assuming `needsVMThreadDependency` is false
* Remove and fold code around TR_Enable390FreeVMThreadReg
> Dismantle some Z VMThread reclamation logic

- port/unix/omrsysinfo.c
Changes `OMRPORT_CPU_BOUND` to check if the CPU subsystem is enabled,
indicating that cgroup limits be used. If so, then `OMRPORT_CPU_BOUND`
return value is capped at an "equivalent" number of processors equal
to `(cpu.cfs_quota_us / cpu.cfs_period_us)` rounded to the nearest
natural number (this "equivalent number of processors" calculation
may be subject to change in the future).
This change only affects Linux and addresses problems discussed in
eclipse/openj9#1166.
This change depends on #2605.
Issue: eclipse/openj9#1166
Signed-off-by: Mohammad Ali Nikseresht <anikser@ibm.com>
> Add cgroup limit checking in omrsysinfo_get_number_CPUs_by_type

- compiler/optimizer/LoopVersioner.cpp
In OpenJ9, versioner could miss necessary type tests, either when
compiling ahead of time, or when determining how to protect a load of
classFromJavaLangClass. These tests are now generated as required.
> Stop versioner from leaving out needed type tests

- compiler/optimizer/ValuePropagationCommon.cpp
Replace PassThrough node with its child in its non-NullCheck parents
> Replace PassThrough with its child in VP

- compiler/x/codegen/FPTreeEvaluator.cpp
Simplify the evaluator by removing experimental paths.
> Remove experimental x86 float conversion code

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/optimizer/RegisterCandidate.cpp
- compiler/x/i386/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- doc/compiler/ProblemDetermination.md
* Remove notion of VMThreadGlobalRegisterNumber
* Remove VMThreadGRA support
* Remove and fold unused VMThread reclamation functions
> Remove more deprecated VMThread reclamation logic

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/Relocation.cpp
- compiler/codegen/Relocation.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/il/OMRSymbolReference.hpp
- compiler/il/symbol/OMRSymbol.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/ras/DebugCounter.cpp
- compiler/ras/DebugCounter.hpp
- compiler/runtime/Runtime.hpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/z/codegen/ConstantDataSnippet.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
Relocatable Debug Counter Support
> Relocatable Debug Counters

- compiler/ilgen/OMRIlType.cpp
> Remove unneeded FrontEnd.hpp include

- compiler/aarch64/codegen/Instruction.hpp
- compiler/aarch64/codegen/OMRInstruction.cpp
- compiler/aarch64/codegen/OMRInstruction.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
This commit implements the initial version of OMRInstruction files
for aarch64.
> AArch64: Initial version of OMRInstruction files

- compiler/optimizer/LocalOpts.cpp
We should ask `classIsFixed()` on the argument to check if it has fixed class constraint.
> Use the right way to check if an argument has fixed type

- README.md
Add a section describing ways contributors can interact with the
Eclipse OMR community.
[skip ci]
> Update README to include community links

- ddr/tools/blob_reader/blob_reader.cpp
> Fix DDR blob_reader so it respects byte ordering

- compiler/optimizer/VPHandlers.cpp
For values not constrained to be constant, if the low bound was the
minimum value of the type (hereafter referred to as MIN), VP (value
propagation) would negate it, which is undefined behaviour. In the best
case, the program would continue using -MIN == MIN, which is correct for
two's complement, but which causes VP to produce a bad constraint.
For a positive high bound, the resulting constraint would exclude all
negative values, even though MIN is possible.
For a non-positive high bound, the resulting constraint's low and high
bounds would be out of order (i.e. high == MIN < low). This constraint
is not only incorrect but malformed, and it is liable to cause VP to
misbehave.
The handlers now deal separately with the possibility that the child is
the minimum value, effectively treating …
> Fix VP handlers for [il]abs when low bound is MIN

- compiler/codegen/CodeGenRA.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/control/OMROptions.hpp
- compiler/infra/CfgEdge.hpp
- compiler/optimizer/RegisterCandidate.cpp
- compiler/optimizer/RegisterCandidate.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/x/codegen/OutlinedInstructions.cpp
- compiler/x/codegen/OutlinedInstructions.hpp
* Misc. VMThread reclamation cleanup
* Remove VMThread reclamation parameter from generateLabelInstruction
> More VMThread reclamation cleanup

- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertest/build/files/common.mk
- fvtest/compilertest/tests/SingleBitContainerTest.cpp
This is a re-submission of PR #2127 with final corrections.  Please see that PR for review history.
> Create unit tests for TR_SingleBitContainer

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/il/symbol/OMRSymbol.cpp
- compiler/il/symbol/OMRSymbol.hpp
- compiler/optimizer/CFGSimplifier.cpp
- compiler/optimizer/CFGSimplifier.hpp
- compiler/optimizer/LocalOpts.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/OMRMachine.hpp
- compiler/z/codegen/SystemLinkage.cpp
> Remove deprecated restricted register support from Z

- .gitignore
> Add z/OS build artifacts to the .gitignore

- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
This commit implements the initial version of ARM64Instruction and
related files for aarch64.  This depends on #2660.
> AArch64: Initial version of ARM64Instruction and related files

- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
Patch site is missed on a runtime guard merged with OSR guard, resulting
a missing of class redefinition assumption in nextGenHCR.
> Create patch site for merged OSR guard for X and Z

- omrmakefiles/rules.linux.mk
- omrmakefiles/rules.mk
Fix typo in debug flag for `as`.
Fix ZTPF contribution to `make clean`.
> Fix makefiles

- compiler/infra/Checklist.hpp
Add isEmpty() API to Checklist to check if the list contains
any elements at all.
> Add isEmpty() API to Checklist

- compiler/z/codegen/OMRTreeEvaluator.cpp
The store operations can be optimized to use just a MVC instruction
instead of a load-store operation to save one instruction. For store
instructions, an UnresolvedDataSnippets is needed so that it can
resolve the symbols at program run-time and patch that store
instruction.
Run-time store instruction patching does not work with MVC. Hence, avoid
generating MVC instructions if the source or target memory locations
are from unresolved symbols.
> Avoid generating MVC for unresolved symbols

- thread/common/threadhelpers.cpp
1) **Revert "Improve locking"**
This commit reverts the commit in #1979.
The purpose of the original change was to reduce compare and swap
operations in the spinlock loop; thus, reducing spinning overhead. The
premise was to improve throughput by reducing spinning overhead. In the
initial benchmarking, no throughput improvements were noticed because of
this change. Recently, this change has resulted in regressing
throughput. ~30% throughput drop is observed in one of the OpenLiberty
benchmarks. Thus, it has been decided to revert the original change.
> Locking Changes

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/OMRMachine.hpp
Remove some additional dead code missed in #2803.
> Deprecate Access Register (AR) support in Z codegen

- compiler/z/codegen/FPTreeEvaluator.cpp
The fbits2i evaluator in the z codegen is suboptimal and hence causes a performance regression as compared to the x codegen. This commit captures the missing corner cases to close that gap, and includes some extra cleanup to simplify the evaluator.
> Optimize the fbits2i Evaluator

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/ras/Debug.hpp
This commit implements the initial version of ARM64Debug.cpp, and
adds declarations in Debug.hpp.
> AArch64: Initial version of ARM64Debug.cpp

- compiler/z/codegen/ConstantDataSnippet.cpp
The debug utility class is now able to print S390InterfaceCallDataSnippet
in the right format.
> Print S390InterfaceCallDataSnippet correctly in trace

- jitbuilder/release/.gitignore
@mstoodle , @Leonardo2718  FYI
> Add inliningrecfib build artifact to jitbuilder/release gitignore

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
This commit implements createPrologue() and createEpilog() for
ARM64SystemLinkage.
> AArch64: Initial version of createPrologue/Epilogue() for SystemLinkage

- compiler/z/codegen/FPTreeEvaluator.cpp
fbits2iEvaluator is used for type-coercion (float to int bits). The evaluator normalizes NaN and infinity values if needed. Since the evaluator assumes that floating point data conforms to the IEEE-754 standard, some simplification can be done here. Mainly, the simplification is that infinity values don't need to be normalized as there is only one possible representation for them anyway.
> Simplify NaN normalization fbits2i

- gc/CMakeLists.txt
> Fix missing file in gc/CMakeLists.txt

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/control/OMROptions.cpp
- compiler/env/TRMemory.cpp
- compiler/env/TRMemory.hpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LocalOpts.hpp
- compiler/optimizer/OMROptimizationManager.cpp
- compiler/optimizer/OMROptimizer.cpp
- compiler/optimizer/Optimizations.enum
- compiler/z/codegen/FPTreeEvaluator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRInstruction.cpp
- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRRegisterDependency.cpp
Enable 64 bit registers on 32 bit for Linux on Z.
> Enable 64 bit registers on 32 bit for Linux on Z

- compiler/optimizer/OMRTransformUtil.cpp
- compiler/optimizer/OMRTransformUtil.hpp
The transformation is:
elseBlock               ifBlock
|                   /     \
...      ===>       /       \
|               elseBlock  thenBlock
mergeBlock             |        /
...      /
\     /
\   /
mergeBlock
> Add a transform util to create alternate path for existing operations

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
> Add an option to disable guarded static final field folding

- gc/base/segregated/MemorySubSpaceSegregated.cpp
- gc/base/segregated/MemorySubSpaceSegregated.hpp
Missed updating these copyrights in #2966
[skip ci]
> Fix copyright dates

- port/unix/omrsysinfo.c
It is possible in certain configurations that cgroup swap limit
capabilities is not enabled. In such cases files in cgroup memory
subsystem related to swap information such as
'memory.memsw.limit_in_bytes' and 'memory.memsw.usage_in_bytes'
won't be present.
Updated retrieveLinuxCgroupMemoryStats() to handle such case.
> Swap limit and usage must be 0 in absence of swap limit capabilities

- compiler/aarch64/codegen/MemoryReference.hpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
This commit implements freeBestRegister() and some other functions
in OMRMachine for aarch64.
> AArch64: Implement OMRMachine functions

- .travis.yml
- scripts/build-on-travis.sh
No more CMake builds on Travis
Here is a link to the OMR CI PR build:
https://ci.eclipse.org/omr/job/PullRequest-linux_x86/
> Remove Linux x86 (32bit) testing

- compiler/p/codegen/OMRCodeGenerator.cpp
Signed-off-by: Boris Shingarov <shingarov@labware.com>
> Remove pointless obtaining of GR1

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
This commit implements BBStart/BBEnd evaluators for aarch64.
> AArch64: Implement BBStart/BBEnd evaluators

- compiler/aarch64/codegen/OMRMachine.cpp
This code adds a guard code to Machine::assignOneRegister() for aarch64.
Do nothing and just return when a real register is already assigned to
a virtual register.
> AArch64: Add guard to Machine::assignOneRegister()

- compiler/x/codegen/OMRCodeGenerator.cpp
Guard following feature flags with "canGenerateArraylets":
1. SupportsArrayCmp
2. SupportsPrimitiveArrayCopy
3. SupportsArraySet
4. SupportsArrayTranslateTRTO
5. SupportsArrayTranslateTROT
6. SupportsArrayTranslateTROTNoBreak
Remove SupportsReferenceArrayCopy as OMR doesn't actually
fully support reference arraycopy.
> Properly set array related feature flags on X86

- compiler/z/codegen/OMRTreeEvaluator.cpp
An unresolved class is resolved at runtime by a PicBuilder routine and the
result (resolved class) is stored in a patchable literal pool
slot referenced by the last slot of an 'unresolved data snippet'.
On Z hardware lower than z10, the JIT compiled code does not use the
correct slot of the snippet and, as a result of this, crashes when loading
the resolved class from the data snippet. This bug is fixed by this
commit.
> Fix result loading from unresolved class data snippet

- port/zos390/omrsl.c
Provide workaround when dllload fails to open lib
Linux and MacOS use the directory of the portLibrary as a
fall back for when a library is not able to be loaded in the 
specified path. z/OS does not support the necessary functions 
(ie. dladdr) to do the same. As a result, a second attempt to 
load a dll will be done with just the name of the library which 
will trigger a search on the filesystem.
Signed-off-by: Tobi Ajila <tobi_ajila@ca.ibm.com>
> Provide workaround when dllload fails to open lib

- compiler/x/amd64/codegen/OMRMemoryReference.cpp
It is safe to assume that the offset field of a memory reference to
a data snippet always fits in 32-bit signed integer range. Hence the
extra register for materialization is not necessary.
> Avoid unnecessary MemRef materialization on X86-64

- port/ztpf/omrosbacktrace_impl.c
z/TPF Symbol Names and Modules names from dladdr are
returned as EBCDIC characters sets.  These values need
to be translated before being stored in the backtrace
frame control structure otherwise they are printed out
as garbage characters.  Furthermore the top of stack for
z/TPF is a dummy invalid frame, and needs to be pruned
from the backtrace otherwise unexpected behaviour occurs.
> z/TPF Backtrace Translation and Processing Fixes

- gc/base/LightweightNonReentrantLock.cpp
- gc/base/TLHAllocationSupport.cpp
- gc/base/segregated/HeapRegionDescriptorSegregated.cpp
- gc/stats/MarkStats.cpp
- gc/stats/ScavengerStats.cpp
- gc/verbose/VerboseHandlerOutput.cpp
> Remove some extra semicolons

- port/unix/omrintrospect.c
> Remove bad check if unsigned int is less than 0

- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/LoopVersioner.hpp
Change the variable and function names from iwrtbar to awrtbari
> Change LoopVersioner var/function names for awrtbari

- port/unix/omrtty.c
All publicly available documentation indicates that FIONREAD outputs an
int, not a pointer-width value. Use an int, and avoid bad aliasing.
There is a comment indicating that _some_ devices output a 64 bit value,
but I cannot see how or when that would ever be true. This PR removes
that comment.
Fixes: #3145
> Use an int to store the output of ioctl FIONREAD

- include_core/AtomicSupport.hpp
Introduce a new type, DoubleConversionData, for converting between a
double and it's bits (uint64_t). Use this type to CAS the bits of a
double. Eliminates a bad cast from double* to uint64_t*.
Fixes: #3123
> Use a union to eliminate an aliasing error

- thread/CMakeLists.txt
- thread/common/omrthread.c
- thread/linux/omrthreadnuma.c
- thread/linux/priority.c
> Add warning flags to thread objects

- fvtest/compilertriltest/ArithmeticTest.cpp
Tril Tests for ladd / lsub
For #3105.
> Tril Tests for ladd / lsub

- compiler/z/codegen/FPTreeEvaluator.cpp
The fbits2i and dbits2l nodes do similar operations. This commit simplifies and consolidates these two evaluators into a single helper.
> Consolidate FPtoInt Type-Coercion Evaluators

- gc/api/CMakeLists.txt
> Extend GC build flags when API is enabled

- cmake/caches/GcApi.cmake
> Add a cmake cache enabling OMR_GC_API

- gc/base/standard/Scavenger.cpp
Update comment to reflect the changes made to
MM_Scavenger::aliasToCopyCache
> MM_Scavenger::aliasToCopyCache Update Comment

- compiler/optimizer/VPHandlers.cpp
It was already so constrained in cases where the class represented by
the ClassObject is known exactly, but the represented class is
irrelevant here. Now (isClassObject() == TR_yes) takes precedence over
isFixedClass() so a location of {JavaLangClassObject} is sufficient to
cause VP to create the constraint.
> Constrain VFT of ClassObject to be java/lang/Class

- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit implements iabs/labsEvaluator() for aarch64.
> AArch64: Implement iabs/labsEvaluator()

- ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
- port/unix/omrsignal.c
* add missing parentheses
* space around binary operators and after keywords
* r-value on left of !=
> Fix coding style

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
* Remove unused CodeGenerator flags
* Fix formatting of available CodeGenerator flags
> Misc. CodeGenerator flags cleanup

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/OMRValuePropagation.hpp
- compiler/optimizer/VPHandlers.cpp
Add transformDirectLoad where downstream project can add language
specific optimizations of direct load.
> Add an extension point for optimizations of direct load in VP

- CONTRIBUTING.md
File renames or moves do not require a copyright header change.
> Clarify copyright updates in CONTRIBUTING.md

- fvtest/compilertriltest/CompareTest.cpp
This commit adds tril test cases for lcmp, lcmpeq and similar evaluators.
> Tril tests for lcmp, lcmpeq, etc.

- port/unix/omrsysinfo.c
Also define platform-specific constants to reduce the complexity of the ifdefs
and reduce duplicated code.
> Fix get_OS_version for MacOS

- omrmakefiles/rules.mk
Omit useless lines with only '@'.
> Reduce size of *.i files

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
This commit implements ificmpeqEvaluator(), similar evaluators(), and
related functions.
> AArch64: Implement ificmpeqEvaluator(), etc.

- gc/.clang-format
> Increase line length in gc clang-format

- fvtest/compilertriltest/LogicalTest.cpp
> Tril Tests for iand and ixor

- fvtest/compilertriltest/TypeConversionTest.cpp
This commit implements Tril test cases for i2f, etc.
> Tril tests for i2f, etc.

- compiler/arm/codegen/ARMBinaryEncoding.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/env/FEBase_t.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/z/codegen/S390Instruction.cpp
* Move NumReservedIPICTrampolines getter/setters to X86 CodeGenerator
* Move codeCacheSwitched getter/setter to CodeGenerator
* Implement switchCodeCacheTo() in CodeGenerator
> Migrate CodeCache switching logic to CodeGenerator

- fvtest/compilertriltest/CompareTest.cpp
This commit adds Tril test cases for fcmpeq, dcmpgt, etc.
> Tril tests for fcmpeq, etc.

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
> Remove deprecated TR_EnableLateCleanFolding Option

- fvtest/compilertriltest/CompareTest.cpp
This commit adds Tril test cases for floating-point conditional
branches, such as iffcmpeq and ifdcmpgt.
> Tril tests for iffcmpeq, etc.

- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/xlc.cmake
- omrmakefiles/rules.aix.mk
- omrmakefiles/rules.linux.mk
- omrmakefiles/rules.osx.mk
- omrmakefiles/rules.zos.mk
> Set the C++ standard to C++0x everywhere

- gc/base/GCExtensionsBase.hpp
heapSizeStatup -> heapSizeStartup
> Fix spelling

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
This commit implements conditional branches of 32-bit unsigned
integer, and 64-bit signed/unsigned integer.
> AArch64: Implement ifiucmpeq, iflcmpeq, iflucmpeq, etc.

- fvtest/compilertriltest/LogicalTest.cpp
Add UsingLoadParam LogicalTest Tril Tests
- Increase Test Coverage by Adding UsingLoadParam, Unary and Binary,
LogicalTest Tril Tests
- Update Copyright Dates as Necessary
Doubles LogicalTest Coverage from `705` Tests to `1410` Tests:
Before this PR: `./comptest --gtest_filter=*LogicalTest*Int*Logical*`:
```
Note: Google Test filter = *LogicalTest*Int*Logical*
[==========] Running 705 tests from 2 test cases.
[----------] 30 tests from LogicalTest/Int32LogicalUnary
[----------] 30 tests from LogicalTest/Int32LogicalUnary (890 ms total)
[----------] 675 tests from LogicalTest/Int32LogicalBinary
[----------] 675 tests from LogicalTest/Int32LogicalBinary (10445 ms total)
[==========] 705 tests from 2 test cases ran. (11362 ms total)
[  PASSED  ] 705 tests.
[  ALL TESTS PASSED  ]
```
With …
> Add UsingLoadParam, Unary and Binary, LogicalTest Tril Tests

- fvtest/compilertriltest/LogicalTest.cpp
Implemented land, lor and lxor tril tests for AArch64
> Implemented land/lor/lxor tril tests

- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
Implemented lneg Evaluator under Unary Evaluator
> AArch64: Implement lneg Evaluator

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/aarch64/codegen/TreeEvaluatorTable.hpp
This commit implements directCallEvaluator() for aarch64.
It also changes the layout of stack frame.
> AArch64: Implement directCallEvaluator()

- cmake/modules/platform/os/win.cmake
- omrmakefiles/rules.win.mk
> Update target windows  version to win 7

- compiler/arm/codegen/OMRRegister.hpp
Removed some of the unused code from Register class for arm
Fixes #2452
Signed-off-by: Somesh Sharma <someshsharma0312@gmail.com>
> Removed some unused functions in the code

- compiler/optimizer/Inliner.cpp
Inliner unconditionally merges the last block of callee and the caller's
block immediately after and copies the caller block's non-OSR exception
successors to callee blocks. Then it splits the merged block when
needed. Split is not needed when no guard and no OSR blocks are
generated for the callee. However, the OSR exception successor from the
caller, must be copied onto the merged block, otherwise the OSR points
from the caller block will be missing OSR exception edges.
This commit does the following:
1. Copy the missing OSR exception edge
2. Ask OSR method data whether OSR blocks have been generated for the
callee instead of checking the trees and crossed basic blocks
3. Improve the code readability by changing variables names and adding
comments
- Rename `blockOfCaller` to …
> Copy OSR exception edge from caller when block is not split

- fvtest/compilertriltest/LogicalTest.cpp
Implemented triltest for lneg evaluator
> lneg evaluator triltest

- gc/base/standard/Scavenger.cpp
Currently in MM_Scavenger::rescanThreadSlot() there is two stage process
to set Remembered State to object header and add object to Remembered
Set:
1) call rememberObject() would try to change Remembered State from 0
(not remembered) to STATE_REMEMBERED atomically and add object to the
Remembered Set if succeeds.
2) upgrade STATE_REMEMBERED to
OMR_TENURED_STACK_OBJECT_CURRENTLY_REFERENCED non-atomically
I believe an upgrade to OMR_TENURED_STACK_OBJECT_CURRENTLY_REFERENCED
might be lost on Weak Ordering platforms and might be a reason for
premature removal of the object from RS.
So proposed fix sets OMR_TENURED_STACK_OBJECT_CURRENTLY_REFERENCED to
the object header atomically. If replaced (old) Remembered State was not
0 (object has been added to RS already) no further action necessary.
If …
> Set CURRENTLY REFERENCED object state atomically

- compiler/codegen/FrontEnd.cpp
- compiler/codegen/FrontEnd.hpp
> Remove deprecated FrontEnd function releaseCodeMemory

- cmake/config.cmake
- configure
- configure.ac
- example/glue/CMakeLists.txt
- example/glue/CollectorLanguageInterfaceImpl.hpp
- example/glue/ScavengerDelegate.cpp
- example/glue/ScavengerDelegate.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- glue/CollectorLanguageInterfaceImpl.hpp
- glue/ScavengerDelegate.cpp
- glue/ScavengerDelegate.hpp
- include_core/omrcfg.h.in
- omrcfg.CMakeTemplate.h
- omrmakefiles/configure.mk.in
This is a first pass. The example and the empty glue version of the
delegate are implemented. The code changes are under the
OMR_GC_SCAVENGER_DELEGATE ifdef, and disabled by default.
> Move scavenger-related CLI functionality to new ScavengerDelegate

- gc/base/standard/Scavenger.hpp
> Add getDelegate to Scavenger

- omr/CMakeLists.txt
- port/CMakeLists.txt
- thread/CMakeLists.txt
- util/avl/CMakeLists.txt
- util/hashtable/CMakeLists.txt
- util/omrutil/CMakeLists.txt
- util/pool/CMakeLists.txt
Specify full path to the files so that they are handled properly by ddr
> Update paths to tracegen'd files

- compiler/arm/codegen/ARMBinaryEncoding.cpp
- compiler/arm/codegen/ARMDebug.cpp
- compiler/codegen/FrontEnd.cpp
- compiler/codegen/FrontEnd.hpp
- compiler/env/FEBase.hpp
- compiler/env/FEBase_t.hpp
- compiler/p/codegen/OMRInstruction.cpp
- compiler/p/codegen/PPCDebug.cpp
- compiler/p/codegen/PPCHelperCallSnippet.cpp
- compiler/runtime/OMRCodeCacheManager.cpp
- compiler/runtime/OMRCodeCacheManager.hpp
- compiler/x/codegen/HelperCallSnippet.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86FPConversionSnippet.cpp
- compiler/z/codegen/OMRSnippet.cpp
- compiler/z/codegen/S390HelperCallSnippet.cpp
- compiler/z/codegen/S390Instruction.cpp
* Replace calls to indexedTrampolineLookup with findHelperTrampoline
* Change return type of findHelperTrampoline to intptrj_t
* Remove deprecated FrontEnd indexedTrampolineLookup function
> Replace calls to deprecated indexedTrampolineLookup

- gc/base/standard/Scavenger.cpp
Scavenger.cpp has some small errors related to ifdefs around concurrent
GC work.  The errors fixed by this PR:
- unused local variable `isParentInNewSpace` (twice)
- undefined member:  `_extensions->concurrentMark`
> Fix some minor ifdef mistakes in the scavenger

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This is a follow-up of #3479 for aarch64.
Two functions in ARM64BinaryEncoding.cpp to use
cg->directCallRequiresTrampoline() for checking the range of branch
instructions.
> AArch64: Use cg->directCallRequiresTrampoline() for checking branch range

- doc/GuideForCommitters.md
Document all the genie build targets.
[skip ci]
> Update genie-omr build targets in committer guide

- compiler/aarch64/codegen/ARM64HelperCallSnippet.cpp
- compiler/aarch64/codegen/ARM64HelperCallSnippet.hpp
This commit adds ARM64HelperCallSnippet files for aarch64.
> AArch64: Add ARM64HelperCallSnippet files

- example/glue/ScavengerDelegate.cpp
This PR fixes a typo where the _omrVM member was missing from the
delegate. This error made it through because the delegate hasn't been
enabled alongside compressed references & compressed object header.
The omrVM used to be cached in the CLI. In the ScavengerDelegate, only
keep the extensions, and just get the VM out of the extensions when
needed.
> Fix missing omrVM in example ScavengerDelegate

- compiler/x/codegen/OMRCodeGenerator.cpp
> Add missing default case to switch statement in X CodeGenerator

- compiler/aarch64/codegen/BinaryEvaluator.cpp
WIP Implementing blanket binary evaluator helper for AArch64
Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>
> Implemented binary evaluator helper for AArch64

- compiler/optimizer/OMRSimplifierHelpers.cpp
> [skip ci] Fix spelling and spacing

- compiler/z/codegen/OMRCodeGenerator.cpp
Ensure the Z CodeGenerator query `directCallRequiresTrampoline` provides the
correct answer on zOS by teaching it about RMODE64.
> Refine Z trampoline check for zOS

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
> Relocate unused slot poisoning function to OpenJ9

- compiler/runtime/OMRCodeCache.cpp
Some straightforward reorganization of CodeCache::replaceTrampoline can be
done to simplify the logic and make it smaller.
> Simplify logic in replaceTrampoline

- port/win32/omrsysinfo.c
Fixes https://github.com/eclipse/omr/issues/3644
> Get Windows version information from registry if major version is 10

- compiler/z/codegen/OMRCodeGenerator.cpp
* remove deprecated VMThread reclamation comments and code
* refactor to eliminate obvious redundant code and sink auto definitions
to the scope they are used in
* fix indentation
> Simplify and cleanup logic in beginInstructionSelection on Z

- compiler/optimizer/LoopVersioner.cpp
Currently when collecting checkcast nodes for loop invariant detection, loop versioner asserts the cast class should always be a loadaddr. With the upcoming CFG simplifier change, the cast class child can be dynamic. So this restriction is removed to allow versioner to detect loop invariant for dynamic checkcast nodes as well. The existing infrastructure appears to be already in-place to handle the new cases.
> Loop versioner support for dynamic checkcast

- jitbuilder/apigen/cppgen.py
- jitbuilder/apigen/genutils.py
Add basic formatting (indentation) to the output from apigen
> Format output of jitbuilder apigen

- compiler/z/codegen/OMRTreeEvaluator.cpp
The arraytranslateEncodeSIMDEvaluator helper function invoked by the arraytranslateEvaluator does not correctly add the number of residue characters succesfully translated if a saturated value is encountered in the second input vector. This commit adds an add instruction to correctly account for all the values successfuly translated.
> Make arraytranslate return correct # of translated chars

- port/unix/omrosdump.c
It should be:
>  int proc_setattr(pid_t, procattr_t*, size_t);
> Fix the signature of 'proc_setattr'

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/optimizer/VPHandlers.cpp
> Fix spelling of createKnownStaticReferenceSymbolRef

- compiler/optimizer/VPHandlers.cpp
Reverts eclipse/omr#3736
Given this was almost an entirely Java specific change for OpenJ9 I'll go ahead and revert it here. With this change in tact I'm seeing exceptions being thrown on Linux on Z and on z/OS under `-Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs` options.
```
j> 13:22:48 Throwable trace:
j> 13:22:48 java.lang.ArrayIndexOutOfBoundsException
j> 13:22:48 	at java.util.AbstractCollection.toArray(AbstractCollection.java:207)
j> 13:22:48 	at sun.reflect.annotation.AnnotationParser.toArray(AnnotationParser.java:877)
j> 13:22:48 	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:599)
j> 13:22:48 	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:651)
j> 13:22:48 	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java …
```
> Revert "Improved Value Propagation for Constant Arrays"

- compiler/runtime/OMRRuntimeAssumptions.hpp
The current RuntimeAssumptionTable design relies on eager clean-up
and the clean-up code is dispresed in the codebase. This change does
two things: 1) it changes the runtime assumption table to use a
self-contained clean-up mechanism defaulting to lazy cleanup and 2)
isolate the API to traverse the RAT to simplify caller implementaiton
and ensure the clean-up is done in a consistent manner.
To faciliate the lazy clean-up of the RAT the special bit in the
next assumption for the JITed body is modified to be always useable.
APIs are added to traverse assumptions both ignoring and respecting
assumptions marked for removal.
> Convert RuntimeAssumptionTable to mark with lazy sweep

- compiler/il/OMRILOps.hpp
Fix a missing return statement
> Missing return

- .gitignore
> Add Visual Studio Code meta data to .gitignore

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/OMRCodeGeneratorUtils.hpp
- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/arm/codegen/FPTreeEvaluator.cpp
- compiler/arm/codegen/OMRCodeGeneratorUtils.hpp
- compiler/arm/codegen/OMRLinkage.cpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/codegen/CodeGeneratorUtils.hpp
- compiler/codegen/OMRCodeGeneratorUtils.hpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGeneratorUtils.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/p/codegen/TreeEvaluatorVMX.cpp
* Introduce a CodeGenerator utilities file for standalone functions
* Migrate Power addDependency to CodeGeneratorUtils
* Migrate ARM addDependency to CodeGeneratorUtils
* Migrate AArch64 addDependency to CodeGeneratorUtils
> Introduce CodeGenerator utilities file

- port/unix/omrsysinfo.c
Add IBM i specfic process for retrieving memory and CPU infos.
> Add IBM i specfic process for retrieving memory and CPU infos

- cmake/modules/ddr/DDRSetStub.cmake.in
See individual commits for detailed descriptions
> CMake: ddr bug fixes

- compiler/aarch64/codegen/BinaryEvaluator.cpp
Implemented lmul evaluator for AArch64
> Implemented lmul evaluator

- ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
Define `INVALID_OFFSET` with a value that should match `UINT32_MAX` and use that instead.
> Replaces uses of UINT32_MAX which is not defined on z/OS

- compiler/z/codegen/ControlFlowEvaluator.cpp
The maxMinHelper compares registers in the wrong order for long values. This commit rearranges the order of the registers to fix that issue and also loads one of the comparison registers into a tmpRegister (instead of clobber evaluating) to avoid an extra register shuffle.
> Fix maxMinHelper when generating Select instructions

- ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
Sometimes on Mac OSX, dwarfdump is linked to "llvm-dwarfdump", which outputs a different format than the version of dwarfdump assumed by ddrgen. This change will select the correct version of dwarfdump to use on those systems that select the wrong version for ddrgen.
Fixes #3708
fyi: @keithc-ca
> Choose correct dwarfdump for osx ddrgen

- compiler/z/codegen/ControlFlowEvaluator.cpp
> Set ContainsCollectedReference on ternary's returnReg

- gc/base/vlhgc/HeapRegionStateTable.hpp
> Fix compile issues on PPC LE

- compiler/optimizer/VPHandlers.cpp
VP (value propagation) recognizes type tests in `constrainIfcmpeqne`, including profiled guards, which look like this:
ifacmpne --> slow path
VFT
aconst 0x... (isClassPointerConstant)
Usually, `VFT` here will be an `aloadi <vft-symbol>` from an object, and VP will set `instanceofObjectRef` to the node that produces the object reference. However, it's possible that `VFT` could be a direct load instead, if e.g. the load of `<vft-symbol>` has been hoisted out of a loop. In that case, `instanceofObjectRef` instead refers to the VFT node. When VP attempts to apply a constraint meant for the object to the VFT on the fallthrough path, intersection fails (because one is an object and the other is not), and as an unintended effect of b485fd2, the fallthrough path (i.e. the inlined body) is removed …
> Constrain the VFT when the object node is unknown

- compiler/aarch64/codegen/BinaryEvaluator.cpp
Optimized imul evaluator register usage
Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>
> Optimized imul evaluator to maximize register re-usage

- util/omrutil/j9memclr.c
> Delete disabled Win32 SSE OMRZeroMemory code

- gc/base/IndexableObjectScanner.hpp
Prepare GC_IndexableObjectScanner to support array elements of different
size (but aligned to sizeof(fomrobject_t)). Also change constructor to
have ability to provide scanMap from child class.
I replaced pointers math to calculation in bytes where necessary.
Also added new constructor for changes and keep old temporary until
child class it not modified to use new constructor. After this old
constructor can be removed.
> New constructor for IndexableObjectScanner

- port/unix/omrsysinfo.c
USER_HZ is an internal kernel constant. sysconf() is the documented way
to get this value.
https://linux.die.net/man/7/time
> It reports times with a granularity defined by the kernel constant
> USER_HZ. User-space applications can determine the value of this
> constant using sysconf(_SC_CLK_TCK).
> Don't rely on USER_HZ

- gc/base/IndexableObjectScanner.hpp
Remove old (unused) constructor
> Cleanup Indexable Object Scanner

- fvtest/porttest/omrfileTest.cpp
- fvtest/porttest/omrvmemTest.cpp
Refer to the individual commits for more details.
> Fix compilation errors on Windows

- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/ObjectModelBase.hpp
- gc/structs/ForwardedHeader.hpp
> Runtime compressed refs work

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
Implement AArch64 GCMaps
-Iterate Over IL Instructions and Set a GCMap if Applicable
> Implement AArch64  GCMaps

- CODEOWNERS
> Add Robert as a code owner to the appropriate files/folders

- CMakeLists.txt
- gc/CMakeLists.txt
- omrtrace/CMakeLists.txt
- port/CMakeLists.txt
- thread/CMakeLists.txt
- util/avl/CMakeLists.txt
- util/hashtable/CMakeLists.txt
> CMake: add headers to scan for macro information

- compiler/il/symbol/OMRSymbol.hpp
- compiler/il/symbol/OMRSymbol_inlines.hpp
- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
Fixes #3993
Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>
> Remove GlobalLabel symbols from compiler

- include_core/omrgcconsts.h
> Add concurrent copy forward read barrier type

- gc/base/GCExtensionsBase.hpp
> Add option to enable concurrent copy forward

- compiler/codegen/OMRRegisterPair.cpp
- compiler/codegen/OMRRegisterPair.hpp
- compiler/z/codegen/OMRRegister.hpp
> Remove FlattenRegisterPairs

- compiler/aarch64/codegen/ARM64HelperCallSnippet.cpp
This commit implements ARM64HelperCallSnippet for AArch64.
> AArch64: Implement ARM64HelperCallSnippet

- CODEOWNERS
Co-owner of optimizer directory.
[skip ci]
> Add Andrew Craik to CODEOWNERS file

- fvtest/compilertest/build/toolcfg/common.mk
- jitbuilder/build/toolcfg/common.mk
Fixes #1651
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Remove J9_VERSION from JitBuilder and Test Compiler

- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LocalOpts.hpp
Left over from a legacy project and not useful to OMR.
> Remove vestigal rematerializeSSAddress

- gc/base/ObjectModelBase.hpp
> More runtime compressed refs work

- ddr/include/ddr/config.hpp
- omrsigcompat/omrsig.cpp
- port/aix/omrosbacktrace_impl.c
- port/aix/omrvmem.c
Fixes https://github.com/eclipse/omr/issues/3927
> Fix compile problems caught by xlc 16

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
This commit implements a new instruction called ARM64CondTrg1Src2Instruction for OMR.
> Implementation of ARM64CondTrg1Src2Instruction instruction

- compiler/optimizer/VPHandlers.cpp
This change adds additional handling in value propagation for known
object arrays which have constant content. Enhancements include
folding of element access as well as folding of arraylength
operations.
> Improved Value Propagation for Constant Arrays

- compiler/z/CMakeLists.txt
> Add missing compiler files to cmake

- cmake/modules/platform/toolcfg/xlc.cmake
- cmake/modules/platform/toolcfg/xlc_exports.exp.in
> CMake: Add support for exported symbols from xlc

- cmake/modules/OmrMetalC.cmake
- port/CMakeLists.txt
> Add initial support for metal c files

- buildenv/jenkins/jobs/pull-requests/PullRequest-zos_390-64
All other pull-request jobs do likewise.
> CMake: Specify -DOMR_DDR=OFF consistently

- cmake/modules/OmrCompilerSupport.cmake
> call perl using PERL_EXECUTABLE

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit implements generateBinaryEncoding() for AArch64
ARM64CompareBranchInstruction.
> Implement ARM64CompareBranchInstruction::generateBinaryEncoding()
