include_core/AtomicSupport.hpp

- dword rather than qword is sufficient for readWriteBarrier
- no memory fence is required for readBarrier
- remove lfence/sfence TODOs (not required for normal reads/writes)

Fix memory fences on x86

---

compiler/aarch64/codegen/InstOpCode.hpp
compiler/aarch64/codegen/OMRInstOpCode.hpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp

This commit implements stubs of InstOpCode files for aarch64.

AArch64: Stub files of InstOpCode

---

gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

CalculateOptimumCopyScanCacheSize can be broken into 2 different
checks. If there are threads waiting for work the GC should use
smaller copyCache to share work more aggressively. Also if the
work queue is empty the GC should also use smaller queues to share
work more aggressively.

Modify calculateOptimumCopyScanCacheSize

---

.gitattributes

when they are download on z/OS system by Rocket Software's
Git program. These changes are needed when building OMR
within OpenJDK with OpenJ9
Signed-off-by: Steve Groeger <groeges@uk.ibm.com>

Add .gitattributes file to allow correct format of files

---

compiler/aarch64/codegen/MemoryReference.hpp
compiler/aarch64/codegen/OMRMemoryReference.cpp
compiler/aarch64/codegen/OMRMemoryReference.hpp

This commit implements the initial version of MemoryReference files
for aarch64.

AArch64: Initial version of MemoryReference files

---

gc/base/GCExtensionsBase.hpp
gc/base/GlobalCollector.hpp
gc/base/Heap.cpp
gc/base/HeapVirtualMemory.cpp
gc/base/MarkingScheme.cpp
gc/base/MarkingScheme.hpp
gc/base/MemorySubSpace.cpp
gc/base/MemorySubSpaceUniSpace.cpp
gc/base/standard/ConcurrentGC.hpp
gc/startup/omrgcstartup.cpp

At a couple of spots Concurrent Scavenger needs to know if the
overlapping Concurrent GC is in pure concurrent mode or it transitioned
to the final STW phase.
Originally, the *mode* variable was used, but this appears to be not
quite correct: there is a small time hole when mode is
CONCURRENT_FINAL_COLLECTION, while exclusive access has not been
obtained yet, and there is still concurrent marking activity (it would
terminate as soon as the tread realizes the mode has changed).
We now rely on isStwCollectionInProgress() API, which will correctly
return true only if ConcurrentGC operatates while having exclusive
access.
All other changes are non-functional and just shuffling the code to
reduce amount of type casting, break mutual #include dependancy, and
generally make compiler happy. …

ConcurrentGC STW phase detection for CS

---

include_core/omrport.h
port/common/omrport.c
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

Added new API sysinfo_cgroup_is_memlimit_set that returns TRUE if
cgroup memory limit is set, FALSE otherwise
Signed-off-by: Ashutosh Mehra asmehra1@in.ibm.com

Add portlib api sysinfo_cgroup_is_memlimit_set

---

compiler/ilgen/MethodBuilder.cpp
compiler/ilgen/MethodBuilder.hpp
compiler/ilgen/TypeDictionary.cpp
compiler/ilgen/TypeDictionary.hpp

The `compiler/ilgen's` `MethodBuilder` and `TypeDictionary` classes
contain a number of class members, maps, that use a custom allocator
(`TR::typed_allocator<...> _memoryRegion`). The allocator itself is
deleted in the destructors of `MethodBuilder` and `TypeDictionary`:
```cpp
_memoryRegion->~Region();
::operator delete(_memoryRegion, TR::Compiler->persistentAllocator());
```
Then, the class destructors automagically invokes the destructors for
member objects: `_structsByName`, `_unionsByName`, `_symbols`, etc.
Eventually, the method `_Node::_Freenode0` of the `_Tree_node` STL
class (std::map is implemented as a tree) for the head node will be
invoked. The method uses the allocator (`_memoryRegion` in our case,
the destroyed yet) to deallocate the head node and, since the allocator
has …

Wrap memory allocators in a struct

---

compiler/arm/codegen/ARMDebug.cpp
compiler/arm/codegen/ControlFlowEvaluator.cpp
compiler/arm/codegen/OMRLinkage.cpp
compiler/il/OMRILOpCodesEnum.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
fvtest/compilertest/iwyu.mk

The runtime/compiler/trj9 directory currently serves no purpose as its
parent directory is completely empty. In an effort to simplify the
codebase and closely match the directory layout of OMR we fold this
trj9 directory away so that understanding how OMR and OpenJ9 fit
together with respect to the compiler component is much easier.

Deprecate trj9 compiler directory

---

include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsignal.c
port/omrportpriv.h
port/unix/omrsignal.c
port/win32/omrsignal.c
port/win64amd/omrsignal.c
port/ztpf/omrsignal.c

1. Add stubs for omrsig_is_master_signal_handler
omrsig_is_master_signal_handler is a newly added function. It determines
if a provided OS handler is a predefined master signal handler. 
There are two master signal handlers: i) masterASynchSignalHandler is
used for asynchronous signals and ii) masterSynchSignalHandler is used
for synchronous signals.
2. Add Unix implementation of omrsig_is_master_signal_handler

Add new function: omrsig_is_master_signal_handler

---

gc/base/Collector.hpp
gc/base/MemorySubSpace.cpp
gc/base/MemorySubSpaceFlat.cpp
gc/base/standard/ParallelGlobalGC.cpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
include_core/omrgcconsts.h

- add gcpolicy:nogc for OpenJ9 to support JEP 318
- new collector epsilon
- _disableGC flag in collector, set it is true for gcpolicy:nogc
- no system gc when _disableGC is true
- only try to expand heap instead of launching gc 
when _disableGC is true

Support An Arbitrarily Low-Overhead Garbage Collector

---

CMakeLists.txt
GNUmakefile
cmake/config.cmake
omr/startup/omrvmstartup.cpp

Also, the corresponding wrapping was done in OMR_ShutdownVM. Not
everything that wants to initialize/shutdown OMR components may
want to initialize/shutdown the health center monitoring tools.
Also fixed a potential bug where the port library's omrtty_printf
member was being used before the port library was initialized.

Wrap omrtrace lib within build flags in OMR_Initialize_VM

---

ddr/lib/ddr-scanner/pdb/PdbScanner.cpp

On Windows, bitfields were not handled properly by DDR.
Consider this declaration found in omrport.h:
```
typedef struct J9Permission {
uint32_t isUserWriteable : 1;
uint32_t isUserReadable : 1;
uint32_t isGroupWriteable : 1;
uint32_t isGroupReadable : 1;
uint32_t isOtherWriteable : 1;
uint32_t isOtherReadable : 1;
uint32_t : 26; /* future use */
} J9Permission;
```
The description produced by ddrgen corresponded to:
```
uint32_t isUserWriteable;
uint32_t isUserReadable : 1;
uint32_t isGroupWriteable : 2;
uint32_t isGroupReadable : 3;
uint32_t isOtherWriteable : 4;
uint32_t isOtherReadable : 5;
uint32_t : 6;
```
Note the first field is not considered a bitfield at all and all but one of the others are just wrong: This change corrects this.

Fetch bitfield width instead of position

---

compiler/env/TRMemory.hpp
compiler/ilgen/OMRIlGeneratorMethodDetails.hpp

For extensible classes such as IlGeneratorMethodDetails when overridden
in downstream projects we may encounter compilation issues as the
extended class will look for a suitable delete operator which should be
compatible with the types on the new operator.
size_t and std::size_t however are not compatible for all compilers
(gcc) and will cause errors complaining that no suitable delete
operator was found for the extensible class.

Use compiler defined size_t instead of std::size_t

---

gc/base/standard/Scavenger.cpp

Adaptive scavenger tenure age adjustment strategy change to mitigate
undesired tenure age adjustments for concurrent scavenger.
Adaptive scavenger tenure age must be adjusted based on the percentage
of new space used. When determining the space used, It not valid to use the
active subspace for concurrent scavenger. The nursery space behaves
in a _“hybrid”_ manner during the concurrent phase of scavenger, where
evacuate and allocate spaces coexist in a single space. Hence, the
active subspace returns an aggregate of allocated space _(from concurrent
allocation)_ and new space used _(bytes flipped)_. This ultimately results
in inconsistent tenure age adjustments between concurrent and
non-concurrent scavenger for the same work loads. That is, tenure age is
observed to be consistently lower …

Concurrent Scavenger Tenure Age

---

compiler/env/FEBase_t.hpp
fvtest/compilertest/runtime/TestCodeCacheManager.cpp
jitbuilder/runtime/JBCodeCacheManager.cpp

JitBuilder, as well as the compiler test infrastructure, use the
`sys/mman.h` memory management api to allocate an executable code cache
for the compiler. Windows doesn't provide the `sys/mman.h` API, so the
`VirtualAlloc` function from the Windows API should be used instead of
`mmap`.
Currently, the method `FEBase<Derived>::allocateRelocationData` (see
`compiler/env/FEBase_t.hpp`) is used only from the
`TR_PPCTableOfConstants` class (so, won't be compiled under Windows) but
in order to compiler the method, the `VirtualAlloc` function are used
there too.
TODO: the use of `VirtualAlloc`/`mmap` has to be replaced with the
`omrvmem_reserve_memory_ex` function from the port library.
The PR depends on #2434
Issue: #1952

Use the VirtualAlloc API to allocate code cache

---

compiler/compile/OMRCompilation.hpp

The Compiler object stores the method to be compiled in a field called
_method, but currently there is no way to retrieve it. This commit adds
that ability.

Create getter for method being compiled

---

compiler/compile/OMRCompilation.hpp
compiler/control/CompileMethod.cpp

In 2 different files in the compiler, omr.h is included,
but not used at all.

Remove unnecessary includes of omr.h in compiler

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/il/OMRSymbolReference.cpp
compiler/il/OMRSymbolReference.hpp
compiler/il/SymbolReference.hpp

Change findOrCreateCPSymbol to take KnownObjectIndex as its last
argument, with the default value being TR::KnownObjectTable::UNKNOWN

Allow findOrCreateCPSymbol to take KnownObjectIndex

---

compiler/aarch64/codegen/OMRMachine.cpp

This commit removes the unnecessary byte order mark (BOM) from
OMRMachine.cpp.

AArch64: Remove BOM from OMRMachine.cpp

---

compiler/aarch64/codegen/Linkage.hpp
compiler/aarch64/codegen/OMRLinkage.cpp
compiler/aarch64/codegen/OMRLinkage.hpp

This commit implements the initial version of OMRLinkage for aarch64.
This is a part of #2545, and depends on #2544.

AArch64: Initial version of OMRLinkage

---

compiler/aarch64/codegen/ARM64SystemLinkage.cpp
compiler/aarch64/codegen/ARM64SystemLinkage.hpp

This commit implements the initial version of ARM64SystemLinkage.
This is a part of #2545, and depends on #2550.

AArch64: Initial version of ARM64SystemLinkage

---

thread/common/omrthread.c

In OpenJ9, segmentation fault is observed because calls to
`interrupt_waiting_thread` has `threadToInterrupt->monitor` set to NULL.
Currently, `interrupt_waiting_thread` does not account for NULL 
`threadToInterrupt->monitor`. If `monitor` is NULL, then `interrupt_waiting_thread`
and `omrthread_monitor_try_enter_using_threadId` should throw an assertion.

Account for NULL monitor

---

port/unix/omrsignal.c

Currently, signalsWithMasterHandlers is set at two places:
omrsig_register_os_handler and registerMasterHandlers.
With this changeset, signalsWithMasterHandlers will only be set within
registerSignalHandlerWithOS after an OS handler has been successfully
registered.
A write barrier is issued before updating signalsWithHandlers and
signalsWithMasterHandlers within registerSignalHandlerWithOS. The write
barrier will allow us to read signalsWithHandlers and
signalsWithMasterHandlers without acquiring registerHandlerMonitor.
omrsig_protect serves asynchronous signals, and OS handlers for
asynchronous signals are generally registered once at startup. Now
onwards, signalsWithMasterHandlers is read without acquiring
registerHandlerMonitor within omrsig_protect. This serves two purposes. 
First, …

Improve setting signalsWithMasterHandlers and fix omrsig_protect

---

jitbuilder/runtime/JBCodeCacheManager.cpp

GCC support of nullptr was introduced with version 4.6; therefore, avoid nullptr for code that may compile with an older version of GCC.

Fix JitBuild compilation error on GCC version < 4.6

---

port/common/omrport.tdf
port/unix/omrsysinfo.c

- Fix container detection with systemd
Up until now, `isRunningInContainer` assumed the process was operating
in a container if init (pid 1) wasn't in the root cgroup in any subsystem.
This is broken in systemd, as it encapsulates pid 1 in a special
"init.scope" group.   
Added the exception of cgroup "init.scope" to fix for systemd
version 226 and onwards.  
[See here](https://github.com/systemd/systemd/blob/master/NEWS#L2951) 
- Fix /proc/[pid]/cgroup file reading with systemd
Systemd adds an entry in /proc/[pid]/cgroup files that has
no subsystem name. This currently breaks the functions that try
to read them, as those functions use fscanf with a format string
expecting a subsystem name.   
This change puts each file entry into a buffer and first attempts
to read expecting a subsystem …

Fix container detection with systemd

---

compiler/env/TRMemory.cpp
compiler/env/TRMemory.hpp

This commit adds two new memory object types that will be used
in downstream projects.

Add new memory object types for stats purposes

---

compiler/aarch64/codegen/PseudoRegisterEnum.hpp
compiler/arm/codegen/PseudoRegisterEnum.hpp
compiler/codegen/OMRRealRegister.hpp
compiler/p/codegen/PseudoRegisterEnum.hpp
compiler/x/amd64/codegen/PseudoRegisterEnum.hpp
compiler/x/i386/codegen/PseudoRegisterEnum.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRInstruction.cpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRRegisterDependency.cpp
compiler/z/codegen/OMRRegisterDependency.hpp
compiler/z/codegen/PseudoRegisterEnum.hpp
compiler/z/codegen/RealRegisterEnum.hpp

Certain registers defined inside RealRegisterEnum.hpp are not hardware backed registers
(ex. TR::RealRegister::NumRegisters), but instead are used as hints for the code generator or as dependencies for real registers. This is quite prevalent in the z/codegen.This commit separates these pseudo registers from the real register enum, and updates the APIs where needed. TR::RealRegister::MISC is also deprecated because it represents the same thing as TR::RealRegister::LastHPR.
Closes: #2491

Define PseudoRealRegisters using new RegDep enum

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

Add option to disable recompilation when inlined callees get redefined

Add option to disable recompilation when inlined callees get redefined

---

compiler/aarch64/codegen/OMRRegisterIterator.cpp
compiler/aarch64/codegen/OMRRegisterIterator.hpp

This commit implements the initial version of OMRRegisterIterator
for aarch64.

AArch64: Initial version of OMRRegisterIterator

---

fvtest/compilertriltest/CallTest.cpp
fvtest/compilertriltest/LinkageTest.cpp
fvtest/tril/tril/ast.cpp
fvtest/tril/tril/ilgen.cpp

Tril parses hexadecimal numbers if and only if they start with the `0x`
prefix. Unfortunately, some C/C++ compilers put the prefix for the `%p`
format specifier (so, they translate `%p` to something like
`0x0123456789ABCDEF`) while others don't. If the `0x` prefix is absent
before the address attribute value of the `Xcall` node, tril
interprets leading digits as a decimal number and the rest starting from
not a digital symbol (A,B,C,D,E or F) as an anonymous attribute. As a
result, the formed `Xcall` node will try to invoke a function by a wrong
address and an Access Violation Error appears.
The commit fixes the problem explicitly adding the `0x` prefix before the
format specifier in all code for `Xcall` tests. Output for the ilgen trace
of the `Xcall` opcode is fixed too.
Signed-off-by: …

Fix tril's Xcall related tests

---

compiler/env/TRMemory.hpp
compiler/env/TRPersistentMemory.cpp
compiler/env/TypedAllocator.hpp
doc/compiler/memory/MemoryManager.md

In the scenario where there is a need to add a class such as the following:
```
class Test
{
public:
Test(uintptr_t f1, uintptr_t f2)
: _field1(f1),
_field2(f2)
{ }
uintptr_t _field1;
uintptr_t _field2;
};
```
into an STL container such as `std::list`. currently there's no way to know how much total persistent memory is used for `Test`. With this commit it is now possible to do so:
1. Add (or replace the existing `TR_ALLOC` with) `TR_ALLOC_SPECIALIZED` with the appropriate `TR_MemoryBase::ObjectType` enum value to the class definition
2. Declare and use the list, eg:
```
typedef TR::list<Test, Test::TrackedPersistentAllocator> TestList;
TestList myList(getTypedAllocator<Test, Test::TrackedPersistentAllocator>(Test::getPersistentAllocator()));
```
Because there is a concern of dll size …

Add tracking of persistent memory in containers

---

port/port_objects.mk
port/unix/omrfiletext.c
port/unix/omrintrospect.c
port/unix/omrosdump.c
port/unix/omrsysinfo.c

This way we don't need to deal with differences in the support for `-Wno-error` in various versions of gcc.
* in omrintrospect.c:
-- record RESUME_FAILURE on failure to destroy a barrier
-- use strcpy instead of strcat to initialize the /proc path

Fix warnings and stop ignoring them

---

compiler/env/FEBase_t.hpp
fvtest/compilertest/runtime/TestCodeCacheManager.cpp
jitbuilder/runtime/JBCodeCacheManager.cpp
port/unix/omrsysinfo.c

- Avoid using nullptr as it is not supported on older gcc.
nullptr is available since gcc 4.6.
- Use J9_IGNORE_RETURNVAL to call mbtowc() when its return value
is not required.

Fix compile errors and warnings

---

compiler/optimizer/RedundantAsyncCheckRemoval.cpp

Remove unnecessary check for case conversion method in
RedundantAsyncCheckRemoval.cpp.

Re-enable toLowerCase/toUpperCase acceleration

---

compiler/z/codegen/InstOpCode.cpp
compiler/z/codegen/OMRInstOpCode.hpp

Add a missing TR::InstOpCode helper for Z.
The missing helper is add logical immediate and
returns ALGFI on 64 bit and ALFI on 32 bit computers.

Add missing TR::InstOpCode helper

---

compiler/codegen/OMRAheadOfTimeCompile.hpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/codegen/Relocation.cpp
compiler/compile/OMRSymbolReferenceTable.cpp
compiler/p/codegen/OMRMemoryReference.cpp
compiler/p/codegen/PPCAOTRelocation.cpp
compiler/runtime/Runtime.hpp
compiler/x/amd64/codegen/OMRMemoryReference.cpp
compiler/x/amd64/codegen/OMRMemoryReference.hpp

More specifically for classes loaded by the bootstrap class loader,
which are unambiguously identifiable at relocation time.
This allows the JIT compiler to make up references to types about which
it has special knowledge. In particular, it's now possible to create a
loadaddr for java/lang/Class "out of thin air," without a corresponding
constant pool entry available.
At a high level, the appropriate relocations are carried out as follows:
1. Allow TR_ClassAddress ExternalRelocations to be created without a
constant pool index.
2. Before grouping into IteratedExternalRelocations, identify these
and set their kind to the new TR_ArbitraryClassAddress.
3. Write the relocation record for TR_ArbitraryClassAddress with the
same data as would be required for TR_ClassPointer.
4. Relocate …

Allow fabricated loadaddr for classes in AOT

---

run_configure.mk

If CONFIG_SHELL not set, default to 'sh' as before
partial solution to #2567 

Call configure using the CONFIG_SHELL variable

---

compiler/control/OMROptions.cpp

verbose={} options was broken causing segmentation fault. This commit fixes that.

Fix vlog options

---

compiler/z/codegen/InstOpCode.cpp
compiler/z/codegen/OMRInstOpCodeEnum.hpp
compiler/z/codegen/OMRInstOpCodeProperties.hpp
compiler/z/codegen/S390GenerateInstructions.cpp

Given the analysis done by our friends over at the V8 project the
software breakpoint in GDB as per [1] is encoded as 0x0001. We add a
new BREAK pseudo instruction and generate this software breakpoint so
users can consistently use the breakOnEntry option cross platform.
[1] https://github.com/v8/v8/blob/a062708467a313d64818b5f8a0ac37dae8775959/src/s390/assembler-s390.cc#L611-L614

Implement breakOnEntry on the Z codegen

---

compiler/optimizer/Inliner.cpp
compiler/optimizer/VPConstraint.cpp
compiler/optimizer/VPHandlers.cpp

This commit was written by Omer for JITaaS and is necessary because we use `TR_DisableKnownObjectTable`. Currently the optimizer will crash without a known object table because it does not check for its existence.
Signed-off-by: Noah Weninger <Noah.Weninger@ibm.com>

Fix crashes with option TR_DisableKnownObjectTable

---

compiler/x/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

Remove conditions on Z and X deciding whether to set static address
of startPC symbol reference. The conditions are complicated and error
prone but the benefit is very limited. Better to set the adderess
unconditionally which is what P is doing already.

Always set address for startPC symbol reference

---

compiler/env/OMRClassEnv.cpp
compiler/env/OMRClassEnv.hpp
compiler/optimizer/VPHandlers.cpp

The optimizer should ideally not fetch class fields directly. Factor it out into a frontend method instead (implemented in openj9).
This commit was originally written by Omer Sheikh and is required for JITaaS support.
Depends on https://github.com/eclipse/openj9/pull/2126
Signed-off-by: Noah Weninger <Noah.Weninger@ibm.com>

Add frontend method getVFTEntry

---

ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/tools/ddrgen/ddrgen.cpp

Explicit casts are needed on 32-bit platforms where size_t and intptr_t are both narrower than int64_t.

Fix compile errors on 32-bit Windows

---

compiler/aarch64/codegen/ARM64OutOfLineCodeSection.cpp
compiler/aarch64/codegen/ARM64OutOfLineCodeSection.hpp

This commit implements the initial version of ARM64OutOfLineCodeSection
for aarch64.

AArch64: Initial version of ARM64OutOfLineCodeSection

---

compiler/aarch64/codegen/OMRCodeGenerator.cpp
compiler/aarch64/codegen/OMRCodeGenerator.hpp

This commit implements the initial version of OMRCodeGenerator files
for aarch64.
This is a part of #2503.

AArch64: Initial version of OMRCodeGenerator

---

compiler/ilgen/IlBuilder.cpp
compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/i386/codegen/TreeEvaluatorTable.hpp

TR::aiadd should only be used on 32-bit;
TR::aladd should only be used on 64-bit;
removing the incorrect supports from their corresponding platforms.
Issue: #566

Fix for incorrect aiadd/aladd support on X86 CG

---

compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/FPTreeEvaluator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OutlinedInstructions.cpp
compiler/x/codegen/OutlinedInstructions.hpp

GC Map and Exception Table are now properly setup for outlined instructions on X86, so that exception can now be throwed.

Support exception throw from outlined code on X86

---

ddr/lib/ddr-scanner/pdb/PdbScanner.cpp

The failing call was to `get_length`; say so in the error message.

Correct error message

---

ddr/tools/getmacros
include_core/omrcfg.h.in
omrcfg.CMakeTemplate.h

Change DDR getmacros script to pick up undef'd flags commented out by
configure.
Treat omrcfg.h as containing both values and flags so unset flags show
up.
Reviewer: @keithc-ca

Include OMR build flags in DDR macros

---

gc/base/MarkingScheme.cpp

Check if Concurrent Marking is in STW mode before attempting to
recoginize/fixup forwarded object

Re-order checks in fixupForwardedSlot

---

compiler/z/codegen/OMRMachine.cpp

If targetReg's state is blocked and no other registers
are available for spilling, then bypass the blocked state to
spill the blocked register, then reverse spill it back when needed.

Spill target register if it is the only one available

---

.gitattributes

git 2.18 starts honoring working-tree-encoding. This causes
means files will be checked out as ebcdic.

Clear gitattributes

---

port/common/omrport.tdf
port/unix/omrsignal.c

- **Update trace point in mapPortLibSignalToUnix [unix]**
Trc_PRT_signal_mapPortLibSignalToUnix_ERROR_unknown_signal is defined as
a TraceEvent. But, it should be a TraceException. Definition of old
trace points can't be changed.
Trc_PRT_signal_mapPortLibSignalToOSSignal_ERROR_unknown_signal is a
TraceException. It was added to replace
Trc_PRT_signal_mapPortLibSignalToUnix_ERROR_unknown_signal. So,
Trc_PRT_signal_mapPortLibSignalToUnix_ERROR_unknown_signal is replaced
with Trc_PRT_signal_mapPortLibSignalToOSSignal_ERROR_unknown_signal.
Trc_PRT_signal_mapPortLibSignalToUnix_ERROR_unknown_signal is set to
Obsolete since it is no longer used.
- **Rename mapPortLibSignalToUnix to mapPortLibSignalToOSSignal [unix]**
Changing function names to be consistent across different platform …

Rename function names and update trace point [unix/omrsignal.c]

---

compiler/compile/OMRCompilation.hpp

Add missing const to std::map allocator type

---

compiler/codegen/OMRTreeEvaluator.cpp
compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/i386/codegen/TreeEvaluatorTable.hpp

TR::a2i should only be used on 32-bit;
TR::a2l should only be used on 64-bit;
removing the incorrect supports from their corresponding platforms.
In addition, use TR_ASSERT_FATAL for badILOpEvaluator and unImpOpEvaluator,
ensuring the invalid usage of IL OpCode is always reported.
Issue #2702

Fix for incorrect a2i/a2l support on X86 CG

---

gc/base/EnvironmentBase.hpp
gc/base/MasterGCThread.cpp
gc/base/MasterGCThread.hpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/EnvironmentStandard.hpp
gc/base/standard/Scavenger.cpp

Stop-the-World Concurrent Scavenger phases of a cycle will now use
implicit master thread (mutator thread that triggered the phase through
Allocation Failure).
MasterGCThread class is modified to now support both implicit and
explicit master GC thread for STW phases. The later (for now) is still
used for Balanced GC (in OpenJ9).
Another optional behavior is whether to acquire or not VM access during
concurrent phase. The default is not to (again, still used by Balanced
GC, during concurrent marking), while CS acquires it (it must because it
moves objects).
The benefit of having implicit master is simpler start/end of a STW
increment, since there is no need for use of assume/relinquish exclusive
access API, which in various ways complicates some corner cases of VM
access synchornization …

Implicit master for CS STW

---

compiler/aarch64/codegen/OMRMachine.cpp
compiler/arm/codegen/OMRMachine.cpp
compiler/codegen/OMRMachine.cpp
compiler/codegen/OMRMachine.hpp
compiler/p/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMachine.hpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRMachine.hpp

* remove deprecated colouring global register allocator functionality
* remove unused cache of register numbers by kind and modify
architecture constructors

Misc. Machine class cleanup

---

compiler/x/amd64/codegen/OMRRealRegister.hpp
compiler/x/codegen/FPTreeEvaluator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRInstruction.hpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/OMRX86Instruction.hpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/codegen/X86Debug.cpp
compiler/x/i386/codegen/OMRRealRegister.hpp

Introducing support for three-operand instructions. 
RegRegReg instructions with Op/En marked as RVM are now supported.

Initial three-operand instruction support for X86

---

port/ztpf/omrintrospect.c
port/ztpf/omrosdump.c
port/ztpf/omrosdump_helpers.h
port/ztpf/omrsignal_context.c
port/ztpf/omrsignal_context.h
port/ztpf/safe_storage.h

This Pull request affects only z/TPF and refactors
ucontext.h header inclusion for some segments
related to dump processing.  The cleanup was
driven by zTPF compiler sysroot cleanup.

Refactor ucontext header inclusions for z/TPF

---

compiler/env/CompileTimeProfiler.hpp
compiler/ras/ILValidationRules.hpp

z/TPF currently doesn't support the Compiler Time Profiling
like Linux.  Potentially in the future depending on priorities.
Also, z/TPF gets a compilation failure in ILValidationRules
because of ATOE translation mapping for remove.  The guard
macro prevents this for z/TPF only.

Disable Compiler Time Profiler and ATOE Mapping for zTPF

---

compiler/z/codegen/ControlFlowEvaluator.cpp

Add evaluator to handle max and min opcodes in Z codegen
The specific opcodes are imax, imin, lmax and lmin.

Add Evaluator for max and min opcodes in Z codegen

---

fvtest/porttest/si_numcpusTest.cpp
include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

This change adds functionality for overriding the number of CPUs
returned by `omrsysinfo_get_number_CPUs_by_type` for the
`OMRPORT_CPU_TARGET` type. This is implemented as a port library
global and can be set through a port library function.
Since this functionality fulfills the needs that were previously
satisfied by the `OMRPORT_CPU_ENTITLED` type, this change also
removes entitled CPU count altogether. User-specified CPUs is now the only
CPU count set by the user.
This change is to satisfy the need for this functionality, as
discussed in eclipse/openj9#1166.
Issue: eclipse/openj9#1166.
Signed-off-by: Mohammad Ali Nikseresht <anikser@ibm.com>

Add userSpecifiedCPUs count for overriding number of CPUs

---

compiler/arm/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/compile/OMRCompilation.cpp
compiler/control/CompileMethod.cpp
compiler/il/Aliases.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/Inliner.hpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRTransformUtil.cpp
compiler/optimizer/OrderBlocks.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/VPHandlers.cpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
compiler/x/amd64/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRRegisterDependency.cpp
compiler/x/i386/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

- during compilation, the per-method TR::Options should be used instead of the global one
- mostly happens at the Optimizer and Code Generation stage
- simplify comp()->getOptions()->getOption(TR_XXX) to comp()->getOptions(TR_XXX), they are equivalent
- switch _options usage to options in OMRCompilation constructor

Fix incorrect usage of TR::Options

---

compiler/optimizer/RegisterCandidate.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRMachine.cpp

Register pressure simulation is a prerequisite for HPR GRA because GRA and local RA need to make consistent choices and register pressure simulation is the only part of GRA that is HPR aware. As concrete examples, among others, consider the following:
1. A collected reference coming in as a parameter
In this case GRA needs to know that on 64-bit such a register candidate should not be considered for HPRs, since they are really 32-bit registers. However GRA does not know anything about this. It is the register pressure simulation algorithm [1] that coordinates with the codegen on whether collected references are HPR elligible.
2. A valid HPR candidate is being used as a return value
In this case GRA needs to be aware of the choices local RA will make. Because a value feeds into a return …

Disable HPR GRA unless register pressure simulation is enabled

---

compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VPHandlersCommon.cpp

This change adds a safety check after the call to constrainCall.

Check if the node has been transformed in constrainVCall

---

port/win64amd/omrsignal.c

1.  **Add a data structure to store signal handler info [win64amd]**
We want to restore the signal handlers after the OMR port library
shutdowns. So, we need to cache the original signal handler.
handlerInfo is added to store {originalHandler, restore} for every
signal on win64amd. restore will be set to 1 after the original signal
handler is cached.
2. **Add registerSignalHandlerWithOS [win64amd]**
registerSignalHandlerWithOS registers the signal handler with the OS on
win64amd platform. Also, it caches the original signal handler.
3. **Add registerHandlerMonitor [win64amd]**
Added registerHandlerMonitor to synchronize calls to
registerSignalHandlerWithOS.
initializeSignalTools updated to initialize registerHandlerMonitor, and
destroySignalTools updated to free registerHandlerMonitor.
In …

Minimal Signal Changes Part 2 [win64amd]

---

compiler/control/OMROptions.cpp
compiler/il/OMRIL.cpp
compiler/il/OMRIL.hpp

This PR involved two changes. 
1. Add helper functions to generate ternary select nodes
2. Add tracing options for jProfiling (J9 specific optimization)

Add helper functions for ternary select node

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

This commits adds following options.
1. jProfilingLoopRecompThreshold : To specify base threshold for loop which will be adjusted as per loop depth and will be compared against raw loop count.
2. jProfilingMethodRecompThrehold : To specify number of method invocations required to trip recompilation of profiling body.

Add options for jProfiling

---

compiler/ilgen/OMRMethodBuilder.cpp
compiler/ilgen/OMRMethodBuilder.hpp

Having the uses of snprintf in the header forces the define for
snprintf to be in the header for Windows platforms. Moving limits
the scope of the definition into the cpp.

Move uses of snprintf into cpp

---

compiler/aarch64/codegen/ARM64Ops.hpp
compiler/aarch64/codegen/OpBinary.cpp

This implements the basic binary encoding extracted from ARM64
documentation.
issue: #2588
Signed-off-by: jeanlego <jeanphilippe.legault@unb.ca>

AArch64: Binary Encoding

---

port/win32/omrsignal.c
port/win64amd/omrsignal.c

1. **Add thread to execute handlers for asynchronous signals [win64amd]**
Added asynchSignalReporterThread to execute handlers
(J9WinAMD64AsyncHandlerRecord->handler) for asynchronous signals.
asynchSignalReporterThread is initialized/created within
initializeSignalTools.
asynchSignalReporter represents the main body of
asynchSignalReporterThread. Currently, it is a stub which sets the
thread's name and executes the thread exit code. The main functionality
of asynchSignalReporter will be added later once required dependencies
have been introduced.
Code related to asynchSignalReporterThread is wrapped with
OMR_PORT_ASYNC_HANDLER flag (similar to the unix implementation).
omrutil.h has the prototype for createThreadWithCategory.
2. **Add registerMasterHandlers [win64amd]** …

Minimal Signal Changes Part 3 [win64amd]

---

compiler/arm/codegen/OMRCodeGenerator.cpp
compiler/control/OMROptions.cpp

Set the option to disable max and min optimizations to
true by default on ARM.

Disable optimizations for max and min on ARM

---

cmake/config.cmake

This flag enables the JitBuilder and Tril tests in the Travis CI builds.
Fixes #2745

Correctly set OMR_JITBUILDER_TEST flag in cmake.config

---

run_configure.mk

Reverts eclipse/omr#2647
Code did not ultimately solve the problem it intended to.  Also the generated configure script will
re-launch itself with $CONFIG_SHELL if set (autoconf documentation indicated that feature was not yet
implemented).

Revert "Call configure using the CONFIG_SHELL variable"

---

compiler/arm/codegen/ARMBinaryEncoding.cpp
compiler/arm/codegen/ConstantDataSnippet.cpp
compiler/arm/codegen/OMRTreeEvaluator.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/codegen/Relocation.cpp
compiler/codegen/Relocation.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRConstantDataSnippet.cpp
compiler/p/codegen/OMRMemoryReference.cpp
compiler/p/codegen/PPCAOTRelocation.cpp
compiler/p/codegen/PPCBinaryEncoding.cpp
compiler/ras/DebugCounter.cpp
compiler/x/amd64/codegen/OMRMemoryReference.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRMemoryReference.cpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/z/codegen/ConstantDataSnippet.cpp
compiler/z/codegen/S390Instruction.cpp

These changes primarily make external relocations a little less AOT-specific (to pave the way for their use in other contexts) by renaming `addAOTRelocation()`. The old API is kept intact so that downstream consumers (OpenJ9) will still build until they are fixed. Also included is a change to the x86 codegen to allow for finer grained control of which kinds of statics are relocatable. Finally, a few bugs are fixed.

Bug fixes, cleanups, and improvements for external relocations and AOT

---

compiler/aarch64/codegen/OMRInstOpCode.hpp

This commit adds the definition of an array binaryEncodings[] in
OMR::ARM64::InstOpCode.
Issue: #2754

Aarch64: Definition of binaryEncodings[]

---

compiler/aarch64/codegen/ARM64ConditionCode.hpp

This commit updates the file ARM64ConditionCode.hpp based on
discussion in #2622:
- Use the TR namespace.
- Fill the enum members.

AArch64: Update ARM64ConditionCode.hpp

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

- need access to OMR::Options private fields in a downstream project

Change OMR::Options fields from private to protected

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/x/codegen/X86Debug.cpp

1. Dump instructions after ProcessRelocationsPhase;
2. Properly print absolute address for DataSnippet on X86.

JIT Debug trace enhancement

---

port/linux/omrvmem.c
port/ztpf/omrvmem.c

Some systems (e.g. Windows Subsystem for Linux) ignore the requested allocation address and repeatedly return the same address. When this happens we terminate the loop early to avoid excessive delays.
More recently, we've seen slow startup on z Linux as well. This change helps there too.
This is marked as 'WIP' because we need to understand what, if any, detrimental effects this has.

Fix slow allocation of memory

---

compiler/infra/SimpleRegex.cpp
compiler/infra/SimpleRegex.hpp

This pointer only remains valid for the lifetime of the original string. However, in practice SimpleRegex objects are only created from strings in enviroment variables or command line options, which have a static lifetime.
Needed to pass regex options from client to server for JITaaS.
Signed-off-by: Noah Weninger <noah.weninger@ibm.com>

Store a pointer to the original regex string in SimpleRegex

---

doc/GuideForCommitters.md

Update the possible build targets in the committer guide.
[skip ci]

Fix documentation of genie-omr platforms

---

compiler/ras/Tree.cpp

Print float/double in scientific notation when necessary, as well as its raw bits.

Print float/double more precisely in trace logs

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/Instruction.hpp

This commit implements the initial version of ARM64BinaryEncoding.cpp
for instruction classes defined in ARM64Instruction.hpp.

AArch64: Initial version of ARM64BinaryEncoding.cpp

---

compiler/x/codegen/OMRCodeGenerator.hpp

supportsCMOV() is not in-use and unnecessary, removing it.

Remove unused query for CMOV support on X86

---

fvtest/compilertest/CMakeLists.txt

Compilation units which specific for other environments, different from the current one, are
excluded from the compilertest cmake-managed build.

[CMake] Build an arch-specific compilertest only

---

compiler/z/codegen/OMRLinkage.cpp
compiler/z/codegen/OMRLinkage.hpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRMachine.hpp
compiler/z/codegen/S390SystemLinkage.hpp
compiler/z/codegen/SystemLinkage.cpp

- Deprecate unused `notifyHasalloca` function
- Deprecate unused `lockGlobalRegister` function
- Deprecate unused `releaseGlobalRegister` function
- Deprecate unused `findGlobalRegisterIndex` function
- Fold `supportLockedRegisterAssignment` as false
- Deprecate unused `[un]lockGPR` function
- Deprecate unused `VaStartPatchGroup` class
- Deprecate unused `AllocaPatchGroup` class

Deprecate unused Z codegen APIs

---

compiler/z/codegen/OMRTreeEvaluator.cpp

Fix z generic load helper to use the correct generate APIs. The genericLoadHelper() looks up an array for the correct load instructions. The load instructions in the array come in different instruction formats and this helper is not using the correct API in all cases. This change corrects the APIs genericLoadHelper() uses.
Also, cleanup and refactor genericLoadHelper() and remove its architecture level support. The codebase's minimum supported z/Architecture level is z9 and genericLoadHelper() uses only instructions from z9 and below.

Fix z codegen generic load helper

---

gc/base/Configuration.hpp
gc/base/standard/ConfigurationStandard.cpp
gc/base/standard/ConfigurationStandard.hpp
gc/verbose/VerboseHandlerOutput.cpp

This is done now in Configuration class, while it used to be initialized
in downstream projects like OpenJ9.
It is done just after initilization of GC thread count for STW
phase. Then Concurrent Scavenger can initialize its own
background count as a function of STW GC thread count.
The background default is set to appox 1/4 of STW GC thread count.
Also, reporting the counts in verbose GC <initialized stanza. It can now
have two more lines (adding for Concurrent Mark, too):
```
<attribute name="gcthreads" value="24" />
<attribute name="gcthreads Concurrent Scavenger" value="6" />
<attribute name="gcthreads Concurrent Mark" value="1" />
```  

Initialize CS background GC thread count

---

compiler/ilgen/OMRVirtualMachineOperandArray.cpp
compiler/ilgen/OMRVirtualMachineOperandArray.hpp
compiler/ilgen/OMRVirtualMachineOperandStack.cpp
compiler/ilgen/OMRVirtualMachineOperandStack.hpp

Currently the name for the operand stack/array base was always
Operand<Type>_Base which means you can only ever use one of them
per application. This change allows multiple to be used if the
consumer specifies a base name.

Create a temp for the Operand[stack/array] base name

---

compiler/runtime/Runtime.cpp
compiler/runtime/Runtime.hpp
include_core/omrcomp.h

Runtime helper table no longer unwrap function pointers at initialization
time. It now keeps an array of function pointers and only unwraps the raw
entry points whenever a user calls the getAddress() API.
Also, add a getEnvironment() API to get the function pointers'
environments. This can be helpful for platforms whose C functions have
environment pointers.

Make runtime helper table class do lazy address translation

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/CodeGenerator.hpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/i386/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

There are several places in the CodeGenerator (common codegen and
individual architectures) where the CodeGenerator object is retrieved
indirectly within CodeGenerator member functions rather than simply from
the immediately available `self()` function. In this case, `self()` is
sufficient rather than `self()->comp()->cg()` as they should return the
same pointer.
Closes: #2755

Use immediately available self() in CodeGenerator

---

fvtest/porttest/omrmemTest.cpp
fvtest/porttest/omrvmemTest.cpp
fvtest/porttest/testHelpers.cpp
include_core/omrport.h
port/linux/omrvmem.c
port/ztpf/omrvmem.c

On some Linux systems (e.g. s390x) the initial text segment is loaded at virtual address `0x80000000`. (I suspect, but don't know how to verify, that this is new behavior on zLinux which lead to https://github.com/eclipse/openj9/issues/2388.)
A 2GB heap (either because the system has 8GB of RAM or the user explicitly requested that size) cannot be allocated below 4GB (to avoid the need for a non-zero shift for compressed references).
The old (documented) behavior of the `OMRPORT_VMEM_ALLOC_QUICK` option is to fall back to a linear search, which in our example will make 512k attempts to allocate blocks at multiples of 4k - all of which will fail. This only serves to delay returning to `MM_MemoryManager::createVirtualMemoryForHeap` where it can retry with larger shifts for compressed …

Avoid linear search if OMRPORT_VMEM_ALLOC_QUICK option is specified

---

port/common/omrport.tdf
tools/hookgen/HookGen.cpp
tools/hookgen/HookGen.hpp
tools/tracegen/ArgParser.cpp
tools/tracegen/CFileWriter.cpp
tools/tracegen/DATFileWriter.cpp
tools/tracegen/TDFTypes.hpp
tools/tracegen/TraceGen.cpp
tools/tracegen/TraceGen.hpp
tools/tracegen/TraceHeaderWriter.cpp
tools/tracemerge/DATMerge.cpp

Reduce the output of both of these tools to none, unless something goes
wrong.  Add a verbose output to give the old output.

Reduce output from hookgen and tracegen

---

compiler/compile/OMRCompilation.cpp
compiler/control/CompileMethod.cpp
compiler/il/Aliases.cpp
compiler/optimizer/Inliner.hpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OrderBlocks.cpp
compiler/optimizer/VPHandlers.cpp
compiler/x/amd64/codegen/AMD64SystemLinkage.cpp

- Backing out this commit because of 2% performance regression on daytrader

Revert part of fix incorrect usage of TR::Options

---

compiler/env/TRMemory.hpp
compiler/il/NodeExtension.hpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/il/OMRTreeTop.cpp
compiler/il/OMRTreeTop.hpp
compiler/infra/List.hpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/OMROptimization.hpp
compiler/optimizer/OMROptimizationManager.hpp
compiler/optimizer/OptimizationPolicy.hpp
compiler/optimizer/OptimizationUtil.hpp
compiler/optimizer/SinkStores.hpp
compiler/optimizer/UseDefInfo.hpp
compiler/optimizer/ValueNumberInfo.hpp
compiler/runtime/CodeCacheTypes.hpp
compiler/runtime/OMRCodeCache.hpp
compiler/runtime/OMRCodeCacheMemorySegment.hpp
compiler/x/codegen/OMRRegisterDependency.hpp

When memory is allocated for an object with operator new, the object's
constructor is called. If the constructor throws an exception, any
memory that was allocated for the object should be deallocated. This
cannot take place unless an operator `delete` function exists that matches
the operator `new`.
The compiler code generates a lot of **C4291** warnings because no placement
form of operator `delete` has been defined that matches the placement form
of operator `new`.
The commit adds missed placement forms of operator `delete` to the
compiler code.

Add matched user-defined placement delete operator through the compiler code

---

README.md

Accidentally discovered this issue. Too many columns resulted in the
platform names being split into multiple lines to fit smaller screens.

Transpose platform build status table in README [skip ci]

---

port/win64amd/omrsignal.c

**1) Add createAsyncHandlerRecord for common code [win64amd]**
createAsyncHandlerRecord function creates a new async handler record.
omrsig_set_async_signal_handler and
omrsig_set_single_async_signal_handler have this code in common. Adding
createAsyncHandlerRecord function reduces redundant code.
**2) Move common code into registerMasterHandlers [win64amd]**
omrsig_set_async_signal_handler and
omrsig_set_single_async_signal_handler share common code related to
registering master handlers. The common code has been moved into
registerMasterHandlers.
**3) Update removeAsyncHandlers [win64amd]**
In removeAsyncHandlers, code has been added to remove the HandlerRoutine
(consoleCtrlHandler) during shutdown if asyncHandlerList is empty.
**4) Update initializeSignalTools [win64amd]**
According to …

Minimal Signal Changes Part 4 [win64amd]

---

port/win32/omrsignal.c
port/win64amd/omrsignal.c

1) **Add signalMap [win32]**
signalMap includes the list of signals supported by a platform.
OMRPORT_SIG_FLAG_SIGALLASYNC is a bit-mask of all the asynchronous
signals that OMR signal library supports on all platforms.
OMRPORT_SIG_FLAG_SIGALLSYNC is a bit-mask of all the synchronous signals
that OMR signal library supports on all the platforms.
signalMap has been added for win32. It specifies the signals which
are supported on win32.
2) **Add implementation of omrsig_map_os_signal_to_portlib_signal [win32]**
Added a static method, mapOSSignalToPortLib, which is called from
omrsig_map_portlib_signal_to_os_signal. mapOSSignalToPortLib will be
used from other places in the future.
3) **Add implementation of omrsig_map_portlib_signal_to_os_signal [win32]**
Added a static method, …

Minimal Signal Changes Part 1 [win32]

---

compiler/x/codegen/OutlinedInstructions.hpp

An API is introduced to allow accessing underlying TR_OutlinedInstructions
from a TR_OutlinedInstructionsGenerator.

Allow accessing TR_OutlinedInstructions on X86

---

compiler/ilgen/IlInjector.cpp
compiler/ilgen/IlInjector.hpp
compiler/ilgen/MethodBuilder.hpp
compiler/ilgen/OMRBytecodeBuilder.hpp
compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
compiler/ilgen/OMRMethodBuilder.cpp
compiler/ilgen/OMRMethodBuilder.hpp
compiler/ilgen/OMRVirtualMachineOperandStack.cpp
jitbuilder/release/Makefile
jitbuilder/release/src/InliningRecFib.cpp
jitbuilder/release/src/InliningRecFib.hpp
jitbuilder/release/src/IterativeFib.cpp
jitbuilder/release/src/IterativeFib.hpp
jitbuilder/release/src/RecursiveFib.cpp
jitbuilder/release/src/RecursiveFib.hpp

Add a new Call service to IlBuilder that provides the target via a MethodBuilder object. The current implementation will inline the code generated by the MethodBuilder object, but forced inlining will not remain the default forever (so treat it like a hint).
The current implementation is an inlining mechanism (no heuristics) mostly at the IlBuilder level. It does not yet use the inliner optimization in the OMR compiler, but the longer term plan is to sink down to the inliner. One distinct drawback of the current implementation is that it does not set up any inline table, so all the code just looks like it is from the method being compiled. Another current drawback is that virtual machine state in the caller will not be taken into account when operations like Commit are invoked in a …

Prototype inlining support for JitBuilder

---

compiler/aarch64/codegen/OMRMachine.cpp
compiler/aarch64/codegen/OMRMachine.hpp
compiler/arm/codegen/OMRMachine.hpp
compiler/codegen/OMRMachine.hpp
compiler/p/codegen/OMRMachine.cpp
compiler/p/codegen/OMRMachine.hpp
compiler/x/amd64/codegen/OMRMachine.cpp
compiler/x/amd64/codegen/OMRMachine.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMachine.hpp
compiler/x/i386/codegen/OMRMachine.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRMachine.hpp
compiler/z/codegen/S390Debug.cpp

Hoist the registerFile array to the common base class to
share the implementation.

Hoist registerFile to base Machine class

---

compiler/codegen/OMRTreeEvaluator.hpp
compiler/env/jittypes.h
compiler/x/amd64/codegen/OMRMemoryReference.cpp
compiler/x/codegen/OMRMemoryReference.cpp

Move data size check helpers into shared header file: env/jittypes.h

Consolidate data size check helpers on X86

---

doc/compiler/CompilerOptions.md
doc/compiler/ProblemDetermination.md

Problem determination document contains info about verbose log and compilation trace logs. Compiler options now have a dedicated document. A lot of the contents in the PR have been migrated from the internal wiki with some changes.
Anyone looking at this PR: please feel free to make suggestions for additions/deletions, point out incorrect info, etc. The goal of these changes is that the community outside of IBM have easy access to information when working with the OMR Compiler.

Updates to compiler docs

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/ARM64ShiftCode.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

This commit adds Trg1Src2ShiftedInstruction, Trg1Src2ExtendedInstruction,
Trg1Src3Instruction, and CompareBranchInstruction for aarch64.

AArch64: Add Trg1Src2ShiftedInstruction, Trg1Src2ExtendedInstruction, etc.

---

compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

This commit adds utility functions for ASR, LSR, and LSL instructions
with immediate shift amount.  They are aliases of SBFM and UBFM
instructions in aarch64.

AArch64: Add functions for generating Shift (immediate) instructions

---

port/unix/omrsysinfo.c

retrieveLinuxCgroupMemoryStats returns non-zero value on success
which is interpreted as failure

Fix return code of retrieveLinuxCgroupMemoryStats

---

port/common/omrcuda.cpp

According to [1], CUDA Toolkit version 9.1 was released in December 2017 and version 9.2 was released in March 2018.
[1] https://developer.nvidia.com/cuda-toolkit-archive

Add support for CUDA 9.1 and 9.2

---

compiler/ras/DebugCounter.cpp

Change debug counters to guard against negative caller
indexes which are less than negative 1. Nodes created in
TR_J9EstimateCodeSize have callerIndexes set to -10 and
would cause a crash when attempting to access the method
using the caller index.

Guard against negative callerIndexes in debugCounters

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCache.hpp

As part of the work to stage the changes for #2832, this PR introduces a
new API for the OMR::CodeCache::initialize() function that does not
accept a CodeCacheHashEntrySlab parameter.  Instead, it will allocate the
slab as part of the initialization process thereby encapsulating the
trampoline requirements within the CodeCache.
This single change is being introduced to allow downstream projects to
adapt to the changes proposed in #2832.

Introduce CodeCache::initialize() without CodeCacheHashEntrySlab parm

---

compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
jitbuilder/release/src/Switch.cpp

This change set adds the `IlBuilder::JBCase` class to encapsulate the different pieces needed to construct a "case" for the `IlBuilder::Switch()` service. This avoids having to keep track of the different pieces independently in the implementation and also simplifies generating language bindings for the service.
This is a breaking change as the API is not backwards compatible. Code of the form:
```c++
Switch("foo", &defaultBuilder, 3,
1, &case1Builder, false,
2, &case2Builder, false,
3, &case3Builder,false);
```
must be changed to
```c++
Switch("foo", &defaultBuilder, 3,
MakeCase(1, &case1Builder, false),
MakeCase(2, &case2Builder, false),
MakeCase(3, &case3Builder,false));
```
FYI @mstoodle @jduimovich @charliegracie @rwy0717

Change implementation of JitBuilder's Switch service

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/OMRInstOpCode.hpp
compiler/aarch64/codegen/OMRMemoryReference.cpp
compiler/aarch64/codegen/OMRMemoryReference.hpp

This commit implements the initial version of generateBinaryEncoding()
in OMRMemoryReference for aarch64 and related functions.

AArch64: Initial version of OMRMemoryReference.generateBinaryEncoding()

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp

This commit does not provide an implementation for findOrCreateLiteral
but simply produces an equivalent stub in the Z CodeGenerator class.
This is the first step in a series of staged commits to safely remove
it from the FrontEnd class.
Issue #2180

Create an implementation of findOrCreateLiteral in Z CodeGenerator

---

compiler/z/codegen/OMRInstOpCodeProperties.hpp

According to PoPs the PPA instruction is an RRF-c format instruction
with no third register and a mask, hence it should be labeled as an
RRF2 instruction.
Note that the .format field in the table modified is only used as a
reference and has no bearing on any execution path.

Update PPA format to RRF2

---

compiler/x/i386/codegen/IA32SystemLinkage.cpp
fvtest/compilertest/tests/X86OpCodesTest.cpp

lcall is now supported on X86-32.

Support lcall on X86-32

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp

This commit adds CodeGenerator to the parameter list of
OMR::ARM64::MemoryReference::estimateBinaryLength().
Issue: #2863

AArch64: Remove CodeGenerator parm from MemoryReference::estimateBinaryLength()

---

compiler/x/codegen/X86Ops_inlines.hpp

The assumption which REX.W can only be set on X86-64 is no-longer true.
For example, REX.W of FMA instructions is set even on X86-32.
Therefore, the assertion should be removed.

Remove checking REX.W when encoding on X86-32

---

jitbuilder/build/files/target/aarch64.mk

Build AArch64 Compiler Files
- The Makefile in the JITBuilder was trying to use a wildcard operation to get all of the .cpp files in the AArch64 Compiler directory but it was failing to do so.
- Now explicitly lists all of the .ccp files as is convention.
For Issue #2839

Build AArch64 Compiler Files

---

include_core/omrthread.h
thread/common/threadhelpers.cpp

In OMR, a user can set `lib->maxSpinThreads` to 0. In the current
implementation, no threads will spin if `lib->maxSpinThreads` is set to 0.
This is a redundant feature since spinning can also be disabled by
setting `lib->defaultMonitorSpinCount1/2/3` to 1.
So, the behavior for `lib->maxSpinThread = 0` is re-purposed. If
`lib->maxSpinThreads` is set to 0, then an upper bound won't be enforced
on spin threads, and unlimited spin threads will be allowed.
This is an experimental feature. A consumer of OMR can enable this
feature by setting `lib->maxSpinThread` to 0 via
`omrthread_global("maxSpinThreads")`. It will be used to create heuristics
for locking workloads which benefit from no bound on the number of spin
threads.

Add feature to ignore spin thread bound

---

configure
configure.ac
ddr/lib/ddr-scanner/pdb/PdbScanner.cpp

The change is to improve DDR support in script/code
so as to allow use of VS 2017 on Windows.
Signed-off-by: CHENGJin <jincheng@ca.ibm.com>

Improve DDR support to allow use of VS 2017

---

fvtest/porttest/omrvmemTest.cpp

The following compile error was encountered - `error:
comparison between signed and unsigned integer expressions`.
The proposed changes fixes the above compile error.
Closes: #2857

Fix compile error

---

include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsignal.c
port/omrportpriv.h
port/unix/omrsignal.c
port/win32/omrsignal.c
port/win64amd/omrsignal.c
port/ztpf/omrsignal.c

1) **Add stubs for omrsig_is_signal_ignored**
omrsig_is_signal_ignored checks if the signal is ignored by the OS. If
the signal is ignored, isSignalIgnored is set to TRUE. Otherwise,
isSignalIgnored is set to FALSE.
If an error is encountered during evaluation, OMRPORT_SIG_ERROR is
returned. 0 is returned on success. If OMRPORT_SIG_ERROR is returned,
then the value of isSignalIgnored should be ignored.
2) **Implement omrsig_is_signal_ignored [unix]**
For unix, implementation for omrsig_is_signal_ignored has been added.
For win32 and win64amd, sigaction doesn't exist. There is no way to
check if a signal is ignored on win32/win64amd. omrsig_is_signal_ignored
should always return FALSE on win32/win64amd. The stub implementation is
sufficient on win32/win64.
For ztpf, an implementation of …

Implement omrsig_is_signal_ignored

---

compiler/z/codegen/FPTreeEvaluator.cpp

Z codegen does not allow memory references to be used in
more than instruction. This change removes the duplicated
usage in fbits2i and instead creates 2 memory references.

Avoid reusing mem ref in fbits2i evaluator in Z codegen

---

compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
jitbuilder/release/src/Conditionals.cpp

As was done in #2821 for JitBuilder's `Switch()` service, the new class `JBCondition` is added to encapsulate the different pieces needed to use the `IfAnd()` and `IfOr()` services. This avoids having to keep track of the different pieces independently in the implementation and also simplifies generating language bindings for the services.
This is a breaking change as the API is not backwards compatible. Code of the form:
```c++
IfAnd(&returnTrue, &returnFalse, 3,
equiv1, rc12Equal,
equiv2, rc23Equal,
equiv3, rc34Equal);
```
must be changed to
```c++
IfAnd(&returnTrue, &returnFalse, 3,
MakeCondition(equiv1, rc12Equal),
MakeCondition(equiv2, rc23Equal),
MakeCondition(equiv3, rc34Equal));
```
FYI @mstoodle @jduimovich @charliegracie @rwy0717

Change implementation of JitBuilder's IfAnd and IfOr services

---

compiler/optimizer/Inliner.hpp

The deprecated FrontEnd interface contains a function `isInlineableNativeMethod`
that should be part of the `OMR_InlinerPolicy` class.  Introduce a
new virtual function into that policy class as the first step
to migrating it from the FrontEnd interface.
Issue #2844

Introduce isInlineableNativeMethod API in OMR_InlinerPolicy

---

compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp

Code related to VMifInstanceOf has been deprecated, removing them.

Code cleanup related to VMifInstanceOf on X86

---

compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRRegisterDependency.hpp

Add registers used in ICF in maxMinHelper to register
dependency. This change also changes the assertion that
registers used inside an ICF have been added to the
dependency since this is a fatal error.

Add registers in maxMinHelper to register dependency

---

gc/stats/ScavengerCopyScanRatio.cpp
gc/stats/ScavengerCopyScanRatio.hpp
gc/stats/ScavengerStats.cpp
gc/stats/ScavengerStats.hpp

Introduce two Concurrent Scavenger specific read barrier stats counts:
- number of objects being copied 
- number of reference slots being updated
Maintain them in ScavengerCopyScanRatio structure, so that we can report
progress of the counts throughout a GC cycle (reporting itself is done
by downstream project, like OpenJ9).

Read barrier stats

---

gc/verbose/VerboseHandlerOutput.cpp

CacheList Splitting Configuration Modification. Adding arguments
to verbose logging and remove code duplication.

CacheList Splitting Configuration Modification

---

compiler/optimizer/OSRDefAnalysis.cpp

Mimic interpreter frame shape doesn't need to zero out dead slots after
OSR out and therefore OSRLiveRangeAnalysis is not needed.

Disable OSRLiveRangeAnalysis when mimic interpreter

---

compiler/z/codegen/OMRCodeGenerator.cpp

Change insert prefetch to insert BPP after ending internal
control flow, this will prevent BPP from being inserted
within a ICF.

Change insert prefetch to insert BPP after ICF

---

ddr/include/ddr/ir/Symbol_IR.hpp
ddr/include/ddr/ir/TypePrinter.hpp
ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/lib/ddr-ir/TypePrinter.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/tools/ddrgen/ddrgen.cpp

Previously, `printf` was used directly which triggers a warning from VS2017 about providing a value of type `size_t` for a format `%ul` which expects `unsigned long`.
> printf("union '%s' size(%lu) {\n", type->_name.c_str(), type->_sizeOf);
Using the port library allows us to use the format `%zu` for values of type `size_t`.

Use port library for printing types

---

gc/base/GCExtensionsBase.hpp
gc/base/MemorySubSpace.cpp

Currently JVM goes into idle state, it performs GC only if the amount
of memory allocated in the java heap since last GC cycle is above a
threshold specified by 'gcOnIdleRatio'.
This is very conservative approach. Since JVM is going into idle state
it can be aggressive in doing GC.
With this change JVM would do GC unconditionally everytime it goes into
idle state.
Issue https://github.com/eclipse/openj9/issues/2312

Do GC on idle every time

---

compiler/x/amd64/codegen/MemoryReference.hpp
compiler/x/amd64/codegen/OMRMemoryReference.cpp
compiler/x/amd64/codegen/OMRMemoryReference.hpp
compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/ConstantDataSnippet.hpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/DataSnippet.cpp
compiler/x/codegen/DataSnippet.hpp
compiler/x/codegen/FPBinaryArithmeticAnalyser.cpp
compiler/x/codegen/FPTreeEvaluator.cpp
compiler/x/codegen/MemoryReference.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMemoryReference.cpp
compiler/x/codegen/OMRMemoryReference.hpp
compiler/x/codegen/X86Debug.cpp
compiler/x/i386/codegen/OMRTreeEvaluator.cpp

IA32DataSnippet and IA32ConstantDataSnippet are actually shared by both X86-32 and X86-64 CodeGen;
however, the "IA32" in their names is misleading as "IA32" usually means X86-32.
Therefore, they are renamed to X86DataSnippet and X86ConstantDataSnippet respectively.
Closes #2792

Rename IA32DataSnippet and IA32ConstantDataSnippet

---

compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
fvtest/jitbuildertest/CMakeLists.txt
fvtest/jitbuildertest/CallReturnTest.cpp
fvtest/jitbuildertest/Makefile

Currently if a function returns a type smaller than Int32 the
returned value will be of type Int32 and not Int16 or Int8. I
added some tests that will assert in JitBuilder if the type of
the return value does not match the declaration. This is achieved
by adding the result to a Const<type> of the appropriate type.
The solution is to convert the result if callNode->getDataType()
does not match the defined return type. To make the change simpler
I modified the parameters of convertTo to take a TR::DataType
instead of a TR::IlType.

Fix JitBuilder Call to return the right type for Int8 and Int16

---

compiler/ras/Debug.hpp
compiler/x/codegen/OMRSnippet.cpp

X86ScratchArgHelperCallSnippet has been long deprecated, removing it.

Remove deprecated X86ScratchArgHelperCallSnippet

---

compiler/ilgen/OMRTypeDictionary.cpp
fvtest/jitbuildertest/CMakeLists.txt
fvtest/jitbuildertest/FieldNameTest.cpp
fvtest/jitbuildertest/Makefile

If a struct of union contains fields whose name are a sub string
of another field TypeDictionary will return the wrong field for
one of the names. The fix is to use strcmp instead of strncmp to
ensure the strings are exactly the same.
I have added a simple test for each of these that verifies the
types of each field returned by GetFieldType and GetUnionFieldType
matches the declared type for that field.

Fix Struct/Union fieldName resolution

---

ddr/tools/blob_reader/blob_reader.cpp
gc/base/standard/ConcurrentSweepScheme.cpp

Address diagnostics of the form:
```
error: 'void* memset(void*, int, size_t)' clearing an object with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
```

Fix 'error=class-memaccess' warnings with gcc 8

---

compiler/x/codegen/ConstantDataSnippet.hpp
compiler/x/codegen/DataSnippet.cpp
compiler/x/codegen/DataSnippet.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

The facilities to support arbitrary size data snippet was introduced by #2772;
this changeset exposes APIs to allow users create arbitrary size data snippets.

Allows arbitrary size data snippet on X86

---

compiler/x/codegen/DataSnippet.cpp

Breaks older compilers - use NULL instead.

Remove use of C++11 nullptr

---

gc/base/AllocationInterfaceGeneric.cpp
gc/base/AllocationInterfaceGeneric.hpp
gc/base/ObjectAllocationInterface.cpp
gc/base/ObjectAllocationInterface.hpp
gc/base/TLHAllocationInterface.cpp
gc/base/TLHAllocationInterface.hpp
gc/base/segregated/SegregatedAllocationInterface.cpp
gc/base/segregated/SegregatedAllocationInterface.hpp
gc/include/omrmodroncore.h

reconnectCache() is not called and can be removed from Allocation
Interface family

Remove unused reconnectCache() function

---

compiler/README.md

nullptr is not supported by g++ 4.4.7, the oldest gcc/g++ that OMR supports.

Update documents related to C++11 nullptr

---

compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRSimplifierHandlers.hpp
compiler/optimizer/OMRSimplifierTableEnum.hpp
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/SimplifierFoldAbsNegTest.cpp

Simplified following patterns:
```
1.
node foo                         node foo
[ilfd]abs                  =>    non-negative node bar
non-negative node bar
node foo                         node foo
[ilfd]abs                  =>    [ilfd]neg
negative node bar                negative node bar
* Note that transformation of [fd]abs is default off *
2.
node foo                         node foo
[ilfd]abs                  =>    [ilfd]abs
[ilfd]abs                        node bar
node bar
3.
node foo                         node foo
[ilfd]abs                  =>    [ilfd]abs
[ilfd]neg                        node bar
node bar
4.
node foo                         node foo
dneg                       =>    node bar
dneg
node bar
```

Optimized Simplifier related to abs/neg

---

thread/common/omrthread.c

init_threadParam was asserting that the default value not be 0, which is
incorrect.

Remove incorrect assertion

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRCodeGenerator.hpp

Following two queries are not used in anywhere, removing them:
supportsDebugCounters
incrementEventCounter

Remove unused queries in CodeGen

---

compiler/z/codegen/OMRTreeEvaluator.cpp

When evaluating the following tree we currently have a bug where we do
not generate the actual add because the displacement is too large to be
handled by long displacement instructions:
```
aiadd
aconst 0x784b8500
iconst 28
```
This is specific to 31-bit. The reason is because we do not generate
the LA instruction to add the 28 to the previous memory reference. This
bug was introduced in commit 564fb25 as part of #2882. In fact the code
that was removed here is actually an optimization on 31-bit that does
not exist for 64-bit but it really should.
This will be addressed in a separate Issue which will be opened as part
of the PR containing this commit.

Do not skip generation of LA in aiadd evaluator

---

omrsigcompat/omrsig.cpp
omrsigcompat/omrsig_internal.hpp
port/win32/omrsignal.c
port/win64amd/omrsignal.c

1) **Properly define MSVC_RUNTIME_DLL in omrsig_internal.hpp**
Added a fail-safe to properly define MSVC_RUNTIME_DLL if build files
fail to define MSVC_RUNTIME_DLL. The new CMake build files set
MSVC_RUNTIME_DLL during compilation. But, the old OMR build files don't
set MSVC_RUNTIME_DLL during compilation. This fail-safe is to support
the old build files.
This is identical to the changes in cmake/modules/OmrMsvcRuntime.cmake.
Closes: #2904
2) **omrsig should support SIGBREAK on Windows**
SIGBREAK is a valid signal on Windows. So, omrsig.cpp::validSignalNum
should accept SIGBREAK as a valid signal on Windows.
3) **Enable signal chaining and use omrsig in omrsignal.c [win32/win64amd]**
a) Calls to signal are replaced with OMRSIG_SIGNAL. OMRSIG_SIGNAL deals
with caching application signal …

Signal changes [win32/win64amd]

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/Relocation.cpp
compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/FEBase_t.hpp

This change enables some external relocations to be performed even outside of AOT compiles.

Enable external relocations outside of AOT compiles

---

ddr/tools/ddrgen/CMakeLists.txt
ddr/tools/ddrgen/Makefile

If OMRPORT_OMRSIG_SUPPORT is defined globally, then ddrgen needs to link
to omrsig in order to compile properly.

Properly link omrsig with ddrgen

---

include_core/omrport.h
port/common/omrport.c
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/unix_include/omrcgroup.h
port/win32/omrsysinfo.c

Changes have been done to add api's in OMR Port Library
omrsysinfo_get_handle_cgroup_subsystem_file:
To get the file pointer of the cgroup subsystem file
omrsysinfo_cgroup_is_running_in_container :
To add the status about running in container
omrsysinfo__get_cgroup_entry_list
To get the Linked List which has the Cgroup Subsystem details
These API's can be used to read the Cgroup subsystem file, to check if it is running in a container and also to get the Cgroup Subsystem details from the list
Signed-off-by: bharathappali <bharath.appali@gmail.com>

added api to read the cgroup subsystem file and get value

---

compiler/x/codegen/OMRTreeEvaluator.cpp

conversionAnalyser() should use cg->evaluate() instead of calling the iload evaluator directly.

Fix for incorrect conversionAnalyser evaluation on X86

---

cmake/CheckSourceTree.cmake

The autotools build now outptus omrcfg.h into include core rather than
the top level source directory

CMake: Fix CheckSourceTree

---

ddr/include/ddr/ir/Field.hpp
ddr/include/ddr/ir/Members.hpp
ddr/include/ddr/ir/NamespaceUDT.hpp
ddr/include/ddr/ir/Type.hpp
ddr/include/ddr/ir/TypedefUDT.hpp
ddr/include/ddr/ir/UDT.hpp
ddr/lib/ddr-ir/EnumUDT.cpp
ddr/lib/ddr-ir/Field.cpp
ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-ir/TypedefUDT.cpp
ddr/lib/ddr-ir/UDT.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/lib/ddr-scanner/pdb/PdbScanner.cpp

Only add enum literals to enum types
* Consider the source pattern `typedef enum E { Ea, Eb } E;`: With Visual Studio 2017, the PDB description for the typedef may precede that of the enum. Thus `_typeMap["E"]` will refer to a TypedefUDT object which is not safe to cast to an EnumUDT.
Minor cleanup
* Be careful capturing the size of a typedef: The call to setType() isn't guaranteed to set _aliasedType immediately so it's not safe to dereference it. Typedef types are omitted from the generated blob and superset files so we don't really need to capture the size of typedef types.
* Explicitly construct base types and initialize all fields. The compiler ought to do the same implicitly, but there's no cost to being explicit.
* Use Modifiers::addArrayDimension. This is preferable to accessing …

Enable DDR to work with VS2017

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/codegen/OMRCodeGenerator_inlines.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
fvtest/compilertest/tests/injectors/OpIlInjector.cpp

Two CodeGen queries are introduced:
```
ilOpCodeForIntrinsicMethod()
isIntrinsicMethodSupported()
```
Two CodeGen queries are updated:
```
isILOpCodeSupported()
suppressInliningOfRecognizedMethod()
```

Introduce CodeGen support queries for intrinsics

---

ddr/tools/getmacros
omrmakefiles/rules.mk

Instead, change the sed scripts to use the DDRFILE_BEGIN and DDRFILE_END markers to denote the annotations to scrape.
This is needed since on AIX, xlC throws illegal character warnings for cpp source files during the preprocessor.
This should be merged after the corresponding OpenJ9 change (https://github.com/eclipse/openj9/pull/2762) which will accept the new pattern.

Change getmacros annotation to not use @ symbol

---

compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
compiler/p/codegen/TreeEvaluatorTable.hpp
fvtest/compilertest/tests/PPCOpCodesTest.cpp
fvtest/jitbuildertest/CMakeLists.txt
fvtest/jitbuildertest/Makefile
fvtest/jitbuildertest/NegateTest.cpp

The OMR compiler supports negate opcodes so it makes sense to
provide a Negate service on ILBuilder. This change also includes
a jitbuildertest for negating.

Implement ILBuilder Negate Service

---

compiler/il/OMRDataTypes.cpp
compiler/il/OMRDataTypes.hpp
compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
fvtest/jitbuildertest/CMakeLists.txt
fvtest/jitbuildertest/ConvertBitsTest.cpp
fvtest/jitbuildertest/Makefile

This commit adds the `ConvertBitsTo` service to JitBuilder. It allows an
integer value's bit pattern to be reinterpreted as a floating point
value and vice versa. It maps directly to the following OMR compiler
IL opcodes:
- `ibits2f`
- `fbits2i`
- `lbits2d`
- `dbits2l`
Fixes #2921

Implement JitBuilder bit-wise type conversion services

---

example/glue/ConcurrentMarkingDelegate.hpp
gc/CMakeLists.txt
gc/base/Configuration.hpp
gc/base/GCExtensionsBase.hpp
gc/base/MarkingScheme.cpp
gc/base/standard/ConcurrentGC.cpp
gc/base/standard/ConcurrentGC.hpp
gc/base/standard/ConcurrentGCIncrementalUpdate.cpp
gc/base/standard/ConcurrentGCIncrementalUpdate.hpp
gc/base/standard/ConcurrentGCSATB.cpp
gc/base/standard/ConcurrentGCSATB.hpp
gc/base/standard/ConcurrentSafepointCallback.cpp
gc/base/standard/ConfigurationStandard.cpp
gc/base/standard/ConfigurationStandard.hpp
gc/base/standard/RememberedSetSATB.cpp
gc/base/standard/RememberedSetSATB.hpp
gc/base/standard/WorkPacketsSATB.cpp
gc/base/standard/WorkPacketsSATB.hpp
include_core/omrgcconsts.h

SATB barrier is used in metronome gc policy. We would like to enable it
for other gc polices under option -Xgc:snapshotAtTheBeginningBarrier.
These are initial changes to add the option and start decoupling barrier
code from metronome gc.
Signed-off-by: Evgenia Badyanova <evgeniab@ca.ibm.com>

Initial changes to refactor snapshot at the beginning barrier

---

compiler/z/codegen/InstOpCode.cpp
compiler/z/codegen/OMRInstOpCode.hpp
compiler/z/codegen/OMRInstOpCodeEnum.hpp
compiler/z/codegen/OMRInstOpCodeProperties.hpp
compiler/z/codegen/OMRInstruction.cpp
compiler/z/codegen/OMRInstruction.hpp
compiler/z/codegen/OMRMemoryReference.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390Instruction.cpp
compiler/z/codegen/S390Instruction.hpp
compiler/z/codegen/S390Peephole.cpp

This is the first step forward towards fixing #2848, among other issues. To keep things sane and avoid having several thousand line PRs we do this in lock step. This PR addresses the issue of formats and instruction descriptions, as well as cleanup in the area of unused instructions, incorrectly defined instructions, and automated validation.
The PR includes a set of logical commits addressing the following issues:
- Fix incorrect opcodes
- Add S390OpProp_SetsCC to instructions missing it
- Remove S390OpProp_SetsCC from instructions that shouldn't have it
- Add S390OpProp_BranchOp to instructions missing it
- Update all instruction descriptions and formats
- Deprecate several undefined instruction formats
- Deprecate several unused and undocumented pseudo-instructions
- Update RI …

Update instruction formats and descriptions as defined in PoPs

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/Instruction.hpp
compiler/aarch64/codegen/OMRInstruction.cpp
compiler/aarch64/codegen/OMRInstruction.hpp

This commit adds constructors with RegisterDependencyConditions for
ARM64AdminInstruction.

AArch64: Add constructors for ARM64AdminInstruction

---

compiler/aarch64/codegen/ARM64SystemLinkage.cpp

generateMemSrcInstruction() was used in code generation for loading
from memory in createEpilogue() by mistake.  Replacing with
generateTrg1MemInstruction().

AArch64: Fix createEpilogue() code

---

compiler/aarch64/codegen/OMRInstruction.cpp
compiler/aarch64/codegen/OMRInstruction.hpp
compiler/aarch64/codegen/OMRMemoryReference.cpp
compiler/aarch64/codegen/OMRMemoryReference.hpp

This commit implements assignRegisters() in OMRMemoryReference
for aarch64.

AArch64: Implement OMRMemoryReference::assignRegisters()

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

This commit implements utility functions in GenerateInstructions.*
for generating CMP (immediate) and TST (immediate) instructions
for aarch64.

AArch64: Add utility functions for generating CMP and TST instructions

---

compiler/compile/OMRCompilation.hpp
compiler/x/codegen/X86BinaryEncoding.cpp

- Relocate `prepareForOSR` helper address. This is needed to support
OSR (On Stack Replacement) in JITaaS.
- Guard `TR_DataAddress` relocation for `AMD64RegImm64SymInstruction`,
perform only if statics need to be relocated. This is needed because
the relocation relies on the static field being resolved, which is
not true in JITaaS mode.
Signed-off-by: Dmitry Ten <Dmitry.Ten@ibm.com>

Minor OpenJ9 project specific changes to relocations

---

compiler/compile/OMRCompilation.hpp

aotMethodCodeStart has been renamed to relocatableMethodCodeStart
See PR#2913 for more detail

Remove deprecated API aotMethodCodeStart

---

compiler/aarch64/codegen/ARM64Instruction.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp

This commit implements functions in ARM64Instruction, such as
assignRegisters(), refsRegister(), etc., for aarch64.
This depends on changes in #2914.

AArch64: Implement assignRegisters(), etc. in ARM64Instruction

---

compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp

1. Optimized simple atomic operations to avoid allocating register when unnecessary.
2. Change the helper inlineAtomicMemoryUpdate() to a static local function to ease C++ compilation.

Optimized atomic memory update inlining on X86

---

compiler/aarch64/codegen/OMRCodeGenerator.cpp
compiler/aarch64/codegen/OMRCodeGenerator.hpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
compiler/aarch64/codegen/OMRInstruction.hpp
compiler/aarch64/codegen/OMRMachine.cpp
compiler/aarch64/codegen/OMRMachine.hpp

This commit implements functions such as beginInstructionSelection(),
and doRegisterAssignment() in OMRCodeGenerator for aarch64.

AArch64: Implement OMRCodeGenerator functions

---

compiler/z/codegen/ControlFlowEvaluator.cpp

When comparing long values in register pairs, only the high word of the registers should do a signed comparison. The low words should be evaluated logically as the high word comparison would have indicated if there was a sign difference between the two.

Use logical comparison in minEvaluator

---

compiler/codegen/Relocation.cpp
compiler/runtime/Runtime.hpp

This kind can be used in downstream projects to describe a relocation
for JIT-compiled code that contains a pointer to a code sequence that
transitions control into an interpreter.

Add TR_J2IVirtualThunkPointer relocation kind

---

ddr/include/ddr/macros/MacroInfo.hpp
ddr/include/ddr/scanner/dwarf/AixSymbolTableParser.hpp
ddr/lib/ddr-scanner/Scanner.cpp
ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/tools/getmacros
omrmakefiles/rules.aix.mk

This pull request, in conjunction with the corresponding OpenJ9 pull request [#2309](https://github.com/eclipse/openj9/pull/2309), enables DDR on AIX, addressing eclipse/openj9#1769. This PR should be delivered before the
OpenJ9 PR.
The PR includes the following changes:
* make _typeName field in MacroInfo non const since xlc on AIX fails to generate a copy assignment operator for const strings
* replace string.front() with array access in Scanner since xlc does not support this method 
* replace unsupported xargs command on AIX
* initialize die sibling to NULL in AixSymbolTableParser.cpp
* in AixSymbolTableParser.cpp, add missing DW_AT_data_member_location to fields parsed
* fix missing digit in a number matching pattern in AixSymbolTableParser.cpp
* fix AixSymbolTableParser incorrectly …

Enable DDR on AIX

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/il/OMRNode.cpp

It's good practice to query on opcode properties rather than checking
individual opcode value one by one when working on a group of opcodes.
With this change, newly added read barrier opcode is included without
explicitly adding the new opcode value to the checking condition.
This is part of #2812 

Change checking opcode to queries on properties

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

Currently, the initial CodeCacheHashEntrySlab is allocated before the
CodeCache object is allocated and then passed in as a parameter to the
CodeCache object initialization.  This is done mainly for the reasons
discussed in Issue #2470.
This commit moves the allocation of the CodeCacheHashEntrySlab object
and the first slab to the CodeCache::initialize() function.  Handling
of allocation failures has also been adjusted to accommodate the new
location to ensure memory is reclaimed.
This change is necessary to consolidate trampoline artifact creation
to a single location to facilitate further refactoring in this area.

Move allocation of CodeCacheHashEntrySlab to CodeCache initialization

---

README.md

Travis: Update OMR README
-Add breakdown of Travis CI matrix builds to main OMR README
-Arrange Builds by Platform in OMR README
[skip ci]

Update OMR README with Travis Matrix Builds

---

compiler/aarch64/codegen/TreeEvaluatorTable.hpp

Add evaluators of rdbar/rdbari opcodes to TreeEvaluatorTable.hpp for
aarch64.  The opcodes were added to other platforms by #2875.

AArch64: Add rdbar/rdbari opcodes

---

compiler/env/TRMemory.hpp
compiler/env/TRPersistentMemory.cpp

The provided jitConfig is not used for anything any longer in the TRMemory
hierarchy.  Prepare to remove it.
This commit adds new constructors to the TRMemory hierarchy that do not take
a jitConfig argument to facilitate necessary changes to downstream projects.
The constructors that take a jitConfig will be removed once all known
downstream projects have been modified to use the new constructors without
jitConfig.

Remove TRMemory dependence on jitConfig

---

compiler/ras/Debug.cpp

The name of TR_referenceArrayCopy is renamed as jitReferenceArrayCopy,
to matching the naming scheme of other JIT helpers.

Update name of TR_referenceArrayCopy

---

compiler/aarch64/codegen/UnaryEvaluator.cpp

This commit implements skeleton functions of UnaryEvaluator.cpp for
aarch64.

AArch64: Initial version of UnaryEvaluator.cpp

---

gc/base/segregated/MemorySubSpaceSegregated.cpp
gc/base/segregated/MemorySubSpaceSegregated.hpp

While compiling **OpenJ9** with **Clang 9.1.0** on **OSX**, the following error was
seen:
```
In file included from MemorySubSpaceMetronome.cpp:39:
./MemorySubSpaceMetronome.hpp:69:8: error:
'MM_MemorySubSpaceMetronome::collect' hides overloaded virtual function
[-Werror,-Woverloaded-virtual]
void collect(MM_EnvironmentBase *env, MM_GCCode gcCode);
^
../omr/gc/base/segregated/MemorySubSpaceSegregated.hpp:92:15: note:
hidden overloaded virtual function
'MM_MemorySubSpaceSegregated::collect' declared here: type mismatch at
2nd parameter ('MM_AllocateDescription *' vs 'MM_GCCode')
virtual void collect(MM_EnvironmentBase *env,
MM_AllocateDescription *allocDescription);
```
The definition of `collect` differs in **MemorySubSpaceSegregated** (base
class) and **MemorySubSpaceMetronome** (derived …

Fix overloaded virtual function hidden error

---

port/common/omrstr.c

This fixes the failure seen in https://ci.adoptopenjdk.net/job/openjdk11_openj9_build_ppc64le_linux/11/console
```
/usr/include/bits/string3.h:81:7: error: call to ‘__warn_memset_zero_len’ declared with attribute warning: memset used with constant zero length parameter; this could be due to transposed parameters [-Werror]
__warn_memset_zero_len ();
^~~~~~~~~~~~~~~~~~~~~~~~~
```

Avoid uses of memset() with a constant zero length

---

compiler/env/OMRPersistentInfo.hpp

Not used in OMR nor any known downstream project.

Delete unneeded cache of CodeCacheManager from PersistentInfo

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/ARM64SystemLinkage.cpp
compiler/aarch64/codegen/OMRMemoryReference.cpp
compiler/aarch64/codegen/OMRMemoryReference.hpp

This commit implements some more cases for estimateBinaryLength()
in OMRMemoryReference for aarch64.

AArch64: Implement OMRMemoryReference::estimateBinaryLength()

---

port/common/omrfile.c

The return values are `EsIsDir` and `EsIsFile` (with an uppercase 'I' instead of a lowercase 'l').
[ci skip] comment change only

Fix typos in documentation of return values

---

compiler/ilgen/OMRIlType.cpp

Use correct alignment for 32-bit and 64-bit targets.

Fix address type alignment in OMRIlTypes

---

gc/base/GCExtensionsBase.hpp
gc/base/WorkPackets.hpp
gc/base/WorkStack.cpp
gc/base/WorkStack.hpp
gc/stats/CopyForwardStatsCore.hpp

CopyForwardHybrid is hybrid mode of CopyForward Scheme that 
GC can run both copyforward and markcompact on the collection set
simultaneously (for balanced PGC only). During precollection, 
GC can reserve some regions for markcompact only(non evacuated 
regions -- such as jni critical regions) and copyforward for 
the rest of collection set. 
- new global flag tarokEnableCopyForwardHybrid for indicating if
CopyForwardHybrid mode is on, default is off.
- new global test option fvtest_forceCopyForwardHybridRatio, which 
can set the percentage of collection set to be reserved for markcompact.
- update workpackets for allow synchronizing with the threads pull
the work from another queue(such as copycache).
-  add new nonEvacuateRegionCount in CopyForwardStats for verbose
gc reporting. …

Change for supporting CopyForwardHybrid

---

compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/MaxMinTest.cpp

This pull request improves the `maxMinHelper` evaluator
in Z codegen in 3 ways.
- Add guards for z10  in the evaluator and lower and disable max/min optimisations on unsupported platforms
- Rewrites the evaluator for lmin and lmax when using register pairs
- Add Tril tests to capture corner cases for this evaluator

Improve maxMinHelper in z/codegen 

---

omrmakefiles/rules.osx.mk

On OSX, -rpath,\\$$ORIGIN doesn't work. -rpath needs to correspond to
either @executable_path, @loader_path or some other path. More
information can be seen in the man pages of dyld. I have chosen to set
rpath as "-rpath,@loader_path/.". @loader_path points to the directory
where dylib being loaded exists.
When naming dylibs, @rpath/ should be appended to dylib names. Example:
@rpath/libomrsig.dylib. Appending @rpath to the dylib name instructs the
dynamic linker to search the list of run paths for the dylib.
Reference:
https://wincent.com/wiki/%40executable_path%2C_%40load_path_and_%40rpath

Fix RPATH and dylib install_name on OSX

---

jitbuilder/build/files/target/aarch64.mk

This commit adds some files that have been missing to
jitbuilder/build/files/target/aarch64.mk.

AArch64: Add missing files in aarch64.mk for jitbuilder

---

compiler/aarch64/codegen/ARM64Instruction.hpp
jitbuilder/build/files/target/aarch64.mk

This commit adds ARM64Instruction.cpp to
jitbuilder/build/files/target/aarch64.mk, and also fixes mismatch
between ARM64Instruction.hpp and ARM64Instruction.cpp.

AArch64: Add ARM64Instruction.cpp to aarch64.mk for jitbuilder

---

compiler/ras/Debug.cpp

This commit resolves the duplicated definition of
print(TR::FILE *, TR::Instruction *) in
compiler/ras/Debug.cpp and compiler/aarch64/codegen/ARM64Debug.cpp.

AArch64: Duplicated definition of print() in Debug class

---

gc/base/MemorySubSpaceFlat.cpp
gc/base/MemorySubSpaceGenerational.cpp
gc/base/MemorySubSpaceGeneric.cpp
gc/base/MemorySubSpaceSemiSpace.cpp
gc/base/MemorySubSpaceSemiSpace.hpp
gc/base/j9mm.tdf

Fixing a regression where an unnecessary scavenge cycle would be
triggered right after aborted scavenge (and percolate global GC), and
only then allocation in Nursery would be restored.
Typically, it was a really minor perf penalty (relative to already
expensive but also very infrequent aborted handling). But in some very
malicious cases if a subsequnt Scavenge also aborts, it would cause a
whole series of frequent aborts. 
The regression was introduced as a part of aborted Concurrent Scavenger
handling, but would affect just the standard (non-CS) Scavenger.
Also adding a lot of trace points in SubSpace allocate path.
SubSpace Generic path which is frequently executed (like TLH refresh),
has the lower trace level of 3 (hence, won't show by default), while the
rest of them, which are …

Restore Nursery allocation after aborted Scavenge

---

compiler/codegen/OMRCodeGenPhase.cpp

Guarded Storage is a Z-only feature and hence should be guarded with
TR::Compiler->target.cpu.isZ().

Fix for missing platform check for Guarded Storage

---

compiler/env/OMRCPU.cpp

This commit adds code for setting arch_arm64 to _majorArch in
OMRCPU.cpp.

AArch64: Enable arch_arm64 in OMRCPU.cpp

---

compiler/aarch64/codegen/OMRMemoryReference.cpp

This commit fixes coding errors in three functions for aarch64.

AArch64: Fix isRegisterOffsetInstruction(), etc.

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/ARM64ShiftCode.hpp
compiler/aarch64/codegen/OMRCodeGenerator.hpp
compiler/aarch64/codegen/OMRTreeEvaluator.cpp

This commit implements loadConstant32() and loadConstant64()
utility functions for loading a integer value to a register for
aarch64.

AArch64: Implement loadConstant32() and loadConstant64()

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

This commit implements some more utility functions in
GenerateInstructions.* for aarch64 for generating instructions
that take xzr as one of target/source registers, in addition to the
functions added in #2888.

AArch64: Add utility functions for generating MOV, MUL, etc.

---

include_core/AtomicSupport.hpp

bitAndU32 was there, bitOrU32 was not for some reason.

Add bitOrU32 to AtomicSupport.hpp

---

compiler/env/OMRArithEnv.hpp
compiler/il/ILOpCodeProperties.hpp
compiler/il/OMRNode_inlines.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRSimplifierHandlers.hpp
compiler/optimizer/OMRSimplifierTableEnum.hpp
compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/codegen/FPTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp
compiler/x/i386/codegen/TreeEvaluatorTable.hpp
fvtest/compilertest/tests/OpCodesTest.cpp
fvtest/compilertest/tests/OpCodesTest.hpp
fvtest/compilertest/tests/X86OpCodesTest.cpp

IL OpCode fsqrt and dsqrt are now supported by X86, including evaluators, simplifiers and tests.

Introduce support for sqrt IL OpCode on X86

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/ilgen/OMRIlBuilder.cpp
compiler/ras/Debug.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp

In support of #2958 we implement the existing intrinsics for Z. Another follow-up PR will address the new intrinsics which are proposed in #2174.
- Implement Z codegen support for several atomic symbols
- Document atomic symbol semantics
- Document supportsAtomicAdd and introduce supportsAtomicSwap 
Issue: #2958

Implement atomic add and swap codegen support for Z

---

compiler/p/codegen/OMRInstOpCodeEnum.hpp
compiler/p/codegen/OpBinary.cpp
compiler/p/codegen/OpProperties.cpp
compiler/p/codegen/PPCOps.ops
compiler/ras/PPCOpNames.cpp

The vbpermq instruction was added in Power 8 and allows performing a
bitwise permutation on a vector, similar to how vperm allows a bytewise
permutation.
[ci skip]

Enable vbpermq support in the Power codegen

---

compiler/optimizer/OMRSimplifierHandlers.cpp

Type information getChild(0) doesn't seem to be propagated properly
when compiling with xlC under AIX. Making the the type of child
explicit seems succificient to get compiled.

Fix for compilation error under certain compilers

---

fvtest/gctest/GCConfigTest.cpp
gc/startup/omrgcstartup.cpp
gc/startup/omrgcstartup.hpp

In the GC tests, If the collector fails to initialize, then the testcase will abort before a VM thread is attached. Unfortunately, some of the GC shutdown APIs require a valid thread.  This dependency is bogus--the thread is not really needed. This PR adds some new shutdown APIs that instead take an OMR VM. With these new APIs, the tests can bring everything down safely, even when the test aborts very early.
This error condition was exposed when trying to run testing for GC features that are disabled. This is bad--obviously a scavenger test will fail when the scavenger is ifdef'd out. This PR moves the offending tests under the relevant feature ifdefs, so we only run tests when they're actually supported.
/cc @youngar @charliegracie

Clean up GC test shutdown; don't run GC tests for disabled features

---

fvtest/jitbuildertest/ConvertBitsTest.cpp

Comparisons such as ASSERT_EQ(0, double2long(0.0)) fail to compile
on gcc>=4.9.  Use the UINT64_C() macro to explicitly specify sign
and bit-width.
Signed-off-by: Boris Shingarov <shingarov@labware.com>

Restore building on gcc>=4.9

---

compiler/z/codegen/InstOpCode.cpp
compiler/z/codegen/OMRInstOpCode.hpp

Add two new static opCode getter APIs for evaluators to get CRJ/CGRJ and AHIK/AGHIK.

Add new static get opCode APIs for code generator evaluators

---

cmake/modules/platform/os/osx.cmake
fvtest/porttest/omrmemTest.cpp
port/common/omrmemtag.c

**1) Allow memory to be mapped below 4GB on OSX**
On OSX 64-bit, linker sets page zero size to 4GB. This prevents memory
to be mapped below 4GB.
On OSX 32-bit, page zero size is set to 4KB by default.
This change will set page zero size to 4KB on 64-bit architectures. This
will allow memory to be mapped below 4GB.
**2) Enable support for compressedrefs feature in OMR**
For compressedrefs, memory needs to be mapped below 4GB.
Currently, code for allocating/mapping memory below 4GB is disabled on
OSX.
Specifying -pagezero_size <SIZE> while creating main executables will
allow us to map memory below 4GB.
Thus, re-enabling code for allocating/mapping memory below 4GB:
omrmem_allocate_memory32 and supporting test code.

Compressedrefs - Map memory below 4GB - OSX

---

compiler/optimizer/ValuePropagationCommon.cpp

These nodes are internal pointers and flagging them as such prevents
code generators from including their registers in GC maps.
generateArrayletAddressTree() is left unchanged because it's unclear
whether the leaf element address should be considered an internal
pointer, but this function is currently unused anyhow: it is only called
when generateArraylets(), which with hybrid arraylets is always false.
Fixes #3040

Set aladd internal pointer flag for VP arraycopy

---

port/unix/omrsysinfo.c

This is required for Java runtime compatibility.
Replaces https://github.com/eclipse/omr/pull/3052

Map OS name "Darwin" to "Mac OS X"

---

gc/include/omrmm.hdf
gc/verbose/VerboseHandlerOutput.cpp

Verbose GC change, 3 cases
1) CS enabled, running interpreted or Jitted with S/W based Read Barrier:
```
<attribute name="concurrentScavenger" value="enabled" />
```
2) CS enabled, running Jitted with H/W based Read Barrier:
```
<attribute name="concurrentScavenger" value="enabled, H/W assisted" />
```
3) CS disabled, the line is not reported

Report if CS is H/W assisted

---

compiler/x/codegen/OMRTreeEvaluator.cpp

Comment above indirectCallEvaluator was incorrect, fixing.

Correct the comment of indirectCallEvaluator on X86

---

compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/i386/codegen/TreeEvaluatorTable.hpp

Comments in tree evaluator tables are annoyingly misaligned, fixing.

Align comments in tree evaluator tables on X86

---

.travis.yml
scripts/build-on-travis.sh

The Linux x86-64 compressed references testing has moved to the
OMR CI so the testing can be removed from Travis.

Remove Linux x86-64 compressed references testing

---

compiler/control/OMROptions.cpp

Remove final mention of Shrink Wrapping from OMR.
Issue: #2107

Deprecate ShrinkWrapping - Part III

---

gc/base/GCExtensionsBase.hpp

Renaming flag S/W Evacuate RB to S/W RangeCheck RB. 
Evacuate is an action that is required by RB in Concurrent Scavenger.
It's always executed in software. What has alternative implementation in
S/W vs H/W is the trigger mechanism, which is the range check against
Evacuate area boundaries (or a set of areas).
Temporarily, keeping the old variable and accessor, until downstream
projects are updated to use the new ones.

Software RangeCheck  Read Barrier

---

.travis.yml
scripts/build-on-travis.sh

The recently created arm and aarch64 jobs on the OMR CI supersede
the Travis jobs so they are being removed.

Remove arm and aarch64 builds from Travis

---

gc/base/GCExtensionsBase.hpp

Do heap memory alignments reqiured for GS in case if CS runs on
supported HW only. Request of using Software Barriers overwrites it.

Align heap for GS if necessary only

---

port/osx/omrsignal_context.c
port/unix/omrsignal.c

The code was returning addresses into a _copy_ of parts of the thread state eliminating the possibility that a signal handler might update that state before allowing a thread to resume.
An example modification is in OpenJ9's handler for division by zero which wants to alter the instruction pointer to a trap handler, but writing to that copy of thread state is ineffective.

Fix OSX implementation of omrsig_info()

---

compiler/compile/OMRSymbolReferenceTable.cpp

This commit is for J9_PROJECT_SPECIFIC code. With the new Symbol
Validation Manager code, it is possible for the compiler to create a
class symbol with cpIndex -1 under AOT even if the class is not loaded
by the system class loader. However, as the code stands, this will
trigger a TR_ASSERT_FATAL. This commit ensures that the code that checks
for the system class loader only runs when the SVM is not enabled.
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

Guard code with SVM check

---

compiler/aarch64/codegen/OMRRegisterDependency.cpp

This commit implements assignRegisters() function in
TR_ARM64RegisterDependencyGroup.

AArch64: Implement TR_ARM64RegisterDependencyGroup::assignRegisters()

---

compiler/optimizer/Inliner.cpp

In findCallTargetUsingArgumentPreexistence(), it is possible for
getResolvedMethod() to fail to find the target. In this case, we should
simply skip adding the target, as already happens in builds without
assertions.

Remove bogus assertion in TR_IndirectCallSite

---

compiler/aarch64/CMakeLists.txt
compiler/aarch64/env/OMRDebugEnv.cpp
compiler/ras/Debug.cpp
jitbuilder/build/files/target/aarch64.mk

This commit adds some more code for aarch64 in the common Debug.cpp
and related files.

AArch64: Add support for ARM64 in Debug.cpp

---

fvtest/compilertriltest/SimplifierFoldAbsNegTest.cpp

The 'SimpifierFoldAbsNegTest' unit test from 'compilertriltest' contains
an initialization block for a vector of floats:
std::vector<  float> fTestData =
{ 0, 1, 2, -1, -2, 3.14, -3.14,
std::numeric_limits<float>::min(), std::numeric_limits<float>::min() };
During a compilation with MSVC the following errors appears:
.\..\fvtest\compilertriltest\SimplifierFoldAbsNegTest.cpp(45): error
C2398: Element '6': conversion from 'double' to 'float' requires a
narrowing conversion
..\..\fvtest\compilertriltest\SimplifierFoldAbsNegTest.cpp(45): error
C2398: Element '7': conversion from 'double' to 'float' requires a
narrowing conversion
Literals '3.14' and '-3.14' can be represented as well 'double' as
'float', the 'f' suffix after the literal must be present to fix the
compilation error. …

Fix MSVC error C2398 requires narrowing conversion

---

gc/base/GCExtensionsBase.hpp
gc/include/omrmm.hdf
gc/verbose/VerboseHandlerOutput.cpp

Slighly modify the verbose GC stanza where we state if Concurrent
Scavenger is enabled:
1) on H/W capable platforms we will state one of two:
enabled, with H/W assistance
enabled, without H/W assistance
2) on plaforms with no H/W assistance we will just state:
enabled
3) if CS is not enabled, regardless of platform, the stanza is not
issued
Since there is an overlap, also piggybacking to this change removal of
unused softwareEvacuateReadBarrier flag and retirment of jitLoaded field
in Initialized hook.

State explicitly CS witout H/W assistance

---

port/common/omrcuda.cpp

According to [1], CUDA Toolkit version 10.0 was released in September 2018.
[1] https://developer.nvidia.com/cuda-toolkit-archive

Add support for CUDA 10.0

---

gc/base/Dispatcher.cpp
gc/base/Dispatcher.hpp
gc/base/ParallelDispatcher.cpp
gc/base/ParallelDispatcher.hpp

Fixing 2 problems, when overriding thread count for a task (via run()
API), which may occur in a scenario when initial heap size is so small
to cause an early GC before even all GC threads are up and running: 
1) major: the overriding value should be no bigger than
_threadCount/_adjustedThreadCount, since there might not be
more slave threads available, yet. Otherwise, the task would hang
waiting for non-existant threads to complete.
2) minor: do not record the overriding value into Dispatcher's
_threadCount, since early at startup _threadCount might still be
constructed. Just pass the value to the task. Otherwise, the final
constructed value could be lost and subsequent GCs may run with reduced
GC counts.
Temporarily, keeping both old and new variant of prepareThreadsForTask()
API until …

Explicit thread count for parallel GC task

---

compiler/compile/OSRData.cpp

If TR_ScratchBufferInfo::writeToBuffer is inlined, it appears to expose
a bug in code generated by the IBM xlC compiler on z-Series.  The same
(or a similar) problem was previously seen on p-Series compiling with
xlC, and the work-around was to avoid inlining when compiling with xlC
on POWER.  This extends the same work-around to z compiling with xlC
Fixes: #3084

Avoid inlining TR_ScratchBufferInfo::writeToBuffer

---

gc/verbose/VerboseHandlerOutput.cpp

There is no local extensions declared in Initialized staza handler. Use
the class member instead.

Use _extensions in VGC handler

---

gc/base/standard/ConcurrentGC.cpp

GC threads at startup act briefly as mutators since they allocate from
heap (various thread specific objects). Before transitioning the thread
type to its specific GC role, they need to flush any GC specific caches,
as any mutators do.
Specifically, in Concurrent Scavenger, if a GC thread is created during
a very early cycle, it may trigger a read barrier and create a copy
cache. This cache has to by flushed (to scan queue for further scanning
in final STW GC phase).
This problem has already been addressed for Master and Slave GC threads
(https://github.com/eclipse/omr/pull/2696). Here Concurrent Marking
Background threads are treated with the identical fix. 

Flush GC caches for concurrent marker thread

---

compiler/z/codegen/OMRCodeGenerator.cpp

ValuePropagation in OMR uses this flag to generate specialized trees for array copy direction if this flag is set. Currently Z platform expects optimizer to generate test for array copy direction. Set this flag in Z CodeGenerator.

Set Specialized for arraycopy direction on IBM Z

---

README.md

CI: Update OMR README
-Remove old, removed, Travis CI Matrix Builds
-Add in new Eclipse OMR Jenkins CI Builds for AArch64 and ARM
-Add other missing Eclipse OMR Jenkins Builds
[skip ci]

CI Update OMR README

---

gc/base/Dispatcher.cpp
gc/base/Dispatcher.hpp
gc/base/ParallelDispatcher.hpp

Now, that there are no more users of old prepareThreadsForTask()
(without explicit threadCount), remove it.

Remove unused ParallelDispatcher API

---

.gitignore

Visual Studio is now providing a useful integration with CMake.
The configuration of an CMake environment is stored in a CMakeSettings.json
file. The file is developer-specific, so it must be ignored by Git.
CLion is a cross-platform C/C++ IDE from JetBrains (they are famous in
the Java community as the authors of IntelliJ IDEA).
The configuration of a CLion project is stored in an .idea folder
inside the root of the project. The configuration is developer-specific,
so the folder must be ignored by Git.
no-ci

Ignore VS and CLion specifics

---

compiler/aarch64/codegen/OMRInstruction.cpp
compiler/aarch64/codegen/OMRRegisterDependency.cpp
compiler/aarch64/codegen/OMRRegisterDependency.hpp

The totalUseCounts of registers in RegisterDependencyConditions were
not counted properly.  This commit adds a new function to
RegisterDependencyConditions, and calls to the function.

AArch64: Add incRegisterTotalUseCounts() to RegisterDependencyConditions

---

compiler/aarch64/codegen/OMRMemoryReference.cpp

OMRMemoryReference::generateBinaryEncoding() had wrong code for
embedding MemoryDataRegister in instruction binary encoding.
This commit removes those lines.

AArch64: Remove code related to MemoryDataRegister from OMRMemoryReference

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
compiler/ras/Debug.hpp

This commit adds ARM64RegBranchInstruction for aarch64 branch
instructions that take a register as the target address.
It also introduces a new opcode that represents a return from a method,
which is separate from the opcode for aarch64 machine instruction "ret".

AArch64: Add ARM64RegBranchInstruction for br/blr/ret

---

compiler/aarch64/codegen/OMRCodeGenerator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp
compiler/aarch64/codegen/UnaryEvaluator.cpp

This commit implements some evaluators in UnaryEvaluator.cpp,
such as iconstEvaluator() and inegEvaluator(), for aarch64.
This depends on #2963, #2964, and #2976.

AArch64: Implement iconstEvaluator() and some others

---

compiler/control/OMROptions.cpp

A lot of the following compilation errors occur on OMROptions.cpp during
compilation with Clang 8:
..\..\compiler\control\OMROptions.cpp(760,94):  error: constant expression evaluates to -2147483648 which cannot be narrowed to type 'uintptrj_t' (aka 'unsigned long long') [-Wc++11-narrowing]
{"enableTraps", "C\tenable trap instructions", RESET_OPTION_BIT(TR_DisableTraps), "F"},
The reason is a narrowing the latest component of the RESET_OPTION_BIT
macro '((x)&~TR_OWM)' to the 'uintptrj_t' aka
'unsigned long long' type. The expression must be explicitly converted
to 'uintptrj_t'.
Closes: #3121

Fix cannot be narrowed to type 'uintptrj_t' error

---

compiler/aarch64/codegen/ARM64SystemLinkage.cpp
compiler/aarch64/codegen/ControlFlowEvaluator.cpp
compiler/aarch64/codegen/OMRCodeGenerator.cpp

This commit fixes the code generation of return for aarch64,
separating the machine instruction "ret" and the abstract representation
of return (ARM64AdminInstruction(TR::InstOpCode::retn)).

AArch64: Fix code generation of return

---

compiler/arm/codegen/OMRCodeGenerator.hpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/codegen/OMRInstruction.hpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRCodeGenerator.hpp

Remove 'no virt' comments from code generators
This commit deletes all occurrences of the 'no virt'  comment in all files since they are no longer relevant, useful, or correct in some cases
Closes: #1398
Signed-off-by: Joannah Nanjekye <nanjekyejoannah@gmail.com>

Remove 'no virt' comments from code generators

---

compiler/il/symbol/OMRSymbol_inlines.hpp
compiler/z/codegen/BinaryAnalyser.cpp
compiler/z/codegen/BinaryCommutativeAnalyser.cpp
compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/CompareAnalyser.cpp
compiler/z/codegen/ConstantDataSnippet.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/FPTreeEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRInstruction.cpp
compiler/z/codegen/OMRInstruction.hpp
compiler/z/codegen/OMRLinkage.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OpMemToMem.cpp
compiler/z/codegen/OpMemToMem.hpp
compiler/z/codegen/S390Debug.cpp
compiler/z/codegen/S390Evaluator.hpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390Peephole.cpp

Set ICF flags on labels instead of instructions in the Z codegen
and deprecate the usage of ICF flags on instructions to prevent
future use.
Closes: #2833

Set ICF flags on labels instead of instructions in the Z codegen

---

gc/base/standard/Scavenger.cpp

For Concurrent Scavenger, on weak memory model, ensure that a candidate
copy is visible before (potentially) winning forwarding.
This covers the more common case of small object forwarding where we
allow duplicates (no cooperative copying of long objects).

Store sync before forwarding in CS

---

compiler/z/codegen/FPTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

This patch replaces TR::InstOpCode::LA with TR::InstOpCode::XR or
TR::InstOpCode::XGR when loading 0 into a register since XOR operation
is faster. Also, the LHI instruction is used instead of LA when loading
small constants. See issue #3047.
Closes: #3047
Signed-off-by: Muzaffar Auhammud <muzaffar@cyberstorm.mu>

Remove usages of LA instruction when loading constants in Z codegen

---

compiler/optimizer/DeadTreesElimination.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/OMRSimplifierHelpers.cpp
compiler/optimizer/ValuePropagationTable.hpp
compiler/ras/Tree.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

Remove the following unused packed decimal opCode from the codebase:
pddivRem, pduexp, pdexp, pdfix, pdcheck, pdshlPreserveSign, and
pdshrPreserveSign.

Remove unused packed decimal IL OpCode

---

compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
compiler/aarch64/codegen/OpBinary.cpp

Some binary encoding values mismatched because of the mismatch in opcodes.
Those values are being updated. 'B' and 'BL' instructions are being added
to ORMInstOpCodeEnum.cpp and OpBinary.cpp
Fixes #3017 

AArch64: Binary Encoding Fix and Addition of 'B' and 'BL' Instructions

---

include_core/omrport.h
port/common/omrport.c
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

This PR adds the Iterator mechanism API's for reading and getting the Cgroup metrics which would be useful for any runtime to get the cgroup metrics.
**omrsysinfo_cgroup_subsystem_iterator_init :**
Initiates the iterator with respective to the cgroup subsystem.
**omrsysinfo_cgroup_subsystem_iterator_hasNext :**
Checks if any other metrics are there to be read.
**omrsysinfo_cgroup_subsystem_iterator_next :**
Reads the cgroup susbsystem file and returns the value of the metric.
This PR removes the API `omrsysinfo_cgroup_get_handle_subsystem_file` which is no longer required.

Added the iterator mechanism for getting the Cgroup metrics in OMR

---

include_core/omrgcconsts.h

Rename the barrier type to range check, which represents the trigger
criteria, rather then the action that barrier will perform. Evacuate is
a specific action performed by Concurrent Scavenger read barrier. Some
other GCs or profiling/debug tools could use the same read barrier
trigger but with its own action (that is not evacuate).
Temporarily keeping the old types, until downstream projects (OpenJ9)
are updated to use the new type.

Rename evacuate read barrier type

---

port/unix/omrsysinfo.c

The cast serves no purpose and causes a compile error on some
compilers.

Remove unnecessary cast

---

include_core/omrgcconsts.h

Now that Evacuate RB type is not used any more, remove it.
Related changes:
https://github.com/eclipse/omr/pull/3132
https://github.com/eclipse/openj9/pull/3507

Remove obsolete RB type

---

port/unix/omrsysinfo.c

This fix provides the optimization like removing the for loop which
performs increment operation on a pointer till certain level and
incrementing the pointer directly to desired level.
Signed-off-by: bharathappali <bharath.appali@gmail.com>

Removes unnecessary loop & makes pointer incremented to certain level

---

glue/configure_includes/configure_linux_ztpf_390.mk

Pull Request 2406 changed the way platforms that require
cross-configuration are configured. New directives need to be specified
to control OMR Tool build options such as type of compiler.

 z/TPF OMR configuration update

---

port/unix/omrsysinfo.c

A semi-recent update in the omrsysinfo segment added CGroup calls in the
retrieveLinuxCgroupMemoryStats function.  TPF currently doesn't support
CGroup calls and needs guard macros around such calls so that it can be
configured out during TPF builds.

Disable CGroup Calls in omrsysinfo for TPF

---

ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/tools/getmacros
omrmakefiles/rules.osx.mk

The following changes will enable ddrgen to create the generated DDR
classes on OSX.
Create dSYM bundle for OMR shared libraries and dont require .dSYM
extension in parser since the bundle is passed in as the .dbg file.
Dwarfdump displays flag attribute values as a string true/false on OSX
instead of 1 or 0. Parse the value as a string and fall back to looking
for 1 or 0 if it doesn't find either "true" or "false" string.
Parse bit offset field for OSX since the data member location field is
missing if the field is a bit field, and instead we look at the
data_bit_offset field.
Include unknown dies in die tree when parsing dwarfdump output, since
there is an issue with parsing based on last indentation with parent
dies that the parser does not recognize. We then remove the unknown
dies …

Get ddrgen working on OSX

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/il/Aliases.cpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/il/OMRNode_inlines.hpp
compiler/optimizer/Inliner.cpp
compiler/ras/Debug.cpp
doc/compiler/osr/OSR.md

- Add a helper named osrFearPointHelper to mark an OSR fear point, a
place that has been optimized with runtime assumptions and requires
protection of OSR points. This helper helps to locate actual fear
points, which as part of the program can be optimized, and allows the
separation of OSR dependent optimization and OSR guard insertion.
- Add a helper named potentialOSRPointHelper to serve as a marker of OSR
points. Currently, OSR points consist of calls, asyncchecks and
monitor enters. As part of the program, they can be optimized and no
longer be identified as OSR points. However, places where they reside
may still be OSR possible. This helper works as a bookkeeping tool to
track place that are OSR possible.
- Add a markdown file that covers a basic introduction to OSR.
- Fix some node …

Add two helpers for OSR related optimizations

---

ddr/include/ddr/error.hpp
ddr/include/ddr/ir/Type.hpp
ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
ddr/lib/ddr-ir/ClassType.cpp
ddr/lib/ddr-ir/EnumUDT.cpp
ddr/lib/ddr-ir/Macro.cpp
ddr/lib/ddr-ir/NamespaceUDT.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-ir/TypePrinter.cpp
ddr/lib/ddr-ir/UDT.cpp
ddr/lib/ddr-macros/MacroTool.cpp

Types names in the blob and the superset should be consistent. Previously, `unsigned short int` would appear in the blob while the superset would say `U16`.
The code from `Macro.cpp` has moved to `Type.cpp` and has been improved to handle `const` and `volatile`.
Also some minor cleanup:
* remove unnecessary #includes from header files
* break #include cycle involving Symbol_IR.hpp and Type.hpp
* add #includes to *.cpp files as needed

Refactor recognition of standard types

---

compiler/optimizer/OMRSimplifierHandlers.cpp

The b<add/sub>Simplifier routines were only simplifying math
operations on 2 constants. The short simplifier handles way more
cases and uses a generic helper routine that should work for byte
operations as well.  This change switches the 2 APIs above to use
the common helper.
Also fix the spacing in the s<add/sub>Simplifier.

Improve byte simplification

---

compiler/arm/codegen/OMRTreeEvaluator.cpp

We need to call the common code generator API in the BBStartEvaluator
on ARM as downstream projects may choose to override behavior of what
happens in catch blocks.
This synchronizes all the platforms in terms of catch block handling.

Call generateCatchBlockBBStartPrologue in ARM BBStartEvaluator

---

compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp

Add genMemToMemCopyElement and genLoadAndStoreForArrayCopy functions. These functions are used to generate more conservative element by element copy loop for array copy.

Add ArrayCopy helper functions

---

compiler/aarch64/codegen/OMRTreeEvaluator.cpp

This commit adds a call to generateCatchBlockBBStartPrologue() in
BBStartEvaluator() for aarch64.

AArch64: Call generateCatchBlockBBStartPrologue in BBStartEvaluator

---

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commmit implements iRegLoadEvaluator(), iRegStoreEvaluator(), and
similar evaluators for aarch64.

AArch64: Implement iRegLoad/iRegStoreEvaluator(), etc.

---

CODEOWNERS

As per the discussion in [1] and the subsequent discussion within the
PR itself we add a CODEOWNERS file at the top-level and specify the
code owners for particular areas within the Eclipse OMR project.
The owners of the corresponding areas will automatically get review
requests when a PR is opened touching files within their respective
area of expertise.
@charliegracie and @mstoodle are identified as global catch-all code
owners for general contributions to the repository.
[skip ci]
[1] https://eclipse-omr.slack.com/archives/CCQ8B4B39/p1541599655022400

Add CODEOWNERS file for automated review requests

---

gc/base/standard/Scavenger.cpp
gc/structs/ForwardedHeader.cpp

Now Concurrent Scavenge GC should compile with all X86 specs.

Fix Concurrent Scavenge GC compilation errors

---

compiler/z/codegen/OMRRegisterDependency.cpp

While resolving register dependencies at split point (GlRegDeps) we check type of the node to decide whether if we need 32 Bit or 64 Bit load instruction. If we have evaluated this node to use 64 Bit register it should use 64 Bit load instruction to generate necessary instruction to satisfy register dependencies at split point.

Check register properties for generating load

---

.gitignore

emacs save files ending in ~ should not be tracked by git.
This commit adds them to the .gitignore file for the project.
Signed-off-by: Vijay Sundaresan <vijaysun@ca.ibm.com>

Adding a .gitignore entry for emacs save files

---

port/unix/omrsysinfo.c

Move variable declarations to top of scope for c89 compilers

---

compiler/aarch64/codegen/ARM64SystemLinkage.cpp

createPrologue() has saved the argument registers using strimmx
or vstrimmd instructions, regardless of the data size.  On the other
hand, the stack offset for the argument registers takes the data
size into consideration.
This commit changes the createPrologue() instruction generation, so
that 32-bit and smaller arguments are saved by strimmw or vstrimms
instructions.

AArch64: Fix createPrologue()

---

compiler/il/ILOpCodeProperties.hpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp

J9 project specific code related to ArrayCopy has been deprecated,
removing them.

Remove J9 project specific arraycopy code on X86

---

compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

This commit adds is64bit parameter to generateCompareInstruction(),
generateTestInstruction(), etc.
Those functions used to look at node->getDataType().isInt64() to
determine whether 64-bit or not.  It is inappropriate for lcmpeq
or other lcmp* nodes that compare 64-bit values and return 32-bit
value.

AArch64: Add is64bit parameter to generateCompareInstruction()

---

compiler/codegen/ScratchRegisterManager.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390GenerateInstructions.hpp

This commit contains following changes.
1. Instead of expecting diamond for array copy direction from
optimizer generates a runtime test for a given single array copy
tree top.
2. Vectorize backward array copy sequence to speed up

Improve ArrayCopy Sequence Part on IBM Z

---

compiler/optimizer/PartialRedundancy.cpp

The child index of rhsNode of a store is more relevant to whether the
store is indirect or direct rather than whether it's a wrtbar. Simplify
the calculation to make it more clear.

Simplify child index calculation code in PRE

---

compiler/z/codegen/OMRTreeEvaluator.cpp

When node is set to be backwardArrayCopy node, we generate backward array copy sequence only. When this is combined with constant length bytelength we end up with NULL byteLenReg which causes segmentation fault.

Fix build break

---

gc/base/CollectorLanguageInterface.hpp
gc/base/standard/ConcurrentScavengeTask.hpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/EnvironmentStandard.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/verbose/VerboseHandlerOutput.cpp

If there is a request to yield, abort the concurrent scan phase. The
rest of the work will be done in final STW phase.
There could be an arbitrary criteria, which this change does not impose;
it just provides API to check if yield is necessary.
An example of a criteria is raised exclusive VM access request (which
could be language specific). In such a case it is fair to yield and
don't have a third party to wait 100s of milisec before the concurrent
phase completes.
Another example would be exhausted hybrid survivor/allocate space.
Application cannot make progress anyway, so it's better to complete the
cycle in the final STW phase with all GC threads available (by default
4x more than number of threads in concurrent phase).
Yield checks are still relatively coarse - they are done before …

Concurrent Scavenger yield

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

This commit contains following changes.
1. Enable Specialized direction trees for arraycopy for 31-Bit IBM Z platform.
2. Minor changes to instruction used for array copy trees

Enable specialized arraycopy trees for 31-Bit Z platform

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64ConditionCode.hpp
compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/ControlFlowEvaluator.cpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
compiler/ras/Debug.hpp

This commit implements icmpeqEvaluator() and similar evaluators for
aarch64.

AArch64: Implement icmpeqEvaluator(), etc.

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

Add induceOSRAfterAndRecompile API to generate the tree for helper call
to trigger both OSR and recompilation.
The old API induceOSRAfter is still useful if only OSR transition
is needed.

Add induceOSRAfterAndRecompile API in OMR

---

compiler/ras/Debug.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

As it is discussed in #2822, X87 support is deprecated, and will be
removed. This fact lets us the opportunity to remove
'TR_X86FPStackIterator' from the codebase as the first step to
consolidate implementations of RegisterIterator.
Issue: #2645

Remove TR_X86FPStackIterator (X87 FP) class

---

CMakeLists.txt
cmake/modules/OmrCompilerSupport.cmake
ddr/CMakeLists.txt
example/CMakeLists.txt
fvtest/rastest/CMakeLists.txt
fvtest/util/CMakeLists.txt
gc/CMakeLists.txt
jitbuilder/CMakeLists.txt
omr/CMakeLists.txt
omrsigcompat/CMakeLists.txt
omrtrace/CMakeLists.txt
port/CMakeLists.txt
thread/CMakeLists.txt
util/a2e/CMakeLists.txt
util/avl/CMakeLists.txt
util/hookable/CMakeLists.txt
util/main_function/CMakeLists.txt
util/omrutil/CMakeLists.txt
util/pool/CMakeLists.txt

OMR uses include_directories and compile_definitions to set up some
basic, universal compile options. The problem is, these only apply to
targets defined in OMR, and will not propagate out to consuming
projects. This patch is a step towards making every OMR component export
all its needed options.
omr_base is an interface library that exports all the core configuration
that most OMR components need. This gives us a centralized location to
configure basic properties of the omr project. omr_base replaces any
usage of include_directories or compile_definitions.
Virtually every library in OMR should link (directly or indirectly)
against omr_base publicly. By doing so, we can count on these properties
correctly propagating out to consuming projects through linking, without
any additional …

cmake: add omr_base: a library defining basic configuration

---

ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp

Fix a couple of bugs with ddrgen related to empty structs
* structs are considered based on the total number of constants/fields
seen globally rather than the number of fields/constants seen in that
struct
* Empty structs are still actually output, even when -e is not specified.
This leads to an assertion failure because the number of structs output
is greater than _buildInfo.header.structureCount
* _buildInfo.header.structDataSize is incremented for empty structs which
should not be output.

DDR: fix ddrgen bugs involving empty structs

---

jitbuilder/CMakeLists.txt
jitbuilder/apigen/README.md
jitbuilder/apigen/test.py
jitbuilder/apigen/test/test_sample.json

These commits add:
- some high-level documentation about how the generated client API code works
- some tests for parts of the generator
- a CMake rule to run the generator tests when `OMR_JTIBUILDER_TEST` is set

Documentation and testing improvements for the JitBuilder API generator

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/structs/SublistPool.cpp
gc/structs/SublistPool.hpp

- explicitly call default constructor for various stats structs in
GCExtensions 
- initialize MasterGCThread struct earlier, so that Scavenge can be
triggered on early Nursery Allocation Failure (with small Xms/Xmns),
rather then fullfilling the request from Tenure (and slowing down the
startup) 
- on shutdown free up previous RS list, too. It will be non-empty, if
shutdown is requested in a middle of CS cycle

Misc startup/shutdown fixes for Concurrent Scavenger

---

compiler/ilgen/BytecodeBuilder.hpp
compiler/ilgen/OMRBytecodeBuilder.cpp
compiler/ilgen/OMRBytecodeBuilder.hpp

BytecodeBuilders have an bcIndex which describes the index for the
bytecode. Similarly a bytecode should be able to describe how many
pc indexes each bytecode represents.

Add bcLength to BytecodeBuilder

---

port/common/omrport.tdf
port/unix/omrsignal.c

If a process has blocked signals, then the signals stay blocked in the
sub-processes across fork(s) and exec(s). Blocked signals prevent signal
handlers to be invoked. Signals listed in signalMap should be unblocked
during initialization in case a parent process has blocked any of those
signals.
Issue: https://github.com/eclipse/openj9/issues/3468

Handle signals blocked by a parent process

---

gc/base/Dispatcher.cpp
gc/base/Dispatcher.hpp
gc/base/GCExtensionsBase.hpp
gc/base/ParallelDispatcher.cpp
gc/base/ParallelDispatcher.hpp
gc/base/standard/ConcurrentScavengeTask.hpp
gc/base/standard/ParallelScavengeTask.cpp
gc/base/standard/ParallelScavengeTask.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

waitingCountAliasThreshold introduced to relax copy cache alias inhibiting - relaxed to 20% from 0% threads that are allowed to be stalled.
See https://github.com/eclipse/omr/issues/3089

GC: Relax Scavenger's Aliasing Inhibiting Condition

---

compiler/aarch64/codegen/ARM64Debug.cpp

This commit changes the order of operands of store instructions
from "str [sp, 0], lr" to "str lr, [sp, 0]", which is the same order
as that in AArch64 assembler syntax.

AArch64: Change the operand order of store instructions in trace file

---

compiler/optimizer/LocalOpts.cpp

Change InvariantArgumentPreexistence to only devirtualize method if the
propagated arg info with known object index is compatible with the
method class of the callsite.

Only devirtualize call for compatible classes

---

gc/base/Dispatcher.cpp
gc/base/Dispatcher.hpp
gc/base/ParallelDispatcher.cpp
gc/base/ParallelDispatcher.hpp

Mac compile fail fix - hidden overloaded virtual function:
**Rename `recomputeActiveThreadCount` to `recomputeActiveThreadCountForTask`**
```
../gc_realtime/Scheduler.hpp:233:15: error: 'MM_Scheduler::recomputeActiveThreadCount' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
virtual void recomputeActiveThreadCount(MM_EnvironmentBase *env);
^
../omr/gc/base/ParallelDispatcher.hpp:111:20: note: hidden overloaded virtual function 'MM_ParallelDispatcher::recomputeActiveThreadCount' declared here: different number of parameters (3 vs 1)
virtual uintptr_t recomputeActiveThreadCount(MM_EnvironmentBase *env, MM_Task *task, uintptr_t newThreadCount);
^

GC: Mac clang fix - hidden overloaded virtual function

---

gc/base/standard/Scavenger.cpp
gc/verbose/VerboseHandlerOutput.cpp
gc/verbose/VerboseHandlerOutput.hpp
gc/verbose/schema.xsd

If concurrent phase is prematurely terminated, a warning message is
reported by verbose GC.
Distinguish (for now) between:
- externally requested termination (JVMTI and similar)
- GC requested (exhausted allocate/survivor, global STW, etc.)
Example of exhausted allocate/survivor:
```
<concurrent-end id="13810" type="scavenge" contextid="13800"
timestamp="2018-11-23T18:07:54.482">
<warning details="termination requested by GC" />  <<<<<<<<<<<<<<<<<<<<
<gc-op id="13811" type="scavenge" timems="9.128"
contextid="13800" timestamp="2018-11-23T18:07:54.482">
<memory-copied type="nursery" objects="46034"
bytes="7511576" bytesdiscarded="142136" />
<memory-copied type="tenure" objects="458" bytes="17376"
bytesdiscarded="496" />
<copy-failed type="nursery" objects="49" bytes="3624" />
</gc-op> …
```

VGC: report Concurrent Scavenger phase termination

---

gc/base/GCExtensionsBase.hpp
include_core/omrgcconsts.h

Suballocator related variables suballocatorInitialSize and
suballocatorCommitSize in MM_GCExtensionsBase are defined for all
platforms but initialized in class constructor only for Compressed Refs.
It cause operations with non-initialized memory might crash Memory
Check. Extending scope of initialization of these variables for all
platforms. As far as Suballocator happen to be used for Compressed Refs
platforms only it is irrelevant which values these variables are
initialized on other platforms. Set them exactly the same as in CR to
have cleaner code. Again, this would not have any impact for non-CR
platforms footprint.

Initialize Suballocator variables all platforms

---

gc/.clang-format

The clang-format only affects the GC. The style is as close as I could reasonably get to the existing GC style. 

Add GC clang-format

---

compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/ras/Debug.hpp

This commit removes some ARM64Dep*Instruction classes.
The base OMR::ARM64::Instruction class already has the common
RegisterDependencyConditions field in it, and you don't need to
define separate classes like ARM64DepLabelInstruction from
ARM64LabelInstruction.

AArch64: Remove unnecessary ARM64Dep*Instruction classes

---

compiler/env/OMRObjectModel.hpp

Object Model now support querying for the kind of read and write barriers.

Provide read/write barrier kind info in Object Model

---

gc/structs/ForwardedHeader.cpp

If a thread (GC or mutator) was participating in co-operative copying of
a large object, prior to announcing it's finished, and leaving the
'party', it will issue a store barrier (for weak memory models) that
will ensure all the copy work it has done is visible to the rest of the
world.

Store barrier in co-operative copy

---

compiler/optimizer/VPHandlers.cpp

The TODO is addressed by adding a comment describing why a particular
optimization related to wrtbars is disabled under concurrent scavenge.

Add comment regarding disabled CS wrtbar optimization

---

compiler/compile/OMRCompilation.cpp

Previously, this option was set only when `OMR::Compilation::compile()`
was called. That resulted in the option not having an effect on
CodeGenerator's `_disableInternalPointers` member as that is
initialized much earlier in its constructor by checking a few
compilation-specific options, including `TR_DisableInternalPointers`.
For this reason, not setting `TR_DisableInternalPointer` option
globally was resulting in performance regression in some cases.
Setting this option  globally is not the correct thing to do,
as this causes the option to be applied to all subsequent
compilations regardless of whether it should be set.
By setting `TR_DisableInternalPointer` to the current
compilation-specific options in the the constructor body of
`OMR::Compilation` before …

Restrict setting TR_DisableInternalPointer to current compilation

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

As part of eclipse/openj9#3763 we have migrated the CLQ related queries
into OpenJ9 where they really belong. This commit removes the OMR
pieces of the code which were left over.

Remove CLQ queries as they have migrated to OpenJ9

---

compiler/optimizer/VPHandlers.cpp

...where genTypeResult() was used.
Rather than attempt not to intersect constraints, this logic now simply
generates the constraint for objects that pass the type test, and tries
to add that constraint on the appropriate path, implicitly intersecting
it with any pre-existing constraint. The branch can be folded away if
one of the paths is found to be unreachable due to an empty constraint
intersection.
The previous logic could sometimes fold away a profiled guard against
java/lang/Class even in the absence of any other type information,
generating an unconditional goto to the taken side (fall-back path),
which is functionally correct but undesirable. This now only happens
when an existing type constraint precludes the object from being an
instance of java/lang/Class.

Simplify instanceof/guard type constraint creation

---

gc/base/standard/Scavenger.cpp

Set the value of the flag only if it really changes (from false to
true).
The flag was being written on every check from multiple threads/CPUs,
causing cash trashing and slowing down GC with plafroms with CS enabled.
The flag (regression) was introduced here:
https://github.com/eclipse/omr/pull/3205.

Fix cache trashing in _shouldYield

---

compiler/aarch64/codegen/ARM64Instruction.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp

This commit fixes the problem in register assignment for zero register.

AArch64: Fix generation of instructions with zero register

---

compiler/aarch64/codegen/OMRMachine.cpp

decFutureUseCount() has not been called upon register assignment for
aarch64 instructions. This commit adds a call to decFutureUseCount()
in OMR::ARM64::Machine::assignOneRegister().

AArch64: Call decFutureUseCount() in Machine::assignOneRegister()

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/OMRMemoryReference.cpp
compiler/aarch64/codegen/OMRMemoryReference.hpp

This commit adds incRegisterTotalUseCounts() in OMRMemoryReference,
and calls to it in ARM64Instruction.hpp.

AArch64: Call incRegisterTotalUseCounts() for MemoryReference

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp

InduceOSR helpers needs to call through snippet to pass arguments as if
calling an interpreted method. Fix and refactor APIs to set the helper
method symbol as interpreted.

Set induceOSR method symbol to be interpreted

---

gc/base/standard/Scavenger.cpp

Fix for https://github.com/eclipse/omr/issues/3211
Flush RS fragment upon backout.

GC Fix: Corrupted Remembered Set Count On Backout

---

fvtest/CMakeLists.txt
fvtest/coretest/CMakeLists.txt
fvtest/coretest/TestBytes.cpp
fvtest/coretest/main.cpp
include_core/OMR/Bytes.hpp

Add a set of convenience functions for working with bytes. Useful for
specifying large sizes like heap minimum size, or maximum memory
overhead.
The kibi/mebi/gibi prefix was chosen to minimize confusion, some people
might consider a kilobyte to be 1000 or 1024 bytes, but a kibibyte is
unambiguously 1024 bytes.

Add Bytes utility header

---

compiler/x/codegen/OMRTreeEvaluator.cpp

FloatingPointAndVectorBinaryArithmeticEvaluator should have checked if a
xload node has been evaluated before optimizing the instruction using
RegMem form instructions. Fixing.

Fix for incorrect FP/Vector arithmetic evaluator on X86

---

fvtest/coretest/CMakeLists.txt
fvtest/coretest/TestIntrusiveList.cpp
include_core/OMR/IntrusiveList.hpp

The IntrusiveList is a doubly linked list, where the node is stored in
the elements itself. The node access mechanism is overridable, allowing
elements to customize node access, or belong in multiple lists
simultaneously.
Compared to the J9_LINKED_LIST, this utility is implemented without
macros while still being type-safe.

Add IntrusiveList utility

---

ddr/lib/ddr-ir/Type.cpp

* inadvertently reversed in #2830

Fix default for signed/unsigned modifier

---

compiler/optimizer/LoopVersioner.cpp

- Use the correct aconst node creation API Node::aconst to ensure
the correct address-type constant is represented. The current API
Node:create takes in a 32-bit int value, which results in 64-bit
addresses being truncated and sign-extended.
- Fix erroneous logic on X86 where erroneously we always generate
compile time constant for tenure range boundaries.

Fix wrtbar loop versioning range check trees

---

gc/base/MasterGCThread.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/stats/ConcurrentPhaseStatsBase.hpp
gc/verbose/VerboseHandlerOutput.cpp

If Concurrent Scavenger yielded to an external async request, after the
third party is complete (after which we are able to regain VM access),
the cycle will resume concurrently (instead of turning into the final
STW phase).
Consequently, we may have several concurrent stanzas in verbose GC
during one Concurrent Scavenge cycle (although it's still unknown what
party requested termination):
```
.... initial STW phase of a CS cycle just completed....
<exclusive-end id="16894" timestamp="2018-11-27T14:23:29.494"
durationms="7.551" />
<concurrent-start id="16895" type="scavenge" contextid="16886"
timestamp="2018-11-27T14:23:29.494">
</concurrent-start>
<concurrent-end id="16896" type="scavenge" contextid="16886"
timestamp="2018-11-27T14:23:29.502">
<warning details="termination requested …
```

Resuming externally terminated CS

---

example/glue/configure_includes/configure_osx.mk
glue/configure_includes/configure_osx.mk

OMR_THR_YIELD_ALG should only be used with Completely Fair Scheduler
(CFS). CFS is only available on Linux.
MacOS schedulers can be classified as multilevel feedback queue
schedulers. MacOS doesn't use CFS. Thus, disabling OMR_THR_YIELD_ALG on
MacOS.

Disable OMR_THR_YIELD_ALG on MacOS

---

cmake/config.cmake
fvtest/CMakeLists.txt

Allow us to enable the GC, and FV testing, while turning the xml-driven
GC heap tests off. These tests are currently incompatible with the
gc-api and om.
In the future, the tests will be made to be gc-api compatible, but it's
unclear if the tests will be based off om or continue to use the object
model from the gc example.

Add OMR_GC_TEST compile flag

---

thread/common/omrthread.c

Without this change, I get a segfault dereferencing a NULL pointer retrieved from a TLS entry that was never set. With this change I get:
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

fix error propagation from init_thread_library in omrthread_attach_ex

---

.gitignore

This lets us ignore any build directory.

Add build*/ to gitignore

---

gc/.clang-format

gc clang-format: put a space after template keyword

---

fvtest/coretest/CMakeLists.txt
fvtest/coretest/TestTypeTraits.cpp
include_core/OMR/TypeTraits.hpp

Type traits are useful in templated code to make queries or assertions
about type parameters. For example, a container might assert that it
never contains a reference type.  A smart pointer won't define
pointer-operators when it's referent is void.
Our supported compilers don't provide the standard C++11 header
<type_traits> in OMR. Even looking at planned compiler upgrades, it's
unlikely we'll ever get a standard implementation of type_traits on XLC.
This header provides some easily implemented type traits without any
hacks or compiler support. As well, this header follows OMR coding
conventions, rather than try to simulate the standard type_traits
header.
This PR implements the following:
* Static constants:
* `IntegralConstant<T, X>`
* `BoolConstant<B>` / `TrueConstant` / …

Add basic type_traits-like utility to OMR

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/OpCodeTest.hpp
fvtest/compilertriltest/TypeConversionTest.cpp

This commit adds tril test cases for integer extension evaluators
such as b2i and s2l.

Tril tests for b2i, s2l, etc.

---

compiler/aarch64/CMakeLists.txt

Remove deprecated OMRRegisterIterator.cpp from AArch64 CMakeLists.txt

---

compiler/x/codegen/ControlFlowEvaluator.cpp

The `TR_MethodAddress` relocation which has until now been generated for the displacement of the memory reference of the jump dispatching a `table` node is incorrect on 64-bit.
First, the displacement is only 32 bits, but the relocation works on a pointer-sized value (64 bits). The high half of the "address" is really the first four bytes of the next instruction. If the address adjustment changes the high half, then the next instruction will be modified.
Second, the 32-bit displacement gets sign-extended. If the code were originally compiled at a location below 2GB, and later loaded above 2GB (but below 4GB), the address adjustment will set the sign bit, so that the sign-extension is no longer the same as the zero-extension (i.e. the correct address).
To prevent these problems, the table …

Make x86-64 table jump position independent in AOT

---

compiler/ilgen/CMakeLists.txt
compiler/ilgen/JitBuilderRecorder.hpp
compiler/ilgen/JitBuilderRecorderBinaryBuffer.hpp
compiler/ilgen/JitBuilderRecorderBinaryFile.hpp
compiler/ilgen/JitBuilderRecorderTextFile.hpp
compiler/ilgen/OMRJitBuilderRecorder.cpp
compiler/ilgen/OMRJitBuilderRecorder.hpp
compiler/ilgen/OMRJitBuilderRecorderBinaryBuffer.cpp
compiler/ilgen/OMRJitBuilderRecorderBinaryBuffer.hpp
compiler/ilgen/OMRJitBuilderRecorderBinaryFile.cpp
compiler/ilgen/OMRJitBuilderRecorderBinaryFile.hpp
compiler/ilgen/OMRJitBuilderRecorderTextFile.cpp
compiler/ilgen/OMRJitBuilderRecorderTextFile.hpp
compiler/ilgen/StatementNames.hpp
fvtest/compilertest/build/files/common.mk
jitbuilder/build/files/common.mk

Recorder is part of the record and replay functionality.
The ultimate goal for such feature is to remove the JIT from
runtimes and provide it as a service. The recorder part of this
feature, as the name implies, will record the IL at the client side
and send it to be compiled in the server. The server then
replays/parses the IL and compiles it, to then send machine code
back to the client so that it can execute the requested IL. The IL
contains services that have recording support (e.g. Add, Sub, Xor,
Store, Loop, etc. More to come). This commit is dedicated to the
Recorder initial functionality. More details as follows.
JitBuilderRecorder defines the basic structure of a JitBuilder IL
(ljbil) representation. The following files provide implementations
that write this representation to a …

Provide classes to record JitBuilder API calls

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

This commit adds a new option -Xaot:disableAOTAtCheapWarm to control the
logic that will force AOT compilations to be performed at a "cheap"
warm level. A "cheap" warm level is an optimization level where the
inliner has been subdued somewhat (the same inliner changes are applied
to the Xtune:virtualized mode in OpenJ9 JVM).
Upgrades of AOT bodies through sampling are also subdued if the
guarded counting recompilation (GCR) is enabled.

Supporting options and code to allow AOT at cheap warm level

---

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements lcmpEvaluator(), which returns -1, 0, or 1 from
comparison of two long values.

AArch64: Implement lcmpEvaluator()

---

gc/base/GCExtensionsBase.hpp
gc/stats/RootScannerStats.cpp
gc/stats/RootScannerStats.hpp

1) Flags for reducing  printing
Introduce two flags (global and per thread) that will assist in reducing
the amount of prints for TGC root scan time. They will be printed only
if any thread worked on any of roots for a given increment. This will be
particularly useful for Metronome (in OpenJ9) since stats are reported
for each GC increment, and most of increments do not deal with roots.
2) Max Increment time
Introduce fields root scan stats for max increment time and entity that
that owns that max increment. This values will be reported by
incremental GCs, like Metronome GC, where scan time spent for one entity
could span over several increments.

 TGC root scan time

---

buildenv/docker/doBuild.sh
buildenv/docker/x86_64/ubuntu16/Dockerfile

While working on a recent PR on my MacBook, I needed to reproduce
a failure in the Linux x86 testing. To do that, I built a Docker
container to build and run tests and to diagnose the failure.
It seemed like something others might find useful, so I cleaned
it up a bit to make it a bit more consumable. It's not perfect
but its gets you to having a workin Linux x86 build with only
a couple of commands.  The basic directions are provided in
the Dockerfile, which I'll reproduce here to save a bit of time:
Basic usage (adapt to your environment and scenario):
git clone https://github.com/eclipse/omr (or cd to a directory that contains an OMR repository)
cd omr/buildenv/docker && docker build -f x86_64/ubuntu16/Dockerfile -t buildomr .
cd ../../../
docker run --privileged -v $PWD/omr:/omr -it …

Provide Dockerfile for easier x86 build failure reproduction

---

compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/aarch64/codegen/OpBinary.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit adds ConstantDataSnippet for aarch64, and implements
fconst/dconstEvaluator().

AArch64: Implement fconst/dconstEvaluator()

---

compiler/aarch64/codegen/OMRTreeEvaluator.cpp

This comment fixes register allocation for fload/dloadEvaluator()
for aarch64 so that they use VFP registers.

AArch64: Fix register allocation for FP xload

---

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/aarch64/codegen/OMRTreeEvaluator.hpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements passThroughEvaluator() for aarch64, and use it
for l2a, lu2a, and a2l.

AArch64: Implement passThroughEvaluator()

---

compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
compiler/aarch64/codegen/OMRMachine.cpp
compiler/aarch64/codegen/OpBinary.cpp

This commit adds aarch64 instructions fmovs/fmovd to the tables,
and implements registerCopy() for TR_FPR.

AArch64: Add instructions for FP mov

---

compiler/aarch64/codegen/TreeEvaluatorTable.hpp
compiler/aarch64/codegen/UnaryEvaluator.cpp

This commit implements i2lEvaluator() and other integer signed/unsigned
extension evaluators.

AArch64: Implement integer extension evaluators: i2l, etc.

---

compiler/aarch64/codegen/BinaryEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements shift evaluators such as ishlEvaluator() for
aarch64.

AArch64: Implement shift evaluators

---

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit fixes the TreeEvaluator table for aarch64.
lcmpeq/lcmpneEvaluator also handles lucmpeq and lucmpne.

AArch64: Fix TreeEvaluatorTable.hpp for lucmpeq and lucmpne

---

compiler/aarch64/codegen/BinaryEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements rotate-left (irol and lrol) evaluators for
aarch64.

AArch64: Implement irol/lrolEvaluator()

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/il/OMRIL.cpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/PartialRedundancy.cpp

Map rdbar/wrtbars to corresponding opcode to normal opcode to keep
consistency with the existing wrtbar opcode. Subprojects can overwrite
the mapping decisions.
PRE and FieldPrivatizer are disabled for now if the trees might contain
newly added rdbar/wrtbar. All the transformations applied to normal
load/write s should be applied to rd/wrtbar s. However, we need to
be careful about the difference in the shape of the trees and the
mapping relationship between different loads and writes. More
investigation is needed to make sure those 2 opts would do the right
thing for rdbar/wrtbars.

Guarantee functional correctness of rdbar/wrtbar

---

compiler/aarch64/codegen/OMRMachine.hpp
compiler/arm/codegen/OMRMachine.hpp
compiler/p/codegen/OMRMachine.hpp
compiler/x/codegen/OMRMachine.hpp
compiler/z/codegen/OMRLinkage.cpp
compiler/z/codegen/OMRLinkage.hpp
compiler/z/codegen/OMRMachine.hpp

This reverts commits with titles such as "Add OMR::XXX::Machine::getXXXRealRegister()"
The wrapper methods 'getXXXRealRegister()' is not required since all
uses of the methods are changed to the 'getRealRegister()' one.
If the methods are still in the codebase, there forever will be a temptation for everyone to use a  platform specific method instead of the generic one.
The PR should be merged after eclipse/openj9#2936.

Revert "Add OMR::XXX::Machine::getXXXRealRegister()"

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRRegisterDependency.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

When a register is spilled in the mainline but used in the out of line
(OOL) code section we are forced to perform a spill and a fill in the
OOL such that the register state remains the same on both paths of
execution.
The way this is handled on Z is that `SpilledReg` register dependencies
are added to the OOL entry label which represent the state of the
machine at the branch to the OOL entry label in the mainline.
Because a register may have been spilled in the mainline and used in
the OOL we must perform a fill (generate a load). When 64-bit registers
are available for use in 31-bit targets the register kind will be a
`TR_GPR64`, however currently the `is64BitReg` flags are not properly
set for these register kinds and as such we cannot use this flag as an
"end-all" answer to whether we …

 Correctly fill 64-bit registers on 31-bit in OOL

---

ddr/include/ddr/blobgen/java/genSuperset.hpp
ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
ddr/lib/ddr-blobgen/java/genSuperset.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
ddr/tools/ddrgen/ddrgen.cpp

* add OSX support for DW_TAG_ptr_to_member_type
* use port library consistently if DEBUG_PRINT_TYPES is defined
* add missing use of Type::isStandardType() in blob generator
* recognize more known types and handle them consistently
-- fix bug in Type::isStandardType()
-- e.g. 'unsigned short int' was handled, but not 'unsigned short'
-- treat char as unsigned unless explicitly 'signed'
-- handle SRP types; e.g. 'J9SRP(U_32)' -> 'J9SRP(U32)'

Multiple ddrgen fixes

---

fvtest/compilertriltest/CompareTest.cpp

This commit adds tests for unsigned integer comparison, such as
iucmpeq and lucmpgt.

Tril tests for iucmpeq, lucmpeq, etc.

---

compiler/z/codegen/OMRRegisterDependency.cpp

On 64-bit platforms #3337 unintentionally changed the semantics of OOL
spill reload logic. The `TR::InstOpCode::getLoadOpCode()` API returns a
64-bit load on 64-bit targets, which means if the spilled register was
32-bit the logic in #3337 made it so that we would never use a 32-bit
load to fill the register.
We correct this by avoiding the use of the aforementioned API and
instead simplify the logic to use a 32-bit load unless the register is
marked as a 64-bit register. This will be correct on both 31-bit and
64-bit targets.

Fix logic error in #3337

---

port/common/omrport.tdf
port/unix/omrsysinfo.c

Get open file count at `Mac OSX`
Adding implementation to get open file count for `Mac OSX`;
Using `proc_pidinfo` twice to get the size of the buffer required and those available `proc_fdinfo` instances.
Note: `Mac OSX` doesn't have Linux/AIX alike `/proc/%d/fd/`
Manually verified that this PR fixes the test failure at https://github.com/eclipse/openj9/issues/3970. Also verified that this PR doesn't break other platforms (`xa/wa/mz/ap`) via a personal build.

Get open file count at Mac OSX

---

fvtest/coretest/TestTypeTraits.cpp
fvtest/tril/tril/ast.hpp
include_core/OMR/TypeTraits.hpp
jitbuilder/apigen/extras/cpp/TypeDictionaryExtrasInsideClass.hpp
jitbuilder/apigen/extras/cpp/TypeDictionaryExtrasOutsideClass.hpp
jitbuilder/release/cpp/Makefile

This changeset adds the following type traits:
- IsIntegral: replaces `std::is_integral`
- IsFloatingPoint: replaces `std::is_floating_point`
- IsArithmetic: replaces `std::is_arithmetic`
- RemovePoineter: replaces `std::remove_pointer`
In addition, the JitBuilder `toIlType` and `is_supported` services and Tril implementation are refactored to make use of these newly implemented utilities, breaking their dependency on the C++11 `type_traits` standard library.
Closes #3323

Add more type traits to OMR/TypeTraits.hpp to support JitBuilder and Tril

---

compiler/il/OMRILOps.cpp

Previously, the IlBuilder::NotEqualTo service was generating fcmpne and
dcmpne opcodes when comparing floating-point values. However, these
opcodes return false when their operands are unordered with respect to
each other (i.e. when one or both are NaN). This result is unexpected
and is almost never what a JitBuilder user wants to generate, as the
IEEE 754 standard (whose behaviour is mandated by many languages) says
that non-equality should return true for unordered operands.
The fcmpneu and dcmpneu opcodes do exhibit the expected behaviour with
regards to unordered operands. Thus, in order to better conform to user
expectations, IlBuilder::NotEqualTo will now emit those opcodes instead
when comparing floating-point values.
Fixes: #3206

Fix IlBuilder::NotEqualTo for floating-point NaNs

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp

The flag only needs to be checked under voluntaryOSR. Yield
points in involuntaryOSR are always OSRPoints and there is always OSR
support for each yield point under this mode.

Only check doNotProfile flag under voluntaryOSR

---

compiler/il/symbol/OMRAutomaticSymbol.cpp
compiler/il/symbol/OMRAutomaticSymbol.hpp
compiler/optimizer/LocalDeadStoreElimination.cpp
compiler/optimizer/VPHandlers.cpp

Changed the name of `getKind` in `OMR::AutomaticSymbol` to have less ambiguity in function names.
`getKind()` function is being defined in two classes of the same hierarchy, but with different return types:
* `OMR::Symbol::getKind()` returns an `int32_t`
* `OMR::AutomaticSymbol::getKind()` returns an `TR::ILOpCodes` object
* `OMR::AutomaticSymbol` indirectly inherits from `OMR::Symbol`
As part of our work to virtualize the class hierarchies of Eclipse OMR (see motivation of #3235 for more info), we stumbled upon this case. Virtualizing `getKind()` here is not possible due to the different return type. In order to move on with our process and help OMR have a clearer design (less ambiguity in function names), we suggest changing the `getKind()` function in `OMR::AutomaticSymbol` to …

Changing the name of OMR::AutomaticSymbol::getKind() to getOpCodeKind()

---

ddr/include/ddr/blobgen/java/genSuperset.hpp
ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
ddr/lib/ddr-blobgen/java/genSuperset.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
ddr/tools/ddrgen/ddrgen.cpp

Reverts eclipse/omr#3355
An OpenJ9 contributor created the initial PR to address some issues with how ddrgen understands types.  Unfortunately, the changes introduced some issues in our builds when OpenJ9 upgraded to the  OMR version with the changes.
We haven't gotten to the bottom of the why the changes are incorrect yet but they seem to trigger a corner case resulting in incorrect behaviour.  See example below.
I'm requesting that these changes be reverted as they've introduced functional issues that affect OpenJ9's ability to take new OMR levels and may cause issues for any other ddrgen users.
We'll follow up on getting the changes fixed and re-delivered in the new year.
Example problem:
```
[OUT] > Problem running command:
[OUT] U64 contains value larger than Long.MAX_VALUE
[OUT] > …
```

Revert "Multiple ddrgen fixes"

---

compiler/il/symbol/OMRSymbol.hpp
compiler/il/symbol/OMRSymbol_inlines.hpp
compiler/ras/Debug.cpp

Create a static symbol to represent the constant pool address for a
resolved method so that a loadaddr node can be created when the CP
address is needed in trees and AOT can relocate the address value
correctly.

Add static symbol for constant pool address

---

port/common/omrsysinfo.c
port/unix/omrsysinfo.c

Questions were raised on whether the result of the function could be
trusted when an error was encountered.  This change clarifies the
functions contract to ensure that FALSE is always returned if an
error occurs.
Checked all three places this function is defined:
* omr/port/common/omrsysinfo.c
* omr/port/win32/omrsysinfo.c (empty implemention, no comment)
* omr/port/unix/omrsysinfo.c

Clarify meaning of return value in omrsysinfo_is_running_in_container

---

compiler/x/codegen/BinaryEvaluator.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRInstruction.hpp
compiler/x/codegen/OMRRegisterDependency.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/OMRX86Instruction.hpp

This patch renames the methods getIA32RegInstruction(), getIA32LabelInstruction(),
getIA32ImmInstruction() to getX86RegInstruction(), getX86LabelInstruction(),
getX86ImmInstruction() as requested in issue #3112 since they are used for both
32-bit and 64-bit.
Closes: #3112
Signed-off-by: Muzaffar Auhammud <muzaffar@cyberstorm.mu>

Rename getIA32*Instruction to getX86*Instruction

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit adds evaluators for load/store indirect to TreeEvaluator
table.

AArch64: Enable *loadi/*storeiEvaluator in TreeEvaluatorTable.hpp

---

compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit enables the entries of icmpeq, iucmpgt, etc., in
TreeEvaluatorTable.hpp.

AArch64: Enable icmpeqEvaluator(), etc., in TreeEvaluatorTable.hpp

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
compiler/ras/Debug.hpp

This commit implements ARM64ImmSymInstruction for method calls.

AArch64: Add ARM64ImmSymInstruction

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commmit implements fRegLoadEvaluator() for aarch64.  It is also
used for dRegLoad.  fRegStore and dRegStore are covered by iRegStore.

AArch64: Implement fRegLoadEvaluator()

---

compiler/aarch64/codegen/ARM64Instruction.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp

This commit removes redundant assignRegisters()
from TR::ARM64ConditionalBranchInstruction, because
OMR::ARM64::Instruction::assignRegisters() does the work.

AArch64: Remove TR::ARM64ConditionalBranchInstruction::assignRegisters()

---

compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/LoopVersioner.hpp

If a GC point is triggered mid-loop, destination object of
the wrtbar can move/tenure. And if it is not remembered, upon return
from GC the remaining loop iterations will not run any wrtbars
since we had versioned them out. The fix here is to be conservative
when versioning wrtbars - for correctness, if there is a GC
point in the loop, wrtbar versioning will not be performed.

Perform wrtbar versioning conservatively

---

compiler/optimizer/OMRRecognizedCallTransformer.cpp
compiler/optimizer/OMRRecognizedCallTransformer.hpp

RecognizedCallTransformer has a perfect use case of #2934: to transform
a supported intrinsic method to its corresponding IL op.

RecognizedCallTransformer to provide a default action

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRMachine.cpp

This spill statistics gathering is a legacy implementation that is no
longer used and not available on all platforms.  No known OMR consumer
is using this.  Remove it to simplify the code.

Remove unused debug register spill stats

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/OMROptimizations.enum

Clean up deprecated flags and Options now that downstream projects have
been modified to not depend on them.

Misc. OMR compiler flag and Option cleanup

---

fvtest/compilertriltest/TypeConversionTest.cpp

This commit adds Tril test cases for FP->integer and FP->FP conversion.

Tril tests for f2i, f2d, etc.

---

fvtest/coretest/TestBytes.cpp
include_core/OMR/Bytes.hpp

The align utility is for quickly rounding sizes up to a power of two.
Aligning is done everywhere, so it makes sense to have one common
implementation. Note that this is not a general rounding utility, as it
can only round certain specially crafted inputs.

Add isPow2, aligned, and align utility to Bytes.hpp

---

compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/X86BinaryEncoding.cpp

Add relocation record for constant pool address symbol and
the existing AOT infra can relocate the address value correctly.

Add AOT support on X86 for CP address symbol

---

compiler/ilgen/OMRJitBuilderRecorderBinaryBuffer.cpp

The stdint.h limits aren't available without a macro definition on older
compilers, but this behaviour is deprecated as-of C++11. Avoid the whole
mess and stick with numeric_limits, the C++  way to get a maximum.

Use numeric_limits, not stdint.h limits

---

port/linux/omrvmem.c

Theoretically smartAddress might be NULL in case when allocation is
impossible only. However we do have a few customers report
findAvailableMemoryBlockNoMalloc() returns NULL intermittently when slow
allocation path succeeds. We can not reproduce problem in house so the
reason is unknown for now. Service is working on details. In order to
prevent possible failures remove early return to allow slow allocation
path unconditionally temporary until findAvailableMemoryBlockNoMalloc()
is fixed.

Remove early return for OMRPORT_VMEM_ALLOC_QUICK

---

fvtest/porttest/si.cpp
fvtest/porttest/si_numcpusTest.cpp

These keywords aren't necessary and trip up some compiler configs.
Signed-off-by: Kevin Bowling <kevin.bowling@kev009.com>

fvtest: 'register' is deprecated and incompatible with C++17

---

compiler/il/Aliases.cpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/LoadExtensions.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRSimplifierHelpers.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VirtualGuardHeadMerger.cpp
compiler/x/codegen/OMRMemoryReference.cpp

Newer compilers complain about a few things that are not syntactically
incorrect, but might be bugs. For example, not wrapping && expressions
in parenthesis when used in || conditionals. This commit fixes a number
of such warnings found primarily in the compiler/optimizer files.

Fix warnings in multiple (mostly compiler/optimizer) files

---

gc/base/GCExtensionsBase.hpp
gc/base/gcutils.cpp
gc/base/standard/PhysicalSubArenaVirtualMemorySemiSpace.cpp
include_core/omrgcconsts.h

Some pre-req work to support Heap size startup hints feature in OpenJ9
- swapped initial order of allocate and survivor in Nursery Physical
Arena to be able to expand early
- introduce new reasons for expansion, which would be reported by
verbose GC during early startup
- introduce two tuning parameters, that will control how aggressively
the feature is used. heapSizeStatupHintWeightNewValue is for now set to
0 (which effectively means the feature is disabled), but plan is to used
more value of 0.8 or so, after some more testing is peformed

Heap size startup hints

---

compiler/p/codegen/OMRCodeGenerator.cpp

The mrPeepholes() function was not handling P9 3-source type
instructions which would result in those instructions using
the incorrect registers after mr instructions are removed by
peepholes opt.

Add case for IsTrg1Src3 type P9 instructions in mrPeepholes()

---

compiler/aarch64/codegen/BinaryEvaluator.cpp

There is a case where isubEvaluator() for aarch64 generates wrong
"addw" instruction.  This commit fixes it.

AArch64: Fix code generation of isub

---

compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp

Caller of generateMovInstruction() should pass is64bit flag to the
function.  It is true by default.

AArch64: Add is64bit flag to generateMovInstruction()

---

compiler/optimizer/DeadTreesElimination.cpp

A treetop hanging a read barrier can be removed if there is no other
real use of the read barrier. Otherwise, the treetop has to be kept to
anchor the read barrier.
This change contains 2 parts:
The first part changes trivial DeadTreesElimination to remove the
first treetop from trees in the following form:
<pre>
treetop   
xrdbari  
anchor    
=>xrdbari
</pre>
The second part prevents rdbar hanging under treetop with referenceCount > 1 from being removed.
isssue #2812 

Modify DeadTreesElimination to support rdbars

---

example/glue/GlobalCollectorDelegate.hpp
gc/base/CollectorLanguageInterface.hpp
gc/base/GCExtensionsBase.hpp
gc/base/HeapVirtualMemory.cpp
gc/base/MemoryManager.cpp
gc/base/MemoryManager.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
glue/CollectorLanguageInterfaceImpl.hpp

Language independent infrastructure needed by
ReadBarierVerifier to catch direct memory reads. Along with creation and
destruction of shadow heap it includes healing and poisoning of memory
addresses before and after GC, respectively.

 Read barrier verification

---

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
compiler/aarch64/codegen/ARM64Debug.cpp
compiler/aarch64/codegen/ARM64Instruction.cpp
compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
compiler/ras/Debug.hpp

This commit implements ARM64Src1Instruction and ARM64Src2Instruction
for use with "fcmp" instructions.

AArch64: Implement ARM64Src1/Src2Instruction

---

fvtest/compilertriltest/ArithmeticTest.cpp
fvtest/compilertriltest/CompareTest.cpp
fvtest/compilertriltest/TypeConversionTest.cpp

I have used the abs() function in some test case filters for
floating-point workaround, but that is an integer function.
This commit corrects it by replacing with std::abs().

Tril tests: Use floating-point abs function in filters

---

fvtest/compilertriltest/ArithmeticTest.cpp

This commit adds Tril test cases for fabs, fneg, and their double-
precision versions.

Tril tests for fabs, fneg, etc.

---

fvtest/compilertriltest/ArithmeticTest.cpp

This commit adds a test case for imulh.

Tril test case for imulh

---

fvtest/compilertest/build/toolcfg/gnu/common.mk
jitbuilder/build/toolcfg/gnu/common.mk

Apple patches libstdc++v3 with additional support for dtrace. These
dtrace symbols use dollar sign identifiers, and are incompatible with
the compile option -fno-dollars-in-identifiers. This commit removes the
option.

compiler: build: Allow dollars in identifiers

---

compiler/optimizer/ValuePropagationCommon.cpp

There is a transformation that changes a reference arraycopy node into a
primitive arraycopy node if neither an arraystore check nor a write
barrier are required. This transformation should also not occur if a read
barrier is required.
transformArrayCopyCall was changed to check if read barriers are required
and elect not to transform the reference arraycopy node if this is the
case.
Closes: #3440

transformArrayCopyCall needs to know about read barriers

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/optimizer/OMRValuePropagation.cpp
compiler/optimizer/OMRValuePropagation.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/ValuePropagationCommon.cpp
compiler/x/codegen/OMRCodeGenerator.cpp

Dynamic array cloning transforms refArrayObject.clone()
into anewarray followed by arraycopy, where refArrayObject
is a resolved, not fixed array class. This is safe as cloning
of an array object can safely be devirtualized and replaced with
a new array allocation followed by an array copy. The caveat is
that since the array class is not fixed, the actual class type of the
cloned array cannot be known at compile time, hence the class
child of the anewarray opcode needs to be dynamically evaluated
at runtime, instead of being represented as a runtime constant under
normal, statically allocated anewarray cases.

Implement dynamic array clone in value propagation

---

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp
compiler/aarch64/codegen/UnaryEvaluator.cpp

This commit implements evaluators for aconst and aload for aarch64.

AArch64: Implement aconst/aloadEvaluator()

---

compiler/aarch64/codegen/ARM64Instruction.hpp
compiler/aarch64/codegen/ControlFlowEvaluator.cpp

This commit improves code generation of comparison evaluators of
64-bit integers.
Their logic is commoned with 32-bit integer comparison. As its
result, it uses subsimmx instruction when the second child is a
small constant (less than 4096), and that saves one instruction.

AArch64: Improve code generation of lcmpeq, lucmpeq, etc.

---

gc/base/GCExtensionsBase.hpp

Remove obsolete heapSizeStatup
Following up https://github.com/eclipse/omr/pull/3437

Fix spelling

---

compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/p/codegen/FPTreeEvaluator.cpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRTreeEvaluator.cpp
compiler/p/codegen/OMRTreeEvaluator.hpp
compiler/p/codegen/TreeEvaluatorTable.hpp

Updated evaluateNULLCHKWithPossibleResolve for Power to recognize read
barrier opcodes.
Fixed a bug in the Power version of evaluateNULLCHKWithPossibleResolve
where reference counts were not handled properly. If the child has already
been evaluated, it is not necessary to decrement the reference counts on
the reference node.
Added default xrdbarEvaluators for Power.
TM is not currently compatible with read barriers. If read barriers are
needed, TM is disabled.
Closes: #3397

Add awareness of Xrdbar operations for Power

---

compiler/optimizer/ValuePropagationCommon.cpp

On Power, setting skip zero init caused assertion in GC. Revert
back the logic for now.

Revert back to not setting skip zero init on anewarray node

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp

In practice we never enable methodEnterTracing without methodExitTracing.
isMethodEnterTracingEnabled() and isMethodExitTracingEnabled() are
implemented as the same. As proposed in issue eclipse/openj9#3585,
combine them into one method - isMethodTracingEnabled(), which should
be used to replace all usages of isMethodEnterTracingEnabled() and
isMethodExitTracingEnabled().

Combine enter/exit tracing queries into one method

---

compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp
fvtest/compilertest/runtime/TestCodeCacheManager.cpp
fvtest/compilertest/runtime/TestCodeCacheManager.hpp
jitbuilder/runtime/JBCodeCacheManager.cpp
jitbuilder/runtime/JBCodeCacheManager.hpp

This change adds the ability to free the code cache memory segments to the compiler. In the Test Compiler and JitBuilder, the code cache repository segment is now freed when the JIT shuts down.
This should resolve the test failure seen in  #3388.

Free the code cache repository segment in the Test Compiler and JitBuilder on JIT shutdown

---

compiler/runtime/OMRCodeCacheManager.cpp

Pull request #3463 added functionality to free the code cache repository
segment when the compiler's code cache manager is destroyed. However, it
is possible to create a code cache manager that doesn't use a
repository. This commit therefore adds to check to only free the
repository segment if it's actually being used.

Only free the code cache repository segment when it's used

---

port/unix/omrsysinfo.c

`omrsysinfo_get_OS_version` uses `sysctlbyname()` to get the MacOS operating system product name, e.g. "10.13.6" for HighSierra.  Older versions of the operating system do not provide this infomation via the sysctl functions and we currently return "unknown">
This change uses the plist file to get the operating system product name if the sysctl function fails.
Fixes https://github.com/eclipse/openj9/issues/4188
Fixes https://github.com/eclipse/omr/issues/3444

Get_OS_version fall back to plist file on MacOS if sysctl doesn't work

---

compiler/optimizer/Inliner.cpp

The old way of iterating nodes can visit a node more than once. Change
to use PreorderNodeIterator to avoid revisiting any node.

Avoid revisit node in TR_ParameterToArgumentMapper

---

compiler/codegen/OMRAheadOfTimeCompile.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/codegen/Relocation.cpp
compiler/codegen/Relocation.hpp
compiler/runtime/Runtime.hpp
compiler/x/codegen/X86BinaryEncoding.cpp

This PR adds a new relocation identifier, `TR_MethodCallAddress` and uses it during BinaryEncoding on x86 to create the corresponding project-specific relocation on direct call instructions. The implementation will be downstream, but the high level description is that it will be used to relocate direct calls where the call target is known at compile time but the address of the call instruction is not, thereby necessitating the use of a relocation to generate the appropriate relative offset for the call once its position is known.
Also included are some self-explanatory cleanups.
FYI @mpirvu.

Add a direct method call relocation and clean up some related code

---

gc/base/GCExtensionsBase.cpp
include_core/omr.h

Add realtime gcCycleOn fields to OMR_VM from OpenJ9

---

compiler/env/FEBase.hpp

Not used in OMR, and known downstream projects that create a FrontEnd.

Remove unused _start_time field from FEBase

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

This option enables JITaaS (a downstream project) clients to perform corresponding local compilations for their remotely compiled methods. The purpose of this is to generate and compare the trace logs of a method's remote compilation and local compilation.

Add JITaaS option to do local compiles for remote compiles

---

fvtest/porttest/omrfileTest.cpp
port/win32/omrfile.c

Change omrfile_lastmod() to match its documentation that -1 should be
returned on error.
Signed-off-by: hangshao <hangshao@ca.ibm.com>

On Windows omrfile_lastmod() should return -1 if an error occurs

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements floating-point binary evaluators, such as
fadd and dsub.

AArch64: Implement fadd, dsub, etc.

---

compiler/aarch64/codegen/BinaryEvaluator.cpp
compiler/aarch64/codegen/GenerateInstructions.cpp
compiler/aarch64/codegen/GenerateInstructions.hpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements evaluators for imulh/lmulh for aarch64.

AArch64: Implement imulh/lmulhEvaluator()

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements fcmpeqEvaluator for aarch64 and similar
floating-point evaluators.

AArch64: Implement fcmpeqEvaluator, etc.

---

compiler/env/FEBase.hpp
compiler/env/FEBase_t.hpp
fvtest/compilertest/env/FrontEnd.hpp
jitbuilder/env/FrontEnd.hpp

The FrontEnd trait scheme predates the extensible class mechanism and
is not necessary.  Use the concrete extensible class for CodeCache and
CodeCacheManager directly.

Remove CodeCache and CodeCacheManager from FETraits

---

include_core/j9nongenerated.h

Code which uses structure J9VMGCRememberedSet has been added to OMR, but not the structure. The intended plan is to add MM_GCRememberedSet to OMR and then replace the J9VMRememberedSet structure in OpenJ9 with a typedef to MM_GC_RememberedSet. This should allow changing usage of J9VMRememberedSet to MM_GCRememberedSet in OMR and OpenJ9 separately without breaking builds.

Add missing RememberedSet structures from OpenJ9

---

include_core/omrport.h
port/common/omrsysinfo.c
port/include/omrportpg.h
port/omrportpriv.h
port/unix/omrsysinfo.c
port/unix_include/omrportpg.h
port/win32/omrsysinfo.c
port/win32_include/omrportpg.h
port/zos390/omrportpg.h

OMR PortLibrary Api `omrsysinfo_is_running_in_container` is required by every runtime built on top of OMR and also might be having many places where this would be called, As this api internally calls other function, its get invoked everytime we make a call to the api so i thought it would be good to have a PortLibrary global variable `PPG_isRunningInContainer` for is running in container check and also that function to be called at the portLibrary startup which assigns the value for the portlibrary global `PPG_isRunningInContainer` and would decrease the calls for `isRunningInContainer` function.
Signed-off-by: bharathappali <bharath.appali@gmail.com>

Added portlibrary global to make isRunningInContainer called at startup

---

port/unix/omrsysinfo.c

Close `cgroupFile` file handle at end of `isRunningInContainer()`.

Fix file handle leak in isRunningInContainer() function

---

compiler/z/codegen/OMRCodeGenerator.cpp

Eliminate calls to the FrontEnd functions `getCodeCacheBase()` and `getCodeCacheTop()`
in all their forms and instead ask the CodeCache directly for its bounds.
The Z code generator was the only consumer of these APIs.  In all cases it contained a
contingency for the situation where a CodeCache had not been allocated yet, which can
occur if the Z code generator function was called during optimization.  There were no
situations in which this occurred so the code was simplified to only handle the case
where there is an allocated CodeCache.
Note that for OMR projects that did not specialize the FrontEnd functions, the bounds
of the CodeCache will now be more precise.  The default FrontEnd implementations in
OMR simply return `0` for the CodeCache base and `(uint8_t*)(~0)` for the CodeCache …

Eliminate FrontEnd calls to inquire about CodeCache bounds

---

port/osx/omrintrospect.c

Currently, the code dereferences a `null` pointer by accessing
`callstack->symbol` when `callstack` is `null`.
`introspect_backtrace_symbols` should be invoked when a `callstack` exists
and `callstack->symbol` is `null`.
The code has been fixed to avoid dereferencing a `null` pointer, and
invoke `introspect_backtrace_symbols` under the correct conditions.
Issue: #3507.

Fix bad code - dereferencing a null pointer

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp
compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/env/FEBase.hpp
compiler/env/FEBase_t.hpp

* Rename CodeGenerator `resizeCodeMemory` to more accurate `trimCodeMemoryToActualSize` and
fix up references.
* Delete unused FrontEnd `resizeCodeMemory` APIs.

Create CodeGenerator trimCodeMemoryToActualSize() API

---

port/linuxs390/omrsignal_context.c
port/zos390/omrsignal_context.c
port/zos390/omrsignal_context_ceehdlr.c
port/ztpf/omrsignal_context.c

In the S/390 architecture, the FPC register is 32-bits wide independent of whether a process is running in 31-bit or 64-bit mode. `infoForControl()` and `infoForControl_ceehdlr()` were incorrectly
returning `OMRPORT_SIG_VALUE_ADDRESS` instead of `OMRPORT_SIG_VALUE_32`.

S390: Fix type of FPC register

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/FEBase.hpp
compiler/env/FEBase_t.hpp

Now that #3371 is merged and downstream projects have been updated, remove
the support scaffolding:
* delete Compilation NumReservedIPICTrampoline getter/setter
* delete Compilation codeCacheSwitched getter/setter
* delete FrontEnd switchCodeCache()

Remove OMR refactoring scaffolding

---

compiler/aarch64/CMakeLists.txt
compiler/aarch64/env/OMRCPU.cpp
compiler/aarch64/env/OMRCPU.hpp
compiler/arm/env/OMRCPU.cpp
compiler/arm/env/OMRCPU.hpp
fvtest/compilertest/build/files/target/arm.mk
jitbuilder/build/files/target/aarch64.mk
jitbuilder/build/files/target/arm.mk

To prevent downstream project breakages, introduce empty extensions
to the CPU hierarchy for ARM and AArch64.  Once merged, downstream
projects can make changes to their build systems to accommodate the new
files before new CPU functionality is added in #3479.

Introduce empty CPU extension classes for ARM and AArch64

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/control/CompileMethod.cpp
compiler/env/FEBase_t.hpp
compiler/z/codegen/OMRCodeGenerator.cpp

Replace calls to Compilation get/setCurrentCodeCache with a direct
inquiry to the CodeGenerator.  The Compilation functions always delegate
to the CodeGenerator.  Delete the Compilation functions.
There is one instance in `CompileMethodFromDetails` where the CodeGenerator
object could be NULL (during an AOT load) and that scenario is handled
by passing a NULL CodeCache as the original Compilation function would have.

Acquire current CodeCache directly from CodeGenerator

---

gc/base/standard/RememberedSetSATB.cpp
gc/base/standard/RememberedSetSATB.hpp

Changing usage of old OpenJ9 structure J9VMGCRememberedSet to new OMR structure MM_GCRememberedSet. J9VMGCRememberedSet does not exist in OMR.

Rename J9VMGCRememberedSet to MM_GCRememberedSet

---

cmake/modules/OmrCompilerSupport.cmake
fvtest/compilertest/build/rules/gnu/common.mk
jitbuilder/build/rules/gnu/common.mk
tools/compiler/scripts/generateVersion.pl

When invoked with an optional second argument, it will write to the named (output) file only if the contents need to change. This avoids recompiling the generated source file and downstream (linking, etc.) when no JIT changes have been made.

Enhance JIT version generation script

---

compiler/README.md

Per the discussion at the Compiler Architecture Meeting (#3326)
and the resolution in #3306, the `TR` namespace shall be used
for the public API of the compiler component that is consumable
by downstream projects.  This PR clarifies the language and
references the umbrella issue that tracks the work to migrate
the existing public API to the `TR` namespace.
Closes #3306
Closes #2084

Refine the guidance on using the TR namespace

---

.travis.yml

Travis has deprecated Trusty machines, as well as container-based images.
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Travis: Update to use Xenial vm

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp

* `getCodeCacheTop`
* `getCodeCacheBase`

Remove deprecated FrontEnd CodeCache boundary inquiry functions

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp

* getClassDepthAndFlagsValue
* getStringLength
These are only used in OpenJ9-guarded code.

Remove OpenJ9-specific FrontEnd functions

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/env/FEBase.hpp
compiler/env/FEBase_t.hpp

* introduce a CodeGenerator `allocateCodeMemoryInner` function that takes
the place of the FrontEnd function and that downstream projects can
override.
* improve documentation for existing CodeGenerator `allocateCodeMemory`
functions
* remove FrontEnd API

Deprecate FrontEnd allocateCodeMemory

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements type conversion evaluators of floating-point
types, such as i2f, d2l, and f2d.

AArch64: Implement FP type conversion evaluators

---

compiler/aarch64/codegen/FPTreeEvaluator.cpp
compiler/aarch64/codegen/TreeEvaluatorTable.hpp

This commit implements conditional branch evaluators for float and
double, such as iffcmpeq and ifdcmpgt.

AArch64: Implement floating-point conditional branches

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/runtime/OMRCodeCacheManager.cpp

Not useful in OMR or any downstream project.

Remove deprecated option EnableMethodTrampolineReservation

---

compiler/optimizer/OMRTransformUtil.cpp

If `elseBlock` and `mergeBlock` are identical, the user wants to create
an alternate path that after completion will jump back to the fall
through of the if test.
```
ifBlock
|    \
|     \
|   thenBlock
|    /
|   /
mergeBlock/elseBlock
```
Under current implementation, `ifBlock` is constructed by splitting
`elseBlock` after prepending `ifTree` to `elseBlock`. The old
`elseBlock` will become `ifBlock`, `elseBlock` will get a new value
after split. If `mergeBlock` is the same as `elseBlock`, then it will be
the same as `ifBlock` after split. The alternate path `thenBlock` will
merge to `ifBlock` if we don't update `mergeBlock`, resulting in a
infinite loop. Fix it.

Allow alternative path to merge to else block

---

compiler/ras/Tree.cpp

When seeing NULLChk without NULLChkReference while printing trees
to tracing log, we should try to continue printing the complete
trees which makes debugging easier.

Dont crash when seeing invalid tree while tracing

---

fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/JitTestUtilitiesTest.cpp

This change set introduces the SKIP_IF macro, which allows Tril-based compiler tests to be conditionally skipped without failing or disabling the test. This commit only intends to introduce the syntax for skipping tests and the underlaying machinery needed for skipping test execution. Support for features such as logging and reporting of skipped tests is still primitive. No built-in support for platform detection is provided.
The basic syntax is for skipping a test is:
SKIP_IF(<condition>, <reason>);
The <condition> parameter can be any boolean expression and specifies when a test should be skipped. The <reason> parameter must be a value from the `SkipReason` enum; it is mainly intended for use in logging and reporting, although the current implementation makes little use of it. …

 Implement a primitive SKIP_IF macro to allow tests to be skipped

---

ddr/include/ddr/scanner/pdb/PdbScanner.hpp
ddr/lib/ddr-scanner/pdb/PdbScanner.cpp

If filename does not end with '.pdb', assume the file is an exe/dll file

DDR: allow ddr-scanner to handle exe/dll files

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

* Relocate CodeCache::allocate function to CodeCacheManager
* Delete unused functionality from CodeCacheManager
* Remove reservationInterfaceCache from CodeCacheManager

Misc. CodeCacheManager API refactoring

---

compiler/optimizer/VPHandlers.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/CallSnippet.cpp
compiler/z/codegen/ConstantDataSnippet.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

This pull request contains three main changes. 
1. Update relocation on Z codegen to support Symbol Validation Manager on Z if it is enabled. 
2. SideEffect guard is not supported in AOT yet though it was generated if Symbol Validation Manager, this caused a potential bug where we are left with Sife Effect guard node in AOT compiled body with no relocations. 
3. Fix x86 Codegen to check if it is compiling relocatable method first so that we do not miss assert in case we encounter a virtual guard that is not supported under AOT. 

Support Symbol Validation Manager on Z

---

compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

The following have been relocated to OpenJ9:
* lateInitialization
* addFreeBlock
* almostOutOfCodeCache
* printMccStats
* printRemainingSpaceInCodeCaches
* printOccupancyStats
Also, delete unused code guarded with `CODECACHE_STATS`.

Remove deprecated OMR CodeCacheManager methods

---

compiler/optimizer/Inliner.cpp

In practice we never enable methodEnterTracing without methodExitTracing.
These two methods are replaced with isMethodTracingEnabled().
Reference issue: eclipse/openj9#3585

Replace enter/exit tracing method with isMethodTracingEnabled

---

port/linux/omrvmem.c
port/unix_include/omrportpg.h
port/ztpf/omrvmem.c

As mentioned in the OpenJ9 issue [#3797](https://github.com/eclipse/openj9/issues/3767) [PortLibrary](https://github.com/eclipse/omr/blob/b21d26c497f0a49736bb39897cc8e012e45df2cf/port/linux/omrvmem.c#L174) and [ThreadLibrary](https://github.com/eclipse/omr/blob/f8fc704032f95cbc0f337eb6be54f2b06e58a773/thread/linux/omrthreadnuma.c#L149) are not having a consistent view on NUMA which is making JVM to crash if its running in container (default docker or any environment where `getmempolicy` system call is restricted) with balanced gc policy. 
This Fix would allow the PortLibrary to get node count and set the memorystate to `J9NUMA_DENIED` if there is a failure in `getmempolicy` system call due to only `security restriction like EPERM - Operation Not Permitted`
FYI @LinHu2016 @ashu-mehra …

Added changes to resolve the balanced gc policy crash in container

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

There are confusingly two independent means in CodeCacheManager for
testing/setting whether the code cache is full.  Neither is behaving
as it should.
The `setCodeCacheIsFull` is never used in OMR nor any downstream project,
although the flag is tested on code memory allocation failure in
`OMR::CodeGenerator::allocateCodeMemoryInner`.
The `setCodeCacheFull` does not have an implementation in OMR (it does
in downstream projects), yet it is invoked in a number of spots in OMR.
Unify the functionality of these functions such that `setCodeCacheFull`
sets the boolean indicating that the code cache is full.  Remove the
`setCodeCacheIsFull` and `codeCacheIsFull` functions.

Unify and fix codeCacheFull functionality

---

compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

* Use 'usingRepository' queries to improve code readability
* Rename `getNewCacheMemorySegment` to the more meaningful
`getNewCodeCacheMemorySegment`

Misc. CodeCacheManager readability improvements

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/optimizer/VPHandlers.cpp

The API supportsNativeLongOperations() is not required and its use is
directly replaced by the API's definition.
Closes: #1864
Signed-off-by: Somesh Sharma <someshsharma0312@gmail.com>

Remove unnecessary API supportsNativeLongOperations()

---

compiler/z/codegen/OMRMemoryReference.cpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390GenerateInstructions.hpp
compiler/z/codegen/S390Instruction.hpp

Fix vector load/store instruction large displacement bug
Fix a problem in VRS, VSI, and VRV vector-storage instruction
formats to handle large displacements correctly.
The fix consists of two parts: an instruction selection phase change and
a binary encoding change. Both of these changes aim to use a scratch register
to hold the base+displacement value if a vector load/store instruction has a
displacement that exceeds the 12-bit signed integer range.

Fix vector load/store instruction large displacement bug

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/JitTestUtilitiesTest.cpp
fvtest/compilertriltest/main.cpp

The JitTest test fixture now has a static field intended to "hold" the
port library object. Two static member function are also added to the
class to initialize and shutdown the library. These are called from
the SetUp() and TearDown() methods of a global gtest environment.
One use case for having the port library available in Tril-based tests
is to skip tests conditionally. For example, using the following line
would cause a test to be skipped if it is executed on x86 and some
variable `foo` is 0:
```c++
SKIP_IF(OMRPORT_ARCH_X86 == omrsysinfo_get_CPU_architecture() && 0 == foo);
```

Make the Port Library a comptest dependency 

---

fvtest/porttest/si.cpp
port/common/omrsysinfo.c
port/unix/omrsysinfo.c

Also update tests.
Fixes 
https://github.com/eclipse/omr/issues/3501
(note: some code moved inside an if statement, resulting in whitespace-only changes)

Add RLIMIT_NOFILE support to omrsysinfo_set_limit

---

compiler/z/codegen/BinaryAnalyser.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRMemoryReference.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

Remove isAddressOfStaticSymRefWithLockedReg() and
isAddressOfPrivateStaticSymRefWithLockedReg() since they always return
false.

Remove dead code

---

gc/base/NUMAManager.hpp

Field idicates if gc should be modifying the affinity of mutator threads

Add shouldSetCPUAffinity field to NUMAManager

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp

In practice we never enable methodEnterTracing without
methodExitTracing. These two methods are replaced by
isMethodTracingEnabled(). Reference issue:
eclipse/openj9#3585

Remove enter/exit tracing methods

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

With the change to generate instructions for array copy
direction test in codegen, we had a bug in case of constant
byte length array copy.
As it is constant byte length array copy, we exploit that information
in our forward direction copy path where we generate loop and encode
instruction with known constant length so in this case byte length
node won't be evaluated. In case of backward array copy we need to load
length into register where it will be used in the copying loop.
This leaves us with a diamond case where we have clobber evaluated
a byteLen node in one path but did not evaluate it in other path.
This was causing a rare bug when you have a constant length array copy
whose byte length node has more than one references and we end up using
a register set to the constant node which …

Fix bug in arraycopy evaluator for constant byte length

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.cpp

isRotateAndMask() API is just power specific and hence, getting rid of
it from the common codegen. Also, removing deprecated opcodes.
Closes: #1876
Signed-off-by: Somesh Sharma <someshsharma0312@gmail.com>

Remove common implementation of isRotateAndMask(...)

---

.appveyor.yml

As of cmake 13.3, users must specify a source directory. Due to an old
typo in the appvyeyor config, the source directory "./" was attached to
the end of the cache name.
This PR adds back the missing space between the initial cache file and
the source directory.
Fixes: #3559

Fix typo in specifying cmake source dir

---

port/win32/omrfile.c
port/win32_include/omrportptb.h

1. Rename file_get_unicode_path() to port_file_get_unicode_path()
2. Similar to port_convertFromUTF8(), export
port_file_get_unicode_path() so
that it can be used if we need to know the file unicode path on Windows.
Related to https://github.com/eclipse/openj9/issues/4351
Signed-off-by: hangshao <hangshao@ca.ibm.com>

Export file_get_unicode_path() through omrportptb.h

---

compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/S390Evaluator.hpp
compiler/z/codegen/TreeEvaluatorTable.hpp

The OMRTreeEvaluator.cpp file is very large, totaling at over 18000
lines. GitHub does not play nice with large files as we hit certain
line limits and size limits [1]. As a first step in cleaning this up we
remove all unused evaluators which we do not foresee using in the
future.
Next step will be to do a big code migration of a ton of OpenJ9
evaluators into the OpenJ9 codebase. This commit however should
alleviate the immediate issue.
[1] https://help.github.com/articles/limits-for-viewing-content-and-diffs-in-a-repository/

Remove dead evaluators from OMRTreeEvaluator.cpp in Z codegen

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp
compiler/compile/OMRSymbolReferenceTable.cpp

`getMethodFromName()` is used for fabricating calls to methods about which the compiler has special knowledge. Since these names originate in the compiler (and not in any particular method we happen to be compiling), the lookups should behave as such, so the `callingMethod` is irrelevant.

Remove callingMethod from getMethodFromName()

---

fvtest/compilertest/Jit.hpp
fvtest/compilertest/control/TestJit.cpp
fvtest/compilertriltest/BitPermuteTest.cpp
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/ShiftAndRotateTest.cpp
fvtest/compilertriltest/TypeConversionTest.cpp
fvtest/compilertriltest/main.cpp
fvtest/tril/examples/incordec/main.cpp
fvtest/tril/examples/mandelbrot/main.cpp
fvtest/tril/test/JitTest.hpp
fvtest/tril/test/main.cpp
fvtest/tril/tril/CMakeLists.txt
fvtest/tril/tril/compiler.cpp

The dependency on JitBuilder is broken by only providing the Test
Compiler as a target link library. A few workarounds for JitBuilder's
new client API are also removed. Lastly, the function to initialize the
Test Compiler with specific options is also exposed.

Use the Test Compiler with Tril tests instead of JitBuilder

---

compiler/env/FEBase_t.hpp
compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

It is more readable and intuitive if the helper you're asking about
is the first parameter.  Fixup uses of this API.
The original API remains in the code and simply redirects to the new
API, and will be removed once downstream projects have been changed.

Transpose parameters to findHelperTrampoline

---

compiler/optimizer/Inliner.cpp
compiler/optimizer/Inliner.hpp

Inliner and several local transformations inside Inliner are using
visitcount to track visited nodes or call nodes that has already been
inlined and the code logic interferes with each other. Changing the
local transformations in Inliner to use NodeChecklist. Global use of
visitcount in Inliner needs more investigation and will be fixed in a
separate commit
https://github.com/eclipse/openj9/issues/3340

Replace visit count in Inliner with node checklist

---

compiler/codegen/Relocation.cpp
compiler/runtime/Runtime.hpp

For the Power codegen to work correctly with the newly implemented
Symbol Validation Manager for AOT, a couple new relocation types need to
be added:
1. TR_DiscontiguousSymbolFromManager represents a discontiguous load
sequence that needs to be relocated with a symbol from the SVM
2. TR_ResolvedTrampolines represents the need to reserve a trampoline
for a resolved method

Add Power-specific relocation types needed for SVM AOT

---

compiler/codegen/Relocation.cpp

Previously, there was special-case code in the collectModifier method on
TR::ExternalRelocation which was trying to handle relocations whose
targets were actually the address of the TR::Instruction rather than the
binary-encoded instruction. However, this is now being handled by
TR::BeforeBinaryEncodingExternalRelocation overriding the
getUpdateLocation method. As a result, this check was calculating the
wrong update location. The apply method was using the correct update
location and thus only calculation of whether wide offsets were needed
was affected by this problem.
This issue went unnoticed for a considerable length of time since the
pseudo-random nature of the incorrect update location would almost
always result in wide offsets being used. Using wide offsets when not
needed is …

Fix check for whether wide relocation offsets are needed on Power

---

compiler/z/codegen/OMRCodeGenerator.cpp

Migrate randomgen architecture disabling from OpenJ9 to OMR

---

compiler/runtime/OMRCodeCacheManager.cpp

The cast is required in order to change the return type of
`findHelperTrampoline` to a `intptrj_t` to allow downstream
projects to continue to build without breaking.

Provide explicit cast for findHelperTrampoline

---

ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp

Parser was writing signed data to udata field instead of sdata.

Fix ddrgen parsing signed data attributes on OSX

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCache.hpp

Fix one final reference to now call reserveSpaceForTrampoline.

Remove deprecated functions reserveTrampoline/unreserveTrampoline

---

include_core/omrthread.h
thread/common/omrthread.c

If set, forked threads will not have their affinity modified unless a
non-zero affinity mask has been specified.

Add J9THREAD_LIB_FLAG_NO_DEFAULT_AFFINITY thread library flag

---

example/glue/ScavengerDelegate.hpp

The field was accidentally omitted when moving code.

Add _extensions field to example ScavengerDelegate

---

gc/base/MemoryPoolSplitAddressOrderedListBase.cpp
gc/stats/LargeObjectAllocateStats.cpp
gc/stats/LargeObjectAllocateStats.hpp

Log() calculation can be broken in OS or output of the function might be
corrupted. This change improves assertions output.

Improve assertion output for large object stats

---

compiler/optimizer/CMakeLists.txt
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/SwitchAnalyzer.cpp
compiler/optimizer/SwitchAnalyzer.hpp
fvtest/compilertest/build/files/common.mk
jitbuilder/build/files/common.mk
jitbuilder/optimizer/JBOptimizer.cpp

Recent testing using JB Switch did not show the performance I was
expecting. Moving the SwitchAnalyzer from OpenJ9 to OMR provides
a 25-30% improvement to my testing.

Move SwitchAnalyzer from OpenJ9 to OMR

---

compiler/aarch64/CMakeLists.txt
compiler/aarch64/runtime/CodeSync.cpp
compiler/codegen/OMRCodeGenerator.cpp
jitbuilder/build/files/host/aarch64.mk

This commit implements arm64CodeSync() using a GCC built-in function,
and adds a call to it in OMR::CodeGenerator::syncCode().

AArch64: Implement arm64CodeSync()

---

compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRConstantDataSnippet.cpp
compiler/p/codegen/OMRMemoryReference.cpp
compiler/p/codegen/PPCBinaryEncoding.cpp

This PR adds support to the Power codegen to generate `TR_SymbolFromManager` and `TR_DiscontiguousSymbolFromManager` relocations where necessary instead of the old relocation types when SVM is enabled.

Add support for generating SVM relocations on Power

---

compiler/compile/OMRCompilation.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OSRDefAnalysis.cpp

OSR live range analysis and OSR def analysis gathers information to
decide what to copy into the OSR buffer during OSR transition. This
should not change regardless of when they are performed. Optimizations
can create nodes with incorrect bytecode index. Those nodes are usually
not important and side effect free, such as `iconst` node. However, such
nodes bring difficulty on OSR live range analysis and OSR def analysis
since the two opts rely highly on the correctness of bytecode info.
Thus, move then up as the first two ilgen opts.
Also fix two minor issues found in OSR live range analysis.

Run OSR live range analysis and OSR def analysis first

---

fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/LinkageTest.cpp
fvtest/compilertriltest/TypeConversionTest.cpp

Microsoft x64 calling convention brings addition limitations for x86-64:
only four registers are available for arguments (not four for integer
and four for float but four for both). Also the caller has
responsibility to allocate 32 bytes of "shadow space" on the stack right
before calling the function (regardless of the actual parameters used).
Two tests are added to check these circumstances: the first just
demonstrates how to invoke a method with five arguments while the second
one invokes a method who is actively using the stack and can corrupts
the return address if no "shadow space" has been allocated.
Issue: #3366

Add linkage tests for Microsoft x64 calling convention

---

compiler/x/codegen/X86BinaryEncoding.cpp

This patch fixes a pile of bad casts where we're converting from a 32bit
integer to a 64bit pointer. The warnings are silenced by performing an
intermediate cast to a uintptr_t, before casting to a pointer.

Explicitly widen the source immediate before casting to pointer

---

compiler/aarch64/codegen/UnaryEvaluator.cpp

There was a minor issue in the previous lneg evaluator implementation. When calling the generateNegInstruction(), the boolean value should be true in the parameter for lneg evaluator. In previous implementation this boolean value is missing and so in this commit I updated that.

AArch64: Fix lnegEvaluator to correctly generate 64-bit negate instruction

---

compiler/infra/Assert.cpp

In J9, [traceAssumeFailure](https://github.com/eclipse/openj9/blob/master/runtime/compiler/env/VMJ9.cpp#L5443-L5446) has been disabled, so calling it has no
effect. This is the only call site, so once it is removed,
traceAssumeFailure can be removed from the J9 VM.

Remove call to VMJ9 traceAssumeFailure

---

compiler/ras/Debug.hpp

It's now safe to delete this unused OpenJ9-specific declaration.

Remove TR::X86UnresolvedVirtualCallSnippet print

---

compiler/control/CompileMethod.cpp
compiler/runtime/OMRCodeCache.cpp
fvtest/compilertriltest/BitPermuteTest.cpp
fvtest/compilertriltest/LogicalTest.cpp
fvtest/compilertriltest/MaxMinTest.cpp
include_core/omrformatconsts.h

Introduce a new header, `omrformatconsts.h`, which defines a set of portable constants for building format strings for special integral types. This header  provides platform-independent format specifiers for the following data types:
- int8_t / uint8_t
- int16_t / uint16_t
- int32_t / uint32_t
- int64 / uint64_t
- size_t
- intptr_t / uintptr_t
- ptrdiff_t
The following formats are provided in this PR:
- x: unsigned hexadecimal format
- u: unsigned decimal format
- d: signed decimal format
(notably missing: i)
Normally, there are either special macros defined by the C library, or
special format characters in the case of size_t / ptrdiff_t.
Unfortunately, because of poor standards compliance across our
compilers, these aren't universally available.
The names of the constants follow the …

Clean up c-style formatting

---

gc/base/GCExtensionsBase.hpp

Usage of GC Concurrent Background thread use to create long pauses on
Exclusive Access. This limitation is not necessary any more. 

Remove obsolete limitation on zLinux

---

compiler/x/codegen/OMRMachine.cpp

Registers objects have vtables that should not be overwritten. Memcpy
will overwrite the entire memory of the object, including the vtable,
and clang doesn't like this. Just use regular assignment instead, which
should be equivalent.

Do not memcpy registers objects, copy by assignment

---

compiler/x/codegen/OMRMachine.cpp

There are a few places where we perform a deep copy of arrays of
register objects in the X OMRMachine. This used to be implemented by
memcpy'ing the elements over copies. In translating this code from using
memcpy to simple assignment, I forgot to dereference the register
pointers in the array. The result is that the array is shallow-copied,
which is very wrong. This PR adds the missing dereference operators, so
now the objects will be deep copied into the new array as intended.
The PR that introduced the error was #3604.

Add missing dereference in copying register arrays

---

jitbuilder/apigen/cppgen.py

The jitbuilder public headers use types from stdint.h, without including
it. This patch adds the missing include, so users won't have to deal
with getting their includes in the right order. I've also included
stddef.h, if only for good measure. stddef defines NULL, size_t, and
ptrdiff_t.

Include system headers in jitbuilder API headers

---

include_core/omrformatconsts.h

u mean "unsigned integer", x means "unsigned integer in hex".

Typo: use x to print in hex, not u

---

ddr/lib/ddr-blobgen/CMakeLists.txt
ddr/lib/ddr-ir/CMakeLists.txt
fvtest/coretest/TestBytes.cpp
include_core/OMR/Bytes.hpp

Update limit constants to use numeric_limits<size_t>::max()
Instead of SIZE_MAX 
Update limit constants to use numeric_limits<uint32_t>::max()
Instead of UINT32_MAX
Updates fix Linux build

Update limit constants to use numeric_limits<>::max()

---

fvtest/porttest/si.cpp
include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

Also add unit test
This replaces the legacy `j9sock_gethostname()`.
Fixes in part https://github.com/eclipse/openj9/issues/1123.

Add omrsysinfo_gethostname

---

compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/env/OMRCPU.cpp
compiler/x/env/OMRCPU.hpp

- Remove unused parameter (TR::Compilation *comp)
- Add missing supportsHLE() to TR_X86ProcessorInfo
- Remove J9_PROJECT_SPECIFIC macro in OMR::X86::CPU::queryX86TargetCPUID()

Clean up x/env/OMRCPU class and add missing supportsHLE()

---

compiler/ilgen/OMRVirtualMachineOperandStack.cpp
compiler/ilgen/OMRVirtualMachineOperandStack.hpp
jitbuilder/apigen/jitbuilder.api.json

The first parameter to VirtualMachineState::MergeInto is declared
as `VirtualMachineState *`. In the client API and in
VirtualMachineOperandStack the first parameter is defined to be
the subclass type which Clang warns about.

Fix warning `hides overloaded virtual function`

---

compiler/codegen/OMRRegister.cpp
compiler/codegen/OMRRegister.hpp
compiler/p/codegen/BinaryEvaluator.cpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/X86Evaluator.hpp

* Remove unused _cc OMR::Register field
* Remove obsolete P and X86 condition code manipulation functions
* Remove obsolete genCodeToPerformLeftToRightAndBlockConcurrentOpIfNeeded
* Remove unused X86 extern for constLengthArrayCopy

Misc. dead code cleanup

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

Not used in OMR nor any known downstream project:
* _nodesUnderComputeCCList
* _nodesToUncommonList

Remove unused lists from CodeGenerator

---

cmake/config.cmake
compiler/codegen/OMRInstruction.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
jitbuilder/apigen/jitbuilder.api.json
jitbuilder/release/CMakeLists.txt
jitbuilder/release/cpp/samples/OperandStackTests.cpp

I recently discovered that many of our extended JitBuilder sample tests (which cannot be run safely on all platforms) are not being run on the x86 platforms where they can run safely. On top of that, one of the samples (OperandStackTests) was broken.
I also found that the JitBuilder API description for VirtualMachineOperandStack constructors was not quite right (and we probably didn't discover that because the tests weren't being run).
This PR includes a fix for the OperandStackTests failure, a fix for the API description, and the extended JitBuilder testing is enabled for X86 platforms so hopefully we won't end up in this state again.
Finally, I also fixed a couple more compiler warnings (one in the optimizer, which I *believe* is the last exposed warning in the entire optimizer, which …

Recover x86 jit builder testing

---

compiler/codegen/OMRLinkageConventions.enum
compiler/ras/Debug.cpp

* TR_AllRegister
* TR_InterpretedStatic
Are not used in OMR nor any known downstream project.

Remove unused linkage conventions

---

compiler/il/symbol/OMRSymbol.hpp
compiler/il/symbol/OMRSymbol_inlines.hpp
compiler/optimizer/VPHandlers.cpp

Optimize the generalized pattern `Field1 f1 = o.field1; if (f1==null) initialize_f1; Field2 f2 = f1.field2; if (f2==null) initialize_f2` where `o` is a known object. If value of `f1` is null, it is initialized just once to a valid non-null value and does not change; similarly, if `f2` is null, it is also initialized to a valid non-null value and also does not change during entire run time. If `o` is a known object. VP loads `f1` at compile time and checks for null. A non-null value means it has been initialized so we treat it as a known object and attach known object, non-null, and fixed class constraints. In the loading of `f2`, the newly propagated known object constraint is attached to the base object `f1`, so again we do a compile-time load of `f2` and attach the appropriate …

Optimize sequential recognized object shadow field loads in VP

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRLinkage.hpp

* remove obsolete functions not used in OMR nor any known downstream project
* use TR_UNIMPLEMENTED rather than bespoke macros
* logically re-order function declarations

Misc. Linkage base class cleanup

---

compiler/x/codegen/ControlFlowEvaluator.cpp

For non-Java projects the register dependencies for GlRegDeps were not
added to the indirect jump instruction, leading to incorrect register
assignment.  Add the appropriate register dependencies.

Correct register dependencies for x86 tableEvaluator

---

fvtest/porttest/si.cpp
port/unix/omrsysinfo.c

If user tries to set the soft limit of file descriptors to unlimited on MacOS,
use the system limit instead.
Add unit  test.
Fixes https://github.com/eclipse/omr/issues/3579

Use system limit on file descriptors  for soft limit

---

include_core/omrformatconsts.h

X is for "uppercase hex" formatting.

Add X format consts to omrformatconsts.h

---

fvtest/jitbuildertest/CMakeLists.txt

By making the source private, we no longer have to worry about giving an
absolute path to the source.
CMake Warning (dev) at fvtest/jitbuildertest/CMakeLists.txt:42 (target_sources):
Policy CMP0076 is not set: target_sources() command converts relative paths
to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
An interface source of target "jitbuildertest" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

Fix jitbuildertest CMake warning

---

fvtest/compilertriltest/ArithmeticTest.cpp

The Tril change is to help the compiler distinguish between the
overloads that exist for the `fadd`, `fsub`, `fmul`, and `fdiv`.

Fix Tril template deduction in ArithmeticTest

---

cmake/modules/OmrTracegen.cmake

Old warning message was quite verbose, and not a real warning.  By
changing the message to status the output is less alarming.
From:
```
CMake Warning at cmake/modules/OmrTracegen.cmake:32 (message):
OMR: No trace root has been set.  Defaulting to
'/home/aryoung/wsp/omr/build'
Call Stack (most recent call first):
CMakeLists.txt:43 (include)
```
To:
```
-- OMR: No trace root has been set. Defaulting to '/home/aryoung/wsp/omr/build'
```

Change OmrTracegen message from a warning to a status

---

gc/verbose/schema.xsd

- add new element <regions> under gc-op-copy-forward to report
the numbers of eden regions, nonEden regions in collection set
and the 	numbers of regions are scheduled for evacuation and mark.

new element <regions> in gc-op-copy-forward

---

cmake/modules/CMakeASM-ZOSInformation.cmake

Add missing -c option when  compiling zos assembly files

---

compiler/infra/OMRMonitor.cpp

When the Windows support was added, or maybe after some subsequent
bad merge happened, it looks like a #if for the Windows platform
was missed or removed from OMR::Monitor::init(), leaving a double
call to MUTEX_INIT. This commit wraps the code in the proper
conditional #if...#else...#endif analogous to similar code in
the destroy(), enter(), and exit() functions.

Fix double initialization of MUTEX in OMRMonitor.cpp

---

compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp

Current implementation of Node::computeIsCollectedReference cannot handle
ternary nodes as it is unaware of the two value children, both of which
may need to be checked in order to answer its collected-ness. This change
provides support for ternary nodes by recursively calling the API on the
true-value child, and then, if the answer is inconclusive (i.e. true-value
node is a NULL constant), on the false-value child node. The recursion
continues if a value child is itself a ternary node. The existing
implementation logic is preserved and reused in the tail call to answer
the collected-ness of the value child nodes. The current implementation of
computeIsCollectedReference is refectored into a private method
`computeIsCollectedReferenceImpl` which preserves the logic and existing
behavior …

Node API computeIsCollectedReference support for ternary node

---

cmake/CheckSourceTree.cmake

The message was being printed as a diagnostic.

Stop printing the CMAKE_SRC_DIR when running cmake

---

compiler/z/codegen/BinaryAnalyser.cpp
compiler/z/codegen/BinaryCommutativeAnalyser.cpp
compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/S390GenerateInstructions.hpp
compiler/z/codegen/UnaryEvaluator.cpp

These macros have multiple definitions and are causing issues in debug
mode on z/OS. However the macros themselves are not very useful and are
actually expensive during tracing while providing no real value.

Deprecate PRINT_ME and TRACE_EVAL macros on Z

---

compiler/aarch64/runtime/VirtualGuardRuntime.cpp

This commit adds VirtualGuardRuntime.cpp in compiler/aarch64/runtime
to declare _patchVirtualGuard().  It is not implemented yet.

AArch64: Add VirtualGuardRuntime.cpp

---

tools/tracegen/Port.cpp

If the provided path is longer than `EsMaxPath`, the buffer containing the
unicode path will be prematurely freed

Fix use after free bug in Port::omrfile_stat

---

tools/tracegen/CFileWriter.cpp
tools/tracegen/DATFileWriter.cpp
tools/tracegen/TraceHeaderWriter.cpp

Make tracegen not output any information unless verbose is enabled.

Reduce default output of tracegen

---

compiler/x/codegen/FPTreeEvaluator.cpp

For 64-bit x86 targets simply XOR the register rather than using a
10-byte immediate load to the register.

Optimize floating point store of constant +0.0

---

include_core/AtomicSupport.hpp

From eclipse/openj9#4797:
```
While we are at this issue, the so-called AtomicSupport drop/restore priority
primitives need to be different for AIX and pLinux, because they choose
different default hardware priority. AIX default priority is Medium (i.e. 4),
while pLinux default is Medium-Low (i.e. 3).
The current implementation is suitable to AIX (dropping to Low -- i.e. 2,
restoring to Medium). It is not suitable for pLinux (restoring to Medium which
is higher than the platform default). The suggestion for pLinux is: dropping
to Very-Low -- i.e. 1; restoring to Medium-Low which is the platform default).
The instruction to drop to Very-Low is: or r31, r31, r31;
The instruction to restore to Medium-Low is: or r6, r6, r6;
```

Update the drop/restoreSMT hints for PPC

---

compiler/codegen/OMRCodeGenerator.cpp

When performing 64-bit signed division by a constant which is not a
power of 2, the division can be replaced with a multiplication using
some fixed point arithmetic trickery. Our previous implementation of
doing this had some hard-coded magic values for common divisors. For
unknown historical reasons, the table containing the 64-bit magic values
was actually an array of 32-bit integers which were being read as 64-bit
integers.
However, the order of 32-bit integers in the aforementioned array was
assuming that the platform was little endian. On big endian platforms,
the values of this table were being read with the two 32-bit parts of
each of the 64-bit integers swapped. As a result, 64-bit signed divides
of non-constant values by certain large constants such as 0x300000000
were being …

Fix incorrect ldiv magic values on BE platforms

---

cmake/modules/OmrHookgen.cmake
cmake/modules/OmrTracegen.cmake

Add OMR_EXE_LAUNCHER variable which is prepended to the command line before
running executables compiled as part of the build.

CMake: Add OMR_EXE_LAUNCHER variable

---

gc/base/standard/PhysicalSubArenaVirtualMemorySemiSpace.cpp

In a rare case (with very small or no Nursery tilt), that Nursery
contraction triggers object movement (sliding), refuse to contract, if
Concurrent Scavenger (CS) is enabled.
Firstly, it may cause significant pauses, negating the low pause
benefits of CS.
Secondly, and more importantly, it's not safe to do in presence of CS.
The area being moved is hybrid Survivor and Allocate. Objects that have
just been allocated during concurrent phase of the cycle, and have been
hashed, would need to grow (by a hash slot). The current reference fix
up logic does not account of that, since STW Scavenger would move only
pure Survived objects, that already grew, if really needed.
Adjusting the fix up logic is not trivial if possible at all (would
probably need an additional pass to figure out what is to …

Prevent object movement in Nursery contract

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCache.hpp

Consolidate `CodeCache::reserveSpaceForTrampoline` and
`CodeCache::reserveNTrampolines` into a single function.  The
error handling functionality from `reserveNTrampolines` will
be incorporated in the merged function as current consumers
of `reserveSpaceForTrampoline` performed the same functionality
now anyway.
The merged function does not unreserve the code cache on failure
(as the current `reserveNTrampolines` function does) as that
functionality is beyond the scope of this function.  Downstream
consumers will need to be modified if they're expecting that
behaviour.
This PR introduces a temporary "bridge" function while necessary
downstream changes are made.  It will become the permanent function
when such changes are complete.

Prepare to consolidate trampoline space reservation functions

---

compiler/z/codegen/BinaryAnalyser.cpp
compiler/z/codegen/BinaryCommutativeAnalyser.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRInstOpCodeProperties.hpp
compiler/z/codegen/OMRInstruction.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/S390Peephole.cpp

This pull request enables fatal asserts in the OMRInstruction
constructor so that instructions not supported by the
architecture level will not be generated.

 Enable minimum ALS asserts as fatal in Z codegen

---

cmake/modules/platform/os/win.cmake
port/CMakeLists.txt

Don't just assume that its on the path

CMake: Search for windows message compiler

---

compiler/optimizer/GlobalValuePropagation.hpp
compiler/optimizer/OMRValuePropagation.cpp
compiler/optimizer/OMRValuePropagation.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/ValuePropagationCommon.cpp

Global value propagation currently handles loops using a two pass
strategy. On the first pass we do not consider constraints entering
the loop and compute a set of backedge constraints. This set of
constraints represents the information produced by an iteration of the
loop. We then process the loop again using the entry constraints and
selectively merge the backedge constraints where required. The current
def constraint merging logic considers backedge constraints only when a
def has not been seen on the current iteration of the loop. This is
insufficient - a definition must have been seen on all paths from the
loop header to the def constraint merge point to be able to ignore the
constraints on the backedge. The intuition here is that if a def has not
happened on some path from the …

Fix GlobalVP handling of backedge constraints

---

cmake/modules/OmrPlatform.cmake
cmake/modules/platform/toolcfg/msvc.cmake
cmake/modules/platform/toolcfg/msvc_exports.def.in
omrsigcompat/CMakeLists.txt

Currently only supported for MSVC

CMake: add support for exporting symbols from libraries

---

compiler/runtime/OMRCodeCache.hpp

For the following fields:
* _tempTrampolineBase
* _tempTrampolineTop
* _tempTrampolineNext
* _trampolineAllocationMark
* _trampolineReservationMark
* _trampolineBase

Add misc CodeCache getters and setters

---

cmake/config.cmake
include_core/unix/thrdsup.h

Check that platform is supported if OMR_THR_YIELD_ALG is enabled.
Previously, if it were enabled on an unsupported platform, the result
would be a link error due to undefined reference to `THREAD_YIELD_NEW`

CMake: Add validation to OMR_THR_YIELD_ALG option

---

compiler/z/codegen/BinaryEvaluator.cpp

There is some Java-ism built into the Z *div evaluators in which we
special case a few corner cases for Java. Technically this code does
not belong in OMR, however that is a separate issue (#3685).
In this commit we disable the need to generate such checks for unsigned
division.
Fixes: #3674

Fix handling of unsigned 32-bit and 64-bit division on Z

---

compiler/optimizer/VPHandlers.cpp

A value number is known obj in a block doesn't mean it's known object
every where in the program.

Change known obj constraint to block constraint

---

fvtest/compilertriltest/ArithmeticTest.cpp
fvtest/compilertriltest/JitTest.hpp

This PR adds tril tests that exercise the `iudiv`, `iurem`, and `ludiv` opcodes that implement unsigned division and remainder. Additionally, it tweaks the default constants used in tests that make use of unsigned 32- or 64-bit integers to cover more corner cases.

Add tril tests for iudiv, iurem, and ludiv

---

CONTRIBUTING.md

The purpose of this PR is two-fold:
1) Announce that a new series of labels will be introduced to better classify issues and pull requests.  The labels group the existing independent component labels (e.g., compiler, gc, port) together under a common prefix (`comp:`), and introduces further classifications based on operating system (`os:`), architecture (`arch:`), and bitness (`bits:`).  See the CONTRIBUTING.md file in this PR for details.
2)  Update the CONTRIBUTING.md file to describe the new issue and PR classification labels for components, operating systems, architectures, and bitness.

Update GitHub label information in CONTRIBUTING.md

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCache.hpp

* complete the API change for reserveSpaceForTrampoline
* route reserveSpaceForTrampoline_bridge to call reserveSpaceForTrampoline
* delete deprecated reserveNTrampolines

Substitute CodeCache::reserveSpaceForTrampoline_bridge

---

include_core/omrformatconsts.h

* include inttypes.h, not stdint.h.
* Fix typo in defining PRIx32.

Fix two mistakes in omrformatconsts.h

---

compiler/ilgen/IlInjector.hpp
compiler/ilgen/OMRIlType.hpp
compiler/ilgen/OMRIlValue.hpp
compiler/ilgen/OMRMethodBuilder.hpp
jitbuilder/apigen/cppgen.py

With the JitBuilder public API in place, env/TRMemory.hpp is now available everywhere, and 
we can fully define the TR_ALLOC macro everywhere.
As a work around in the internals of the JitBuilder API, we have to use the global new operator to allocate internal compiler types.

Define TR_ALLOC everywhere

---

compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/p/codegen/GenerateInstructions.cpp
compiler/p/codegen/GenerateInstructions.hpp
compiler/p/codegen/PPCBinaryEncoding.cpp
compiler/p/codegen/PPCInstruction.cpp
compiler/p/codegen/PPCInstruction.hpp

Currently ternary opcodes are not widely used, however there are upcoming
optimizer changes in CFG simplification that will generate more integer
and address-typed ternary opcoe (i.e. iternary, lternary, aternary). This
change fixes long ternary (lternary) evaluation on 32 bit platforms where
the result and operands need to be represented by register pairs, in all
various cases handled in evaluator; also, for address-typed ternary
(aternary), it marks the result register(s) as collected reference if
required.

Support of i/a typed ternary opcode on P codegen

---

gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

threadFinalReleaseCaches method is generalized to be used in a middle of
a Scavenger cycle, when we do not want to flush Copy Cache Remainders,
since they can be re-used later.
Additional parameter is introduced to control, if we want to be final
release (when remainders are abandoned) or not.
At all existing call sites we set the parameter to true and we used to
abandon them always, what makes this a non-functional change. Future
users will set the parameter to false when needed.

Thread final/non-final Release Caches

---

compiler/runtime/CodeCacheTypes.cpp
compiler/runtime/CodeCacheTypes.hpp
compiler/runtime/OMRCodeCacheManager.cpp

Make the mcc_printf macro an inline function
mcc_printf is a variable-like macro which aliases the token printf.
However, when CODECACHE_DEBUG is disabled, mcc_printf is defined to
nothing. When this happens, the arguments at each "call site" will stick
around as a parenthesized expression. These unused expressions generate
compiler warnings.
So a call like:
mcc_printf("hello %s\n", my_name);
is transformed to the expression:
("hello %s\n", my_name);
This PR makes mcc_printf a variadic function-like macro that calls
printf when CODECACHE_DEBUG is on, and expanding to nothing otherwise.
By expanding the entire call to nothing, we can ensure that there are no
leftover artifacts of the disabled code.
This PR also drops the additional test against the variable
CodeCacheDebug, which isn't …

Make mcc_printf a variadic function macro

---

compiler/arm/codegen/ARMBinaryEncoding.cpp
compiler/arm/codegen/ARMDebug.cpp
compiler/arm/codegen/OMRLinkage.cpp
compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/p/codegen/OMRInstruction.cpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/z/codegen/S390Instruction.cpp

Provide an API in the Compilation class for checking whether calling a
given method symbol represents a recursive call to the method currently
being compiled.  Use the API throughout the code generators.

Provide Compilation API for checking for recursive calls

---

compiler/z/codegen/Linkage.hpp
compiler/z/codegen/OMRLinkage.cpp
compiler/z/codegen/OMRLinkage.hpp

`Linkage(TR::CodeGenerator *cg)`
Provides sensible defaults for the linkage type and explicit linkage type.

Introduce new Z Linkage constructor

---

gc/base/GCExtensionsBase.hpp

- enable CopyForwardMarkCompactHybrid mode by default for fully
testing.
CopyForwardMarkCompactHybrid mode intends to avoid MarkCompactOnly
PGCs, which are caused by jniCritical or abort case during GMP.
it would improve the GC performance for the most cases, but in
some cases, it might be no performance difference or slight draw back.

Enable CopyForwardMarkCompactHybrid mode

---

gc/verbose/VerboseHandlerOutput.cpp
gc/verbose/VerboseHandlerOutput.hpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.hpp

Dedicated master GC thread in CS, which can report concurrent-start/end stanza races with some other asynchronous reporting (e.g. kickoff for concurrent mark)
1. Implementation for `enterAtomicReportingBlock` and `exitAtomicReportingBlock` with a lightweight lock. (Already implemented for Balanced and Metronome.. separate PR will be opened for OpenJ9 to make this common once OMR changes are in)
2. Introduced handleScavengeEndNoLock (wrapped by handleScavengeEnd), required by CS to avoid deadlock due to lock nesting. `handleConcurrentEnd` calls `handleScavengeEnd` with attempt to acquire a lock again, hence `handleScavengeEndNoLock` is called instead.
Fixes: #3619

Fix assertions in VerboseBuffer.cpp with CS

---

compiler/infra/Assert.cpp

The function which actually triggers a trap, `assumeDontCallMeDirectlyImpl`, cannot be marked as no-return, because it only traps when handling fatal assertions.
Since fatal_assertion doesn't call any no-return functions, it cannot be marked as no-return.
Remove the OMR_NORETURN attribute from fatal_assertion and silence a compiler warning.

 Make fatal_assertion actually "no return"

---

cmake/modules/platform/os/linux.cmake
example/glue/ArrayletObjectModel.hpp
fvtest/porttest/omrvmemTest.cpp
gc/base/Heap.hpp
gc/base/HeapSplit.cpp
gc/base/HeapSplit.hpp
gc/base/HeapVirtualMemory.cpp
gc/base/HeapVirtualMemory.hpp
gc/base/MemoryManager.cpp
gc/base/MemoryManager.hpp
gc/base/VirtualMemory.cpp
gc/base/VirtualMemory.hpp
gc/base/j9mm.tdf
gc/include/RootScannerTypes.h
glue/ArrayletObjectModel.hpp
include_core/omrport.h
port/CMakeLists.txt
port/aix/omrvmem.c
port/common/omrport.c
port/common/omrvmem.c
port/linux/omrvmem.c
port/omrportpriv.h
port/osx/omrvmem.c
port/win32/omrvmem.c
port/zos390/omrvmem.c
port/ztpf/omrvmem.c

Include one test in fvtest to test reserve API with file handles
This is the initial step for the upcoming arraylet double mapping API
which will be included in incremental subsequent PRs
Co-authored-by: Charlie Gracie <charlie.gracie@gmail.com>

Add double map API for LINUX and balanced GC policy

---

cmake/modules/platform/os/linux.cmake

This flag is used to indicate to external projects that OMR requires the
rt library to properly link.

Define OMR_NEED_RT for external projects 

---

fvtest/porttest/omrvmemTest.cpp
port/aix/omrvmem.c
port/linux/omrvmem.c
port/zos390/omrvmem.c

Some users store the identifier in the allocated
memory call from vmem_reserve_memory(). We therefore store the
mode in a temp, clear the identifier, then free the memory.
Add test against use-after-free memory usage.
One such example is the usage from J9JNIRedirectionBlock
where J9PortVmemIdentifier is put into a memory region
allocated using j9vmam_reserve_memory()
Update omrvmem_free_memory for aix, linux and zos390

Fix omrvmem_free_memory

---

example/glue/Object.hpp
example/glue/ScavengerDelegate.cpp
example/glue/ScavengerDelegate.hpp
gc/base/HeapLinkedFreeHeader.hpp
gc/base/ObjectModelBase.hpp
gc/base/standard/Scavenger.cpp
gc/structs/ForwardedHeader.cpp
gc/structs/ForwardedHeader.hpp
glue/ScavengerDelegate.cpp
glue/ScavengerDelegate.hpp
port/common/omrmem32helpers.c
port/common/omrportcontrol.c
port/unix/omrmem.c

Replace with OMR_GC_COMPRESSED_POINTERS. In every build, either both or
neither the flags are set. Removal of the flag definitions will follow
later.
[ci skip]

Remove uses of OMR_INTERP_COMPRESSED_OBJECT_HEADER

---

cmake/modules/OmrAssert.cmake

This matches behaviour of cmakes message() command.

CMake: add SEND_ERROR option to omr_assert

---

compiler/optimizer/VPHandlers.cpp

This change adds additional handling in value propagation for known
object arrays which have constant content. Enhancemetns include
folding of element access as well as folding of arraylength
operations.

Improved Value Propagation for Constant Arrays

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/control/OMROptions.hpp
compiler/control/OMROptions_inlines.hpp
compiler/env/OMRObjectModel.hpp
compiler/optimizer/LoopReducer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/ValuePropagationCommon.cpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

eclipse/omr#3168 has introduced new read/write barrier kind; and known
downstream projects have adopted it; therefore OMR is fully moving to
this new read/write barrier kind.

Adopt new read/write barrier kind

---

compiler/x/codegen/HelperCallSnippet.cpp
compiler/x/codegen/HelperCallSnippet.hpp

X86CheckAsyncMessagesSnippet has been deprecated and is not used by any
known downstream projects; hence removing it.

Remove deprecated X86CheckAsyncMessagesSnippet

---

compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/OMRX86Instruction.hpp
compiler/x/i386/codegen/OMRTreeEvaluator.cpp

1. Removed deprecated constructor and generation helper;
2. Consolidated private field initialization,

Code clean related to Label Instruction on X86

---

gc/base/MarkingScheme.cpp
gc/base/MarkingScheme.hpp
gc/base/ObjectScanner.hpp

Pass-by-reference is disallowed by coding standards. It makes code hard
to read. Pass pointer explicitly instead.

Remove pass-by-reference parameter

---

gc/base/standard/CompactScheme.cpp

Replace with GC_COMPRESSED_POINTERS
[ci skip]

Remove uses of INTERP_SMALL_MONITOR_SLOT

---

cmake/modules/platform/toolcfg/msvc.cmake

CMAKE_CONFIGURATION_TYPES is only set for multi-configuration generators
(eg Visual Studio). For single configuration generators (eg makefiles)
this will be empty, but we still need to remove configuration specific
flags.

CMake: Fix option handling for MSVC

---

compiler/il/OMRILOps.hpp
compiler/ilgen/OMRIlBuilder.cpp
compiler/ilgen/OMRIlBuilder.hpp
compiler/optimizer/VPHandlers.cpp
fvtest/jitbuildertest/CMakeLists.txt
fvtest/jitbuildertest/Makefile
fvtest/jitbuildertest/UnsignedDivRemTest.cpp
jitbuilder/apigen/jitbuilder.api.json

This PR adds `UnsignedDiv` and `UnsignedRem` services on `IlBuilder` to perform unsigned division and remainder. Unfortunately, due to the lack of an `lurem` opcode at this time, a hack is necessary to allow taking the unsigned remainder of two 64-bit numbers: namely, the remainder is calculated as `lhs - ((lhs / rhs) * rhs)`.
Additionally, a couple of bugs in the value propagator handlers for division and remainder have been fixed. Specifically, their special cases for `INT_MIN / -1` are no longer erroneously applied when the opcode being used is unsigned.

 Add JitBuilder services for unsigned division and remainder 

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp

This change adds APIs for creating temps with known obj index so
that the various local optimizations can see the known obj info
for temps without needing expensive global optimization like
global VP and global copy propagation.
Notice the existing API findOrCreateSymRefWithKnownObject always create
a symRef with known object index based on the given original symRef so
the symbols are shared by the 2 symRefs. It doesn't work for temps
because each temp symbol can only have one symbol reference.

Add APIs for creating temp symRef with known obj

---

compiler/il/symbol/OMRSymbol.hpp

The previous enum overlapped with IsNamed and both can be set for static
symbol.

Change enum for constant pool address symbol

---

compiler/aarch64/codegen/OMRLinkage.cpp
compiler/aarch64/codegen/OMRLinkage.hpp
compiler/arm/codegen/OMRLinkage.cpp
compiler/arm/codegen/OMRLinkage.hpp
compiler/codegen/OMRLinkage.cpp
compiler/codegen/OMRLinkage.hpp
compiler/codegen/OMRLinkage_inlines.hpp
compiler/p/codegen/OMRLinkage.cpp
compiler/p/codegen/OMRLinkage.hpp
compiler/x/codegen/OMRLinkage.cpp
compiler/x/codegen/OMRLinkage.hpp
compiler/z/codegen/OMRLinkage.cpp
compiler/z/codegen/OMRLinkage.hpp

* Move CodeGenerator object into base of OMRLinkage
* Consolidate Linkage convenience functions
* Make use of Linkage convenience functions
* Remove concrete CodeGenerator dependence from x86 Linkage base header

Rework OMRLinkage base class

---

compiler/compile/OMRSymbolReferenceTable.hpp
compiler/ras/Debug.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp

X86 CG now supports Atomic Compare And Swap.

Introducing Atomic Compare And Swap Support to X86

---

compiler/optimizer/IsolatedStoreElimination.cpp

This improves the cases recognized by the IsolateStoreElimiation
optimization. The optimization was previously recognizing
induction variables as not increasing when they were in fact
increasing. This change improves the recognition and more cases
can now be covered.
Also early in the optimization a nodes GlobalIndex was used to
check to verify that all defs were used within the current region.
This should be using the UseDefIndex to properly perform this check.

Improve coverage of IsolatedStoreElimination

---

compiler/control/OMROptions.hpp
compiler/ras/Debug.cpp

Remove last piece of dead code related to deprecated write barrier kind.

Code cleanup related to new read/write barrier kind

---

compiler/env/CMakeLists.txt
compiler/env/OMRVMMethodEnv.cpp
fvtest/compilertest/build/files/common.mk
jitbuilder/build/files/common.mk

Add an empty file for project-specialized method queries and functions.
The staged approach is needed to prevent downstream breakages.  The file
will be populated when downstream projects are modified to build the new
file.

Introduce OMRVMMethodEnv.cpp stub

---

gc/base/EnvironmentBase.hpp
gc/base/GCExtensionsBase.hpp
include_core/omr.h

APIs currently return true or false based on OMR_GC_COMPRESSED_POINTERS.

Add new APIs for mixed compressed mode

---

example/glue/GlobalCollectorDelegate.hpp
example/glue/ScavengerDelegate.cpp
example/glue/ScavengerDelegate.hpp
gc/base/Configuration.cpp
gc/base/GCExtensionsBase.hpp
gc/base/MemoryManager.cpp
gc/base/modronapicore.cpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/verbose/VerboseHandlerOutput.cpp
include_core/omr.h

In order to support both compressed and full pointers, code ifdeffed for
compressed or not must be changed.
Currently, OMR_GC_COMPRESS_POINTERS controls whether object references
are compressed or not. This needs to change to an optional runtime
check.
In the future, OMR_GC_COMPRESS_POINTERS will mean that compressed
references is a supported configuration. The new flag
OMR_GC_FULL_POINTERS will mean that uncompressed pointers are supported.
One or both of these will be allowed to be defined in a build.
For now, synthetically define OMR_GC_FULL_POINTERS only if
OMR_GC_COMPRESS_POINTERS is not defined (so
!defined(OMR_GC_COMPRESS_POINTERS) changes to
defined(OMR_GC_FULL_POINTERS)).
As a further migration step, add runtime checks (which currently
evaluate to true or false at compile-time) …

First pass of changes for mixed mode object references

---

ddr/tools/getmacros

* remove use of 'grep -h' as it's not supported on z/OS
* improve scraping of anotations from preprocessed code by using using 'xargs cat | grep' instead of 'xargs -L1 grep' to spawn fewer processes

Remove unnecessary use of grep '-h' option

---

.gitignore
buildenv/jenkins/jobs/builds/Build-aix_ppc-64
buildenv/jenkins/jobs/builds/Build-linux_390-64
buildenv/jenkins/jobs/builds/Build-linux_aarch64
buildenv/jenkins/jobs/builds/Build-linux_arm
buildenv/jenkins/jobs/builds/Build-linux_ppc-64_le_gcc
buildenv/jenkins/jobs/builds/Build-linux_x86
buildenv/jenkins/jobs/builds/Build-linux_x86-64
buildenv/jenkins/jobs/builds/Build-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/builds/Build-osx_x86-64
buildenv/jenkins/jobs/builds/Build-win_x86-64
buildenv/jenkins/jobs/builds/Build-zos_390-64
buildenv/jenkins/jobs/pull-requests/PullRequest-aix_ppc-64
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_390-64
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_aarch64
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_arm
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_ppc-64_le_gcc
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_x86
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_x86-64
buildenv/jenkins/jobs/pull-requests/PullRequest-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-osx_x86-64
buildenv/jenkins/jobs/pull-requests/PullRequest-win_x86-64
buildenv/jenkins/jobs/pull-requests/PullRequest-zos_390-64

Migrate Eclipse OMR Jenkins build and pull request pipelines from the
configuration panel of the jobs themselves into the repository so that
we may modify the respective pipeline steps within PRs.
There is some concern that this change may increase build times as
Jenkins has to check out the repository to fetch the pipeline
definitions. These are shallow checkouts however. To figure out how
much this change will affect build times I've compiled statistics on
the average build times for each platform of our current setup and how
long the "Get Sources" step takes in each case.
There are however several steps done in the "Get Sources" stage and the
git commands are as follows:
```
git init /home/jenkins/workspace/PullRequest-linux_x86-64
git --version
git fetch --tags --progress …
```

Add Eclipse OMR Jenkins build and pull request pipelines

---

compiler/optimizer/LoopVersioner.cpp

In `versionNaturalLoop`, the loop that is being versioned and its clone are placed into a new proper region, along with the loop's invariant block, all preceded by a sequence of conditions.  In the process, all edges to the invariant block are made to be edges to the sequence of conditions at the start of the region.
However, if the original loop had an exit to the invariant block, we end up with a situation where the new proper region structure has an exit edge from the cloned original loop that refers to the original
invariant block, even though that block is part of that region.
Also in that same situation, the subgraph node for the cloned original loop in the new proper region ends up pointing to itself.
Made some changes to the updating of the structures to consider this case.
Also …

Ensure structures are updated correctly for versioned loop

---

compiler/aarch64/codegen/OMRLinkage.hpp
compiler/arm/codegen/OMRLinkage.hpp
compiler/p/codegen/OMRLinkage.hpp

Subsumed by the versions in CodeGeneratorUtils.hpp.

Remove deprecated addDependency from Linkage files

---

include_core/unix/zos/leconditionhandler.h
port/common/omrportcontrol.c
port/win64amd/omrsignal.c
port/zos390/omr__le_api.h
port/zos390/omrsignal_ceehdlr.c
port/zos390/omrsignal_context.c
port/zos390/omrsignal_context_ceehdlr.c
port/zos390/omrsignal_context_ceehdlr.h
port/ztpf/omrsignal.c

- J9 was removed or renamed to OMR in the structures, functions and comments used in the omrsig library. 
- At some places, redundant code was removed.
- A macro with the old name is introduced to prevent breakage in the downstream projects. Such macros can be removed once the old names are no longer used in the downstream projects.
- These changes don't impact external projects.
- Related to https://github.com/eclipse/omr/issues/3713.

Remove J9 from omrsig* code [Part 2]

---

gc/base/IndexableObjectScanner.hpp

GC_IndexableObjectScanner(MM_EnvironmentBase *env,
GC_IndexableObjectScanner *objectScanner, uintptr_t splitAmount) is not
necessary as far as the only consumer do not use it any more

Remove unused constructor

---

compiler/z/codegen/OMRTreeEvaluator.cpp

Fix a bug in the ipopcnt evaluator by zeroing out the high 32-bit of a
64-bit input.

Fix a bug in the ipopcnt evaluator

---

cmake/modules/OmrDetectSystemInformation.cmake
include_core/omrcfg.h.in
include_core/unix/thrdsup.h
omrcfg.CMakeTemplate.h

For cmake builds determine appropriate semapahore implementation at
configure time. Autoconf builds just set value according to OS.

Find appropriate semaphore implementation

---

compiler/optimizer/Inliner.cpp
omrmakefiles/rules.ztpf.mk
port/ztpf/omrintrospect.c
port/ztpf/omrosdump_helpers.c
thread/common/thrprof.c

z/TPF had a build path change which needs to be propagated to the
build (redhat subpath is now gnu).  Additionally, z/TPF now supports
some features of getrusage.  A micro sleep was reduced during
system dump processing to improve reliability and performance.

Miscellaneous updates specific to z/TPF

---

example/glue/MixedObjectScanner.hpp
gc/base/ObjectScanner.hpp

Changing signature of GC_ObjectScanner::getNextSlotMap() to avoid using
parameters by reference. This is step 2. Step 1 was creation of
functions with new signature in OpenJ9, so it is ready and would not be
broken.  
However this change would break all other projects based on OMR -
correspondent functions signature should be updated accordingly.
Old signatures:
getNextSlotMap(uintptr_t &, bool &) or
getNextSlotMap(uintptr_t &, uintptr_t &, bool &)
New signatures:
getNextSlotMap(uintptr_t *, bool *) or
getNextSlotMap(uintptr_t *, uintptr_t *, bool *)

Change signature of getNextSlotMap()

---

gc/base/EnvironmentBase.hpp
gc/base/GCExtensionsBase.cpp
gc/base/GCExtensionsBase.hpp
include_core/omr.h

Add fields and code (under ifdef) to allow the language to choose
compressed or full pointers at runtime.

Add (disabled) code to allow runtime compressed refs

---

buildenv/jenkins/README.md

This readme describes some of the subtleties of setting up Jenkins on
z/OS to work with pipelines which are checked into a git repository.

Add buildenv/jenkins/README.md

---

compiler/env/OMRObjectModel.hpp

Retire the shouldReplaceGuardedLoadWithSoftwareReadBarrier() API.

Remove an unused query

---

port/aix/omrsignal_context.c
port/aix/omrsignal_context.h
port/common/omrsignal.c
port/linux386/omrsignal_context.c
port/linux386/omrsignal_context.h
port/linuxaarch64/omrsignal_context.c
port/linuxaarch64/omrsignal_context.h
port/linuxamd64/omrsignal_context.c
port/linuxamd64/omrsignal_context.h
port/linuxarm/omrsignal_context.c
port/linuxarm/omrsignal_context.h
port/linuxppc/omrsignal_context.c
port/linuxppc/omrsignal_context.h
port/linuxs390/omrsignal_context.h
port/osx/omrsignal_context.c
port/osx/omrsignal_context.h
port/win32/omrintrospect.c
port/win32/omrosbacktrace_impl.c
port/win32/omrosdump.c
port/win32_include/omrsignal.h
port/win64amd/omrsignal.h
port/zos390/omrsignal_context.h
port/ztpf/omrsignal.h
port/ztpf/omrsignal_context.h

In #3777, the copyrights were not updated.
Updating the copyrights for the files which were changed in #3777.
Related to https://github.com/eclipse/omr/issues/3713.

Update the copyrights, which were missed in #3777

---

include_core/unix/zos/leconditionhandler.h
port/linuxppc/omrsignal_context.h

In eclipse/openj9#5735, J9 renamed `J9*` to `OMR*` for the following structs:
- `J9ZOSLEConditionHandlerRecord` -> `OMRZOSLEConditionHandlerRecord`
- `J9UnixSignalInfo` -> `OMRUnixSignalInfo`
So, the wrapper macros for the above structs are no longer needed. Hence, the
defines for the two structs have been removed.
Related to https://github.com/eclipse/omr/issues/3713.

Remove wrapper macros to support structs with J9* naming

---

cmake/modules/ddr/DDRSetStub.cmake.in

CMake DDR: Fix bug where include paths and defines not properly passed

---

cmake/modules/OmrDDRSupport.cmake

CMake DDR: fix bug where cmake was re-run unnecessarily

---

compiler/env/OMRCPU.hpp
compiler/p/env/OMRCPU.cpp
compiler/p/env/OMRCPU.hpp
compiler/x/env/OMRCPU.cpp
compiler/x/env/OMRCPU.hpp
compiler/z/env/OMRCPU.cpp
compiler/z/env/OMRCPU.hpp

In Eclipse OpenJ9, I need to add an AOT feature flag for Transactional Memory (TM) in order to ensure consistency with regard to TM across the compile and load runs. However, as it turns out, the processor query for determining whether TM is enabled is different for each platform. If it was as simple as different names, I would've just `#ifdef`'d the different queries and moved on. However, on x86, the query isn't even in the `TR::CPU` class; it's initialized as a static member of the x86 codegen class, and the `initialize` method is private that can only be accessed by the x86 codegen class. 
This PR only contains changes that provide (for the most part) a wrapper around existing TM queries. The right thing to do would be to refactor all the code into the `TR::CPU` class, but that's a …

Add Platform Agnostic TM Query

---

cmake/modules/ddr/cmake_ddr.awk

CMake DDR: Fix bug where #undef statements were not recognized

---

compiler/compile/OMRCompilation.cpp

The hashing function used signed intger for varaible hash and seed,
which could lead to integer overflow. Fix the issue by changing the
signed integer type to unsigned.
Closes: #1794

Use unsigned integer for hashing algorithm

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

The _firstTimeLiveOOLRegisterList is only used in the the
OMR::Z::CodeGenerator class, but is defined and declared in the
OMR::CodeGenerator class. Thus, move the variable and its accessor
funcitons to Z CodeGenerator
Closes: #1893

Move firstTimeLiveOOLRegisterList to Z CodeGenerator

---

compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp

Enabled Missed Tree Evaluators in AArch64 Compiler
-Enable ladd, lsub, lmul, land, lor and lxor Tree Evaluators in AArch64 Compiler
-Evaluators Were Implemented But Not Enabled in "compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp"

Enabled Missed Tree Evaluators in AArch64 Compiler

---

cmake/modules/ddr/cmake_ddr.awk

CMake DDR: Ignore header include guards

---

cmake/modules/ddr/DDRSetStub.cmake.in

With the commit, properties are added to the ddr targets to allow user to
specify:
- Output file names for blob and superset files
- A blacklist file
- An overrides file

CMake DDR: allow user to specify extra options

---

include_core/omrcomp.h

C++-style comments confuse xlc on z/OS which complains about unterminated character literals.

Use C-style comments in C header file

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

The variable bool _afterRA was defined in OMR::CodeGenerator but was
only used in the Z CodeGenerator. The variable is therefore moved into
OMR::Z::CodeGenerator. However, I believe the
field is attempting to track that local register assignment (RA) has
already run. There is probably a better way to accomplish this using the
code generator phase enum.
Closes: #1898

Move _afterRA to OMR::Z::CodeGenerator class

---

compiler/codegen/CodeGenRA.cpp
compiler/il/symbol/OMRMethodSymbol.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopReducer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/VPHandlers.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

`isNoTemps` and `setNoTemps` are remants of a legacy project consuming
OMR and are no longer relevant.  Remove and fold code assuming `isNoTemps`
always returns false.

Remove OMR::ResolvedMethodSymbol NoTemps

---

port/linux/omrosbacktrace_impl.c
port/linux/omrvmem.c
port/unix/omrintrospect.c
port/unix/omrsl.c
port/unix/omrsysinfo.c

defining `_GNU_SOURCE` feature macro only if not defined to avoid redefinition error.
Signed-off-by: bharathappali <bharath.appali@gmail.com>

Fix _GNU_SOURCE redefinition

---

compiler/compile/OMRCompilation.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

Not useful in OMR nor any known downstream project.  Since the
property is never set, remove guarded code assuming it is set.

Remove unused unkilledTemp property from ResolvedMethodSymbol

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/Inliner.cpp

This method is a remnant of a legacy project consuming OMR.  It is
no longer relevant, and simply returns `getParameterList`.  Replace
all references with `getParameterList` and remove the `TR::Compilation *`
argument.

Replace ResolvedMethodSymbol::getLogicalParameterList

---

compiler/p/codegen/OMRLinkage.cpp
compiler/p/codegen/OMRLinkage.hpp
compiler/p/codegen/PPCSystemLinkage.cpp
compiler/p/codegen/PPCSystemLinkage.hpp

* Remove and fold calculateParameterRegisterOffset from Linkage
* Remove and fold calculateActualParameterOffset from Linkage
* Fold and simplify code in Power linkage saveArguments
* Unify float/double handling in Power linkage

Misc. Power linkage cleanup

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp

The code guarded with J9_PROJECT_SPECIFIC has been relocated to OpenJ9.

Relocate part of OMR::ResolvedMethodSymbol constructor to OpenJ9

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

`TR::Node *createOrFindClonedNode` function in `OMR::CodeGenerator` has only relevance to the OpenJ9 project. Therefore, remove it from OMR and relocate it to the `J9::CodeGenerator` instead. In addition, fix the spelling mistake on `_uncommonedNodes` and relocate it from OMR to J9.
Closes: #2068

Remove the createOrFindClonedNode function in OMR

---

port/unix/j9nlshelpers.c

OSX considers 'UTF-8' as a valid LC_CTYPE, and we never considered this
case, so we blindly copy that as the language name when we get it from
the LC_CTYPE env variable. 'UTF-8' is more like 'C' or 'POSIX' locale,
so just go with default language and region.
Fixes https://github.com/eclipse/openj9/issues/5705
fyi: @DanHeidinga

Add UTF-8 case when reading locale from LC_CTYPE

---

ddr/tools/ddrgen/CMakeLists.txt

ddrgen uses the thread library. It works in current builds because the
port library is a static lib and has a dependency on the thread library

CMake: Link ddrgen against thread library

---

omrmakefiles/rules.ztpf.mk

Very minor update for one of the vpaths used during z/TPF only builds.
The directory path change and we didn't correctly update the path to
reflect the correct name.

z/TPF Root VPATH Rename

---

cmake/modules/ddr/cmake_ddr.awk

CMake DDR: Add support for 'valuesandbuildflags' option

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

`OMR::CodeGenerator` has field `_nodesSpineCheckedList` that has only
relevance to OpenJ9. This commit removes the field from OMR.
closes: #1895

Remove CodeGenerator::_nodesSpineCheckedList from OMR

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

`OMR::CodeGenerator` has field `compressedRefs` that does not appear to do anything useful in OpenJ9. Therefore, remove the field by first deleting the references in OpenJ9. Then remove the initialization in OMR.
Closes: #1896

Delete _compressedRefs from OMR

---

include_core/AtomicSupport.hpp
port/aix/omrintrospect.h
port/unix/omrintrospect.c

xlC16 appears to be based on clang and now recognizes the
__GNUC__ defines.  Reorder this code so that the compiler
sees the __xlC__-specific case first.
+ additional changes to support xlc16
issue: #3775

Reorder defines so xlC16 finds the xlc before gnu

---

compiler/codegen/OMRCodeGenerator.hpp

This patch adds an overload function of
`incRefCountForOpaquePseudoRegister` but without parameters `cg` and `comp`. This is the
first out 6 steps to simpify function
`incRefCountForOpaquePseudoRegister` by using less parameters.
Issue: #1855

Overload function void incRefCountForOpaquePseudoRegister in OMR

---

compiler/p/codegen/BinaryEvaluator.cpp
compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/p/codegen/GenerateInstructions.cpp
compiler/p/codegen/GenerateInstructions.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRTreeEvaluator.cpp

There exists certain helper functions in the power codegen in various
evaluator files that should be moved to GenerateInstructions.cpp. This
commit moves these helpers to GenerateInstructions.cpp so all evaluator
files have easy access to to them.
Signed-off-by: Andrew Gao <andrewgao98@gmail.com>

Move helpers for generation to GenerateInstructions.cpp

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

The `OMR::CodeGenerator` has field `JniCallSites` that has only relevance in
OpenJ9. Therefore, move it to `J9::CodeGenerator`. This commit removes the
field from OMR.
Closes: #1894

Relocate JniCallSites to OpenJ9

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp

This patch removes declaration, initialization and reference to
`_snippetsToBePatchedOnRegisterNative` from OMR.
Closes: #3573

Remove _snippetsToBePatchedOnRegisterNative from OMR

---

port/common/j9nls.c

Delay looking up the NLS catalog (a slowish operation) if the NLS
message request supplies a default message and the locale is english.
This improves on https://github.com/eclipse/omr/pull/3812 in that's automatic and will still cause the catalog to be parsed when a request is made without a default message.

Avoid looking up the NLS catalog in en locale's with default msg

---

port/aix/omrintrospect.h
port/unix/omrintrospect.c
port/zos390/omrintrospect.h
port/ztpf/omrintrospect.c

The POSIX standard the type is `union sigval`. sigval_t is only provided
as a typedef convinience on linux

Stop using sigval_t

---

compiler/z/codegen/ConstantDataSnippet.cpp

This is a deprecated API and the list is never populated.  Remove the
remaining reference to fix a build break.

Remove reference to getSnippetsToBePatchedOnRegisterNative

---

gc/base/segregated/FreeHeapRegionList.hpp
gc/base/segregated/LockingFreeHeapRegionList.cpp
gc/base/segregated/LockingFreeHeapRegionList.hpp
gc/base/segregated/LockingHeapRegionQueue.hpp
gc/base/segregated/MemoryPoolSegregated.cpp
gc/base/segregated/RegionPoolSegregated.cpp
gc/base/segregated/RegionPoolSegregated.hpp

Main issue was that using metronome gc, a long pause occured when using large heap sizes. These changes address that issue.
- Added counters in both `LockingFreeHeapRegionList` and `LockingHeadRegionQueue`
- Counter is incremented by number of regions being added
- `LockingFreeHeapRegionList.cpp::getTotalRegions()` no longer has to iterate through a list to find count, as it just returns the count
- Reduces pause to only a few microseconds
- Removed a paramater in `RegionPoolSegregated::countFreeRegions` which unnecessarily traversed a list, whose value was not used
- addresses issue eclipse/openj9#4769
Signed-off-by: Cedric Hansen <cedric.hansen@ibm.com>

Total regions count for metronome regions lists

---

include_core/omrmemcategories.h

This is needed by OpenJ9, see
https://github.com/eclipse/openj9/pull/5891/

Add OMRMEM_CATEGORY_9_CHILDREN macro

---

port/linux/omrosdump_helpers.c
thread/unix/thrdsup.c

This header is unneccisary. Linux documentation indicated only
`sys/prctl.h` is required
(http://man7.org/linux/man-pages/man2/prctl.2.html)

Remove references to `linux/prctl.h`

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/LiveVariableInformation.cpp
compiler/optimizer/Liveness.cpp
compiler/optimizer/SinkStores.cpp

The `OMR::ResolvedMethodSymbol` maintains a list of method metadata
symbols that are a remnant of a legacy project consuming OMR.  They
are not used in OMR nor any known downstream project.
Remove and fold code that referenced this list (it was never populated
with anything).

Remove and cleanup MetaDataList from ResolvedMethodSymbol

---

compiler/il/symbol/OMRSymbol.hpp

The comment describing the API for the `Symbol(TR::DataType d, uint32_t size)`
constructor was incorrectly stating the size is inferred from the type.
Correct the text, and add Doxygen headers to all the OMRSymbol constructors.

Correct API comment for OMRSymbol constructor

---

.gitignore
GNUmakefile
ddr/include/ddr/ir/TextFile.hpp
ddr/include/ddr/macros/MacroTool.hpp
ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
ddr/include/ddr/scanner/pdb/PdbScanner.hpp
ddr/lib/ddr-ir/CMakeLists.txt
ddr/lib/ddr-ir/Makefile
ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/lib/ddr-ir/TextFile.cpp
ddr/lib/ddr-macros/MacroTool.cpp
ddr/lib/ddr-scanner/Scanner.cpp
ddr/lib/ddr-scanner/dwarf/DwarfFunctions.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/lib/ddr-scanner/pdb/PdbScanner.cpp
ddr/test/makefile
ddr/tools/blob_reader/CMakeLists.txt
ddr/tools/blob_reader/Makefile
ddr/tools/blob_reader/blob_reader.cpp
ddr/tools/ddrgen/Makefile
ddr/tools/ddrgen/ddrgen.cpp
ddr/tools/getmacros
omrmakefiles/rules.zos.mk
tools/hookgen/HookGen.cpp
util/a2e/atoe_utils.c
util/a2e/sysTranslate.c

* Add ddrgen dependency on j9a2e.
* Build hook and trace artifacts incrementally.
* Don't compile ddr/test with '-qdbgfmt=stabstring'.
* Enable generation of debug information.
* Ignore *.tracesentinel.
* Link ddrgen with elfdwarf.
* Simplify host-specific conditionals.
* Copy .x files instead of moving them.
* Use quotes instead of multiple escape sequences in compiler options.
* Add required includes of <string.h>.
* Make hookgen more robust - print a message if an XML child is missing instead of crashing with a segmentation fault.
* Read text files consistently - add TextFile class for reading text files consistently (using the port library instead of 'FILE *' or stl streams).
* Fix getmacros to use iconv to work with EBCDIC-encoded files.
* Remove checking for redundant input to …

Enable DDR on z/OS

---

compiler/optimizer/ExpressionsSimplification.cpp

Summation reduction in the expressions simplification optimization pass transforms loops of the following form:
for (int i = 0; i < k; i++) {
...
sum += loopInvariantExpression;
...
}
into a form where the sum is computed via multiplication:
sum += loopInvariantExpression * k;
for (int i = 0; i < k; i++) { ... }
Currently `k` must be a compile-time constant. However, summation reduction is attempted even when `k` is variable, and when expressions simplification fails to determine the number of iterations, the candidate tree is treated instead as a loop-invariant store, and hoisted above the loop with no modifications, like so:
sum += loopInvariantExpression;
for (int i = 0; i < k; i++) { ... }
The resulting sum is correct only when `k` happens to be 1.
Expressions simplification is …

Stop reducing sums with a variable iteration count

---

CONTRIBUTING.md

Document purpose of "toolchain bug" label

---

compiler/control/OMROptions.cpp

Complete support isn't ready yet.  Disabling until it is.

Disable on stack replacement (OSR) for AArch64

---

port/common/j9nls.c

Reverts eclipse/omr#3912
I'd like to revert this change as it's causing problems for OpenJ9.  There seems to be an issue with OpenJ9's use of NLS default messages that is preventing new versions of OMR from being consumed.
I haven't been able to track down the root cause and would like to revert this while I continue to investigate.
Given NLS is a deprecated component in OMR, I'd appreciate willingness from the OMR community to temporarily revert this change.

Revert "Avoid looking up the NLS catalog in en locale's with default msg"

---

compiler/optimizer/ExpressionsSimplification.cpp

Summation reduction in the expressions simplification optimization pass transforms loops of the following form:
for (int i = a; i < k; i++) {
...
sum += loopInvariantExpression;
...
}
into a form where the sum is computed via multiplication:
sum += loopInvariantExpression * k;
for (int i = 0; i < k; i++) { ... }
For illustration these are written as typical for-loops on the range [0,`k`), but summation reduction works on a variety of loops. For example, the IV (induction variable) may be either increasing or decreasing, and the loop test may be inclusive or exclusive.
The initial value of the IV, the step amount, and the loop bound must all be compile-time constants, so that the number of iterations can be computed at compile time. This is the constant by which to multiply.
In calculating …

Fix the iteration count for summation reduction

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

This commit removes all declarations and initializations  of  `constLoadNeedsLiteralFromPool` in OMR
Closes: #1873

Move constLoadNeedsLiteralFromPool to OpenJ9

---

gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp

- FreeEntryAllocateStats has been updated after sweep,
but compaction would change freeEntries stats,
update FreeEntryAllocateStats after compaction.
- the change would keep FreeEntryAllocateStats up to date,
avoid potential trace error later.

Merge FreeEntryAllocateStats after compaction

---

compiler/ilgen/OMRVirtualMachineRegister.cpp
compiler/ilgen/OMRVirtualMachineRegister.hpp
compiler/ilgen/OMRVirtualMachineRegisterInStruct.hpp
jitbuilder/apigen/jitbuilder.api.json
jitbuilder/release/CMakeLists.txt
jitbuilder/release/cpp/Makefile
jitbuilder/release/cpp/samples/VMRegister.cpp
jitbuilder/release/cpp/samples/VMRegister.hpp

JitBuilder math APIs like Add, Mul, etc. require that the left and
right operands have the same type or if the left is a pointer that
the right is an Int32 or Int64. Currently a VMRegister wrapping a
int8_t * will fail when Adjust is called since
_integerTypeForAdjustment will be Int8. It is incorrect to limit
the adjustBy amount to the primite type of the pointer since a user
may want to adjust the value by a large value. The solution is to
adjust by an Int64 not matter what the primitive register type is.
This PR includes a new test called vmregister which verifies that
VMRegisters wrapping a pInt8 work. This test failed before this
PR. The Operand[Array,Stack]Tests verify that the code continues
to work for larger types.

Fix Adjust APIs

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

This patch deletes all references to the function
`bndsChkNeedsLiteralFromPool` in OMR.
Closes: #1872

Delete bndsChkNeedsLiteralFromPool function from OMR

---

compiler/z/codegen/OMRMemoryReference.cpp

This commit changes all `incRefCountForOpaquePseudoRegister`  function calls to the fewer parameter overload version, which was implemented in #3905 and eclipse/openJ9#5881. This commit is step 4 / 6.
Issue: #1855

Fix function calls of incRefCountForOpaquePseudoRegister in OpenJ9
