eclipse-omr/omr

- compiler/codegen/OMRCodeGenerator.hpp
The `OMR::CodeGenerator` class defines
`functionsgetSupportsBigDecimalLongLookasideVersioning` and
`setSupportsBigDecimalLongLookasideVersioning` that are not used in OMR.
They only have relevance in OpenJ9 and should be relocated to the
`J9::CodeGenerator` class there.
Closes: #1882
> Relocate OMR::SupportsBigDecimalLongLookasideVersioning to OpenJ9

- compiler/codegen/OMRCodeGenerator.hpp
Removes the old version of the function `incRefCountForOpaquePseudoRegister` from OMR. This is the last commit to simpify `incRefCountForOpaquePseudoRegister(TR::Node * node, TR::CodeGenerator * cg, TR::Compilation * comp)`  to `void incRefCountForOpaquePseudoRegister(TR::Node * node)` . 
Issue:#1855
> Remove old version of incRefCountForOpaquePseudoRegister

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/S390Peephole.cpp
- compiler/z/codegen/S390Peephole.hpp
Simplifying function calls of `TR_S390Peephole`, `TR_S390PostRAPeephole` and
`TR_S390RreRAPeephole`. They now require `TR::Compilation* comp` as the only 1 argument. This will close #1855 as there is no more function that passes both `cg` and `comp` at the same time.
Closes: #1855
> Simplifying function calls of TR_S390Peephole in OMR

- compiler/il/OMRILOps.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- fvtest/compilertest/tests/OpCodesTest.cpp
- fvtest/compilertest/tests/OpCodesTest.hpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
- fvtest/compilertest/tests/S390OpCodesTest.cpp
- fvtest/compilertest/tests/X86OpCodesTest.cpp
- fvtest/compilertest/tests/injectors/OpIlInjector.cpp
Removes all uses to the ILOpcode: `bucmpeq`. The definitions and initializations in the lists remains. If this commit merges successfully, then we can remove the uses of all the Opcodes in `Equality compare` category at the same time. 
Issue:#2657
> Remove all uses of the ILOpcode: bucmpeq

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Remove all the references to `supportsTrapsInTMRegion` from OMR as the
field has already been transferred to  OpenJ9.
Closes: #1868
> Remove supportsTrapsInTMRegion from OMR

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.hpp
This commit removes field `getInternalPtrMapBit` from OMR.
Closes: #1877
> Remove getInternalPtrMapBit from OMR

- CMakeLists.txt
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/ddr/DDRSetStub.cmake.in
- cmake/modules/ddr/cmake_ddr.awk
- ddr/test/CMakeLists.txt
- gc/CMakeLists.txt
- omr/CMakeLists.txt
- omr/startup/CMakeLists.txt
- omrsigcompat/CMakeLists.txt
- omrtrace/CMakeLists.txt
- port/CMakeLists.txt
- thread/CMakeLists.txt
- util/a2e/CMakeLists.txt
- util/avl/CMakeLists.txt
- util/hashtable/CMakeLists.txt
- util/hookable/CMakeLists.txt
- util/omrutil/CMakeLists.txt
- util/pool/CMakeLists.txt
Introduced a number of changes
- Headers can now be directly associated with a ddr set
- A DDR set no longer needs to be specified when enabling DDR for a target.
- Added a new command `ddr_set_add_targets` which adds a target to a DDR
set. Combined with the above, this allows for a delayed definition of a
DDR set. In addition targets can be in multiple DDR sets.
- DDR sets can now be composed via `ddr_set_add_targets`. This means we can
get rid of the awkward `OMR_DDR_SET` mechanics. Instead we just define
our own DDR set, and consumers simply add our DDR set to theirs
> CMake: Refactor DDR support

- gc/base/GCExtensionsBase.hpp
Introduce an explicit flag to control use of heap sizing startup hints
from Shared Cache. Disabled by default.
Restore internal learning parameter that was set to 0 (temporarily used
as a shortcut to disable the feature).
> Flag to control use of GC startup hints

- gc/base/standard/ConcurrentGC.cpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
Normally, we prevent CM kickoff logic before Scavenge Stat info is
available (survival rate, allocate space size....). In presence of CS,
we incorrectly conclude that first Scavenge cycle is complete (while
only the first STW increment is complete) and proceed with incomplete
data to kickoff math. This indirectly may lead to premature and too
frequent kickoff.
This problem is only visible when CM concurrentSlack option is provided
with high values.
> Concurrent Mark kickoff with Concurrent Scavenger

- gc/base/GCExtensionsBase.hpp
- gc/base/MemorySubSpaceSemiSpace.cpp
- gc/base/MemorySubSpaceSemiSpace.hpp
When calculating tilt ratio in Concurrent Scavenger, allocation rate is
taken into account (beside Nursery flipping rate), since during active
CS cycle allocation is fed from common allocate/survivor space.
Allocate rate can vary a lot (more than flipping rate). So far, we
compensated the variability by boosting the average allocate rate by
fixed 20%. Real life variability could be much larger.
We now track deviations in allocation rate from the average, and use
this parameter to more precisely boost the allocation rate provided to
the tilt math.
> Allocation deviation boost in CS

- compiler/p/codegen/PPCSystemLinkage.cpp
Implemented breakOnEntry debugging option on Power for methods compiled using system linkage.
> Generate entry breakpoints for methods compiled with system linkage

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
Delete variable `_dummyTempStorageRefNode` from `OMR::CodeGenerator`.
Closes: #1897
> Remove _dummyTempStorageRefNode from OMR

- gc/base/MemorySubSpaceSemiSpace.cpp
Fix Windows compiler warnings in
https://github.com/eclipse/omr/pull/3959
> Fix loss of precision warning in alloc boost logic

- gc/base/MarkingScheme.cpp
- gc/base/MarkingScheme.hpp
The assert served its purpose. Removing it now, since it's defeating
leaf object optimization.
> Remove expensive CS assert

- README.md
Fix broken links for "Blog Posts about OMR technologies"
> Fix broken links in OMR README

- compiler/aarch64/codegen/OMRMemoryReference.hpp
This commit fixes the doxygen comment for
OMRMemoryReference::generateBinaryEncoding() for AArch64.
> AArch64: Fix comment for OMRMemoryReference

- compiler/optimizer/CFGSimplifier.hpp
- compiler/optimizer/CMakeLists.txt
- compiler/optimizer/OMRCFGSimplifier.cpp
- compiler/optimizer/OMRCFGSimplifier.hpp
- compiler/optimizer/OMROptimizationManager.cpp
- compiler/optimizer/OMROptimizer.cpp
- fvtest/compilertest/build/files/common.mk
- jitbuilder/build/files/common.mk
- an explicit if obj == null to a throw of new NullPointerException will
now be simplified to NULLCHK (for both resolved and unresolved
NullPointerException cases.
- an explicit if obj == null to a throw of another exception will become
a NULLCHK to a catch with a goto to the throwing code
- a diamond or triangle storing a single temp will become a ternary
- a triangle storing to multiple temps will become a sequence of
ternaries
- an excplicit if obj instanceOf class with a throw becomes a checkcast
to a catch with a goto to the throwing code
This commit also adds CFGSimplification to ILGenOpts to fold complex
control flow early
Co-authored-by: Andrew Craik <ajcraik@ca.ibm.com>
> Enhances CFG simplification with new patterns

- omrmakefiles/rules.mk
This avoids a problem on z/OS where c89 refuses to consider C++ code:
```
FSUM3008 Specify a file with the correct suffix (.c, .i, .s, .o, .x, .p, .I, or .a), or a corresponding data set name, instead of RegionPool.cpp.
```
> Use the C++ compiler to preprocess C++ code for DDR

- gc/structs/ObjectIteratorState.hpp
There's only one instance of OMR_GC_HYBRID_ARRAYLETS in the codebase.
Remove the ifdef, so the flag is effectively enabled with OMR_G_ARRAYLETS in OMR.
> Merge the arraylets and hybrid arraylets build flags

- cmake/modules/OmrDDRSupport.cmake
Add NO_DEBUG_INFO option which stops ddrgen from extracting info from
debug symbols for the target
> CMake: Add ability to skip parsing debug info for ddr

- ddr/tools/blob_reader/CMakeLists.txt
> CMake: blobreader needs to link against the thread library

- compiler/optimizer/OMRCFGSimplifier.cpp
Boolean store simplification has caused test failures in downstream
project openj9. We haven't fully understood the defect, so disable this
opt until we have a fix for it.
> Disable boolean store simplification

- compiler/x/amd64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/x/i386/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertest/tests/X86OpCodesTest.cpp
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilertriltest/TernaryTest.cpp
Add tril tests for ternary opcode with different compare nodes and value
nodes
> Tril tests for ternary opcode

- port/unix/omriconvhelpers.c
- port/zos390/omrgetjobname.c
- port/zos390/omrgetuserid.c
- port/zos390/omrmmap.c
- port/zos390/omrsyslog.c
Heed compiler advice about built-in functions, for example:
```
INFORMATIONAL CCN3573 ./zos390/omrgetjobname.c: To use the built-in form of the strcpy function add the #include <string.h> directive.
```
> General z/OS improvements

- omrmakefiles/rules.mk
Fixes error on z/OS:
```
No rule to make target 'omrlpdat.i', needed by 'ddrgen'.
```
> Extend DDR rules to handle *.mc files

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OpMemToMem.cpp
- compiler/z/codegen/OpMemToMem.hpp
* Remove inlineNDmemcpyWithPad and fold code assuming false
* Fold code assuming MemToMemVarLenMacroOp::needsLoop is always true
> Misc. Z CodeGenerator cleanups

- omrmakefiles/rules.ztpf.mk
- thread/unix/thrdsup.c
Compiler Option updates as part of building for GCC 7.  Additionally,
needed to bypass z/TPF stack validation.
> Updates associated with z/TPF GCC 7 Builds

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/arm/codegen/OMRLinkage.cpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/codegen/OMRLinkage.cpp
- compiler/il/symbol/OMRParameterSymbol.hpp
- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
- compiler/x/codegen/X86SystemLinkage.cpp
- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/SystemLinkage.cpp
Provide more meaningful names for the following APIs to make
the code that uses it more readable:
* `getAllocatedIndex` --> `getAssignedGlobalRegisterIndex`
* `setAllocatedIndex` --> `setAssignedGlobalRegisterIndex`
* `getAllocatedLow` --> `getAssignedLowGlobalRegisterIndex`
* `setAllocatedLow` --> `setAssignedLowGlobalRegisterIndex`
* `getAllocatedHigh` --> `getAssignedHighGlobalRegisterIndex`
* `setAllocatedHigh` --> `setAssignedHighGlobalRegisterIndex`
Add Doxygen comments where appropriate.  Modify references in OMR.
The original API is left in place for now while downstream projects
switch over to the new API.
> Rename global register allocated indexes on ParameterSymbol

- gc/base/EnvironmentBase.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
See https://github.com/eclipse/openj9/issues/6060 for background and results
* deepScan routine introduced to "special treat" objects with self referencing fields (fast traversal of deep structure nodes)
* Split into two functions `deepScan` and `deepScanOutline`. Frequently called checks _(see lazy start check below)_ must be inlined
* `deepScanOutline` scans self referencing field of an object follows it and repeats. If it can't follow through in one direction, it will attempt to use the second self referencing field (e.g., the next and previous pointes of double linked lists)
* Lazy Start condition used for gatekeeping - inhibit the special treatment routine with relatively high probability to skip over most false positives (shorter lists), while only marginally delay detection of very …
> Deep Structure Scan Optimization

- compiler/optimizer/OMRCFGSimplifier.cpp
- compiler/optimizer/OMRCFGSimplifier.hpp
`new CFGSimplifier` in OMR namespace will create an
`OMR::CFGSimplifier` object, so implementation from downstream project will
never be picked up. Fix this by using `TR::CFGSimplifier`.
> Create TR::CFGSimplifier instead of CFGSimplifier

- compiler/optimizer/Inliner.cpp
When splitting a block, temps are created to uncommon references across
the splitted blocks. Use known object temps, if the original referenced
value is a known object.
> Create known object temps when splitting block

- compiler/compile/Method.cpp
- compiler/il/symbol/OMRResolvedMethodSymbol.cpp
- compiler/il/symbol/OMRResolvedMethodSymbol.hpp
If known object information is avaible for the method receiver, use
known object index to create the parm symbol reference. Optimizations
can make use of the info without running global VP which is very
expensive and doesn't kick in at warm.
> Use symRef with known obj index for known parms

- compiler/optimizer/CallInfo.hpp
- compiler/optimizer/Inliner.cpp
Limits set by exceedsSizeThreshold are ignored for force inlining
targets. The bytecode size for those targets won't be used so
skip calling estimateAndRefineBytecodeSize for them to save some
compilation time.
> Skip estimate code size for force inlining targets

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Fixes #3961
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Remove RegisterITF references from OMROptions

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
This commit adds following options to control and trace compression of AOT code.
1. disableAOTBytesCompression : Disable compressing AOT compiled method
before storing it into cache.
2. verbose={compression} : Support verbose out put about compressing/decompressing
AOT compiled method in the verbose log.
> Add options for compressing AOT Code

- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
This change does two things: (1) when we find a NULLCHK with a first
child that has reference count 1 - turn that node into a PassThrough to
provide an opportunity for something more useful to move up under the
NULLCHK and (2) allow compactNULLCKs to cross block boundaries when the
two blocks are in treetop order and are in a single predecessor to
single successor relationship (eg the break is due to exception edges or
similar.
> Improve compactNULLCHKs

- compiler/codegen/CodeGenPrep.cpp
- compiler/codegen/FrontEnd.hpp
- compiler/env/FEBase.cpp
- compiler/infra/Assert.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
* Remove obsolete code from FEBase.cpp
* Remove unnecessary J9_PROJECT_SPECIFIC macros
> Misc. compiler code cleanup 

- compiler/p/codegen/OMRCodeGenerator.cpp
The logic in allowGlobalRegisterAcrossBranch() must match the logic in
switchDispatch() when deciding which lookup scheme logic to use. The
failure to check for an overflow in allowGlobalRegisterAcrossBranch()
allowed for GRA to use 25 registers which caused a crash in
freeBestRegister() because all registers were blocked when local RA was
looking to allocate a register needed by the switch lookup code.
> Fix logic in allowGlobalRegisterAcrossBranch() for POWER

- compiler/il/symbol/OMRParameterSymbol.hpp
* `getAllocatedIndex`
* `setAllocatedIndex`
* `getAllocatedLow`
* `setAllocatedLow`
* `getAllocatedHigh`
* `setAllocatedHigh`
> Remove deprecated ParameterSymbol allocated register APIs

- compiler/compile/OMRAliasBuilder.hpp
- compiler/compile/OMRMethod.hpp
* Remove NonUserMethod enum
* Remove unnecessary includes and forward decls from OMRMethod.hpp
> Misc. OMRMethod.hpp cleanup

- port/win32/omrsysinfo.c
Major verson 5, minor version 1 is Windows XP, 32 bit. An application may
report this version depending on how it is manifested.
Fixes https://github.ibm.com/runtimes/infrastructure/issues/1995
> Handle Windows version 5.1 in omrsysinfo_get_OS_type()

- compiler/optimizer/SwitchAnalyzer.cpp
The unsigned ILopcode: `TR::iflucmpeq` and `TR::ifiucmpeq` have already been deprecated. Remove the two unsigned opcodes from the` SwitchAnalyzer.cpp`.
Issue: #3983
> Remove unsigned ILopcode: TR::iflucmpeq and TR::ifiucmpeq from SwitchAnalyzer

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/optimizer/FieldPrivatizer.cpp
- compiler/optimizer/FieldPrivatizer.hpp
- compiler/optimizer/OMROptimizationManager.cpp
This is a legacy optimization that has never been enabled and not
immediately useful to OMR or any known downstream projects.
> Remove deprecated element privatization from FieldPrivatizer

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit removes the line "TR_UNIMPLEMENTED();" for TR_Private
from OMR::ARM64::CodeGenerator::beginInstructionSelection().
> AArch64: Enable beginInstructionSelection() for PrivateLinkage

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ParallelGlobalGC.cpp
- Added a few heuristics related to the rate of promotion from nursery to better predict how many scavenges remaining until percolate will occur. These heuristics include a calculation for `headroom` which is related to `concurrentKickoffTenuringHeadroom` and `lastGlobalGCFreeBytes`. Default value for `concurrentKickoffTenuringHeadroom` is 2%
- Kickoff point for concurrent mark will still  be triggered when `scavengesRemaining` point is reached, but this now includes the headroom calculations. The headroom is always set to be 'worst case scenario' between 1, and whatever value is calculated as the headroom remaining
- Added `lastGlobalGCFreeBytesLOA` to `GCExtensionsBase`. The usage of this field is almost identical as `lastGlobalGCFreeBytes`, but only considers LOA. This field is being …
> Modifying kickoff point for concurrent mark

- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit adds compressedRefsEvaluator to the TreeEvaluatorTable
for AArch64.  It calls the platform-independent
OMR::TreeEvaluator::compressedRefsEvaluator().
> Arch64: Enable compressedRefsEvaluator

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit adds some members and their getters to ARM64LinkageProperties
for use in OpenJ9.
> AArch64: Add some members to ARM64LinkageProperties

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/ParallelGlobalGC.cpp
- Disabled dark matter compaction when concurrent sweep is enabled, due to concurrent sweep reporting innacurate dark matter info
- Doubled default value for `darkMatterCompactThreshold` so that it doesn't trigger unless specified by command line option.
- Refer to https://github.com/eclipse/omr/pull/3939 for description of the dark matter compact metrics
Signed-off-by: Cedric Hansen <cedric.hansen@ibm.com>
> Disable dark matter compact for concurrent sweep

- compiler/optimizer/LocalOpts.cpp
Archetype specimen is the most refined form of `MethodHandle.invokeExact`,
thus it does not need to go through any more refinement. Plus its symbol
reference does not have a valid vtable offset, it will cause the
subsequent code that uses this offset to get a resolved method to crash.
> Return if MethodHandle.invokeExact has been specialized

- compiler/optimizer/SwitchAnalyzer.cpp
From `SwtichAnalyzer.cpp`, remove deprecated `const` unsigned IL Opcodes listed in #3983.
e.g. `TR::iuconst` and `TR::luconst`
Issue: #3983
> Remove deprecated const IL Opcodes from SwitchAnalyzer

- cmake/modules/FindLEX.cmake
- cmake/modules/FindYACC.cmake
The `find_package_handle_standard_args` utility in cmake is used to help implement FindXyz.cmake modules. Specifically, the macro will test whether the package was required, or whether a specific version was required.
This macro will also define the `YACC_FOUND` / `LEX_FOUND` variables, which can be used to determine success.
It also gives us a nice little print out:
```
-- Found YACC: /usr/bin/yacc
-- Found LEX: /usr/bin/lex
```
Fixes: #4070
> Handle args in FindLEX/FindYACC

- compiler/runtime/OMRCodeCache.hpp
Move the CodeCacheBase fields and functions into the OMR::CodeCache
class, and remove the CodeCacheBase class.  The downstream dependency
requiring this has been eliminated.
> Remove CodeCacheBase class

- compiler/il/symbol/OMRSymbol_inlines.hpp
- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/optimizer/PreExistence.cpp
- compiler/optimizer/PreExistence.hpp
When inliner inlines a method and replaces the loads of parms with loads
of priv arg temps, the known object info we got from prex arguments are
lost. GlobalVP needs to run to propagate the known object info again
which is expensive and doesn't kick in at warm level. This change replaces
the priv args with known object temps when feasible.
> Use known object temps for inlined callee

- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
This commit enables all rdbar/rdbari & wrtbar/wrtbari Evaluators on Power.
Signed-off-by: Alen Badel <Alen.Badel@ibm.com>
> Enable rdbar and wrtbar Evaluators on Power

- gc/base/GCExtensionsBase.hpp
As requested by
https://github.com/eclipse/openj9/issues/3743#issuecomment-505569900
(the feature is really only available in OpenJ9)
> Enabling GC Startup Hints by default

- include_core/thread_api.h
- thread/aix/omrthreadnuma.c
- thread/common/omrthreadnuma.c
- thread/linux/omrthreadnuma.c
- thread/win32/omrthreadnuma.c
Function returns the numa node number the thread is currently executing
on
> Add omrthread_numa_get_current_node()

- compiler/compile/CMakeLists.txt
- compiler/compile/Method.cpp
- compiler/compile/OMRMethod.cpp
- compiler/compile/OMRMethod.hpp
- compiler/il/symbol/MethodSymbol.hpp
- compiler/optimizer/CallInfo.hpp
- compiler/optimizer/DebuggingCounters.hpp
- compiler/optimizer/Inliner.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- fvtest/compilertest/build/files/common.mk
- fvtest/compilertest/compile/Method.hpp
- jitbuilder/build/files/common.mk
- jitbuilder/compile/Method.hpp
* create the OMR base class structure and the concrete class in
the TR:: namespace.  Fixup forward declarations.
* the class does not have the OMR_EXTENSIBLE attribute yet
* connect the existing JitBuilder and CompilerTest hierarchies
without making them extensible classes yet
> Initial implementation of extensible TR::Method base class

- port/unix/auxv.c
Fix for the error (Building on Alpine):
```
./unix/auxv.c:49:19: error: '__environ' undeclared (first use in this function); did you mean 'saved_environ'?
saved_environ = __environ;
^~~~~~~~~
saved_environ
```
> Fix : environ on PPC64LE

- compiler/compile/ResolvedMethod.cpp
This file will eventually be populated with ResolvedMethod information,
but an empty version with no dependencies is first required so that downstream
builds can be changed without breakages.
> Add dummy ResolvedMethod.cpp

- thread/linux/omrthreadnuma.c
Older kernels seem to define the system call as SYS_get_cpu
> Fix issue with SYS_getcpu not being defined

- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit enables the evaluator table entries for iand, ior, and
ixor for AArch64.  The evaluators are already implemented in
BinaryEvaluator.cpp.
> AArch64: Enable iand, ior, and ixor evaluators

- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit adds calls to mr->incRegisterTotalUseCounts() and
useRegister() in the constructors of memory access instructions for
AArch64.
> AArch64: Call mr->incRegisterTotalUseCounts() and useRegister()

- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
The virtualGuardHelper() on ARM, x86, PPC, and z now use the same query to
decide whether or not a NOP-virtual-guard should be generated.
> Use a common query to decide if a VG-NOP is needed

- compiler/z/codegen/OMRMemoryReference.cpp
Adding TR_ASSERT_FATAL to `generateS390MemoryReference` which use `MemoryReference` constructor directly and pass in `Node` type variable. So that it will be noticed when zero symbol reference node is passed in, which may lead to crash in `calcDisplacement` function.
Signed-off-by: simonameng <simonameng97@gmail.com>
> Add TR_ASSERT_FATAL to `generateS390MemoryReference`

- port/unix/omrcpu.c
Fix the following ld problems.
```
12:09:23  ld: 0711-318 ERROR: Undefined symbols were found.
12:09:23  	The following symbols are in error:
12:09:23   Symbol                    Inpndx  TY CL Source-File(Object-File) OR Import-File{Shared-object}
12:09:23                                RLD: Address  Section  Rld-type Referencing Symbol
12:09:23   ----------------------------------------------------------------------------------------------
12:09:23   .dcbz                     [497]   ER PR ./unix/omrcpu.c(../../../../lib/libomrstatic.a[omrcpu.o])
12:09:23                                     00000220 .text    R_RBR    [431]   .omrcpu_startup
12:09:23   .dcbst                    [499]   ER PR ./unix/omrcpu.c(../../../../lib/libomrstatic.a[omrcpu.o])
12:09:23 …
```
> Fix omrcpu.c assembler helpers for AIX xlC 16

- compiler/z/codegen/ControlFlowEvaluator.cpp
The nullChkWithPossibleResolve evaluator has a special case for compressed references. The node to be checked is not the iloadi itself and is instead its child. When fieldwatch is enabled, the iloadi is transformed into an irdbari. Therefore, in those cases the NullChk evaluator must try to find the child of the irdbari node instead of trying to find the iloadi node.
> Recognize the rdbar op code in NullChk evaluator

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit implements indirectCallEvaluator() for AArch64 for icalli
and other opcodes.
> AArch64: Implement indirectCallEvaluator() for icalli, etc.

- gc/base/standard/Scavenger.cpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
Gather the following Scavenger stats (to be reported part of TGC
parallel):
- The number of deep structures that are scanned with
priority (number of deepScanOutline function calls)
- The total number of deep structure nodes that are special treated
(number of copyAndForward with priority)
- Length of longest deep structure that is special treated
> Deep Scan TGC Stats Gathering

- cmake/modules/OmrUtility.cmake
- cmake/modules/platform/toolcfg/msvc.cmake
Processes a template by expanding variable references, then evaluation
generator expressions.
Resolves #4104
> CMake: Add omr_process_template utility function

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements some unimplemented parts in OMRMemoryReference
for AArch64.
> AArch64: Implement OMRMemoryReference.cpp

- compiler/aarch64/env/ARM64ProcessorEnum.hpp
- compiler/env/Processors.hpp
Implement AArch64 and ARMv8 Processor Information
> Implement AArch64 and ARMv8 Processor Information

- compiler/z/codegen/UnaryEvaluator.cpp
Change the implementation of dsqrtEvaluator on Z to calculate the `sqrt` using C++ function if the first child is `dconst`. Else, depending on the reference count, generating the SQDB or SQDBR instruction.
> Change the implementation of dsqrtEvaluator

- compiler/z/codegen/OMRTreeEvaluator.cpp
The `TR::iRegStore` evaluator on Z makes an implicit assumption that if
the value being globally stored is a conversion of an appropriate type,
for example `TR::su2i` of a `TR::cloadi` then the evaluators will have
generated a full 64-bit sign extended load.
This is very dangerous as an evaluator should never implicitly assume
another evaluator will generate a specific instruction sequence to
perform some action. Because of this implicit assumption the
`TR::iRegStore` evaluator omitted the generation of an explicit sign
extension and just assumed the evaluator has already done it. It then
marked the register via the `setAlreadySignExtended` API that the
extension has been performed. Later a `TR::i2l` conversion operation
consumes the value of the `TR::su2i` and it checks whether the child …
> Remove implicit sign extension assumptions from iRegStore evaluator

- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
Remove all references to the IL Opcodes in the `Add/Subtract` category listed in #2657.
Note:
- Function `bool OMR::Node::isTernaryHigh()` will always return `false` after removing these unsigned opcodes. Therefore, should fold this function in the future. But be CAUTION that this function is also referenced in the OpenJ9.
- Function `static TR::ILOpCodes unsignedSubtractOpCode(TR::DataType type)` should also be removed as all unsigned sub opcode for this datatype should have been deprecated
Issue: #2657
> Remove references of deprecated  Add/Subtract IL opcodes

- port/unix/omrcpu.c
Use a more flexible implementation for changes added by #4099
Not sure #4099 works properly for xlc 16, it may exclude the assembler code. The `__xlC__` macro isn't supported by xlclang/xlclang++.
https://www.ibm.com/support/knowledgecenter/en/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/compiler_ref/xlmacros.html
> __xlC__ is not defined by xlclang

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/il/OMRILOps.hpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/SystemLinkageLinux.cpp
- compiler/z/codegen/SystemLinkagezOS.cpp
Remove all references to the IL Opcodes in the `Call/Return` category listed in #2657.
Issue: #2657
> Remove references of deprecated Call/Return IL opcode

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/VPHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
- fvtest/compilertest/tests/S390OpCodesTest.cpp
- fvtest/compilertest/tests/X86OpCodesTest.cpp
Remove all references to the IL Opcodes in the `Multiply` and `Ternary` category listed in #2657.
Note that there is no commit mentioning `TR::luternary` and `TR::suternary` since there is no references for them.
Issue: #2657
> Remove references of deprecated Multiply and Ternary IL Opcode

- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
Reverts eclipse/omr#4096.
The following tree produces a compile time crash with this change in tact:
```
------------------------------
n112n    (  0)  treetop                                                                              [     0x3ff469512c0] bci=[-1,57,184] rc=0 vc=929 vn=- li=6 udi=- nc=1
n111n    (  4)    luaddc ()                                                                          [     0x3ff46951270] bci=[-1,54,184] rc=4 vc=929 vn=- li=6 udi=- nc=3 flg=0x20
n102n    (  1)      luaddc ()                                                                        [     0x3ff46950fa0] bci=[-1,45,183] rc=1 vc=929 vn=- li=6 udi=- nc=3 flg=0x20
n79n     (  2)        lumulh ()                                                                      [     0x3ff46950870] …
```
> Revert "Remove references of deprecated  Add/Subtract IL opcodes"

- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.hpp
- compiler/arm/codegen/OMRTreeEvaluatorTable.hpp
This commit removes resolveCHKEvaluator() for ARM32, and uses the
function in the OpenJ9 side.
> Remove ARM32 resolveCHKEvaluator()

- omrmakefiles/rules.aix.mk
Add '-bnolibpath' to DLL link flags so that only the default library
paths are added to the loader section of those shared libraries being
built rather than the ones specified in '-L' flags, which can expose
system information.
> Remove extra rpaths in AIX shared libs

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.hpp
- compiler/arm/codegen/OMRTreeEvaluatorTable.hpp
Removed ARM and AArch64 specific monexitfenceEvaluator code.
monexitfenceEvaluator is now shared across architectures in openj9.
Signed-off-by: Michael Flawn <mflawn@unb.ca>
> Removed monexitfenceEvaluator from ARM and AArch64

- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/LoopVersioner.hpp
Versioner currently treats loads of fields and statics as loop-invariant (when the loop doesn't explicitly write them) and generates versioning tests containing such loads. If another thread writes to a field or static, it's possible for the value observed by the loop body to differ from the value observed in a versioning test. For a load that has been copied into multiple versioning tests, it is even possible to see values that are inconsistent between versioning tests. In particular, after running a versioning test, the property it tests for may no longer hold of the value obtained by repeating the load, so it is incorrect to skip checks.
In the absence of synchronization and calls it is possible to version based on expressions containing such loads by privatizing their values, …
> Do not version w.r.t. concurrently writable memory

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit implements unordered FP conditional branch evaluators
(iffcmp*u and ifdcmp*u) for AArch64.  It generates additional
instruction with the condition code "VS" for unordered comparison.
> AArch64: Implement unordered FP conditional branch evaluators

- compiler/il/OMRILOps.hpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/VPHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/S390Peephole.cpp
Remove all references to the IL Opcodes in the `Shift` category listed in #2657.
Issue: #2657
> Remove references of deprecated Shift IL Opcode

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- Reorganized DeepScan code to avoid an extra check on hot path
- Added loop check to ensure we break from deep scan on NULL reference
- Resolves deep scan issue with concurrent scavenger https://github.com/eclipse/openj9/issues/6393
where mutator nulls the next reference link
- Rename fields for clarity
> Deep Scan CS fix

- compiler/optimizer/LoopCanonicalizer.cpp
This allows canonicalization of while loops with conditions that load reference-typed fields, e.g.
for (int i = 0; i < this.data.length; i++) { ... }
Such loops are already successfully canonicalized when compressed references are not in use.
> Skip compressedRefs anchors in canonicalizer

- compiler/compile/OMRCompilation.hpp
- compiler/env/HeuristicRegion.hpp
- compiler/optimizer/LocalOpts.cpp
The getClassFromSignature call in TR_ColdBlockMarker::hasNotYetRun is
only used to make a heuristic decision as to whether or not the block
should be marked cold. In a relocatable compile (currently in OpenJ9),
the getClassFromSignature will result in a validation record that will
be used in the load run. This validation could fail because the class
from signature might not yet exist. However, executing the body in a
subsequent run does not require this class to exist (assuming this is
the only reference to it during the compilation), since its existence
was only used for a heuristic decision regarding cold block marking -
an act that only mattered during the compilation.
This PR wraps the getClassFromSignature call in a heuristic
region.
Signed-off-by: Irwin D'Souza …
> Add Heuristic Region in Cold Block Marker

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
This PR adds DSB to the opcode tables in AArch64, as it is
needed in OpenJ9.
Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>
> Add DSB instruction to AArch64 opcode tables

- compiler/aarch64/codegen/OMRSnippet.hpp
This commit adds a new Snippet Kind for AArch64, IsForceRecompilation.
> AArch64: Add IsForceRecompilation as Snippet Kind

- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit implements loadaddrEvaluator() for AArch64.
> AArch64: Implement loadaddrEvaluator()

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit implements aladdEvaluator() for AArch64.
> AArch64: Implement aladdEvaluator()

- compiler/optimizer/SelectOpt.hpp
Allows for multiplexing between a default optimizations and a another one
conditional upon a JITCmdLineOption.
Contributes to issue #3956.
Signed-off-by: Erick <eochoa@ualberta.ca>
> Create TR::SelectOpt class

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/S390GenerateInstructions.cpp
Move `BREAK` instruction to one instruction after `PROC` when adding `breakOnEntry` option in command, so that the debugger can stop at the beginning of methods. Also, generating `BREAK` instruction in `doBinaryEncoding` function instead of in the function where `PROC` gets generated.
Signed-off-by: simonameng <simonameng97@gmail.com>
> Fix `breakOnEntry` option on Z

- ddr/include/ddr/ir/ClassType.hpp
- ddr/lib/ddr-ir/ClassType.cpp
- ddr/lib/ddr-ir/Symbol_IR.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
Fix handling of forward declarations
* Types can't be considered complete until something more than a forward declaration is encountered. Previously missed, for example, were the enum literals of `MM_ConcurrentGC::InitType`.
Fix merging of super type of classes
* Forward declarations will not provide information about base types. When base type information is available later, it must be merged. An example of a (previously) missed super type is: `class MM_Scavenger : public MM_Collector`.
> DDR: Fix missing information

- compiler/z/codegen/SystemLinkagezOS.cpp
- compiler/z/codegen/SystemLinkagezOS.hpp
- compiler/z/codegen/snippet/XPLINKCallDescriptorSnippet.cpp
- compiler/z/codegen/snippet/XPLINKCallDescriptorSnippet.hpp
The call descriptor offset in the NOP following a call within an XPLINK
frame was not being correctly calculated. The patch location was
correct, however the offset encoded was from the patch location, which
is incorrect.
As per the documentation linked in the source code the value we wish to
encoding is a (positive) signed offset in doublewords from  the
doubleword at or preceding the return point (NOP) to the XPLINK call
descriptor for this signature.
This is not something we can encoding with the existing locations, and
due to the doubleword alignment that is required it is not something
that we should generalize either since we don't envision other uses for
such a strict API. Instead we create a private relocation in the XPLINK
linkage class and handle the relocation there. …
>  Fix calculation of XPLINK call descriptor offset

- compiler/infra/Cfg.hpp
- compiler/infra/OMRCfg.cpp
- compiler/infra/OMRCfg.hpp
This commit adds an internal memory region to the CFG.
By default, the internal memory region is created from the heap
region. CFG edges are now allocated to this internal memory
region.
Signed-off-by: Erick Ochoa <eochoa@ualberta.ca>
Needed for this [openj9 issue](https://github.com/eclipse/openj9/issues/6099)
Will be needed for this [openj9 PR](https://github.com/eclipse/openj9/pull/6141)
> Add internal memory to CFG

- gc/base/GCExtensionsBase.hpp
- gc/base/Math.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/Scavenger.cpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
- Added heuristics to keep track of bytes moving from nursery to tenure, along with the deviation of this value.
- `_avgTenureBytes` keeps track of average bytes that are being tenured, while `_avgTenureBytesDeviation` keeps track of the average amount of deviation in bytes being tenured.
- Adding this deviation into the calculation for concurrent kickoff
- The default boost for the deviation on top of the existing kickoff logic is 2x. This field is called `tenureBytesDeviationBoost`
- This change results in far less aborts/percolates, but at the expense of more global GC cycles
- Will be accompanied by a change on the j9 side for explicitly setting `tenureBytesDeviationBoost`. Setting this to 0 will effectively disable it's effects
- This calculation is done for both SOA bytes (if …
> Adding Tenure bytes deviation to modify concurrent kickoff

- compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit fixes genericBinaryEvaluator() for AArch64.
The function fails with trgReg being NULL in a specific case.
> AArch64: Fix genericBinaryEvaluator()

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
Before this change, applyPolicyToTargets removes the invalid targets
**AFTER** calling estimate code size on them. Estimating code size for
invalid targets is redundant since they are removed no matter what the
code size is. In case of not inlineable native methods, there is
functional issue because estimate code size iterates bytecode
in the callee which doesn't even exist for native methods.
This change removes the invalid targets **BEFORE** estimate code size
to both save compilation time and fix the functional issue with non-inlineable
native method.
Fixes: eclipse/openj9#6547
> Remove invalid target before EstimateCodeSize

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit implements TR_Debug::print() function for
ARM64CompareBranchInstruction.
> AArch64: Implement TR_Debug::print(ARM64CompareBranchInstruction)

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit implements imax/lmax/imin/lmin evaluators for AArch64.
> AArch64: Implement integer max/min evaluators

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
* Make ARM64ImmInstruction a base class purely for immediate values by removing
unnecessary functionality
* Correct Imm instruction binary encoding
* Rebase the ARM64SynchronizationInstruction to extend ARM64ImmediateInstruction
and share functionality
Fixes #4165
> Fix ARM64ImmInstruction functionality

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/il/symbol/OMRStaticSymbol.hpp
- compiler/il/symbol/OMRSymbol.hpp
- compiler/optimizer/VPHandlers.cpp
It is not used in OMR nor any downstream project.
> Remove unused DLP SymbolReference management

- compiler/il/OMRNode.cpp
allocationfence node doesn't have children, we should use setAllocation
to set the allocation node.
> Use setAllocation

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
When applyPolicyToTargets remove the targets first before calling
estimate code size to reduce some compilation time.
Add requestAdditionalOptimizations to request for other optimizations
based on what's got inlined.
Change the condition of doing targeted inlining in optimizer to base
on request.
> Minor changes to prepare for new targeted inlining

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
Add following placeholder call symbol to CommonNonHelperSymbol enum for jProfilingValue.
1. jProfileValue : Symbol for regular value profiling which does not need NULLCHK
2. jProfileValueWithNullCHK : Symbol for value profiling that requires NULLCHK
> Add a placeholder call symbol for jProfileValue

- compiler/optimizer/Inliner.cpp
In many places, OSR-related code in the inliner is calling `getOwningMethodSymbol()` on a symbol reference in order to access information about the calling method.  However, the owning method for a symbol reference is not necessarily the calling method.
Instead, code should call `getInlinedResolvedMethodSymbol()` on the `TR::Compilation` object for the bytecode's caller index or, if the caller index is -1, call `getMethodSymbol()`.
> Look for right caller method when handling OSR in context of inliner

- compiler/il/OMRILOps.hpp
- compiler/ilgen/OMRIlBuilder.cpp
- compiler/ilgen/OMRIlBuilder.hpp
- compiler/ilgen/StatementNames.hpp
- fvtest/jitbuildertest/CMakeLists.txt
- fvtest/jitbuildertest/Makefile
- fvtest/jitbuildertest/SelectTest.cpp
- jitbuilder/apigen/jitbuilder.api.json
This changeset also includes the following:
* JitBuilder tests added to test the Select service
* Introduced OMR::IlOpCode::ternaryOpCode static function to lookup the right
opcode for different data types
* Updated jitbuilder.api.json with the new entry
The need for this service was driven by the [LLJB project](https://github.com/nbhuiyan/lljb) when trying to translate LLVM IR's [`select` instruction](https://llvm.org/docs/LangRef.html#select-instruction) to JITBuilder API calls.
> Implement ternary Select IlBuilder service

- compiler/optimizer/Inliner.hpp
Changes to the way the calling method is determined for OSR-related code in the Inliner are conditionally compiled under `#if defined(INLINER_OSR_CALLING_METHOD)`.  This change enables that code.
> Enable change to determine calling method for OSR code in Inliner

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
As decided by eclipse/openj9#6203, name `JITaaS` is replaced with `JITServer`.
Add new option and verbose log names using `JITServer`.
After the new names are picked up by OpenJ9, the old names
with `JITaaS` will be removed.
> Prepare JITaaS to be replaced with JITServer

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit adds AArch64 DMB (data memory barrier) instruction to
opcode tables.
> AArch64: Add DMB instruction to opcode tables

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/ras/Debug.hpp
This commit adds support for a new instruction kind,
ARM64CondTrg1Src2Instruction, to ARM64Debug.cpp.
> AArch64: Add ARM64CondTrg1Src2Instruction to ARM64Debug.cpp

- compiler/aarch64/CMakeLists.txt
This commit adds ARM64HelperCallSnippet.cpp to CMakeLists.txt for
AArch64.
> AArch64: Add ARM64HelperCallSnippet.cpp to CMakeLists.txt

- cmake/modules/ddr/DDRSetStub.cmake.in
Instead use the configured C compiler
> CMake: Stop hardcoding preprocessor for DDR

- fvtest/jitbuildertest/CMakeLists.txt
Make JitBuilder sources private due to CMP0076 warning policy and path type conversion.
Fixes: #4069
Signed-off-by: Batyr Nuryyev <nuryyev@ualberta.ca>
> Make JitBuilder sources private

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit changes the output of
TR_Debug::print(ARM64Trg1ImmInstruction) for movz/movn/movk
instructions, for better readability.
> AArch64: Pretty print for movz/movn/movk instructions

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds generation of AArch64 DMB instructions for volatile
variables.
> AArch64: Generate DMB instructions for volatile variables

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit adds functions such as assignRegisters() and refsRegister()
to ARM64CompareBranchInstruction.
> AArch64: Add assignRegisters(), etc. for ARM64CompareBranchInstruction

- compiler/il/OMRBlock.cpp
- compiler/il/OMRBlock.hpp
Splitting block after Global Register Allocator requires manual uncommoning of nodes while respecting the register dependencies generated by GRA. This commit adds support to split the blocks after GRA is finished.
Co-authored-by: Andrew Craik <ajcraik@ca.ibm.com>
Co-authored-by: Ben Thomas <ben@benthomas.ca>
Co-authored-by: Rahil Shah <rahil@ca.ibm.com>
> Add support to split blocks post GRA

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit fixes fstore/dstore evaluators for AArch64.
They have been calling commonLoadEvaluator() instead of
commonStoreEvaluator().
> AArch64: Fix fstore/dstore evaluators

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit adds functions such as assignRegisters() and refsRegister()
to ARM64RegBranchInstruction.
> AArch64: Add assignRegisters(), etc. for ARM64RegBranchInstruction

- compiler/compile/OMRCompilation.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
Replace the usage of that query with `CodeGenerator::needRelocationsForStatics`.
They are supposed to be used in the same circumstances but it is more appropriate to have this query in the codegen, since different platforms may require different answers.
> Remove OMR::Compilation::needRelocationsForStatics

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit implements the printARM64GCRegisterMap() in ARM64Debug.cpp.
> AArch64: Implement TR_Debug::printARM64GCRegisterMap()

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
Changes to the way the calling method is determined for OSR-related code in the Inliner were guarded by `if defined(INLINER_OSR_CALLING_METHOD)`.  Now that downstream components
have made that change unconditional, it can be unconditional in OMR.  The downstream change was made in [OpenJ9 pull request 6651](https://github.com/eclipse/openj9/pull/6651).
> Enable change to determine calling method for OSR code unconditionally

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
eclipse/openj9#6643 has made the change to start
using `JITServer` names. As a follow up to PR #4173,
this change removes all the references to `JITaaS` completely.
> Remove JITaaS name references

- compiler/optimizer/OMROptimizer.cpp
Enable new optimization passes for OpenJ9 associated with Escape Analysis, `preEscapeAnalysis` and `postEscapeAnalysis`, only under OSR.
Submitted on behalf of Andrew Craik <ajcraik@ca.ibm.com>
This pull request is dependent upon [~OpenJ9 pull request 5737~](https://github.com/eclipse/openj9/pull/5737) [OpenJ9 pull request 6654](https://github.com/eclipse/openj9/pull/6654), which is in turn dependent upon pull request #3841
> Enable Pre-/PostEscapeAnalysis optimizations for OpenJ9

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
Add `OMR::ARM64::TreeEvaluator::areturnEvaluator` to handle `areturn`,
which was handled by `lreturnEvaluator`.
`areturnEvaluator` sets the return info to `TR_ObjectReturn` while
`lreturnEvaluator` sets it to `TR_LongReturn`.
> AArch64: Correct return info of methods with reference return type

- compiler/arm/codegen/OMRInstruction.hpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/ras/Debug.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRInstruction.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
There is currently overlap on the Z codegen on ways to add breakpoints
in compiled code. We deprecate the break point list in favor of using
the more robust `BREAK` pseudo-instruction which generates a the binary
encoding recognized by debuggers.
> Deprecate isBreakPoint in favor of the BREAK pseudo-instruction

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
> Copy linkage register info to parm symbols during CodeGenerator init

- compiler/ilgen/OMRBytecodeBuilder.cpp
- compiler/ilgen/OMRIlBuilder.cpp
- compiler/ilgen/OMRIlType.cpp
- compiler/ilgen/OMRJitBuilderRecorderBinaryBuffer.cpp
- compiler/ilgen/OMRMethodBuilder.cpp
- compiler/ilgen/OMRTypeDictionary.cpp
- compiler/ilgen/OMRVirtualMachineOperandArray.cpp
- compiler/ilgen/OMRVirtualMachineOperandStack.cpp
- compiler/ilgen/OMRVirtualMachineRegister.cpp
Every condition being checked by assertions in the JitBuilder
implementation classes is non-recoverable, so we should make
these assertions fatal.
> Use TR_ASSERT_FATAL for JitBuilder assertions

- compiler/env/CompileTimeProfiler.hpp
- compiler/infra/BitVector.cpp
- compiler/optimizer/DebuggingCounters.cpp
- compiler/ras/CallStack.cpp
- compiler/ras/Debug.cpp
Correct several printf format specifiers.
> Fix warnings in compiler files

- compiler/runtime/OMRRuntimeAssumptions.hpp
Add documentation about the API and some warnings to avoid potential
double free bugs for future developers.
> Document OMR::RuntimeAssumption::reclaim()

- cmake/modules/platform/toolcfg/gnu.cmake
- omrtrace/CMakeLists.txt
Fixes a problem with strncpy inlining in the omrtrace component
when the build type is Release. Without this fix, the following
error can occur on the Linux platform using the GNU toolchain:
In file included from /usr/include/string.h:635:0,
from omr/include_core/omrstdarg.h:27,
from omr/omrtrace/omrtracelog.cpp:25:
In function ‘char* strncpy(char*, const char*, size_t)’,
inlined from ‘OMR_TraceBuffer* getTrcBuf(OMR_TraceThread*, OMR_TraceBuffer*, int)’ at omr/omrtrace/omrtracelog.cpp:290:75:
/usr/include/x86_64-linux-gnu/bits/string3.h:126:71: error: call to char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int) will always overflow destination buffer [-Werror]
return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
This problem was fixed …
> Fix omrtrace component build when CMAKE_BUILD_TYPE=Release

- compiler/infra/OMRCfg.cpp
- compiler/infra/OMRCfg.hpp
Commit fbb7aa1713ddc61affecc02dba9c80a393a658af introduced a new API
for adding edges to the CFG and marked the previous implementations
of `addEdge` and `addExceptionEdge` as deprecated. This current
commit removes the deprecated implementations from the code base.
Signed-off-by: Erick Ochoa <eochoa@ualberta.ca>
Depends on this OpenJ9 merge: https://github.com/eclipse/openj9/pull/6141
> Remove deprecated `addEdge` and `addExceptionEdge`

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/OMRInstructionDelegate.hpp
This commit adds support for Labels and Helpers as the target of
ARM64ImmSymInstruction (used for bl instruction).
> AArch64: Allow Labels and Helpers as target of ARM64ImmSymInstruction

- include_core/omrhookable.h
- util/hookable/hookable.cpp
- Adding a `totalTime` field for the OMR Hook info, which is sum of previous events duration
- Changing the measurement time from ms to us for increased precision.
- Will be accompanied by a change on j9 side to reflect the time measurement change
Signed-off-by: Cedric Hansen <cedric.hansen@ibm.com>
> Adding a totalTime field for hooks

- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
A cfgSimplifier opt is generating bsub which can be converted
to badd, both of which are not implemented in the POWER code
generator. The cfgSimplifier opt that makes use of bsub is
currently disabled, but it could be re-enabled at any time so
we need to have bsub and badd supported on POWER.
> Implement TR::badd and TR::bsub evaluators

- thread/linux/omrthreadnuma.c
z/TPF does not make use of sys/syscall.h.  The update
was to simply move the header include statement into
a !z/TPF guard macro block in the linux/omrthreadnuma.c
segment.
> Minor Header Platform configuration change for z/TPF

- compiler/aarch64/codegen/GenerateInstructions.cpp
This commit removes the code for embedding the "N" bit from
functions such as generateArithmeticShiftRightImmInstruction().
The bit is of no use because it is later masked by
insertImmediateField() in ARM64Trg1Src1ImmInstruction.
The "N" bit (bit 22) is encoded in TR::InstOpCode::sbfmx and ubfmx
in OpBinary.cpp instead.
> AArch64: Remove unused bit from generating shift instructions

- omrmakefiles/rules.aix.mk
- remove unsupported options: -qmbcs, -qinfo
- replace -qlanglvl=extended with -qlanglvl=extended0x
- add -qxlcompatmacros to enable legacy macros
- add -fno-exceptions -fno-rtti options to C++ flags
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
> Update C and C++ flags to support AIX XL/C 16.1 Clang-based compiler 

- compiler/aarch64/codegen/ARM64Instruction.cpp
This commit fixes the register assignment for the source1 register
in ARM64MemSrc1Instruction.
decFutureUseCount() was not called for the source1 register when
it had an assigned real register.
> AArch64: Fix register assignment for ARM64MemSrc1Instruction

- compiler/control/OMROptions.cpp
The openj9 project has a feature that lowers invocation counts for
cold AOT runs (JVM invocations with AOT enabled, but empty shared
class cache). For diagnostic purposes we would like a command line
option to disable this feature.
The newly added option is  -Xjit:dontLowerCountsForAotCold
> Add option to disable lowerCountsForAotCold feature

- compiler/codegen/OMRRegisterPair.cpp
- compiler/codegen/OMRRegisterPair.hpp
Remove `REGPAIR_THIS` macro.
Add `self()` as a private method for `RegisterPair
Fixes #3969
> Replace REGPAIR_THIS macro with self()

- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertriltest/MaxMinTest.cpp
Change evaluator for `fmax`, `fmin`, `dmax` and `dmin` from `maxEvaluator` to `UnImpOpEvaluator`.
Add Tril tests for `fmax`, `fmin`, `dmax` and `dmin`.
Fixes #4176
> Change floating point min/max and double min/max to UnImpOpEvaluator on Z

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit adds a call to missing addToAtlas() in doBinaryEncoding()
for AArch64.
> AArch64: Add addToAtlas() in doBinaryEncoding()

- .gitignore
Folder ccls-cache and compile_commands.json used by Vim for autocompletion.
Closes: #4270
Signed-off-by: Batyr Nuryyev <nuryyev@ualberta.ca>
> Added ccls-cache and compile_commands.json into gitignore

- cmake/modules/OmrMetalC.cmake
- -o option needs to be passed before input source file to assembler
- OMR_METALC_ASM_FLAGS needs to be formatted as a list (otherwise it gets
passed on command line as one long argument
- xlc does not generate an assembly list file
- CMake does not seem to be able to track dependencies properly across
3 'add_custom_command's. In addition, if CMake needs to know about the
intermediate .c file, otherwise it complains about a invalid files in
object libraries
> CMake: Fix bugs in omr_comple_metalc

- port/common/j9nls.c
- port/unix/omrfiletext.c
In OMR the default encoding of all strings on z/OS is the native
encoding, which is EBCDIC. As such we do not want to convert strings
from EBCDIC to ASCII when using the various tty OMR APIs. In this
instance calls to `omrtty_err_printf` for example will end up being
incorrectly converted from EBCDIC to EBCDIC and garbage characters will
be printed out to the screen.
> Avoid EBCDIC to ASCII translation in omrfile_write_text in OMR

- include_core/omrhookable.h
- util/hookable/hookable.cpp
- measurement time has been changed from ms to us for
increased precision in Hook tracepoint(Pull request#4221).
- need to update the default tracepoint threshold to microsecond
to avoid triggering warning too frequent.
related: eclipse/omr#4221
> Update hook tracepoint threshold to microsecond instead of millisecond

- gc/base/GCExtensionsBase.hpp
tail candidate list is created for reusing free space of survivor
regions and tenure regions. sort the list Ascending or Descending
might help reduce fragmentation or increasing Cache locality.
- add global variable tarokTailCandidateListSortOrder
the variable can be set Ascending, Descending or no order.
- default is no order.
> Option to sort Tail Candidate List by free size

- example/glue/MixedObjectScanner.hpp
- gc/base/IndexableObjectScanner.hpp
- gc/base/ObjectScanner.hpp
- gc/base/standard/Scavenger.cpp
Currently GC_ObjectScanner has slot _parentObjectPtr to store pointer to
header of scanned object. This slot is used for Scan Cache
initialization for split array in Scavenger.
So there is no real use for this field for GC_ObjectScanner or it's
Mixed Object scanners children. In case we need to scan Headless Mixed
object an address of object header is even not available (as far as
there is no any). So the proposal is to move it to
GC_IndexableObjectScanner with renaming of field (_parentObjectPtr to
_arrayPtr) and correspondent function (getParentObject() to
getArrayObject())
This change required a silo dance, so this is first step of three:
- add new constructor to GC_ObjectScanner
- add _arrayPtr field to GC_IndexableObjectScanner
- replace getParentObject() to getArrayObject()
- remove …
> Remove object pointer from Object Scanner

- compiler/optimizer/LoopVersioner.cpp
In `TR_LoopVersioner::versionNaturalLoop`, a `NULLCHK` might be specialized away.  However, it will still appear among the list of treetops that are tracked in `nullCheckTrees`.  When subsequent operations iterate over that list, they must skip `NULLCHK` nodes that no longer take effect.
> Skip NULLCHK that has already been optimized away in Loop Versioner

- buildenv/jenkins/jobs/builds/Build-zos_390-64
Synchronize the PullRequest and Build pipelines to use the same method
of building and testing commits. The current state of the z/OS builds
as seen in [1] is not great as they're more or less always failing
because we are not running the same set of tests which get tested via
PRs. This commit synchronizes so we test the exact same thing,
similarly to what we do on all the other platforms.
[1] https://github.com/eclipse/omr/commits/master
> Use CMake for z/OS Build pipeline

- compiler/env/OMRClassEnv.cpp
- compiler/env/OMRClassEnv.hpp
New member functions are being added
to `J9::ClassEnv` (eclipse/openj9#7018)
In order for member functions to be called
without using the implicit `this` pointer,
add `self()` method to the extensible class `ClassEnv`.
> Add self method to ClassEnv

- port/zos390/omrsl.c
Reverts eclipse/omr#4277
The new calls are failing to find libraries, where the old calls succeeded. Reverting this PR until we can find a fix.
Here is a log from j9, showing new failures:
```
** ASSERTION FAILED ** j9vm.226 at ./vmprops.c:558 Assert_VM_notNull((optionString) != NULL)
JVMJ9VM011W Unable to load j9dmp29: JVMPORT002E Unknown error loading shared library
JVMJ9VM011W Unable to load j9trc29: JVMPORT002E Unknown error loading shared library
JVMZIPS000W Unable to open j9zlib29 (JVMPORT002E Unknown error loading shared library)
JVMJ9VM013W Initialization error in function VMInitStages(1): JVMJ9VM009E J9VMDllMain failed
```
/cc @AidanHa
> Revert "Replace deprecated DLL system calls"

- jitbuilder/optimizer/JBOptimizer.cpp
Somehow, the warm strategy used by JitBuilder is missing a late
redundant goto cleanup pass needed to cleanup after GRA, which
tends to introduce blocks that end up as simple goto's after
global dead store elimination.
> Add late goto elimination pass to JitBuilder's opt strategy

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This code adds code for generating instruction for masking VFTMask.
> AArch64: Generate VFTMask in aloadEvaluator()

- util/avl/CMakeLists.txt
OMR_SOURCE_DIR in all capitals is undefined, causing the include path to
be: `-I/include_core`. The build does not fail because other libraries
have the proper include path `-I../include_core`.
> Fix include path for avl

- .gitignore
.ccls stores completion data for the CCLS autocomplete engine
> Add .ccls to git ignore

- tools/hookgen/HookGen.cpp
Hookgen is printing all arguments that were passed to it.  Remove this
as it is not helpful and verbose.
> Make hookgen invocation less verbose

- gc/base/IndexableObjectScanner.hpp
- gc/base/ObjectScanner.hpp
- Remove _parentObjectPtr and _hotFieldsDescriptor slots
- Use new ObjectScanner constructor in IndexableObjectScanner
> Final cleanup of ObjectScanner

- compiler/x/codegen/ControlFlowEvaluator.cpp
sucmpeq evaluator is used to evaluate both sucmpeq and sucmpne
and Codegen fails when CFGSimplifier was performed generating 
setne regardless of evaluation. Added Boolean to properly select
correct sete/ne instruction.  
Signed-off-by: Jacob Nauenberg <jacob.nauenberg@ibm.com>
> Fix TR::sucmpeq evaluator

- compiler/il/OMRBlock.cpp
In Post GRA Block splitter, std::map is used to store information about nodes which are referenced after the split point and will be uncommonned. In this information we basically store how many times node is referenced after split point and a replacement node to use post split point.
There was a bug in the routine where it scans treetops before split-point and adds nodes into this map. In cases where node is not added into the map and referenced only one time, it was accessing value field from `map::end` and illegally modifies it. On macOS this was causing an alteration into memory area which happened to be pointing at a `stackMemoryRegion` which was used to allocate some of the data structures required by this same routine. This later on manifested into segmentation fault.
Changes in …
> Fix macOS failures in Post GRA Block splitter

- compiler/infra/Checklist.hpp
- compiler/optimizer/LoopVersioner.cpp
In `TR_LoopVersioner::versionNaturalLoop`, while walking through the loop body looking for OSRGuards, the code should skip any OSRGuards that have already been included in the list of removed nodes.
Also added a debugging print method to `TR::NodeCheckList`.
Submitted on behalf of Andrew Craik <ajcraik@ca.ibm.com>.
> Skip OSR Guards nodes that have already been removed

- example/CMakeLists.txt
- example/gcmain.cpp
`gcexample` allocates objects with the NO_GC flag in a loop until the
heap is exausted.  After this it allocated one more time causing a
garbage collection.  At some point it stopped using the NO_GC flag,
causing the test to constantly allocate objects and collect them in an
infinite loop. This change fixes the allocation flags
> Fix hang in gcexample

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
As discussed in eclipse/openj9#7049 this phase no longer serves any
purpose since the support for allocating warm and cold blocks at the
code cache level has been removed from the compiler.
> Deprecate splitWarmAndColdBlocksPhase

- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
Routed sadd/ssub operations to iadd/isubEvaluator and added comptril tests for badd/bsub and sadd/ssub
NOTE: Should not be merged before https://github.com/eclipse/omr/pull/4212
Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>
> Add Power evaluators for sub-int type addition/subtraction

- port/common/omrcuda.cpp
NVIDIA released CUDA 10.1 in February, 2019.
> Add support for CUDA 10.1

- compiler/z/codegen/ControlFlowEvaluator.cpp
The masks for the SELECT instruction are generated such that the false result in a ternary is favored. Thus, the register order needs to be rearranged when generating the instruction.
> Fix register order when generating SELECT instruction

- compiler/il/Aliases.cpp
This commit changes the code in Aliases.cpp that calls
TR_PersistentMethodInfo::get() so that it checks RecompilationInfo
before that.
> Call TR_PersistentMethodInfo::get() after checking RecompilationInfo

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds code for creating exception table entries for OOL
code for AArch64.
> AArch64: Add code for creating exception table entries for OOL code

- port/unix/omrsysinfo.c
* missing comma if both `RLIMIT_SIGPENDING` and `RLIMIT_MEMLIMIT` defined
* use 'defined(XXX)' consistently (parentheses & spacing)
> Fix potential compile error

- gc/base/standard/Scavenger.cpp
Code does not compile without flag OMR_GC_MODRON_SCAVENGER
because end of file was outside of final #endif
> Fix Scavenger.cpp flag OMR_GC_MODRON_SCAVENGER position

- ddr/lib/ddr-ir/Symbol_IR.cpp
The size of an enum type is unknown if first seen in the debug info from:
```
enum Flavour;
void * sample(enum Flavour *flavour) { return flavour; }
```
(e.g. in DWARF, there is no `DW_AT_byte_size` attribute); remember the size if available in a subsequent compilation unit.
This is like #2336, but for enums.
> DDR: merge enum sizes

- compiler/ras/CallStack.cpp
Changed demangler call from Demangle() (defined in demangle.h) to __cxa_demangle() (defined in cxxabi.h) for xlclang++.
Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>
> Enable XLC 16.1 toolchain for AIX platforms

- include_core/omr.h
- include_core/omrcomp.h
Add macros OMRVM_REFERENCE_SHIFT, OMRVMTHREAD_REFERENCE_SHIFT and
OMR_LOG_POINTER_SIZE for use in mixed mode.
> Runtime compressed refs work

- compiler/il/Block.hpp
- compiler/il/OMRBlock.cpp
- compiler/il/OMRBlock.hpp
- compiler/infra/OMRCfg.cpp
- compiler/infra/OMRCfg.hpp
Base class CFGNode has two constructors,
1) one that takes a TR_Memory * parameter
2) one that takes a TR::Region& parameter
When the first constructor is used the sucessors and predecessors
are stored in the parameter region. Otherwise, they are stored in the
heap memory region.
Child class OMR::Block only implements the first type of constructor.
This commit creates another constructor for OMR::Block which takes a
TR::CFG & parameter and uses the internal memory region for calling
the second type of CFGNode constructor.
Signed-off-by: Erick Ochoa <eochoa@ualberta.ca>
Must be merged this OpenJ9 PR before https://github.com/eclipse/openj9/pull/6866
> Use CFG's internal region on CFGNodes

- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
Change `OMRTreeEvaluatorTable.hpp` so that `TR::s2b` is handled
by `l2iEvaluator`.
> AArch64: Enable evaluator for TR::s2b

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/env/OMRClassEnv.hpp
- compiler/env/TypeLayout.hpp
The TypeLayout API abstracts the process of querying and caching
information related to the layout of objects in memory - this API
will be needed to help implement the newvalue opcode because its
meaning is coupled to the layout of the type being instantiated.
Signed-off-by: Yiling Han <Yiling.Han@ibm.com>
> Add a TypeLayout introspection api

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit makes changes to OMRMemoryReference for AArch64.
They are required by loadaddrEvaluator().
> AArch64: OMRMemoryReference changes for loadaddrEvaluator()

- port/CMakeLists.txt
- thread/CMakeLists.txt
- thread/exports.cmake
- util/hookable/CMakeLists.txt
- util/omrutil/CMakeLists.txt
This is in preparation of removing the object libraries see #4357
> CMake: add export symbol info onto shared libraries

- compiler/compile/OMRCompilation.cpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Use JProfiling infrastructure instead of JIT Profiling infrastructure for profiling compilations on all platform except x86-32 Bit platform.
> Enable JProfiling in Profiling Compilations

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
This series of commits consolidates the JIT-to-JIT entry point alignment on all codegens so we all use the same API, namely `alignBinaryBufferCursor`, to perform the alignment. As part of this change we introduce several new APIs and rename some existing ones so as to stay more consistent. We also take this opportunity to document all the APIs.
This cleanup is a step towards commoning up the Binary Encoding phase across codegens and will hopefully help the adaptation of new code generators, such as ARM, AArch64, and RISC-V.
> Consolidate JIT-to-JIT entry point alignment on all codegens

- compiler/aarch64/codegen/ARM64HelperCallSnippet.cpp
This commit adds implementation of debug print function for
`TR::ARM64HelperCallSnippet`.
> AArch64: Add implementation of debug print function for ARM64HelperCallSnippet

- compiler/codegen/CodeGenGC.cpp
- compiler/codegen/OMRInstruction.cpp
- compiler/codegen/OMRInstruction.hpp
Field is no longer in use, neither are its getters and setters.
change `instr->getRegisterSaveDescription()` to zero in the GC stack map.
> Remove _registerSaveDescription from OMRInstruction.hpp

- compiler/x/codegen/CompareAnalyser.cpp
Fix double decrement on node reference counts and properly sign it
Corrects the double decrement of node reference counts in the x86 integer compare analyser by bounding the depth of recursion used to decrement node reference counts in subtrees.
Fixes: #4121 
Signed-off-by: Mark Thom <mark.thom@unb.ca>
> Correct double decrement of node reference counts in x86 integer compare analyser

- CMakeLists.txt
- cmake/modules/platform/os/zos.cmake
The `install()` command needs to be called from the same directory that
defines the targets. The current code works because the top level
CMakeLists includes  zos.cmake (which defines the libraries). However
If a consumer of omr includes zos.cmake before calling add_subdirectory
on omr, the definition and installation commands will be in different
directories
> Cmake: Fix install of omr_ebcdic and omr_ascii targets

- compiler/x/codegen/BinaryCommutativeAnalyser.cpp
- compiler/z/codegen/S390Instruction.hpp
The word 'instruction' was spelled wrong in 2 omr files
Signed-off-by: Kishor Patil <patil@ca.ibm.com>
> Fix Typo of word instruction

- compiler/p/codegen/OMRRegisterDependency.cpp
- run_configure.mk
This change fixes two small typos of the word 'specific'
Signed-off-by: Pushkar Bettadpur <pushkar.bettadpur@gmail.com>
> Fixes two typos

- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/arm/codegen/OMRTreeEvaluatorTable.hpp
- compiler/il/OMRILOpCodeProperties.hpp
- compiler/il/OMRILOpCodesEnum.hpp
- compiler/optimizer/OMRSimplifierTableEnum.hpp
- compiler/optimizer/ValuePropagationTable.hpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- compiler/ras/Tree.cpp
- compiler/x/amd64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/x/i386/codegen/OMRTreeEvaluatorTable.hpp
- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
The newvalue opcode both allocates and initializes an
immutable object whose identity is either unobservable or otherwise
considered irrelevant, i.e. a value. Allocation and initialization
are combined into a single step so that semantically the fields
are never mutated, allowing highly aggressive aliasing
properties and facilitating scalarization.
Issue: #4028
Signed-off-by: Yiling Han <Yiling.Han@ibm.com>
> Add the newvalue opcode

- compiler/il/OMRDataTypes.hpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCInstruction.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
- fvtest/tril/tril/compiler_util.hpp
- fvtest/tril/tril/ilgen.cpp
Previously, the Power codegen was performing NaN canonicalization using
the control flow pseudoinstructions cfnan and cdnan. These have now been
replaced with proper internal control flow.
> Remove cfnan and cdnan pseudoinstructions

- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, the implementations of the irol and lrol opcodes in the
Power codegen were in functions in OMRTreeEvaluator.cpp. This was a
holdover from when these functions were used for inlining certain
recognized methods in OpenJ9. Since this dependency has since been
removed, using separate functions for this is now redundant and the
implementations of the irol and lrol opcodes have been moved into their
respective evaluators.
> Move implementations of irol/lrol into BinaryEvaluator.cpp

- compiler/aarch64/codegen/ARM64HelperCallSnippet.cpp
- compiler/aarch64/codegen/ARM64HelperCallSnippet.hpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- This commit changes ARM64HelperCallSnippet to always use `bl` instruction
instead of `b`.
- The mainline code which jumps to a helper call snippet does not use `bl` instruction because aarch64 instruction set does not have conditional branch-and-link instruction. Thus, we need to use `bl` instruction so that the stack walker can find the correct gc map.
- This commit also adds getSnippetForGC virtual function to instruction classes defined in ARM64Instruction.hpp
- This commit also changes the evaluator using ARM64HelperCallSnippet to set register mask to GC map of the snippet.
> AArch64: Change ARM64HelperCallSnippet to set GC Map to the branch instruction

- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
Add a case in genericLongShiftSingle that would generate
a RISBG command for a LSHR->LAND pattern
Add a similar case for LSHL->LAND pattern
Add a similar case for the unsigned variants of the
instruction(LUSHR and LUSHL)
Rename tryToReplaceLongAndWithRotateInstruction() to
tryToReplaceShiftLandWithRotateInstruction()
Allocate target register properly in
tryToReplaceShiftLandWithRotateInstruction()
Add respective Tril test for these changes
Fixes #3212
Signed-off-by: Aidan Ha <qbha@edu.uwaterloo.ca>
> Improve rotate then insert selected bits on Z

- gc/base/GCExtensionsBase.hpp
- gc/base/MemoryPoolBumpPointer.cpp
- gc/base/MemoryPoolBumpPointer.hpp
region tail point to the last freespace which connect to region top,
can be reused as survivor or tenure space during copyforward.
the first sweep after GMP does reset all of region tails.
recover region tails during post-sweep could reduce copyforward
abort cases.
- global variable tarokEnableRecoverRegionTailsAfterSweep for
enabling/disabling recover region tails during post-sweep.
- global variable tarokEnableAllocationPointerAssertion for
enabling verifying recovered tails.
- add freeList and last free entry in MemoryPoolBumpPointe.r
- generate freelist during sweep(for MemoryPoolBumpPointer).
> Recover Region tail during post-sweep of GMP

- compiler/arm/codegen/OMRTreeEvaluatorTable.hpp
> Fix typo in ARM TreeEvaluatorTable

- fvtest/tril/examples/incordec/main.cpp
- fvtest/tril/examples/mandelbrot/main.cpp
- jitbuilder/release/cpp/samples/Union.cpp
When compiling in release mode, we compile with `-DNDEBUG`.  When this
happens any statements inside of asserts are not run.  We must
initialize the jit outside of the assert.
> Remove side effects in assert statements

- compiler/aarch64/codegen/OMRLinkage.hpp
- compiler/env/TRMemory.cpp
- compiler/env/TRMemory.hpp
This commit adds some types for ARM64 to TRMemory.
> AArch64: Add types for ARM64 to TRMemory

- compiler/compile/OMRSymbolReferenceTable.cpp
OMR::SymbolReferenceTable::methodSymRefFromName creates a method symref
using the value returned by fe()->getMethodFromName. However, it is
possible for the value to be NULL in relocatable compiles (for various
runtime specific reasons).
This PR handles the case where a NULL is returned.
Fixes: https://github.com/eclipse/openj9/issues/6511
Fixes: https://github.com/eclipse/openj9/issues/7273
> Handle symref creation under relocatable compiles

- include_core/omrport.h
- include_core/omrportsock.h
- port/CMakeLists.txt
- port/common/omrport.c
- port/common/omrsock.c
- port/omrportpriv.h
- port/port_objects.mk
Created Functions Unimplemented Prototypes in omrsock.c
-Modified omr files to be able to see and compile omrsock code
-Added new omrsock.c files for common, this
includes function prototypes proposed by the Socket API proprosal
-Added omrsock variables needed by the function prototypes. They are
created in omrportsock.h
Issue #4102
> Created Function Prototypes for OMRSocketAPI

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements an unimplemented path in loadaddrEvaluator().
> AArch64: Implement a path in loadaddrEvaluator()

- compiler/runtime/Trampoline.cpp
This commit rewrites arm64CreateHelperTrampolines() in Trampoline.cpp.
The existing code was copied from the 32-bit ARM version, which never
works in AArch64.
> AArch64: Rewrite arm64CreateHelperTrampolines()

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit enables those evaluators because those evaluators are generated
when running some benchmark programs with noOpt.
Actual implementation of those evaluators are same as ones of `lucmp` evaluator variants.
> AArch64: Enable acmpeq, acmpne, acmplt, acmpge, acmpgt and acmple evaluators

- compiler/z/codegen/BinaryEvaluator.cpp
If the node entered is a common node, then there is no guarantee that the child of the common node will still be alive. And when we try to access the value in that node, we might receive values from a node that might've been killed already. Thus, The optimization will not work.
Fixes GH-4298
> Add fix for tryToReplaceShiftLandWithRotateInstruction

- compiler/il/OMRNode.cpp
Add `ladd`/`lsub`  support in the `isTernaryhigh`, `isDualhigh`, `isAdjunct` and
`setIsAdjunct` functions as the `luadd`/`lusub` are going to be replaced by
their signed versions.
Simply replacing all `luadd` and `lusub` by `ladd` and `lsub` would cause segmentation faults without this change. eclipse/openj9#7004
> Add OMR support for removing deprecated unsigned opcodes: TR::luadd and TR::lusub

- compiler/infra/Assert.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
assert(0) does nothing on a release build, so abort() instead.
Use TR::trap() instead of assert(0) in OMRTreeEvaluator.
> Make TR:Trap() work on release builds

- compiler/p/runtime/PPCCodeSync.inc
Also:
* correct type of `cacheLineSize`
* remove redundant computation of `limit`.
> Remove assumption that sizeof(unsigned long) == sizeof(void *)

- compiler/z/codegen/OMRTreeEvaluator.cpp
Code generation for all compare and branch instructions has been
consolidated into `generateS390CompareAndBranchInstruction()` API.
Instructions consolidated in this commit are `CIJ` and `CGIJ`.
This is allows for compare and branch instruction optimizations to be
applied through a common point. In addition to that, all compare and
branch instructions can now be to be disabled through
`Xjit:disableCompareAndBranch`.
> Improved code generation for compare and branch instructions

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds arrayTranslateMinimumNumberOfElements and
arrayTranslateAndTestMinimumNumberOfIterations to aarch64 codegen to
avoid hitting assert.
> AArch64: Provide thresholds for arrayTranslate/arrayTranslateAndTest

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertest/tests/OpCodesTest.cpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
Routed bmul/smul to imulEvaluator, modified imulEvaluator accordingly, and added corresponding tril tests.
NOTE: Should not be merged before https://github.com/eclipse/omr/pull/4249
Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>
> Add Power evaluators for sub-int type multiplication

- compiler/codegen/CodeGenPhaseToPerform.hpp
- compiler/codegen/OMRCodeGenPhase.cpp
- compiler/codegen/OMRCodeGenPhase.hpp
- compiler/codegen/OMRCodeGenPhaseEnum.hpp
- compiler/codegen/OMRCodeGenPhaseFunctionTable.hpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/codegen/OMRInstruction.hpp
- compiler/z/codegen/CodeGenPhaseToPerform.hpp
Currently, there are many instances where a single TR::Instruction will
end up being binary encoded as multiple instructions. While there are
some cases which cannot be easily avoided, such as alignment using nops,
since they rely on information only available during binary encoding,
many do not require any such information. Performing these expansions
during binary encoding is more error-prone, requires the binary length
estimation functions to take such expansions into consideration, and
sometimes results in confusing mismatches between what a tracefile says
was emitted and what is seen during disassembly.
A better solution would be to expand these sequences into multiple
TR::Instruction objects and allow binary encoding of these to proceed as
normal. However, it is often not desirable …
> Add a new codegen phase for instruction expansion

- compiler/compile/Method.cpp
- compiler/compile/ResolvedMethod.hpp
- fvtest/compilertest/compile/Method.cpp
- fvtest/compilertest/compile/Method.hpp
- jitbuilder/compile/Method.cpp
- jitbuilder/compile/Method.hpp
The two implementations of `ResolvedMethod::makeParameterList` in
JitBuilder and CompilerTest are identical, and they are a more appropriate
default implementation in OMR than the existing `makeParameterList` which
is tailored to OpenJ9.  Consolidate their implementations in the OMR
`TR_ResolvedMethod` class and remove their implementations from JitBuilder
and CompilerTest.
Create an API to obtain the IlType of a parameter if it is available.
Closes #3909.
> Change default implementation of makeParameterList

- compiler/optimizer/LoadExtensions.cpp
Currently we are seeing issues with load extension on Z where we are using a full 64 Bit register for 32 Bit values assuming the value is extended load at the source. Disabling the portion of the Load Extensions which uses Global Use Def info to do the optimization.
> Disable portion of Load Extension on Z

- compiler/optimizer/SwitchAnalyzer.cpp
The switch analyzer currently uses an int8_t counter to count the number
of time a given block is a successor of the swtich/table. This can easily
overflow and result in undefined behaviour by the C++ code. This change
enlarges the compiler to int32_t to prevent this kind of overflow and
improves the assert to ensure a sesnible number is being generated.
> Enlarge SwitchAnalyzer successor counter

- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
Stop generating deprecated unsigned opcodes of `Multiply`/`Ternary`/`Shift`/`Shift logical` from OMR.
Using `TR_ASSERT_FATAL` to ensure no downstream projects will attempt to use aforementioned opcodes. 
Note that there is no assertion for `TR::cmul` and `TR::cshl` as they no longer exist in the opcode list.
Issue: #2657
> Stop generating deprecated Multiply/Ternary/Shift/Shift logical opcodes from OMR

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit adds code for setting the destination address of "bl"
instruction in ARM64ImmSymInstruction when possible, to improve the
readability of trace files.
> AArch64: Set destination address in ARM64ImmSymInstruction

- include_core/AtomicSupport.hpp
**Job failure:** https://ci.eclipse.org/omr/job/PullRequest-aix_ppc-64/1584/console.
**Details:**
1540-0256 (S) A parameter of type "volatile unsigned long *" cannot be
initialized with an expression of type "volatile long *".
1540-1205 (I) The error occurred while converting to parameter 1 of
"__fetch_and_swaplp(volatile unsigned long *, unsigned long)".
**Related:** https://github.com/eclipse/omr/pull/4469.
From the XLC AIX documentation,
```
Prototype:
unsigned int __fetch_and_swap (volatile unsigned int* addr, unsigned int val); 
unsigned long __fetch_and_swaplp (volatile unsigned long* addr, unsigned long val);
```
> Fix the compile failure related to the lockExchange function on AIX

- gc/base/MasterGCThread.cpp
- gc/base/MasterGCThread.hpp
- gc/base/standard/Scavenger.cpp
Previously, after terminating and yielding to an exclusive VM access request, Concurrent Scavenger would only resume if it yielded to an **external** request. However, CS should also resume after yielding to **internal GC request** CM init as this completely terminates CS and results in missed opportunity for CS to make progress.
- upon GC termination request, `_concurrentState` is no longer transitioned to `concurrent_state_complete`, it's left in scan state.
- Introduced `_concurrentResumable` configuration param for `MasterGCThread` which is set to true if the collector is resumable. (initialized to true for Scavenger, defaults to false for balanced)
> Concurrent GC Yield and Resume after CM VM Exclusive

- thread/common/omrthread.c
1. Fix formatting of `ifdefs`.
2. Initialize variables, fix null checks and use `OMR_ARE_*_BITS_SET` macros.
3. Remove unnecessary `NULL` checks around `omrthread_free_memory`.
> Improve OMR thread library code

- compiler/z/codegen/ConstantDataSnippet.cpp
Use FE query to decide if data represented by RamMethodConst
and JNITargetAddress need relocation records.
> Add relocation records correctly inside ConstantDataSnippets

- compiler/il/OMRILOps.hpp
Remove `TR::ILOpCodes OMR::ILOpCode::unsignedShiftLeftOpCode(TR::DataType type)` function.
Closes:#4467
> Remove OMR::ILOpCode::unsignedShiftLeftOpCode function

- compiler/optimizer/OMRSimplifierHandlers.cpp
checkAndReplaceRotation tests for pattern validity by comparing an expected
shift amount based on the size of the operand with the constant from the
multiply node:
```
if ( (1 << correctLeftShiftAmount) != mulConst )
return false;
```
Unfortunately, the implicit int constant '1' allows the C++ compiler to ignore
the possibility of shift amounts>32 (undefined behaviour), resulting in 1<<n
giving the same answer as 1<<(n+32). This allowed the simplification to proceed
on a 64 bit operand with shift values that were only valid for 32 bit operands.
The shift has been updated with code crafted by Leonardo which allows the test
to correctly differentiate between 32 and 64 bit valid patterns.
Signed-off-by: James Kingdon <jkingdon@ca.ibm.com>
> Fix checkAndReplaceRotation 32/64 bit ambiguity

- include_core/AtomicSupport.hpp
For XLC versions < 13.1.3, the following __fetch_and_swap(lp)
definitions are supported:
i) __fetch_and_swaplp(volatile long *, long)
ii) __fetch_and_swap(volatile int *, int)
For XLC versions >= 13.1.3, the following __fetch_and_swap(lp)
definitions are supported:
i) __fetch_and_swaplp(volatile unsigned long *, unsigned long)
ii) __fetch_and_swap(volatile unsigned int *, unsigned int)
Co-Authored-By: Robert Young <rwy0717@gmail.com>
> Handle __fetch_and_swap(lp) across XLC versions used by OMR consumers

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
Previously, ExpandInstructionsPhase would iterate over every instruction
and call a virtual method on each, even if the codegen in question
wasn't making use of it. Since only the Power codegen currently has
plans to make immediate use of this phase, other codegens do not need to
be doing this. To avoid performing unnecessary work, expandInstructions
is now stubbed out on all codegens other than Power.
> Disable ExpandInstructionsPhase on codegens that don't use it

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
When encoding a recursive compiled method call instruction, ask the
linkage for the compiled method entry point.
> Use linkage entry point API for recursive method calls

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/control/OMROptions.cpp
This commit implements a PrefetchEvaluator for AArch64.
It does not generate "PRFM" instructions yet.
> AArch64: Implement PrefetchEvaluator

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Set first instruction to the block of the node in BBStartEvaluator in order to avoid
crash in `J9::CodeGenerator::generateCatchBlockBBStartPrologue`.
https://github.com/eclipse/openj9/blob/c91114a70f3b59d29c747a9ffe2a0a736a86546e/runtime/compiler/codegen/J9CodeGenerator.cpp#L4634
> AArch64: Set first instruction to block in BBStartEvaluator

- compiler/optimizer/LoadExtensions.cpp
- compiler/optimizer/OMROptimizer.cpp
- compiler/optimizer/OMROptimizer.hpp
- compiler/optimizer/UseDefInfo.cpp
- compiler/optimizer/UseDefInfo.hpp
- compiler/optimizer/ValueNumberInfo.cpp
This change implements the recommended refactorig by @andrewcraik in the
review comments
for https://github.com/eclipse/omr/pull/2823.
The background is that we need to allow setting of the _hasCallAsUses
flag depending on the language front-end. However this is currently hard
coded to false. Following is a copy of Andrew's recommendation.
Setting _hasCallAsUses should be handled as part of the constructor if
it needs to be configured by different languages. This is the first time
we are going to have a language specific override of a flag like this
for UseDefInfo. Looking at how it is currently used instances of
TR_UseDef_info are allocated in the OMROptimizer.cpp,
ValueNumberInfo.cpp and LoadExtensions.cpp. There is some variation
between them in how they configure UseDefInfo for …
> Refactor the optimizer to allocate UseDefInfo through a central location

- compiler/infra/Assert.cpp
TR::Assertion is passing the format string, but not the variadic
arguments, to fatal assert. This is causing crashes in the printing
helper.
This commit introduces a new function, va_fatal_assertion, which accepts
a va_list argument. Both assertion and fatal_assertion call this helper.
Using this helper, the arguments should be forwarded along correctly to
the printing helper.
Fixes: #4423
> Forward format args to trace function in nonfatal assertion

- compiler/optimizer/CallInfo.hpp
The old macro doesn't support callsite subclasses for defining more
complicated constructor other than initailizing the fields that exists
in the super class. Adding this ability by breaking the single macro
into three parts 1. TR_ALLOC 2. constructor signature and super classes
field initialization 3. constructor method body
> Refactor callsite constructor macro

- compiler/ras/Debug.cpp
This commit adds AArch64 helpers to getRuntimeHelperName() in Debug.cpp.
> Add AArch64 helpers to getRuntimeHelperName()

- include_core/omrport.h
- include_core/omrportsock.h
- port/CMakeLists.txt
- port/common/omrport.c
- port/common/omrsock.c
- port/omrportpriv.h
- port/port_objects.mk
Created Unimplemented Function Prototypes in omrsock.c
-Modified omr files to be able to see and compile omrsock code
-Added new omrsock.c file for common for all operating systems, this
includes function prototypes proposed by the Socket API proprosal
-Added omrsock variables needed by the function prototypes. They are
created in omrportsock.h
Issue: #4102
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>
> Created Function Prototypes for OMR Socket API

- .appveyor.yml
- .travis.yml
With the merge of #4345 we no longer depend on Flex and Bison being
installed for our testing. AppVeyor seems to be broken at the moment in
that checksums are failing when installing this package. We fix the
issue by removing the dependency as it is no longer needed.
> Remove Flex/Bison from AppVeyor and Travis

- include_core/omrthread_generated.h
- thread/common/threaddef.h
- thread/common/threadhelpers.cpp
1) Add new data structures and macros for implementing MCS locks.
2) Add a field to a store a OMRThreadMCSNodes pointer in J9Thread.
3) Add a field to store a pointer to the MCS queue tail in J9ThreadMonitor.
4) Add function prototypes for the MCS lock API.
5) Add function stubs with description for the MCS lock API.
6) [DONT MERGE] Enable the OMR_THR_MCS_LOCKS flag to verify compilation.
Will remove 6) after it is verified that the code compiles properly through the pull request build jobs.
Related: #4086.
> MCS Locks: Part 1

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
- compiler/ras/Debug.hpp
This commit adds `VirtualGuardNOPInstruction` to aarch64 codegen in order to add support for HCR.
https://github.com/eclipse/openj9/issues/6775
> AArch64: Add VirtualGuardNOPInstruction

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit adds `virtualGuardHelper` function and change `ificmpHelper` to use it.
https://github.com/eclipse/openj9/issues/6775
> AArch64: Implement virtualGuardHelper function

- include_core/omrthread_generated.h
- thread/common/omrthread.c
1) Add code to allocate and free OMRThreadMCSNodes.
2) Initialize J9Thread->mcsNodes.
3) Initialize and reset J9ThreadMonitor->queueTail.
4) [DONT MERGE] Enable the OMR_THR_MCS_LOCKS flag to verify compilation.
Will remove 4) after it is verified that the code compiles properly through the pull request build jobs.
Related: #4086.
Dependent on #4484. Will require a rebase once #4484 is merged.
> MCS Lock (Part 2): Initialize structures for the MCS lock

- port/common/omrstr.c
**Add omrstr_convert target code page CP_ACP/CP_THREAD_ACP**
Added target encoding `J9STR_CODE_WINDEFAULTACP/J9STR_CODE_WINTHREADACP` for Windows code page `CP_ACP/CP_THREAD_ACP`.
required by: https://github.com/eclipse/openj9/pull/7607
Verified that this PR along with https://github.com/eclipse/openj9/pull/7607 fix https://github.com/eclipse/openj9/issues/6722.
FYI: @DanHeidinga @pshipton 
> Add omrstr_convert target code page CP_ACP/CP_THREAD_ACP

- buildenv/jenkins/jobs/builds/Build-aix_ppc-64
- buildenv/jenkins/jobs/pull-requests/PullRequest-aix_ppc-64
- cmake/modules/OmrCompilerSupport.cmake
- compiler/infra/OMRMonitor.hpp
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertest/runtime/TestCodeCacheManager.cpp
- fvtest/compilertest/tests/OpCodesTest.hpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/BitPermuteTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TernaryTest.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
- fvtest/omrGtestGlue/CMakeLists.txt
- fvtest/tril/test/IlGenTest.cpp
- fvtest/tril/tril/CMakeLists.txt
- fvtest/tril/tril/method_compiler.hpp
- fvtest/tril/tril/simple_compiler.cpp
- jitbuilder/control/Jit.cpp
- jitbuilder/runtime/JBCodeCacheManager.cpp
- third_party/gtest-1.8.0/include/gtest/internal/gtest-port.h
Previously, the AIX CI builds were explicitly not compiling nor testing the JIT component, as it turns out that the JIT would not compile correctly under CMake on AIX. This PR fixes some issues with the JIT CMake builds and makes it possible to run both Tril and JitBuilder tests on AIX through use of some similar hacks to what are currently used on z/OS.
As part of this, I've enabled the Tril and JitBuilder tests on our CI AIX builds in this PR. I'm not 100% sure if this will work, as I don't know whether the AIX CI machines have `lex` and `yacc` set up, which are required to compile Tril. If they don't, this PR can wait until #4345 lands, which will remove the dependency on these tools altogether.
FYI @gita-omr @zl-wang
> Enable Tril and JitBuilder tests on AIX

- compiler/arm/codegen/OMRCodeGenerator.cpp
- compiler/arm/codegen/OMRLinkage.cpp
- compiler/x/i386/codegen/IA32SystemLinkage.hpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRLinkage.hpp
J9 private linkage has been largely isolated to OpenJ9 and moved
into the J9 namespace.  Remove unused references in OMR and for
code guarded in project-specific macros reference the appropriate
private linkage class in the J9 namespace.
> Remove references to OpenJ9 private linkage

- fvtest/porttest/CMakeLists.txt
- fvtest/porttest/makefile
- fvtest/porttest/omrsockTest.cpp
Created test stubs in omrsockTest.cpp, in test set PortSockTest in Port Tests
-Created 2 helper function stubs, one for setting up  a server socket, one
for setting up a client socket. These functions will be called multiple times,
in multiple tests.
-Created 4 test stubs in PortSockTest.
-Will need to add other tests during implementation.
Issue: #4102
> Create Test Stubs for OMR Socket API 

- compiler/z/codegen/S390Peephole.cpp
- `CLR` and `BRC` instructions are reduced to `CLRJ`
- The reduction happens only if one of the following conditions are met
1. Branch target is a snippet, or
2. Condition code is not used by the next 5 instructions, or
3. Condition code is set by an instruction in that 5 instruction window
Closes: eclipse/openj9#4384
> Peephole optimizations for BNDCHK evaluator on Z

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/ras/Debug.hpp
This commit implements ARM64Trg1MemSrc1Instruction, for generating
AArch64 "store exclusive" instructions.
> AArch64: Implement ARM64Trg1MemSrc1Instruction

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit adds "nop" and "vgdnop" instructions to ARM64Debug.cpp.
> AArch64: Add "nop" and "vgdnop" to ARM64Debug.cpp

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit adds code to loadRelocatableConstant() in OMRMemoryReference
for AArch64, so that it can handle resolved class pointer.
> AArch64: Handle resolved class pointer in loadRelocatableConstant()

- compiler/il/OMRBlock.cpp
In post GRA block splitter there are some issue which we found in tests.
This commits fixes following two issues.
1. While creating approprite symbol reference for to be uncommoned node to
store on temp slot or global register, it checks if that node is representing
internal pointer. In such case it needs get corresponding pinning array symref
if already exists and need to mark created symref with it. In case if corresponding
pinning array symref does not exist then it needs to find it and create new pinning
array pointer symref. Issue was, it was only checking variable load nodes for already
existing pinning array pointer symref while with splitting block after GRA, we can have
regLoad node which already contains it.
2. Second issue we found was altering the Basic Block semantics and …
> Fix Bugs in splitPostGRA

- gc/base/standard/ConcurrentScavengeTask.hpp
- gc/base/standard/Scavenger.cpp
Removed unused private field `_bytesToScan` from `ConcurrentScavengeTask` to resolve:
```
/ConcurrentScavengeTask.hpp:38:18: error: private field '_bytesToScan' is not used [-Werror,-Wunused-private-field]
uintptr_t const _bytesToScan;   /**< The number of bytes that this must scan before it will stop trying to do more work */
```
> Fix compile error with Concurrent Scavenger enabled on macOS

- compiler/p/codegen/GenerateInstructions.cpp
- compiler/p/codegen/GenerateOMRInstructions.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRInstruction.cpp
- compiler/p/codegen/OMRInstruction.hpp
- compiler/p/codegen/OMRInstructionKindEnum.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCDebug.cpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/ras/Debug.hpp
For performance reasons, it is beneficial to align labels that represent the start of a loop on a 32-byte boundary on Power. Previously, padding nops were added in the binary encoder loop based on the node associated with the label instruction. This is quite surprising behaviour, as IMO the binary encoder should never be looking at which node generated an instruction to make a decision.
This PR implements a more elegant solution in which the `BBStart` evaluator will emit a special "alignment nop" instruction which will be expanded at binary encoding time into the correct number of nops to ensure that the following instruction has the necessary alignment. This also opens up the possibility of enforcing alignment for loops that show up in ICF (usually because of recognized methods) rather …
> Rework how the Power codegen aligns loop labels

- compiler/z/codegen/OMRMachine.cpp
When we assign a new real register to a virtual register (for GPRs), we were not
updating the virtual register to hold its new real register. This led to a
discrepancy between the real->virtual and virtual->real mapping between registers. This
commit ensures that the virtual register now knows of its new real register.
Signed-off-by: Pushkar Bettadpur <pushkar.bettadpur@gmail.com>
> Fixes bug found in Real Register Assignment

- compiler/codegen/OMRCodeGenPhase.cpp
> Remove isAOT check in order to enable relo logging for JITServer

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/ras/Debug.hpp
This commit implements ARM64Trg1ImmSymInstruction, for generating
PC relative load register instructions.
> AArch64: Implement ARM64Trg1ImmSymInstruction

- compiler/x/amd64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
Adding X86's version of `getSupportsHardwareSQRT()` function and make it return `true` value. So that X86 will be able to reduce `StrictMath.sqrt()` and `Math.sqrt()` function to `dsqrt` in `recognizedCallTransformer`. 
Also, on X86, there is a function `inlineMathSQRT()` which previously handles the call to `StrictMath.sqrt()` and `Math.sqrt()`. X86 specially handled the constant case in `inlineMathSQRT()`. In `dsqrtEvaluator`, I didn't include the constant handling, because the constant case will be handled in `treeSimplification` (i.e. reducing `dsqrt` to `dconst`). Following is the trace log I generated from my own test case[1] using the jvm which includes the newly added `dsqrtEvaluator` and having `inlineMathSQRT` removed:
- Post Inlining Trees: for testsqrt.sq(D)D (Trees before …
> Adding `dsqrtEvaluator` on X86

- compiler/arm/codegen/ARMBinaryEncoding.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/z/codegen/S390Instruction.cpp
Each code generator duplicates logic to re-reserve a trampoline for a
call target if the code cache is switched between the time the trampoline
is first reserved (likely instruction selection) and binary encoding.
The logic is nearly the same in all cases.  Provide a common version
that is shared by all code generators.
> Share implementation to re-reserve trampolines on code cache switch

- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit fixes the wrong encoding of the immediate value for "adr"
and "adrp" instructions.
Those two instructions encode the lower 2 bits of the immediate value
in bits 29-30 of the instruction word, and the upper 19 bits of the
immediate value in bits 5-23 of the instruction word.
There was a mistake with masking and shifting the upper 19 bits.
> AArch64: Fix code generation for adr and adrp instructions

- port/unix/omrsignal.c
Currently, all supported asynchronous signals are unblocked during
startup. A signal is unblocked even when a signal handler is not
installed for it. This conflicts with an OMR consumer, who wants to
block a set of signals. The OMR consumer blocks a set of signals but the
OMR signal library unblocks those signals at startup. OMR signal library
should only unblock a signal if a signal handler is registered for it.
In other words, a signal should not be unblocked if it is not used i.e.
a signal handler is not registered for it. 
**Related:**
1. [Customer Issue (IntelliJ IDE doesn't receive signals; 28th Oct. 2018)](https://github.com/eclipse/openj9/issues/3468)
2. [OMR Fix (Handle signals blocked by a parent process; 23rd Nov. 2018)](https://github.com/eclipse/omr/pull/3225)
3. [Add support …
> Only unblock an asynchronous signal if it is used 

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/ParallelGlobalGC.cpp
Dark matter and paging compact triggers currently only compare potential
free memory gains vs current free memory (with aim to reduce Global GC
frequency). While trigger thresholds are set rather high, they can still
easily trigger with Tenure being fairly full.
To account for the cost of work by doing the compact, the gains are
not just compared with total free memory but with total heap size, too.
That alone would make the trigger way less probable to occur, so as a
compromise: the weight of total heap that account into the formula is
set to 50%, and thresholds are cut by a factor of 2 or so.
> Compact trigger adjustment

- cmake/config.cmake
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrPlatform.cmake
- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/xlc.cmake
Add new flag OMR_SEPARATE_DEBUG_INFO. If set, debug info for a target
is copied into <target_file>.dbg, and debug info from <target_file> is
stripped.
> CMake: Add ability to handle split debug info

- thread/common/threadhelpers.cpp
The implementation is added for the following functions:
1. omrthread_mcs_lock
2. omrthread_mcs_trylock
3. omrthread_mcs_unlock
4. omrthread_mcs_node_allocate
5. omrthread_mcs_node_free
A. [DONT MERGE] Enable the OMR_THR_MCS_LOCKS flag to verify compilation.
Will remove A) after it is verified that the code compiles properly through the pull request build jobs.
Related: #4086.
Dependent on #4508. Will require a rebase once #4508 is merged.
> MCS Lock (Part 3): Implement the MCS lock API

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
This PR overloads the `loadAddressConstant` API on Power. We add a new boolean which allows the consumer of this API to determine if relocatable code needs to be generated.
Once the commits are merged and have propagated into downstream projects, we will make the necessary API changes there and remove the old definition of the API since it will no longer be needed.
> Add isRelocatable boolean to power's loadAddressConstant API

- compiler/z/codegen/BinaryEvaluator.cpp
Codes guarded by `isUnsigned()` are dead codes since all the `unsigned imul` ILOpcodes have been removed in #4512. Only `TR::imul` still invokes `Z::imulEvaluator` on Z.  Therefore, remove unsigned support in the `Z::imulEvaluator`.
*Note: I have checked all the `evaluator`s, `simplifier`s and `constrain`s that are affected by #4512, there is no other similar problem (e.g. there is no other "dead unsigned support path" caused by that PR.)*
Issue: #2657
> Remove unsigned support in Z::imulEvaluator

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
- compiler/arm/codegen/ARMSystemLinkage.cpp
- compiler/arm/codegen/OMRLinkage.cpp
- compiler/arm/codegen/OMRLinkage.hpp
- compiler/codegen/OMRLinkage.hpp
- compiler/p/codegen/OMRLinkage.hpp
- compiler/x/amd64/codegen/AMD64SystemLinkage.hpp
- compiler/x/codegen/OMRLinkage.cpp
- compiler/x/codegen/OMRLinkage.hpp
- compiler/x/i386/codegen/IA32SystemLinkage.hpp
- compiler/z/codegen/OMRLinkage.hpp
- compiler/z/codegen/snippet/XPLINKCallDescriptorSnippet.cpp
- compiler/z/codegen/snippet/XPLINKCallDescriptorSnippet.hpp
Do not include unnecessary header files to prevent downstream breakages.
Introduce include directives and forward declarations as appropriate to
compensate for removing header files from the extensible OMRLinkage.hpp
> Break unneeded class dependencies on OMRLinkage

- cmake/modules/FindLibElf.cmake
Use data from pkg-config if available
> CMake: Update FindLibElf

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
Add findOrCreateShadowSymbol function and findOrFabricateShadowSymbol
to accept a TR_OpaqueClassBlock. These will be needed for supporting
value types. The behavior of these are project specific, so their
implementation in OMR is empty. Downstream projects should override
these as needed.
Co-authored-by: Yiling Han <Yiling.Han@ibm.com>
> Add findOr{Create,Fabricate}ShadowSymbol functions

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
This commit adds extraRegister and related code to
OMRMemoryReference for AArch64.
It will be used by UnresolvedSnippet.
> AArch64: Add extraRegister to OMRMemoryReference

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit corrects the AArch64 condiiton codes used for fcmp and dcmp
operations.
> AArch64: Correct the condition code for fcmp/dcmp

- include_core/omrport.h
- port/common/omrsock.c
- port/omrportpriv.h
Decided to match with old API until new socket API is done implementing.
-Made sure the function prototypes have the same arguments
Issue: #4102
> Fixes to match prototypes to old socket API

- omrtrace/omrtracemisc.cpp
- port/linux/omrosdump_helpers.c
- port/linux/omrvmem.c
- port/unix/omrintrospect.c
- port/unix/omrsysinfo.c
The test in the old code (formatCursor >= MAX_IMAGE_PATH_LENGTH - 1)
only ensured there was room for one more character (plus the
NUL-terminator) in any iteration of the loop and thus the expansion
of '%p', '%d' or '%t' might not fit.
strncpy() does not add a NUL-terminator if not part of the specified
segment of the source, so if the file name was more than 11 characters
long, buf might not be NUL-terminated and the following strcat()
may write beyond the end of the buffer.
strncpy() does not add a NUL-terminator if not part of the specified
segment of the source, so the result may not be NUL-terminated; use
OMR's str_printf() instead. Affected functions are deriveCoreFileName()
and renameDump().
Also fixed typo in corePatternFormat parameter name.
strncpy() does not add a NUL-terminator …
> Fix issues highlighted by warnings from gcc 9

- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/DebuggingCounters.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/OMRSimplifierHelpers.cpp
Delete any creations or recreations of node with unsigned deprecated IL opcodes in `Equality compare`/`Equality Compare and Branch`/`Constant` category.
Using `TR_ASSERT_FATAL` to ensure no downstream projects will attempt to use aforementioned opcodes.
Issue: #2657
> Stop generating deprecated unsigned opcodes of equality compare and const

- third_party/gtest-1.8.0/src/gtest-typed-test.cc
- third_party/gtest-1.8.0/src/gtest.cc
This is an error in gtest, not in OMR.
This same error is repeated in a few places, causing different types of
bad behaviour on AIX, including breaking almost all logging and option
processing.
Rather than bind a const mytype& to a temporary result, copy the result
into a local, which ensures it is safe to access the value later in the
program.
When a reference is bound to a temporary value, that reference is
invalid when the value dies, at the end of the "full expression" that
created it. Using this reference to a temporary in a later expression
results in a kind of "use after destruction" error.
Fixes: #4537
> gtest: Do not reference temporaries past the expression that created them

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
Relocate getMonClass and addMonClass to OpenJ9
The OMR::CodeGenerator functions- getMonClass and addMonClass are
relocated to OpenJ9 CodeGenerator and removed from OMR.
The changes also include the array- _monitorMapping moving from OMR
to OpenJ9.
Closes: #1869
> Relocate getMonClass and addMonClass to OpenJ9

- compiler/z/codegen/S390Instruction.hpp
The following are not used in OMR nor any known downstream project.
* `targetReg` parameter from constructors
* `_handle` field
* PreservedForListing flag
> Remove unused features from S390LabelInstruction

- compiler/z/codegen/OMRInstruction.cpp
- compiler/z/codegen/OMRRegisterDependency.cpp
- compiler/z/codegen/OMRRegisterDependency.hpp
* Remove unused isHint from Z register dependencies
* Remove unused conflictsResolved field from Z RegisterDependencyConditions
> Misc. Z RegisterDependency cleanup

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit adds a member computedCallTargetRegister to
ARM64LinkageProperties.
> AArch64: Add computedCallTargetRegister to ARM64LinkageProperties

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
> Add option disabling inline JSR292 without peeking

- compiler/aarch64/codegen/ARM64OutOfLineCodeSection.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit implements generateARM64OutOfLineCodeSectionDispatch()
in TR_ARM64OutOfLineCodeSection.
> AArch64: Implement generateARM64OutOfLineCodeSectionDispatch()

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit adds a call to TR_Debug::print() for
ARM64RecompilationSnippet.
> AArch64: Add call to TR_Debug::print(TR::ARM64RecompilationSnippet)

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Move arithmeticNeedsLiteralFromPool function from OMR to OpenJ9
This commit moves arithmeticNeedsLiteralFromPool function from OMR to
OpenJ9. arithmeticNeedsLiteralFromPool is not used in OMR, but it is
used in OpenJ9 for Z codegen implementation.
Fixes: #1870
Signed-off-by: Md. Ariful Haque <mhaque5@unb.ca>
> Move arithmeticNeedsLiteralFromPool function from OMR to OpenJ9

- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilertriltest/MinimalTest.cpp
This suite contains a really minimal tests such as "return 42"
or "return arg + 10". These tests are useful when porting compiler
to a new architecture, such as RISC-V.
> Add new 'MinimalTest' suite to compilertest.

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCOutOfLineCodeSection.cpp
This is to check in the OMR portion ...
It was caused by changes committed for OpenJ9 issue #4893. When JNILinkage is not
set on the method symbol anymore, OutOfLine performCall eventully evaluated it
through PrivateLinkage and stuck in interpreter. The fundamental reason is that
a new node is created for performCall but the isPreparedForJNI flag is not copied
over and performCall doesn't get the linkage right.
Resolve: #4132
> Fix JNI performance regression

- configure
- configure.ac
Autoconf has a rudimentary macro-prerequisite feature, which allows
macros and tests to automatically invoke dependencies.
Because of this system, AC_PROG_CC is being automatically invoked in the
middle of a check for the size of void*, which is much earlier than
where we manually invoke the macros. For clarity, I'm moving the calls
to AC_PROG_CC/CXX higher, to the beginning of the "build environment"
section of the script, and a few lines before the sizeof_void_p test.
Fixes: #4532 
> Move the calls to AC_PROG_CC/CXX higher

- ddr/include/ddr/config.hpp
- ddr/include/ddr/scanner/dwarf/AixSymbolTableParser.hpp
- ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
- ddr/include/ddr/scanner/dwarf/DwarfScanner.hpp
- ddr/include/ddr/scanner/pdb/PdbScanner.hpp
- ddr/include/ddr/std/unordered_map.hpp
- ddr/lib/ddr-blobgen/java/genBlobJava.cpp
- ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfFunctions.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
- ddr/tools/ddrgen/ddrgen.cpp
- gc/base/standard/CompactScheme.hpp
- include_core/omr.h
* add support for continued STABS entries
* add support for C++ ellipses parameter types
* consider types '__\d+' un-named on AIX
* define DW_FORM_block* constants
* extract function to get value of DW_AT_const_value attribute
* fix handling of pointer to member types
- skip past optional 'virtual' and 'multiple' base specifications
* fix handling of enum literal values
(they are expressed in decimal not hex in STABS entries)
* fix recognition of vtable pointers (xlclang defines __GNUC__)
* handle anonymous typedefs
* ignore static fields (xlc 13 doesn't produce STABS entries for them)
* don't return NULL for unknown builtin types
* fail if we can't decode a STABS string
* define macro ddr_constant(name, value)
- for handling anonymous nested types; expands to
static enum { name = value } …
> DDR: add support for xlc/xlclang version 16

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
This commit implements tableEvaluator() for AArch64.
Co-authored-by: KONNO Kazuhiro konno@jp.ibm.com
Co-authored-by: Aaron Graham aaron.graham@unb.ca
Co-authored-by: Md. Mahbubur Rahman mrahma15@unb.ca
> AArch64: Implement tableEvaluator

- ddr/include/ddr/config.hpp
- ddr/include/ddr/scanner/dwarf/AixSymbolTableParser.hpp
- ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
- ddr/include/ddr/scanner/dwarf/DwarfScanner.hpp
- ddr/include/ddr/scanner/pdb/PdbScanner.hpp
- ddr/include/ddr/std/unordered_map.hpp
- ddr/lib/ddr-blobgen/java/genBlobJava.cpp
- ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfFunctions.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
- ddr/tools/ddrgen/ddrgen.cpp
- gc/base/standard/CompactScheme.hpp
- include_core/omr.h
This causes problems for building openj9 on AIX (all versions) and on OSX.
I expect updating the AIX build machines with the new version of `dump` required for use with xlclang 16 with fix that platform, but I'd like to understand the OSX problem rather than doing anything hasty.
Reverts eclipse/omr#4620
> Revert "DDR: add support for xlc/xlclang version 16"

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
In this PR we make the changes needed to use front end queries instead of `cg->compileRelocatableCode()` when deciding whether to generate relocatable code inside `accessStaticItem`. This allows us to generate relocatable code for remote compilations in a consumer project such as OpenJ9, because the appropriate front-end query can return the right answer depending on the mode of compilation.
> Rework MemoryReference::accessStaticItem in Power for JITServer

- ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
- ddr/include/ddr/scanner/dwarf/DwarfScanner.hpp
- ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
This is to enable ddrgen to work on IBM i. I have refined the code per suggestion from @keithc-ca . Please help to review and merge it. I didn't break any existing routines. thanks.
FYI @keithc-ca
> Add support of J9OS_I5 for ddrgen

- buildenv/jenkins/jobs/builds/Build-linux_x86-64_cmprssptrs
- buildenv/jenkins/jobs/pull-requests/PullRequest-linux_x86-64_cmprssptrs
- run_configure.mk
- scripts/build-on-travis.sh
config.guess and config.sub are not generated files, they are checked in to our repository. With this PR, `make -f run_configure.mk distclean` will no longer remove these scripts. I've also removed the rules for downloading new versions, and stopped calling distclean at the beginning of our builds.
> Stop re-downloading config.guess and config.sub

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit rewrites the instruction "ldrimmw" (12-bit unsigned offset)
to "ldurw" (9-bit signed offset) when a negative value is used as the
offset.
> AArch64: Allow negative immediate offset for memory access

- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
- This commits adds implementation of `OMR::ARM64::RegisterDependencyConditions::clone`.
- It adds optional arguments to `clone` that enables cloning only pre/post part
of original dependency conditions.
- It adds utility methods `clonePre` and `clonePost` which call `clone`.
> AArch64: Implement OMR::ARM64::RegisterDependencyConditions::clone

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit makes `logicImmediateHelper` available to the code
outside BinaryEvaluator.cpp.
> AArch64: Make logicImmediateHelper available outside BinaryEvaluator.cpp

- ddr/tools/blob_reader/CMakeLists.txt
- ddr/tools/ddrgen/CMakeLists.txt
Its not gauranteed that consumers of omr will export the symbols we need
from their versions of the port and thread libraries
> CMake: Link ddr tooling against omr thread/port libraries

- cmake/modules/ddr/cmake_ddr.awk
awk on osx does not behave properly when the result of split() overwrites
the input.
> CMake: Fix ddr on osx

- fvtest/porttest/si.cpp
- include_core/omrport.h
- port/CMakeLists.txt
- port/common/omrport.c
- port/common/omrport.tdf
- port/common/omrsysinfo.c
- port/common/omrsysinfo_helpers.c
- port/common/omrsysinfo_helpers.h
- port/linuxs390/omrsysinfo_helpers.h
- port/omrportpriv.h
- port/port_objects.mk
- port/unix/omrsysinfo.c
- port/unix_include/omrportpg.h
- port/win32/omrsysinfo.c
- port/zos390/omrportpg.h
OpenJ9 port library has processor and feature detections that can be sunk down to OMR. This can be divided into 4 steps:
1: Creation of processor and feature detection in OMR (from OpenJ9).
2: Implementation of the new feature throughout out OMR.
3: Implementation of the new feature throughout OpenJ9.
4: Deletion of the processor detection in OpenJ9 port library.
This PR serves to implement step 1 of the list above. This PR includes the following:
- Move and rename necessary port library macros from OpenJ9 to OMR's `omrport.h` (Commit 1)
- Move and implement processor/feature detection for windows systems[WIP] (Commit 2)
- Move and implement processor/feature detection for unix systems (x86, Power, AIX, Z) (Commit 3)
- Move and test the respective port tests that helps verify that …
> Migrate processor/feature detection from OpenJ9 to OMR Part 1

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
The queries modified in this PR are used to replace the
generic compileRelocatableCode() query so that it is easier
for downstream projects to override them on a case-by-case
basis. Since the queries are replacing the original
compileRelocatableCode() call, they should be returning the
same result as before in OMR. This commit fixes that issue.
> Redefine CG queries to return correct answer

- include_core/thread_api.h
- thread/common/omrthreadinspect.c
This define is never set, and the code guarded by it no longer compiles.
> Remove uses of J9VM_OUT_OF_PROCESS

- cmake/modules/FindDiaSDK.cmake
- Honor the 'DiaSDK_ROOT' variable
- Use 64bit libraries when on a 64bit platform
> CMake: Update FindDiaSDK

- thread/exports.cmake
- thread/thread_include.mk
For some reason omrthread_attr_set_detachstate was not exported,
while other similar functions are.
omrthread_attr_set_detachstate is now needed by OpenJ9 project as part
of this PR: https://github.com/eclipse/openj9/pull/7940.
Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>
> Export omrthread_attr_set_detachstate

- cmake/modules/ddr/DDRSetStub.cmake.in
> CMake: Enable OMR_EXE_LAUNCHER support when launching ddrgen

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LocalOpts.hpp
- compiler/optimizer/PreExistence.hpp
Invariant argument preexistence (IAP) stores argument type info in parm symbols. The problem with this is that most type information is site specific.
This PR will fix this issue by stop putting site specific information on parm symbols. The improved type information will be put on prex arg info which will be used by inliner.
> Fix argument info propagation in inlining

- ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
- ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfFunctions.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
The current dwarf parser for OSX does not actually prune duplicate file names,
which leads to wasted time parsing the file name list later on. Switching the
container for the file names from list to map would allow us to remove the
duplicate file names from the list and thus improve the performance of ddrgen.
On AIX, we keep a separate set for this purpose and this change would also do
away with that. We need a map instead of a set so that dwarf_srcfiles returns
the file list in the correct order indicated by the DW_AT_decl_file attribute.
Fixes https://github.com/eclipse/omr/issues/4498
On my personal machine it takes around 2 minutes on OpenJ9 source after the change, compared to around 6 minutes beforehand.
From the profiler, it looks …
> Change Dwarf_CU_Context files list from vector to map

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds `generateBinaryEncodingPrePrologue` in `OMR::ARM64::CodeGenerator`, which is used
to generate meta data and pre-prologue before method body.
> AArch64: Add generateBinaryEncodingPrePrologue in OMRCodeGenerator

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/il/Aliases.cpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/ras/Debug.cpp
The OpenJ9 Escape Analysis optimization currently overloads the meaning of the OSR
helper callees as part of its analysis. This change introduces a new non-helper
symbol for this optimization pass to use to avoid overloaded meanings and the
resultant confusion in the codebase.
This helper is added to OMR because its aliasing etc must match that of the various other
helpers used for the same purpose and any other language implementing an escape
analysis-like optimization would benefit from the presence of this non-helper.
> Add eaEscapeHelperSymbol

- compiler/aarch64/CMakeLists.txt
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ConstantDataSnippet.cpp
- compiler/aarch64/codegen/ConstantDataSnippet.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRSnippet.hpp
- jitbuilder/build/files/target/aarch64.mk
This commit adds Constant Data Snippet for aarch64.
The code generator is changed to have a list of constant data snippets
as x/z code generator does.
The snippet adds minimal meta data to the address as ppc version does.
The data at the snippet can be loaded by `ldr` literal instruction, which does pc relative load.
> AArch64: Add Constant Data Snippet

- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LocalOpts.hpp
For interface and abstract classes, even though they haven't been
extended, we can't treat them as currently final as they will be
extended later.
Also check that `refinedMethod` is not `NULL` before continue.
> Interface and abstract class can not be final

- gc/base/Configuration.cpp
- gc/base/modronopt.h
- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/Scavenger.cpp
- include_core/omr.h
- include_core/omrcomp.h
Remove always-defined flags and use OMR_ flags instead of J9VM_ ones.
> Remove definitions and uses of J9VM_ flags

- compiler/ilgen/OMRTypeDictionary.cpp
- compiler/ilgen/OMRTypeDictionary.hpp
- fvtest/tril/test/IlGenTest.cpp
- fvtest/tril/tril/CMakeLists.txt
- fvtest/tril/tril/CallConverter.cpp
- fvtest/tril/tril/CallConverter.hpp
- fvtest/tril/tril/GenericNodeConverter.cpp
- fvtest/tril/tril/GenericNodeConverter.hpp
- fvtest/tril/tril/converter.hpp
- fvtest/tril/tril/ilgen.cpp
- fvtest/tril/tril/ilgen.hpp
- fvtest/tril/tril/simple_compiler.cpp
- fvtest/tril/tril/state.hpp
Refactored Tril ilgen `ToTRNode` to use `ASTToTRNode` class, and changes are made to the followings:
- Defined private copy constructor for `TypeDictionary` class
- Added `ASTToTRNode`, its subclasses and each exception classes to make it be extensible
- Added `IlGenState` class to store the maps get from `TRLangBuilder`, and values in `IlInjector`
> Added ASTToTRNode class to refactor Tril ilgen

- compiler/p/codegen/OMRInstOpCodeProperties.hpp
Previously, the prototypes for the vmax* family of instructions were
incorrect. Sepcifically, trying to generate a vmaxs* instruction would
actually generate a vmaxu* instruction and vice-versa. This could cause
unpredictable and difficult to diagnose issues if these instructions
were used.
> Fix incorrect binary encoding for vmax* instructions

- compiler/z/codegen/S390Instruction.cpp
- compiler/z/codegen/S390Instruction.hpp
This API is not used anywhere and its current implementation looks
incomplete. We remove it here to prevent people using it.
> Deprecate assignRegistersNoDependencies as it is no longer used

- compiler/aarch64/codegen/GenerateInstructions.cpp
This commit adds a TR_ASSERT() for the range of the immediate value
in generateCompareImmInstruction().
> AArch64: Add TR_ASSERT() to generateCompareImmInstruction()

- compiler/p/codegen/OMRInstOpCodeProperties.hpp
Previously, the prototypes for the tabortwc extended mnemonics were
incorrect and were instead generating tabortdc instructions. This could
cause undefined behaviour, since the upper word of a register containing
a 32-bit value is generally considered undefined. This has now been
fixed and these instructions should generate the correct binary
encodings.
> Fix incorrect binary encoding for tabortwc

- compiler/codegen/ELFGenerator.cpp
- compiler/codegen/ELFGenerator.hpp
As suggested by @0xdaryl, I've added a Data Section Header, as well as an empty Data section to relocatable ELF files. Below I will include instruction on where and how to add actual data to the ELF relocatable object file.
1: Modify https://github.com/eclipse/omr/pull/4635/files#diff-e69de10eeec42fdf52a50ed4a60b4008R331 to point to the data you wish to write
2: Add the size of the data segment you wish you write to this equation: https://github.com/eclipse/omr/pull/4635/files#diff-e69de10eeec42fdf52a50ed4a60b4008R546
3: Do the same here: https://github.com/eclipse/omr/pull/4635/files#diff-e69de10eeec42fdf52a50ed4a60b4008R565
4: Add pointer to Data segment here: https://github.com/eclipse/omr/pull/4635/files#diff-e69de10eeec42fdf52a50ed4a60b4008R584
5: Replace the zero value with the size …
> Add Data Section and Header to Relocatable ELF Object

- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, the enumeration value names for the VMX record-form compare
instructions did not follow the general rule of adding '_r' to the name
of their non-record-form instructions. This was needlessly confusing and
inconsistent. These instructions have now had their names updated to
follow the usual style. Note that aliases have been left for the old
names, since OpenJ9 is referencing some of these instructions directly.
Additionally, the instruction properties table has been updated to
derive the properties of the VMX record-form compare instructions from
those of their non-record-form counterparts.
> Rename VMX record form compare instructions

- compiler/compile/OMRCompilation.cpp
- compiler/il/OMRResolvedMethodSymbol.cpp
- compiler/il/OMRResolvedMethodSymbol.hpp
Both `detectInternalCycles` and `catchBlocksHaveRealPredecessors` are
intended to detect patterns in the CFG of the receiver method symbol.
When calling from `OMR::ResolvedMethodSymbol::genIL` the CFG of the
compiling method is passed in rather than the method whose IL is
generated which is incorrect.
Remove the CFG parm which can be obtained from self()->getFlowGraph() to
avoid incorrect use of the API.
> Remove redundant parm to avoid incorrect usage

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit changes aconstEvaluator to add AOT relocation
to address constant.
Depends on https://github.com/eclipse/omr/pull/4588
> AArch64: Add AOT relocation to address constant

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
Correctly decode immediate value for logical operator
in ARM64Debug.cpp.
> AArch64: Correctly decode logic immediate in ARM64Debug

- port/unix/omrsysinfo.c
Since buffer[] is stack allocated, it can never be NULL.
Fixes #4698
> Remove redundant NULL check code to fix xlc 16 compile error

- compiler/compile/OMRCompilation.cpp
- compiler/env/Region.hpp
- compiler/il/NodePool.cpp
- compiler/infra/OMRCfg.cpp
- compiler/optimizer/RegisterCandidate.hpp
Add a helper function that correctly releases memory managed by TR::Region.
Implemented the helper functions throughout all instances listed on #4649.
Fixes #4649
> Add TR::Region::reset helper function

- compiler/optimizer/CopyPropagation.cpp
Replace a load of an auto sym ref A by a loadaddr
of an auto sym ref B if there was a store of A :
store A = loadaddr B
feeding the load of sym ref A.
Signed-off-by: Vijay Sundaresan <vijaysun@ca.ibm.com>
> Added support for loadaddr in copy propagation

- gc/base/MemoryManager.hpp
Change control access of isLargePage in MemoryManager to public
This update is required by eclipse/openj9#8254
Related to issue: #4703
> Change control access of isLargePage in MemoryManager to public

- compiler/optimizer/CopyPropagation.cpp
Recent changes in PR4699 to add support to copy propagation for
loadaddr nodes are responsible for acceptance build failures at
OpenJ9 with a variety of crashes. This change backs out the
changes in PR4699 until the cause of the problem is identified.
This reverts commit d27fc6166b643f07d8fc83d4c5cf5c7976bbb4ba.
> Revert PR4699 "Added support for loadaddr in copy propagation."

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit enables <s>`ARMTrg1ImmInstruction`</s> `ARMTrg1ImmSymInstruction` to handle StartPC constant,
and change `loadRelocatableConstant` to use it.
> AArch64: Load StartPC constant with pc-relative load instruction

- compiler/il/OMRSymbolReference.hpp
Remove any references to deprecated class ` TR_NodeAliasSetInterface`.
Closes: #4706 
> Remove references to deprecated class TR_NodeAliasSetInterface

- compiler/optimizer/VPConstraint.cpp
This workaround was for a very old version of xlC compiler (10 years
old) which we no longer build with. Code archeology reveals the
original bug was a compile time crash with the following backtrace:
```
Method_being_compiled=sun/io/Converters.cache(ILjava/lang/Object;)Ljava/lang/Class;
TR_J9VM::getBaseComponentClass(TR_OpaqueClassBlock*,int&)
TR_J9VMBase::getClassSignature(TR_OpaqueClassBlock*,int&,TR_Memory*)
TR_VPResolvedClass::create(TR_ValuePropagation*,TR_OpaqueClassBlock*)
constrainCheckcast(TR_ValuePropagation*,TR_Node*)
TR_ValuePropagation::processTrees(TR_TreeTop*,TR_TreeTop*)
TR_GlobalValuePropagation::processBlock(TR_StructureSubGraphNode*,bool,bool)
TR_GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*,bool,bool) …
```
> Remove xlC V1R11 workaround in optimizer

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/S390Peephole.cpp
Similarly to all other processors, since the migration of CPU checks to
the CPU class we no longer need to explicitly check for specific
"disableZ13*" options when also checking for processor support since
these checks are already performed for us.
We simplify the implementation here to stay consistent with all the
other checks for the various CPU processors.
> Remove redundant z13 processor checks on Z

- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/gnu_exports.exp.in
> CMake: Add exported symbol support for gcc

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Adding an -Xjit option TR_DisableImmutableFieldAliasing to disable the aliasing logic for fields considered immutable by a language runtime. 
> Add -Xjit option TR_DisableImmutableFieldAliasing

- compiler/il/OMRResolvedMethodSymbol.cpp
This commit sets `prepareForOSR` helper to system linkage for aarch64.
> AArch64: Set prepareForOSR helper to system linkage

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds `generateNop` function to `OMR::ARM64::CodeGenerator`.
> AArch64: Add generateNop to code generator

- compiler/p/codegen/OMRMemoryReference.cpp
Previously, there was an issue when encoding a TR::MemoryReference on
Power that used delayed indexed form but without an index register set.
The comment in the code implied that the correct thing to do here was to
use addi to add the displacement to the base register. However, instead
we were trying to fill one of the fields of the instruction with the
index register, which was NULL. This code has now been corrected to
encode the correct instruction.
> Fix null pointer deref when encoding a MemoryReference

- compiler/control/OMROptions.cpp
This commit enables OSR for aarch64.
Depends on https://github.com/eclipse/openj9/pull/8305 and https://github.com/eclipse/omr/pull/4723
> AArch64: Enable OSR

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
Previously, the Power codegen had the ability to generate ba and bla
instructions. These instructions were able to branch to any absolute
sign-extended 24-bit address. However, the binary encoding logic never
supported these instructions and they would be exceedingly difficult to
use, as ensuring an address falls within the range a ba/bla instruction
could branch to would be difficult. As a result of this, these
instructions have been removed.
> Remove the unused Power ba and bla instructions

- compiler/compile/ResolvedMethod.cpp
- compiler/compile/ResolvedMethod.hpp
With `JITServer`, the dynamic constant object uintptrj_t
needs to be dereferenced at the client instead of the server.
It’s taken care of by `TR_ResolvedJ9JITServerMethod::dynamicConstant()`.
To prevent the caller from dereferencing the pointer directly at the server, adding a new `dynamicConstant` API to deference it.
The server will send one message to retrieve both the pointer
and the object values in `TR_ResolvedJ9JITServerMethod::dynamicConstant()`.
Since the caller could be run at the client or the server,
the new API should always be used when dereferencing the pointer.
The old API `dynamicConstant(int32_t cpIndex)` will be deprecated next.
> Add a new dynamic constant API to dereference the pointer

- compiler/compile/CompilationException.hpp
Very often when failing ilgen is because of limitation of the compiler
we would want the caller's compilation to continue but don't want to
recompile the failing method itself because it would fail again due to
the limitation. Added NoRecompilationRecoverableILGenException for such case.
> Add NoRecompilationRecoverableILGenException

- compiler/optimizer/CopyPropagation.cpp
This reverts commit e1519a01cd43304b4e15e8cdcf10f17af2a0445a.
Intermittent failures are found in Openj9 build, those failures need more time to investigate, thus reverting the change.
#4740 is created to document this problem.
> Revert "Added support for loadaddr in copy propagation"

- include_core/omrport.h
- port/unix/omrsysinfo.c
> Add Unix rlimit support for RLIMIT_DATA

- gc/base/Collector.hpp
- gc/base/Heap.cpp
- gc/base/Heap.hpp
- gc/base/MemorySpace.cpp
- gc/base/MemorySpace.hpp
- gc/base/MemorySubSpace.cpp
- gc/base/MemorySubSpace.hpp
- gc/base/PhysicalSubArenaVirtualMemoryFlat.cpp
- gc/base/segregated/MemorySubSpaceSegregated.cpp
- gc/base/segregated/MemorySubSpaceSegregated.hpp
- gc/base/segregated/SegregatedGC.cpp
- gc/base/segregated/SegregatedGC.hpp
- gc/base/standard/ConcurrentCardTable.cpp
- gc/base/standard/ConcurrentCardTable.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/ParallelGlobalGC.hpp
- gc/base/standard/PhysicalSubArenaVirtualMemorySemiSpace.cpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- gc/startup/omrgcstartup.cpp
- include_core/omrgcconsts.h
Fixes https://github.com/eclipse/openj9/issues/8020
- MarkMap init consolidated
MarkMap init logic has been merged to resolve the timing hole outlined in https://github.com/eclipse/openj9/issues/8020#issuecomment-573843125. MarkMap init is dependent on Concurrent State of the global collector, with the init logic split between `heapAddRange` and `heapReconfigured`, any changes in states between the two may leave expanded mark map uninited. Hence, the decision to init (`setMarkBitsInRange`) the mark map has been moved from `heapAddRange` to `heapReconfigured` which is where we determine if an update to the init table is required (`tuneToHeap`/`determineInitWork`). As a result, init is no longer affected by the change in Concurrent state and we eliminate the timing window. This guarantees …
> Heap Resize: Concurrent KO/Uninitialized Mark Map Bug fix

- include_core/ute_dataformat.h
- omrtrace/omrtracelog.cpp
- thread/common/thrprof.c
- util/omrutil/gettimebase.c
The changes mainly include miscellaneous code
to enable RISC-V 64bit from the OMR perspective.
Issue: eclipse#4426
> Change misc code for RISC-V in OMR (part5/misc)

- compiler/compile/OMRCompilation.cpp
- compiler/il/OMRMethodSymbol.hpp
- compiler/il/OMRNode.cpp
This commit contains mainly following two changes.
1. Create a list of methods calls to which does not yield to OSR and use this information in the query to know if a call node can catch OSR.
2. Method calls which does not have any side-effects are marked as pure function. Calls to those method does not throw an exception. Use this information in query to know if a call can raise exceptions.
> Consider callee type in exceptionRaised query

- gc/base/GCExtensionsBase.hpp
Reverts eclipse/omr#4735
This PR is causing intermittent failures in openj9, that will take some time to fix. Reverting this PR will make the double-mapping feature disabled by default.
> Revert "Make double map true as default option "

- cmake/modules/platform/arch/s390.cmake
- cmake/modules/platform/os/linux.cmake
In the autoconf world _LONG_LONG is only defined by the compiler component.
Update cmake config to reflect that.
> CMake: Refactor _LONG_LONG definition

- cmake/modules/OmrPlatform.cmake
Only add build steps to split the debug info from a target on the first
call to omr_split_debug(). Subsequent calls silently return
> CMake: avoid splitting debug symbols multiple times

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds code to support compressed references
to `istoreEvaluator` in aarch64.
It calls `setStoreAlreadyEvaluated` when using compressed refs
and the store is indirect.
> AArch64: Add code for compressed refs - istoreEvaluator

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit adds `astoreEvaluator` to support compressed references
for aarch64.
> AArch64: Add code for compressed refs - astoreEvaluator

- compiler/z/codegen/SystemLinkageLinux.cpp
- compiler/z/codegen/SystemLinkagezOS.cpp
The `setProperties` API overrides all previously set properties, while
the `setProperty` API appends a property to the existing list. We want
the latter, not the former semantics.
> Use setProperty instead of setProperties in Z system linkages

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit adds code for compressed refs for AArch64:
l2aEvaluator(), aloadEvaluator()
> AArch64: Add code for compressed refs - l2aEvaluator, aloadEvaluator

- gc/base/Collector.hpp
- gc/base/PhysicalSubArenaVirtualMemoryFlat.cpp
Follow-up changes to https://github.com/eclipse/omr/pull/4716 to remove code which was required temporarily to not break OpenJ9 heapReconfigured API dependency 
> heapReconfigure API Rework Follow-Up

- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
Add associated flag, set and get function for `VectorFacilityEnhancement1` feature for z platform. This feature is required for recognizing `Math.fma` method on Z platform.
Issue: eclipse/openj9#7474
> Add VectorFacilityEnhancement1 feature on Z::CPU

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit adds code to support compressed references to
`OMR::ARM64::MemoryReference::populateMemoryRefernce`.
> AArch64: Add code for compressed refs to memory reference

- compiler/x/amd64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/x/codegen/X86Ops.hpp
- compiler/x/i386/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/JitTest.hpp
Implementation for bmul and smul evaluators and change TRIL to reenable the corresponding tests.
Closes: #4408
> Add byte and short multiplier on x86

- gc/base/Configuration.cpp
- gc/base/GCExtensionsBase.hpp
- gc/verbose/VerboseHandlerOutput.cpp
Simplify the heuristic for Marking and Scavenge Scan Queue splitting
defaults.
The rule is simple: one queue per 8 GC threads, which is less than what
we now  use, especially for low number of threads.
This rule has already been used for allocation lock splitting with
success, for a long time.
Some more additional stress testing with Scavenger with 4x smaller
workunit (32K cache size) has been performed and no regression (lock
contention causing longer GC times) was seen.
Potential benefit of this simplification is that the cost of checking if
the global cache/packet pool is full/empty will be much lower, what will
be important for Concurrent Scavenge that will used this info as an scan
loop exit criteria.
> Scan Queue splitting defaults

- buildenv/jenkins/jobs/builds/Build-aix_ppc-64
- buildenv/jenkins/jobs/pull-requests/PullRequest-aix_ppc-64
xlc_r is the reentrant version of xlc. Invoking the compiler changes
many default configuration, to produce thread-safe code. As well,
pthreads will be linked by default to each executable.
> Compile with xlc_r on AIX

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/runtime/OMRCodeCache.cpp
- compiler/runtime/OMRCodeCacheManager.cpp
- compiler/runtime/OMRCodeCacheManager.hpp
To support `-XX:+PrintCodeCache`(eclipse/openj9#8184), the high water
mark of the code cache usage needs to be tracked.
The usage is tracked when increasing/decreasing the code cache repository
take place and also the reuse of the free blocks in the code cache.
The code cache usage reported in the javacore dump file will
reflect this change because `increase/decreaseFreeSpaceInCodeCacheRepository`
will also be called when the free blocks are reused/freed.
Added `TR_PrintCodeCacheUsage` to `TR_CompilationOptions`. It's set
when `-XX:+PrintCodeCache` is passed to the JVM or when it's set
as an environment variable.
Also added information on the config size, the total free size,
and the used size for each code cache in `printOccupancyStats()`
which is used by OpenJ9 to show the code cache …
> Track the total usage of the code cache

- compiler/p/codegen/OMRCodeGenerator.cpp
Previously, the addConstantToLong function used on 32-bit performed two
separate checks to see if an addic instruction could be used to perform
the lower part of the addition with duplicate code. The duplicate
branches of this if statement have now been merged together with one
check for the range of lowValue.
This has been done because the previous code was optimized incorrectly
by XLC 13.1 on ppc32 Linux under certain conditions and the range check
would not work correctly, resulting in an invalid addic instruction
being generated.
> Remove duplicate if branches from addConstantToLong

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
Moving supportVMInternalNatives from OMR to Openj9
Moved CodeGenerator::supportVMInternalNatives() from
OMRCodeGenerator to J9CodeGenerator with no other changes
Resolves: #1865
> Moving supportVMInternalNatives from OMR to Openj9

- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/ras/Debug.cpp
This flag expresses that the identity of the resulting object of a node
is unobservable. Eventually, this flag will enable transformations that
take advantage of the lack of identity.
> Add Identityless node flag

- compiler/p/codegen/OMRInstOpCodeEnum.hpp
As part of a previous pull request, the VMX record-form instructions
were renamed to be more consistent with other record-form instructions.
However, aliases had to be left for the old names since OpenJ9 still had
code which used the old names. Recently these references were finally
removed, so it should now be safe to remove the old aliases.
> Remove old aliases for record-form VMX instructions

- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- fvtest/compilerunittest/CMakeLists.txt
- fvtest/compilerunittest/CodeGenTest.hpp
- fvtest/compilerunittest/main.cpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
Previously, there was no direct testing of the Power codegen's binary
encoder. While portions of it would be exercised by the Tril tests and
through the test suites of downstream projects such as OpenJ9, there was
a significant amount of functionality that was not tested since it is
either currently unused or only used in very exotic situations that are
unlikely to be exercised by the existing test suite.
In order to better confirm that the Power binary encoder is working as
expected, a new set of unit tests are being added that should exercise
as much of its functionality as possible. The iteration of these tests
being contributed include comprehensive tests for most non-memory
opcodes currently in use by the Power codegen in either OMR or OpenJ9.
Note that a number of these tests are …
> Add unit tests for the Power binary encoder

- cmake/modules/platform/toolcfg/xlc.cmake
Debug info should be stripped from the target file, not the debug file
> CMake: Fix bug in stripping debug info on xlc

- buildenv/jenkins/jobs/builds/Build-linux_riscv64
- buildenv/jenkins/jobs/builds/Build-linux_riscv64_cross
- buildenv/jenkins/jobs/pull-requests/PullRequest-linux_riscv64
- buildenv/jenkins/jobs/pull-requests/PullRequest-linux_riscv64_cross
This PR adds a basic pipelines for RISC-V. These pipelines are compile-only, i.e., they do not
run any tests. Testing will be added in subsequent PRs - compiler tests that are known to fail 
should be (somehow) skipped. 
"Build" pipelines were (are) tested, "PullRequeste" pipelines are not tested since I have 
limited way of testing them.
> RISC-V: add CI pipelines for RISC-V

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
Fix `commonFPUnaryEvaluator` to correctly allocate a register
when the child node is not clobberable.
> AArch64: Fix logic allocating fp register when child node register is not clobberable

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit fixes a case in populateMemoryReference() where no base
register has been allocated with aconst/iconst/lconst.
Closes: eclipse/openj9#8475
> AArch64: Fix for populateMemoryReference() with no base register

- compiler/il/OMRResolvedMethodSymbol.cpp
Control flow analaysis can not handle CFG with `catch blocks have
real predecessors` so we should avoid inline or compile such method.
Use `NoRecompilationRecoverableILGenException` for this purpose.
> Change ilgen exception to correct exception type

- CMakeLists.txt
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrDetectSystemInformation.cmake
DDR works on windows, however it does not work on multi-config generators.
> CMake: Remove guards for windows around ddr code

- compiler/il/OMRIL.cpp
- compiler/optimizer/DebuggingCounters.cpp
Stop generating deprecated unsigned opcodes of `load` and `store` from OMR.
Will use `TR_ASSERT_FATAL` to ensure no downstream projects will attempt to use aforementioned opcodes in #4363.
Issue: #2657
> Stop generating deprecated unsigned opcodes of load and store from OMR

- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/DebuggingCounters.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
Stop generating deprecated unsigned opcodes of `Call/Return` and `Add/Sub` from OMR.
Using `TR_ASSERT_FATAL` to ensure no downstream projects will attempt to use aforementioned opcodes. 
Note that this PR needs support from #4310 and eclipse/openj9#7004
Issue: #2657
> Stop generating deprecated unsigned opcodes of Call/Return and Add/Sub from OMR

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/il/OMRNode_inlines.hpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LoopReducer.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/OMRSimplifierHelpers.cpp
- compiler/optimizer/VPHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/UnaryEvaluator.cpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/UnaryEvaluator.cpp
Remove all references to the IL Opcodes in the `const` category listed in #2657, namely,  `buconst`, `iuconst`, `luconst`, `cconst`. 
Also removed `TR::Node::cconst` 
*Anything in `SwitchAnalyzer.cpp` as they will be removed explicitly in #3983*
Issue: #2657 
> Remove references of deprecated const IL Opcode

- compiler/p/codegen/OMRInstOpCode.hpp
- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
The Power codegen previously had an unused pseudoinstruction called
depend that was meant to simply hang dependencies off of. However, this
instruction is unused and the assocreg instruction provides the same
functionality. To simplify things, the redundant depend instruction has
been removed.
> Remove the unused depend Power pseudoinstruction

- compiler/il/OMRNode.hpp
Use `TR_ASSERT_FATAL` to ensure no downstream projects will attempt to use aforementioned opcodes.
Issue: #2657
> Fatal asserts any creation of deprecated unsigned load/store opcodes

- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRLinkage.hpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/BitPermuteTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TernaryTest.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
- fvtest/jitbuildertest/SystemLinkageTest.cpp
This PR fixes some long-standing issues in the Power system linkage that have resulted in #3525 and #4765. For little endian, this fixes incorrect stack argument offsets for arguments passed via the stack rather than in registers. For big endian, this fixes incorrect alignment of non-long arguments in their respective stack slots. With these issues corrected, all tests that were disabled on Power due to these bugs have now been re-enabled.
> Fix issues with the Power system linkage

- fvtest/porttest/CMakeLists.txt
- fvtest/porttest/makefile
- fvtest/porttest/omrsockTest.cpp
- include_core/omrport.h
- include_core/omrporterror.h
- include_core/omrportsock.h
- include_core/omrportsocktypes.h
- port/CMakeLists.txt
- port/common/omrport.c
- port/common/omrsock.c
- port/common/omrsockptb.c
- port/common/omrsockptb.h
- port/omrportpriv.h
- port/port_objects.mk
- port/unix/omrsock.c
- port/win32/omrsock.c
Created 4 commits for this PR:
-  `Added Omrsock Related Per Thread Buffer functions` contains changes related to the per thread buffer and its functionalities.
- `Added startup and shutdown functions to omrsock API` contains changes related to OMR socket API startup and shutdown, which utilizes the ptb functions in the previous commit to startup and shutdown the per thread buffer.
- `Added Unix implementation for omrsock_getaddrinfo_create_hints` contains implementation of the OMR socket API function, that uses the ptb function to store information. It also contains a few new error codes related to OMR socket API.
- `Added Implementations to omrsockTest.cpp to test omrsock PTB` contains tests that are still being work on for the per thread buffer.
> Added a per thread buffer and related tests for OMR socket API

- compiler/compile/ResolvedMethod.cpp
- compiler/compile/ResolvedMethod.hpp
PR #4726 adds a new `dynamicConstant()` API
`dynamicConstant(int32_t cpIndex, uintptrj_t *obj)`.
The new API dereferences the dynamic constant object pointer
into the passed in parameter `obj`. The reason is that
in the JITServer mode, the server will need to send a message
to the client to retrieve both the pointer and the object value
in TR_ResolvedJ9JITServerMethod::dynamicConstant().
Since the caller of dynamicConstant () could be run at the
client or the server, the new API should always be used
when the dynamic constant object pointer needs to be dereferenced.
It'd be a better practice to deprecate
dynamicConstant(int32_t cpIndex) to reduce the chances
of the caller from dereferencing the pointer directly at the server.
Closes #4731
Signed-off-by: Annabelle Huo …
> Remove dynamicConstant(int32_t cpIndex)

- compiler/optimizer/OMRSimplifierHelpers.cpp
This change adds a check in the simplifier helper logic to see if
a child, which has been simplified, has become a PassThrough. If
the root node does not answer true to isNullChk() then attach the
child of the PassThrough to minimize the number of PassThrough
nodes and maximize opportunities for optimization.
> Enhance Simplifier to minimize child PassThroughs

- compiler/compile/VirtualGuard.cpp
- compiler/compile/VirtualGuard.hpp
- compiler/optimizer/VPHandlers.cpp
This PR fix a problem where VP converts a profiled guard with VFT test to a hierarchy guard with method test. A method test is not sufficient as the optimizer may assume the receiver has a fixed type based on the guard and transform the code based on this assumption. One example is devirtualization.
This PR also create `ResolvedClass` constraint on a VFT load if the object class is resolved.
> Use VFT test in hierarchy guard converted from profiled guard with VFT test

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCInstruction.hpp
On Power, the maximum distance of a conditional branch is less than the
maximum distance of an unconditional branch. As a result of this, it is
possible for the target of a conditional branch instruction to be
out of range. In this case, it is necessary to transform that
conditional branch into a flipped conditional branch around an
unconditional branch.
The previous implementation of this had several notable issues. The
expansion of conditional branches was previously delayed until
generateBinaryEncoding was called on the conditional branch in question,
resulting in that function being much more complex than it needs to be.
Additionally, the previous implementation was trying to be clever and
avoid including the extra 4 bytes of estimated length for conditional
branches in some cases, …
> Change how far conditional branch expansion works on Power

- gc/structs/ForwardedHeader.cpp
- gc/structs/ForwardedHeader.hpp
When retrying to win a chunk to copy, to be sure we properly re-read the
the fields of the control word, the address of control word must be of
type pointer to volatile word.
Without it we may (for example) end up missing just incremented
outstandingCopies count and eventually hit negative value on way down
when decrementing.
The missing volatile is regression from relatively recent re-org for
CR/nonCR runtime feature: #4627
Original code indeed used to read the control word through
volatile MutableHeaderFields::slot *
Fixes: eclipse/openj9#8478
> Fix missing volatile in CS large object copy

- compiler/infra/OMRCfg.cpp
When generating code, if the last block being generated does not end in
a control-flow statement a GPF can occur in the CFG trying to add an
appropriate exit edge. While such an unterminated block is ilformed, the
block may be unreachable and will be cleaned up by the optimizer. This
change is to prevent the compiler crashing - an edge from the last block
is added to the end of the CFG.
> Fix ILGen GPF if last block is malformed

- include_core/omrport.h
z/TPF has different signal architecture, therefore turning off until
architecture is reviewed.
> Configure OMR Signal Macros for z/TPF

- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
- compiler/z/codegen/S390GenerateInstructions.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/BitPermuteTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TernaryTest.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
Now that #4733 has been merged we have fixed the issue which was
preventing us from running various sub-int32 tests because the
incoming arguments were not being loaded correctly. We can now
re-enable all the sub-int32 tests which were disabled as a result.
Fixes: #3525
Fixes: #3796
> Fix and enable sub-int32 tests on Z

- compiler/x/amd64/codegen/MemoryReference.hpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
- compiler/x/amd64/codegen/OMRMemoryReference.hpp
- compiler/x/codegen/X86Debug.cpp
Provide the means to specify the use of RIP-relative data addressing for
directly accessible symbols whose addresses are known at compile-time.
The current means is to load the target address into a register and then
indirect load/store from the register.
This commit repurposes an existing boolean flag `_preferRIPRelative` that was
not used in OMR nor any downstream project.  It provided some means of suggesting
that RIP-relative addressing is preferred, but it still wasn't guaranteed to
be used.  This boolean was repurposed to now require that RIP-relative addressing
be used if requested.
This implementation provides two new constructors for MemoryReferences based
on those that take symbol references as parameters.  The constructors now
allow the consumer to specify (require) that …
> Rudimentary support for RIP-relative symbols

- compiler/optimizer/DeadTreesElimination.cpp
We want a volatile field (both static and instance) access to be a
barrier to code motion of other field accesses (to preserve the ordering
semantics that are expected from volatile keyword). The way this is
enforced in the compiler is to consider volatile accesses as "defs"
essentially and relying on the aliasing on the symbol reference to kill
other symbol references impacted by the ordering semantics. Defs in the
compiler must be either a treetop or the first child under a treetop for
optimizations to locate them, i.e. there are optimizations that walk the
IL trees only looking at the treetop and first child for potential defs.
So if a volatile access was accessed for the first time at an arbitrary
spot (level) in a tree (rather than at the treetop level) then it might
get missed as a …
> Fix DeadTreeElimination for volatile load

- fvtest/porttest/si.cpp
- include_core/omrport.h
- port/common/omrport.c
- port/common/omrsysinfo.c
- port/omrportpriv.h
- port/unix/omrsysinfo.c
- port/win32/omrsysinfo.c
This PR implements the API proposed in option 5. in [1]. The new API is implemented on all platforms currently supported by OMR. The new `omrsysinfo_get_CPU_load` calculates the cumulative CPU utilization of all CPUs on the system as a double in the [0.0, 1.0] interval. We implement the new API using the already existing API `omrsysinfo_get_CPU_utilization` by taking two snapshots of CPU time
usage over time and calculating the delta.
At the moment the new `omrsysinfo_get_CPU_load` API is not thread safe.
[1] https://github.com/eclipse/omr/pull/3152#issuecomment-438347430
> Add new omrsysinfo_get_CPU_load API

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- gc/stats/ScavengerCopyScanRatio.cpp
- gc/stats/ScavengerCopyScanRatio.hpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
For background see https://github.com/eclipse/omr/issues/4825
A thread's copy/scan update will be discarded and reset if it finishes
scanning with less than 512 slots scanned
(SCAVENGER_SLOTS_SCANNED_PER_THREAD_UPDATE). Furthermore, if the
accumulator has gathered updates, but doesn't reach the 32 update
threshold (SCAVENGER_THREAD_UPDATES_PER_MAJOR_UPDATE), the updates will
never be pushed to history table and will be discarded/reset.
- Flush implemented
- After complete scan routine but prior to blocking, thread will
flush it's update to the accumulator (minor update)
- Last thread to block will flush the accumulator to update history
table (major update)
- ~~Recording to the history table takes scan cache metrics. This is
problematic during a major flush. To get around this, a snapshot …
> TGC Parallel Flush Copy/Scan Updates

- compiler/il/OMRNode.cpp
Code has been commented out for over 15 years.  It is time to purge.
> Remove deprecated comment from getFirstArgumentIndex

- CMakeLists.txt
- buildenv/jenkins/jobs/builds/Build-linux_x86-64
- buildenv/jenkins/jobs/pull-requests/PullRequest-linux_x86-64
- cmake/config.cmake
- cmake/modules/FindOmrCuda.cmake
- port/CMakeLists.txt
* Stop automatically enabling OMR_OPT_CUDA, so a user has to specifically opt-in for CUDA support.
* Stop using the built-in FindCUDA package, because it requires a complete installation of CUDA. We only need a small subset of the CUDA SDK.
* Enable OMR_OPT_CUDA explicitly in X86-64 builds
> Turn CUDA off by default

- compiler/il/OMRTreeTop_inlines.hpp
`OMR::TreeTop::join()` checks if self() is NULL [1], which is odd
because it never makes sense to call a member function on a NULL
object. Such calls are undefined behaviour.
Closes: #4835
Signed-off-by: Tucker <tuckermiles70@gmail.com>
> Remove NULL check for Self() in TreeTop::join

- compiler/env/FrontEnd.cpp
- compiler/env/FrontEnd.hpp
Removed deprecated FrontEnd getObjectAlignmentInBytes method.
https://github.com/eclipse/openj9/pull/8606 needs to be merged before.
Closes: https://github.com/eclipse/openj9/issues/5904
Signed-off-by: Sean Moffatt <sean.moffatt@unb.ca>
> Removed deprecated FrontEnd:getObjectAlignmentInBytes

- cmake/modules/OmrDetectSystemInformation.cmake
> CMake: recognize 'amd64' processor name

- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, the code for performing a 5-child arraycopy inline was
broken and would generate an instruction with an out-of-bounds immediate
under certain circumstances. This has been fixed by completely disabling
arraycopy inlining for arraycopy nodes with lengths that do not fit in a
32-bit integer.
> Disable Power arraycopy inlining for very long lengths

- include_core/omrport.h
- port/common/omrsysinfo_helpers.c
- port/common/omrsysinfo_helpers.h
- port/unix/omrsysinfo.c
This change involves updating the omrsysinfo_get_x86_description() API and
a few enums.
Issue: #4339
> Update port library's processor detection APIs and enums

- gc/stats/LargeObjectAllocateStats.cpp
- gc/stats/LargeObjectAllocateStats.hpp
- currently we pass double floating precision or
floating precision for SizeClass logarithm calculating,
it might cause wrong result on some special linux system,
pass only floating precision instead of double floating precision
for logarithm calculating.
> Pass floating-point precision to base-e logarithm consistently

- port/common/omrsysinfo_helpers.c
- port/common/omrsysinfo_helpers.h
> Fix missing omrsysinfo_get_x86_description on Windows

- fvtest/porttest/omrsockTest.cpp
- include_core/omrport.h
- port/common/omrsock.c
- port/omrportpriv.h
- port/unix/omrsock.c
- port/win32/omrsock.c
- Fixed minor changes to argument name in omrsock_getaddrinfo_length.
- Added Unix Implementations for extracting elements of OMRAddrInfoNode struct.
- Added tests to further test omrsock_getaddrinfo_create_hints and per thread buffer functions,
using newly implemented element extraction functions.
Issue: #4745
Depends on PR: #4555
> Added Unix Implementations for Element Extracting Functions in OMRSOCK API

- compiler/ilgen/OMRIlBuilder.cpp
- compiler/ilgen/OMRIlBuilder.hpp
- jitbuilder/apigen/jitbuilder.api.json
- jitbuilder/release/cpp/samples/Switch.cpp
- jitbuilder/release/cpp/samples/TableSwitch.cpp
The existing Switch and  TableSwitch (and their overloads) services
could only be used if the condition to switch upon was a named
variable. It was not possible to provide an IlValue to switch on,
which limited the scenarios where we could use the Switch service.
This changeset adds 2 overloads of the Switch service to use IlValue
as the condition to switch on, while still ensuring that the IlValue
provided is of Int32 data type.
This changeset was motivated by the [lljb project](https://github.com/nbhuiyan/lljb).
> Provide IlValue as condition for the Switch IlBuilder service

- jitbuilder/apigen/jitbuilder.api.json
A change in jitbuilder.api.json introduced unnecessary indentation in #4340 
[skip ci] since this is just whitespace modifications
> Remove unnecessary indentation in jitbuilder.api.json.

- compiler/control/OMROptions.cpp
When the perfTool option is enabled the user is likely profiling JIT
generated code which means we would want to disable code cache
reclamation to avoid the profiling tool from mapping ticks to
overlapping JIT methods. We spit out a warning message to stderr so it
is obvious to the user that this is happening.
> Disable code cache reclamation if perfTool option is enabled

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit implements the path in AArch64 OMRMemoryReference for
handling offsets wider than 12 bits.
It is used by loadaddrEvaluator().
> AArch64: Implement large offset path for loadaddrEvaluator()

- compiler/riscv/codegen/OMRTreeEvaluator.hpp
This commit fixes broken compilation on RISC-V after a merge of
66aae968.
> RISC-V: rename `vselectEvaluator()` to `vbitselectEvaluator()`

- fvtest/compilertest/tests/OptTestDriver.cpp
- fvtest/compilertest/tests/OptTestDriver.hpp
The `_ilVer` member specifically needs to be initialized because it is optional. If the user doesn't set one we'll dereference an uninitialized pointer in `OMR::Compilation::compile()`.
> Initialize OptTestDriver's members

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
When the shared class cache feature is not used, the default invocation counts
are count=3000,bcount=3000. They are rather large to allow for enough interpreter
profiling information to be collected. However, this affects the rampup of
Java applications because the transition from interpreter to jitted code is delayed.
Recent experiments have shown that it is possible to reduce the counts from
(3000,3000) to (2000,1000) without affecting the long term throughput.
Because lower invocation counts means more compilations, we can afford to lower the
counts only when we have enough computing power. In this PR the default
invocation counts will be lowered to (2000,1000) only when there are 4 CPUs
or more available.
> Reduce counts when running without SCC and many CPUs are available

- compiler/compile/OMRCompilation.hpp
- compiler/env/OMRKnownObjectTable.cpp
- compiler/env/OMRKnownObjectTable.hpp
- compiler/optimizer/Inliner.cpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/VPConstraint.cpp
- compiler/optimizer/VPHandlers.cpp
Add ` KnownObjectTable::updateKnownObjectTableAtServer()`
which is used to update KOT at the server. 
Remove `KnownObjectTable::getfPointerLocationAt()` which is not used any where.
Add `Compilation::isOutOfProcessCompilation()`which returns true only when it’s called at the server. `Compilation::isOutOfProcessCompilation()` is used to prevent KOT from being used in OMR code at the server where the object pointer needs to be dereferened.
Replace the direct dereference of `getPointerLocation()` with `getPointer()`.
When `getPointer()` is called at the server, it sends a message to the client to dereference it
with the proper VM access.
Although there are a few places where the known object pointers are dereferenced directly, it shouldn't cause any issue if the critical section is created …
> Support Known Object Table in JITServer

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Reduce max and increment size of the pool by factor of 3.4x
This is effectively fixing a regression where this pool increased due to
decrease of minimum copy cache size from 32K to 8K about a couple of
years ago.
The heuristic for the size of the pool is now based on both min and max
size of copy cache. Relying on just min size was too conservative. If GC
dynamically decided to use small copy caches it means that parallelism
is low, what in turn means that scan queue is mostly empty, hence the
need for the caches is low.
> CopyScanCache pool size

- cmake/modules/OmrDetectSystemInformation.cmake
- include_core/omrcfg.cmake.h.in
- include_core/omrcfg.h.in
- port/unix/omrsl.c
Rather than gating behaviour on platform, instead base on availabilty of
the dladdr function
> Update omrsl_open_shared library behaviour on unix platforms

- example/glue/EnvironmentDelegate.hpp
- gc/base/EnvironmentBase.hpp
- gc/base/MasterGCThread.cpp
- gc/base/OMRVMThreadInterface.cpp
- gc/base/standard/EnvironmentStandard.cpp
- gc/base/standard/EnvironmentStandard.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Introducing inactive survivor and tenure copy caches for mutator
threads. A copy cache during VM access release/acquire will move copy
caches to inactive/active. When inactive, they will be eligible for
pushing to scan queue by a third thread (one that senses it's almost end
of concurrent phase).
Cache is deactivated by setting a special inactive cache pointer and
setting null to active one (as opposed to setting an explicit boolean or
a low tag bit in existing cache pointer). This is friendly with existing
object allocation code that checks first thing if copy cache is null or
not. We don't have to do any extra checks to determine that cache is to
be activated.
During VM access release, if there are idle GC threads, the copy cache
will not be deactivated but pushed right away to help …
> Inactive copy caches for Concurrent Scavenger

- include_core/omrport.h
- port/common/omrport.c
- port/common/omrport.tdf
- port/common/omrsysinfo.c
- port/omrportpriv.h
- port/unix/omrsysinfo.c
- port/win32/omrsysinfo.c
This API is used for disabling features in OMRProcessorDesc.
Issue: #4339
> Add omrsysinfo_processor_disable_feature API

- cmake/config.cmake
- configure
- configure.ac
- example/glue/configure_includes/configure_aix_ppc.mk
- example/glue/configure_includes/configure_linux_390.mk
- example/glue/configure_includes/configure_linux_ppc.mk
- example/glue/configure_includes/configure_linux_riscv.mk
- example/glue/configure_includes/configure_linux_x86.mk
- example/glue/configure_includes/configure_win_x86.mk
- example/glue/configure_includes/configure_zos_390.mk
- include_core/omrcfg.cmake.h.in
- include_core/omrcfg.h.in
- omrmakefiles/configure.mk.in
OMR_INTERP_COMPRESSED_OBJECT_HEADER and OMR_INTERP_SMALL_MONITOR_SLOT
are no longer used for anything
> Remove unused compressed ref flags

- cmake/modules/OmrDetectSystemInformation.cmake
- include_core/omrcfg.cmake.h.in
- include_core/omrcfg.h.in
- port/unix/omrsl.c
Change to be inline with autoconf convention
> Rename OMR_HAS_DLADDR to OMR_HAVE_DLADDR

- include_core/omrport.h
Simplify some of the preprocessor conditional logic
> Cleanup preprocessor logic in omrport.h

- port/unix/omrsysinfo.c
> Add omrsysinfo_get_physical_memory implementation for BSD

- fvtest/porttest/omrvmemTest.cpp
As part ofr cleanup testOverlappingSegments deallocates all its memory
descriptrors. However if one of the allocations in the first pass fails,
the remaining portion of the array of descriptors remains uninitialized.
Attempting to later deallocate them causes a segfault. To solve the
issue, all descriptors are initialized to 0, and empty descriptors are
skipped during deallocation cleanup.
> Fix segfault in omrvmemtest

- compiler/aarch64/env/OMRCPU.hpp
- compiler/arm/env/OMRCPU.hpp
- compiler/env/CPU.hpp
- compiler/env/OMRCPU.cpp
- compiler/env/OMRCPU.hpp
- compiler/env/OMRCompilerEnv.cpp
- compiler/env/OMRCompilerEnv.hpp
- compiler/p/env/OMRCPU.cpp
- compiler/p/env/OMRCPU.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
The purpose of this change is to make x86 consistent with other platforms (Power, Z) which use the CPU class instead of codegen to query and cache processor related information.
Issue: #4339
> Migrate x86 processor info from codegen to CPU

- compiler/optimizer/LocalOpts.cpp
Add an explicit check for supported recompilation to enable this optimization.
> Enable invariant argument prex only when recompilation supported

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/PreExistence.cpp
- compiler/optimizer/PreExistence.hpp
I originally submitted these changes in #4779. However, I have made modifications so that this PR does not need to be merged at the same time as a PR in openj9.
This PR is a step towards making the TR_PrexArgInfo class more reusable by decoupling it from the TR_InlinerTracer class. The next step is here https://github.com/eclipse/openj9/pull/8759
- Duplicate functionality from `TR_InlinerTracer::dumpPrexArgInfo` into the new method `TR_PrexArgInfo::dumpTrace`.
- Once all callsites in openj9 are updated to use the new method, the old method can be removed.
- Define the macro `TR_PREXARGINFO_TRACER_CLASS` and update `TR_PrexArgInfo` method signatures to use this macro
- This is done so that we can eventually modify `TR_PrexArgInfo` method signatures to accept a `TR_LogTracer` argument …
> Refactor TR_PrexArgInfo to reduce coupling with TR_InlinerTracer

- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
Remove any references to deprecated Add/Sub IL Opcode by mapping to their signed version.
Issue: #2657
> Remove references of deprecated Add/Sub IL Opcode

- fvtest/rastest/cpuLoadAgent.c
If testTICpuLoad fails, agent aborts without detaching thread. This
results in a hang at shutdown while we wait for all outstanding threads
to shutdown.
> Fix hang in omrrastest

- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertriltest/MaxMinTest.cpp
Provide naive implementations of these two evaluators with internal
control flow regions. We also take this opportunity to refactor and
reduce duplication in the evaluators.
Much of the code between the max/min evaluators for different datatypes
is shared. We minimize the duplication by moving code into helpers and
using parameters to pass in mnemonics which to generate.
Issue: #4276
> Implement dmin/dmax and fmin/fmax on Z 

- compiler/env/ProcessorInfo.hpp
- compiler/x/codegen/X86Ops.hpp
1. Set up `SizeParameterizedOpCode` for `VFMADD231SRegRegReg`. 
2. Add TR_FMA feature mask to `ProcessorInfo.hpp` so that FMA feature detection is supported on the processor.
This commit will support recognizing fma on x86 https://github.com/eclipse/openj9/pull/8573
Issue:eclipse/openj9#7474
> Add support for recognizing fma on x86

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/il/OMRIL.cpp
- compiler/il/OMRIL.hpp
- compiler/il/OMRILOpCodesEnum.hpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRILProps.hpp
Cleaning up duplicated code
Removed deprecated functions (i.e. `getSupportsTernary` etc.)
which were introduced by the PR #4578.
Closes: #681 and #4847
> Refactor ternary to select cleanup

- compiler/optimizer/VPHandlers.cpp
The functions `constrainIntegerLowestOneBit` and `constrainLongLowestOneBit`
were passing the functions `integerToPowerOf2` and `longToPowerOf2`,
respectively, to the helper function
`constrainHighestOneBitAndLeadingZerosHelper`. This caused the helper to compute
the highest one bit instead of the lowest one bit.  This has been fixed by
creating new functions which compute the lowest one bit for integer and log
types.
- Created new helper functions to compute lowest one bit for integer and long
types.
- Pass these new helper functions to
`constrainLowestOneBitAndTrailingZerosHelper`.
Fixes: https://github.com/eclipse/openj9/issues/7088
> Fix bug in value propagation for lowestOneBit

- buildenv/jenkins/jobs/builds/Build-linux_riscv64
- buildenv/jenkins/jobs/pull-requests/PullRequest-linux_riscv64
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/CompareTest.cpp
- fvtest/compilertriltest/ILValidatorTest.cpp
- fvtest/compilertriltest/IfxcmpgeReductionTest.cpp
- fvtest/compilertriltest/JitTest.hpp
- fvtest/compilertriltest/LinkageTest.cpp
- fvtest/compilertriltest/LongAndAsRotateTest.cpp
- fvtest/compilertriltest/MaxMinTest.cpp
- fvtest/compilertriltest/MinimalTest.cpp
- fvtest/compilertriltest/SelectTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
- fvtest/compilertriltest/VectorTest.cpp
- fvtest/jitbuildertest/CMakeLists.txt
This PR enables compiler tests on RISC-V native build CI pipelines. Tests known to fail are disabled and will be dealt with in subsequent PRs.
> RISC-V: enable compiler tests in CI pipeline

- compiler/aarch64/codegen/OpBinary.cpp
This commit corrects the binary encoding of 64-bit "extr" instruction
of AArch64.
> AArch64: Correct the binary encoding of 64-bit "extr" instruction

- compiler/infra/Assert.cpp
- compiler/infra/Assert.hpp
- compiler/p/codegen/OMRInstOpCode.hpp
This PR adds two new macros for asserts that print out more detailed contextual information to assist in debugging: `TR_ASSERT_FATAL_WITH_NODE` and `TR_ASSERT_FATAL_WITH_INSTRUCTION`. When an assert using one of these two macros is triggered, it will print out the relevant context: the treetop that contains the node in question or a small window of instructions surrounding the instruction in question. In addition, by setting the environment variable `TR_AssertFullContext`, the entire method will be printed instead of just the failing node/instruction.
The method by which context is printed is easily extensible by subclassing `TR::AssertionContext` and using the more powerful `TR_ASSERT_FATAL_WITH_DETAIL` macro.
As an example, I added a test assert in the Power binary encoder and then …
> Allow extra context to be printed on assertion failures

- fvtest/porttest/omrsockTest.cpp
- include_core/omrportsock.h
- port/unix/omrsock.c
- port/unix_include/omrsock.h
- Added defintions for constants for OMRSOCK API
- Added OS definitions for constants needed by OMRSOCK API
- Added OMR to OS dependent constants mapping
- Added OS to OMR constants mapping
- Fixed current implementations to accept constants
- Change current test cases to use the new constants
Depends on PR: #4832
Issue: #4795
> Added constants for Unix Implementations in OMRSOCK API

- compiler/il/AliasSetInterface.hpp
- compiler/il/OMRSymbolReference.hpp
Since `TR_SymAliasSetInterface` is the only subclass of `TR_AliasSetInterface`, we can merge the subclass into its parent class.
After this PR, any reference to `AliasSet` will be initialized from `TR_AliasSetInterface` directly.
Issue: #4623 
> Merge TR_SymAliasSetInterface to TR_AliasSetInterface

- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/OMRX86Instruction.hpp
Add versions that take the preceding instruction to append to rather
than a node.
> Add additional generate functions for X86ImmSymInstruction

- compiler/env/OMRCPU.cpp
- compiler/env/OMRCPU.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
On Z, modifications to the processor description are needed
due to command line options and other factors. On X, unused
features are masked out (may come in handy for processor
compatibility tests)
Issue: #4339
> Override CPU::detect() on Z and X86

- compiler/z/codegen/SystemLinkagezOS.cpp
A merge conflict caused us to miss this case which is guarded by the
`J9_PROJECT_SPECIFIC` ifdef which is why the OMR testing did not catch
it.
> Fix use of uintptrj_t guarded by J9_PROJECT_SPECIFIC

- compiler/z/env/OMRCPU.cpp
Downstream projects which are using the newly introduced APIs here are
failing to compile with undefined symbols to `getOptions` since we
forgot to include the inlines file to resolve these symbols.
> Fix OMROptions_includes.hpp missing from OMRCPU on Z

- compiler/optimizer/VPConstraint.cpp
When intersecting VP constraints involving an unresolved class, permit
the intersection of a multi-dimensional array and an array of
java/lang/Objects.  For example, the following constraints should be
mergeable:
Fixed class:     [[I
Unresolved class [Ljava/lang/Object;
Closes: eclipse/openj9#8869
> Fix VP constraint merging for multi-dimensional arrays

- compiler/env/OMRKnownObjectTable.cpp
- compiler/env/OMRKnownObjectTable.hpp
This is the first step of the clean-up:
- Add `getOrCreateIndex()` and `getOrCreateIndexAt`() which
will be used to replace `getIndex()` and `getIndexAt()` in
the second clean-up phase.
- Remove `virtual` declaration of the methods since `KnownObjectTable`
is an extensible class.
> Clean-up support for Known Object Table in JITServer

- compiler/runtime/OMRCodeCache.hpp
This code is intending to refer to ::align() (i.e. a function in the global
namespace, defined in compiler/runtime/Alignment.cpp).
However since the code is itself in the OMR namespace and the align()
is unqalified the compiler will choose OMR::align() in compilation units
that include that definition, and that definition is incompatible both
lexically and functionally.
Unfortunately ::align() and Alignment.cpp are referenced in downstream
projects and so we can't just fix it in the most sensible way without
breaking things first, so instead just make sure this use of align is
properly qualified.
> Fix reference to global align

- compiler/z/codegen/BinaryEvaluator.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
#4811 introduced a bug in the `TR::ssub` and `TR::bsub` evaluators which was not caught during testing because of a testing hole. The bug in #4811 is that we accidentally used the commutative analyzer for evaluating subtraction, but of course subtraction is not a commutative operation.
On Z where we support memory-constant instructions for subtraction we end up taking advantage of the commutative property to attempt to carry out the subtraction from memory directly. Unfortunately if the first operand happens to be the memory operand the commutative analyzer will attempt to reorder it so it is the second operand and use a subtraction instruction (`SH` on Z). This is incorrect.
The fix here is simply to use a non-commutative analyzer.
> Fix ssub and bsub evaluators on Z to use a non-commutative analyzer

- compiler/runtime/OMRCodeCacheManager.cpp
Change `REACHEABLE_RANGE_KB` to 128MB for aarch64 as the offset for
`bl` instruction is in the ragne +/-128MB.
> AArch64: Change REACHEABLE_RANGE_KB to 128MB

- configure
- configure.ac
This option was deprecated, and currently does nothing. Now that all
downstream consumers have been updated, stop supporting the option
entirely.
> Remove option to specify compressed pointers

- ddr/lib/ddr-scanner/dwarf/AixSymbolTableParser.cpp
Crashes have been observed in the current implementation of `split()` in `AixSymbolTableParser.cpp` (see eclipse/openj9#8508); the hope is that this simpler version will fix that.
> Simplify implementation of split()

- compiler/il/OMRNode.cpp
Some code in OMRNode.cpp is guarded with `REMOVE_REGLS_SYMREFS_FROM_SETSYMREF`
macros with a comment explaining it should be cleaned up.  Issue #4647 was created
for that purpose.  Document this in the code.
> Annotate OMRNode code cleanup with issue number

- gc/base/HeapMap.hpp
- gc/base/MarkMap.hpp
base on current MarkMap, verify if there are any liveObjects
in the card. it is helper function for card flushing or
card pruning.
> New Inline function areAnyLiveObjectsInCard

- compiler/runtime/OMRCodeCache.cpp
This patch replaces the use of ::align() in OMRCodeCache.cpp with
OMR::align() as a first step towards removing it altogether. This
step allows downstream extensions of OMR::CodeCache to remove
::align() without breakage.
Issue: #4949
> Use OMR::align() in OMR compiler

- gc/base/EnvironmentBase.cpp
- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.cpp
- gc/base/GCExtensionsBase.hpp
- gc/base/standard/CopyScanCacheStandard.hpp
- gc/base/standard/EnvironmentStandard.cpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Once all GC threads run out of work, the last thread (that would
normally notify all other threads that the scan loop is terminating)
will activate Async Handler to force mutator threads to flush their copy
caches. Then, it (as any other GC thread) would wait till new caches
occur on the scan queue and scan them and eventually again all meet at
the same termination point.
This process may repeat several (typically 1-3) times, until all
copy-scan caches have been returned to the global free cache pool. It is
guaranteed to converge since live set in evacuate is finite, and
mutators are forced to flush caches through either Async Handler or when
they release VM access.
While waiting for caches to occur, the thread that triggered Async
Handling can be also be awaken to yield VM access to …
>  Concurrent Scavenger Async Handler triggering

- compiler/ilgen/OMRMethodBuilder.cpp
The `Call()` JitBuilder service can take a `MethodBuilder` object
as the target, which currently chooses to always inline that
`MethodBuilder`. It only works properly for `MethodBuilder` objects
that haven't been previously compiled. Previously compiled
`MethodBuilder` objects retain some state that cause problems
when the object is passed `Call`. In particular:
- there are dangling `SymbolReference`s stored in `_symbols`
- `_connectedTrees` is true so `connectTrees()` skips the
inlined method code as it stitches the caller's trees
together
These are readily fixed by clearing the `_symbols` map and
clearing the `_connectedTrees` flag.
Fixes: #4909
> Prepare compiled MethodBuilder for use in later Call()

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit sets the enforceStoreOrder flag on AArch64 SMP.
> AArch64: Set the enforceStoreOrder flag

- compiler/codegen/CodeGenPrep.cpp
- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/env/TypeLayout.hpp
To avoid having to implement support for `newvalue` in all the code generators, we now lower it to a `new` with the appropriate field initialization.
The first commit adds a straightforward implementation of the lowering. The second makes the implementation slightly more optimal but, IMO, less straightforward. I've included both of these in the PR so reviewers can compare and decide which is best. Once a decision is made, I will either merge the two commits or drop the second one.
FYI @andrewcraik @cathyzhyi
> Lower newvalue to new

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
This change is to support the JITServer to send the option flag from the client to the Compilation object at the server.
Related to issue eclipse/openj9#8707
> Change realTimeGC field to an internal option

- fvtest/porttest/omrvmemTest.cpp
Expand omrvmemtest on Z/OS
Expanding the current tests to add cases where `OMRPORT_VMEM_PAGE_FLAG_PREFER_PAGEABLE` may be used.
These test cases include:
1) Default large page when `pageable` is preferred
This test will return a `pageable 1M` default large page when available, and 1M fixed pages otherwise.
If no large pages are configured an invalid large page state will be set.
2) Default large page when `pageable` is preferred, and mode is `OMRPORT_VMEM_MEMORY_MODE_EXECUTE`
This test will return a `pageable 1M` default large page when available, otherwise an invalid large page state will be set.
3) Verify 1M large pages when `pageable` is preferred
This test will verify that 1M large pages are supported if there exists a `pageable`, or fixed `1M pages` are available.
4) Verify 1M large …
> Expand omrvmemtest on Z/OS

- gc/base/Collector.hpp
- gc/base/EnvironmentBase.cpp
- gc/base/EnvironmentBase.hpp
- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/ParallelGlobalGC.hpp
https://github.com/eclipse/omr/pull/4905 causing Verbose GC lib linkage
failure on ZOS
EnvironmentBase cannot call Scavenger directly (which is in
standard dir).
Using indirection: EnvironmentBase will call base Collector and through
virtual dispatch effectively call ParallelGlobalGC (which is in standard
dir) that will call Scavenger.
> Fix for ZOS linkage

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ilgen/OMRMethodBuilder.cpp
- compiler/ilgen/OMRMethodBuilder.hpp
- fvtest/jitbuildertest/CMakeLists.txt
- fvtest/jitbuildertest/GlobalTest.cpp
- jitbuilder/apigen/jitbuilder.api.json
Adds DefineGlobal function to MethodBuilder for defining a global variable.
Makes the following changes:
- Adds DefineGlobal function to MethodBuilder in compiler and jitbuilder components. 
- Introduces tests for storing and loading the values of global variables. 
Signed-off-by: Petar Jelenkovic <pjelenko@unb.ca>
> Add DefineGlobal to MethodBuilder

- fvtest/compilertriltest/ArithmeticTest.cpp
Disable some new tests on RISC-V as they test not yet implemented features
and therefore breaks CI builds on RISC-V. Indeed it'd be better to fix RISC-V backend 
to pass those tests, but  the resulting PR would be rather big. 
Therefore I opted for hope-to-be-straightforward PR to disable tests first followed 
by more PRs implementing tested features. Having tests disabled helps me to validate
subsequent PRs as well as to check for unintended breakage of RISC-V port caused by
other PRs being merged.
> RISC-V: disable failing (new) UsingLoadParamAndLoadConst

- include_core/omrcfg.h.in
Add `OMR_ARCH_AARCH64` to omrcfg.h.in.
> AArch64: Add OMR_ARCH_AARCH64 to omrcfg.h.in

- include_core/AtomicSupport.hpp
Use `OMR_ARCH_AARCH64` instead of `AARCH64` which is not defined for OpenJ9 builds.
Depends on https://github.com/eclipse/omr/pull/4982
> AArch64: Use OMR_ARCH_AARCH64 instead of AARCH64

- include_core/omrcfg.cmake.h.in
Add `OMR_ARCH_AARCH64` to `omrcfg.cmake.h.in`.
`OMR_ARCH_AARCH64` is added to `omrcfg.h.in` in https://github.com/eclipse/omr/pull/4982,
but it must be also added to `omrcfg.cmake.h.in` for CMake builds.
> AArch64: Add OMR_ARCH_AARCH64 to omrcfg.cmake.h.in

- compiler/compile/CompilationException.hpp
Initial prototype support in the JIT compiler for identity classes (value types) will not generally handle the case where the class of a value type is unresolved.  For now the JIT compiler should abort the compilation with an `UnsupportedValueTypeOperation` exception, to allow such unsupported operations to be more easily kept track of.
> Define new UnsupportedValueTypeOperation exception

- compiler/z/codegen/OMRRegisterDependency.hpp
With initial implementation, using a fallback such as an interpreter to execute method for which compilation failed due to dependency list overflow could result in silent performance issues.
Changing the assert to fatal helps avoid any potential silent performance issues by ensuring initialization of dependency list with correct capacity.
> Changed dependency list overflow assert to fatal

- port/common/omrport.tdf
Values of type `uintptr_t` may be truncated using `%d`.
> Fix shared library trace formats

- gc/base/MemoryPoolLargeObjects.cpp
- gc/base/MemoryPoolLargeObjects.hpp
LOA size should be bigger than largeObjectMinimumSize, otherwise
the assertion would be triggered during allocation.
small initial heap size via custom Xms option might cause the case.
Update the code to set LOA = 0 if initial LOA size is smaller
than largeObjectMinimumSize.
use inline function isSizeEnoughForLOA() to reduce code duplication.
> Update to avoid initial LOA size is smaller than largeObjectMinimumSize

- fvtest/porttest/si.cpp
Skip sysinfo_test for MacOS tests because resource limits do not work on OSX, and print an error message to the user
> Skip sysinfo_test for MacOS

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit fixes the instruction used in generating a memory address.
You need to use addextx instead of addx when you use the SXTW option.
> AArch64: Fix instruction for add with sign-extension

- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertriltest/SelectTest.cpp
Fix Select Evaluators for Double and Float on Z.
Fixes: #4953
> Fix Select Evaluators for Double and Float

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/optimizer/PreExistence.hpp
This macro was introduced in #4903.
The original issue is here: https://github.com/eclipse/openj9/issues/7936
This is a step towards refactoring the `TR_PrexArgInfo` class so that it is
decoupled from the `TR_InlinerTracer` class.
- Change `TR_PrexArgInfo` method declarations to accept arguments of type
`TR_LogTracer` instead of `TR_InlinerTracer`.
- Change the definition of `TR_PREXARGINFO_TRACER_CLASS` to TR_LogTracer so that
the corresponding method definitions in openj9 are also updated.
- Remove method `TR_InlinerTracer::dumpPrexArgInfo` since it is no longer called
anywhere.
See: https://github.com/eclipse/openj9/issues/7936
> Change TR_PREXARGINFO_TRACER_CLASS macro definition to TR_LogTracer

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/OMRValuePropagation.hpp
When versioning blocks, it's possible for the generated checks to load
index variables from objects by duplicating code from within blocks that
are protected by inlining guards. Therefore the object might not be of
the expected type possibly resulting in loads that reach past the end
of the object. In rare cases this load can result in a SEGV when the
object is allocated at the very end of the heap. In addition, this change
will abort versioning of blocks when the estimated cost of executing the 
required tests is higher then the savings from removing bound-checks.
> Generate instanceOf checks in Block Versioner for index field objects and introduce throttling heuristics

- fvtest/porttest/omrsockTest.cpp
- include_core/omrport.h
- port/common/omrport.c
- port/common/omrsock.c
- port/omrportpriv.h
- port/unix/omrsock.c
- port/win32/omrsock.c
- Small fix to change element extraction function name in OMRSOCK API. The reason for change is to clarify what these function do: to access elements of addrinfo stuct within OMRAddrInfoNode.
- The commits are grouped by groups of related files.
Issue: #4102
> Fix addrinfo element extraction function name in OMRSOCK API

- compiler/x/codegen/FPTreeEvaluator.cpp
The local RA on x86 can't handle spills inside ICF region. Add the
dependencies to endlabel to guarantee that there would be no spills on
both the mainline path and the outlined path
Fixes: https://github.com/eclipse/openj9/issues/7748
> Add register dependencies to ICF end label

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/optimizer/VPConstraint.cpp
- compiler/optimizer/VPHandlers.cpp
Replace `getIndex()` and `getIndexAt()` with `getOrCreateIndex()` and `getOrCreateIndexAt()`.
> Replace the obsolete known object table APIs

- port/zos390/omrsignal_ceehdlr.c
Why did no compiler complain about this?
> Add missing return statement

- compiler/optimizer/VPHandlers.cpp
Interface guard or abstract guard will be patched on class extend event
on any subclass. The test type doesn't matter. However, abstract guard
is only used with method test and interface guard is usually used with
method test. Use method test on them which is what had been used for a
very long time.
Also check if inlining with that guard is supported before doing the
transformation.
> Use method test for interface or abstract guard

- compiler/env/jittypes.h
This commit implements FLUSH_MEMORY() for AArch64 in jittypes.h.
> AArch64: Implement FLUSH_MEMORY() in jittypes.h

- buildenv/jenkins/jobs/builds/Build-zos_390-64
- buildenv/jenkins/jobs/pull-requests/PullRequest-zos_390-64
- compiler/codegen/OMRCodeGenPhase.cpp
- compiler/control/CompileMethod.cpp
- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/SystemLinkagezOS.cpp
- compiler/z/codegen/SystemLinkagezOS.hpp
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertriltest/JitTest.hpp
- fvtest/compilertriltest/LinkageTest.cpp
- fvtest/compilertriltest/MinimalTest.cpp
- fvtest/tril/test/IlGenTest.cpp
- fvtest/tril/tril/simple_compiler.cpp
- jitbuilder/control/Jit.cpp
- jitbuilder/release/CMakeLists.txt
- jitbuilder/release/cpp/samples/Call.cpp
- jitbuilder/release/cpp/samples/Call.hpp
- jitbuilder/release/cpp/samples/Mandelbrot.cpp
This PR contains a series of commits which enables full support for JIT <-> native calls on z/OS. The change appears rather large due to the amount of test code that was enhanced to validate the support. There was also other issues encountered during development which were fixed. Please see the commit descriptions for details on what each change does and why.
The "meat" of the support can be found in the two commits titled:
- "Create the XPLINK Function Descriptor for OMR compiled bodies on z/OS"
- "Use method symbol address to get the entry point in Tril and JitBuilder"
These two commits give us the support and are not very large changes all in all.
Issue: #4719
> Add full support for calls on z/OS and enable corresponding tests

- compiler/p/codegen/OMRInstOpCodeProperties.hpp
The current binary encoding template used for Power ldux instructions is
incorrect, instead encoding a dcbst instruction which would not perform
the requisite load or update the base register. This has now been
corrected and ldux instructions should encode correctly.
> Fix binary encoding template for ldux

- compiler/z/codegen/BinaryCommutativeAnalyser.cpp
- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
This commit adds a flag for miscellaneous-instruction-extensions facility 2
within OMR::Z::CPU. It also adds the relevant methods to retrieve/toggle
this flag.
Lastly, it guards the emission of `MGH`, `MSGC` and `MSC` instructions within `z/codegen/BinaryCommutativeAnalyzer.cpp` with a check for this facility.
Signed-off-by: Pushkar Bettadpur <pushkar.bettadpur@ibm.com>
> Add support for miscellaneous-instruction-extensions facility 2 in OMR::Z::CPU

- compiler/optimizer/OMRValuePropagation.cpp
Fix a build break caused by a failure to check for NULL
> Build-Break fix caused by Pull Request 4598

- compiler/env/OMRClassEnv.hpp
~Classes with value type fields might have those fields flattened (that is, expanded into their components).  `hasUnflattenedValueTypeFields` checks whether a class has any such fields that have not been flattened.~
Define an `isZeroInitializable` method that indicates whether a class's instances have fields that can be trivially initialized by zeroing memory.
The default implementation returns true unconditionally, but can be overridden by downstream projects.
> Add query method for class whose instances are zero initializable

- compiler/z/codegen/BinaryCommutativeAnalyser.cpp
A few instructions are being emitted with only CPU checks
but without checking if the correct facilities have been
installed on the machine. This commit correctly guards
a few such instructions.
Signed-off-by: Pushkar Bettadpur <pushkar.bettadpur@gmail.com>
> Guard Instructions dependant on MIE2 installed

- buildenv/jenkins/omrbuild.groovy
- Change from Declarative to Scripted pipeline syntax.
- Use parameter BUILDSPEC to determine what spec to use.
- Add build node link in build description.
- Add build timeout of 1 hour and overall timeout of 8 hours.
- Reduce fetch on PR builds by limiting refspec to single PR ID.
- Use custom workspace name as a workaround for issue setting
LIBPATH on zOS.
- Will need to update the jobs once this is merged. Then
a follow up PR to remove the old files.
> Refactor Jenkins Pipelines into single file

- compiler/env/OMRClassEnv.cpp
- compiler/env/OMRClassEnv.hpp
- compiler/optimizer/VPHandlers.cpp
This PR removes an OMR function `numConcreteClasses`. and added a frontend calling corresponding OpenJ9 function. 
This function takes a list of subclasses and count the number of concrete classes. It is called only once in the code base and compare number of concrete class with two. Thus it is safe to modify this function and return a boolean value once number of concrete class reaches two. This is also included in the change.
This change reduces JITServer messages between client and server. Since this function can be now executed on the server instead of sending messages to client. 
This change contains two PRs, one in OpenJ9 and one in OMR. The OMR PR depends on this PR, thus this should be merged after OpenJ9 or it will break the build. 
Reference: …
> Move function numConcreteClasses into OpenJ9 ClassEnv

- buildenv/jenkins/omrbuild.groovy
- In declarative syntax, the SCM variables were
exposed in the env variable. In scripted syntax
this is not the case. We must capture the SCM
variables in order to access them.
Related #4992
> Return SCM variables for Github statuses

- gc/base/MemoryPoolLargeObjects.cpp
- gc/base/MemoryPoolLargeObjects.hpp
zero minLOAFreeRatio during the class construction, to avoid
the case, which minLOAFreeRatio can be used before being set to
a meaningful value.
extra assertion for verifying minLOAFreeRatio value is between
0 to 1.
> Fix minLOAFreeRatio initialization issue

- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/runtime/ppcasmdefines.inc
Previously, the list of Power opcodes included a number of VSX
load/store indexed with update instructions that do not actually exist.
These have been removed.
> Remove non-existent VSX load/store with update instructions

- include_core/omrgcconsts.h
Re-order write barrier types so that two groups for pre/post-store
action are easily identified.
Also adding comments to help understand some other
changes that rely on these barrier types.
> Barrier type re-ordering 

- compiler/aarch64/codegen/OpBinary.cpp
Fix encoding of `ldxr`/`stxr` instructions.
> AArch64: Fix encoding of ldxr/stxr instructions

- azure-pipelines.yml
When a test fails we want the job to be marked as failed as well,
however we still wish to run the "Publish results" job so that the test
output can be parsed and test results published. We modify the pipeline
so if there are failures we fail the "Test" job, but still continue to
run the "Publish results" job.
> Fix marking of failed tests in Azure Pipelines

- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/il/Aliases.cpp
- compiler/ras/Debug.cpp
The new `objectEqualityComparison` non-helper represents an object equality comparison that is more complex than a simple reference comparison.
This new symbol, along with `acmpHelper`, is also added to appropriate alias sets.
> Add non-helper symbol for working with value types

- compiler/env/OMRClassEnv.cpp
- compiler/env/OMRClassEnv.hpp
- compiler/optimizer/VPHandlers.cpp
Correct typo in new added function name `containsZeroOrOneConcreteClass`.
Reference: https://github.com/eclipse/omr/issues/5037
Depends on: https://github.com/eclipse/openj9/pull/9166
Signed-off-by: Chris Chong <Zichun.Chong@ibm.com>
> Fix typo in function name containesZeroOrOneConcreteClass

- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit corrects the binary encoding of AArch64 "load/store
exclusive" instructions.
> AArch64: Binary encoding of load/store exclusive instructions

- compiler/env/OMRKnownObjectTable.cpp
- compiler/env/OMRKnownObjectTable.hpp
Remove `getIndex()` and `getIndex()` and they have been replaced by `getOrCreateIndex()` and
`getOrCreateIndexAt()`.
This is the last commit for this cleanup. The previous related PRs are:
- #5004
- #4930
- eclipse/openj9#8931
- eclipse/openj9#9075
> Remove obsolete APIs in known object table

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit adds a call to redoTrampolineReservationIfNecessary()
upon hasCodeCacheSwitched() in generateBinaryEncoding() for
ARM64ImmSymInstruction.
Fixes: eclipse/openj9#9214
> AArch64: Call redoTrampolineReservationIfNecessary()

- port/common/omrcuda.cpp
This reverts #4389 and more generally fixes the way error codes of type `J9CudaError`, `cudaError_t` and `CUresult` are handled. Conversions between `J9CudaError` and `cudaError_t` are sensitive to the version of the CUDA runtime in use.
> Translate between J9CudaError and cudaError_t as necessary

- compiler/optimizer/OMRLocalCSE.cpp
- compiler/optimizer/OMRLocalCSE.hpp
For the optimization level hot and above, we run two passes in localCSE. First one for the volatiles only and second one for non volatiles only. In case of the volatiles only pass, to make sure we common the volatile which are based on an indirection non volatile finals or non global autos/parm it marks such node available for commoning in volatile pass. Issue occurs, where it encounters first reference of such non volatile nodes and just adds it to the list of replaced nodes without replacing it. This causes an issue with the subsequent reference of such non volatiles which will be replaced with the available expression as node is already in the list of replaced nodes. 
This commit fixes the issue so that if it encounters finals or autos or parms in volatile pass which are candidate for …
> Fix localCSE where it does not common the eligible node

- ddr/tools/blob_reader/CMakeLists.txt
- ddr/tools/blob_reader/Makefile
- ddr/tools/ddrgen/CMakeLists.txt
- ddr/tools/ddrgen/Makefile
Using g++ 7.5 requires a version of libstdc++ that is newer than what is available on CentOS. Statically linking that library allows these tools to run on CentOS.
> Use '-static-libstdc++' when linking ddrgen and blob_reader

- port/common/omrcuda.cpp
* fix omrcuda_deviceGetAttribute() - it should not return `J9CUDA_ERROR_NO_DEVICE` on success
* fix omrcuda_hostAlloc() - it should not return `J9CUDA_NO_ERROR` unconditionally
> Fix CUDA return values

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/env/TRMemory.cpp
- compiler/env/TRMemory.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/env/OMRCPU.hpp
Previously, a half-implemented feature called LM guarded storage was
present in the Power codegen. This code was never used since the
necessary hardware support was never added for it to work. Since it's
unlikely that the necessary support will ever be added, all associated
code has been removed.
> Remove remnants of LM from the Power codegen

- compiler/infra/OMRMonitor.hpp
- compiler/runtime/Runtime.hpp
The following warning is emitted when compiling a compilation unit
which includes the OMRCodeCache.hpp file:
```
"omr/compiler/runtime/OMRCodeCache.hpp", line 450.14: CCN8891 (W) The
array member "void *_CCPreLoadedCode[]" may only be followed by members
of consistent type.
```
The reason this warning is emitted is because `TR_numCCPreLoadedCode`
evaluates to 0 on S390 due to an ifdef and so we have a zero length
array on z/OS. It is emitting a warning because we have types declared
after the zero length array which are not of the same type as the array
elements.
To fix this issue we simply omit an ifdef which forces the value of
`TR_numCCPreLoadedCode` to be non-zero on S390. This is reasonable, as
this enum is not used at all in the S390 codegen.
When a compilation unit including the …
> Fix pervasive warnings on z/OS and AIX

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
Adding Instr Opocde `fmaddd` and `fmadds` for supporting FMA operations on aarch64
Issue:eclipse/openj9#7474
> Support FMA operations on aarch64

- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrPlatform.cmake
- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/xlc.cmake
- Update logic omr_split_debug/omr_process_split_debug. It is now safe to
call on all targets. Checks on library type and config options are now
handled internally.
- Rename omr_split_debug() -> omr_process_split_debug to reflect new
behaviour.
- Toochain debug info splitter functions are now responsible for setting
the OMR_DEBUG_FILE property on a target, which points to the file where
the debug info is stored.
> CMake: Overhaul split debug handling

- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- getMethodFromBCInfo is removed from CompilerThread.cpp, IProfiler.cpp
and HWProfiler.cpp
- getMethodFromNode is removed from IProfiler.cpp
- getMethodFromBCInfo is added to OMRNode.cpp
- fej9->isAOT_DEPRECATED_DO_NOT_USE() in getMethodFromBCInfo is
replaced with compileRelocatableCode()
- This routine is renamed to getOwningMethod and declared as static.
Issue: eclipse/openj9#5257
> Consolidating getMethodFromBCInfo type routines

- compiler/ilgen/OMRIlBuilder.cpp
- jitbuilder/release/cpp/samples/Call.cpp
- jitbuilder/release/cpp/samples/Call.hpp
Re-initialize method builder objects before inlining
When using the JitBuilder `Call` service and passing a `MethodBuilder` object, we do not know the origin of that object before we begin to inline it. In most code samples, that object is a "fresh" `MethodBuilder` that hasn't been compiled itself. When it has been compiled previously, there are some TR objects cached in it that cause problems during inlining, such as the compilation object, the method symbol, etc. These should be re-initialized to the current `MethodBuilder` being compiled before the callee `MethodBuilder` is inlined. While `setupForBuildIL()` is called, we also need to call `initialize()` to re-initialize these fields. I missed this in my earlier attempt to address #4909 .
Included in this fix is an update to the `Call` …
> Jb call inline sample

- cmake/modules/OmrDDRSupport.cmake
We need to make sure that the split debug info is procesed before we
start handling the ddr side of things, otherwise calls to
omr_process_split_debug after target_enable_ddr will cause ddr to fail to
extract the debug info from the target.
> CMake: Ensure that split debug info is processed in  target_enable_ddr

- compiler/x/codegen/X86Ops.ins
Add encodings for BTR8RegImm1 and BTR4RegImm1.
> Introduce bit-test-and-reset immediate instructions on x86

- compiler/x/codegen/OMRMemoryReference.cpp
The X86 MemoryReference copy constructor does not copy the constant data
snippet field if there is one.  Make it so.
> Fix X86 MemoryReference copy constructor for constant data snippets

- compiler/x/codegen/OMRTreeEvaluator.cpp
On one path where a preceding instruction was provided, the wrong instruction
constructor was being used that will lead to the instruction being inserted in
the wrong place.  Use the correct constructor when a preceding instruction is
provided.
> Use correct RegImm64 constructor for insertLoadConstant

- compiler/ras/Debug.cpp
Implement `TR_Debug::getGlobalRegisterName` for aarch64.
> AArch64: Implement TR_Debug::getGlobalRegisterName

- gc/base/EnvironmentBase.hpp
- gc/base/MasterGCThread.cpp
- gc/base/standard/EnvironmentStandard.hpp
- gc/base/standard/Scavenger.cpp
When creating remainder or abandoning it, use target environment even if
current thread != from target environment.
This we resolve the problem of occasional waste of abandoned Tenure TLH
remainders for mutator threads. Now, we will be able to re-use them on
next CS cycle.
However, to be able to safely use target's environment, it must be
ensured that target thread is not using the remainder at the same time.
This will be ensured by either target thread not holding VM access, or
if racing to acquire VM access it will serialize by external means (for
example, in OpenJ9, by public flags mutex).
> Cache clear and abandon simplification

- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/TLHAllocationInterface.cpp
- new _traceAllocationBytes include ool and inline allocation
- new flag disableInlineAllocationForSamplingBytesGranularity
> Support tracing both inline and out of line allocation bytes

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
Implement `getLinkageGlobalRegisterNumber` for aarch64.
> AArch64: Implement getLinkageGlobalRegisterNumber

- example/glue/configure_includes/configure_linux_riscv.mk
The change is to ensure the installed cross-compiler
is correctly set up on the host system from OMR
perspective by changing the prefix of the cross-toolchain
if users prefer the installed cross-compiler rather than
building a cross-compiler from the source.
Issue: #4426
> Add support to the installed cross-compiler for RISCV

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit implements `getMaximumNumbersOfAssignableGPRs` and `getMaximumNumbersOfAssignableFPRs`.
> AArch64: Implement getMaximumNumbersOfAssignableGPRs/FPRs

- buildenv/jenkins/jobs/builds/Build-aix_ppc-64
- buildenv/jenkins/jobs/pull-requests/PullRequest-aix_ppc-64
- buildenv/jenkins/omrbuild.groovy
* related eclipse/omr#5016
* /usr/vac is the location of xlc12 which new machines do not have installed
> Update AIX builds with version appropriate copy of CreateExportList

- include_core/unix/thrdsup.h
Instead of being strictly platform based, attempt to check for POSIX
compliance
> Update logic surrounding THREAD_YIELD()

- cmake/modules/OmrDetectSystemInformation.cmake
OpenJ9 depends on `OMR_ENV_GCC` being defined (or not) appropriately.
> Set OMR_ENV_GCC in gnu.cmake (except on OSX)

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/ARM64SystemLinkage.hpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit adds register allocation order list to linkage property
and populates it in the constructor of `ARM64SystemLinkage`.
The intention of this commit is to move `_globalRegisterNumberToRealRegisterMap` from `OMRMachine` to linkage class as ppc codegen does.
> AArch64: Add register allocation order list to linkage property

- gc/base/Collector.cpp
- gc/base/Collector.hpp
- gc/base/GlobalCollector.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
Generalize the existing flag that was being set only in Concurrent
Global GC to being maintained by base Collector, so that can be used
for any STW Collector.
Specifically, it was needed in an unusual combination when Concurrent
Scavenger was enabled, but Concurrent Mark disabled (so Global GC was
not MM_ConcurrentGC, but MM_ParallelGlobalGC which would not set STW
flag), and when CS would abort and Global Marking would miss to fixup
forwarded slots (during STW phase).
In future, the flag might be useful for other code in CS & Balanced to
determine if GC threads running in STW or concurrent phase. But for that
we have to properly set it for cases when Master Threads is explicit.
This is better to do in a separate change, if/when it becomes important.
For now, this flag is reliable only …
> Collector STW flag

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
- Change code generator to initialize global register table
from linkage property instead of `OMRMachine`.
- Remove unused members from `OMRMacine`.
Depends on 
- https://github.com/eclipse/omr/pull/5109
- https://github.com/eclipse/openj9/pull/9337
> AArch64: Initialize global register table from linkage property

- fvtest/porttest/si.cpp
- port/unix/omrsysinfo.c
on OSX, there are two mechanisms for reporting the limits of the system.
The first is getrlimit/setrlimit, and the second is through sysctl.
Sysctl will report the maximum number of open files that the kernel will
allow a process to have. This is a global property that affects all
processes.
getrlimit/setrlimit, on the other hand, will report the limits set on a
given process.
These two limits do not have to match.
The true soft limit for open files is the minimum between the current
rlimit and the sysctl limit.  The true hard limit is the minimum between
the max rlimit and the sysctl limit.
With this PR, this is what we report and enforce on OSX.
Fixes: #4990
> Fix max open file limits on OSX

- compiler/aarch64/codegen/OMRMemoryReference.cpp
`OMR::ARM64::MemoryReference::addToOffset` uses node's register as displacement
if node is `const` node. It uses the node associated with the last instruction
if `NULL` is passed to `addToOffset` as `node` argument. Unfortunately,
the node chosen is irrelevant in some cases.
This commit adds value check before using the node's register to avoid using
incorrect register for displacement.
This commit also moves if-block for the case where const value can be encoded
in `addimmx` instruction before the if-block for the case where node's register
can be reused.
> AArch64: Add check before using register of node in memory reference

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit enables Global Register Allocation for aarch64.
- Add call to `setSupportsGlRegDeps` to constructor of CodeGenerator.
Depends on:
- https://github.com/eclipse/omr/pull/5091
- https://github.com/eclipse/omr/pull/5092
- https://github.com/eclipse/omr/pull/5093
- https://github.com/eclipse/omr/pull/5094
> AArch64: Enable Global Register Allocation

- compiler/optimizer/PreExistence.hpp
This is the next PR in a sequence of steps to refactor the TR_PrexArgInfo class.
The previous PR was here: https://github.com/eclipse/openj9/pull/9163
This macro was used temporarily to coordinate changes with openj9. Now that the
necessary changes have been made in openj9, this macro can be removed.
See: https://github.com/eclipse/openj9/issues/7936
> Remove TR_PREXARGINFO_TRACER_CLASS macro

- CODEOWNERS
> Add knn-k as a code owner for ARM code generators

- compiler/optimizer/OMRSimplifierHandlers.cpp
```
OMRSimplifierHandlers.cpp: In function 'bool evaluateIntComparison(TR_ComparisonTypes, bool, int64_t, int64_t)':
OMRSimplifierHandlers.cpp:2023:4: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```
Also remove dead code (break after return).
> Fix compile warning

- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit stops generating unnecessary instruction for zero extension
in iu2lEvaluator().
iloadi-iu2l sequence often appears in IL compressedRefs tree, and
AArch64 ldrimmw instruction clears the upper 32 bits of the register.
> AArch64: Omit unnecessary zero-extension instruction in iu2l

- compiler/x/codegen/OMRCodeGenerator.cpp
The static variable TR_X86ProcessorInfo should only be initialized
once. Initializing it repeatly caused a race condition in the code.
Technically we may still have syncronization issues without a lock,
but the chances will be much lower with this change. Note that this
implementation of processor detection will be replaced soon. This
change is only needed to test out the new processor detection APIs.
Issue: #4339
> Prevent TR_X86ProcessorInfo::initialize from re-initializing

- compiler/p/codegen/UnaryEvaluator.cpp
It seems that previously, there was code in the Power codegen guarded by
the definition of a J9_ProjectSpecific macro. This was a misspelling of
the J9_PROJECT_SPECIFIC macro, so this code was never actually used.
This could cause incorrect behaviour in OpenJ9 if an irsload node
appeared under an s2i node. The spelling of this check has been
corrected so that the code should now be enabled correctly.
Fixed: #5137
> Fix incorrect spelling of J9_PROJECT_SPECIFIC

- include_core/AtomicSupport.hpp
- include_core/omrutilbase.h
- util/omrutil/CMakeLists.txt
- util/omrutil/makefile
- util/omrutil/unix/linux/riscv/32/cas32helper.s
- util/omrutil/unix/linux/riscv/64/cas64helper.s
The changes mainly include the code for CAS-specific
functions as well as memory barrier on RISC-V.
Issue: #4426
> Change CAS code & memory barrier for RISC-V in OMR (part6/cas)

- compiler/aarch64/codegen/BinaryEvaluator.cpp
This code improves code generation for iadd/ladd/isub/lsub evaluators.
Add/sub (immediate) instructions for AArch64 takes unsigned values as
their operands.  Use negated immediate when applicable so that it can
be embedded in the instruction.
> AArch64: Improve code generation for add/sub constant

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- fvtest/compilertriltest/SelectTest.cpp
This commit implements iselectEvaluator() and fselectEvaluator() for
AArch64.
> AArch64: Implement select evaluators

- include_core/omrport.h
- port/common/omrsysinfo_helpers.c
- port/common/omrsysinfo_helpers.h
- port/unix/omrsysinfo.c
- port/win32/omrsysinfo.c
- replace OMRPORT_SYSINFO_OS_FEATURES_SIZE with OMRPORT_SYSINFO_FEATURES_SIZE for omrsysinfo_processor_set_feature and omrsysinfo_processor_has_feature
- update the port library to include extended features
- replace CPUID_SIGNATURE_FAMILY with CPUID_SIGNATURE_MODEL on one instance (used the CPUID_SIGNATURE_FAMILY mask to get modelCode for CPUID_FAMILYCODE_AMDKSERIES which is incorrect)
- add helpers to extract cpu information
Issue: #4339
> Update x86 processor detection in port library

- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
For the internal control flow end labels, there is no change to the
register state. Hence, instead of adding both the pre-conditions and
the post-conditions to such labels; it is sufficient to use
post-conditions only.
This commit addresses such cases for the power codegen.
Resolves: #4991
Signed-off-by: Mohammad Nazmul Alam <mohammad.nazmul.alam@oibm.com>
> Change to postconditions only for ICF end labels

- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
Remove `OMR::ARM64::Linkage::hasToBeOnStack` so that the common
implementation `OMR::Linkage::hasToBeOnStack` is used.
> AArch64: Remove `hasToBeOnStack` from OMRLinkage

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/ARM64SystemLinkage.hpp
- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
- Move `copyParametersToHomeLocation` to OMRLinkage class. We will use this function from both system linkage and private linkage.
- Change `ARM64SystemLinkage::createPrologue` to use `copyParametersToHomeLocation`.
- Implement `ARM64SystemLinkage::setParameterLinkageRegisterIndex`.
> AArch64: Move copyParametersToHomeLocation to OMRLinkage

- compiler/control/OMROptions.cpp
This commit changes the default JIT option for AArch64.
> AArch64: Change the default JIT option

- compiler/aarch64/codegen/OMRLinkage.cpp
This commit enhances `OMR::ARM64::Linkage::copyParametersToHomeLocation` to
support Linkage Register Allocation.
Depends on https://github.com/eclipse/omr/pull/5162 and https://github.com/eclipse/omr/pull/5161
> AArch64: Enhance copyParametersToHomeLocation to support Linkage Register Allocation

- compiler/compile/OMRSymbolReferenceTable.cpp
MonitorExit helper can throw exception so set canGCandExcept to true
> Fix canGCAndExcept flag for TR_monitorExit helper

- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OpMemToMem.cpp
- compiler/z/codegen/S390GenerateInstructions.cpp
- compiler/z/codegen/S390GenerateInstructions.hpp
- Document the uses of function `generateShiftAndKeepSelected(64|31)Bit`. And provide corresponding example. 
- Remove the redundant arguments.
- Add assertions to restrict the values of arguments.
Issue: #3814
Signed-off-by: simonameng <simonameng97@gmail.com>
> Document uses of function 'generateShiftAndKeepSelected(64|31)Bit'

- compiler/ras/ILValidationRules.cpp
- compiler/ras/ILValidationRules.hpp
- compiler/ras/ILValidationStrategies.hpp
- compiler/ras/ILValidator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/ILValidatorTest.cpp
- Implement `axaddEvaluator` on Z which combine the code of current 'aiaddEvaluator' and 'aladdEvaluator', because they have almost the same codes. 
- Add tril tests for `aiadd` and `aladd`. Ideally, `aiadd` should be only used on 32 bit platforms and `aladd` should be used on 64 bit platforms. So their tril tests will be guarded by `OMR_ENV_DATA64`. Also, add an verifiers for 'aiadd' and 'aladd' to ensure the data types of their pass-in arguments are correct.
> Improve handling of 'aiadd' and 'aladd'

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit turns on `SupportsGlRegDepOnFirstBlock` for aarch64.
Depends on:
- https://github.com/eclipse/omr/pull/5161
- https://github.com/eclipse/omr/pull/5162
- https://github.com/eclipse/omr/pull/5163
> AArch64: Enable SupportsGlRegDepOnFirstBlock

- CMakeLists.txt
This means that `make all` will not build any of the third party code,
unless it is required  by other targets given your configuration
> CMake: Exclude third party code from the `all` target

- gc/base/Collector.cpp
- gc/base/Collector.hpp
- gc/base/GlobalCollector.hpp
Fixes: eclipse/omr#5178
moving isTimeForGlobalGCKickoff() from MM_Collector(base) to MM_GlobalCollector (subclass) so downstream projects will not invoke isTimeForGlobalGCKickoff against MM_Collector.
Signed-off-by: Enson <enson.guo@ibm.com>
> Remove isTimeForGlobalGCKickoff() from base Collector class

- gc/base/j9mm.tdf
- gc/base/standard/Scavenger.cpp
Remove the Concurrent Scavenger transition at the begining of
Scavenger's percolate, since we will attempt it anyway before really
percolating as part of
MM_ParallelGlobalGC::completeExternalConcurrentCycle().
Having both attempts can cause problems if first one aborts and then
instead of directly percolating, the second one may trigger another STW
increment seeing the previous one did not complete cycle (not knowing it
aborted).
For a few trace points adjusted priorities, based on how important they
are vs how frequently they occur.
> Redundant CS transition

- compiler/ras/Debug.hpp
This snippet class is dead and being removed from OpenJ9 ([PR 9548](https://github.com/eclipse/openj9/pull/9548))
> Remove mention of dead PPCHeapAllocSnippet class

- .gitignore
- cmake/modules/OmrTargetSupport.cmake
- cmake/modules/OmrUtility.cmake
- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/xlc.cmake
- doc/ddr.md
Rework computation of debug info filenames for consistency with makefile behavior.
> CMake: Generate libX.debuginfo instead of libX.so.dbg

- cmake/modules/OmrTargetSupport.cmake
Allows the target OUTPUT_NAME to be set before processing split debug info
> CMake: Add support for OUTPUT_NAME parameter in omr target functions

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/ras/Debug.hpp
Add `ARM64MemSrc2Instruction` to enable `stp/ldp` instructions.
> AArch64: Add ARM64MemSrc2Instruction

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit makes `registerBitMask` function available to
outside of `OMRCodeGenerator.cpp`.
> AArch64: Make registerBitMask function available to outside of code generator

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRSnippet.hpp
Add `IsHeapAlloc` to enum for Snippet kind.
> AArch64 Add IsHeapAlloc to enum for Snippet kind

- compiler/ras/Debug.cpp
This commit adds some entries for AArch64 in TR_Debug::getRuntimeHelperName().
> AArch64: Add entries in TR_Debug::getRuntimeHelperName()

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit changes `getRegisterName()` in `ARM64Debug.cpp`
to support `NoReg`.
> AArch64: Make getRegisterName() support NoReg

- compiler/il/NodePool.cpp
error message mispelt collection as colleciotn
Signed-off-by: Austin Wells <austin.wells@mail.utoronto.ca>
> Fix typo in NodePool::removeDeadNodes

- compiler/x/codegen/OutlinedInstructions.cpp
- compiler/x/codegen/OutlinedInstructions.hpp
TR_OutlinedInstructionsGenerator::endOutlinedInstructionSequence() will
eventually do the cleanup necessary after generating an outlined
instruction sequence in the x86 codegen. For now, an empty
implementation is provided for the purpose of coordinating changes
with downstream projects.
Issue: #4846
> Add empty definition for endOutlinedInstructionSequence

- cmake/modules/OmrCompilerSupport.cmake
> CMake: Add support for OUTPUT_NAME parameter for compiler libraries

- buildenv/jenkins/omrbuild.groovy
Since we manage our own export lists, this functionality is not needed.
> Jenkins: Disable CreateExportList on aix

- compiler/optimizer/OMRCFGSimplifier.cpp
There are bugs in these patterns. Disabling them allows CFG simplification to
be enabled while the root causes of these problems are investigated.
See: https://github.com/eclipse/openj9/issues/8397
> Disable CFG simplifier patterns related to conditional stores

- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
- compiler/z/codegen/S390Debug.cpp
Downstream projects such an OpenJ9's JITServer
cannot operate correctly if certain fields are static.
This is because the JITServer can talk to multiple
JVM clients such that the static field's value on the JITServer
side is no longer valid for all client JVMs. This commit
removes those problematic statics.
An unused function is also removed.
> Remove some statics from z/codegen

- compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OutlinedInstructions.cpp
- compiler/x/codegen/OutlinedInstructions.hpp
`TR_OutlinedInstructionsGenerator::endOutlinedInstructionSequence()` can now be safely implemented by taking the code from the class destructor. The destructor will now also assert that `endOutlinedInstructionSequence()` is called when needed.
Closes #4846
> Move code out of ~TR_OutlinedInstructionsGenerator(), preventing it from throwing

- cmake/caches/Travis.cmake
- cmake/config.cmake
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrUtility.cmake
- cmake/modules/platform/toolcfg/gnu.cmake
- cmake/modules/platform/toolcfg/xlc.cmake
Fix the handling of how we determine the name of the split debug file.
Also enable split debug info in the CI builds, so it hopefully catches these issues
in the future.
> CMake: Update split  debug info handling

- .github/workflows/stale.yml
Apparently v1.1.0 does not support `exempt-issue-labels` option, even
though the release page [1] says it does. Upgrade to v3.0.0 and set the
cron job to run only once per day so we can evaluate whether the issue
is fixed.
[1] https://github.com/actions/stale/releases/tag/v1.1.0
> Upgrade stale GitHub Action to v3.0.0

- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRLinkage.hpp
- compiler/z/codegen/SystemLinkage.cpp
- compiler/z/codegen/SystemLinkage.hpp
- compiler/z/codegen/SystemLinkageLinux.cpp
- compiler/z/codegen/SystemLinkageLinux.hpp
- compiler/z/codegen/SystemLinkagezOS.cpp
- compiler/z/codegen/SystemLinkagezOS.hpp
This commit removes references to the S390JNICallDataSnippet
class in OMR. This is in preparation to move the class down
to OpenJ9 as it doesn't belong in OMR.
> Remove TR::S390JNICallDataSnippet references

- .github/workflows/first-interaction.yml
Upgrade the cron-first-interaction GitHub Action to version 0.2.0 [1].
This release improves the query for whether a PRs is a particular users
first PR. The problem with version 0.1.0 is that the action only
fetched the default number of issues per query, which ends up being 25
issues.
The problem we ran into at OMR is that due to the limitation of the
octokit API in that there is no way to filter only PRs by author [2],
we have to resort to fetching both issues and PRs, as that allows for
filtering. Now we only filtered by author, and according to [3] that
defaults to fetching issues and PRs sorted by date created in
descending order, meaning most recent first.
Now the issue arises for contributors in OMR that have very old PRs
open. One example can be seen in [4] by @wbh123456 where the …
> Upgrade first-interaction to 0.2.0 and decrease cron to every 30 minutes

- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit enables rdbar/rdbari evaluators in OMRTreeEvaluatorTable.hpp
for AArch64.
The evaluators are available in the common codegen/OMRTreeEvaluator.cpp.
> AArch64: Enable rdbar/rdbari evaluators in OMRTreeEvaluatorTable

- port/linux/omrosdump_helpers.c
Some versions of glibc generate warnings about ignoring the return
value of strtoull. Its not important here as we are just strtoull
to advance the string pointer.
> Fix warning in port linux/omrosdump_helpers.c

- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/GenerateInstructions.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
For a better encapsulation of codegen
`generateConditionalBranchInstruction` helper functions.
The caller passes branch hints when possible and the
function checks if the processor supports it.
> Refactor processor version check for branch hints

- .github/workflows/stale.yml
There was a bug in the official implementation caught when the stale
issue action ran on the OMR repo. I have investigated the issue and
submitted a fix in [1], however I'm unsure of when that change will
land into the official repo. Until then we disable the stale issue
marker and run it under debug mode only which will print out all the
actions it is about to do without actually doing them.
Following this change and the upstream fix I'll be able to monitor the
debug output to ensure the action is correctly functioning, at which
point we can enable it again.
[1] https://github.com/actions/stale/pull/85
> Disable stale issue marker until upstream issue is resolved

- compiler/arm/env/OMRCompilerEnv.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/env/OMRCPU.cpp
- compiler/env/OMRCPU.hpp
- compiler/env/OMRCompilerEnv.cpp
- compiler/env/OMRCompilerEnv.hpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/IntegerMultiplyDecomposer.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Ops_inlines.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
- compiler/z/env/OMRCPU.cpp
- Replace old processor APIs with new APIs from the CPU class
- Replace global TR::Compiler target with per comp target so that each compilation can either use target or relocatableTarget depending on the type of the compilation (JIT or AOT)
- When there is no port lib available, continue to use old APIs
Issue: #4339
> Replace CPU APIs on x86

- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- fvtest/compilertriltest/MaxMinTest.cpp
This PR solves issue #5156 by adding NaN checks and returns the correct result when NaN is one of the operands.
Also while working on that issue I noticed that `[ilfd]maxminSimplifier`s and Power's `generateMaxMin` functions still support arbitrary number of operands, and given the discussion in #4176, I removed that support leaving only support for 2 operand. 
Closes: #5156 
> Max/Min support for NaN on Power and set Max/Min support to 2 operands only

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit enables bcmp*, bucmp*, scmp* and sucmp* evaluators for
AArch64.
> AArch64: Enable bcmp*, bucmp*, scmp* and sucmp* evaluators

- compiler/control/OMROptions.cpp
In OpenJ9, the implementation of value types does not behave well with regDepCopyRemoval. Specifically,  the ifacmp{eq,ne} operations rely on lowering that requires basic block splitting after GRA. RegDepCopyRemoval currently leaves the trees in a state that the post GRA block splitter cannot handle. So, for now, the optimization is disabled.
https://github.com/eclipse/openj9/issues/9712 was opened to track the work to re-enable the optimization.
Unfortunately, the design of the option processing framework requires the disabling code to be in OMR (rather than OpenJ9) and guarded with J9_PROJECT_SPECIFIC.
> Disable regDepCopyRemoval when value types are enabled

- compiler/env/OMRObjectModel.hpp
- compiler/il/OMRBlock.cpp
- compiler/il/OMRBlock.hpp
- compiler/il/OMRNode.cpp
- compiler/optimizer/VPHandlers.cpp
In prototype support for value types, the `AASTORE` bytecode will throw a `NullPointerException` if the source operand is a null reference.  This checking will be performed under `ArrayStoreCHK`.  The `VPHandler` for `ArrayStoreCHK` needs to consider whether the source of the store could be a null reference and the component type of the array could be a value type - if so, the `ArrayStoreCHK` cannot be removed, so the necessary
checking can be performed.
In addition, `NullPointerException` needs to be recognized as an exception thrown by `ArrayStoreCHK` if value types are enabled.
> Consider value type arrays in VPHandler for ArrayStoreCHK

- omrmakefiles/rules.osx.mk
Previously the version was 0.0.0
> OSX libraries should have a version, set 1.0.0

- cmake/modules/OmrPlatform.cmake
- cmake/modules/OmrTargetSupport.cmake
Move omr_process_exports(), omr_add_exports() and,
omr_process_split_debug() to OmrTargetSupport.cmake as they don't really
belong with the platform config code.
> CMake: Move a number of functions to OmrTargetSupport.cmake

- doc/compiler/il/SymbolsSymrefsAliasing.md
Since we removed node aliasing in https://github.com/eclipse/omr/pull/3965 and changed the structure of  class `TR_AliasSetInterface` in https://github.com/eclipse/omr/pull/4624, update its documentation.
Closes: #4623
> Update documentation for class TR_AliasSetInterface

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
- compiler/arm/codegen/ARMDebug.cpp
- compiler/arm/codegen/ARMSystemLinkage.cpp
- compiler/arm/codegen/ARMSystemLinkage.hpp
- compiler/arm/codegen/OMRLinkage.cpp
- compiler/arm/codegen/OMRLinkage.hpp
- compiler/codegen/OMRLinkage.cpp
- compiler/codegen/OMRLinkage.hpp
- compiler/codegen/OMRLinkage_inlines.hpp
- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRLinkage.hpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/riscv/codegen/OMRLinkage.hpp
- compiler/riscv/codegen/RVSystemLinkage.cpp
- compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
- compiler/x/codegen/OMRLinkage.cpp
- compiler/x/codegen/OMRLinkage.hpp
- compiler/x/codegen/X86SystemLinkage.cpp
- compiler/x/i386/codegen/IA32SystemLinkage.cpp
- compiler/z/codegen/OMRLinkage.hpp
- compiler/z/codegen/SystemLinkageLinux.cpp
- compiler/z/codegen/SystemLinkagezOS.cpp
The `getOffsetToFirstParm` API currently belongs to linkage properties
class in each codegen, with the Z codegen being the exception having it
inside of the Z specific `OMRLinkage`. This API is however used
throughout all codegens and can belong to the common code `OMRLinkage`
class. We migrate the API there for use in downstream projects.
> Common getOffsetToFirstParm in the linkage class across codegens

- compiler/compile/CompilationException.hpp
The `UnsupportedValueTypeOperation` exception extended `CompilationException`, which meant that, if it was thrown, compilation would be aborted.  However, it should be considered a recoverable exception - if an unsupported operation is encountered during inlining, only the inlining of that particular method should be aborted while compilation of the outermost method continues.
Fixed this by having `UnsupportedValueTypeOperation` extend `RecoverableILGenException` instead.
> Make UnsupportedValueTypeOperation a recoverable exception

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
This commit changes generateCompareImmInstruction() to allow negative
constant.  Comparison with zero or positive constant (< 4096) uses
subsimm (cmpimm) instruction, and comparison with negative constant
(> -4096) uses addsimm (cmnimm) instruction.
> AArch64: Allow negative constant for generateCompareImmInstruction()

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit adds `is64bit` parameter to following functions:
- generateArithmeticShiftRightImmInstruction
- generateLogicalShiftRightImmInstruction
- generateLogicalShiftLeftImmInstruction
> AArch64: Add is64bit parameter to functions to generate shift instructions

- port/unix/omrsignal.c
**Control bits:** In the `unix` version of `omrsignal.c`, the control bits are
the four least significant bits (0xF). They are common/shared between
the port library signal flags. 
**`omrsig_set_async_signal_handler`:** allows multiple async handlers to be
registered against a port library signal flag.
**`omrsig_set_single_async_signal_handler`:** allows only one async handler to
be registered against a port library signal flag. It unregisters other
async handlers previously registered using
`omrsig_set_async_signal_handler`.
**`runHandlers`:** invokes all registered async handlers for a port library
signal flag if the corresponding operating system signal is raised.
**Issue:** Currently, `omrsig_set_single_async_signal_handler` unsets the
control bits while unregistering async handlers …
> Do not unset control bits while unregistering async handlers

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
Due to various reasons:
It never gave tangible performance benefit anyway. except for construed micro-benchmark scenario;
RHEL8 is buggy on TM. We don't want to see PMRs pouring in because of it. We already spent quite some resources on investigating weird crashes because of it (two PMRs and one internal performance testing).
Plus, TM is likely transforming into a totally new architecture on future POWER hardwares. POWER10 implementation is quite less ambitious.
Closes: #4231
> Disable TM by default on POWER

- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit renames functions in OMRLinkage.hpp and OMRLinkage.cpp for
AArch64, so that they are consistent with the functions in
ARM64PrivateLinkage.
> AArch64: Change OMRLinkage function names

- example/glue/EnvironmentDelegate.hpp
- example/glue/LanguageThreadLocalHeap.hpp
- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/TLHAllocationInterface.cpp
- gc/base/TLHAllocationSupport.cpp
- gc/base/TLHAllocationSupport.hpp
- gc/stats/AllocationStats.cpp
- gc/stats/AllocationStats.hpp
in order to sampling heap allocation bytes precisely without
compromising the performance, we have the below changes.
Handle instrumentableAllocateHook and
VM_OBJECT_ALLOCATE_WITHIN_THRESHOLD is still via disabling inline
allocation
Handle smapling for tracepoint is still during out of line allocation
Handle smapling for JEP331 is via setTLHSamplingTop(size)
Using fake Heap Top instead of fake Heap Alloc for disabling inline
allocation (realHeapAlloc-->realHeapTop,
set/getRealAlloc()-->set/getRealTop(), getRealSize(), getUsedSize())
Using fake Heap Top to force out of line allocation at sampling thresold
for sampling heap allocation (setTLHSamplingTop()/resetTLHSamplingTop())
setTLHSamplingTop(size) are only called in the below 3 cases
1, sampling threshold has been changed via GC-VM api …
> Sampling allocation bytes precisely without compromising the performance

- compiler/ras/LimitFile.cpp
Update comment to add more context that excluded methods are compiled when -Xjit:ifExcluded() option is specified
Issue #5243
Signed-off-by: Kishor Patil <patil@ca.ibm.com>
> Update comment when excluded methods are compiled

- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
This commit adds constructors with register dependencies for
ARM64CompareBranchInstruction.
> AArch64: Add register dependencies to ARM64CompareBranchInstruction

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/ras/Debug.hpp
This commit introduces 3 new instruction classes:
- ARM64Trg1ZeroSrc1Instruction
- ARM64ZeroSrc1ImmInstruction
- ARM64ZeroSrc2Instruction
These classes are used to handle alias instructions using the `xzr` register.
For example, `cmp` instruction is an alias of `subs` instruction with `xzr`
as target register.
The current implementation of helper functions for generating alias instructions
such as `generateCompareImmInstruction` allocates a virtual register
and associates it with `xzr` using register dependency.
Ths problem with this approach is:
- That register dependency interferes other register dependencies.
- Those helper functions cannot be used to generate instructions after
register assignment phase. (generating prologue/epilogue)
The new implementation of those helper functions …
> AArch64: Create new instruction classes to handle alias instructions

- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
addis and lis accept a signed 16 bit value as an immediate. They are passed
into generateTrg1Src1ImmInstruction as signed 32 bit values. In some edge
cases, the sign extension was not handled properly. In most cases this was due
to the value being incremented after sign extension. In other cases it was due
to an unnecessary mask clearing the upper 16 bits.
Also fixed an issue in inlineSimpleAtomicUpdate where the check for whether a
value stored as a signed 64 bit could fit in a signed 32 bit was incorrect.
Closes: #5212
> Fixed imm value for addis and lis

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
Fix `generateTestInstruction` to use `andsx`/`andsw`.
> AArch64: Fix generateTestInstruction to use andsx/andsw

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/ras/Debug.hpp
This commit implements ARM64Trg1Src2ZeroInstruction class so that we can
get rid of the register dependency on the zero register in generating
instructions for integer multiply.
> AArch64: Implement ARM64Trg1Src2ZeroInstruction

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit contains the following changes:
- Implement and use insertZeroRegister() functions in classes introduced
by #5280
- Remove the code for printing "cmp" from ARM64Trg1Src2Instruction
(It was moved to ARM64ZeroSrc2Instruction)
- Remove some trailing spaces
> AArch64: Implement insertZeroRegister() in some Instruction classes

- compiler/compile/OSRData.cpp
- compiler/compile/OSRData.hpp
Updated `OSRCompilationData::buildDefiningMap` to accept a `TR_Region` argument to be supplied.  As the validity of `DefiningMap`s is tied to the current state of the trees, it's likely that an optimization will want to build and then discard the `DefiningMap`s.  Also added an
`OSRCompilationData::clearDefiningMap` method to allow the client to discard the `DefiningMap`s once they are no longer needed.
To simplify this, the `OSRMethodData::getDefiningMap` method is no longer responsible for allocating its own `DefiningMap` - the processing in `OSRCompilationData::buildDefiningMap` is now responsible, and once built, the `DefiningMap` is added to `OSRMethodData` via a `setDefiningMap` method.
Also made `printMap` into a public method of `TR_OSRCompilationData`.
> Allow memory region to be supplied for building DefiningMaps

- compiler/il/OMRDataTypes.cpp
- compiler/il/OMRDataTypes.hpp
Add functions to get INF or -INF values of float/double.
There has been some previously defined hex values for max/min
float/double but cannot use it directly because the values are defined in
hex, e.g. [1]. The TR::getMax/MinFloat/Double functions reinterpret the hex
representations to their floating point values and return a floating
point type.
[1] https://github.com/eclipse/omr/blob/92e2fea39ad35c44d9d0c3428ea54118e4510d90/compiler/il/OMRDataTypes.hpp#L62
> Add TR::getMax/MinFloat/Double features

- gc/stats/LargeObjectAllocateStats.cpp
Clang emits a warning about change of value due to implicit conversion
from int to float.
> Fix warning in LargeObjectAllocateStats.cpp

- compiler/compile/OMRCompilation.hpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/IntegerMultiplyDecomposer.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Ops_inlines.hpp
Disabled the cpu related asserts for outOfProcessCompilations. These asserts are meant to only test the correctness of new APIs against old APIs for a single host processor and they fall apart when we introduce remote target processors into the picture.
> Disable cpu asserts for outOfProcessCompilations

- port/unix/omrsysinfo.c
Every other platform sets procInfoArray[0].online to
OMRPORT_PROCINFO_PROC_ONLINE. Index 0 is used for the total processor
information.
> get_processor_info OSX procInfoArray[0].online should be ONLINE

- doc/diagnostics/CallingConventions.md
This information was only available internally; this PR adds it to the repo to aid with debugging.
> Add Calling conventions Doc

- compiler/p/codegen/GenerateInstructions.cpp
- compiler/p/codegen/GenerateOMRInstructions.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRInstructionKindEnum.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCDebug.cpp
- compiler/p/codegen/PPCInstruction.cpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/p/codegen/PPCOpsDefines.hpp
- compiler/ras/Debug.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
Previously, lxvl and stxvl instructions were represented using Trg1Mem
and MemSrc1 instructions respectively. However, their RB registers did
not actually represent an index register but rather determined the
length of the load, so using TR::MemoryReference might cause issues due
to assumptions made about the index register. Instead, lxvl and stxvl
will now use Trg1Src2 and a new Src3 instruction class respectively.
> Change how lxvl/stxvl instructions are represented

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/control/OMROptions.cpp
This commit enables recompilation for AArch64.
Profiling is not supported yet.
> AArch64: Enable Recompilation

- .github/workflows/first-interaction.yml
- .github/workflows/labeler.yml
- .github/workflows/stale.yml
This prevents GitHub Actions from running on people's forks and every
so often the infrastructure will fail on the GitHub side and an Action
job will report as failed which results in an unnecessary notification
to the forked repo owner. We would like to avoid this, in addition to
wasted resources since these Actions are not meant to be ran on forks.
> Run GitHub Actions only on eclipse/omr repository

- compiler/compile/OSRData.cpp
Currently buildDefiningMap calls to read the first child of a node without
checking if the node has a first child. This change adds the simple check
to ensure the child exists.
> Guard OSR defining map first child access

- doc/diagnostics/CallingConventions.md
This commit adds sections for 32-bit Arm and AArch64 to CallingConventions.md.
> Add 32-bit Arm and AArch64 to CallingConventions.md

- compiler/p/codegen/OMRInstOpCode.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRInstruction.hpp
- compiler/p/codegen/PPCAOTRelocation.cpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/p/codegen/PPCOpsDefines.hpp
After the replacement of the vast majority of the Power binary encoder, small pieces were still left which are being removed in this PR. This includes the `updateImmediateField` method, which was previously used from relocation code and was keeping a large chunk of immediate-related code alive, as well as a number of now-useless flags that don't have any particular uses outside of binary encoding.
> Remove some remnants of the old Power binary encoder

- compiler/compile/OSRData.cpp
The buildDefniningMap code was dormant until recently. Two issues have been
found with the implementation: buildDefiningMap uses global new and
collectRegLoadStoreSymbolReferences calls getRegLoadStoreSymbolReference
without first checking the opcode of the node. This change addresses both
of these issues.
> Fix bugs in OSR buildDefiningMap

- compiler/aarch64/codegen/ARM64Instruction.hpp
This commit adds calls to setNeedsAOTRelocation() in the constructors
of ARM64RelocatableImmInstruction.
> Add calls to setNeedsAOTRelocation() in ARM64RelocatableImmInstruction

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit changes node->decReferenceCount() in AArch64 code to
cg->decReferenceCount(node).
> AArch64: Change calls to decReferenceCount()

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/RealRegisterEnum.hpp
This commit adds NULL register dependencies for volatile registers
x8-x18 in in ARM64SystemLinkage::buildArgs().
It also changes the use of x18 in ARM64SystemLinkage from
Preserved to Reserved, following AAPCS64.
> AArch64: Add NULL dependencies for volatile registers

- compiler/control/OMROptions.cpp
- compiler/env/OMRCPU.cpp
- compiler/env/OMRCPU.hpp
- compiler/env/OMRCompilerEnv.cpp
- compiler/env/OMRCompilerEnv.hpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/IntegerMultiplyDecomposer.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Ops_inlines.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
Introduce relocatableTarget environment to be used by the portable AOT feature.
Disable cpu tests for relocatable compilations (i.e. AOT). The cpu tests are used 
for testing the new api's against old api's on a single target processor. The tests 
become invalid when there are multiple targets.
Issue: #4518
> Create relocatableTarget environment for portable AOT

- port/unix/omrsysinfo.c
As per: https://github.com/eclipse/openj9/issues/7247
Direct access to `environ` on OSX should use `_NSGetEnviron`, as `environ` is only directly accessible via that environment
subroutine from shared libraries and bundles since Mac OS X 10.5 (Leopard).
This change likely does not fix the crash noted in the issue, but makes access to `environ` available from shared libraries and bundles.
---
`environ` is a list of strings that is made available when a process begins. Each string has the convention "name=value" which is set in the user environment.
`environ` can be directly accessed, except from shared libraries and bundles, since it is only available to the loader `ld` when a complete program is being linked. The environment routines `getenv`, `setenv` and `putenv` can be used to access …
> Use _NSGetEnviron() on OSX to retrieve environ

- compiler/il/OMRResolvedMethodSymbol.cpp
- compiler/il/OMRResolvedMethodSymbol.hpp
- compiler/optimizer/Inliner.cpp
These commits add the `OMR::ResolvedMethodSymbol::isParmVariant()` function that detects variant parameters (parameter slots who's value has been overwritten with something else).
In addition, this new function is used to prevent the inliner from using variant parameter symbols to derive call targets.
Fixes eclipse/openj9#8823
> Detect variant method parameters and prevent inliner from using their symbol type to get call targets

- compiler/control/OMROptions.cpp
Code that disables the `regDepCopyRemoval` optimization when value types are enabled for OpenJ9 was situated under the `else` branch of an `if` that checks `if (!optionSet)`.  In other words, the optimization was only disabled if there were JIT options to be processed.  Fixed by moving the code out of the `if-else`.
> Move code that disables RegDepCopyRemoval

- tools/tracegen/ArgParser.cpp
- tools/tracegen/FileUtils.cpp
- tools/tracegen/TDFTypes.hpp
- tools/tracemerge/DATMerge.cpp
Tools like `tracemerge` may encounter temporary files or directories created by other processes running in parallel that disappear almost immediately: failing to `stat()` such resources should not be fatal by default.
Fixes eclipse/openj9#9869.
> Add option '-statErrorsAreFatal'
