eclipse-omr/omr

compiler/optimizer/BackwardBitVectorAnalysis.cpp, compiler/optimizer/BitVectorAnalysis.cpp
This commit fixes some indentation issues and deletes unused code
in both bit vector analysis and backward bit vector analysis.
It also skips checking the same block as regular and
exception successor in bit vector analysis.
Signed-off-by: Vijay Sundaresan vijaysun@ca.ibm.com
=> Bit vector analysis code cleanup

compiler/README.md, doc/CxxInOmr.md
This is an old document that i've been keeping around for myself, and I figured it was about time to polish up and share with others. There is a good chance that there are some inaccuracies, but its a good starting point.
=> Document C++ features usable in OMR

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
Create the instruction kind for AArch64 exception generating instructions.
=> Add ARM64ExceptionInstruction kind

include_core/AtomicSupport.hpp, port/unix/omrcpu.c, util/omrutil/j9memclr.c
fixes https://github.com/eclipse/openj9/issues/6486
=> Replace PowerPC pragmata with inline assembler

compiler/z/codegen/OMRMemoryReference.cpp
The arraycopy codegen was not expecting a specific pattern
where the second aladd had a NULL address child and an lsub
integer child. Since the address child is NULL we use the
integer child as the base register, but the code for cleaning
up the folded lsub assumed the index register was used. A simple
fix which selects the appropriate register in the memref
handles this case.
Signed-off-by: Simon Hirst <shirst@ca.ibm.com>
=> Handle specific arraycopy case

compiler/ras/CallStack.cpp
Since #pragma mc_func and #pragma reg_killed_by are no longer supported on AIX, any functions defined in this manner have been replaced with equivalent inline assembly code.
Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>
=> Replace #pragmas mc_func and #reg_killed_by with gcc inline asm

compiler/aarch64/CMakeLists.txt, compiler/aarch64/codegen/OMRInstructionDelegate.cpp, compiler/aarch64/codegen/OMRInstructionDelegate.hpp, compiler/arm/codegen/OMRInstructionDelegate.cpp, compiler/arm/codegen/OMRInstructionDelegate.hpp, compiler/codegen/InstructionDelegate.hpp, compiler/codegen/OMRInstructionDelegate.hpp, compiler/p/CMakeLists.txt, compiler/p/codegen/OMRInstructionDelegate.cpp, compiler/p/codegen/OMRInstructionDelegate.hpp, compiler/x/CMakeLists.txt, compiler/x/codegen/OMRInstructionDelegate.cpp, compiler/x/codegen/OMRInstructionDelegate.hpp, compiler/z/CMakeLists.txt, compiler/z/codegen/OMRInstructionDelegate.cpp, compiler/z/codegen/OMRInstructionDelegate.hpp, fvtest/compilertest/build/files/target/arm.mk, fvtest/compilertest/build/files/target/p.mk, fvtest/compilertest/build/files/target/x.mk, fvtest/compilertest/build/files/target/z.mk, jitbuilder/build/files/target/aarch64.mk, jitbuilder/build/files/target/arm.mk, jitbuilder/build/files/target/p.mk, jitbuilder/build/files/target/x.mk, jitbuilder/build/files/target/z.mk
This is a skeleton implementation only and contains no static member
functions yet.
Issue #3778
=> Initial implementation of an InstructionDelegate hierarchy

compiler/aarch64/codegen/ARM64Debug.cpp
This change adds implementation of `TR_Debug::isBranchToTrampoline` for AArch64.
`TR_Debug::isBranchToTrampoline` will be used from debug print functions for snippets.
=> AArch64: Add implementation of TR_Debug::isBranchToTrampoline

fvtest/compilertriltest/ArithmeticTest.cpp
Fixes: #4258
Signed-off-by: Yuehan-Lin <Yuehan.Lin@ibm.com>
=> Used templated oracle function in Tril test

port/zos390/omrsl.c
Replace `dllqueryfn()`, `dllLoad()` and `dllfree()` with `dlsym()`, `dlopen()` and `dlclose()`
Fixes #2294
=> Replace deprecated DLL system calls

compiler/optimizer/LocalOpts.cpp
Closes: #4074 
Signed-off-by: Batyr Nuryyev <nuryyev@ualberta.ca>
=> Removed deprecated code in optimizer/LocalOpts.cpp

CMakeLists.txt, cmake/config.cmake, port/CMakeLists.txt
=> Enable CUDA support in cmake when available

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit adds implementation of
`TR::ARM64AdminInstruction::generateBinaryEncoding()`.
=> AArch64: Implement TR::ARM64AdminInstruction::generateBinaryEncoding()

include_core/omrport.h
it's already included at line 47
=> Remove redundant include of omrcuda.h

README.md
Move code of conduct from "What's the goal?" to "How Do I Interact With the Community?"
=> Move code of conduct in README.md

README.md
Move beginner issue information to a new section called "Contributing".
=> Delete "What's being worked on" section from README

port/common/omrcuda.cpp
In some (newer?) versions of the CUDA runtime, calling some functions (e.g. cudaSetDevice) with a bad deviceId returns 101 (CUresult CUDA_ERROR_INVALID_DEVICE) instead of 10 (cudaError_t cudaErrorInvalidDevice) as expected.
Avoid this problem by always checking the deviceId before making any device-specific calls.
=> Improve handling of invalid CUDA device identifiers

README.md
=> Small fixup to README.md

compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OpMemToMem.cpp
This fixes typo for word weird in two files
[skip ci]
=> Fixed two typos of word weird

CMakeLists.txt
=> Soften message when CUDA isn't supported

CMakeLists.txt
=> Revert "Soften message when CUDA isn't supported"

cmake/caches/Appveyor.cmake, cmake/caches/Travis.cmake, cmake/config.cmake
=> Disable DDR by default

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds `loadAddressConstantRelocatable` which is called
by `loadAddressConstant` when compiling relocatable code.
=> AArch64: Add function to load address constant for relocation

port/unix/omrfile.c
I noticed there is no way to distinguish EOF condition from error in
omrfile_read(). Return code 0 is replaced to -1 and reports as an error.
However an "errno" is not set by OS and not stored in Port Library data
so redundant error code might be received. Adding existing (but never
used) portable code OMRPORT_ERROR_FILE_EOF
to recognize EOF case. Use platform code 0 to get correspondent portable
error code. There is an alternative: there is a portable code
OMRPORT_ERROR_FILE_READ_NO_BYTES_READ is used for Windows already for
similar purpose.
=> Add EOF recognition to omrfile_read() for Unix

compiler/aarch64/runtime/VirtualGuardRuntime.cpp, compiler/runtime/OMRRuntimeAssumptions.cpp
This commit adds implementation of `_patchVirtualGuard` for
AArch64 environment.
=> AArch64: Implement _patchVirtualGuard

fvtest/tril/tril/tril.l, fvtest/tril/tril/tril.y
Fixes several warnings about implicit function declaration.
=> Add forward declarations for lexer functions

compiler/aarch64/codegen/OMRCodeGenerator.hpp
=> Add CodeGenerator getter/setter for returnTypeInfoInstruction

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/arm/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRLinkage.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
* Introduce a Linkage post binary encoding operation
* Add calls to linkage performPostBinaryEncoding in each doBinaryEncoding
=> Introduce a Linkage post binary encoding operation

compiler/aarch64/codegen/ARM64SystemLinkage.cpp, compiler/aarch64/codegen/ARM64SystemLinkage.hpp, compiler/arm/codegen/ARMSystemLinkage.cpp, compiler/arm/codegen/ARMSystemLinkage.hpp, compiler/codegen/OMRLinkage.hpp, compiler/p/codegen/PPCSystemLinkage.cpp, compiler/p/codegen/PPCSystemLinkage.hpp, compiler/x/codegen/X86SystemLinkage.cpp, compiler/x/codegen/X86SystemLinkage.hpp, compiler/z/codegen/SystemLinkage.cpp, compiler/z/codegen/SystemLinkage.hpp
* Define linkage API for inquiring about method entry address
* Provide System linkage implementations of entry point APIs
=> Define Linkage API for inquiring about method entry address

compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit adds the following changes to doBinaryEncoding() for
AArch64.
- Remove the loop that sets GC map overwriting existing GC map
- Call setPrePrologueSize() and setStaticAddress()
=> Add changes to doBinaryEncoding() for AArch64

include_core/AtomicSupport.hpp
The new `AtomicSupport::lockExchange` function is equivalent to a fetch
and store operation. A new value is stored at a memory location, and the
old value at the memory location is returned.
=> Add a function for the atomic exchange operation

compiler/z/codegen/ConstantDataSnippet.cpp
=> Add relocation record for TR_DataAddress in JITServer

compiler/z/codegen/S390Instruction.cpp
=> Create TR_MethodCallAddress relocation for resolved methods

gc/base/MemoryPoolLargeObjects.cpp
- Keep LOA size not smaller than minimum LOA size during
resizeLOA and resetLOA, expandWithRange, redistributeFreeMemory
to avoid potential crash on some	platforms.
- Add assertion check for the case.
=> Keep contracted LOA size not smaller than minimum LOA size

compiler/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/X86BinaryEncoding.cpp, compiler/z/codegen/OpMemToMem.cpp
=> Use FE query to add relocations for TR_HelperAddress

compiler/x/i386/codegen/OMRTreeEvaluator.cpp
=> Fix IA32PrivateLinkage static_cast typo

compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/S390Instruction.cpp, compiler/z/codegen/S390Peephole.cpp
Also collapse multiple blank lines into a single blank line (using `cat -s`).
=> Fix spelling of 'label'

compiler/il/OMRBlock.cpp
There was an issue with splitPostGRA where it was creating temp slot for the node which was either of Int8 or Int16 type. To maintain alignment, it needed conversion to Int32 type before storing it into memory. splitPostGRA was missing this conversion and which was causing issues on Z where it was storing a byte into memory without conversion and then loads a byte from that slot causing us to load most significant byte which contains 0 instead of the original value.
This commit adds the missing conversion piece of code for such nodes.
Fixes: eclipse/openj9#7275
Fixes: eclipse/openj9#7299
=> Fix missing conversion in splitPostGRA

compiler/codegen/CodeGenPrep.cpp, compiler/codegen/OMRCodeGenerator.cpp
Some code cleanup in tree lowering to make it easier to read and understand.
=> Miscellaneous clean up in tree lowering

compiler/aarch64/codegen/ControlFlowEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit adds implementation of igotoEvaluator.
=> AArch64: Implement igotoEvaluator

buildenv/jenkins/jobs/builds/Build-aix_ppc-64, buildenv/jenkins/jobs/pull-requests/PullRequest-aix_ppc-64
=> Make ccache treat omrcfg.h as a dependency for every object

util/pool/CMakeLists.txt
=> CMake: Make ddr scan j9pool.h

fvtest/tril/tril/parser.cpp
Fixes: #4524
Signed-off-by: Yuehan-Lin <Yuehan.Lin@ibm.com>
=> Used fgets to read file in parseFile

compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit adds code generation for madd and msub instructions to
iadd/ladd/isub/lsubEvaluators.
It also removes an unused function addOrSubInteger() from
BinaryEvaluator.cpp.
=> AArch64: Use madd and msub instructions when applicable

compiler/p/codegen/OMRCodeGenerator.cpp
=> Disable ResumableTraps when TR_DisableTraps option is set

gc/base/GCExtensionsBase.hpp
This update is required by eclipse/openj9#8254
Related to issue: #4703
=> Add arraylet double map request field

gc/base/ObjectModelBase.hpp, include_core/omrgcconsts.h
=> Move object meta data flag defines to omrgcconsts.h

compiler/optimizer/OMRCFGSimplifier.cpp
Currently the CFG Simplifier simplifyBooleanStore routine allows
simplification when both sides of an if are storing indirectly to
the same symref number. This change enhances the code to also allow
indirect stores where the store is done to an offset from the same
symref number on both sides.
=> Enhance CFGSimplifier simplifyBooleanStore

gc/base/GCExtensionsBase.hpp
For more information: https://github.com/eclipse/openj9/pull/5318
Related to issue: https://github.com/eclipse/openj9/issues/8349
=> Make double map true as default option 

gc/CMakeLists.txt
=> CMake: FIx typo in gc

compiler/z/codegen/OMRTreeEvaluator.cpp
There was a bug in helper function to generate optimized compare and branch instruction on IBM Z codegen. When one of the child of `ifacmp*` node is VFT Load from object which is treated specially on 64-Bit platform with compressed references and other child is loading value from a temp slot from Stack, evaluator was generating an instruction to compare only 4 bytes.
This is incorrect on 64-Bit platform as the address load from temp slot on the stack takes up 8 bytes in the memory. This commit fixes this issue by identifying such cases and setting up correct data type for the operation.
=> Fix generateS390CompareAndBranchOpsHelper

compiler/riscv/codegen/OMRInstruction.cpp, compiler/riscv/codegen/OMRInstruction.hpp, compiler/riscv/codegen/OMRMemoryReference.cpp, compiler/riscv/codegen/RVInstruction.cpp, compiler/riscv/codegen/RVInstruction.hpp
This PR contains various tiny improvements to RISC-V backend here and there.
=> Assorted improvements to RISC-V backend

compiler/ras/Debug.cpp
=> Fix debug print code for the newValue JIT helper

compiler/optimizer/LocalAnticipatability.cpp, compiler/optimizer/LocalTransparency.cpp
=> Clean up PRE trace msg

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
This commit implements lookupEvaluator() for AArch64.
=> AArch64: Implement lookupEvaluator()

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
* Provide options to specify generating a read-only code cache
* Set Compilation flag enabling read only code
=> Provide options to enable read-only code generation

configure, configure.ac, include_core/omrcfg.cmake.h.in, include_core/omrcfg.h.in, omrmakefiles/configure.mk.in
Config option is not referenced anywhere
=> Remove OMR_GC_HEAP_CARD_TABLE

fvtest/sigtest/sigTest.cpp
Allows for a consistent type of env, as setjmp uses a jmp_buff while
sigsetjmp uses a sigjmp_buff and the two are not necissarily convertible
=> Change setjmp to sigsetjmp

gc/stats/MarkStats.cpp, gc/stats/MarkStats.hpp
=> Move split array mark stats to OMR for metronome

compiler/optimizer/VPHandlers.cpp
`findSingleImplementer()` is already implemented in `PersistentCHTable`. Remove the one defined in OMR which didn't consider `enterHeuristicRegion` and could trigger the assert `SVM_ASSERT_ALREADY_VALIDATED` in `addVirtualMethodFromOffsetRecord()`.
(Thanks to @dsouzai for root-causing the assert.)
=> Remove the redundant implementation of findSingleImplementer

compiler/arm/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/compile/OMRCompilation.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
* Add CodeGenerator flag indicating support for recompilation
* Do not allocate recompilation info if recompilation not supported
=> Create and use CodeGenerator flag for recompilation support

include_core/omrport.h, port/common/omrport.c, port/common/omrport.tdf, port/common/omrsysinfo.c, port/omrportpriv.h, port/unix/omrsysinfo.c, port/win32/omrsysinfo.c
=> Add omrsysinfo_processor_set_feature API

compiler/x/codegen/OMRX86Instruction.hpp
While doing some archaeology on the purpose of an assert in the `X86VFPCallCleanupInstruction` class I uncovered a very articulate description of the motivation behind this instruction class that was not included in the code but I think it should be.  This PR surfaces that comment.
=> Add X86VFPCallCleanupInstruction comment

port/CMakeLists.txt
Also perform some cleanup of os if statments
=> CMake: Link port library with omrsig if OMRPORT_OMRSIG_SUPPORT enabled

compiler/x/codegen/BinaryEvaluator.cpp
The division by a constant optimization in the x86 backend does not work
for the MIN_INT/MIN_INT and MIN_LONG/MIN_LONG case.  Provide a special
sequence that does work for those boundary values.
Fixes: #4942
Fixes: #1482
=> Fix int/long division with MIN_INT/MIN_LONG divisors

compiler/x/codegen/OMRX86Instruction.cpp, compiler/x/codegen/OMRX86Instruction.hpp
Add additional APIs for:
* X86RegInstruction
* X86CallMemInstruction
=> Add additional X86 generate instruction functions

.appveyor.yml, buildenv/jenkins/jobs/builds/Build-win_x86-64, buildenv/jenkins/jobs/pull-requests/PullRequest-win_x86-64, fvtest/porttest/si.cpp
Fix porttest bug where Windows paths with / give false negatives
=> Fix sysinfo_test0 for Windows

compiler/env/OMRClassEnv.hpp
=> Add isClassValueType to ClassEnv query

gc/base/IndexableObjectScanner.hpp, gc/base/ObjectScanner.hpp
cc @rwy0717 @amicic @dmitripivkine
=> Add support for element iteration in IndexableScanner

compiler/ras/Debug.cpp
Opts marked as MustBeDone will always run. However, the optional
transformations should be omitted if the opt's opt index is not in the
range specified by firstOptIndex and lastOptIndex.
=> Omit optional transformations in an opt marked as MustBeDone

port/common/omrmem32helpers.c
=> Add missing parentheses

buildenv/jenkins/README.md
=> Update Jenkins README with instructions for configuring jobs

compiler/optimizer/Inliner.cpp
findAndUpdateCallSiteInGraph maps the callNode generated in actual ilgen
to a callsite created when doing estimate code size baseed on byte code
info. There is a potential problem if there are more than one callNode at
the same byte code index. For now, we always choose to inline the first
callNode with matching byte code info.
This change also changes the location of the trace message
"before findAndUpdateCallSiteInGraph" so that it actually appears
before the callsite gets updated.
=> Don't overwrite the _callNode of a mapped callsite

port/common/omrcuda.cpp
CUDA 10.2 was released in November, 2019.
=> Add support for CUDA version 10.2

port/linux/omrvmem.c
=> Fix undeclared macro MAP_HUGETLB

compiler/optimizer/OMRSimplifierHandlers.cpp
This adds a simplification to a pattern of trees which will be later generated by an optimization in openj9. The code was originally authored by @andrewcraik and was refined by me.
This code further simplifies a pattern of trees that will be generated by the optimization in this PR: https://github.com/eclipse/openj9/pull/8780
This PR should be merged before the openj9 PR so that the openj9 changes can have the maximum benefit to performance.
There are 2 stages in this new simplification:
1. The first stage simplifies comparison nodes where one child is a constant
and the other is a tree of select nodes with constant leaves.
The constant is compared to the leaves of the select node(s) and the values
of these leaves are replaced by zero or one depending on the result of the
comparison.
2. …
=> Enhance simplifier to simplify comparison between a constant and a tree of select nodes

fvtest/porttest/CMakeLists.txt
=> CMake: Add missing exports to sltestlib

cmake/modules/OmrUtility.cmake
=> CMake: Add omr_count_true utility

port/unix/omrsysinfo.c
Signed-off-by: gaoli <gaolibj@cn.ibm.com>
=> Add IBM i specific definition

port/unix/omrsysinfo.c
=> Add support for finding executable name on bsd

port/unix/omrsysinfo.c
=> Simplify control flow in omrsysinfo_get/set_limit

port/aix/omrvmem.c
Signed-off-by: gaoli <gaolibj@cn.ibm.com>
=> Add IBM i specific flags to support the build.

omrmakefiles/rules.aix.mk
Signed-off-by: gaoli <gaolibj@cn.ibm.com>
=> Add IBM i specific flags to support build

port/unix/omriconvhelpers.c
=> Explicity state endianess of UTF-16 encoding

compiler/env/OMRCompilerEnv.cpp, compiler/env/OMREnvironment.hpp, compiler/env/defines.h, compiler/ras/IgnoreLocale.hpp, compiler/x/codegen/OMRCodeGenerator.cpp
=> Add initial BSD support to the compiler

tools/hookgen/makefile
Signed-off-by: gaoli <gaolibj@cn.ibm.com>
=> Add IBM i specific change to support the build.

compiler/aarch64/codegen/OMRRegisterDependency.cpp
This commit implements one of constructors of `RegisterDepencyConditions`
used to handle `GlRegDeps`.
=> AArch64: Implement constructor of RegisterDependencyConditions for GlRegDeps

doc/compiler/optimizer/ValuePropagation.md
Use the transcription and outline in #4927 to fully document how the
Value Propagation optimization works at a high level, giving details
and references to the code where needed.
Special thanks to @vijaysun-omr for describing the optimization is such
great detail which enabled this document to be written.
[skip ci]
Closes: #4927
=> Document the Value Propagation optimization

gc/base/Collector.cpp, gc/base/Collector.hpp, gc/base/GlobalCollector.hpp, gc/base/standard/ConcurrentGC.cpp, gc/base/standard/ConcurrentGC.hpp
=> Revert "Collector STW flag"

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
=> Clean up DecimalFormatPeephole

cmake/modules/OmrCompilerSupport.cmake, cmake/modules/OmrTargetSupport.cmake
See individual commits for details
=> Update create_omr_compiler_library to use omr_add_library

compiler/il/OMRDataTypes.hpp, compiler/il/OMRDataTypes_inlines.hpp
Add function to also check if the datatype is of float type.
This function is needed in https://github.com/eclipse/omr/issues/5057, however I think this function can also help in any other issue that involves `float` type.
=> Add DataType::isFloat()

compiler/z/codegen/SystemLinkageLinux.cpp, compiler/z/codegen/SystemLinkagezOS.cpp
Fixes: #4447
Signed-off-by: Michael Wang <mw918@hotmail.com>
=> Remove redundant calls to self() in Z classes with TR:Linkage

compiler/x/codegen/OMRLinkage.hpp
Closes: #5171
Signed-off-by: Isha Bhatt <ibhatt@umich.edu>
=> Fix qualified name enum warnings in OMRLinkage.hpp

fvtest/porttest/CMakeLists.txt
=> CMake: Add exports to aixbaddep

compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.hpp, compiler/z/codegen/S390GenerateInstructions.cpp
Closes: #5140
Signed-off-by: Austin Wells <austin.wells@mail.utoronto.ca>
=> Remove CodeGenerator param from createConstantInstruction

.github/labeler.yml, .github/workflows/first-interaction.yml, .github/workflows/labeler.yml, .github/workflows/stale.yml
Adds three GitHub Actions to the OMR project described in #5088. See #5088 for full details and examples.
=> Add GitHub Actions to the OMR project

compiler/optimizer/Structure.cpp
Original recursive findCycle implementation renamed to findCycleDEPRECATED
and put behind the TR_UseOldFindCycle environment variable.
New iterative implementation of findCycle is now used by default. The new
implementation no longer has the stack overflow problem that the original
recursive findCycle implementation had when compiling very large methods.
Closes: #5220
=> New iterative implementation of findCycle

gc/stats/ScavengerCopyScanRatio.hpp
Proper fix for compiler warning treated as error (potential loss of data) from using a mix of different size types.
(https://github.com/eclipse/openj9/pull/8626/files)
Change MM_ScavengerCopyScanRatio::UpdateHistory::updates
from uint64_t to uintptr_t.
This modification eliminates the need to cast in:
openj9/runtime/gc_trace/TgcParallel.cpp
Signed-off-by: Enson <enson.guo@ibm.com>
=> Change type of variable `updates` 

compiler/env/OMRCPU.cpp, compiler/env/OMRCPU.hpp, compiler/il/Aliases.cpp, compiler/x/env/OMRCPU.cpp, compiler/z/codegen/BinaryAnalyser.cpp, compiler/z/codegen/BinaryCommutativeAnalyser.cpp, compiler/z/codegen/BinaryEvaluator.cpp, compiler/z/codegen/ControlFlowEvaluator.cpp, compiler/z/codegen/FPTreeEvaluator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OpMemToMem.cpp, compiler/z/codegen/S390GenerateInstructions.cpp, compiler/z/codegen/TranslateEvaluator.cpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp
=> Replace CPU APIs on Z

compiler/control/OMROptions.cpp, compiler/optimizer/LoadExtensions.cpp, compiler/optimizer/OMROptimizations.enum
=> Add option to disable load extensions

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstructionKindEnum.hpp, compiler/ras/Debug.hpp
This commit adds ARM64RelocatableImmInstruction.
=> AArch64: Add ARM64RelocatableImmInstruction

compiler/il/OMRILOps.hpp
=> Add brief documentation for isTreeTop query

gc/base/standard/ParallelGlobalGC.cpp
Prefer expanding Tenure space while still can over doing a compact.
=> Micro-fragmentation trigger only on fully expanded heap

cmake/modules/ddr/GenerateStub.cmake
- Error out if the input file does not exist
- Remove timeout on grep. If the input file exists, grep should not time
out unless something is very wrong. If the timeout was kept, it would be
hard to distinguish between a timeout and grep not fining a match
- Bump timeout of awk script to 10 seconds.
- Properly handle errors from awk script
=> CMake: tweak ddr stub generation

compiler/optimizer/LiveVariableInformation.cpp
Both of these bitvectors are initialized using the default constructor
and are only queried via the `IsZero` API and are never set. Thus the
code being guarded by queries to these bitvectors is dead and can be
removed to simplify the implementation.
=> Deprecate unused indirectMethodMetaUses and regStarAsmUses bitvectors

doc/diagnostics/CallingConventions.md
=> RISC-V: document calling convention

gc/verbose/VerboseHandlerOutput.cpp
Report h/w assistance on ZOS too, not just zLinux
=> Concurrent Scavenge VGC initialize stanza

doc/compiler/optimizer/DataFlowEngine.md
Use the transcription and outline in #5283 to fully document how the
Data-Flow Engine works at a high level, giving details and references
to the code where needed.
Special thanks to @vijaysun-omr for describing the data-flow engine in
such great detail which enabled this document to be written.
[skip ci]
Closes: #5283
=> Document the Data-Flow Engine

gc/base/standard/Scavenger.cpp
1) Implement one more null check after thread entering the monitor to avoid
unnecessary resize cache pool if pool has been resized by other threads
entered the monitor before current thread.
2) Remove pool resize after Tenure Expansion
Copy-cache pool size should be a function of Nursery size, not Tenure size. Removing resizing from `collectorExpanded()` avoid unnecessary pool expansions.
3) Rename varialbe result => resizePerformed for readability.
=> Eliminate unnecessary cache pool resize

buildenv/jenkins/omrbuild.groovy
- Also use reference repository to speed up clones. This will
not fail if the dir does not exist.
- Set default location to $HOME/gitcache. Set
blank for zos as it is not supported.
=> Increase Git timeout to 30 minutes

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
=> Use new cpu api for power10

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
Use CBZ/CBNZ instructions in ificmpHelper function
This commit uses CBZ/CBNZ instructions in ificmpHelper function when cc
is TR::CC_EQ or TR::CC_NE and second child of the node is a constant
zero.
Fixes: #3364
Signed-off-by: Md. Ariful Haque <mhaque5@unb.ca>
=> Use CBZ/CBNZ instructions in ificmpHelper function

compiler/codegen/OMRCodeGenerator.hpp
=> Add method to reset SupportsArrayTranslateTRxx flag

compiler/z/codegen/OMRInstruction.cpp
=> Remove deprecated and unreachable isInternalControlFlowOneEntryOneExit

compiler/z/codegen/OMRTreeEvaluator.cpp
=> Improve relocation record checks inside genLoadLongConstant

compiler/aarch64/codegen/ARM64Debug.cpp
This commit adds support for printing FMOV (imm) instructions in
ARM64Debug.cpp.  The instructions use a special 8-bit format for
representing floating point values.
=> AArch64: Print FMOV (imm) instructions in ARM64Debug.cpp

gc/CMakeLists.txt, gc/base/MainGCThread.cpp, gc/base/MainGCThread.hpp, gc/base/standard/Scavenger.hpp
Merge to be coordinated with: https://github.com/eclipse/openj9/pull/10139
Related to: https://github.com/eclipse/openj9/issues/10071
I'm starting with renaming files since this is a refactor, name replacements for master will come in a later pr to make it easier to review.
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
=> Rename MasterGCThread files to MainGCThread

example/glue/MarkingDelegate.hpp, gc/base/MarkingScheme.cpp, gc/base/MarkingScheme.hpp
=> Add base setupPointerArrayScanner() implementation

gc/base/Dispatcher.hpp, gc/base/GCExtensionsBase.hpp, gc/base/ParallelDispatcher.cpp, gc/base/ParallelDispatcher.hpp
This reverts commit 298eb34aa69f3102d7c95c0e8e557dd263cfcd1e given https://github.com/eclipse/openj9/issues/10171
=> Revert "Dispatcher Rework: Thread Selection & Hybrid Notification"

include_core/omrutil.h, util/omrutil/CMakeLists.txt, util/omrutil/omrcrc32.c, util/omrutil/util.tdf, util/omrutil/wildcard.c
This commit is in support of the refactored OpenJ9 shared cache into OMR.
Issue: #4610
Signed-off-by: Mark Thom <mark.thom@unb.ca>
=> Merge wildcard and CRC32 routines from OpenJ9 into omrutil

port/common/omrport.tdf, port/common/omrsysinfo.c
Address the issues in PR https://github.com/eclipse/omr/pull/5403
=> Fix tracepoint and declaration for omrsysinfo_get_processor_feature_name

compiler/il/OMRBlock.cpp
In Post GRA Block splitter, there was a bug where for nodes of BCD type, it was trying to find a global register and in attempt to do so, was hitting a FATAL_ASSERT. Uncommoning of such nodes should be done using temp slots with symbol reference containing the correct precision and length information. This commit removes the FATAL_ASSERT and adds code to handle such cases.
=> Fix bug in postGRA block splitter

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds TR_ARM64ScratchRegisterManager.
=> AArch64: Implement TR_ARM64ScratchRegisterManager

compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit adds implementation for indirect load/store of local object
in `OMRMemoryReference` class.
=> AArch64: Handle indirect load/store of local object in memory reference

compiler/il/OMRIL.cpp, compiler/il/OMRIL.hpp
The APIs are needed for a PRE fix.
=> Add opCodeForCorresponding APIs for load/store

port/unix/omrsock.c
- Wrong error code was returned from omrsock_poll. Fixed that to return
the correct errno error.
=> Fixed error code returned from omrsock_poll

port/unix/omrsock.c
- poll returns when system is full.
=> Fix system full potential segmentation problem

buildenv/jenkins/omrbuild.groovy, buildenv/jenkins/refRepoUpdater.groovy
- Updates all reference repos on all slaves
- Excludes master, proxy and zOS since they don't work
Related #5195
[skip ci]
=> Add reference repo updater pipeline

CODEOWNERS
=> Add Ben Thomas as Power code owner

doc/port/sockets.md
- Added a simple Linux to omrsock API comparison
=> Added documentation for omrsock API

cmake/modules/FindDiaSDK.cmake
Cygwin builds of CMake aren't able to use get_filename_component() to read
from the registry. If we are using a Cygwin build of CMake, instead use
regtool which is provided by cygwin.
=> CMake: update DIA registry search handling

cmake/modules/OmrMsvcRuntime.cmake
=> CMake: Fix msvc library detection for RelWithDebInfo

port/common/omrport.tdf
Additions for #4752 should have been at the end of the file.
=> Relocate additions for omrshmem at the end of the file

compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp
=> Remove old processor detection code

gc/base/ParallelDispatcher.cpp
For background see https://github.com/eclipse/openj9/issues/10491#issuecomment-686057277
- Existing assert expanded in `MM_ParallelDispatcher::workerEntryPoint` to cover task dispatch during shutdown
- Asserting more strictly with new assert in added else clause
Fixes: eclipse/openj9#10491
=> Expand Dispatcher Wait Loop Exit Assert

compiler/x/codegen/X86BinaryEncoding.cpp
=> Calls to labels do not require trampolines

compiler/riscv/codegen/FPTreeEvaluator.cpp, compiler/riscv/codegen/TreeEvaluatorTable.hpp
=> RISC-V: implement fcmpl, fcmpg, dcmpl and dcmpg

compiler/optimizer/RegDepCopyRemoval.cpp
Fix the assert added in RegDepCopyRemoval to consider missing case where child of GlRegDeps is PassThrough with the regLoad child and both uses same register.
Fixes: eclipse/openj9#10630
=>  Fix the ASSERT in RegDepCopyRemoval

port/unix/omrsysinfo.c
=> Print s390 processor feature name

port/unix/omrsysinfo.c
=> Print ppc processor feature name

compiler/aarch64/codegen/OMRRegisterDependency.hpp
Add variant of `stopUsingDepRegs` method to the register dependency class.
The method takes iterators to the list of registers as arguments.
The list contains registers we do not want to kill.
=> AArch64: Add another method to kill temporary registers added to register dependency

compiler/optimizer/OMRCFGSimplifier.cpp
Transforming stores of internal pointers can cause the gc map to be incorrect.
=> Prevent cfg simplification from transforming stores of internal pointers

compiler/arm/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/optimizer/RegisterCandidate.cpp, compiler/x/codegen/OMRCodeGenerator.cpp
x87 floating point is deprecated.
* Rename CodeGenerator disableFpGRA to disableFloatingPointGRA
* Disable x87 floating point GRA
=> Disable x87 floating point GRA

compiler/arm/codegen/ARMBinaryEncoding.cpp, compiler/compile/OMRCompilation.cpp, compiler/p/codegen/OMRInstruction.cpp, compiler/p/codegen/PPCDebug.cpp, compiler/z/codegen/S390Instruction.cpp
=> Use entryPointFromCompiledMethod linkage API for recursive calls

fvtest/porttest/omrsockTest.cpp
Adjust logic to make less assumptions about socket implementation,
and more tolerant of unexpected conditions.
=> Make PortSockTest::poll_functionality_many_sockets more robust

compiler/optimizer/LoopCanonicalizer.cpp
Improve selection criteria for IndVarEliminination
Add post dominance check for primary induction variable(PIV) and derived
induction variable(DIV) to improve selection criteria for
`redundantInductionVarElimination` optimization.
Previously when checking whether or not to replace a DIV with PIV one
of the things we did was count the number of increments. We replaced DIV
with PIV only if both had equal number of increments. However, when
counting the increments we did not check if those increments were in the
same block. Because of this we would sometimes replace a DIV even if it
was in a different block than the PIV it was being replaced with. This
resulted in addition of extra add and load instructions to compensate
for the  different block locations. Addition of those extra add and …
=> Improve selection criteria for IndVarEliminination

doc/compiler/runtime/ELFGenerator.md
Signed-off-by: Dan Heidinga <heidinga@redhat.com>
=> Correct "Elf Hello World Tutorial" link

port/common/omrcuda.cpp
CUDA 11.1 was released in September, 2020.
=> Add support for CUDA version 11.1

compiler/optimizer/Inliner.cpp
=> Only unset argInfo if value changes

port/osx/omrvmem.c
Attempting to allocate 2M pages with a memory range would take a very long time before failing. 
Fixed up the code a little at the same time. The changes don't look so big if you ignore whitespace.
=> Return quickly on OSX when 2M pages cannot be allocated

compiler/p/codegen/OMRTreeEvaluator.cpp
The `patchRequestors()` function asserts relative instruction addresses for fixedSeqMemAccess which fails when a spill is performed in the middle of the sequence. 
Also, technically speaking the asserts also ensure the order of the instructions in the sequence but given that the patches are done by instruction pointers and not having a scheduler reordering instructions, and after checking with @zl-wang, its safe to just remove the current asserts.
EDIT: Given that the first fix keeps AOT vulnerable, new fix using NoReg dependency is used instead.
Resolve eclipse/openj9#11163
=> Add NoReg dependency for fixedSeqMemAccess to make it spill safe

compiler/infra/BitVector.hpp
Added methods for (de-)serialization of TR_BitVector.
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>
=> Add support for serialization of TR_BitVector

compiler/optimizer/CMakeLists.txt, compiler/optimizer/abstractinterpreter/AbsOpArray.cpp, compiler/optimizer/abstractinterpreter/AbsOpArray.hpp, compiler/optimizer/abstractinterpreter/AbsOpStack.cpp, compiler/optimizer/abstractinterpreter/AbsOpStack.hpp, compiler/optimizer/abstractinterpreter/AbsValue.cpp, compiler/optimizer/abstractinterpreter/AbsValue.hpp, doc/compiler/optimizer/BenefitInliner.md, fvtest/compilerunittest/CMakeLists.txt, fvtest/compilerunittest/CodeGenTest.hpp, fvtest/compilerunittest/CompilerUnitTest.hpp, fvtest/compilerunittest/abstractinterpreter/AbsInterpreterTest.cpp, fvtest/compilerunittest/abstractinterpreter/AbsInterpreterTest.hpp
Issue: https://github.com/eclipse/omr/issues/5488
=> BenefitInliner phase 1/3: Basic classes for performing abstract interpretation

cmake/modules/OmrCompilerSupport.cmake, compiler/env/Processors.hpp, compiler/riscv/codegen/OMRCodeGenerator.hpp, compiler/riscv/codegen/OMRLinkage.cpp, compiler/riscv/codegen/OMRLinkage.hpp, compiler/riscv/codegen/RVSystemLinkage.cpp, compiler/riscv/env/RVProcessorEnum.hpp
This PR adds a few changes here and there required by OpenJ9 JIT component
=> RISC-V: assorted changes for OpenJ9 JIT

include_core/omrport.h, port/common/omrsysinfo.c, port/omrportpriv.h, port/unix/omrsysinfo.c, port/win32/omrsysinfo.c
=> Remove newline in omrsysinfo_get_processor_feature_string

compiler/ras/CallStack.cpp
=> Fix invalid OMR format specifier on Win32

compiler/p/codegen/OMRMachine.cpp, compiler/p/codegen/OMRMachine.hpp, compiler/x/codegen/OMRMachine.cpp, compiler/x/codegen/OMRMachine.hpp
* on X86 and Power: cloneRegisterFile
* on Power: cloneRegisterFileByType
=> Remove unused Machine class functionality

compiler/z/codegen/OMRTreeEvaluator.cpp
=> Add recompCounter relocation in generateLoad32BitConstant

compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/env/TRMemory.cpp, compiler/env/TRMemory.hpp, compiler/objectfmt/FunctionCallData.hpp, compiler/objectfmt/JitCodeRWXObjectFormat.hpp, compiler/objectfmt/JitCodeRXObjectFormat.hpp, compiler/objectfmt/OMRFunctionCallData.hpp, compiler/objectfmt/OMRJitCodeRWXObjectFormat.hpp, compiler/objectfmt/OMRJitCodeRXObjectFormat.hpp, compiler/objectfmt/OMRObjectFormat.hpp, compiler/objectfmt/ObjectFormat.hpp, compiler/x/CMakeLists.txt, compiler/x/amd64/objectfmt/OMRJitCodeRWXObjectFormat.cpp, compiler/x/amd64/objectfmt/OMRJitCodeRWXObjectFormat.hpp, compiler/x/amd64/objectfmt/OMRJitCodeRXObjectFormat.cpp, compiler/x/amd64/objectfmt/OMRJitCodeRXObjectFormat.hpp, compiler/x/objectfmt/FunctionCallData.hpp, compiler/x/objectfmt/OMRFunctionCallData.hpp, compiler/x/objectfmt/OMRJitCodeRWXObjectFormat.hpp, compiler/x/objectfmt/OMRJitCodeRXObjectFormat.hpp, fvtest/compilertest/build/files/target/amd64.mk, jitbuilder/build/files/target/amd64.mk
* Initial ObjectFormat and FunctionCallData definitions
* Create X86 specialization of FunctionCallData
* Initial AMD64 implementation of JitCodeRWXObjectFormat
* Initial AMD64 implementation of JitCodeRXObjectFormat
Issue: #5569
=> Initial ObjectFormat implementation

compiler/optimizer/LocalAnalysis.cpp
In `hasOldExpressionOnRhs()`, we temporarily change wrtbar to aloadi
for the syntactic comparison in `areSyntacticallyEquivalent()`.
When it’s an indirect store, the number of children of the node is
set to 1, otherwise 0. Because the check on whether not the node
is an indirect store happens after the wrtbar node is recreated as aloadi,
`node->getOpCode().isStoreIndirect()` is false for aloadi, and the
number of children for wrtbar node ends up as 0. It prevents
`areSyntacticallyEquivalent()` from comparing the first child of the two
nodes. It concludes that different expressions as the same.
The fix is to check if it’s an indirect store from the original node.
Fixes eclipse/openj9#11569
=> Fix the check on isStoreIndirect in LocalAnalysis

compiler/optimizer/PrefetchInsertion.cpp
Disallow prefetch insertion when read barriers are necessary because
this optimization may insert loads of array elements past the 0th
element for a backwards traversal. That is, if the primary induction
variable is traversing the array backwards, on the last iteration of
the loop we will be prefetching the (i - 1)th element of the array.
Since the prefetch needs to load such an element, we must ensure the
read barrier will not trigger on such a value which may "look like" an
object. For example today, the (i - 1)th element is really the last
word of the array header, which is the `dataAddr` pointer which looks
like an object, but it is not. Thus the read barrier may incorrectly
trigger on such a value.
In theory the same issue can happen on a forward traversal since there
may be padding …
=> Disallow prefetch insertion when read barriers are necessary

gc/base/standard/Scavenger.cpp
Implemented fix to allow gencon to work with flattened arrays.
Currently does not support partitioning for multithreaded scanning
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
=> Fix gencon to work with flattened arrays

doc/compiler/il/IntroToTrees.md
* fix the expression being used in the IL example
* provide a clearer ASCII diagram for IL example
* fix minor typos
=> Fix errors in IL documentation

compiler/x/codegen/OMRRegisterDependency.cpp, compiler/x/codegen/OMRRegisterDependency.hpp, compiler/x/codegen/OMRRegisterDependencyStruct.hpp
* Remove x87 code from RegisterDependency constructor
* Remove and fold code consuming x87 GlobalRegisterFPDependency property
* Remove x87 GlobalRegisterFPDependency regdep property
=> Remove x87 global register support from RegisterDependency

ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
`dwarfdump-classic` is an old tool that has not been updated to support current versions of clang on macOS. We don't need to recognize the DWARF version 5 concepts used by newer compilers, we can just ignore them.
See eclipse/openj9#11834.
=> Create a DIE for a tag that dwarfdump-classic doesn't understand

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit changes commonStoreEvaluator to generate memory barrier
if the symbol of the node is `Shadow` and `Ordered`.
The logic for deciding whether memory barrier is generated or not
is borrowed from ppc codegen.
=> AArch64: Generate memory barrier for store if symbol is shadow and ordered

fvtest/compilertriltest/JitTest.hpp, fvtest/compilertriltest/TypeConversionTest.cpp
This commit implements Tril test cases for ibits2f, etc.
=> Tril tests for ibits2f, etc.

compiler/codegen/Relocation.cpp, compiler/runtime/Runtime.hpp
Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>
=> Add relo type for a pointer to an inlined method

compiler/optimizer/OMROptimizer.hpp
Signed-off-by: Tao Guan <jamesgua@ca.ibm.com>
=> Make Optimizer self() function protected

compiler/control/OMROptions.cpp
=> Add useful comment for disableGuardedCountingRecompilation option

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/cs2/allocator.h, compiler/il/NodePool.cpp, compiler/il/NodePool.hpp, compiler/il/OMRLabelSymbol.cpp, compiler/optimizer/OMROptimizer.cpp, compiler/optimizer/UseDefInfo.cpp, compiler/optimizer/UseDefInfo.hpp
* Remove allocator name fields
* Remove unused arena allocator factory function for LabelSymbol
* Remove unused allocator parameter from NodePool constructor
=> Misc. allocator cleanup

example/glue/ArrayletObjectModel.hpp, gc/base/EnvironmentBase.hpp, gc/base/standard/CompactScheme.cpp, gc/base/standard/CompactScheme.hpp, gc/base/standard/Scavenger.cpp, gc/base/standard/Scavenger.hpp
Reverts eclipse/omr#5795
See https://github.com/eclipse/openj9/issues/12110 and https://github.com/eclipse/openj9/issues/12110#issuecomment-790098433
=> Revert "Update dataAddr whenever GC moves indexable object"

compiler/cs2/allocator.h, compiler/env/TRMemory.hpp
=> Remove unused stats collection functions from CS2 allocators

omrtrace/omrtracecomponent.cpp
Remove an inappropriate use of `atof()` in favour of locale-independent parsing of the tracepoint data file.
See also eclipse/openj9#12009 and eclipse/openj9#12092.
=> Fix reading of version from tracepoint data files

compiler/aarch64/codegen/BinaryEvaluator.cpp
Avoid reusing source register when node is `aladd` because the target register
can contain an internal pointer. Exception is when the source register
also conatins an internal pointer and has the same pinning array pointer
as the node.
=> AArch64: Fix genericBinaryEvaluator for internal pointer case

CONTRIBUTING.md, README.md, doc/GitCrashCourse.md
=> Rename 'beginner' label to 'good first issue'

cmake/modules/ddr/DDRSetStub.cmake.in
Add `-nologo` option for MSVC compiler.
=> Suppress MSVC version banner

gc/base/standard/ConcurrentGC.cpp
When transitioning from tracing only state to tracing and card cleaning
state, account that pre-calculated remaining free memory for card
cleaning kickoff threshold should be higher if global kickoff was due to
reasons other than low free memory such a language specific kickoff
(class unloading).
The adjustment for card cleaning kickoff threshold is exactly the same
as the difference between actual free memory at the time of global
kickoff and expected free memory global kickoff threshold.
Without the adjustment, card cleaning and any other states after (most
importantly final STW phase where we reclaim memory) are delayed till
(incorrectly very low) pre-calculated card cleaning threshold is met,
effectively negating any efforts of the early language specific kickoff.
Signed-off-by: …
=> Adjust cardCleaningThreshold for language specific kickoff

gc/base/MemorySubSpace.cpp
This helps avoid unnecessary (duplicate) Global GC in case one thread is
triggering final STW step of Concurrent global (due to exhausted
concurrent work),and another thread triggering Scavenge that ends up
percolating to Global.
=> Increment Exclusive count for percolate Global

cmake/modules/ddr/GenerateStub.cmake
There's no need to remove a file that's about to be overwritten.
=> Remove redundant file removal

port/win32/omrsysinfo.c
=> Allocate correct buffer size in omrsysinfo_get_OS_type()

port/win32/omrsysinfo.c
If _WIN32_WINNT_WIN10 isn't defined, which it isn't for VS2013, use
deprected GetVersionEx() to detect Windows 10.
Issue https://github.com/eclipse/openj9/issues/12260
=> Better detection of Windows 10 in omrsysinfo_get_OS_type()

compiler/riscv/codegen/OMRLinkage.cpp, compiler/riscv/codegen/OMRLinkage.hpp
This code is basically a copy from AArch64.
=> RISC-V: implement copyParametersToHomeLocation()

doc/compiler/il/GlRegDeps.md
This note captures the concepts of mainline code,
out of line code, and `GlRegDeps` that Vijay
explained in a meeting.
Co-authored-by: Vijay Sundaresan <vijaysun@ca.ibm.com>
=> Add notes on GlRegDeps

compiler/x/codegen/OMRLinkage.hpp, compiler/x/codegen/X86LinkageProperties.hpp
Signed-off-by: Harpreet Kaur <hkaur3@unb.ca>
=> Separate OMR x86 linkage properties from linkage class

gc/base/standard/ConcurrentGC.cpp
The trigger point of the end of final STW increment of concurrent global
GC event was mistakenly removed as part of VGC re-org, believing that
Verbose GC was the only user of. However, global GC scheduling and
compact heuristics indirectly also relied on it.
See: https://github.com/eclipse/omr/pull/5688
=> Restore concurrent end trigger

compiler/optimizer/OMROptimizer_inlines.hpp
This is prior step for #5880 completion
=> Dummy OMROptimizer_inlines.hpp header added

compiler/p/codegen/OMRTreeEvaluator.cpp
P10 uses paadi in conjuction with lxvdsx for vsplats. The opcode
paddi requires a GPR for correct address calculation as lxvdsx
uses GPR for loading the data. The passed register for
loadfloatConstant can be of type FPR/VSX thus leading to assert
in RegisterAssigning phase. This commit ensures that paddi and
lxvdsx uses GPR for the constant data snippet address.
Fixes: openj9#12383
=> Fix paddi and lxvdsx for vsplatsEvaluator to have GPR register

compiler/optimizer/Optimizer_inlines.hpp
This is prior step for #5880 completion together with #5919
=> Optimizer_inlines.hpp header added

doc/compiler/il/MainlineAndOutOfLineCode.md
The notes are collected from a meeting with Vijay.
[skip ci] Documentation only.
Co-Authored-By: Vijay Sundaresan <vijaysun@ca.ibm.com>
=> Add notes on mainline and outofline concepts

compiler/x/codegen/OMRCodeGenerator.hpp
=> Remove unused temps from x86 CodeGenerator

compiler/optimizer/SwitchAnalyzer.cpp
Remove dead branches from `SwitchAnalyzer::addTableBlock` caused by unchanged `branchTableSymRef` and `branchTable`.
Remove unused includes.
Simplify if statement with duplicate if and else branches in `TR::SwitchAnalyzer::emit`
Closes #5182
=> Cleanup SwitchAnalyzer by removing dead code, unused includes, formatting

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRInstruction.cpp, compiler/aarch64/codegen/OMRInstruction.hpp, compiler/arm/codegen/OMRInstruction.cpp, compiler/arm/codegen/OMRInstruction.hpp, compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.hpp, compiler/p/codegen/OMRInstruction.cpp, compiler/p/codegen/OMRInstruction.hpp, compiler/p/codegen/PPCSystemLinkage.cpp, compiler/riscv/codegen/OMRCodeGenerator.cpp, compiler/riscv/codegen/OMRInstruction.cpp, compiler/riscv/codegen/OMRInstruction.hpp, compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.hpp, compiler/z/codegen/OMRInstruction.cpp, compiler/z/codegen/OMRInstruction.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/S390Instruction.hpp
Deprecate blockIndex in codegen
Closes: #5293
=> Remove blockindex

compiler/compile/ResolvedMethod.cpp, compiler/compile/ResolvedMethod.hpp
Required for the changes in eclipse/openj9#12549
=> Update TR_ResolvedMethod to obtain the number of ROM method args

compiler/aarch64/codegen/OMRRegisterDependency.cpp, compiler/aarch64/codegen/OMRRegisterDependency.hpp
This commit adds TR_ARM64ScratchRegisterDependencyConditions class
which is a convenience class to temporarily hold register dependencies.
=> AArch64: Add ScratchRegisterDependencyConditions class

compiler/optimizer/LoopVersioner.cpp
A crash would occur in decReferenceCount() after privatizing a pdLoadi
because the Z evaluator was not expecting a pdLoad Opcode. This fix
will disable privatizing all BCD type nodes.
=> Prevent LoopVersioner from attempting to privatize BCD type nodes

compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit improves code generation for the IL sequence i2l-lshl that
often appears in offset calculation for array access, by using `sbfm`
instruction.
This is a revisit of #5890.
=> AArch64: Improve code generation for i2l-lshl sequence

port/aix/omrvmem.c
=> Revert "Allow 64K page size as a valid option on AIX"

compiler/optimizer/VPHandlers.cpp
`isArrayCompTypeValueType` was originally defined as a static function in `VPHandlers.cpp`, but an equivalent virtual method that downstream projects can override is now defined in `OMR::ValuePropagation`.  This change eliminates the function in `VPHandlers.cpp` and has that file use the method in `ValuePropagation` instead.
This change depends on pull request #5909, and a pending downstream implementation of `ValuePropagation::isArrayCompTypeValueType`
=> Replace method in VPHandlers.cpp with equivalent method in VP

compiler/aarch64/codegen/FPTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp, fvtest/compilertriltest/CompareTest.cpp
This commit implements fcmpg/fcmpl/dcmpg/dcmpl evaluators for AArch64.
=> AArch64: Implement fcmpg/fcmpl/dcmpg/dcmpl evaluators

compiler/compile/OMRCompilation.hpp, compiler/control/OptimizationPlan.hpp, compiler/env/OMRPersistentInfo.hpp, compiler/env/TRMemory.hpp, compiler/il/OMRILOps.hpp, compiler/il/OMRNode.hpp, compiler/il/OMRRegisterMappedSymbol.hpp, compiler/il/OMRTreeTop.hpp, compiler/infra/Array.hpp, compiler/infra/Link.hpp, compiler/optimizer/OMROptimizer.hpp, compiler/optimizer/PreExistence.hpp, compiler/ras/Debug.cpp, compiler/ras/Debug.hpp, compiler/ras/Tree.cpp, compiler/runtime/OMRRuntimeAssumptions.hpp
See https://github.com/eclipse-openj9/openj9/issues/12520
This should not be merged before https://github.com/eclipse-openj9/openj9/pull/12765
Closes https://github.com/eclipse-openj9/openj9/issues/12520
=> Remove TR_DebugExt

port/common/omrmemcategories.c
Use addAtomic for incrementing counters of OMRMemCategory instead of
spinning with compareAndSwapUDATA.
Similarly, use subtractAtomic for decrementing counters.
=> Use addAtomic for incrementing counters of OMRMemCategory

cmake/modules/OmrDDRSupport.cmake
=> CMake: Set LIBPATH for ddr on z/OS

buildenv/jenkins/omrbuild.groovy
=> Revamp Jenkins labels to a single compile label

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- This commit adds ArrayCopyBNDCHKEvaluator() and
compareIntsAndBranchForBNDCHK() methods.
- ArrayCopyBNDCHKEvaluator() is required for arrayCopyEvaluator()
implementation.
=> AArch64: Adding ArrayCopyBNDCHKEvaluator()

compiler/riscv/codegen/OMRTreeEvaluator.cpp
This commit changes code sequence used to load 64bit constants. It first
loads high 32bit value into target registers' low 32bits and then use
a sequence of slli + addi instructions to load lower 32 bits.
The advantage of this approach is that this sequence uses only one
(target) registers whereas the previous one required additional scratch
register.
=> RISC-V: improve loadConstant64

compiler/ras/CallStack.cpp, compiler/ras/CallStack.hpp
=> Add guarding macro when including OS specific header

port/unix/omrsysinfo.c
If a program is built by a 10.15 or earlier SDK is run on Big Sur (version 11)
or newer, it will run in a backwards compatibility context which will return
product version as 10.16.
Thus, when we need to get Mac OS version when running on 11+, we need to use
a workaround to get the real version string. In this case, we look at a symlink
to the SystemVersion.plist file which bypasses the backwards compatibility
context.
Fixes https://github.com/eclipse-openj9/openj9/issues/12630
=> Get real MacOS product version if in compability mode

compiler/optimizer/ValuePropagationCommon.cpp
Closes [openj9/#12819](https://github.com/eclipse-openj9/openj9/issues/12819)
=> Invalidate parmInfo for DLT compiles

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit changes commonStoreEvaluator to use xzr register
if the stored value is a zero constant integer.
=> AArch64: Use xzr register for storing zero

compiler/aarch64/codegen/BinaryEvaluator.cpp
Use add (shifted register) instruction if add operation can be
encoded into this instruction.
Similarly, use sub (shifted register) instruction if sub operation
can be encoded into this instruction.
=> AArch64: Use add/sub shifted register instruction if possible

compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit changes `generateMaddOrMsub` to reuse one of source registers
if the source node's reference count is 1.
=> AArch64: Reuse src registers in `generateMaddOrSub` if possible

compiler/z/codegen/OMRMachine.cpp
When assigning virtual register to target real register while assigning
registers for instruction, register exchange API which would take care
of care of making exchange between the target real register and current
assigned register bails out when faced with different sized register and
falls back to the path where we would need spare register to satisfy the
requirement. This would cause an issue where we run out of all the
registers.
In order to make exchange between target real register and current
assigned register, if either one is 64-bit, we can simply use 8 byte
spill slot to do that. This commit upgrades the register exchange API to
do that.
Fixes: https://github.com/eclipse-openj9/openj9/issues/12789
=> Improve registerExchange API on Z

compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/PartialRedundancy.cpp
=> Remove obsolete long parm value profiling code

compiler/control/OMROptions.hpp
=> Remove self included header

compiler/il/OMRMethodSymbol.hpp, compiler/il/OMRResolvedMethodSymbol.hpp, compiler/optimizer/OMROptimizer.cpp, compiler/optimizer/OMROptimizer.hpp
This flag will be needed to add extra passes to optimization
strategies required for VectorAPIExpansion
=> Add IfVectorAPI optimizer flag

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit implements reference arraycopy for AArch64.
=> AArch64: Implement reference arraycopy

compiler/optimizer/VPHandlers.cpp
When we are loading VFT pointer from an object whose
type is known and fixed, we can transform such indirect
load to load constant.
=> Fold VFTLoad from object of known fixed class

compiler/control/OMROptions.hpp
=> Add setter for TR::Options::_bigCalleeScorchingOptThreshold

gc/base/standard/ConcurrentGC.cpp, gc/base/standard/ConcurrentGCIncrementalUpdate.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/13206
This change switches the order between updating INIT table _(tuneToHeap call)_ and setting mark bits during expansion. This way, we guarantee that MM bits are set during heap expand when we miss to update INIT table (or it's not updated in time) given overlap of KO and Tenure Expand.
The issue being resolved is similar to what has been [outlined in a previous issue](https://github.com/eclipse-openj9/openj9/issues/8020#issuecomment-573843125), where MM Bits get missed for init. Here, we have another similar timing hole, when one thread kicks off concurrent, `Concurrent_OFF -> (Concurrent_INIT or INIT Complete)`, while the expanding thread is in middle of `heapReconfigured`.
With the original ordering of `heapReconfigured` - first, …
=> ConcurrentGC Heap/Tenure Expand Fix

gc/base/MemoryPoolAddressOrderedList.cpp
inconsist issue caused by missing to update previous free entry
during elimilating free entry due to card alignment, it would
generate gap between previous and current free entry for
recycleHeapChunk, then cause losing free entries. it could trigger
the assertions of gc allocation for balanced gc case.
- updated previous free entry for the case
- additional assertion check in recycleHeapChunk for verifying
the case.
=> Fix MPAOL inconsist issue between freeBytes and freeList

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
Correctly count the integer or address child nodes added to GlRegDeps node
to avoid adding too many integer registers to the register dependencies.
Add a src register of compare branch instructions to register dependencies
so that a src register is assigned when other registers in the register dependencies
are assigned.
=> AArch64: Correctly handle ificmpeq/ificmpne nodes with many global registers

doc/compiler/optimizer/IntroReadLogFile.md
This document captures the topic on compilation log that Vijay presented in meetings. It also uses GC map content from TestarossaWiki.
Co-Authored-By: Vijay Sundaresan <vijaysun@ca.ibm.com>
=> Add document on reading compilation log

doc/compiler/optimizer/IntroLoopOptimizations.md
This document captures the topics on Loop Specializer Vijay presented in a meeting.
Co-Authored-By: Vijay Sundaresan <vijaysun@ca.ibm.com>
=> Add documentation on Loop Specializer

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds inlined backward arraycopy implementation for
constant length.
=> AArch64: Adding backward arraycopy implementation

gc/stats/CopyForwardStatsCore.hpp
Report how many TLHRemainder has been created during CopyForward.
=> New field TLHRemainderCount in CopyForwardStatsCore

compiler/il/Aliases.cpp, compiler/il/OMRSymbolReference.hpp, compiler/optimizer/GlobalAnticipatability.cpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/LocalAnalysis.cpp, compiler/optimizer/LocalOpts.cpp, compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPHandlers.cpp
=> Replace classNameToSignature with the define in ClassEnv

compiler/runtime/OMRRuntimeAssumptions.hpp
=> Add build assert for OpenJ9 specific file needing refactoring

port/osx/omrsignal_context.c
This commit implements omrsignal_context.c for AArch64 macOS.
=> AArch64 macOS: Implement omrsignal_context.c

gc/base/EnvironmentBase.cpp, gc/base/GCExtensionsBase.cpp, gc/base/GCExtensionsBase.hpp, gc/base/GlobalCollector.hpp, gc/base/MarkingScheme.cpp, gc/base/MarkingScheme.hpp, gc/base/Packet.hpp, gc/base/ParallelMarkTask.cpp, gc/base/ParallelMarkTask.hpp, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/ParallelGlobalGC.hpp, gc/base/standard/RememberedSetSATB.hpp, gc/base/standard/WorkPacketsSATB.cpp, gc/base/standard/WorkPacketsSATB.hpp
Isolated changes part of Core SATB work. These changes are intended for next few PRs for SATB.
=> Non-functional Core SATB Changes

compiler/control/OMROptions.cpp
Prior to this change, if `suffixLogs` (i.e. `TR_EnablePIDExtension`) was enabled (which by default it is), log files for compilation threads other than compilation thread 0 would be opened using a name consisting of only the extra suffix, e.g. "`.193310.88163.20211109.150243.193310`".
The cause was as follows:
1. When `openLogFile()` got a valid `idSuffix`, it would concatenate `_logFileName` with it into a stack buffer (`filename`).
2. Then when `suffixLogs` was also enabled, it would use the same stack buffer (`filename`) as the destination for the concatenation of the name so far (e.g. `foo.log.1`) with the PID and time. This was a call to `sprintf()` in which the destination buffer was also passed as an argument corresponding to a `%s` format specifier. This could (depending on …
=> Ensure that created log files' names start with the specified name

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
Implements vadd and vsub for Short and ByteVectors of size 128
=> Implement vadd and vsub for Short and ByteVectors of size 128

port/unix/omrsignal.c
Issue https://github.com/eclipse-openj9/openj9/issues/12526
=> On OSX incorporate nano time in wakeUpASyncReporter sem name

compiler/env/OMRKnownObjectTable.cpp, compiler/env/OMRKnownObjectTable.hpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPConstraint.hpp, compiler/optimizer/VPHandlers.cpp
- array elements are considered stable if their values are constant
unless they are zero
=> Optimize arrays with stable elements

port/win32/omrsysinfo.c
The update to Windows 11 does not increment the major version,
so we detect using other info such as CurrentBuild number.
Fixes https://github.com/eclipse-openj9/openj9/issues/13755#issuecomment-951230263
Can you take a look please @pshipton
=> Add OS detection for Windows 11 and Server 2022

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp
Add `findOrFabricateFlattenedArrayShadowSymbol`
=> Add findOrFabricateFlattenedArrayShadowSymbol

compiler/optimizer/PartialRedundancy.cpp
1)This commit deletes some inactive code in the PRE optimization.
2)There were some old mentions that were renamed to exception check removal.
3)Tracing was improved in the cost benefit part of PRE.
Signed-off-by: Vijay Sundaresan vijaysun@ca.ibm.com
=> Minor cleanup of PRE code

include_core/omrmemcategories.h
This reverts commit 431b7d1db3bf335b316d9962b01623adacbfdfbb.
=> Revert "Add a memory category for the Foreign Linker API"

compiler/aarch64/codegen/BinaryEvaluator.cpp
Use shifted register instruction for binary operations such as
`and`/`or`/`xor` in addition to `and`/`sub`.
=> AArch64: Use shifted register instruction for binary operations

port/osx/omrosdump.c
This commit implements omrosdump.c for AArch64 macOS.
=> AArch64 macOS: Implement omrosdump.c

compiler/aarch64/codegen/BinaryEvaluator.cpp
Use `bic`/`orn`/`eon` instructions if possible.
=> AArch64: Use bitwise logical operation with NOT if possible

compiler/infra/OMRCfg.hpp
=> Remove declared only methods

buildenv/jenkins/jobs/pull-requests/PullRequest-zos_390-64, buildenv/jenkins/omrbuild.groovy
=> Correct repository URL

compiler/control/OMROptions.cpp, compiler/z/codegen/ControlFlowEvaluator.cpp, compiler/z/codegen/InstOpCode.cpp, compiler/z/codegen/OMRInstOpCode.enum, compiler/z/codegen/OMRInstOpCode.hpp, compiler/z/codegen/OMRInstOpCodeProperties.hpp, compiler/z/codegen/OMRInstructionKindEnum.hpp, compiler/z/codegen/S390Debug.cpp, compiler/z/codegen/S390GenerateInstructions.cpp, compiler/z/codegen/S390GenerateInstructions.hpp, compiler/z/codegen/S390Instruction.cpp, compiler/z/codegen/S390Instruction.hpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp, include_core/omrport.h, port/unix/omrsysinfo.c, port/unix_include/omrportpg.h, port/zos390/omrportpg.h
This PR adds the necessary improvements to exploit zNext hardware in the JIT compiler. The commits have been authored by myself, @VermaSh and @r30shah.
=> Add zNext improvements to z/codegen

jitbuilder/apigen/jitbuilder.api.json
=> Add missing identity queries to IlType service API

port/osx/omrosdump.c
Use stack allocated buffer when reading from process memory instead of
the one automatically created by mach_vm_read since we get memory
access issues in MacOS 12 using the automatically created buffer if the
runtime is signed.
Fixes https://github.com/eclipse-openj9/openj9/issues/14192
=> Read core memory segments into local buffer

compiler/optimizer/FieldPrivatizer.cpp
The Field Privatizer optimization needs to write back privatized field
stores on loop exits. This fix will ensure that write barrier field
stores will be used as the basis of the exit store back node to
ensure that loop exit stores do not skip write barrier operations when
some original non-privatized store inside the loop was doing the
operation. Previously a field load could have been used an the basis of
the exist loop store resulting in an astore rather then an awrtbar.
=> Fix FieldPrivatizer so that it does not miss emitting write barriers

compiler/optimizer/VPHandlers.cpp
Changes in [1] optimizes the VFTLoad from an object if the object is of known fixed type. This transformation would convert such load from an object to load of constant address. This would change
how loading of isClassAndDepthFlags would look like from J9Class *. Consider following example,
```
n3745n    treetop
n3744n      new  jitNewObject[#91  helper Method] [flags 0x400 0x0 ]
n3743n        loadaddr  org/junit/internal/ExactComparisonCriteria[#748  Static]
n3802n    astore  <temp slot 2>[#758  Auto]
n3744n      ==>new
n3820n    NULLCHK on n3784n [#32]
n3788n      aloadi  <vft-symbol>[#307  Shadow]
n3784n        aload  <temp slot 2>[#758  Auto]
n3793n    ificmpne --> block_69 BBStart at n3799n ()
n3791n      iand (X>=0 cannotOverflow )
n3789n        iloadi  <isClassAndDepthFlags>[#304 …
```
=> Simplify load of J9Class flags off fix loadaddr

port/common/omrstr.c
OpenJ9, for example, expects the timezone name to be encoded in ASCII.
=> Convert timezone name to ASCII on z/OS

compiler/z/codegen/OMRLinkage.cpp, compiler/z/codegen/OMRLinkage.hpp, compiler/z/codegen/SystemLinkage.cpp, compiler/z/codegen/SystemLinkage.hpp
* Remove unused LocalsAreaBeginOffset and LocalsAreaEndOffset
* Remove unused get/setStackSizeCheckNeeded from Z linkage
=> Cleanup unused Linkage fields and functions

port/common/omrcuda.cpp
Note release date of each version.
=> Add support for CUDA versions 11.3, 11.4, 11.5 and 11.6

compiler/compile/OMRNonHelperSymbols.enum, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/ras/Debug.cpp
=> Add new inlineEncodeASCIISymbol

.copyrightignore, buildenv/jenkins/copyrightCheck.groovy
=> Add copyrightCheck from OpenJ9 as-is

compiler/compile/ResolvedMethod.cpp, compiler/compile/ResolvedMethod.hpp, compiler/control/OMROptions.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/InlinerFailureReason.hpp, compiler/x/codegen/FPBinaryArithmeticAnalyser.hpp, compiler/z/codegen/FPTreeEvaluator.cpp, fvtest/compilertest/compile/ResolvedMethod.hpp, jitbuilder/compile/ResolvedMethod.hpp
Feature has been deprecated and no longer applies.
=> Remove remaining remnants of strictFP

compiler/x/amd64/codegen/OMRTreeEvaluator.cpp, compiler/x/amd64/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/UnaryEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.hpp, fvtest/compilertriltest/VectorTest.cpp
=> Implement 128-bit vector negation on x86

compiler/x/codegen/FPTreeEvaluator.cpp
=> Optimize fpUnaryMaskEvaluator with 3-operand instruction form

compiler/x/amd64/codegen/RealRegisterEnum.hpp, compiler/x/codegen/OMRInstruction.cpp, compiler/x/codegen/OMRRegisterDependency.cpp, compiler/x/codegen/OMRRegisterDependency.hpp, compiler/x/codegen/OMRRegisterDependencyStruct.hpp, compiler/x/codegen/OMRX86Instruction.cpp, compiler/x/codegen/OMRX86Instruction.hpp, compiler/x/codegen/X86BinaryEncoding.cpp, compiler/x/codegen/X86Debug.cpp, compiler/x/i386/codegen/RealRegisterEnum.hpp
* Remove x87 assignFPRegisters() from RegisterDependency
* Remove x87 AllFPRegisters RegisterDependency special register
* Remove x87 X86FPRemainderRegRegInstruction class
* Remove x87 X86FPArithmeticRegRegInstruction class
* Remove x87 numReferencedFPRegisters()
=> Remove misc. dead x87 code

compiler/il/OMROpcodes.enum, compiler/x/amd64/codegen/OMRTreeEvaluator.cpp, compiler/x/amd64/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/FPTreeEvaluator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRInstOpCode.enum, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/UnaryEvaluator.cpp, compiler/x/codegen/X86Ops.ins, compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.hpp, fvtest/compilertriltest/VectorTest.cpp, fvtest/compilerunittest/x/BinaryEncoder.cpp
=> Implement vdsqrt opcode on x86

port/unix/omrsysinfo.c
Add logic to detect the presence of container files for both cgroup v1
and v2. If these files are not present, resort to the original method
(which will not work if namespaces are enabled in the container).
Also, the cgroup mount point is renamed as both cgroup v1 and v2 are
conventionally mounted at the same point.
Issue: #1281
=> Improve container detection

fvtest/compilerunittest/abstractinterpreter/AbsInterpreterTest.cpp, fvtest/coretest/TestIntrusiveList.cpp, fvtest/coretest/TestTypeTraits.cpp, include_core/OMR/Bytes.hpp, include_core/OMR/IntrusiveList.hpp, include_core/OMR/TypeTraits.hpp
=> Correct Copyright header

compiler/optimizer/DeadTreesElimination.cpp
When a volatile RegStore node is moved down to the end of the block,
the order of the trees cannot be changed because that is the order
containsNode used to check if canMoveIfVolatile should be true or not
=> Do not change lastTree when moving a volatile RegStore node

gc/structs/SublistPool.cpp
This prevents a delayed initialization of RememberedSet puddle, on POWER
weak memory model, that may occur when the puddle is exposed to other
threads/CPUs before the initialization has completed.
In turn the delayed initialization could wipe out valid remembered
object added by other racing threads.
The fix introduces a low-level writeBarrier that will enforce the
initializaton completion, before the puddle is exposed to other threads.
=> Fix for newly allocated RS puddle delayed initialization

compiler/control/OMROptions.cpp
=> Disable zNext on 31-Bit zLinux

compiler/aarch64/codegen/OMRMemoryReference.cpp
`populateMemoryReference` function skips `l2a` node if the node's reference
count is 1 and node does not have a register.
Skipping it makes the base register of the memory reference
a non-collected reference register. This is incorrect but harmless in normal
cases. However, if the memory reference has a UnresolvedDataSnippet,
the first generated instruction would be a branch to the snippet. The resolution
helper is called fron the snippet, which may trigger GC. Because GC does not
know about the base register, the value of the base register would not be
updated correctly.
This commit changes `populateMemoryReference` to evaluate `l2a` node if
the memory reference has a UnresolvedDataSnippet.
=> AArch64: Do not skip l2a node if the MemoryReference has UnresolvedDataSnippet

gc/base/standard/CompactScheme.cpp, gc/base/standard/ConcurrentCardTable.cpp, port/osx/omrosdump.c
Fixes #6448
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>
=> Issue #6448: Fix variable set but not used compile errors

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements an evaluator for vector fma.
=> AArch64: Implement evaluator for vector fma

compiler/riscv/codegen/ControlFlowEvaluator.cpp, compiler/riscv/codegen/GenerateInstructions.cpp, compiler/riscv/codegen/GenerateInstructions.hpp, compiler/riscv/codegen/OMRCodeGenerator.cpp, compiler/riscv/codegen/OMRInstructionKindEnum.hpp, compiler/riscv/codegen/RVInstruction.cpp, compiler/riscv/codegen/RVInstruction.hpp
The code in this PR is just adapted AArch64 version.
=> RISC-V: implement virtual guard nopping

compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.hpp
=> Move J9 specific i386 evaluators to OpenJ9

port/unix/omrsysinfo.c
Update `retrieveLinuxCgroupMemoryStats` to collect memory metrics from
cgroup v2 files.
The cgroup memory files are changed from cgroup v1 to v2 as follows:
`memory.limit_in_bytes` -> `memory.max`
`memory.usage_in_bytes` -> `memory.current`
`memory.memsw.limit_in_bytes` -> `memory.swap.max`
`memory.memsw.usage_in_bytes` -> `memory.swap.current`
`memory.stat` no change
In the `memory.stat` file, the metric `cache` -> `file`
Issue: https://github.com/eclipse/omr/issues/1281
=> Collect cgroup v2 memory stats

compiler/aarch64/codegen/BinaryEvaluator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, fvtest/compilertriltest/VectorTest.cpp
Implement vdiv evaluator for integer elements.
=> AArch64: Implement vdiv evaluator for integer elements

gc/base/j9mm.tdf, gc/base/standard/Scavenger.cpp
Replace SyncAndReleaseMaster to SyncAndReleaseMain
=> Replace Master to Main leftover

buildenv/jenkins/README.md
=> Replace slave with node leftover

fvtest/porttest/omrfileTest.cpp
PortFileTest2.file_test27 and PortFileTest2.file_test29 fail when runnning
as root. Add logic to change test behaviour if tests are being run as root.
=> Fix omrfileTest failures when running as root

compiler/p/codegen/OMRCodeGenerator.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/15074
Signed-off-by: midronij <jackie.midroni@ibm.com>
=> Fix for assertion failure during OMR acceptance build

ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
Recognize and handle simple expressions by skipping `"DW_OP_plus_uconst"` when present for field offsets.
Verify that attribute values are reasonable; insist that at least some (normally all) of the string is consumed.
Ignore attributes where the value begins with `'<'`, e.g.
```
DW_AT_const_value (<0x04> 00 00 80 3f )
```
These have been seen in relation to inlined functions and provide the value of a formal parameter given at the call site: we don't need that information.
=> Improve dwarfdump attribute value parsing

compiler/il/OMRDataTypes.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/SIMDTreeEvaluator.cpp, fvtest/compilertriltest/VectorTest.cpp
=> Revert "Revert "Implement 256 and 512-bit vload/vstore on x86""

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.hpp, fvtest/compilertriltest/VectorTest.cpp
=> Make getSupportsOpCodeForAutoSIMD() statically accessible

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Implement evaluator for `vreductionAdd` opcode.
=> AArch64: Implement evaluator for vector reduction add

compiler/aarch64/codegen/OMRMachine.cpp
In register assignment, a temporary register is used for
exchanging floating point or vector registers.
However, if a register dependency has all 32 FPRs, the register assigner
cannot find the temporary register and fails abruptly.
Since vector eor instructions can be used for exchanging floating point
or vector registers without a temporary register, this commit changes
the register assigner to generate those instructions for exchanging registers
and removes the use of a temporary register.
=> AArch64: Use vector eor instructions for register exchange

compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Implement evaluator for `vreductionMul` opcode.
=> AArch64: Implement evaluator for vector reduction multiplication

compiler/z/codegen/OMRMachine.cpp, port/aix/omrosbacktrace_impl.c, port/common/omrosbacktrace.c, port/common/omrosbacktrace_impl.c, port/osx/omrosbacktrace_impl.c, port/win32/omrosbacktrace_impl.c, port/zos390/omrosbacktrace_impl.c, port/ztpf/omrosbacktrace_impl.c
=> Fix misspellings of "aren't"

compiler/codegen/CodeGenRA.cpp, compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp
=> Reuse 32 and 64-byte backing stores

compiler/optimizer/OMRSimplifierHandlers.cpp
- fold ibits2f<=>fbits2i and lbits2d<=>dbits2l
=> Fold unnecessary FP to Integral type casts

CODEOWNERS
* Add 0xdaryl as a project lead in CODEOWNERS
* Add babsingh to port, thread, and core in CODEOWNERS
=> Misc. CODEOWNERS updates

compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/SIMDTreeEvaluator.cpp, fvtest/compilertriltest/VectorTest.cpp
=> x86: implement vsplats for all vector lengths

compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp
=> Implement VMIN and VMAX Evaluator

fvtest/threadtest/CMakeLists.txt
Related https://github.com/eclipse/omr/issues/6665
=> Disable PriorityInterrupt on Linux riscv64

compiler/x/codegen/OMRTreeEvaluator.cpp
=> x86: Support bitwise vector opcodes for each data-type

gc/base/GCExtensionsBase.hpp, gc/base/standard/ParallelGlobalGC.cpp
=> Refactor idle tuning fields

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Fix vector compare evaluators to return the correct value when any of float/double element is NaN.
=> AArch64: Fix vector compare evaluators

compiler/optimizer/VPHandlers.cpp
The previous logic here incorrectly assumed that an `aloadi` must load `<vft-symbol>`, but it could load from elsewhere, e.g. a field of a reflective object. When loading `<classFromJavaLangClass>`, the base object could be constrained with `isClassObject() == TR_yes`, which would result in the right type even though it doesn't seem like the previous logic was intended to take this case into account. But it could also be constrained with `isClassObject() != TR_yes`, and with a type bound. In that case, the type bound describes the type of the object we're loading from, which is actually as expected by the previous logic, but because the `aloadi` loads `<classFromJavaLangClass>` rather than `<vft-symbol>`, that type is not in general related to the result of the load, and VP could …
=> Ignore opcodes when attempting to fold array class tests

compiler/optimizer/DataFlowAnalysis.hpp
=> Add TR::Region allocator/deallocator to TR_DataFlowAnalysis

buildenv/jenkins/README.md, compiler/control/OMROptions.cpp
=> Replace whitelist with allowlist

gc/base/GCExtensionsBase.hpp
Downstream project has been updated to use new function names. Old functions can be deleted now.
=> Cleanup after functions renaming

buildenv/jenkins/omrbuild.groovy, doc/GuideForCommitters.md
=> Add macOS on AArch64

gc/base/GCCode.cpp, gc/base/gcutils.cpp
Add missing checkpoint GC checks
=> Add missing checkpoint GC checks

jitbuilder/runtime/JBCodeCacheManager.cpp
This commit updates JBCodeCacheManager to allocate the CodeCacheMemorySegment object by malloc instead of using a part of the mmaped memory segment on AArch64 Mac. The mmaped memory segment is not both writable and executable at the same time on Apple Silicon. If the CodeCacheMemorySegment object is allocated on the mmaped segment, an access violation would occur when updating its members.
=> AArch64 Mac: Update JBCodeCacheManager to enable jitbuilder

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements a2iEvaluator.
=> AArch64: Implement a2iEvaluator

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements vmfma evaluator.
=> AArch64: Implement vector masked FMA evaluator

compiler/x/codegen/OMRCodeGenerator.hpp
Allow project extensions to CodeGenerator class to access this data member.
=> Make _dataSnippetList protected

compiler/optimizer/DataFlowAnalysis.hpp
=> OMR changes needed to support an OpenJ9 EA fix

compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit adds support for mustNormalizeNanValues in fbits2i/dbits2l evaluators for AArch64.
Closes: #6789
=> AArch64: Add support for mustNormalizeNanValues in fbits2i/dbits2l

compiler/ras/Debug.cpp
See https://github.com/eclipse/omr/pull/6595#pullrequestreview-1165704003.
=> Fix check of trace file length

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.hpp, compiler/il/OMRILOps.hpp, compiler/il/OMRILProps.hpp, compiler/il/VectorOperations.enum, compiler/optimizer/OMRSimplifierTable.enum, compiler/optimizer/ValuePropagationTable.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.hpp, compiler/riscv/codegen/OMRTreeEvaluator.cpp, compiler/riscv/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp
- mTrueCount, mFirstTrue, mLastTrue, mToLong
=> Add mask reduction opcodes

compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit fixes code generation for iffcmpne/ifdcmpne evaluators for AArch64.
Fixes: #6790
=> AArch64: Fix iffcmpne/ifdcmpne evaluators for unordered case

compiler/il/OMRNode.hpp
downstream project now can reuse/extend the method
=> Modify method computeIsCollectedReferenceImpl to protected

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements Vector Masked Compare evaluators.
=> AArch64: Implement Vector Masked Compare operations

port/zos390/omrvmem.c
A new `__MOPL_EXECUTABLE` flag is being defined to the zOS LE `__moservices()` call to specify executable property under PTF UI83032. Explicitly set the execute storage flags for memory allocated with __moservices if appropriate.
=> Add execute flag for __moservice allocations on zOS

port/osx/omrosdump.c
In MacOS 13, we can no longer pass the task port to a child process through setting the bootstrap port to the same port name as the task port and having the child inherit that. Instead we must pass a normal port to the child process which will be creating the core dump in order to set up messaging. Then we can use that to pass the task port so the child has access to the parent.
Fixes https://github.com/eclipse-openj9/openj9/issues/16328
fyi @pshipton
=> Pass task port for core dump using IPC

gc/base/standard/Scavenger.cpp
- Trc_MM_Scavenger_calculateRecommendedWorkingThreads_threadStallBreakDown shouldn't be reported for Concurrent Scavenger
- Replace use of `_extensions->concurrentScavenger` in Scavenger with `IS_CONCURRENT_ENABLED` macro for consistency
=> Fix Reporting Of Scavenger Adaptive Threading trc point

compiler/optimizer/VPHandlers.cpp
Prevent GVP in AOT SVM compiles from inspecting objs and replacing array
length checks with hard-coded values based on an object's array length
Prevent GVP from inspecting heap objects of static final fields. 
This leads to possibility of an array overrun executing an AOT SVM 
compile because it's possible for the <clinit> to assign arrays of
different lengths to a field in different JVM instances. For non-AOT
compiles the code is also unsafe because it's possible for reflection
or the unsafe API to change static final field values.
=> GVP fix for SVM AOT compiles

compiler/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
=> x86: disable GRA for vectors & masks

compiler/optimizer/VPHandlers.cpp
If the following program
```
public class Bug {
public static final int sub(int i) {
int[] arr = {1,2,3,4,5,6,7,8};
long l = 0;
return arr[-((int) (i % l))];
}
public static final void main(String[] args) {
sub(1);
}
}
```
is run with `java -Xjit:count=0 Bug`, the following assertion failure results:
```
Assertion failed at /root/hostdir/defects/issue15730/openj9-openjdk-jdk17/omr/compiler/optimizer/VPHandlers.cpp:8171: low <= high
VMState: 0x000514ff
Node 0x7f87257752c0 [l2i]: reversed child constraint bounds
```
The problem is that the `constrainIrem` and `constrainLrem` Value Propagation handlers guard against a right-hand operand of zero if the left-hand operand is a constant, but not if the left-hand operand is a non-constant.  In the latter case, a constraint in the range [1,-1] …
=> Check for right-hand operand of zero in lrem and irem

compiler/x/codegen/X86Debug.cpp
=> x86: refactor asm debug traces

compiler/optimizer/LoopVersioner.cpp
Some guard trees, e.g. for nonoverridden guards, do not contain an occurrence of the receiver. Since it doesn't occur in the guard tree, it is not automatically privatized by `depsForLoopEntryPrep()`.
Detect this case and explicitly privatize the receiver (if necessary) to ensure that it cannot vary from one iteration to the next, even in the presence of a data race. This will also prevent versioning of the guard whenever privatization is disallowed, i.e. whenever a cold call will necessarily remain within the hot loop, since the cold call could change the receiver.
=> Ensure receivers are privatized (if necessary) when versioning guards

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit improves instruction sequence generated in mFirstTrue and mLastTrue evaluators.
=> AArch64: Improve mFirstTrue and mLastTrue evaluators

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.hpp
Signed-off-by: midronij <jackie.midroni@ibm.com>
=> PowerPC: Disable GRA for Vector Mask types

compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp
Signed-off-by: Bradley Wood <bradley.wood@ibm.com>
=> x86: Support masked vector fma

gc/base/standard/ConcurrentGCIncrementalUpdate.cpp, tools/hookgen/HookGen.cpp, tools/tracegen/Port.hpp, tools/tracegen/TraceHeaderWriter.cpp, tools/tracemerge/DATMerge.cpp
This commit replaces sprintf() with snprintf().
=> Replace sprintf() with snprintf()

third_party/pugixml-1.5/pugixml.cpp
=> Revert "Replace sprintf() in pugixml with snprintf()"

gc/base/standard/ConcurrentGCIncrementalUpdate.cpp, tools/hookgen/HookGen.cpp, tools/tracegen/Port.hpp, tools/tracegen/TraceHeaderWriter.cpp, tools/tracemerge/DATMerge.cpp
=> Revert "Replace sprintf() with snprintf()"

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/il/OMRILOps.cpp, compiler/optimizer/OMRLocalCSE.cpp, compiler/optimizer/PartialRedundancy.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/riscv/codegen/OMRTreeEvaluator.cpp, compiler/x/amd64/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
- in contrast to vconv IL opcode, vcast is a noop
=> Implement vcast IL opcode

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Add b2sEvaluator which just calls b2iEvaluator.
=> AArch64: Implement b2sEvaluator

azure-pipelines.yml
Related: #6924
Ref: https://github.com/actions/runner-images/issues/5583#issuecomment-1426004850
=> Change Azure x64 build to macOS-11

compiler/riscv/codegen/OMRTreeEvaluator.cpp
In OpenJ9, classes are aligned on 256-bit boundaries, and the low 8
bits of the class pointer in the object header are used for flags.
So to get the proper class pointer we have to clear the flags using
(OpenJ9 specific) generateVFTMaskInstruction().
=> RISC-V: call generateVFTMaskInstruction() from aloadEvaluator()

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/ParallelDispatcher.cpp, gc/base/ParallelDispatcher.hpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp, gc/base/standard/ConfigurationStandard.cpp, gc/base/standard/ConfigurationStandard.hpp
- Follow up cleanup changes to previous CRIU GC API refactoring: https://github.com/eclipse/omr/pull/6947
- Implement MM_Configuration::reinitializeForRestore to iterate and reinit memory pools
=> GC CRIU: Refactor Follow-up + Reinit memory pool API

port/unix/omrsysinfo.c
cgroupFile - `/proc/<PID>/cgroup`
There can be multiple lines in the cgroupFile. This happens when
cgroups v1 controllers, which do not have a cgroups v2 equivalent,
are enabled in a cgroups v2 environment.
In this case, all lines in the cgroupFile need to be parsed to locate
the line with the `0::<cgroup>` format.
The new container detection method reads the first line in
`/proc/1/sched` if it exists. If the initialization process is neither
`init` nor `systemd`, then it can be assumed that the process is
operating inside a container.
The new method will only be used if the existing methods fail
to correctly detect a containerized environment.
Related: #6935
=> Improve cgroups v2 and container detection

compiler/control/OMROptions.cpp
=> Correct typos in OMROptions.cpp

compiler/aarch64/CMakeLists.txt, compiler/aarch64/codegen/OMRSnippetDelegate.cpp, compiler/aarch64/codegen/OMRSnippetDelegate.hpp, compiler/arm/codegen/OMRSnippetDelegate.cpp, compiler/arm/codegen/OMRSnippetDelegate.hpp, compiler/codegen/OMRSnippetDelegate.hpp, compiler/codegen/SnippetDelegate.hpp, compiler/p/CMakeLists.txt, compiler/p/codegen/OMRSnippetDelegate.cpp, compiler/p/codegen/OMRSnippetDelegate.hpp, compiler/riscv/CMakeLists.txt, compiler/riscv/codegen/OMRSnippetDelegate.cpp, compiler/riscv/codegen/OMRSnippetDelegate.hpp, compiler/x/CMakeLists.txt, compiler/x/codegen/OMRSnippetDelegate.cpp, compiler/x/codegen/OMRSnippetDelegate.hpp, compiler/z/CMakeLists.txt, compiler/z/codegen/OMRSnippetDelegate.cpp, compiler/z/codegen/OMRSnippetDelegate.hpp
This is similar in design and purpose to the InstructionDelegate hierarchy (#3778).
This is a skeleton implementation only and contains no static member functions yet.
=> Initial implementation of a SnippetDelegate hierarchy

buildenv/jenkins/omrbuild.groovy
@babsingh @keithc-ca as per comment in https://github.com/eclipse/omr/pull/7004#pullrequestreview-1450727124
=> Revert copyright change performed in #7004

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit implements vpopcnt evaluator on AArch64.
=> AArch64: Implement Vector Population Count evaluator

gc/base/ParallelDispatcher.cpp
Relates to https://github.com/eclipse-openj9/openj9/issues/17463#issuecomment-1567689009
Fixes https://github.com/eclipse-openj9/openj9/issues/17463
=> Allow Single Threaded GC Dispatch During Checkpoint

gc/base/standard/ParallelGlobalGC.cpp
Relates to https://github.com/eclipse-openj9/openj9/pull/17459#discussion_r1218353391
=> Invoke Scavenger Reinit during Global GC Reinit

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/standard/ConfigurationStandard.cpp
Relates to https://github.com/eclipse-openj9/openj9/pull/17459#discussion_r1231139601
=> initializeGCParameters During CRIU Restore

gc/base/segregated/SweepSchemeSegregated.cpp
This is causing a compiler issue in the latest version of Xcode. Related to https://github.com/eclipse-openj9/openj9/issues/17493
=> Remove unused counters

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
`vrolEvalutor` on AArch64 uses a left shift and a right shift operations to achieve a vector rotate operation.
However, if elements of the second source vector which describes rotate amount are negative, it incorrectly calculates the shift amount applied fo the left and right shift operations.
This commit fixes the evalutor to validate the rotate amount vector before applying shift operations.
Fixes https://github.com/eclipse/omr/issues/7062.
=> AArch64: Fix Vector Rotate Evaluator

compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit improves shiftHelper() for AArch64 by stopping generation of shift instruction when the shift value is a constant 0.
=> AArch64: Stop generating shift 0

compiler/p/codegen/BinaryEvaluator.cpp
In some cases when attempting a shift right calculation, a rotate left instruction is used instead on Power. For this to work, the shift value needs to be convered to be (data width - shift amount).
eg. Shift right by 4 on a 32 bit value becomes a rotate left and mask by (32-4=) 28.
However, this doesn't work when trying to shift right by 0. It gets converted to a rotate left and mask by 32 (for 32 bit values) which is not a legal encoding of the instruction.
This has now been updated to take the modulo by data width after the old version of the conversion. This will catch cases of a shift right by 0 and convert to a rotate left and mask by 0.
=> Fixed shift calculations for shift right on Power

util/omrutil/xml.c
The function came under focus due to eclipse-openj9/openj9#17978 because the character sequence "&amp;#x1;" encodes a character that is not legal in XML version 1.0.
The function now only uses an escape sequence for legal characters and replaces illegal characters with the Unicode replacement U+FFFD. Also the intermediate buffer is no longer needed.
Fixes eclipse-openj9/openj9#17978.
=> Encode only valid XML characters in escapeXMLString()

compiler/x/codegen/OMRTreeEvaluator.cpp
...as they occur in plain stores (as opposed to write barriers, or elsewhere). Usually a compression (not decompression) sequence feeds directly into some kind of store, and usually write barriers storing null should have already been changed into plain stores before code generation.
Consider this sequence of stores that set an object's fields to null:
foo.f1 = null;
foo.f2 = null;
foo.f3 = null;
We've been generating code that looks something like this:
xor ecx, ecx
mov rdx, rcx
shr rdx, 0x03
mov dword ptr [rax+0x8], edx
mov rdx, rcx
shr rdx, 0x03
mov dword ptr [rax+0xc], edx
shr rcx, 0x03
mov dword ptr [rax+0x10], ecx
With this commit we'll now use immediates, like so:
mov dword ptr [rax+0x8], 0
mov dword ptr [rax+0xc], 0
mov dword ptr [rax+0x10], 0
or, if the null constant has already …
=> Improve x86 code generation for constant null compression sequences

compiler/runtime/OMRCodeCache.cpp
The first two fields of a TR::CodeCache data structures are `_warmCodeAlloc` and `_coldCodeAlloc` and they used by a third party (e.g. the JVM) to compute the amount of free space in the code cache. During the TR::CodeCache initialization we populate the _warmCodeAlloc and _coldCodeAlloc fields and then write a pointer to the TR::CodeCache structure at the beginning of the segment that provides memory for the code cache itself. Just before writing this pointer we need to issue a write memory barrier to ensure that the values of _warmCodeAlloc and _coldCodeAlloc are seen by another thread at the time when the pointer to the TR::CodeCache is written at the begining of the memory segment.
=> Fix code cache segment race condition

gc/verbose/VerboseHandlerOutput.cpp
Last Responder thread can be NULL in the case of Safe Point Exclusive. Check pointer for NULL and leave thread name empty.
=> Allow Last Responder thread pointer to be NULL

gc/base/GCCode.cpp, gc/base/GCCode.hpp, gc/base/ParallelHeapWalker.cpp, gc/base/ParallelHeapWalker.hpp, gc/base/j9mm.tdf, gc/base/standard/HeapWalker.cpp, gc/base/standard/HeapWalker.hpp, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/ParallelGlobalGC.hpp, gc/verbose/VerboseHandlerOutput.cpp, include_core/omrgcconsts.h
Reverts eclipse/omr#7159
causes a Java exception on Linux AArch64: https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_OMR/406/tapResults/
=> Revert "Clear Inactive Objects at Checkpoint"

omrmakefiles/rules.linux.mk
See also https://github.com/eclipse-openj9/openj9/pull/15004.
=> UMA: use -gdwarf-4

compiler/x/codegen/X86Debug.cpp
- For OSR induction helpers and `<jitDispatchJ9Method>`, there is no move instruction to set `rdi` to the target `J9Method`, so don't print it.
- Print the correct helper name in the final `jmp`.
- Print the correct argument stack slot store instructions.
=> Print x86 call snippets correctly

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/optimizer/GlobalRegisterAllocator.cpp, compiler/optimizer/GlobalRegisterAllocator.hpp, compiler/optimizer/OMRRegisterCandidate.cpp
=> Revert "GRA changes to reduce JIT overhead at warm opt levels"

compiler/optimizer/LoopVersioner.cpp
Add overflow test in BNDCHK versioning tests
**This PR depends on**
=> Add overflow test in BNDCHK versioning tests

compiler/z/codegen/OMRTreeEvaluator.cpp
This PR targets array cmp helper implementation when the length is constant. the arraycmpEvaluator calls arraycmpHelper when the length is constant and less than 4k and requested response is unsigned.
=> Z: Short circuit constant length array cmp helper

compiler/optimizer/ValuePropagationCommon.cpp
StringCoding.implEncodeAsciiArray is a renamed version of US_ASCII/Encoder.encodeASCII, which is a recognized method. This commit introduces infrastructure to enable inlining of implEncodeAsciiArray like it is done for encodeASCII.
=> Transform new converter call to arraytranslate

doc/compiler/optimizer/DataFlowEngine.md
This note is extracted out from a meeting content that Vijay covered.
=> Add descriptions on analyses used by PRE

compiler/optimizer/LocalTransparency.cpp
When processing a volatile store in `TR_LocalTransparency::updateUsesAndDefs`, it should kill any store node that has appeared earlier in the block. Otherwise, the store node could survive the block in local transparency but will be killed in `_downwardExposedAnalysisInfo` when the volatile store is processed in local anticipatability, which causes inconsistency between local transparency and local anticipatability. This matches [how a call node is processed in
`TR_LocalTransparency::updateUsesAndDefs`](https://github.com/eclipse/omr/blob/dd4c5d5459a1e2a890f18b68d5c6b7b105b658d0/compiler/optimizer/LocalTransparency.cpp#L578-L594) to set up `symRefsDefinedAfterStored`.
Fixes: eclipse-openj9/openj9#19218
=> Kill prior store nodes in processing volatile store in local transparency

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
This is a follow-up of PR #7361, adding support for select nodes with other kinds of cmp nodes as the first child, such as icmpne and acmpgt.
=> AArch64: Improve *cmp*-*select instruction sequence

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/il/OMROpcodes.enum, compiler/optimizer/LoopReducer.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/ArrayTest.cpp
=> Revert "Change arraycmp length child to 64 bits"

gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/Scavenger.cpp
https://github.com/eclipse/omr/pull/7420 seems to cause perf regression, and since investigation is not trivial and revert of the original change would drag 3 more PRs to be reverted this is just a partial revert, that basically gets the same run-time behavior, although it does not revert some other code this will not be used/invoked.
=> Revert invocations of cpu util calculation

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
- this option will control whether AOT code is reinstalled into cold code cache or not
=> Add TR_ReinstallAOTToColdCode option

compiler/optimizer/VPConstraint.cpp
- Correctly handle `isInstanceOf()==TR_maybe` in `VPClass::mustBeNotEqual()`
- Re-enable new `VPClass::mustBeNotEqual()`
=> Fix and re-enable new VPClass::mustBeNotEqual()

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
-  add option that enables all experimental options that can help
code cache disclaiming
=> Add -Xjit:EnableCodeCacheDisclaimingSupport option

port/common/omrport.tdf
This matches the other filestream tracepoints.
=> Fix j9filestrean tracepoint group to be omrfilestream

compiler/il/Aliases.cpp
Update System.arraycopy and intrinsics alias to be the same when HCR is enabled and when HCR is disabled since we already skip HCR guard for some JCL methods.
=> Update System.arraycopy and intrinsics alias

thread/thread_include.mk
=> UMA: export omrthread_get_thread_times()

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/OMRInstOpCode.enum, compiler/aarch64/codegen/OpBinary.cpp
This commit adds YIELD instruction for AArch64.
=> AArch64: Add YIELD instruction

gc/base/Collector.cpp
Current vmState for Collector does not include pre- and post- collect. If crash occur in pre- or post- collect vmState can be misleading.
=> Extend vmState to pre/post collect

example/glue/UtilGlue.c, include_core/omr.h, util/omrutil/thrname_core.c
Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>
=> Fix unnamed spelling mistake

gc/stats/ClassUnloadStats.cpp, gc/stats/ClassUnloadStats.hpp
Add cumulative counters for anonymous classes, classes and classloaders. Add update counters and get cumulative counters API.
=> Add cumulative counters to class unloading stats

compiler/x/amd64/codegen/OMRTreeEvaluator.cpp, compiler/x/amd64/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/UnaryEvaluator.cpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp, compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.hpp
Implement lpopcnt and ipopcnt IL opcodes for x86.
=> X: Implement popcnt

port/win32/omrsysinfo.c
See https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info
=> Recognize Windows Server 2025

compiler/p/codegen/OMRTreeEvaluator.cpp
- when a byte mask is loaded from a byte array the true value is represented as 1.
- expand the least significant bit so that instructions like xxsel work correctly.
=> Implement byte mask load

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64SystemLinkage.cpp, compiler/runtime/OMRCodeCacheMemorySegment.cpp
Three simple fixes for aarch64 issues that were discovered while creating JB2 with OMR on my Macbook M1.
=> Aarch64 fixes

compiler/optimizer/VPHandlers.cpp
This function created block constraints most of the time, but it would instead create a global constraint in the case of a constant string or a known object that's an instance of `java/lang/Class`.
Now it takes a boolean parameter `isGlobal`, which it uses to decide whether the new constraint should be a global constraint.
When called from `constrainNewlyFoldedConst()`, a global constraint can be created when the folding was based only on global constraints, which is similar to the way we already handle integral and null constants. This change will be important for const refs (coming later), since otherwise we could create a global constraint based on the symref of a const ref load that was just folded based on a block constraint, and the load might share its value number with others, …
=> Fix choice of global vs block constraints in addKnownObjectConstraints

compiler/optimizer/Inliner.cpp
Check for any RdBar nodes after a tree has been duplicated, and correctly anchor them to prevent an assertion failure.
Addresses https://github.com/eclipse-openj9/openj9/issues/17649
=> Anchor RdBar Nodes after Duplication in Rematerialization

compiler/il/Aliases.cpp
Fix tab in recent PR https://github.com/eclipse-omr/omr/pull/7637
=> Fix tab in Aliases.cpp

compiler/aarch64/codegen/ARM64SystemLinkage.cpp
Track whether anything needs to be allocated into the frame and do not bump the frame pointer if the frame size is zero.
Discovered in JitBuilder tests where what should be single instruction functions unnecessarily bump the stack pointer by 16 and then back. Probably not very beneficial in realistic workloads but also an easy optimization. Just be careful that methods with calls need to have a frame even if it's not otherwise needed.
@knn-k I would especially appreciate your review here.
=> AArch64: Do not allocate system linkage frame if not needed

util/a2e/atoe_utils.c
Addresses https://github.com/eclipse-omr/omr/pull/7658#pullrequestreview-2617900271.
=> Remove useless dereference

compiler/p/codegen/ControlFlowEvaluator.cpp, compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp
Improve the Math.min/max_F/D Intrinsics with xsmaxjdp and xsminjdp instructions introduced on Power9.
=> Improve the Math.min/max_F/D Intrinsics for Power9 or Later

compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/TrivialDeadBlockRemover.cpp, compiler/optimizer/VPHandlers.cpp, compiler/optimizer/ValuePropagationCommon.cpp, compiler/ras/Debug.cpp, compiler/ras/Debug.hpp
Add utility method to print TR_YesNoMaybe
Related: eclipse-openj9/openj9#17956
=> Add utility method to print TR_YesNoMaybe

compiler/ras/Debug.cpp
- Name static symrefs in JIT logs regardless of CP index
- Improve JIT tracing for string literals
This is in preparation for const refs, but the second commit is mostly general improvements.
=> Improve JIT tracing for string literals

compiler/optimizer/LocalOpts.cpp
There is a case where before block splitter, the merge block is the original fall-through block of the split block and it is also the split block's branch destination. In this case, there is only one edge from the split block to the merge block.
```
--- Before block splitter ---
BBStart <block_1>  (splitPred)
ificmpeq ------> block_2
BBStart <block_2>  (mergeNode)
```
As part of the block splitter transformation, it removes the edge from the split block to its original branch destination. It reverses the split block's branch destination to its original fall-through block. In this case the new branch destination is the same as the original branch destination, but the edge between them is now missing.
We need to create the edge if it doesn't exist.
```
--- After block splitter  ---
BBStart …
```
=> Add missing edge in block splitter

gc/base/SparseVirtualMemory.cpp
In an unlikely case SparseVirtualMemory is fragmented or configured inappropriately small, proceed with a failed allocation by returning NULL rather than asserting it's not possible.
This will help with a caller to be able to handle the situation as OutOfMemory exception (as any other allocation failure in the main heap).
=> Return NULL rather than assert in Sparse Memory alloc

compiler/optimizer/Structure.cpp
`moveNodeIntoParent` replaces the entire region with the unconditional exit node if the node is the entry of the region. It expects the region has only one sub node in this case. However, in this case the region could have contained unreachable blocks after prior optimizations and its number of the sub nodes is greater than one, which will fail the assert in `moveNodeIntoParent` that checks if the number of the sub nodes in the region equals to one. So we need to clean up the CFG before unconditional exit extraction if necessary.
Fixes: eclipse-openj9/openj9#15332
=> Remove unreachable blocks before exit extraction

gc/base/VirtualMemory.hpp
Make a few VirtualMemory methods public
=> Make a few VirtualMemory methods public

compiler/il/VectorOperations.enum
- some masked operations are missing the flag
- make description more uniform
=> Fix ILProp1::VectorMasked flag for some masked vector operations

gc/base/SparseVirtualMemory.cpp
Avoid rounding down ratio percentage
=> Adjust offheap custom size math

compiler/x/codegen/OMRTreeEvaluator.cpp
Use correct clobber evaluator for src.
=> X: Fix compressExpandBitsEvaluator

cmake/modules/platform/toolcfg/gnu.cmake
Related to https://github.com/eclipse-openj9/openj9/pull/21803
Issue https://github.com/eclipse-openj9/openj9/issues/20956
=> Set noexecstack when linking

gc/base/standard/Scavenger.cpp
Concurrent Mark kickoff heuristic threshold and the current value is expressed in terms of memory free and allocations from the default allocate space, which is Nursery for Gencon.
In a case of Concurrent Scavenger, allocations do not occur just from pure Allocate area of Nursery, but also from hybrid Allocate/Survivor area, although in a well configured heap, those allocations are about an order of magnitude smaller.
This change will adjust that allocation measurement to account for allocation from the hybrid areas, too.
The end effect is, that in cases where those allocations are significant (tight memory conditions in Nursery with no tilt and back to back CS cycles) kickoff will be delayed and Global GCs will be less frequent.
=> Account for allocations from survivor in CM kickoff

compiler/x/codegen/OMRTreeEvaluator.cpp
This commit includes a number of fixes for
vector comparision operations.
1. Grab element type from first child node
2. Fix mask inversion on AVX-2 (NE, GE, LE)
3. Fix masked comparison on AVX-2
=> x86: Fix vector comparison evaluation

compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit improves the code generated by the
fmax/fmin/dmax/dmin evaluators for AArch64.
=> AArch64: Improve fmax/fmin/dmax/dmin evaluators

cmake/modules/platform/os/zos.cmake, compiler/control/OMROptions.cpp, compiler/ras/LimitFile.cpp, ddr/include/ddr/std/sstream.hpp, ddr/include/ddr/std/string.hpp, ddr/include/ddr/std/unordered_map.hpp, fvtest/omrGtestGlue/omrGtest.cpp, fvtest/omrGtestGlue/omrTest.h, include_core/omrcomp.h, util/a2e/headers/ctype.h
=> Revert "Remove isdigit macro redefs, replace with OMR_ISDIGIT"

compiler/optimizer/ValuePropagationCommon.cpp
This commit recognizes SingleByte$Decoder.decodeToLatin1 as a converter method and then inlines it into
arraytranslate IL in the JIT.
=> Recognize SingleByte$Decoder.decodeToLatin1 as a converter method

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
Implement PPC codegen for mFirstTrue for Int16/32/64 on P9 and higher
=> Implement mFirstTrue on PPC

ddr/lib/ddr-ir/Macro.cpp
The tool ddrgen uses the port library and so reads text files via atoe support. Avoid complications on z/OS with definitions of `isdigit()`, etc. that don't play nicely with ASCII.
=> Avoid using isXX() functions from ctype.h

ddr/lib/ddr-blobgen/java/genSuperset.cpp, ddr/lib/ddr-ir/Symbol_IR.cpp, ddr/test/CMakeLists.txt
* fix comment and indentation in code
* indent with tabs consistently in `CMakeList.txt` files
=> Minor DDR cleanup

port/common/omrport.tdf, port/unix/omrsysinfo.c
Use getprocs64 to extract command line on AIX
Use getargs for user-space processes and pi_comm for others.
=> Extend SystemProcesses API implementation to AIX

port/aix/omrsl.c, port/unix/omrsl.c, port/win32/omrsl.c
Update variable names to camel case.
=> Apply OMR coding standard fixes for PRs #7810, #7793 and #7759

port/unix/omrsysinfo.c
Extend SystemProcesses API support to z/OS
Support for /proc on z/OS is enabled through APAR OA62757 integration.
Use /proc filesystem to extract command line.
Use cmdline for user space processes and comm for others.
=> Extend SystemProcesses API implementation to z/OS

port/aix/omrsl.c
Issue https://github.com/eclipse-openj9/openj9/issues/22288
=> On AIX attempt to load shared archive member even when decorate not set

compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/UnaryEvaluator.cpp
The SSE versions of many SIMD instructions,
such as pabs, require aligned loads when
using memory operands. This change prevents
unaligned loads in unary and binary SSE ops.
Issue: eclipse-openj9/openj9#22286
=> x86: Prevent unaligned unary/binary sse ops

gc/base/standard/Scavenger.cpp
Replace the trivial/passive pausing with actual scanning work.
The progress heuristic is still unchanged (will not trigger).
=> Active CS taxation

compiler/p/codegen/OMRTreeEvaluator.cpp
To avoid issues with non-VRF registers being used for VMX instructions, we want to ensure that VMX instructions are only ever used for operations on Integral types (Byte, Short, Int, Long). For `VReductionAdd`, this means using the `xxsldwi` instruction (VSX) to rotate the input vector instead of `vrld` (VMX).
=> PPC VRF/VSX register use fix for VReductionAdd

compiler/optimizer/OMRValuePropagation.cpp
Currently VP inlining is disabled at <= warm via the TR_DisableInliningDuringVPAtWarm option, and limited by the _maxSzForVPInliningWarm otherwise, but unconstrained at > warm. This patch adds a block frequency check and prevents inlining into blocks with frequency < 750 independent of opt level. It also adds an env var to allow for override.
This reduces method IL size and reduces the chances of high opt methods failing to compile due to exceeding scratch space limits or exceeding other complexity thresholds.
=> Reduce high opt inlining
