- compiler/control/CompileMethod.cpp
- compiler/control/OMROptions.cpp
- compiler/env/CompileTimeProfiler.hpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
- compiler/ras/LimitFile.cpp
- compiler/ras/OptionsDebug.cpp
The `TR_VerboseLog::writeLine*` APIs currently write the newline
character before the message being printed which is non-conventional.
Typically the expectation of a user is that any API that outputs
newline characters outputs them at the end, examples from various
languages in [1] [2] [3], and there are numerous other examples.
The reason we are making this change is because other components in OMR
will expect to be writing at the start of a newline, whether that be
stdout, stderr, or a file. The verbose log not adhering to this
expectation yields in messages getting printed one after another which
is not desirable.
[1] https://docs.python.org/3/library/functions.html#print
[2] https://docs.oracle.com/javase/8/docs/api/java/io/PrintStream.html#println-java.lang.String-
[3] …
> Write out newline character after the message in verbose output

- gc/base/TLHAllocationInterface.cpp
Add current allocated size inside TLH to traceAllocationBytes
during flushing TLH(the size inside TLH will be cleared after
flushing).
fix: https://github.com/eclipse/openj9/issues/9808
> Update traceAllocationBytes with the size inside TLH in flushing TLH

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
Aligning the entry point of a method on a particular boundary is a
performance optimization. However, the use of a threshold introduces
non-determinancy (and arguably randomness run-to-run) into any
performance benefit. Whether or not a particular method is aligned
depends on the methods that have been compiled before it. It also
doesn't take into account the "importance" of any particular method.
For instance, a method invoked millions of times is better suited to be
aligned than one only invoked a few times, but it could be rejected for
alignment because it exceeds the threshold. Unless we align every
method boundary we cannot achieve consistent performance.
As such the benefit of having a threshold is overweighed by the
complexity and non-determinism it introduces and is hence being …
> Deprecate getJitMethodEntryAlignmentThreshold

- compiler/p/runtime/PPCArrayCopy.inc
- compiler/p/runtime/ppcasmdefines.inc
Either #if or macro can fix it. I chose to go with macro, because
the lxvl dependnecy on [0-7] bit of RB which is not working with
Rest assured that 64bit instructions can run in 32bit mode, since
we only supported 64bit processors.
Temporarily put LEarraycopy back in to not break the build as well.
> Provide a fix for using 64bit instructions in 32bit assembly mode

- compiler/p/runtime/ppcasmdefines.inc
For both sldi & srdi, the macro encoding for shift-amount is incorrect.
It should be: (sh & 31) << 6 | sh & 32, instead of: sh << 5
Renaming the macro as well, in case it overrides the existing old code
unintentionally.
> Fix macro encoding errors

- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit stops generating redundant sign extension for byte and
halfword in b2iEvaluator() and s2iEvaluator() respectively.
Issue:#4856
> Improve Code generation for loading signed byte/halfword

- compiler/aarch64/codegen/MemoryReference.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
This commit removes the unused _length field from OMRMemoryReference.
It also adds constructors without the length parameter.
Issue: #4137
> AArch64: Remove length parameter from MemoryReference (step 1)

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
For Concurrent Scavenger, when a Mutator releases VM access, we now
clear the cache eagerly, even though it might just be deactivated and
not pushed to scanning yet.
Otherwise, deferring the clearing at the point of pushing an inactive
cache may cause a subtle race with a third thread doing it on behave of
owner thread, later toward the end of concurrent cycle.
With this change clearCache can only occur in the context for owning
thread, and never in the context of a third thread (signaling GC thread
for final scanning, or Mutator thread doing exclusive VM access thread
pass)!
Small downside is that we may clear the cache (effectively check and
create if there is a potential remainder) multiple times during CS
cycle, before it's finally abandoned.
Newly introduced INACTIVE cache flag is …
> ClearCache on deactivate

- compiler/optimizer/VPHandlers.cpp
Code in `isArrayCompTypeValueType` was checking the array component type for the type associated with a constraint, assuming that it must represent an array type, without first checking that the constraint definitely held an array type.  That could lead to segmentation faults for the garbage component type.
Added the missing check to confirm that the constraint is definitely for an array type.
> Check whether type for VP constraint is definitely an array

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/MemoryReference.hpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit removes the unused length parameter from calls to
MemoryReference constructors.
It also removes the old constructors with the length parameter.
It depends on eclipse/openj9#10023.
> AArch64: Remove length parameter from MemoryReference (step 3)

- port/unix_include/omrsock.h
This header is responsible for defining the in6_addr struct. This type
is used in the header <netinet/tcp.h>. On some versions of AIX, tcp.h
does not include in.h (despite using types defined there), so we have to
manually include it before tcp.h. This isn't a problem on other posix
platforms.
Fixes: #5360
> Include <netinet/in.h> in omrsock.h

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/arm/codegen/OMRTreeEvaluator.hpp
- compiler/arm/codegen/OMRTreeEvaluatorTable.hpp
- compiler/il/OMRILOpCodeProperties.hpp
- compiler/il/OMRILOpCodesEnum.hpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/LoopReducer.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/optimizer/OMRSimplifierHandlers.hpp
- compiler/optimizer/OMRSimplifierTableEnum.hpp
- compiler/optimizer/ValuePropagationTable.hpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- compiler/ras/Tree.cpp
- compiler/riscv/codegen/ControlFlowEvaluator.cpp
- compiler/riscv/codegen/OMRTreeEvaluator.hpp
- compiler/riscv/codegen/TreeEvaluatorTable.hpp
- compiler/x/amd64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.hpp
- compiler/x/i386/codegen/OMRTreeEvaluatorTable.hpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- compiler/z/codegen/OMRTreeEvaluatorTable.hpp
Removed definitions, declarations, properties and all other lists/enums that define the behavior of the unsigned IL Opcodes in `Equality compare` and `Equality compare and branch`. The above ILOpcodes will be completely removed from OMR after this PR.
Note that this PR need to be merged simultaneously with https://github.com/eclipse/openj9/pull/8939
Issue:#2657
> Remove definitions of deprecated unsigned IL Opcodes of Equality Compare and branch

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
The Power code generator previously had a method on TR::CodeGenerator to
delete an instruction from the list of instructions. However, this
method is no longer used, as Instruction::remove is the preferred way of
doing this now. To reflect this, the old method has now been removed.
> Remove CodeGenerator::deleteInst from the Power codegen

- omrmakefiles/rules.win.mk
This is motivated by eclipse/openj9#10099 so that .map files can be made available in a debug image for all shared libraries.
> Put Windows .map file in same folder as .dll

- fvtest/porttest/omrvmemTest.cpp
Came across a couple of issues while doing other work in this file:
- Fix order of params in debug output
- Clean up conditional page flags access
> omrvmemTest minor cleanups

- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/OMRInstruction.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
This commit adds `bookKeepingRegisterUses` method to register dependency
and memory reference and changes instruction classes to call them.
This commit also removes `incTotalUseCount` method from memory reference class.
Because `incTotalUseCount` method of register dependency class is used from
instruction class of OpenJ9 side, it will be removed after the instruction class
is changed to use `bookKeepingRegisterUses`.
> AArch64: Enhance bookkeeping of register use count

- gc/base/GCExtensionsBase.hpp
Enabling the low pause optimization by default. High level description
and a series of PRs that implements the optimization can be found here:
https://github.com/eclipse/omr/issues/4787
> Enable CS Exhaustive Termination by default

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
This commit refactors an x86 codegen query to the common
codegen such that it can be used by the Z codegen as well
inside the supportsMergingGuards() routine.
> Use CG query to check for guard merging support

- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
This commit removes `incTotalUseCount` method from OMRRegisterDependencyConditions.
Depends on:
https://github.com/eclipse/omr/pull/5385
https://github.com/eclipse/openj9/pull/10140
> AArch64: Remove incTotalUseCount method from OMRRegisterDependencyConditions

- cmake/modules/OmrCompilerSupport.cmake
> CMake: Fix typos in aarch64 spp handling

- gc/base/Dispatcher.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/ParallelDispatcher.cpp
- gc/base/ParallelDispatcher.hpp
**Assign task to threads at hand (earliest available) to start task independently of which threads are available:**
- Forgo selecting specific threads and updating thread tables prior to notification.
- Use threads in the order they wake up/reacquire slave thread mutex after notification.
**Hybrid approach to notifying threads:**
When using a small set of threads from a large pool, it can be significantly cheaper to do to individual notifies (`omrthread_monitor_notify`) as compared to `omrthread_monitor_notify_all`. However, for large set of threads, it will be more expensive to wake up threads with individual notifies.
- Introduced `dispatcherHybridNotifyThreadBound` (Individual notifies for count < MIN(bound, maxThreads/2), otherwise notify_all))
Background & Results: …
> Dispatcher Rework: Thread Selection & Hybrid Notification

- compiler/p/codegen/OMRInstOpCode.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/PPCInstruction.cpp
- compiler/p/codegen/PPCOpsDefines.hpp
This PR adds code to prevent gr0 from being automatically assigned to the RA field of all extended mnemonics of `isel`, since these instructions will treat this as having a value of 0 regardless of the actual value stored in gr0. Additionally, the way in which gr0 exclusions are specified has been changed to use an instruction property flag, as proposed by #5297.
> Add a gr0 exclusion for RA on isel extended mnemonics

- compiler/codegen/Relocation.cpp
- compiler/codegen/Relocation.hpp
Previously, there was a relocation kind for filling in the absolute
address of an instruction. This was completely unused and is also
completely redundant, as one can simply place a label immediately before
or after the instruction in question and relocate using that instead.
For that reason, this relocation kind has been removed.
> Remove InstructionAbsoluteRelocation

- include_core/omrutil.h
- util/omrutil/argscan.c
Merge omrargscan.[c|h] in support of porting the refactored OpenJ9 shared cache into OMR.
Issue: #4610
Signed-off-by: Mark Thom <mark.thom@unb.ca>
> Merge the omrargscan library from OpenJ9

- gc/base/MemorySubSpaceUniSpace.cpp
- gc/base/MemorySubSpaceUniSpace.hpp
- gc/base/j9mm.tdf
The expansion and contraction of flat memory for tenured space, used by the optthuput/opavgpause
heap and gencon old gen, is governed by several criteria. Prior to this change, it evaluated a
simple minimum and maximum heap free percentage then checked the GC STW time overhead. If the
current heap free percentage was greater than the configured max free, the heap would not be
expanded even with very high GC time overhead. This change employs a heuristic to offset the
allowable maximum heap free percentage by a factor of the GC time overhead to allow the GC to
expand even with high free memory percentage when the GC time overhead is very high.
For example, with max free memory of 60% and a max CPU overhead of 13%, the heap would not be
expanded when the heap is 70% free even if the GC time …
> Add heap free ratio heuristics for heap expansion

- compiler/codegen/CodeGenPrep.cpp
When lowering newvalue to new, stores to fields of reference type are generated. When using compressed references, the references being stored must be compressed. These commits ensure this happens correctly.
> Ensure newvalue lowering correctly handles compressed refs

- compiler/z/codegen/OMRTreeEvaluator.cpp
This commit improves relo checks to account for various types
of compilations such as AOT, remote, AOTaaS, and a regular JIT
compile.
> Improve relocation record checks and avoid generating PC relative instructions for JITServer

- compiler/optimizer/OMRTransformUtil.cpp
- compiler/z/codegen/OMRCodeGenPhase.cpp
fold the two calls with the value as in #5402
Signed-off-by: James Guan <jamesgua@ca.ibm.com>
> Remove unnecessary uses of getOptimizationPhaseIsComplete()

- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit changes register allocation in extendToIntOrLongHelper()
for AArch64.
> AArch64: Change register allocation in i2lEvaluator, etc.

- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit improves code generation for loading unsigned short/byte
for AArch64.
The AArch64 compiler used to generate `ldrshimmx` (signed halfword)
instruction followed by `uxthx` instruction for zero extension, for
an IL sequence `sloadi - su2i`.
This commit uses `ldrhimmx` (unsigned halfword) instruction instead,
and there is no need for zero extension.
It also does the similar for loading unsigned byte.
Closes: #5343
> AArch64: Code generation for loading unsigned short/byte

- fvtest/porttest/omrttyTest.cpp
Rename PortTTyTest -> PortTtyTest
> Fix naming on PortTTyTest

- gc/base/MemorySubSpaceUniSpace.cpp
- gc/base/MemorySubSpaceUniSpace.hpp
- gc/base/j9mm.tdf
Reverts eclipse/omr#5327
Change caused intermittent serbuf test failures on all platforms
Signed-off-by: Jason Hall jasonhal@ca.ibm.com
> Revert "Add heap free ratio heuristics for heap expansion"

- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit verifies floating point values by the respective IEEE 754
representation, generates the relevant 8-bit immediate values,
implements FMOV (imm) instruction, and does the binary encoding
associated to the instruction.
Partially Fixes: #3377
> FMOV (imm) instruction implementation

- jitbuilder/compile/ResolvedMethod.hpp
Initializes _externalName as in the other two
constructors.
Signed-off-by: Petar Jelenkovic <pjelenko@unb.ca>
> Initialize external name for ResolvedMethod

- compiler/infra/OMRCfg.cpp
- compiler/infra/OMRCfg.hpp
The motivation behind adding this new method is that monitor elimination in openj9 needs to be able to add a new exception edge before removing an existing one. See this issue: https://github.com/eclipse/openj9/issues/9754.
The method `OMR::CFG::addExceptionEdge` checks for existing exception edges
before adding a new one. In cases where an exception edge already exists, it
silently fails to add a new edge.
Some optimizations which rearrange exception edges may want to add a new
exception edge before removing an existing one. This is not possible to do with
`OMR::CFG::addExceptionEdge`. This commit adds a new method which will add an
exception edge even when one already exists.
> Add OMR::CFG::addExceptionEdgeUnchecked method

- compiler/p/codegen/MemoryReference.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRMemoryReference.hpp
- compiler/p/codegen/PPCAOTRelocation.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCDebug.cpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
This PR adds binary encoder support for encoding PC-relative offsets on the new POWER10 prefixed loads and stores. There are currently two different ways of specifying the displacement:
1. Using an offset relative to a `TR::LabelSymbol`
2. Using a constant displacement
The first method is meant to be the standard way of doing this, with the second method existing only to allow the displacement field to be forced to be 0 when a PC-relative load/store's displacement will be patched.
> Implement binary encoding for POWER10 PC-relative loads and stores

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRConstantDataSnippet.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
Currently, the Power codegen has a decent amount of special handling to deal with trying to load the StartPC of the current method, including a particularly egregious hack in `ConstantDataSnippet` that would cause the address of StartPC itself to be patched on the instructions rather than the address of a slot in the snippet from which to load. In addition to being generally very confusing and inconsistent, this hack makes modifications to this snippet (such as those required for #5367) quite difficult without inadvertently breaking things.
Since this functionality was introduced, the Power codegen has become capable of generating and relocating a sequence to load the address of an arbitrary label into a register in a much more reasonable manner. By instead generating a label at StartPC …
> Switch to using a label for StartPC in the Power codegen

- cmake/modules/FindDiaSDK.cmake
If DiaSDK_ROOT is not set, attempt to determine a value by looking up
the DLL registered to handle the COM GUID currently used by the DIA API
> CMake: Add fallback measure to find DIA SDK

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit adds the opcodes for the MOVI (Imm) instruction for
loading the constant 0.0 into an FP register and implements the
generateTrgInstruction() function for this operation.
Closes: #5415
> MOVI (Imm) instruction implementation for 0.0

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/ARM64OutOfLineCodeSection.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/codegen/CodeGenGC.cpp
- compiler/ras/Debug.cpp
This commit implements OutOfLineCodeSection for aarch64.
Some parts of OutOfLineCodeSection were already implemented.
This commit adds missing parts.
The major parts of OOL section are following:
1. Take a snapshot of all register states at the merge point and restore
the states at the end of the cold path.
2. Take a snapshot of all virtual - real register assignments at the branch
instruction (*) to the entry label of the cold path and attach it as register
dependencies at the entry label.
3. Create a list of all spilled registers in main line and the hot path until
the branch instruction (*) and attach it as register dependencies (SpilledReg)
at the entry label.
4. Protect any spilled register's backing storage if the register is spilled
in a lower "depth" path and reuse the same …
> AArch64: Implement OutOfLineCodeSection

- compiler/optimizer/LocalLiveRangeReducer.cpp
This commit changes the condition for checking constraints with allocationFence
in TR_LocalLiveRangeReduction::isAnySymInDefinedOrUsedBy().
> Checking the constraints with allocationFence

- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit fixes su2i/bu2iEvaluator() for AArch64.
The evaluators generated wrong code when the child node had two or
more references.
> AArch64: Fix su2i/bu2iEvaluator()

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
When trying to load the address of a label into a register on 64-bit
machines, it is necessary to allocate a pTOC entry to be filled in
later. Previously, such entries were being filled in immediately after
binary encoding, which was fine as long as the label in question was not
part of a snippet.
However, there are several snippets in OpenJ9 which require that their
addresses be loaded into a register. Previously, this was handled
individually by each snippet by patching the mainline code manually with
the correct address. Not only does loading addresses this way cause
needless code duplication and other such issues, it also makes it very
difficult to take advantage of POWER10 PC-relative paddi instructions
in a uniform manner.
In order to prepare for OpenJ9 to be able to handle this in …
> Move pTOC label processing into processRelocations

- .github/labeler.yml
Modify the labeler GitHub Action to add the `comp:utilities` label to
PRs which modify files in `util` directory and `comp:core` to PRs which
modify files in `include_core` directory.
> Add comp:utilities label to util and comp:core to include_core

- port/common/omrstr.c
Re-write guard condition involving signed and unsigned types to avoid undefined behavior.
Without this change, gcc 10 complains:
```
In function ‘convertPlatformToWide’,
inlined from ‘convertPlatformToMutf8’ at ../../../../../../../omr/port/common/omrstr.c:2524:35,
inlined from ‘omrstr_convert’ at ../../../../../../../omr/port/common/omrstr.c:264:13:
../../../../../../../omr/port/common/omrstr.c:3132:15: error: writing 2 bytes into a region of size 0 [-Werror=stringop-overflow=]
3132 |   *terminator = 0;
|   ~~~~~~~~~~~~^~~
../../../../../../../omr/port/common/omrstr.c: In function ‘omrstr_convert’:
../../../../../../../omr/port/common/omrstr.c:2486:10: note: at offset -450 to object ‘onStackBuffer’ with size 256 declared here
2486 |  uint8_t onStackBuffer[CONVERSION_BUFFER_SIZE];
| …
```
> Fix compiler warning

- compiler/optimizer/OMRCFGSimplifier.cpp
- compiler/optimizer/OMRCFGSimplifier.hpp
Patterns similar to BNDCHK but throws different exceptions is matched
and simplified with a BNDCHK that branches to appropriate exception
block.
This essentially checks for array index bound check patterns, which
starts with a ificmp followed by another ificmp and either branches to
a block that throws exception or executes the non-exception behavior.
Upon matching such pattern, it replaces the two ificmp checks with a
BNDCHK with a catch-all block that jumps to the exception block. This
ensures the returned exceptions are correct, while simplifies the
pattern for non-exception cases (BNDCHK -> non-exception case).
> Recognizes patterns like BNDCHK and simplifies them

- port/common/omrstr.c
* fix compile error on win32
* also, use sizeof(uint16_t) instead of '2'
> Fix signed/unsigned comparison

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
When the OpenJ9 optimizer inlines Integer.rotateRight, it creates
`irol` node with `ineg` child node to adjust shift amount.
AArch64 has instruction for rotate to right only, so we need to negate
the shift amount again. This commit changes `irolEvaluator` to
use child node of `ineg` node as shift amount if the `ineg` node is not commoned.
Also, this commit enhances trace output to print `rorx`/`rorw` instruction
instead of `extrx`/`extrw` instruction.
> AArch64: Enhance irol evalutor to cancel out double negation

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
This commit fixes register allocation in iselectEvaluator() for AArch64.
The evaluator has to allocate a collectedReferenceRegister for its
result when the opCode is TR::aselect.
> AArch64: Fix register allocation for aselect

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds two JIT utilify functions for AArch64, addConstant32/64().
> AArch64: Utility functions addConstant32/64()

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/codegen/CodeGenPrep.cpp
- compiler/il/OMRIL.cpp
- compiler/il/OMRILOps.hpp
- compiler/optimizer/LoopReducer.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/UnaryEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/BinaryCommutativeAnalyser.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
Remove all references to the IL Opcodes in the `load` category listed in #2657.
Issue: #2657
> Remove references of deprecated  load IL opcode

- gc/base/MemorySubSpaceUniSpace.cpp
- gc/base/MemorySubSpaceUniSpace.hpp
- gc/base/j9mm.tdf
The expansion and contraction of flat memory for tenured space, used by the optthuput/opavgpause
heap and gencon old gen, is governed by several criteria. Prior to this change, it evaluated a
simple minimum and maximum heap free percentage then checked the GC STW time overhead. If the
current heap free percentage was greater than the configured max free, the heap would not be
expanded even with very high GC time overhead. This change employs a heuristic to offset the
allowable maximum heap free percentage by a factor of the GC time overhead to allow the GC to
expand even with high free memory percentage when the GC time overhead is very high.
For example, with max free memory of 60% and a max CPU overhead of 13%, the heap would not be
expanded when the heap is 70% free even if the GC time …
> Add heap free ratio heuristics for optthruput heap expansion

- include_core/omrhashtable.h
Add a new flag in J9HashTableState to control the behaviour when 
iterating the hash table.
Related to OpenJ9 PR https://github.com/eclipse/openj9/pull/10300
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
> Add a new field into J9HashTableState

- compiler/p/codegen/OMRInstOpCode.hpp
Add missing return statements (compiler doesn't know that `TR_ASSERT_FATAL` never returns).
Without this, we have these warnings (many, many times):
```
00:27:19.227  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/build/aix-ppc64-normal-server-release/vm/compiler/../omr/compiler/p/codegen/OMRInstOpCode.hpp", line 210.7: 1540-1101 (W) A return value of type "signed char" is expected.
00:27:19.227  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/build/aix-ppc64-normal-server-release/vm/compiler/../omr/compiler/p/codegen/OMRInstOpCode.hpp", line 227.7: 1540-1101 (W) A return value of type "signed char" is expected.
```
> Fix AIX compile warnings

- gc/base/GCExtensionsBase.hpp
- gc/base/HeapVirtualMemory.cpp
Commits memory during initial Heap Inflation or Heap Expansion by writing 0s.
Default: Disabled
> Adding Global GC Flag to pretouch Heap Memory

- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/S390Instruction.cpp
This routine will return true if a method call is implemented using an internal runtime helper.
> Add new callUsesHelperImplementation

- compiler/p/codegen/OMRPeephole.cpp
- fvtest/compilerunittest/CMakeLists.txt
- fvtest/compilerunittest/CodeGenTest.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
- fvtest/compilerunittest/p/Peephole.cpp
The Power code generator's load-hit-store peephole invokes undefined
behaviour by always assuming that the current instruction is a MemSrc1
instruction and that the next instruction is a Trg1Mem instruction. This
could cause a segfault if the current instruction is the last
instruction or if the next instruction has a load opcode, but is not a
Trg1Mem instruction. This has now been fixed.
Fixes: #5418
> Fix undefined behaviour in the Power LHS peephole

- azure-pipelines.yml
- fvtest/compilertest/tests/X86OpCodesTest.cpp
- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilertriltest/CompareTest.cpp
- fvtest/compilertriltest/JitTest.hpp
- fvtest/compilertriltest/LinkageTest.cpp
- fvtest/compilertriltest/LogicalTest.cpp
- fvtest/compilertriltest/MaxMinTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
- fvtest/compilertriltest/TypeConversionTest.cpp
- fvtest/jitbuildertest/JBTestUtil.hpp
- fvtest/tril/tril/parser.cpp
- fvtest/tril/tril/simple_compiler.cpp
Tril Tests are currently not running on Windows. Fix Tril Tests errors that occurs under Windows and enable it for Windows Azure builds. Note that `Tril Test` refers to the two ctest units in `fvtest`: `comptest` and `triltest`.
Details about the fix is stated in issue #5324 
Issue: #5324
> Enable tril tests on Windows

- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
`_supportedArch` shouldn't be initialized in this constructor because it's part of the old implementation.
> Revert change to OMR::CPU()

- gc/base/GCExtensionsBase.hpp
- gc/base/ParallelDispatcher.cpp
- gc/base/ParallelDispatcher.hpp
Fixes https://github.com/eclipse/openj9/issues/10171
For details regarding the reverted changes being reintroduced here, please refer back to the original PR (https://github.com/eclipse/omr/pull/5336). This PR details the issue with the original change and the patch to fix it.
Initial changes caused intermittent test failures/hangs. This was caused by a race (introduced by rework) between task dispatch and thread startup routine. This occurred when a task was dispatched before a thread finished its startup routine - before the thread got a chance to enter its main loop (in worker entryPoint) and "wait for the task". This caused the thread to miss wakeUp notification and wait indefinitely.
Before the rework, thread status was updated prior to task being dispatched. Hence, a task dispatched …
> Reintroduce Dispatcher Rework with fix

- util/omrutil/CMakeLists.txt
- util/omrutil/j9memclr.cpp
This commit replaces `PFD` with `memset` as the default way to zero
object heap memory. `PFD` can be toggled back on by setting environment 
variable `PFD_TO_ZERO_OBJECT_HEAP_MEMORY_ENABLED`
> Swapped `PFD` with `memset` to 0 object heap mem

- compiler/control/OMROptions.cpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRConstantDataSnippet.cpp
- compiler/p/codegen/OMRConstantDataSnippet.hpp
- compiler/p/codegen/OMRMachine.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCOpsDefines.hpp
- compiler/p/codegen/TreeEvaluatorVMX.cpp
This PR implements the majority of the changes proposed in #5367 to replace and disable the pTOC when POWER10 support is enabled. Generally, this PR switches to using `ConstantDataSnippet` with PC-relative loads for most 64-bit and FP constants, applies the `disableToc` option by default, switches to using PC-relative `paddi` when loading label addresses, and adds some smaller exploitations of these new instructions when run with POWER10 support enabled.
This PR is currently marked as WIP since it causes issues with the LHS peephole (#5418) due to creation of load instructions with a `Trg1Imm` instruction class. This issue must be corrected before this PR can be merged.
> Replace and disable the pTOC on POWER10

- util/omrutil/j9memclr.cpp
This fixes ppc build failures due to https://github.com/eclipse/omr/pull/5430
> Explicit conversion to char* from void*

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/il/OMRIL.cpp
- compiler/il/OMRILOps.hpp
- compiler/optimizer/LoopReducer.cpp
- compiler/optimizer/VPHandlers.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
Remove all references to the IL Opcodes in the `Store` category listed in #2657.
Did not remove the reference of `TR:iustore` in `DebuggingCounters.cpp` as
the opcode is used in a function argument. Will investigate on this
in the future.
Issue: #2657
> Remove references of deprecated Store IL Opcode

- compiler/optimizer/LocalAnalysis.cpp
`opCodeFor*Load/Store` does widening magic in Openj9 for data type
narrower than 32 bits. It is used only for narrow java fields, not
applicable to other data. However, LocalAnalysis uses it for everything
which is causing a problem for non-java-field data. This PR will fix the
problem by introducing `opCodeForCorresponding*Load/Store` API that
takes a load/store opcode, and return its corresponding store/load API.
The opcode passed in and the opcode returned will have matching data
type.
> Fix LocalAnalysis

- compiler/aarch64/env/OMRCPU.hpp
- compiler/arm/env/OMRCPU.hpp
- compiler/env/OMRCPU.hpp
- compiler/p/env/OMRCPU.cpp
- compiler/p/env/OMRCPU.hpp
- compiler/x/env/OMRCPU.hpp
- compiler/z/env/OMRCPU.hpp
This commit adds `getSupportsHardware32bitRotate` and `getSupportsHardware64bitRotate`
to CPU class.
> Add APIs answering if cpu supports integer rotation

- fvtest/compilertest/tests/OpCodesTest.cpp
- fvtest/compilertest/tests/OpCodesTest.hpp
- fvtest/compilertest/tests/PPCOpCodesTest.cpp
- fvtest/compilertest/tests/PPCOpCodesTest.hpp
- fvtest/compilertest/tests/X86OpCodesTest.cpp
- fvtest/compilertest/tests/X86OpCodesTest.hpp
This test checked that `bdiv`, `brem`, `sdiv` and `srem` are unsupported. This
is bogus - these should be supported.
> Remove bogus tests from JITCrossPlatformsOpCodesTest.UnsupportedOpCodesTest

- cmake/modules/platform/arch/s390.cmake
Appears to fix a crash regarding the SIZE_MAX macro. Using -D_LONG_LONG,
as that is what is specified in the makefiles, although going forward
we may want to look at using -qlonglong instead
> CMake: enable _LONG_LONG definition on s390

- compiler/optimizer/GlobalRegisterAllocator.cpp
- compiler/optimizer/GlobalRegisterAllocator.hpp
A number of fields are either not used or are data structures that are
never populated.  Remove and fold code.
* _gotoCreated
* _storeSymRef
* _nodesToBeCHecked
* _seenInternalMethods
* _performCellCount
* _allocatedPerformCellSymRefs
* _nodeTriplesToBeChecked
* _defIndexToTempMap
* _rejectedSignExtNodes
> Remove deprecated fields from GlobalRegisterAssigner

- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/schema.xsd
Example:
`<object-monitors candidates="17" cleared="0"  />`
> VGC: report Object Monitors

- CODEOWNERS
Given how tightly coupled the optimizer is to the IL I am adding myself as an
owner of the IL since I want to be involved in the designs/reviews and be aware
of impacts on the optimizer of any such changes.
> Add Andrew Craik as IL code owner

- port/unix/omrsharedhelper.c
strncpy() is replaced with strcpy() in order to avoid warnings/errors
which lead to failure of AdoptOpenJDK11 build (riscv) with GCC version 9.
Issue: #5484
Co-authored-by: Damian Diago D'monte <damian.dmonte@unb.ca>
Co-authored-by: Mark Thom <markjordanthom@gmail.com>
Signed-off-by: Damian Diago D'monte <damian.dmonte@unb.ca>
> Replace strncpy with memcpy to avoid AdoptOpenJDK11 build error

- cmake/modules/FindDiaSDK.cmake
if(EXISTS ...) does not auto expand variables, like other if() commands
> CMake: Fix typo in FindDiaSDK

- compiler/p/codegen/OMRInstOpCode.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
For future use, the Power codegen's instruction properties table
contains a field called minimumALS that describes the first processor
architecture which introduced a given instruction. Previously, this used
the TR_Processor enum, which has since been deprecated in favour of
using the OMRProcessorArchitecture enum from the port library. To keep
this field consistent, it has also been changed to use
OMRProcessorArchitecture.
Signed-off-by: Benjamin Thomas <ben@benthomas.ca>
> Switch the Power minimumALS to use OMRProcessorArchitecture

- gc/base/Configuration.cpp
- gc/base/GCExtensionsBase.hpp
When this flag is on, compressed reference shift is set to 3 if possible.
> Add shouldForceLowMemoryHeapCeilingShiftIfPossible flag to gc extensions

- compiler/compile/Compilation.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
This is needed so that the codegen is able to set the correct
flags when initializing.
> Explicitly specify target in Compilation constructor

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/aarch64/codegen/OpBinary.cpp
- compiler/aarch64/env/OMRCPU.hpp
This commit implements fsqrt/dsqrtEvaluator() for AArch64.
> AArch64: Implement fsqrt/dsqrtEvaluator()

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/S390Instruction.cpp
- compiler/z/codegen/S390Instruction.hpp
Label target NOPs was a feature on the Z codegen which inserted padding
NOP bytes before labels to align them to cache boundaries. This was an
experimental feature for performance which did not pan out and is
currently unused (disabled by default). We do not envision padding
labels for cache alignment in the future, especially in the way things
are currently implemented as we do now support an ALIGN
pseudo-instruction for this purpose.
> Deprecate label target NOPs on Z

- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/FPTreeEvaluator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRPeephole.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OpMemToMem.cpp
- compiler/z/codegen/S390GenerateInstructions.cpp
- compiler/z/codegen/TranslateEvaluator.cpp
- compiler/z/env/OMRCPU.hpp
There are numerous reasons why this change is warranted which are
described below:
- We do not have access to z9 machines to test the project on so the
current unofficial support is untested
- z/OS 2.2 is the minimum supported OMR OS version which has an ALS of
z10, so it is not an issue to drop z9 support from the perspective of
z/OS
- SLES 12, RHEL 7.4, and Ubuntu 16.04 are the minimum supported OS
versions for Linux, and according to [3] z9 is not supported on any of
the OS version specified
- In addition to Centos 7.4 which is based off of RHEL 7.4, meaning
there is no support for z9 systems either
- z9 has been out of service since January 2019 [2]
- Updating the `-march` build flags will allow the compiler to build
the project using z10 instructions which can allow for better C/C++ …
> Bump ALS on Z to z10

- compiler/z/codegen/OMRPeephole.cpp
> Deprecate uses of getSupportsArch in Z codegen

- compiler/z/codegen/OMRTreeEvaluator.cpp
Relocatable compiles such as remote compilations in openj9 don't allow the use of PC relative instructions like LARL. This commit prevents the use of such an instruction when
tring to load a methodPointerConstant.
> Use Snippet to load methodPointer in remote compile

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit fixes evaluators where `TR::CodeGenerator::decReferenceCount()`
is issued before a `TR::Node::setRegister()`, which kills the register too early.
> AArch64: Fix order of calls to maintain the proper live state of registers

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
Add `stopUsingDepRegs` to the register dependency class for properly killing
temporary registers added to the dependency.
> AArch64: Add a method to kill temporary registers added to register dependency

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/ras/Debug.hpp
Implement Register Association for aarch64.
- Introduce `assocreg` pseudo instruction.
- Keep track of the real register to virtual register mappings
which are set up by register dependencies.
- Emit `assocreg` instructions at the end of every extended basic block.
- Emit `assocreg` instructions when setting up register dependencies.
- In register assignment phase, update virtual register to real register mappings
when we encounter an `assocreg` instruction.
- Enhance `findBestFreeRegister` and `freeBestRegister` to use register assocations.
> AArch64: Enable Register Association

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/riscv/codegen/ControlFlowEvaluator.cpp
- compiler/riscv/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
In the codegen for `aselect` nodes, if at least one of the possible values of the `aselect` is the address of a collected reference, then the result register for the `aselect` node should be flagged as a collected reference.
This PR addresses 2 existing issues related to collected references in `aselect` nodes:
1. On some platforms, the evaluator for `aselect` nodes did not check for collected references or checked incorrectly. This PR ensures that the correct check is done and that `setContainsCollectedReference()` is called on the result register if necessary.
2. On some platforms, `gprClobberEvaluate` was used to generate a register for the result of the `aselect` node. In some cases, `gprClobberEvaluate` will allocate a new register to hold the given value. In these cases, it should …
> Fix bugs in codegen for aselect nodes where register not flagged as collected reference

- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/PPCSystemLinkage.cpp
After disableTOC is turned on in POWER10 and TOCBaseRegister is about to
be recovered as a usual preserved register, we should get rid
of any reference to TOCBaseRegister. Otherwise, we will crash
in register assignment phase.
We set the baseRegister in the fake memRef to NULL
instead, given the pTOC is full by definition due to disableTOC.
Set up gr12 for systemLinkage dispatch for LE Linux naturally
through PC-relative constant snippet or direct materialization.
> Stop referencing TOCBaseRegister on POWER10

- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRRegister.hpp
This commit changes `findFreeBestRegister` and `freeBestRegister`
to use live register information for better decision.
> AArch64: Change Register Assigner to use live register information

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
This commit changes register dependency class to set up
live register information.
> AArch64: Change register dependency to set up live register information

- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit fixes a problem of memory reference when
root node is indirect load and the child of that node
is const. The problem was introduced by OMR #5520.
When the problem is exposed, `_baseRegister` is NULL.
This change evaluates the `base` node so that the valid value
is set to `_baseRegister` in `populateMemoryReference`.
> AArch64: Fix memory reference for indirect load of const node

- compiler/aarch64/codegen/OMRCodeGeneratorUtils.hpp
- compiler/aarch64/codegen/OMRInstruction.cpp
- compiler/aarch64/codegen/OMRInstruction.hpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
This commit makes following changes to register dependencies and instruction class.
- Change `addDependency()` helper method to set place holder flag of virtual register
if the virtual register is allocated in the method.
- Add `useRegister()` method to `OMR::ARM64::Instruction` class to reset place holder
flag if the virtual register is actually used by an instruction.
Depends on https://github.com/eclipse/omr/pull/5528
> AArch64: Use placeholder registers

- ddr/tools/ddrgen/CMakeLists.txt
Ensures that omrsig can be found when executing omr_ddrgen
> CMake: Add omrsig to omr_ddrgen rpath on aix

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit enables Live Registers for aarch64 code generator.
Depends on:
https://github.com/eclipse/omr/pull/5516
https://github.com/eclipse/omr/pull/5526
https://github.com/eclipse/omr/pull/5527
https://github.com/eclipse/omr/pull/5528
https://github.com/eclipse/omr/pull/5529
https://github.com/eclipse/omr/pull/5530
> AArch64: Enable Live Registers

- compiler/il/OMRBlock.cpp
- compiler/optimizer/RegDepCopyRemoval.cpp
- compiler/optimizer/RegDepCopyRemoval.hpp
- compiler/ras/ILValidationRules.cpp
RegDepCopyRemoval is the last ran optimization which intends to reduce register shuffling due to global register dependencies. It was generating tree where we have a PassThrough Child under PassThrough to copy node to new virtual register. This tree was not working well with the post GRA block splitter. Issue was that PassThrough child encountered in GlRegDeps was anchored to tree top. In postGRA block splitter, it records the regStores encountered before the GlRegDeps in extended basic block to guide decision on which register to chose for the node after split point.In this commit, adding changes to both splitPostGRA block splitter and RegDepCopyRemoval optimization so that we can split the blocks after later has run.
> Changes in RegDepCopyRemoval for splitPostGRA block splitter

- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/GenerateInstructions.cpp
- compiler/p/codegen/MemoryReference.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRLinkage.cpp
- compiler/p/codegen/OMRMachine.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRMemoryReference.hpp
- compiler/p/codegen/OMRRegisterDependency.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCInstruction.cpp
- compiler/p/codegen/PPCSystemLinkage.cpp
- compiler/p/codegen/TreeEvaluatorVMX.cpp
- compiler/p/codegen/UnaryEvaluator.cpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
- fvtest/compilerunittest/p/MemoryReferenceExpansion.cpp
- fvtest/compilerunittest/p/Peephole.cpp
- fvtest/compilerunittest/p/Util.hpp
This PR does the following:
-Add static helper methods for each MemoryReference constructor
-Replace all direct calls to MemoryReference constructors with corresponding static helpers
> Provide Factory Methods for Power MemoryReference objects

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRInstOpCodeEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit changes the code generation in fselectEvaluator() for
AArch64, using the fcsel instruction.
> AArch64: Improve fselectEvaluator() using fcsel

- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/p/codegen/GenerateInstructions.cpp
- compiler/p/codegen/OMRInstOpCodeEnum.hpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRRegister.hpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCInstruction.cpp
- fvtest/compilertriltest/SelectTest.cpp
This PR performs major refactors primarily focusing on the `*select` evaluators in the Power codegen:
- Split floating-point and integer select evaluation into two separate evaluators
- Switch from a control flow pseudoinstruction to internal control flow for the branching sequence
- Add an optimization to switch the order of the operands to avoid register shuffles due to `gprClobberEvaluate`
- Exploit `isel` to perform branchless integer selects on POWER10
- Add a general API for evaluating a node to a condition register bit, reusing infrastructure from the newly refactored compare evaluators
- Move compare operand flipping into `evaluateThreeWayIntCompareToConditionRegister`
- Improve Tril test coverage for these evaluators
> Refactor the Power select evaluators

- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrUtility.cmake
- cmake/modules/ddr/DDRSetStub.cmake.in
- cmake/modules/ddr/GenerateStub.cmake
Pass paths through cygpath when generating ddr files, so  that they will
be understood by msvc
> CMake: Add support for cygwin paths when using msvc

- compiler/optimizer/OMRValuePropagation.hpp
- compiler/optimizer/ValuePropagationCommon.cpp
Transformation from Unsafe.copyMemory to System.arrayCopy does not belong to OMR as it is OpenJ9 specific.
> Remove Unsafe.copyMemory transformation from OMR

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/env/OMRCPU.cpp
- compiler/p/env/OMRCPU.hpp
> Remove old processor detection code on Power

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- example/glue/ObjectModelDelegate.hpp
- gc/base/EnvironmentBase.cpp
- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/ObjectModelBase.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Add a gc scavenger scan ordering feature that enables the
copying of a hot field marked by the JIT immediately after the
object containing the hot field is copied.
Issue: eclipse/openj9#7552
Signed-off-by: Jonathan Oommen jon.oommen@gmail.com
> Add Dynamic Breadth First Scan Ordering to GC

- compiler/compile/OMRCompilation.cpp
The readOnlyCode setting may be needed during CodeGenerator initialization.
Issue: #5542
> Initialize RX Compilation setting before CodeGenerator construction

- compiler/control/CompilationController.cpp
- compiler/control/OptimizationPlan.hpp
When the JIT fails initialization it proceeds with the
shutdown routines. In here the JIT tries to deallocate
the TLS storage for the compilation object. However,
because the JIT failed so early, this storage might
not have been allocated in the first place.
This PR checks whether the TLS storage was allocated
before attempting to free it.
> Check whether TLS storage for comp object was created before freeing it

- compiler/x/codegen/OMRX86Instruction.cpp
The assert is too restrictive.  It has been in place for a very long time
and I believe the situation it is trying to prevent is one where a register
spill is inserted in between the call instruction and the VFP cleanup
instruction (because the spill instruction uses the stack pointer and may
get an incorrect offset).  Restricting this special instruction's use to
ICF regions would ensure that because (in theory) no spilling should be
happening within an ICF.  Hence the assert.
However, there are circumstances in carefully constructed call sequences
where this instruction could be used outside of an internal control flow
region where register assignment and spilling won't be a problem between
the call instruction and the VFP cleanup instruction.
Like any instruction, when used properly in …
> Remove X86VFPCallCleanupInstruction assignRegister assert

- compiler/control/OMROptions.cpp
- compiler/optimizer/VPHandlers.cpp
https://github.com/eclipse/omr/issues/5542
Disable features that do not currently make sense to have enabled for a read only code cache, specifically:
1. Recompilation (because the code cache is not writable)
2. Side Effect guards (because the associated runtime assumptions cannot patch a read only code cache)
> Prevent Recompilation & Side-effect guards for a read only code cache

- cmake/modules/OmrTargetSupport.cmake
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilerunittest/CMakeLists.txt
- fvtest/jitbuildertest/CMakeLists.txt
- fvtest/tril/examples/incordec/CMakeLists.txt
- fvtest/tril/examples/mandelbrot/CMakeLists.txt
- fvtest/tril/test/CMakeLists.txt
- fvtest/tril/tril/CMakeLists.txt
- jitbuilder/release/CMakeLists.txt
During a previous change, adding the warning flags was moved into
omr_add_executable and omr_add_library. Unfortunately, the OMR compiler
is not yet ready to be compiled with warnings and this causes the
compiler tests to spam lots of warnings. To correct this, these
functions now accept an extra "NOWARNINGS" option that disables this
behaviour, which the OMR compiler uses for its tests and examples.
Fixes: #5296
Signed-off-by: Benjamin Thomas <ben@benthomas.ca>
> Fix compiler tests causing lots of warnings

- compiler/runtime/OMRRuntimeAssumptions.hpp
https://github.com/eclipse/omr/issues/5542
This PR adds some infrastructure changes to the runtime assumptions to facilitate support for a read only code cache. Specifically, 
1. `serialize` and `size` APIs are added, which child classes of `OMR::RuntimeAssumption` can extend
2. A pointer to the owning metadata is added to the Sentinel Assumption; this allows one to dangle a chain of runtime assumptions associated with a specific compiled body off of a metadata structure that describes said body when reifying the assumptions is necessary (e.g. in a snapshot/restore implementation).
> Runtime Assumptions infrastructure for Read Only Code

- compiler/runtime/OMRRuntimeAssumptions.hpp
The API to serialize a runtime assumption should also take the owning
metadata, as that information would be necessary during reification if
the desire is to attach those runtime assumptions targetting a
particular compiled body with a metadata structure associated with said
compiled body.
Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>
> Add missing param to serialize API

- ddr/tools/ddrgen/CMakeLists.txt
Fix INSTALL_RPATH as older versions of cmake do not expand generator
expressions in this property
> CMake: Fix omr_ddrgen on aix

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
- fvtest/compilertriltest/LogicalTest.cpp
This commit implements byteswap evaluators for AArch64.
> AArch64: Implement byteswap evaluators

- compiler/runtime/OMRCodeCacheManager.cpp
- compiler/runtime/OMRCodeCacheManager.hpp
Two functions are provided for asking whether a given code cache address resides
in a read-only (RX) code cache or not.  While their primary motivation is to be
used at runtime they can be used at either compile-time or runtime.
Issue: #5542
> Introduce RX code address inquiry functions

- compiler/optimizer/VPHandlers.cpp
- gc/base/ObjectModelBase.hpp
Add language specific changes for Dynamic Breadth First Scan Ordering to allow for proper functionality of Dynamic Breadth First Scan Ordering now that https://github.com/eclipse/omr/pull/5377 and https://github.com/eclipse/openj9/pull/10124 are merged.
Issue: eclipse/openj9#7552
> Add Language Specific Changes for Dynamic BF Scan Ordering

- compiler/arm/codegen/OMRInstruction.cpp
- compiler/optimizer/InductionVariable.cpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LoopReplicator.cpp
- compiler/optimizer/VirtualGuardHeadMerger.cpp
- compiler/p/codegen/OMRInstruction.cpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/x/codegen/BinaryCommutativeAnalyser.cpp
- compiler/x/codegen/BinaryCommutativeAnalyser.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OutlinedInstructions.hpp
- compiler/x/codegen/SubtractAnalyser.cpp
- compiler/x/codegen/SubtractAnalyser.hpp
- compiler/x/codegen/X86Ops_inlines.hpp
- compiler/z/codegen/BinaryAnalyser.cpp
- compiler/z/codegen/ConstantDataSnippet.hpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- compiler/z/codegen/OpMemToMem.hpp
- compiler/z/codegen/S390Debug.cpp
The `TR::Compilation` object is sometimes fetched from TLS (via `TR::comp()`)
when there are cheaper alternative means available (e.g., fetching it from
a `TR::CodeGenerator` object).  Replace some obvious candidates.  Also,
when the TLS version must be used, optimize its use to avoid repeated calls
in the same function.
> Replace some uses of TR::comp() with cheaper alternatives

- compiler/p/codegen/OMRTreeEvaluator.cpp
setMemoryEvaluator generates a sequence of instructions that initializes
a segment of memory of a specified length with a specified value. This
commit enables Int64 Length Node support while maintaining support for
Int32.
Signed-off-by: AlenBadel <Alen.Badel@ibm.com>
> Support Int64 Length Node within setmemoryEvaluator

- cmake/modules/OmrDDRSupport.cmake
When we are using a makefile generator, build ddrsets using $(MAKE)
to ensure we get proper parallelism.
> CMake: call $(MAKE) for ddr on makefile generators

- compiler/codegen/Relocation.hpp
It seems silly that by default all Relocations are considered External relocations
when only those that are in the `ExternalRelocation` hierarchy should be
considered as such.
Flip the default answer returned from `isExternalRelocation()` to be false, and have
only the relocations in the `ExternalRelocation` hierarchy return true.
> Flip default setting of isExternalRelocation

- compiler/optimizer/SinkStores.cpp
- compiler/optimizer/SinkStores.hpp
A previous cleanup of this code left some unreachable remnants behind.  Remove them now.
> Remove deprecated code from StoreSinking

- compiler/p/codegen/MemoryReference.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRMemoryReference.hpp
This PR does the following:
-Remove and replace legacy MemoryReference constructor
-Change all MemoryReference constructors from public to private/protected
Depends on https://github.com/eclipse/openj9/pull/10553
> Privatize all MemoryReference constructors and Remove/Replace legacy constructor

- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
tempSlotSymbol is a non-helper symbol that will provide a
mechanism for the compiler to insert temporary information
that the VM can use - such as the number of args when calling
signature-polymorphic methods that are implemented in the VM as
internal natives. The VM can use that information to locate
items on the stack.
> Add tempSlot symbol in Symbol Reference Table

- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/Scavenger.cpp
- gc/stats/CollectionStatistics.hpp
- gc/stats/GlobalGCStats.hpp
- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/schema.xsd
- Attribute `stalltimems` is added to `gc-end` to report time spent in stalling (in ms).
- New API `getStallTime()` introduced for `MM_GlobalGCStats`
- Expanded `MM_CollectionStatistics` to `_stallTime`
- New attribute is added in `gc-end` in schema.
- Update `MM_VerboseHandlerOutput::getTagTemplateWithDuration()` to reflect the addition of `stalltimems`
> Adding `stalltimems` in `gc-end` stanza

- compiler/arm/codegen/BinaryEvaluator.cpp
- compiler/arm/codegen/FPTreeEvaluator.cpp
- compiler/arm/codegen/OMRCodeGenerator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/p/codegen/BinaryEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/z/codegen/FPTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OpMemToMem.cpp
* Make findOrCreateRuntimeHelper boolean parms default to false
* Replace references to findOrCreateRuntimeHelper on Power
* Replace references to findOrCreateRuntimeHelper on Z
* Replace references to findOrCreateRuntimeHelper on X86
* Replace references to findOrCreateRuntimeHelper on ARM
Closes: #5601
> Create default parameters for findOrCreateRuntimeHelper

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit corrects debug printf format string for `tst` instruction.
> AArch64: Fix debug print for tst instruction

- gc/stats/ScavengerStats.cpp
In Scavenger, when we clear stats for each GC cycle, we miss to clear 2
fields relevant for array splitting, causing the stats being cumulative
since the beginning of the run.
Marking array splitting is ok.
> Clear array split stats

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/ras/Debug.hpp
Add `TR::ARM64TestBitBranchInstruction` instruction class
to support tbz/tbnz instructions.
> AArch64: Add support for tbz/tbnz instructions

- compiler/aarch64/codegen/ConstantDataSnippet.cpp
Change `ConstantDataSnippet` to use targetaddress2 parameter to
constructors of `TR_ExternalRelocation` class if the node is not `aconst`
because some evaluators in downstream projects would use `ConstantDataSnippet` for loading
address constant with non-aconst node.
> AArch64: Change ConstantDataSnippet to use targetaddress2 for non-aconst node

- compiler/optimizer/Inliner.cpp
The `_callNode` field in the call site may be `NULL` which was not being
checked in code paths guarded by BCD tracing. There was a bug exposed
due to recent changes to enable BCD tracing when `traceCG` is enabled in
#5165. This change activated the BCD tracing code path which exposed the
`NULL` dereference.
The BCD tracing here is actually not very useful because there are
`heuristicTrace` statements immedaitely above which trace pretty much
the same information. Thus the safest and easiest thing to do is to just
remove these extra BCD traces.
> Avoid null dereference in inliner due to BCD

- include_core/j9nongenerated.h
Change makes it easier to see how the different bits combine
and if there are any free bits.
Existing order is due to the way the code was exported out
of Envy Smalltalk, way, way back in the day.
Signed-off-by: Dan Heidinga <heidinga@redhat.com>
> Reorder J9MemorySegment constants from low to high value

- omrmakefiles/rules.zos.mk
Performance is seriously degraded on z/OS when files are compiled with `-Wc,debug` (for example, GC times are increased by a factor of over 2.5). On the other hand, `-Wc,debug` is required to produce the debug information required by DDR.
The solution is to compile files twice on z/OS when DDR is enabled. The first compile uses `-Wc,debug` to produce the `*.dbg` file required for DDR, a second compile omits `-Wc,debug` to avoid limiting the optimizer.
> Compile twice for DDR on z/OS so optimization is not hindered

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/OMRCompilation.cpp
* Add factory create() function to CodeGenerator class
* Call factory create() function to instantiate a CodeGenerator
Issue: #3235
> Add and use CodeGenerator factory function

- compiler/arm/codegen/OMRCodeGenerator.hpp
- compiler/codegen/OMRCodeGenerator.hpp
This commit adds supportsIntAbs/FPAbs() functions to CodeGenerator.
> Add supportsIntAbs/FPAbs() functions to CodeGenerator

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
The Linkage Info word is a 32-bit piece of memory right before the start PC of a compiled body. It is not used in OMR, but **is** used by at least one downstream project (OpenJ9). This PR abstracts away the initialization of this word so that downstream projects can initialize it appropriately.
> Unify LinkageInfo word initialization

- cmake/modules/platform/toolcfg/xlc.cmake
Lang level set to `extended0x` on c++, c remains on `extended`
> CMake: Update langlvl on aix

- compiler/arm/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRLinkage.cpp
MethodHandle.invokeWithArgumentsHelper was removed in
eclipse/openj9#10859.
This PR removes all dead-code related to invokeWithArgumentsHelper.
Related: https://github.com/eclipse/openj9/issues/7352, https://github.com/eclipse/openj9/pull/10856.
Co-authored-by: Jack Lu <Jack.S.Lu@ibm.com>
> Remove code related to invokeWithArgumentsHelper

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit fixes `TR::ARM64TestBitBranchInstruction`.
- Support branching to OOLCodeSection.
- Use correct relocation class as the destination is encoded in imm14 field.
> AArch64: Fix TestBitBranch instruction

- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.hpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRILProps.hpp
- compiler/il/OMRNode.cpp
- compiler/optimizer/OMRLocalCSE.cpp
- compiler/optimizer/ValuePropagationTable.hpp
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/p/codegen/UnaryEvaluator.cpp
- compiler/ras/Tree.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
Previously, OpenJ9 had a number of opcodes for performing byteswapped
loads and stores implementation details of which have leaked into OMR.
Since OMR now supports byteswap opcodes for all of the types for which
these reverse loads/stores were implemented, these opcodes are being
removed.
Closes: #5149
This PR needs to be merged concurrently with eclipse/openj9#10938.
> Remove reverse load/store opcodes

- compiler/codegen/CodeGenRA.cpp
- compiler/codegen/RegisterPressureSimulatorInner.hpp
- compiler/p/codegen/OMRInstruction.hpp
- compiler/p/codegen/OMRRegisterDependency.hpp
- compiler/p/codegen/PPCInstruction.hpp
Code became obsolete when instruction scheduler was removed prior to open sourcing.
> Remove deprecated Power register liveness code

- compiler/riscv/codegen/OMRCodeGenerator.hpp
- compiler/riscv/codegen/RVInstruction.cpp
- compiler/riscv/codegen/RVSystemLinkage.cpp
- compiler/riscv/codegen/RVSystemLinkage.hpp
* Replace recursive method checks with `isRecursiveMethodTarget` Compilation query.
* Provide System linkage implementations of entry point APIs
* Use entryPointFromCompiledMethod linkage API for RISC-V recursive calls
> Improve RISC-V recursive method invocations

- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, the Power codegen contained an optimization for performing a
store of a byteswapped value in a single instruction. Unfortunately, the
initial implementation of this optimization did not correctly check that
the byteswap node in question was not commoned, which could result in
erratic behaviour. This has now been corrected.
Issue: #5642
> Fix byteswapped store optimization on Power

- compiler/runtime/OMRRuntimeAssumptions.hpp
Since the sentinel assumption has a field to point to some metadata
associated with the same body that the list of assumptions is, it would
be useful to have the ability to retrieve the sentinel assumption given
a regular assumption.
Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>
> Add API to get the sentinel assumption

- configure
- configure.ac
OMR_PRODUCT_NAME was not properly substituted due to a typo
> Windows: Fix copyright strings in shared libraries

- compiler/p/codegen/OMRTreeEvaluator.cpp
As it turns out, the previous code for performing a byteswapped store of
a long on ppc32 was broken and would end up creating a memory reference
with both an index register and an offset. This has been corrected.
> Fix lbyteswap store optimization on ppc32

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OSRData.cpp
- compiler/control/CompileMethod.cpp
- compiler/control/OMROptions.cpp
- compiler/env/CompileTimeProfiler.hpp
- compiler/env/FEBase.cpp
- compiler/env/FrontEnd.hpp
- compiler/env/TRPersistentMemory.cpp
- compiler/il/OMRResolvedMethodSymbol.cpp
- compiler/il/OMRResolvedMethodSymbol.hpp
- compiler/infra/SimpleRegex.cpp
- compiler/ras/LimitFile.cpp
- compiler/ras/OptionsDebug.cpp
- compiler/runtime/OMRCodeCache.cpp
- compiler/runtime/OMRCodeCacheManager.cpp
* eliminate unnecessary includes and forward declarations
* fix up other files to accommodate removed includes and declarations
> Remove unneeded content from FrontEnd.hpp

- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, the codegen optimization for performing an lbyteswap and an
lstore in one stdbrx instruction was not properly checking that the
stdbrx instruction was actually available on the current processor.
Since this instruction was only added in P7, this could result in P6 and
earlier processors encountering an illegal instruction.
> Fix invalid use of stdbrx on P6 and before

- compiler/optimizer/RegDepCopyRemoval.cpp
For creating a fresh copy for RegDepCopyRemoval optimization, there was a case when a regLoad is under PassThrough node in which case we would not have corresponding regStore. To handle this case we were creating a regStore by getting the type from PassThrough node which would cause badIlOp. This commit fixes that issue.
> Fix the badIlOp node generated by RegDepCopyRemoval

- compiler/env/OMRClassEnv.hpp
- compiler/optimizer/LocalOpts.cpp
isConcreteClass() checks to see if the class is an interface or Abstract class.This
will reduce overhead resulting from calling two queries.
Issue in OpenJ9: https://github.com/eclipse/openj9/issues/11029
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>
> Replacing isAbstractClass() and isInterfaceClass() with isConcreteClass()

- port/unix/omrcpu.c
This commit implements omrcpu_flush_icache() for ARM and AArch64,
using GCC built-in funciton.
> Implement omrcpu_flush_icache() for ARM and AArch64

- compiler/control/CompileMethod.cpp
- compiler/control/OMROptions.cpp
- compiler/infra/SimpleRegex.cpp
- compiler/ras/LimitFile.cpp
- compiler/ras/OptionsDebug.cpp
There are locations within OMR compiler which we write to the verbose
log without acquiring the verbose log lock first. This patch addresses
the problem.
Issue: #5154
Signed-off-by: Allan Manuba <manuba@ualberta.ca>
> Fix missing verbose log acquire and release

- compiler/optimizer/ValuePropagationTable.hpp
These were guarded with `J9_PROJECT_SPECIFIC` and were accidentally left
as part of centralizing the opcode enum.
> Remove reverse load and store opcodes from ValuePropagationTable.hpp

- compiler/aarch64/codegen/OMRTreeEvaluatorTable.hpp
This commit enables fsqrt/dsqrt evaluators in OMRTreeEvaluatorTable
back again.
> AArch64: Enable fsqrt/dsqrt evaluators in OMRTreeEvaluatorTable

- compiler/codegen/CCData.cpp
- compiler/codegen/CCData.hpp
- compiler/codegen/CCData_inlines.hpp
- compiler/codegen/CMakeLists.txt
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertest/tests/CCDataTest.cpp
- fvtest/compilertest/tests/CCDataTest.hpp
- fvtest/coretest/TestBytes.cpp
- include_core/OMR/Bytes.hpp
- include_core/omrcomp.h
`CCData` is a simple linear buffer that can be used to store arbitrary data that can then be referenced from compiled code. The intention is for it to be used to store data that would otherwise be stored in the instruction stream (as immediate operands, in snippets, etc) in cases where that is undesirable. This is not unlike GOTs, TOCs, PLTs, and so on in other ABIs that store pointers and constants.
The PPC codegen has a similar structure called the pseudo-TOC, with most of the implementation living in OpenJ9, but its interface is very Java-specific and it stores both the user's data and its own internal book-keeping data (in the form of a hash table) in the same memory space. `CCData` on the other hand uses an `std::map` and has a language-agnostic interface.
> Add CCData data structure and related functions/tests

- compiler/il/OMRSymbol.hpp
- compiler/il/OMRSymbol_inlines.hpp
The existing flags are used for a limited types of objects, add a flag
for any types of objects.
> Add NonSpecificConstObject flag

- compiler/optimizer/LoopCanonicalizer.cpp
This fixes the issue pointed out by @keithc-ca in https://github.com/eclipse/omr/pull/5660#discussion_r521476967
> Move postDominators allocation to heap

- GNUmakefile
- ddr/Makefile
- ddr/lib/Makefile
- ddr/tools/Makefile
- fvtest/compilertest/iwyu.mk
- fvtest/compilertest/linter.mk
- jitbuilder/linter.mk
Run select parts of make-based builds sequentially.
- Because we haven't expressed dependencies of these targets clearly, we can't allow make to build them in parallel (at least at this level). Otherwise, things like util/a2e (a prerequisite of several targets) get built twice. Often we get lucky and both branches leave things in a reasonable state for dependents, but not always.
Remove unnecessary uses of double-colon rules in makefiles.
> Avoid duplicate work in non-cmake builds

- omrmakefiles/rules.win.mk
Without `/fo`, `rc` writes the `*.res` file in the same directory as the `*.rc` file. Some versions of `make` form the command as:
```
rc {options} ./win32/omrsyslogmessages.rc
```
which yields the `*.res` file in the win32 directory which then won't be found at the link step.
> Explicitly specify output for resource compiler

- port/common/omrerror.c
`omrerror_set_last_error_with_message` expects a non-null message
though the API doesn't indicate that in the documentation.
Protect against the inadvertant passing of NULL by defaulting to
an empty string for the message.  This ensures that anyone checking
for a message after this call won't get stale data.
Fixes segfaults when the NLS catalog can't be found as it's a common
pattern to pass the NLS result directly to this call.
Signed-off-by: Dan Heidinga <heidinga@redhat.com>
> Use a default empty message when NULL passed to set error api

- CMakeLists.txt
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/ddr/DDRSetStub.cmake.in
zos doesnt store the dwarf debug info in the target executable, but
creates a .dbg file for every compilation unit. In order to collect
these we glob for .dbg files residing under a directory specified by
the DDR_OBJECT_SEARCH_ROOT property on the ddrset target (which defaults
to the ddr set's binary dir). In addition to this paths to exclude from
the globbing are specified in the DDR_OBJECT_EXCLUDES property
> CMake: Enable support for ddr on zos

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- example/glue/ObjectModelDelegate.hpp
- gc/base/EnvironmentBase.cpp
- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/ObjectModelBase.hpp
Add a gc scavenger scan ordering feature that enables the
copying of a hot field marked by the JIT immediately after the
object containing the hot field is copied for balanced GC policy.
Issue: eclipse/openj9#7552
Signed-off-by: Jonathan Oommen jon.oommen@gmail.com
> Add Dynamic Breadth First Scan Ordering to Balanced GC

- compiler/codegen/ELFGenerator.cpp
Formating implies that e_ident is set in the loop but
it's only set once, after the loop.
Signed-off-by: Dan Heidinga <heidinga@redhat.com>
> Correct formating to clarify code in for loop

- compiler/infra/InterferenceGraph.cpp
- compiler/infra/InterferenceGraph.hpp
Some of the largest symbols in the compiler obj files originates
from TR_InterferenceGraph resulting from its use of
CS2::ABitVector, while providing no real benefits in terms
of capabilities or performance. Use of CS2::ABitVector has been
replaced with TR_BitVector in TR_InterferenceGraph, which results
in significant reduction in the size of the Compiler component's
obj files, whether it is part of a standalone OMR build or part of
a downstream project.
With this fairly small change, compiler builds will see a 41.5 KB
reduction in the on-disk size of the obj files.
> Use TR_BitVector instead of CS2::ABitVector in TR_InterferenceGraph

- compiler/optimizer/LoopVersioner.cpp
Pointer field `_postDominator` gets initialized to a local variable.
As of right now all access points of the variable are guarded by NULL
checks. Setting it to NULL before we exit the method to avoid bugs which
may arise from accidental use of the variable without a NULL check.
> NULL ptr field `_postDominators` to avoid scope issues in future

- compiler/p/codegen/OMRTreeEvaluator.cpp
Previously, stores/loads with byteswaps were generating optimized
sequences in the Power codegen. Unfortunately, in some cases this
support required the use of delayed indexed-form, which has been found
to be broken. In order to temporarily correct issues arising from these
optimizations, they have been disabled until the underlying issue is
corrected.
Issue: #5684
> Temporarily disable Power reverse load/store optimizations

- compiler/x/amd64/codegen/OMRMemoryReference.cpp
In some cases, e.g. method enter/exit hooks,
JITServer takes the static hook address directly from the client,
but the address load might be encoded using offset relative
to server's RIP, which results in an invalid address.
This commit ensures that static address loads for out-of-process
compilations always get loaded in a register first, preventing
relative access.
> Require address load instruction for statics in JITServer

- compiler/optimizer/LocalAnticipatability.cpp
Two traceMsg statements were missing a parameter.
> Fixed traceMsg in LocalAnticipatability

- compiler/runtime/Helpers.inc
- compiler/z/codegen/OMRTreeEvaluator.cpp
Changes in PR adds supporting changes to add fences after volatile field stores made in https://github.com/eclipse/openj9/pull/11262.
> Supporting changes to add fences after volatile field stores

- gc/verbose/VerboseBuffer.cpp
- gc/verbose/VerboseBuffer.hpp
- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/VerboseManager.hpp
- gc/verbose/VerboseWriterChain.cpp
- gc/verbose/VerboseWriterChain.hpp
- gc/verbose/VerboseWriterFileLogging.cpp
- gc/verbose/VerboseWriterFileLogging.hpp
- gc/verbose/VerboseWriterFileLoggingBuffered.cpp
- gc/verbose/VerboseWriterFileLoggingBuffered.hpp
- gc/verbose/VerboseWriterFileLoggingSynchronous.cpp
- gc/verbose/VerboseWriterFileLoggingSynchronous.hpp
When using `-Xverbosegclog`, prints `Initialized` stanza at the beginning of each file.
In order to achieve this, following changes have been made:
- Relocate `formatAndOutput(),formatAndOutputV()` to `MM_VerboseBuffer` from `MM_VerboseWriterChain`
- In `MM_VerboseHandlerOutput`:
- Modified `writeVmArgs` to take a `MM_VerboseBuffer`
- Factored out lines for printing `Initialized` stanza in `handleInitialized`
- Created `outputInitializedStanza` dedicated to output `Initialized` stanza, which also takes a `MM_VerboseBuffer`
- In `outputInitializedStanza`, replaced `handleInitializedInnerStanzas` with `outputInitializedInnerStanza` 
- In `VerboseHandlerOutput`:
- Modified `writeVmArgs` to takes a `MM_VerboseBuffer`
- Implement virtual method `outputInitializedInnerStanza()`
- Implement …
> Print `initialized` stanza to each file

- compiler/control/OMROptions.cpp
- compiler/optimizer/OMROptimizer.cpp
Define the OpenJ9-specific optimization, `HandleRecompilationOps`, along with options for tracing its actions and disabling it.
This pull request depends upon the downstream [OpenJ9 pull request #11020](https://github.com/eclipse/openj9/pull/11020)
> Define OpenJ9-specific HandleRecompilationOps optimization

- gc/base/standard/CopyScanCacheList.cpp
Currently, we decrement the counter of non-empty sub-queues after we
remove an element from a sub-queue. In a corner case, when this is the
last element of the last non-empty queue, for a moment there will be
effectively no elements in the queue, but the counter will not be zero.
If the GC thread doing dequeue is stalled (by OS due to overloaded CPUs)
at that moment, other worker GC threads may spin in a higher level scan
loop trying to dequeue a (non-existent) element from seemingly non-empty
queue. The spinning takes CPU resources and does not help the stalled
thread resume.
By re-ordering these 2 steps, if a thread stalls between them, the queue
will appear as empty before the dequeue, what will make other GC threads
quickly block (although they may shortly spin on spinlock of the that …
> Swap dequeue and decrement in Scavenger scan queue

- gc/verbose/VerboseHandlerOutput.hpp
This is a fix for compile error in
PR: https://github.com/eclipse/omr/pull/5607
Previous PR removed handleInitializedRegion() and writeVmArgs() prematurely.
Fixed by adding empty implementation for these two methods.
These empty methods are temporary, which will be removed by time
downstream projects (OpenJ9) starting using new API.
> Fix compile problems in PR #5607

- compiler/riscv/codegen/RVInstruction.cpp
- compiler/riscv/codegen/RVInstruction.hpp
This commit replaces `TR_RISCV_?TYPE()` macros with (inline) functions
and provide overloaded versions for easier use. This provides a nicer
instruction encoding interface for encoding snippets.
> RISC-V: refactor instruction encoding macros

- port/common/omrstr.c
This prevents buffer overrun when there is second round `iconv()` call within `convertWideToPlatform()`.
> Reset on stack buffer pointer for iconv

- compiler/z/codegen/S390Instruction.hpp
Failing to default initialize these fields to 0 when a new instruction is generated can result in an ignored byte in the instruction having a non-zero value. This can cause bugs in the future when the byte may no longer be ignored.
> Default initialize all immediate fields for RIE instructions

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
Change initializer of `OMRCodeGenerator` not to set `hasResumableTrapHandler`
if `TR_DisableTrap` is set.
Set `_numberBytesReadInaccessible` and `_numberBytesWriteInaccessible` to 4096
if `TR_DisableTrap` is not set.
> AArch64: Unset hasResumableTrapHandler if TR_DisableTrap is set

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit adds 'printInstructionComments()` call to debug print functions
of memory reference instructions.
> AArch64: Print instruction comments for memory reference instructions

- cmake/config.cmake
- gc/CMakeLists.txt
- gc/api/CMakeLists.txt
- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.cpp
- gc/base/GCExtensionsBase.hpp
- gc/base/MemoryPool.hpp
- gc/base/ObjectModelBase.hpp
- gc/base/ObjectScanner.hpp
- gc/base/SlotObject.hpp
- gc/structs/ForwardedHeader.hpp
- include_core/omrcfg.cmake.h.in
- include_core/omrcfg.h.in
These are the CMake GC changes needed to enable mixed references mode for https://github.com/eclipse/openj9/issues/8878.
OpenJ9 changes: https://github.com/eclipse/openj9/pull/11166
**Set _compressObjectReferences if mixed build override not defined**
`_compressObjectReferences` should only be defined if `OMR_OVERRIDE_COMPRESS_OBJECT_REFERENCES` is not defined. Otherwise, when mixed mode is enabled and the override is defined, `_compressObjectReferences` is considered a private field that is declared, but never used, which the compiler may complain about.
**Add support for mixed references mode in CMake builds**
In mixed references static mode, split the omr gc library into `omrgc` and `omrgc_full` so that the appropriate library can be used. `omrgc` has …
> Add support for mixed references mode in CMake builds

- compiler/control/OMROptions.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
The changes in this PR are tied to the `sequentialStoreSimplification` opt in OpenJ9.
`setSupportsAlignedAccessOnly` sets the `SupportsAlignedAccessOnly` flag. The `SequentialStoreSimplification` optimization checks on the status of this flag to determine whether it should proceed or not. Currently, this is the only place in OMR and OpenJ9 that queries the flag. Due to updates to the `sequentialStoreSimplification` opt in OpenJ9, it became desireable to update how the `SupportsAlignedAccessOnly` flag is set on Power to be a bit more accurate. As such the following changes are made:
`SupportsAlignedAccessOnly` flag is no longer set for 64 bit Power 9.
`SupportsAlignedAccessOnly` flag is no longer set for 64 bit BE Power 8.
`SupportsAlignedAccessOnly` flag is now set for 32 bit Power 7. …
> Changes to support sequentialStoreSimplification opt

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/OMRInstructionDelegate.hpp
Add `setupImplicitNullPointerException` method to InstructionDelegate class
and change instruction classes with memory reference to call it from their constructor.
> AArch64: Add a method for setting up implicit exception point to InstructionDelegate

- compiler/control/OMROptions.cpp
This commit enables profiling recompilation on AArch64.
> AArch64: Enable profiling recompilation

- compiler/optimizer/OMRRecognizedCallTransformer.cpp
- compiler/optimizer/OMRRecognizedCallTransformer.hpp
Some transformation require additional data or the trees to be
preprocessed, so add a preProcess extention point to be implemented by
downstream projets.
Also dump trees before and after the transformation when trace is on.
> Add preProcess stage to recognized call transformer

- compiler/z/codegen/OMRMemoryReference.cpp
- compiler/z/codegen/OMRMemoryReference.hpp
Commit in this pull request adds the trivial implementation of the TR::MemoryReference::create API before we change use of `generateS390MemoryReference(TR::Node *, TR::CodeGenerator *)` to `TR::MemoryReference::create` in the downstream OpenJ9 project. 
> Add TR::MemoryReference::create API with trivial implementation

- compiler/compile/OMRCompilation.cpp
- compiler/env/OMRIO.hpp
- compiler/ras/CallStack.cpp
- compiler/ras/Debug.cpp
Eliminates numerous `-Wformat` warnings.
> Use portable formats from omrformatconsts.h

- compiler/z/codegen/BinaryAnalyser.cpp
- compiler/z/codegen/BinaryCommutativeAnalyser.cpp
- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/CompareAnalyser.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/FPTreeEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
- compiler/z/codegen/OMRMemoryReference.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/UnaryEvaluator.cpp
Changes in this PR ports the code from Snapshot branch to use TR::MemoryReference API. 
> Use TR::MemoryReference::create API

- compiler/ras/Debug.hpp
- compiler/riscv/codegen/OMRCodeGenerator.cpp
- compiler/riscv/codegen/OMRCodeGenerator.hpp
- compiler/riscv/codegen/OMRInstructionKindEnum.hpp
- compiler/riscv/codegen/RVDebug.cpp
- compiler/riscv/codegen/RVInstruction.cpp
- compiler/riscv/codegen/RVInstruction.hpp
This PR introduces new (pseude) instruction  class - `DataInstruction`. 
This is then used as return type info instruction.
> RISC-V: implement data instruction

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds `findOrCreate4ByteConstant()` helper method
which finds or creates ConstantDataSnippet with 4byte data.
> AArch64: Add a variant of helper method for creating constant data snippet

- cmake/toolchains/riscv64-linux-cross.cmake
This commit improves CMake toolchain file to work with both,
the "official" RISC-V GNU Compiler Toolchain and Debian (Ubuntu)
provided RISC-V toolchains.
> RISC-V: improve CMake toolchain file

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit changes the debug print function for `compare and branch` and
`test bit and branch` instructions to print out register dependencies.
> AArch64: Add debug print of register dependencies to branch instructions

- include_core/thread_api.h
- thread/common/omrthread.c
- thread/exports.cmake
- thread/thread_include.mk
API additions expose details about acquired monitors such as owner, number of times acquired, and information about waiting threads. May be useful for runtimes that require specific information about the state of acquired monitors such in Eclipse OpenJ9 snapshot+restore.
Signed-off-by: Theresa Mammarella <tmammare@redhat.com>
> Threading API additions for acquired monitors

- compiler/codegen/Relocation.cpp
- compiler/il/OMRSymbol.hpp
- compiler/runtime/Runtime.hpp
In OpenJ9 the JProfiling framework is used to create profiled code
which contains references to internal data structures like block
frequencies stored in `TR_BlockFrequencInfo` class, or the flag for
checking if the method is already in recompilation queue.
To support AOT compilation for such code, we need to generate relocation
records for such data structures referenced by the compiled code.
OpenJ9 PR https://github.com/eclipse/openj9/pull/9591 creates the necessary
structures representing the relocation record for this data.
This commit adds the changes required by the OpenJ9 PR by adding
required enum for new relocation records and providing API for tagging
the symbols appropriately.
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>
> Add support for relo records for block freqeuncy and recomp queued flag

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/codegen/Relocation.cpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/compile/OMRMethod.hpp
- compiler/p/codegen/ControlFlowEvaluator.cpp
- compiler/runtime/Runtime.hpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
This PR contains changes mostly necessary to improve AOT in Eclipse OpenJ9. It contains:
- Addition of new relo types
- Addition of new fields to `TR_AOTMethodInfo`
- New incInlineDepth API
- New API to determine relo type for method to be inlined
- Adding Breakpoint Guards to the list of guards AOT will be able to handle
> Facilitate improvements for AOT

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
`ificmpeq` and its variant nodes have 3 children and the third child is
`GlRegDeps` whose children are `aRegLoad`/`iRegLoad`/`PassThrough` of global registers.
In some cases, `GlRegDeps` node uses all the allocatable integer registers.
If this happens, we cannot use `cbz`/`cbnz` instruction for branch
because `cbz`/`cbnz` requires a register in addition to those global registers.
This commit changes `ificmpHelper` to use `b.cond` instruction for that case.
> AArch64: Use b.cond instead of cbz/cbnz when all register are used up

- gc/base/MemorySubSpace.hpp
- gc/base/MemorySubSpaceGenerational.hpp
Fixes a bug in Gencon where an incorrectly returned 0 contraction size
prevents additional compaction to aid contraction from occuring. The
generational memory subspace was returining its own unused field rather
than the correct contraction size of the actual sub space.
> Fix 0 getContractionSize() in MemorySubSpaceGenerational

- gc/base/omrmmprivate.hdf
- gc/base/standard/ConcurrentGC.cpp
- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.hpp
- gc/verbose/schema.xsd
https://github.com/eclipse/openj9/issues/11237
Added attribute `contextid` to `concurrent-collection-start` stanza. 
Changed name of `concurrent-collection-start` stanza to `conurrent-global-final` to show its relation to `cycle-end` stanza which follows it.
Removed `concurrent-collection-end` to reduce redundancy with `exclusive` stanza follows it.
Overloaded `MM_VerboseHandlerOutput::getTagTemplate()` to take `contextid`
> Add `contextid` in `concurrent-collection-start` 

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/il/OMRTreeTop.cpp
- compiler/optimizer/LoadExtensions.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/x/amd64/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
This PR removes the use of `getAccessStaticsIndirectly` and `setAccessStaticsIndirectly` APIs as it no longer makes sense to use them. We also remove the `checkSimpleLoadStore` routine in the Z codegen since it has no consumers.
> Deprecate get and setAccessStaticsIndirectly API

- port/unix/j9nlshelpers.c
Locales such as C.UTF-8 must set the language to "en" and not "c.u".
Issue https://github.com/eclipse/openj9/issues/11620
> Filter "C." in the list of locales using language "en"

- fvtest/porttest/omrsignalExtendedTest.cpp
- port/unix/omrsignal.c
When signals are blocked, it stays blocked across sub-processes through inheritance of the SignalMask.
Keeping synchronous signals blocked cause external effect with specific environments on signal control causing unexpected change in signal mask/handler [1].
Allowing synchronous signals to get unblocked when used, as asynchronous signals do, fix the issue and ensure signals don't get received by a wrong handler and for the process to terminates abruptly. This PR also moves unblocking signals to after registering the signal handler with the OS instead of before to ensure no signals get received between the unblocking and registering of signals.
> As per the Notes in https://man7.org/linux/man-pages/man2/sigprocmask.2.html, there are only side-effects for blocking signals such as SIGBUS, …
> Unblock synchronous signals when in use and ensure registering handler before unblocking a signal 

- gc/verbose/VerboseHandlerOutput.hpp
https://github.com/eclipse/omr/pull/5607
This is a follow-up PR to clean obsolete APIs.
Following APIs are deleted:
`MM_VerboseHandlerOutput::writeVmArgs`
`MM_VerboseHandlerOutput::handleInitializedRegion`
> Delete obsolete APIs in `MM_VerboseHandlerOutput`

- compiler/p/codegen/UnaryEvaluator.cpp
The b2iEvaluator currently does not generate sign extension for
bRegLoad. While it will work for sign extended bRegLoad, it may
yield wrong result if the byte was not sign extended. This commit
cover such cases, by making sure bRegLoad is always sign extended.
Fixes: eclipse/openj9#11192
> Fix b2iEvaluator in power for bRegLoad

- compiler/codegen/CCData.cpp
Declaring the functions inlined allows the compiler skip emitting
callable symbols for them in `CCData.o`, but because the functions are
declared in a header that's included in other compilation units the
linker complains that there are no implementations for said functions
available, even though they're declared private and not referenced
outside of `CCData.o`.
Unfortunately said functions need to be declared as class members
because they refer to private typedefs in the CCData class.
> Remove inline from CCData static member funcs

- compiler/p/codegen/OMRTreeEvaluator.cpp
In-register byte-reverse uses the same instruction sequence for P7, P8 & P9.
Given that `rlwimi` became cheaper in P8 & P9, using it instead of `rlwinm` in P8 & P9 results in more performant and less total instructions to execute.
Also, given the higher throughput of `rlwimi` in P8 & P9, instructions were ordered in a non-dependent matter to allow for parallel execution when possible.
 `rlwimi` Cost | Latency | Throughput |   
-- | -- | -- | -- 
POWER7 | 3-4 cycles | 1 per cycle |   
POWER8 | 1 cycle | 2 per cycle |   
POWER9 | 2 cycles | 4 per cycle | pipe busy 1 cycle
**Number of Instructions**:
| Type 	| Original #Instr 	| Improved #Instr 	|
|-	|-	|-	|
| Short Byte Swap 	| 3 	| 2 	|
| Int Byte Swap 	| 7 	| 3 	|
| Long Byte Swap (32-bit runtime)	| 16 (14) 	| 8 (6)	|
**BumbleBench …
> Add more performant in-reg byte-reverse series of instr for P8 & P9

- compiler/codegen/OMRLinkageConventions.enum
- compiler/z/codegen/Linkage.hpp
- compiler/z/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRLinkage.hpp
- compiler/z/codegen/SystemLinkage.cpp
- compiler/z/codegen/SystemLinkage.hpp
These enums serve the same purpose, and so this PR merges the specialized S390 enum into the common one.
Fixes: #2911
> Fold TR_ S390LinkageConventions into TR_LinkageConventions

- CODEOWNERS
@andrewcraik has retired from his position as a project committer and
has requested to be removed as a code owner. He no longer has a valid
ECA so I am committing the change for him.
Thanks for all your contributions and for serving as a project
committer, Andrew!
> Remove @andrewcraik as a code owner

- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.cpp
- gc/base/GCExtensionsBase.hpp
- gc/base/MemoryPool.hpp
- gc/base/ObjectModelBase.hpp
- gc/base/ObjectScanner.hpp
- gc/base/SlotObject.hpp
- gc/structs/ForwardedHeader.hpp
Fixes: https://github.com/eclipse/openj9/issues/11469
OpenJ9 equivalent changes: https://github.com/eclipse/openj9/pull/11691
- Remove `!defined(OMR_OVERRIDE_COMPRESS_OBJECT_REFERENCES)` from preprocessor guard of `_compressObjectReferences` field
- Make `_compressObjectReferences` a `protected` field in header files that declare it -- keeping it as a private field while removing the OVERRIDE check causes clang to error on osx (`-Wunused-private-field`)
Related:  https://github.com/eclipse/openj9/issues/8878,  https://github.com/eclipse/openj9/pull/11166
> Fix DDR field inconsistency in mixed refs builds

- compiler/il/OMRBlock.cpp
Before uncommoning the nodes between split points, make sure the uncommoning won't won't orphan any commoned out compressedrefs anchor node.
> Fix trees around split point in PostGRA block splitter

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit implements `generateDebugCounterBump` for aarch64.
> AArch64: Implement generateDebugCounterBump

- gc/base/MemoryPoolLargeObjects.cpp
- gc/base/MemorySubSpace.cpp
With an LOA, tenure contraction was previously limited to only
contracting within the LOA. This allows tenure to contract further
when the LOA is empty. This is accomplished by contracting both
the LOA and SOA simultaneously, then rebalancing the LOA size.
> Allow tenure to contract beyond LOA size when LOA is empty

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/ParallelGlobalGC.cpp
- include_core/omrgcconsts.h
This is intended to allow a new command-line option to adjust the
ratio of high address free tenure space to requested contraction size
which causes an extra compaction. A higher ratio results in more
performance-heavy compactions and allows tenure to contract more.
> Add field to adjust compact to contract minimum contraction ratio

- gc/base/EnvironmentBase.hpp
- gc/base/GCExtensionsBase.hpp
- gc/base/MemoryPool.hpp
- gc/base/ObjectModelBase.hpp
- gc/base/ObjectScanner.hpp
- gc/base/SlotObject.hpp
- gc/structs/ForwardedHeader.hpp
- include_core/omr.h
Replace repetition of preprocessor tests of
* `OMR_GC_COMPRESSED_POINTERS`,
* `OMR_GC_FULL_POINTERS` and
* `OMR_OVERRIDE_COMPRESS_OBJECT_REFERENCES`
with a new macro `OMR_COMPRESS_OBJECT_REFERENCES(dynamic)`.
> Consolidate tests for whether to compress pointers

- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.hpp
https://github.com/eclipse/openj9/issues/11239
- Replace `concurrent-mark-end` in `concurrent-end` with `gc-op`
- moved `terminationReason` as one attribute to `concurrent-end` stanza
for both concurrent marking and concurrent scavenging
- delete warning for reporting termination reason in scavenging (rare case)
- report concurrent marking duration `timems` in gc-op
- Add new API to get termination reason
`MM_VerboseHandlerOutput::getReasonForTermination`
- Consolidate `handleConcurrentGCOpEnd` into `handleConcurrentEndInternal`
> Convert `concurrent-mark-end` to `gc-op` in GMP concurrent increment

- gc/structs/ForwardedHeader.hpp
Flag is required to support DDR for ForwardHeader API
> Introduce OMR_FORWARDED_TAG_MASK flag for forwarded header

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
- compiler/optimizer/PreExistence.cpp
- compiler/optimizer/PreExistence.hpp
Part of an effort to refactor prex arg info. This commit contains the
following changes:
- Move two TR_PrexArgInfo functions from OpenJ9 to OMR such that we can
merge prex arg infos in OMR.
- When creating prex arg info for a target, propagate arg info from call
site.
- Add an inliner util to clear arg info for variant argument given a
prex arg info
- `computePrexInfo` will not assume storing the result to `_prexArgInfo`
of a target, instead, the user will take the result and store it to the
place they want.
Part of https://github.com/eclipse/openj9/issues/11584
> Refactor prex arg info computation and propagation

- port/CMakeLists.txt
- port/common/omrgetsysname.c
- port/common/omrgetsysname.h
- port/common/omrstr.c
- port/port_objects.mk
- port/zos390/omrgetsysname.c
Populate the %sysname token using __osname() nodename, which provides
the SYSNAME sysparm.
> Add %sysname dump token on z/OS

- compiler/ilgen/OMRIlBuilder.cpp
This PR addresses #5775
Credit for the fix of the problem goes to Mark Stoodley (@mstoodle).
The changes were tested with OMR compiler test and JitBuilder test.
> Fix to OMR ILBuilder ConstInt64 logging problem

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/codegen/Relocation.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/z/codegen/ConstantDataSnippet.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
In OpenJ9 the JProfiling framework is used to create profiled code
which contains references to internal data structures like block
frequencies stored in `TR_BlockFrequencInfo` class, or the flag for
checking if the method is already in recompilation queue.
To support AOT compilation for such code, we need to generate relocation
records for such data structures referenced by the compiled code.
This commit adds the code for generating the relocation records
for block frequency and the recompilation queued flag.
Currently it only handles x and p architectures.
Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>
> Create relocation records of type TR_BlockFrequency and TR_RecompQueuedFlag

- gc/base/standard/Scavenger.cpp
`_causedRememberedSetOverflow` scavenger stat flag is never set. This flag is the only way to tell whether a completed collection caused an overflow. Other than missing details in verbose log, this hasn't been an issue. However, there's planned future work relying on this flag being correct.
Guard condition around setting `_causedRememberedSetOverflow` will never pass. Consequently, it's impossible for it to be set:
```
if(!isRememberedSetInOverflowState())
env->_scavengerStats._causedRememberedSetOverflow = 1;
```
Upon `allocateMemoryForSublistFragment` failing, `setRememberedSetOverflowState` is called which will makes `isRememberedSetInOverflowState()` true and the condition fail.
We can rely on `_isRememberedSetInOverflowAtTheBeginning` as the condition (Cached RS Overflow flag at the …
> Ineffective _causedRememberedSetOverflow Flag Fix

- compiler/objectfmt/OMRObjectFormat.hpp
- compiler/z/codegen/CallSnippet.cpp
- compiler/z/codegen/CallSnippet.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/objectfmt/FunctionCallData.hpp
- compiler/z/objectfmt/OMRFunctionCallData.hpp
- compiler/z/objectfmt/OMRJitCodeRWXObjectFormat.cpp
- compiler/z/objectfmt/OMRJitCodeRWXObjectFormat.hpp
- compiler/z/objectfmt/OMRJitCodeRXObjectFormat.cpp
- compiler/z/objectfmt/OMRJitCodeRXObjectFormat.hpp
In https://github.com/eclipse/omr/pull/5575 ObjectFormat API alongside FunctionCallData to generate/emit function calls were introduced. Changes in this PR contains supporting changes for the API. 
> Changes for Object Format API on Z

- port/linuxamd64/omrsignal_context.c
- port/osx/omrsignal_context.c
- port/win64amd/omrsignal.c
The fix has been applied to `win64amd`, `linuxamd64` and `osx`.
On `osx`, `rflags` is available instead of `eflags`. Since `eflags` is analogous
to `rflags`, `OMRPORT_SIG_CONTROL_X86_EFLAGS` is used for `rflags` on `osx`.
> Add missing switch case statements for Eflags

- buildenv/jenkins/omrbuild.groovy
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrTest.cmake
- example/CMakeLists.txt
- fvtest/CMakeLists.txt
- fvtest/algotest/CMakeLists.txt
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/compilertriltest/SelectTest.cpp
- fvtest/compilerunittest/CMakeLists.txt
- fvtest/coretest/CMakeLists.txt
- fvtest/gc_api_test/CMakeLists.txt
- fvtest/gctest/CMakeLists.txt
- fvtest/jitbuildertest/CMakeLists.txt
- fvtest/lljbtest/CMakeLists.txt
- fvtest/porttest/CMakeLists.txt
- fvtest/rastest/CMakeLists.txt
- fvtest/sigtest/CMakeLists.txt
- fvtest/threadextendedtest/CMakeLists.txt
- fvtest/threadtest/CMakeLists.txt
- fvtest/tril/test/CMakeLists.txt
- fvtest/utiltest/CMakeLists.txt
- fvtest/vmtest/CMakeLists.txt
- jitbuilder/release/CMakeLists.txt
This PR provides CMake-based support for running tests under simlator such as QEMU.
This can be used to run tests as part of cross-compilation pipelines - this PR enables it on RISC-V. 
This is an alternative to what has been proposed an implemented by @fjeremic in PR #5753 
As of now, not all tests pass (for example, some port tests fail but I suppose that's because of the use of emulator). 
I did not spend time fixing them yet - the aim of this (draft) PR is to demonstrate an alternative and spark
discussion. 
FYI: @fjeremic , @AdamBrousseau
> CMake: enable tests on cross-compilation jobs 

- gc/base/standard/Scavenger.cpp
Update pointer offset addition for adding a hot field
offset to an object pointer in order to copy the hot
field of the object for dbf Scan Ordering in gencon GC.
Issue:  eclipse/openj9#11819
> Update pointer offset addition for dbf Scan Ordering

- compiler/env/OMRCPU.hpp
- compiler/p/env/OMRCPU.cpp
- compiler/p/env/OMRCPU.hpp
Removing the unused implementation of applyUserOptions.
applyUserOptions was implemented only on Power so that on startup it was possible to disable P10 support when TR_EnableExperimentalPower10Support is not set.
applyUserOptions was ultimately implemented but never used.
Since the method is not implemented on any other platform, it should be removed from the class.
Signed-off-by: AlenBadel <Alen.Badel@ibm.com>
> Remove unused applyUserOptions

- compiler/riscv/codegen/OMRLinkage.hpp
- compiler/riscv/codegen/RVSystemLinkage.cpp
This PR adds members required/used by OpenJ9 to RISC-V linkage properties. 
Since they are (seem to be) OpenJ9 specific, I added them conditionally using `#ifdef J9_PROJECT_SPECIFIC`. I also took the opportunity to do the same for AArch64 in order to keep the code similar. If this is not desirable, I'm happy to drop these `#ifdef`s.
FYI: @0xdaryl , @knn-k
> RISC-V add OpenJ9 specific members to linkage properties

- cmake/modules/OmrDDRSupport.cmake
DDR is may supported when cross compiling, unless we are on Windows with
CYGWIN in which case we do have support.
> Disable fatal message when cross compiling on CYGWIN

- compiler/env/OMRCompilerEnv.hpp
- compiler/env/TRPersistentMemory.cpp
Instead of using the global `::trPersistentMemory` object,
`jitPersistentAlloc/Free` now use a new method
`OMR::CompilerEnv::persistentMemory`.
This does not change the behavior for OMR, but upstream
projects can override `persistentMemory` method and return
memory objects that are not the global one.
> Enable jitPersistentAlloc/Free to use non-global persistent memory

- compiler/env/OMRVMEnv.cpp
- compiler/env/OMRVMEnv.hpp
- compiler/il/OMRNode.cpp
- compiler/optimizer/GlobalRegisterAllocator.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/ras/OptionsDebug.cpp
- compiler/x/codegen/BinaryEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRMemoryReference.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
This commit removes `OMR::VMEnv::heapBaseAddress()` as this routine always returns 0. It was introduced in the codebase early on in the codebase and has since been superseded by a shift-based solution. Hence this is no longer needed. See https://github.com/eclipse/openj9/issues/11263 for original issue and discussion.
> Eliminate vm.heapBaseAddress()

- compiler/compile/OMRCompilation.hpp
I had made changes to only one class as said and written the self class of `OMRCompilation.hpp`  from `public` to `protected`.
Please check that is this the right way or some more changes needed. @mstoodle @0xdaryl
> REVIEW : self changed to protected 

- cmake/modules/OmrCompilerSupport.cmake
- cmake/modules/OmrDetectSystemInformation.cmake
- cmake/modules/ddr/DDRSetStub.cmake.in
- cmake/modules/platform/toolcfg/xlc.cmake
This allows AIX XLClang CMake builds to work for JDK16.
Note: The new compiler ID `XLClang` is for CMake 3.15 and beyond. `XL` represents both `XLC and XLClang` as the `CMAKE_<LANG>_COMPILER_ID` in CMake 3.14 and prior. Latest CMake Compiler ID Documentation: [here](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html).
Existing xlc/xlclang files for reference
- [omrmakefiles/rules.aix.mk](https://github.com/eclipse/omr/blob/master/omrmakefiles/rules.aix.mk)
Successfully ran personal builds `JDK16_ppc64_aix_cm` and `JDK16_ppc64_aix_mixed` with these changes + corresponding OpenJ9 changes: https://github.com/eclipse/openj9/pull/11889.
> Set up AIX XLClang flags for JDK 16+ CMake builds

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/il/OMRNode.hpp
- compiler/il/OMRNode_inlines.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/BinaryAnalyser.cpp
- compiler/z/codegen/BinaryCommutativeAnalyser.cpp
- compiler/z/codegen/BinaryEvaluator.cpp
- compiler/z/codegen/ControlFlowEvaluator.cpp
- compiler/z/codegen/FPTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/UnaryEvaluator.cpp
See eclipse/omr#5648 for discussion. It was decided during the OMR
architecture meeting that this API is not very clear and that inlining
it's uses is more understandable as it is very explicit as to what is
being checked.
Closes: #5648
> Deprecate isSingleRefUnevaluated

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/ConcurrentGC.cpp
Improve the parallelization of remembered set scanning
in the final stop-the-world phase of the concurrent global
GC cycle in Gencon. Remove old solution that used command-line
option  -XXgc:dirtCardDuringRSScan.
Issue:  eclipse/openj9#11792
> Improve Parallelization of Remembered Set Scanning in Gencon

- compiler/infra/Assert.cpp
SIGABRT only has one global signal handler, so we cannot guard
function calls against SIGABRT using the port library APIs. Raising a
SIGTRAP is useful for downstream projects who may want to catch such
signals for  compilation thread crashes and requeue such compilations
(for another attempt, or perhaps to generate additional diagnostic data).
> Raise SIGTRAP in TR::trap() instead of SIGABRT

- compiler/codegen/OMRCodeGenerator_inlines.hpp
- compiler/codegen/OMRInstruction_inlines.hpp
- compiler/codegen/OMRMachine_inlines.hpp
- compiler/compile/OMRCompilation_inlines.hpp
- compiler/control/OMROptions_inlines.hpp
- compiler/il/OMRNode_inlines.hpp
- compiler/il/OMRSymbol_inlines.hpp
- compiler/il/OMRTreeTop_inlines.hpp
- compiler/il/TreeTop_inlines.hpp
- compiler/ilgen/OMRIlGeneratorMethodDetails_inlines.hpp
- compiler/optimizer/OMROptimizationManager_inlines.hpp
modify macro guard to INLINES
include header same as for cpp file but not extended ones
Signed-off-by: James Guan <jamesgua@ca.ibm.com>
> Trim inlines header of extensible classes

- gc/verbose/VerboseWriterFileLoggingBuffered.cpp
- gc/verbose/VerboseWriterFileLoggingSynchronous.cpp
Using `printf` methods to write to files _(e.g `omrfile_printf` & `omrfilestream_printf`)_ is problematic when the output buffer contains a string with specifier characters (e.g %s). In such a case, the format specifiers are intended to be outputted raw to the file rather than evaluated/expanded. `printf` will treat the string as a format string and attempt to evaluate the specifiers **(and crash)** whereas the buffer must be printed raw. Currently, `printf` methods are used when outputting verbose initialized block (string).
When outputting the init block, **use the verbose writer's `outputString` method** rather than using
- `omrfilestream_printf` for FileLoggingSynchronous Writer
- `omrfile_printf` for FileLoggingBuffered Writer
`outputString` will use `omrfile_write_text` and just …
> VerboseGC Initialized Stanza Print Fix

- compiler/p/CMakeLists.txt
- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/LoadStoreHandler.hpp
- compiler/p/codegen/OMRLoadStoreHandler.cpp
- compiler/p/codegen/OMRLoadStoreHandler.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/p/codegen/OMRTreeEvaluatorTable.hpp
- compiler/p/codegen/UnaryEvaluator.cpp
- fvtest/compilertest/build/files/target/p.mk
This PR introduces the new API proposed by #5630 to clean up generation of loads and stores from nodes for codegen optimization purposes. This new API should correct issues related to missing volatile memory barriers and eliminate a lot of unnecessary duplicate code. Note that a lot of code is currently present in this implementation which is guarded under `J9_PROJECT_SPECIFIC` guards. The plan is for this code to be sunk down to OpenJ9 by extending the `LoadStoreHandler` and `LoadStoreHandlerImpl` classes after this PR is merged.
This PR should be merged simultaneously with eclipse/openj9#11305.
> Implement a new API for performing node-based loads and stores on Power

- compiler/p/codegen/OMRCodeGenerator.cpp
Add support to create relocations for absolute helper addresses when loading constant addresses on power.
Signed-off-by: AlenBadel <Alen.Badel@ibm.com>
> Support TR_AbsoluteHelperAddress constant address loads on power

- compiler/cs2/allocator.h
- compiler/env/FEBase.hpp
- compiler/env/TRMemory.cpp
- compiler/env/TRMemory.hpp
- compiler/optimizer/UseDefInfo.cpp
- compiler/ras/CallStack.cpp
* Misc. source formatting cleanup in CallStack.cpp
* Replace globalAllocator with TR::CompilerEnv rawAllocator
* Remove deprecated GlobalAllocator
* Remove deprecated GlobalSingletonAllocator
* Remove deprecated CS2::stat_allocator
> Deprecate global allocator and misc. cleanup

- compiler/p/codegen/OMRLoadStoreHandler.cpp
POWER `generatePairedStoreSequence` is missing baseReg dependency to
ensure no RA register movement during the sequence. Adding baseReg
condition to `generatePairedLoadSequence` dependency check to be
consistent with `generatePairedStoreSequence`.
> Add baseReg dependency for POWER generatePairedStoreSequence

- gc/base/MemorySubSpaceUniSpace.cpp
- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/Scavenger.cpp
- gc/stats/HeapResizeStats.hpp
Add a new flag to GC heap stats and set it on percolate start
for JNI Critical Region percolates. On GC cycle end, exclude
the GC time from the GC CPU time if the flag is set.
The extra condition added to maximum heap heuristic checks
causing no contraction when the computed heuristic was arbitrarily
greater than 100 has also been removed.
Signed-off-by: Jason <jasonhal@ca.ibm.com>
> Exclude percolate GC CPU time from stats

- compiler/control/OMROptions.cpp
- compiler/optimizer/OMROptimizations.enum
This commit adds a few support pieces that must be in OMR but will be used by the new optimization being added in OpenJ9 in https://github.com/eclipse/openj9/pull/11968.
> Add support for lowering optimization

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit is a temporary workaround for huge methods.
The range of AArch64 conditional branch instruction is +/- 1MB.
This commit gives up compilation when the size of the generated code
exceeds that range.
> AArch64: Workaround for huge methods

- compiler/ilgen/ByteCodeIteratorWithState.hpp
- compiler/x/codegen/DataSnippet.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
* make comparisons with `NULL` explicit
* avoid shifting negative values
* fix casts: don't change both width and signed-ness in a single step
* fix casts: don't cast to pointer from integer of a different size
> Address some warnings from clang on macOS

- port/common/omrcuda.cpp
CUDA version 11.2 was released in December 2020.
> Add support for CUDA version 11.2

- cmake/config.cmake
- cmake/modules/OmrPlatform.cmake
- ddr/lib/ddr-scanner/CMakeLists.txt
- fvtest/algotest/CMakeLists.txt
- fvtest/compilertest/CMakeLists.txt
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/gctest/CMakeLists.txt
- fvtest/jitbuildertest/CMakeLists.txt
- fvtest/omrGtestGlue/CMakeLists.txt
- fvtest/porttest/CMakeLists.txt
- fvtest/sigtest/CMakeLists.txt
- fvtest/threadextendedtest/CMakeLists.txt
- fvtest/threadtest/CMakeLists.txt
- fvtest/tril/tril/CMakeLists.txt
- fvtest/utiltest/CMakeLists.txt
- omrsigcompat/CMakeLists.txt
- port/CMakeLists.txt
- thread/CMakeLists.txt
- util/CMakeLists.txt
- util/omrutil/CMakeLists.txt
* prefer flags over string comparisons
Flag            | Replaces
:---            | :-------
OMR_OS_AIX      | OMR_HOST_OS STREQUAL "aix"
OMR_OS_BSD      | OMR_HOST_OS STREQUAL "bsd"
OMR_OS_LINUX    | OMR_HOST_OS STREQUAL "linux"
OMR_OS_OSX      | OMR_HOST_OS STREQUAL "osx"
OMR_OS_WINDOWS  | OMR_HOST_OS STREQUAL "win"
OMR_OS_ZOS      | OMR_HOST_OS STREQUAL "zos"
See OmrDetectSystemInformation.cmake.
See also eclipse/openj9#12048.
> Reduce use of OMR_HOST_OS

- compiler/compile/OMRAliasBuilder.hpp
- compiler/compile/OMRCompilation.hpp
- compiler/compile/OMRMethod.hpp
- compiler/compile/OMRSymbolReferenceTable.hpp
The self() instance method is not supposed to be publicly visible in
extensible classes like `OMR::AliasBuilder`, `OMR::Method`, `OMR::SymbolReferenceTable` ; It should be made protected
Issue: #5780
> Change self() to protected in Method, SymbolReferenceTable, AliasBuilder

- buildenv/jenkins/omrbuild.groovy
Particularly due to riscv hitting the 1 hour timeout.
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
> Increase build & test timeout to 2 hours

- example/glue/ArrayletObjectModel.hpp
- gc/base/EnvironmentBase.hpp
- gc/base/standard/CompactScheme.cpp
- gc/base/standard/CompactScheme.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Update GC code to make sure whenever an indexable object moves, the object  will always contain the correct `dataAddr`
value, which is the address pointing right after array header.
Introduce pre/postObjectCompact wrapers for EnvironmentDeletegate pre/postObjectCompact API for object compaction fixup.
This is phase 2 of https://github.com/eclipse/openj9/issues/11438
> Update dataAddr whenever GC moves indexable object

- compiler/infra/HedgeTree.hpp
remove param TR_Frontend* and keep all declarations same
> Remove unused TR_FrontEnd parameter from HedgeTree print and printTree

- compiler/compile/OMRSymbolReferenceTable.cpp
Symbol Reference Table accessed the class loader directly,
instead of going through the front-end query, which may lead
to `TR_ASSERT_FATAL` triggered on JITServer.
Closes: #5837
> Access system class loader using a front-end query

- compiler/compile/OSRData.cpp
The `_methodInfo` field of `TR_InlinedCallSite` actually holds a `TR_ResolvedMethod` under relocatable compilation. As such, `checkOSRLimits` was incorrect passing in the `TR_ResolvedMethod` to `OSRFrameSizeInBytes`. This PR fixes this.
I recognize that this is a band-aid solution to a deeper problem. However, I'm opening this PR as a tactical fix because
1. There are a lot of crashes in OpenJ9 under JITServer when running FSD tests
2. There is some urgency to get the FSD feature functional in OpenJ9 for the next release, as well as for IBM releases which is based off of OpenJ9.
This PR solves the immediate JITServer issues and fixes what could be an extremely subtle bug - the emergency OSR buffer only comes into play when a thread that's trying to OSR out to the runtime fails to allocate …
> Get TR_OpaqueMethodBlock correctly under relocatable compilations

- include_core/omrport.h
- port/CMakeLists.txt
- port/port_objects.mk
- port/zos390/omrcel4ro31.c
- port/zos390/omrcel4ro31.h
- port/zos390/omrsl.c
Leverage the new LE CEL4RO31 support to enable z/OS 64-bit portlib to load 31-bit shared libraries, lookup target functions.
Introduces new OMRPORT_SLOPEN_ATTEMPT_31BIT_OPEN flag to control whether omrsl_open_shared_library() will attempt to open a 31-bit target DLL. Also a OMRPORT_SL_ZOS_31BIT_TARGET_HIGHTAG to tag 31-bit target DLL handles and function descriptors to distinguish against 64-bit targets.
> CEL4RO31 support for shared library load, lookup and close

- compiler/optimizer/RegDepCopyRemoval.cpp
While replacing with new node in RegDepCopyRemoval, we check if the
passthrough node attached to the register dependency has corresponding
regStore which is needed if if later optimization decides to split the
blocks. Currently we were throwing assert while creating
copyToNewVirtualRegister node under dependency where a global register
used by passThrough is different than the global register used by the
value node under it. As we are going to generate a regStore for that
passthrough node, we do not need this strict assert.
Fixes: eclipse/openj9#11943
> Relax the assertion in RegDepCopyRemoval

- compiler/ras/Tree.cpp
Previously, a buffer size of 100 characters was passed to sprintf in the
block validator. However, the format string itself is 94 characters,
which doesn't leave enough room in the buffer for the print arguments.
As a result, running the block validator (e.g. with paranoidOptCheck)
can lead to a buffer overflow.
This commit fixes the issue by increasing the size of the buffer to 150
characters.
> Increase size of buffer in block validation

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
Add internal pointer support to aarch64 code generator.
> AArch64: Support Internal Pointer

- cmake/modules/ddr/DDRSetStub.cmake.in
Remove CR and trailing whitespace.
> DDR: omit blank lines in annt files

- include_core/omr.h
Signed-off-by: Kenneth cox <differentialcalc1050@gmail.com>
> Remove declaration and definition of movedObjectHashCode

- gc/base/GCExtensionsBase.hpp
- gc/base/ParallelDispatcher.cpp
- gc/base/ParallelTask.cpp
- gc/base/ParallelTask.hpp
- gc/base/Task.hpp
- gc/base/j9mm.tdf
- gc/base/standard/ConcurrentScavengeTask.hpp
- gc/base/standard/ParallelScavengeTask.cpp
- gc/base/standard/ParallelScavengeTask.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
> Using overhead data (busy/stall times for managing and synchronizing threads), Adaptive Threading aims to identify sub-optimal/detrimental parallelism and continuously adjusts the GC thread count to reach optimal parallelism.
_Adaptive Threading changes are implemented at the various phases of GC as follows, during:_
1. **Pre-collection _(during to task/thread dispatch)_:** to adjust thread count based on the previous cycle’s recommendation
2. **Collection:** to gather data for parallelization overhead for the running cycle
3. **Post-collection _(after worker threads are suspended)_:** to project/calculate optimal thread count and give recommendation for the next cycle based on the current GC that’s completed
Adaptive threading will be enabled by default. The user may choose to …
> Adaptive GC Threading

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/ras/Debug.hpp
Add ARM64MemImmInstruction class and generateMemImmInstruction helper function.
Add enum class for Prefetch operations.
> AArch64: Support PRFM instruction

- compiler/aarch64/codegen/ConstantDataSnippet.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/z/codegen/ConstantDataSnippet.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/S390GenerateInstructions.cpp
* Move snippets-to-be-patched lists from Compilation to CodeGenerator
* Consolidate duplicate code to remember snippets containing class pointers
> Move snippets-to-be-patched lists from Compilation to CodeGenerator

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/compile/OSRData.cpp
- compiler/env/FrontEnd.cpp
- compiler/env/jittypes.h
- compiler/il/OMRNode.cpp
- compiler/optimizer/RedundantAsyncCheckRemoval.cpp
- compiler/ras/DebugCounter.cpp
- compiler/ras/Tree.cpp
Previously, `TR_InlinedCallSite::_methodInfo` stored either
a method pointer during a regular compilation,
or `TR_AOTMethodInfo *` during an AOT compilation,
despite `_methodInfo` having `TR_OpaqueMethodBlock *` type.
This makes the code prone to subtle bugs like #5845.
This commit moves storage of `TR_AOTMethodInfo *` outside of
`TR_InlinedCallSite`, putting it in `TR_InlinedCallSiteInfo`
which allows to simplify the definition of `TR_InlinedCallSite`
and places where it is used.
Closes: #5844
> Refactor TR_AOTMethodInfo out of TR_InlinedCallSite

- port/win32/omrsysinfo.c
This fixes two problems. If _WIN32_WINNT_WIN10 isn't defined, which it
isn't for VS2013, use deprecated GetVersionEx() to detect Windows 10.
Also query the Windows 10 build number instead of hard coding an old
build number.
Issue https://github.com/eclipse/openj9/issues/12260
See also https://github.com/eclipse/omr/pull/5870
Tested to ensure this compiles and works with VS2013 (Java 8), VS2017 (Java 11), VS2019 (Java 16). 
A Windows 10 machine shows "10.0 build 19042" which matches the OS via running `ver` in a cmd prompt.
The OpenJ9 build machine continues to show "6.3 build 9600" as expected.
> Compute Windows 10 build number in omrsysinfo_get_OS_version()

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit changes `aconstEvaluator` to load address constant
with `ConstantDataSnippet` if unloading assumption is required.
It also changes `loadAddressConstantInSnippet` to add
class unloading pic site to those snippets.
> AArch64: Add class unloading pic site to address constant

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
`getMethodSnippetsToBePatchedOnClassUnload()` and `getSnippetsToBePatchedOnClassUnload()` have
recently moved to the `CodeGenerator` class.
> Fix AArch64 compile failures

- port/win32/omrsysinfo.c
- port/win32_include/omrportpg.h
omrsysinfo_get_OS_version() allocates memory for the Windows 10 version
that needs to be freed.
See https://github.com/eclipse/omr/pull/5873
> Fix memory leak from omrsysinfo_get_OS_version()

- gc/base/GCExtensionsBase.hpp
- gc/base/standard/Scavenger.cpp
When `OMR_GC_MODRON_SCAVENGER` is not enabled the GC fails to compile.
Also, correct the spelling in the function name and fixup references.
> Guard adaptiveThreadingEnabled() for OMR_GC_MODRON_SCAVENGER only

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
Add refsRegister/usesRegister/defsRegister/defsRealRegister/assignRegister
to ARM64MemInstruction class and change child classes to call those methods.
> AArch64: Add register related virtual method to ARM64MemInstruction

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/optimizer/Inliner.cpp
Not consumed in OMR or any known downstream project.
> Remove unused _noEarlyInline field from Compilation class

- compiler/env/TRMemory.cpp
- compiler/env/TRMemory.hpp
This PR adds a new memory object type that will be used by the JITServer AOT cache in OpenJ9.
> Add memory object type for OpenJ9 JITServer AOT cache

- fvtest/compilertriltest/VectorTest.cpp
This commit adds test-cases for the vector add implementation on
relevant tril test- VectorTest for the following vector data-types-
- VectorInt8
- VectorInt16
- VectorFloat
> AArch64: Vector add tril test

- compiler/compile/OMRNonHelperSymbols.enum
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
This symbol is intended to facilitate setting up computed calls
for methods that are yet to be compiled.
> Add computedStaticCallSymbol

- fvtest/compilertriltest/VectorTest.cpp
This commit excludes tril tests for VectorInt8 & VectorInt16 for PPC
platform as it does not have support for these data types.
> PPC: Exclude tril tests

- compiler/aarch64/codegen/ARM64Debug.cpp
This commit adds `printInstructionComments()` call to debug print functions
of branch instructions.
> AArch64: Print instruction comments for branch instructions

- compiler/env/JitConfig.hpp
- compiler/env/OMRCPU.hpp
- compiler/env/OMRCompilerEnv.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
`TR_X86ProcessorInfo` is currently used in OMR because the compiler does not yet have access to the portlib. Therefore, it has to determine the processor features itself. In order to not initialize `TR_X86ProcessorInfo` multiple times a flag is set. However, it is
a race possible if there are multiple compilations, as is the case in Eclipse OpenJ9. Because the processor feature flags were copied from the target `TR::Environment` set in `TR::Compilation` object, if two racing compilations had different target environments, the feature flags could become inconsistent.
This PR initializes the processor info just once in `OMR::CompilerEnv::initializeTargetEnvironment()`.
This change is based on https://github.com/eclipse/omr/pull/5561 and fixes https://github.com/eclipse/openj9/issues/12334 …
> Initialize TR_X86ProcessorInfo once

- compiler/x/codegen/OMRMemoryReference.cpp
Presently in the x86 code generator, there is an optimization during
MemoryReference creation that always assumes that accesses to local
objects via a loadaddr should use the frame register, as opposed
to evaluating (or re-using) the register associated with the loadaddr
as the base register.
Add an environment variable `TR_useLoadAddrRegisterForLocalObjectMemRef`
to disable this optimization for diagnostic purposes.
> Add flag to disable loadaddr specialization in x86 MemoryReferences

- compiler/riscv/codegen/OMRLinkage.cpp
- compiler/riscv/codegen/OMRLinkage.hpp
- compiler/riscv/codegen/RVSystemLinkage.cpp
- compiler/riscv/codegen/RVSystemLinkage.hpp
- compiler/riscv/codegen/RealRegister.hpp
This PR contains changes to RISC-V linkage properties - the aim is to reduce code duplication when implementing private linkage in consumer projects (e.g. OpenJ9). 
These changes are along the lines of earlier draft - #5836 which has been discusses on OMR Arch meeting on 2021-03-04 (#5816). 
This PR changes *only* the RISC-V codegen. Last two commits:
* RISC-V: move initialization of (system) linkage properties
* RISC-V: make system linkage properties static
make the linkage property instance shared among all instances of linkage as discusses. This perhaps  makes it quite different from all other backends. If this is considered too radical, I'm happy to drop these commits from this PR - they do not affect usefulness of the rest in consuming projects, just that it seems a logical step to …
> RISC-V: Refactor linkage properties

- port/unix/omrsysinfo.c
`z/OS` application using `IARV64`/`__moservices` can only allocate memory at `memory above bar` which is specified by `RLIMIT_MEMLIMIT`, not `RLIMIT_AS`.
related https://github.com/eclipse/omr/issues/5881
> Map OMRPORT_RESOURCE_ADDRESS_SPACE to RLIMIT_MEMLIMIT for z/OS 64 bit

- fvtest/compilertriltest/VectorTest.cpp
This commit adds test-cases for the vector subtraction tril tests in
VectorTest for the following vector data-types-
- VectorInt8
- VectorInt16
- VectorFloat
- VectorDouble
> AArch64: Vector sub tril test

- compiler/aarch64/codegen/ARM64Instruction.cpp
Handle VirtualGuardNOP as a branch instruction to OOL section.
> AArch64: Enable using VirtualGuardNOP as branch to OOL section.

- fvtest/compilertriltest/ArithmeticTest.cpp
- fvtest/compilertriltest/CompareTest.cpp
- fvtest/compilertriltest/IfxcmpgeReductionTest.cpp
- fvtest/compilertriltest/MaxMinTest.cpp
- fvtest/compilertriltest/ShiftAndRotateTest.cpp
This commit adds SKIP_ON_AARCH64() and SKIP_IF() to the tests of opcodes
that are not supported yet on AArch64.
> Skip some tests in compilertriltest on AArch64

- compiler/codegen/Relocation.cpp
- compiler/il/OMRResolvedMethodSymbol.cpp
- compiler/runtime/Runtime.hpp
This PR contains changes necessary to support the Method Handle feature in Eclipse OpenJ9 (https://github.com/eclipse/openj9/issues/4850), namely:
- Adding a new relo type, which is used to relocate special methods known to the VM.
- Ensuring consistency between the isInterpreted flag between the resolved method and resolved method symbol.
> Relocatable Compilation support for Method Handles in Eclipse OpenJ9

- compiler/p/codegen/OMRCodeGenerator.cpp
In POWER the peephole optimization for iushr, ishr uses rlwinm.
However, the rlwinm does not take into consideration of sign
extension that is required by iushr/ishr. This commit fix the case
for ishr so that the optimization is only possible for correct case.
> Fix Peephole optimization for iushr,ishr

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
> Remove unused _gpuParms and _gpuBlockDimX fields from Compilation class

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit improves code generation for the IL sequence i2l-lshl that
often appears in offset calculation for array access, by using `sbfm`
instruction.
> AArch64: Improve code generation for i2l-lshl sequence

- port/zos390/omrcel4ro31.h
- port/zos390/omrsl.c
The latest specification of the CEL4RO31 control block
consolidates the environment and entry point members into
a single function descriptor member.
> Update CEL4RO31 control block function descriptor member

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/OMRValuePropagation.hpp
This change adds a virtual method and base implementation of `isArrayCompTypeValueType` to `OMR::ValuePropagation` that can be used to determine whether the component type of an array is definitely, might be or is definitely not a value type.
The base implementation simply assumes any array's component type might be a value type if value type support is enabled, and that it is definitely not a value type otherwise.
> Define isArrayCompTypeValueType method for Value Propagation

- fvtest/compilertriltest/VectorTest.cpp
This commit adds test-cases for the vector multiplication & division
tril tests in VectorTest for the following vector data-types-
- VectorInt8
- VectorInt16
- VectorFloat
- VectorDouble
> AArch64: Vector mul-div tril test

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
In copy method we checked 2x if forwarding succeeded. It's needed for
Concurrent Scavenger for 2 different paths: small objects
(allowing duplicates) and large objects (disallowing duplicates).
These 2 `if` checks (and their associated then&else code blocks) were
serialized, but now they are nested. It makes it somewhat easier to
read, but more importantly more friendly for later code versioning
for CS and nonCS case.
A small compromise is that handling of failed forwarding path now is
duplicated at the level of source code (now at each end of those 'if's,
while it used to be only once at the very end). Still, in run time, it's
only handled once.
> Reorg Scavenger::copy() epilog

- compiler/aarch64/codegen/BinaryEvaluator.cpp
Reverts eclipse/omr#5890
#5890 introduced many failures in https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/209/
> Revert "AArch64: Improve code generation for i2l-lshl sequence"

- cmake/modules/platform/arch/s390.cmake
We do not want the flag for z/OS, and on zLinux we get the flag via
OMR_PLATFORM_DEFINITIONS (see lower in the file).
> Remove _LONG_LONG from TR_COMPILE_DEFINITIONS on z

- CONTRIBUTING.md
- doc/GitCrashCourse.md
- scripts/commit-msg
The Eclipse Foundation no longer requires commits to be signed.  Modify
documentation and tooling to reflect that.  Also, clean up some of the
related wording in the CONTRIBUTING.md guide.
See https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html
> Remove Signed-off-by requirement for OMR commits

- example/glue/ScavengerDelegate.hpp
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
When we consider yielding in Concurrent Scavenger (prematurely
terminating scanning loop, while in concurrent phase, due to external
Exclusive Access Request being raised), we can now rely on explicit flag
that tells us we are really in concurrent phase. Yielding while in STW
phases is meaningless.
Previously we checked if we were not in STW mode by checking that
exclusive access was in 'pending' state, but exclusive VM access
actually can be pending even state is already 'exclusive'. This is true
when exclusive VM access was requested by external thread. In this case,
we could incorrectly conclude we are not in concurrent mode, and never
yield.
> Check if current phase concurrent when trying to yield

- compiler/aarch64/env/OMRCPU.cpp
- compiler/aarch64/env/OMRCPU.hpp
This commit adds `supportsFeature` method to `OMRCPU` class for aarch64.
> AArch64: Add query for supported feature of CPU

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Use correct parameter for `dmb` instrutions.
- for shareability domain parameter, the correct one is `inner shareable domain`.
- barrier required after volatile load is an acquire barrier. A full barrier is not required.
> AArch64: Use correct parameter for memory barrier instructions

- compiler/il/SymbolReference.hpp
Match underlying OMR::SymbolReference constructors and enable it for extension.
> Add default constructor for SymbolReference

- compiler/p/codegen/PPCSystemLinkage.cpp
AbsoluteHelperAddress relocation store and patch an absolute helper
address in a series of instructions. This commit uses this relocation
for calls with PPCSystemLinkage.
AbsoluteHelperAddress relocation implementation: eclipse/openj9#12008
> Add AbsoluteHelperAddress Relocation for PPCSystemLinkage calls

- compiler/env/TRPersistentMemory.cpp
- compiler/infra/OMRMonitor.cpp
- compiler/infra/OMRMonitorTable.hpp
The global `memoryAllocMonitor` is no longer used by the persistent allocator in OpenJ9 - it was removed in https://github.com/eclipse/openj9/pull/12443. This PR removes its definition from OMR.
> Remove unused global memoryAllocMonitor definition

- compiler/ras/Debug.cpp
The object comparison non-helper is not recognized by `TR_Debug::getName`, so it's shown in tree listings as `unknown[#337  helper Method]`.  This change has its name reported as `<objectEqualityComparison>`.
> Use a human readable name for the object comparison non-helper

- gc/base/standard/CompactScheme.cpp
- tools/hookgen/HookGen.cpp
This PR fixes compiler errors in the OpenJ9 build when the compile time flag `DEBUG` is defined.
> Fix compiler errors when DEBUG is defined

- compiler/x/codegen/OMRMemoryReference.cpp
- compiler/x/codegen/OMRMemoryReference.hpp
Remove the remaining deprecated references.
See #5064
> Remove deprecated references to X86 UnresolvedVirtualCallSnippets

- compiler/ras/Debug.cpp
- compiler/ras/Debug.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
This parameter is no longer used.
Closes: #5055
> Deprecate isWarm parameter for data snippets

- cmake/modules/platform/toolcfg/gnu_exports.exp.in
Put the semicolons at the end of a line rather than at the beginning of the next line.
Generate this:
```
{
global :
a;
b;
local : *;
};
```
instead of
```
{
global :
a
;b
;
local : *;
};
```
> Generate normal .exp files

- fvtest/porttest/omrstrTest.cpp
- include_core/omrport.h
- port/common/omrport.c
- port/common/omrstr.c
- port/omrportpriv.h
This was motivated by eclipse/openj9#12397.
* like `omrstr_ftime()`, with a flag for requesting UTC formatted time
* support '%a' format specifier
* simplify implementation for Windows
* remove obsolete code
* add new tests
* clean up
- add missing struct tags
- initialize local variables
- make comparisons with zero explicit
- add missing parentheses
- remove unnecessary braces in switch cases
- fix spelling of `@param` in documentation
> Add omrstr_ftime_ex()

- cmake/modules/ddr/DDRSetStub.cmake.in
Ensure that macros from limits.h have correct values on 64bit builds.
> CMake: fix ddr macro processing on z/OS

- port/zos390/omrcel4ro31.c
Two fixes:
- In omrcel4ro31, add OMR_EBCDIC guards around two a2e calls to
ensure the module and function name is EBCDIC irregardless of
whether OMR is being built with EBCDIC or ASCII convlit.  For the
fvtests in omrporttest, OMR is built as EBCDIC.
- Update CELQGIPB offset from CAA fast vector array to +96.
> Guard a2e calls and update CELQGIPB vector offset

- fvtest/porttest/CMakeLists.txt
- fvtest/porttest/omrslTest.cpp
- fvtest/porttest/sltestlib31/sltest.cpp
- fvtest/porttest/sltestlib31/sltestlib31.exportlist
Add an omrport shared library test to load 31-bit libraries
from 64-bit and query a function via the CEL4RO31 interface on zOS.
> Add omrsl cel4ro31 testcase

- compiler/compile/OMRNonHelperSymbols.enum
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
This symbol represents the floatTemp1 field in j9vmthread.
It will provide another mechanism for the compiler to insert
temporary information at run-time that the VM can use, similar
to how tempSlot is used. While the name suggests this field
would contain floats, other data types could also be stored.
> Add j9VMThreadFloatTemp1Symbol

- cmake/modules/ddr/DDRSetStub.cmake.in
> CMake: fix typo in DDRSetStub.cmake.in

- cmake/modules/platform/toolcfg/xlc.cmake
- cmake/modules/platform/toolcfg/zos_rename_exports.cmake
Copy the .x files to the ARCHIVE_OUTPUT_DIRECTORY to be consistent with the
CMake model. However, we continue to copy the .x files to the
RUNTIME_OUTPUT_DIRECTORY as well, to work around a bug in CMake which causes
it to look for the .x files in the wrong directory.
> CMake: update z/OS export handling

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
This API is unimplemented and calling it and using the result will
likely produce a crash. This API is used in dead code paths:
1. DFP
2. arraycmpWithPad
3. pdneg
4. vsetlem
under certain circumstances. Please see the self review in the PR which
is associated to this commit for explicit reasons as to why failing the
compilation in each case is safe and warranted.
Closes: #5937
Closes: #2180
> Deprecate findOrCreateLiteral codegen API

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Add support for inlining the atomic intrinsics on aarch64.
- atomicAddSymbol
- atomicFetchAndAddSymbol
- atomicSwapSymbol
Issue: https://github.com/eclipse/omr/issues/2958
> AArch64: Implement atomic add and swap codegen support

- thread/common/omrthreadinspect.c
Enable omrthread_get_stack_range on AIX
> Enable omrthread_get_stack_range on AIX

- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/env/OMRCPU.hpp
The minimum target processor level for OMR code generation is Pentium 4,
which has support for SSE2.  All modern operating systems are assumed
to support preserving the SSE state.  Disable x87 code generation in
preparation for removal.
Issue: #946
> Disable x87 floating point for 32-bit code generation

- cmake/modules/OmrMetalC.cmake
- port/CMakeLists.txt
- Move handling of -q64 flag to ensure it gets properly set regardless of
scoping
- add -qnosearch and -I/usr/include/metal by default as standard c headers
are unusable by metal-c
- Move port library metal-c files to new library to work around
limitations on older versions of cmake
> CMake: Update metal-c handling

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit enables byteswap on AArch64.
Evaluators for sbyteswap/ibyteswap/lbyteswap are already implemented.
> AArch64: Enable byteswap

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/arm/codegen/OMRCodeGenerator.cpp
- compiler/arm/codegen/OMRMachine.cpp
- compiler/arm/codegen/OMRRegisterDependency.cpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRMachine.cpp
- compiler/p/codegen/OMRRegisterDependency.cpp
- compiler/riscv/codegen/OMRCodeGenerator.cpp
- compiler/riscv/codegen/OMRMachine.cpp
- compiler/riscv/codegen/OMRRegisterDependency.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/OMRRegisterDependency.cpp
This option is inconsistently used throughout the codebase. It was
originally introduced when OOL code sequences were first implemented as
a fallback path due to register allocation issues.
We have been using OOL sequences for almost a decade now and in some
places we don't even have a guard or fallback path against using OOL,
so enabling this option is not safe. Because of these reasons it is
best to just remove it.
Closes: #5968
> Deprecate TR_DisableOOL option

- thread/common/omrthreadinspect.c
Fix omrthread_get_stack_range behaviour on AIX
On AIX stack start means where sp begins not the low memory.
This is the opposite of how it is on linux and how this API is
intended to be used.
> Fix omrthread_get_stack_range behaviour on AIX

- compiler/aarch64/env/OMRCPU.cpp
- compiler/aarch64/env/OMRCPU.hpp
- compiler/arm/env/OMRCPU.hpp
- compiler/env/OMRCPU.hpp
- compiler/p/env/OMRCPU.cpp
- compiler/p/env/OMRCPU.hpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/env/OMRCPU.hpp
- compiler/z/codegen/OMRInstruction.cpp
- compiler/z/env/OMRCPU.cpp
- compiler/z/env/OMRCPU.hpp
This commit cleans up and simplifies usage of the getProcessorName routines in z/codegen's implementation of OMRCPU.
> Update getProcessorName routines

- cmake/modules/platform/os/zos.cmake
- fvtest/algotest/CMakeLists.txt
- fvtest/compilertriltest/CMakeLists.txt
- fvtest/gctest/CMakeLists.txt
- fvtest/porttest/CMakeLists.txt
- fvtest/porttest/omrsignalTest.cpp
- fvtest/porttest/si.cpp
- fvtest/porttest/testProcessHelpers.cpp
- fvtest/sigtest/CMakeLists.txt
- fvtest/threadextendedtest/CMakeLists.txt
- fvtest/threadtest/CMakeLists.txt
- fvtest/threadtest/createTestHelper.h
- fvtest/utiltest/CMakeLists.txt
- omrsigcompat/CMakeLists.txt
- omrtrace/omrtracewrappers.cpp
- port/CMakeLists.txt
- thread/CMakeLists.txt
- util/CMakeLists.txt
- util/a2e/CMakeLists.txt
- Move include folders from platform includes to omr_ascii since they
aren't required when doing an EBCDIC build
- Make omr_port_obj inherit compile options from omr_base so releveant
a2e flags get applied if required.
> CMake: Update handling of a2e/omr_ascii

- gc/base/Collector.cpp
- gc/base/Collector.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
- gc/base/standard/Scavenger.hpp
- gc/stats/ConcurrentMarkPhaseStats.hpp
- gc/stats/ConcurrentPhaseStatsBase.hpp
- gc/verbose/VerboseHandlerOutput.cpp
- gc/verbose/VerboseHandlerOutput.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.hpp
Introduce `concurrent-start/end` stanza pair for Concurrent Global Marking to match with scavenging. Concurrent-start stanza is printed in initial STW phase as we transition away from init complete and concurrent-end can be printed either before final STW (when we exhaust concurrent work) or during STW (if halted).
- New API in `MM_Collector`:
- `notifyAcquireExclusiveVMAccess` to notify local collector
- New API in `MM_ConcurrentGC`:
- `preConcurrentInitializeStatsAndReport` for triggering concurrent-start event
- `postConcurrentUpdateStatsAndReport` for triggering concurrent-end event
- `notifyAcquireExclusiveVMAccess` to recored time stamp when concurrent marking is halted or completed in STW
- Introduce a subclass `MM_ConcurrentMarkPhaseStats` of `MM_ConcurrentPhaseStatsBase`
- New …
> Adding `concurrent-start/end` for Concurrent Global/Marking

- gc/base/Configuration.cpp
- gc/base/GCExtensionsBase.hpp
Introduce a new default scan ordering type 'none'. In gencon configuration, scan ordering will be set to hierarchical if it has not already been overridden by an option. In balanced, scan ordering will be set to dynamic BF if it has not already been overridden by an option.
> Introduce New Default Scan Ordering 'None'

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/arm/codegen/OMRCodeGenerator.cpp
- compiler/arm/codegen/OMRCodeGenerator.hpp
- compiler/arm/codegen/OMRInstruction.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/il/OMRBlock.hpp
- compiler/optimizer/OMRSimplifier.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
- compiler/riscv/codegen/OMRCodeGenerator.cpp
- compiler/riscv/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRInstruction.cpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/S390Instruction.cpp
- compiler/z/codegen/S390Instruction.hpp
See commit messages for details on what was done. Unfortunately on x86 we seem to be doing something completely different from all the other platforms, so in general tackling register allocation on x86 will need to be done separately.
Fixes: #5977
> Unify doRegisterAssignment on all platforms except x86

- port/CMakeLists.txt
With enabling vector code generation for Project Panama, AIX systems
need to define `__EXTABI__` for full Vector ABI support. This is
required for the signal handling code in the port library.
> Define __EXTABI__ for Port library compilation on AIX64

- thread/common/omrthreadinspect.c
Fix omrthread_get_stack_range on Mac OSX
On Mac OSX stack start means where sp begins not the low memory.
This is the opposite of how it is on linux and how this API is
intended to be used.
> Fix omrthread_get_stack_range on Mac OSX

- compiler/il/OMROpcodes.enum
This commit corrects the IL Opcode properties of vnot so that it will
be of the same type as the node's children.
> Update vnot IL Opcode Properties

- util/omrutil/CMakeLists.txt
This ensures that omrutil_obj is compiled with required a2e flags.
> CMake: apply omr_base flags to omrutil_obj

- cmake/modules/OmrCompilerSupport.cmake
- compiler/compile/OMRCompilation.hpp
- compiler/control/OMROptions.cpp
- compiler/env/FEBase.cpp
- compiler/il/OMRBlock.cpp
- compiler/infra/BitVector.cpp
- compiler/infra/BitVector.hpp
- compiler/optimizer/DebuggingCounters.cpp
- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/LoopVersioner.hpp
- compiler/optimizer/Structure.cpp
- compiler/optimizer/VPHandlers.cpp
The commits have addressed all warnings on an OSX build, so to prevent
new warnings from being introduced we enable warnings as errors only on
this platform. Future platforms will follow. See each commit for an
explanation of what warning was triggered and fixed.
Issue: #1640
> Enable warnings as errors in compiler component on OSX

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Use atomic operation instructions for calls for atomic method symbols
if FEAT_LSE is available on target CPU.
> AArch64: Use atomic operation instructions for atomic method symbols

- fvtest/compilertriltest/VectorTest.cpp
This commit adds Tril test-cases for the vector bitwise operations in
VectorTest. Following operations are covered-
- Vector And
- Vector Or
- Vector Exclusive Or
- Vector Negation
- Vector Not
> Vector bitwise Tril tests

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.hpp
This patch implements the proposed changes in #5912.
This commit moved all instances of the _ialoadUnneeded attribute to the Z subfolder:
- Moved  "List<TR_Pair<TR::Node, int32_t> > _ialoadUnneeded;" from compiler/codegen/OMRCodeGenerator.hpp to z/codegen/OMRCodeGenerator.hpp
- Moved "_ialoadUnneeded(comp->trMemory())," from compiler/codegen/OMRCodegenerator.cpp to z/codegen/OMRCodeGenerator.cpp
Closes: #5912
> Move _ialoadUnneeded field to Z CodeGenerator

- gc/base/HeapRegionDescriptor.hpp
- gc/base/ObjectHeapBufferedIterator.cpp
- gc/base/ObjectHeapBufferedIterator.hpp
In order to smooth transition for replacing MemoryPoolBumpPointer
with MemoryPoolAddressOrderedList, update setMarkMapValid() to handle
both AddressOrdered and BumpPointer regionType.
Rollback the changes in ObjectHeapBufferedIterator.
it is a fix for omr acceptance build failures, which is caused by https://github.com/eclipse/omr/pull/5783 
> Handle both AddressOrdered and BumpPointer regionType in setMarkMapValid

- compiler/z/codegen/OMRCodeGenerator.hpp
For use in downstream projects. OpenJ9 is a consumer.
> Make _ialoadUnneeded protected

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Added `enableAggressiveInlining` command line option which, under the covers,
will enable other options or set threshold values such that the Inliner is
more aggressive in inlining callees. This is done in the `jitPostProcess()`
phase, so it may override other inliner specific options, also present on
the command line.
The new option is directed at experimentation and not geared towards
production use. Moreover, the new option cannot be applied in a subset,
but only globally, to all the methods.
> Add command line option to make inliner more aggressive

- port/aix/omrvmem.c
xlpCodeCacheTests fails on AIX because the default
code cache large page size 64K is absent in the
list of available code cache large page sizes
output by `-verbose:sizes`.
Include 64K in the list of available code cache
large page sizes for the test to parse as the
expected page size when no `-Xlp` option is
supplied and the default page size is used.
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com
> Allow 64K page size as a valid option on AIX

- gc/base/MemoryPoolAddressOrderedList.hpp
Incremental Card Alignment is designed only for 64bit system,
the code should never run on 32/31 bit system, use OMR_ENV_DATA64
precompile define to avoiding the side affection on 32/31 bit system.
fix:  acceptance build issue on Z/OS
> Limit Incremental Card Alignment under 64 bit system

- gc/base/Configuration.cpp
- gc/base/GCExtensionsBase.hpp
Update scan ordering configuration for more correct configuration of adaptiveGcCountBetweenHotFieldSort.
Related to PR: https://github.com/eclipse-openj9/openj9/pull/12514
> Update Default Scan Ordering Configuration

- compiler/compile/OMRCompilation.cpp
In the profiling compilations that was using JIT Profiler, we had to
disable the OSR in profiling compilations as we had to duplicate the
method and size would become an issue and profiling compilations are
very short-lived. With JProfiler we do not need to duplicate the method
body and counters to collect profiling data are inserted in the code.
This commits enables OSR and sets HCR mode to osr from traditional for
profiling compilations when JProfiler is used which would allow us to
collect accurate profile of the method to be used in subsequent
compilations which by default has OSR enabled.
> Enable OSR for profiling compilations with JProfiling

- compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit fixes an issue introduced by #6011.
The i2l-lshl optimization skips assigning a register to the i2l node.
When the i2l node has two or more references, the i2l node is evaluated
later again, and it leads to unexpected results.
> AArch64: Fix i2l-lshl optimization

- compiler/optimizer/Inliner.cpp
- compiler/optimizer/Inliner.hpp
Previously, for direct calls, targets that appear to be a different method from the one specified by the call node's symbol reference would always be removed.
This behaviour is still the default, but the new query allows downstream projects to customize the conditions under which those targets are removed, e.g. by exempting certain methods.
> Allow inliner policy to decide whether to remove differing targets

- example/glue/ObjectModelDelegate.cpp
- example/glue/ObjectModelDelegate.hpp
- gc/base/ObjectModelBase.hpp
Refactor CopyForward to be more consistent with Scavenger by reusing the existing fixupForwardedObject method from ObjectModel. This allows for the simplification of calculateObjectDetailsForCopy for balanced as `doesObjectNeedHash` argument is no longer needed.
Related to: https://github.com/eclipse-openj9/openj9/pull/12661
> Refactor CopyForward to reuse fixupForwardedObject

- compiler/z/codegen/OMRCodeGenerator.cpp
On Z, during trees lowering phase, it checks if the encountered aloadi
node while walking trees appears under nopable inline guards. Conditions
used to check if we are going to generate NOP for such parent Virtual
Guard node (In which case, aloadi would not be evaluated) while marking
aloadi unneeded was incorrect and in some cases, it would mark such
aloadi unneeded even though it will generate the inline test which
eventually can cause incorrect functional behaviour.
> Correct condition used to setting unneeded aloadi

- compiler/ras/Debug.cpp
This commit changes `TR_Debug::getRuntimeHelperName` to return valid name
for `TR_ARM64jitCollapseJNIReferenceFrame`.
> AArch64: Add TR_ARM64jitCollapseJNIReferenceFrame to getRuntimeHelperName

- compiler/p/codegen/OMRInstOpCode.enum
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCOpsDefines.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
This implementation uses wider load than current inlineArrayCmp, as
well as minimal branching.
> InlineArrayCmp improvements for P10

- port/zos390/omrvmem.c
`omriarv64.h` is for `zOS 64bit`, and should not be included for `zOS 31bit`.
> Include omriarv64.h only for ZOS 64bit

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Duplicated definitions of some evaluators cause build breaks.
This commit fixes them.
> AArch64: Fix build break by duplicated evaluators

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/ras/Debug.hpp
- compiler/ras/LimitFile.cpp
Deleting generally unused code guarded by TR_OrderedCompiles as per https://github.com/eclipse-openj9/openj9/issues/12500
Should not be merged before https://github.com/eclipse-openj9/openj9/pull/12809
Closes https://github.com/eclipse-openj9/openj9/issues/12500
> Remove TR_OrderedCompiles

- compiler/optimizer/LocalOpts.cpp
This loop expected that, for a given `exitTreeTop`, the next tree `exitTreeTop->getNextTreeTop()` would remain fixed even if the current block is removed from the trees. However, we shouldn't assume anything about the next/prev pointers of trees that have been deleted, since it's highly unclear which trees are supposed to be before/after a deleted tree. And indeed, the removal of the current block can sometimes update the next pointer. In particular, this happens when removing an empty block (in the following example, `block_X`) with two predecessors, one of which falls through (`block_F`) and one of which branches (`block_B`):
BBStart <block_B>
...
if... --> block_X
BBEnd </block_B>
...
BBStart <block_F>
... (can fall through)
BBEnd </block_F>
BBStart <block_X>
BBEnd </block_X>
BBStart …
> Fix iteration in redundant goto elimination

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
- compiler/compile/ResolvedMethod.cpp
using TR::ResolvedMethodSymbol::createJittedMethodSymbol directly 
> Remove wrapper method createJittedMethodSymbol in Compilation

- compiler/il/OMRSymbol.hpp
- compiler/il/OMRSymbol_inlines.hpp
Includes getter/setter functions. This flag is used to identify
symbols corresponding to dummy TR_ResolvedMethod that are not
really resolved, but treated as such as the resolution mechanism
involves resolving the arguments instead. An example of that is
linkToStatic, which is a VM internal native call that is created
for unresolved invokedynamic and invokehandle bytecodes.
> Add DummyResolvedMethod flag to OMR Symbol

- compiler/optimizer/OMRValuePropagation.cpp
Ignore unreachable paths when merging defined on all paths in GlobalVP. 
Signed-off-by: Gita Koblents <koblents@ca.ibm.com>
Related:
[1] https://github.com/eclipse/omr/commit/de384893e9c36dff5b7329ed14e23bd23f15733f
> Ignore unreachable paths when merging defined on all paths in GlobalVP

- fvtest/porttest/omrslTest.cpp
- fvtest/porttest/sltestlib31/sltest.cpp
- port/zos390/omrcel4ro31.c
- port/zos390/omrsl.c
A few miscellaneous updates and fixes related to CEL4RO31:
- LE added a new CEEPCB_3164 bit on CEEPCBFLAG6 flag within Process
Control Block (PCB) to indicate support for CEL4RO31/64.  Update
omr_cel4ro31_isSupported() and sl_testOpen31bitDLLviaCEL4RO31
to use this new bit.
- Add extern "C" to sltestlib31's function to ensure name is
not C++ mangled.
- Capture the CEL4RO31 return code for function lookup
to the Trc_PRT_sl_lookup_name_Exit2 when function is
not found.
> zOS: Exploit CEEPCB_3164 indicator bit + propagate CEL4RO31 lookup return code

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRCodeGenerator.hpp
POWER CG implements instanceOfEvaluator but not `supportsInliningOfIsInstance`. This commit implement it allowing a call node to Class.isInstance() to be changed to an `instanceof` node.
Depends on eclipse-openj9/openj9#12622 which fixes the `ifInstanceOf` evaluator for certain cases.
> Implement supportsInliningOfIsInstance on POWER

- compiler/optimizer/VPHandlers.cpp
Fix accessing NULL lhs or rhs when printing VP in trace
> Fix accessing NULL lhs or rhs when printing VP in trace

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
An expression for TR_ASSERT_FATAL() in
compareIntsAndBranchForArrayCopyBNDCHK() for AArch64 is wrong.
> AArch64: Fix compareIntsAndBranchForArrayCopyBNDCHK()

- compiler/env/OMRPersistentInfo.cpp
- compiler/ras/DebugCounter.cpp
> Move definition of PersistentInfo::createCounters to cpp file

- compiler/optimizer/OMROptimizer.cpp
- compiler/optimizer/Optimizer.hpp
- compiler/optimizer/Optimizer_inlines.hpp
enable self method to be referenced in extended Optimizer
> Remove inline keyword from OMR::Optimizer::self in cpp file

- gc/stats/FreeEntrySizeClassStats.hpp
- gc/stats/LargeObjectAllocateStats.cpp
- gc/stats/LargeObjectAllocateStats.hpp
global variables largeObjectAllocationProfilingVeryLargeObjectThreshold,
largeObjectAllocationProfilingVeryLargeObjectSizeClass and
freeMemoryProfileMaxSizeClasses are initialized during
MM_LargeObjectAllocateStats construction, new static method
initializeFreeMemoryProfileMaxSizeClasses is created for avoiding the
case, which the global variables has been used before initialized.
> New static method initializeFreeMemoryProfileMaxSizeClasses

- compiler/env/OMRPersistentInfo.cpp
- compiler/ras/DebugCounter.cpp
Reverts eclipse/omr#6065
More investigation is needed into why this causes a problem on Power.
> Revert "Move definition of PersistentInfo::createCounters to cpp file"

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
This commit accommodates the changes needed to support Int32 and Int64
data types for Vector arithmetic operations. The following operations
are covered-
- Vector Add (VectorInt32, VectorInt64)
- Vector Subtract (VectorInt32, VectorInt64)
- Vector Multiplication  (VectorInt32)
> AArch64: Vector Int32 & Int64 Support

- compiler/riscv/codegen/BinaryEvaluator.cpp
- compiler/riscv/codegen/OMRCodeGenerator.cpp
- compiler/riscv/codegen/OMRLinkage.cpp
- compiler/riscv/codegen/OMRLinkage.hpp
- compiler/riscv/codegen/OMRMachine.cpp
- compiler/riscv/codegen/OMRRegisterDependency.cpp
- compiler/riscv/codegen/RVDebug.cpp
- compiler/riscv/codegen/RVInstruction.cpp
- compiler/riscv/codegen/RVSystemLinkage.cpp
- fvtest/compilertriltest/CallTest.cpp
- fvtest/compilertriltest/LinkageTest.cpp
This PR adds support for calls without trampolines as a temporary solution until #2017 is implemented.
> RISC-V: implement calls without trampolines

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit accommodates the implementation of the vector splat
operation and respective opcodes for the data types-
- VectorInt8
- VectorInt16
- VectorInt32
- VectorInt64
- VectorFloat
- VectorDouble
> AArch64: Vector Splat Implementation

- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
Copy is now an inline function which calls copyForVariant, which
performs the previous functionality for copy. copyForVariant is a
template function that is told the variant of template that it is to
use, either CS or STW. This dictates if copyForVariant should
exhibit Concurrent Scavenger behaviour or Stop The World behaviour.
The enum CopyVariant is introduced to represent the different variants
of copyForVariant. The two options are STW for IS_CONCURRENT_ENABLED
== false, and CS for IS_CONCURRENT_ENABLED == true.
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
> Refactor copy to use template for concurrent GC

- compiler/ras/Debug.hpp
This commit adds printARM64ArgumentsFlush to TR_Debug.
> AArch64: Add TR_Debug::printARM64ArgumentsFlush

- compiler/aarch64/CMakeLists.txt
- compiler/aarch64/runtime/ARM64arrayCopy.spp
This commit adds assembly file for arraycopy for primitive
nodes in forward and backward directions.
Issue: #6438
Co-authored-by: KONNO Kazuhiro <konno@jp.ibm.com>
> AArch64: Assembly helper for arraycopy

- README.md
Once eclipse-cbi/jiro#173 was merged, it became clear that there no longer is a 'Linux x86-64 Compressed Pointers' build. This removes the reference to that obsolete build.
> Remove link to obsolete compressed pointers build

- gc/base/ParallelSweepChunk.hpp
- gc/base/SweepPoolManager.hpp
- gc/base/SweepPoolManagerAddressOrderedListBase.cpp
- gc/base/SweepPoolManagerAddressOrderedListBase.hpp
- gc/base/standard/SweepHeapSectioningSegmented.cpp
New variable _minFreeSize in MM_ParallelSweepChunk for keeping minimum
free entry size for sweeping related memory pool.
Avoid callback check and retrieve minimum free entry size from
memorypool every time.
for Default case:
minimum free entry size = memorypool.minimumFreeEntrySize
> Simplify the logic for identifying minimum free size for sweeping

- util/a2e/atoe.c
- util/a2e/headers/old-stdio.h
- util/a2e/headers/stdio.h
gets() is deprecated in the C runtime (C99) and subsequently removed
(C11).
@0xdaryl fyi
> Remove atoe_gets() since gets() is insecure and deprecated

- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit contains the following changes:
- Remove unnecessary end-of-line characters from TR_ASSERT() messages
- Include header files in alphabetical order in OMRTreeEvaluator.cpp
- Change the indentation of a line in OMRTreeEvaluator.cpp
> AArch64: Code cleanup

- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
The evaluators removed in this commit are OpenJ9 specific and were previously being declared in OpenJ9. This commit removes the definitions down to OpenJ9 as well. The evaluators that cannot be moved down are now defined in the OMRTreeEvaluator class itself.
> Remove OpenJ9 specific evaluators from z/codegen

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit accommodates changes needed to enable the vectorization for
AArch64. The following changes are made-
- Called `setSupportsAutoSIMD()` in code generator.
- Implemented `getSupportsOpCodeForAutoSIMD()`
> AArch64: Enable Vectorization

- compiler/optimizer/LoopVersioner.cpp
Once versioner has decided to use loop transfer for a guard, there is a guarantee that the guard, if it is still present in the hot loop, will exit the loop if taken. The guard can still be versioned (and removed entirely from the loop), in which case there will no longer be any possibility that it could be taken at all. So the taken edge of the guard can always be disregarded when searching the loop for operations that will remain in the hot loop after versioning. To make such searches more precise, loop transfer candidates are automatically included in `_definitelyRemovableNodes` and `_optimisticallyRemovableNodes`.
One such search of the loop determines whether or not HCR guards can be versioned, and also finds the HCR guards to be versioned (if possible). By ignoring removable nodes …
> Version HCR guards even if they are loop transfer candidates

- compiler/compile/OMRCompilation.hpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/IntegerMultiplyDecomposer.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRInstOpCode.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
Add a new query to the TR::Compilation class to allow the compiler to
query whether the runtime is some kind of mode (such as
snapshot/restore) that would necessitate the generation of
code that is portable (ie generated on one system but can run on
another). This is different from relocatable compiles because, for
example with snapshot/restore, the code does not need to be relocated
but it does need to be portable.
Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>
> Add compilePortableCode query

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
This commit adds a new verbose option `TR_VerboseJITServerConns`.
The option is used by OpenJ9 JITServer to log connection events
between servers and clients.
> Add a new verbose option for JITServer

- compiler/optimizer/UseDefInfo.cpp
Don't use once read symbol heuristics in UseDef at warm
- Use onceReadSymbolsIndices at < warm since it helps performance
without considerably increasing compile time
> Don't use once read symbol heuristics in UseDef at warm

- include_core/AtomicSupport.hpp
If we are building with `-Wc,"convlit(ISO8859-1)"` xlC option then we
want to avoid doing literal conversion of inline assembly statements
because HLASM expects them to be in EBCDIC. Failing to do this results
in compilation errors with HLASM as it tries to interpret ASCII
characters of the inline assembly string.
This pragma is used elsewhere in the codebase so it is not something
new.
> Suspend convlit around inline assembly on z/OS

- compiler/aarch64/codegen/BinaryEvaluator.cpp
Generates `ubfm` instruction for shift and mask operation if the operation
can be encoded into `ubfm`.
> AArch64: Use ubfm instruction for shift and mask operation if possible

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
This commit enables use of shifted immediate value for
`add` and `sub` instructions and their variants.
> AArch64: Enable shifted immediate for add/sub instructions

- compiler/optimizer/VPHandlers.cpp
Use getVirtualCallNodeForGuard() during ValuePropagation
- replace existing code in constrainIfcmpeqne by a call
to getVirtualCallNodeForGuard()
> Use getVirtualCallNodeForGuard() during ValuePropagation

- compiler/codegen/Relocation.cpp
- compiler/codegen/Relocation.hpp
A label has a null address until its location is determined when it is encountered in the instruction stream during binary encoding. When the compiler generates a jump to a label whose address has not yet been determined, it also generates a label relocation to correct the jump target once the label's address is known after binary encoding. But if for some reason the label's address is never updated, the relocation would silently continue using zero and generate an incorrect jump.
Because such jumps can be hard to debug, this commit adds assertions that verify that the label has at least had some address set, otherwise failing fast. Note that zero cannot be the true address of a label, since we never generate instructions there.
> Assert that labels are defined when applying label relocations

- gc/base/SweepHeapSectioning.cpp
- gc/base/SweepHeapSectioning.hpp
- gc/base/standard/SweepHeapSectioningSegmented.cpp
- gc/base/standard/SweepHeapSectioningSegmented.hpp
Avoid logic duplication between SweepHeapSectioning subclasses
> Share common logic in SweepHeapSectioning base class

- port/osx/omrosdump.c
Dumping core using the signal requires an the task-get-allow
entitlement, which prevents notarization. Thus we dump the core
with a user space tool which does not require an entitlement.
Resolves https://github.com/eclipse/omr/issues/5813
fyi @keithc-ca
> Add new core dump tool for OSX

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit changes `genericBinaryEvaluator` to use negated value for add/sub
operation if the negated value can be loaded into the register with the fewer
instructions than original value.
Also, `genericBinaryEvaluator` to set a register to the constant node
if the constant cannot be encoded into the instruction and the negated value is not used.
This change prevents instructions to load the constant into the register from
generated multiple times even if the constant node has multiple reference counts.
> AArch64: Use negated constant value for add/sub node if it is more concise

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit changes populateMemoryReference() so that the compiler
generates ldr/str instructions with constant immediate offsets in
accessing arrays with constant indexes.
> AArch64: Use the immediate offset of ldr/str instructions

- compiler/il/OMRNode.cpp
- copy node's children early in case the node has typeless opcode
> Copy node's children early in OMR::Node::copyValidProperties

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
This option will be used to disable recognition of
the ForceInline annotation by the Inliner
> Add disableForceInlineAnnotations JIT command line option

- compiler/aarch64/codegen/OMRCodeGenerator.hpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements arraycopyEvaluator() and related functions
for primitive arraycopy for AArch64.
> AArch64: Implement arraycopyEvaluator() for primitive arraycopy

- compiler/optimizer/VPHandlers.cpp
Due to missing external relocation record, disable transforming VFT load
of known object with fixed class to loadaddr on Power when compiling
relocatable code without Symbol Validation Manager.
> Disable transforming VFTLoad to loadaddr on Power for nonSVM AOT

- compiler/p/runtime/ppcasmdefines.inc
The AIX assembler perform bitwise-and then negate the value when
`dq` is a negative value with a `-` sign. The pranthases ensure
negating the immediate before performing the and operation.
> Ensure correct instr construction with neg imm using AIX Assembler

- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/PartialRedundancy.cpp
- compiler/ras/Tree.cpp
Allow known object information to be associated with arbitrary nodes.
This will permit more accurate association of refined known object
info, and allow it to be placed on arbitrary nodes.
A new 32-bit bit field is added to the Node class in the padding
space between two fields.  This incurs no TR::Node footprint increase
on 64-bit architectures.
> Cache known object info on TR::Nodes

- compiler/aarch64/codegen/OMRMachine.cpp
This commit changes code generation of GPR-to-GPR "mov" instruction
in registerCopy() in register assignment for AArch64.
> AArch64: Change generation of "mov" instruction in register assignment

- compiler/ras/Tree.cpp
Disable `verifyGlobalIndices()` by default because the allocation below of `nodesByGlobalIndex` exposes a leak in `TR::Region` / `TR::SegmentProvider` when there are many nodes. This check has been effectively doing nothing in most builds anyway because it just traverses the trees doing `TR_ASSERT()`.
> Disable verifyGlobalIndices()

- compiler/compile/OMRNonHelperSymbols.enum
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/optimizer/LocalOpts.cpp
- compiler/ras/Debug.cpp
Compacting NULLCHK into computed calls will result in the NULLCHK
not being performed before dispatching into the call target if
there is no need for dereferencing of the reference child to
dispatch.
Furthermore, this PR introduces a new symbol required for eclipse-openj9/openj9#12341
> Prevent compacting NULLCHKs into computed call trees; add new symbol J9JNIMethodIDvTableIndexFieldSymbol

- compiler/aarch64/codegen/ControlFlowEvaluator.cpp
A relocation record for class or method pointer in the second child of
`ifacmpeq`/`ifampne` is missing if the constant value of it can be
encoded into 12bit immediate field.
This commit adds a relocation record for it by evaluating the node
if it needs relocation.
> AArch64: Add relocation record for second child of ifacmpeq/ifacmpne

- compiler/arm/codegen/ControlFlowEvaluator.cpp
- compiler/arm/codegen/OMRMemoryReference.cpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/p/codegen/OMRMemoryReference.cpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/PPCAOTRelocation.cpp
`TR_AOT` is a legacy option that isn't the way AOT compilations are controlled in downstream projects. `TR_EnableCompilationThread`/`TR_DisableCompilationThread` is no longer need in OpenJ9.
Needs to be merged together with https://github.com/eclipse-openj9/openj9/pull/13304 to prevent an OpenJ9 build break.
> Clean up TR_AOT and TR_(En|Dis)ableCompilationThread

- buildenv/jenkins/omrbuild.groovy
- fvtest/compilertest/CMakeLists.txt
- fvtest/tril/test/ASTTest.cpp
- gc/CMakeLists.txt
- gc/base/HeapRegionManager.hpp
- gc/base/LightweightNonReentrantRWLock.cpp
- gc/base/LightweightNonReentrantRWLock.hpp
- jitbuilder/CMakeLists.txt
- port/common/omrfilestream.c
- port/common/omrfilestreamtext.c
- port/unix/omrfiletext.c
- port/unix/omrsharedhelper.c
- port/unix/omrsysinfo.c
- port/unix_include/omriconvhelpers.h
- port/zos390/omrgetjobname.c
- port/zos390/omrgetstfle64.s
- port/zos390/omrgetuserid.c
- port/zos390/omrjobname.s
- port/zos390/omrosdump.c
- port/zos390/omrsysinfo_helpers.c
- port/zos390/omrsyslog.c
- port/zos390/omruserid.s
- port/zos390/omrzfs.c
- third_party/gtest-1.8.0/include/gtest/internal/gtest-internal.h
- thread/common/thrprof.c
- util/omrutil/gettimebase.c
- util/omrutil/unix/zos/omrgetdsa.s
Address the last warning on z/OS and enable warnings as errors on all S390 platforms.
> Enable warnings as errors in compiler component on S390

- compiler/control/CompileMethod.cpp
- compiler/ilgen/OMRMethodBuilder.cpp
- compiler/infra/CMakeLists.txt
- compiler/infra/String.cpp
- compiler/infra/String.hpp
- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/OMROptimizer.cpp
- `TR::[v]printfLen()`: return the length of the formatted string without writing the string into any buffer
- `TR::[v]snprintfTrunc()`: format into a fixed-size buffer, possibly truncating
- `TR::[v]snprintfNoTrunc()`: format into a fixed-size buffer with an assertion that the result is not truncated
- `TR::StringBuf`: a reusable growable `Region`-allocated buffer into which formatted text can be appended using `[v]appendf()`
These obviate the MSVC conditional `snprintf` `#define` at use sites, and they deal with the portability concerns of that `#define` correctly and in a centralized place. Additionally, `StringBuf` makes it simple to allocate enough memory to do formatting without truncation.
> Define compiler string formatting utilities

- compiler/aarch64/codegen/BinaryEvaluator.cpp
Fix `mulConstant32` and `mulConstant64` to use correct 32bit/64bit variant
of `mov` and `neg` instructions.
Resolves https://github.com/eclipse-openj9/openj9/issues/13401
> AArch64: Fix mulConstant32/64 to use correct instrutions

- gc/base/standard/Scavenger.cpp
Rason for condition change:
- allowDuplicate bool only set to true if CS is enabled. Compiler
can skip condition check for allowDuplicate if
OMR_GC_CONCURRENT_SCAVENGER is enabled but CS is disabled.
- nested if-forwarding-succeeded check succeeds in forwarding
the object if CS is disabled. This is for the case
OMR_GC_CONCURRENT_SCAVENGER but CS is disabled. Compiler can
go directly into succeeded logic
- if OMR_GC_CONCURRENT_SCAVENGER enabled but CS is disabled,
there's no need to check allowDuplicateOrConcurrentDisabled,
so we skip the block.
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
> Modified Concurrent Scavenger conditions to use compiler optimization

- gc/base/Configuration.cpp
Fix the possibility that GC scavengerScanOrdering is not initialized correctly when GC policy is gencon and splitFreeListSplitAmount is specified to be a value other than zero.
> Fix GC scavengerScanOrdering Not Initialized Correctly When splitFreeListSplitAmount is Specified

- azure-pipelines.yml
The added job does the equivalent of the [check in openj9](https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/jobs/infrastructure/lineEndingsCheck.groovy).
This was tested in my fork (without the existing jobs to speed testing); see https://github.com/keithc-ca/omr/pull/2.
Fixes: https://github.com/eclipse/omr/issues/2255.
> Add job to check line-endings

- compiler/env/FrontEnd.hpp
- compiler/ras/Debug.hpp
With `-Wall`, gcc complains about the multi-line comments (notice the trailing `\` in the letter D).
> Fix compiler warnings

- ddr/lib/ddr-scanner/dwarf/DwarfFunctions.cpp
- ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
Using the GNU compiler option `-gdwarf-2` means that field offset expressions cannot use `DW_FORM_exprloc` because that form was not introduced until DWARF version 4; so the compiler instead uses `DW_FORM_block*`.
> Interpret field offsets in 'block' forms as expressions

- compiler/il/OMRNode.cpp
- compiler/optimizer/OMRValuePropagation.hpp
- compiler/optimizer/VPHandlers.cpp
- compiler/optimizer/ValuePropagationCommon.cpp
- compiler/optimizer/VirtualGuardCoalescer.cpp
- handle direct calls, use call site index and bytecode index to
find the right call
- sometimes, at the time the guard is seen not all constraints
are available for the call. Keep a side table that maps call node
to the corresponding guard and try to eliminate the guard at the
time the call is encountered
- support multiple guards pointing to the same block
- Check isTheVirtualCallNodeForAGuardedInlinedCall inside getVirtualCallTreeForGuard
> Improve non-overridden guard optimization in globalVP

- compiler/compile/OMRSymbolReferenceTable.cpp
It's possible to encounter an unresolved call, then to resolve its CP entry in another thread, and finally encounter another call with the same CP index, which is now resolved. In this situation, sharing is usually prevented due to the `!(resolvedMethod && symRef->isUnresolved())` condition. However, a dummy resolved method does not satisfy `symRef->isUnresolved()`.
It's important not to share the symbol reference because the dummy resolved method used in the unresolved case may expect arguments of a different type or a different number of arguments from the real resolved method.
> Avoid symbol reference sharing for dummy resolved methods

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
A workaround for huge methods was introduced in #5819 because the range of
AArch64 conditional branch is +/- 1MB.
This commit enhances the workaround by taking into account the size of
snippets which was disregarded in #5819.
> AArch64: Consider snippets size when aborting compilation of huge methods

- gc/base/MemorySubSpaceSemiSpace.cpp
- gc/base/MemorySubSpaceSemiSpace.hpp
- gc/base/omrmmprivate.hdf
- gc/base/standard/Scavenger.cpp
- gc/base/standard/Scavenger.hpp
- gc/include/omrmm.hdf
- gc/stats/ConcurrentMarkPhaseStats.hpp
- gc/stats/ConcurrentPhaseStatsBase.hpp
- gc/stats/ScavengerStats.cpp
- gc/stats/ScavengerStats.hpp
- gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
Issue reported in https://github.com/eclipse/omr/pull/5830#discussion_r584834266
Move `_start/_endTime` from `MM_ScavengerStats`
to `MM_Scavenger` and rename to `_cycleStart/End`.
Rename `MM_MemorySubSpaceSemiSpace::_lastScavengeEndTime`
to `_lastGCEndTime`
Rename `MM_ScavengerStats::_workerScavengeStart/EndTime`
to `_start/endTime`
Add `incrementStart/EndTime` to `MM_LocalGCEndEvent`
> Move `_start/_endTime` in `ScavengerStats` to `Collector`

- gc/CMakeLists.txt
Ensure that the omr_base compile flags get applied to omrgc_tracegen.
This is important on z/OS to ensure that we get relevant ascii/ebcdic
flags.
> CMake: Fix compile flags on omrgc_tracegen

- compiler/env/MemorySegment.hpp
...so that they will actually be checked.
> Use TR_ASSERT_FATAL for TR::MemorySegment asserts

- compiler/compile/OMRCompilation.cpp
To stay consistent with other platforms, internal pointers will be disabled for PPC under OptServer. They were temporarily re-enabled due to a 20% regression on WAS and Liberty, but this occurred nearly seven years ago, so the chances of reproducing it now are low. As of the time of this commit, further investigation is being done into Liberty performance, so if this does expose a bug or regression, it will be caught, and a permanent fix can be implemented.
Signed-off-by: midronij <jackie.midroni@ibm.com>
> Disable Internal Pointers for PPC under OptServer

- port/osx/omrosdump.c
Handle checking the readability of memory segments from vm_region_recurse_64
and writing the readable segments in one step since multiple calls to
mach_vm_read on the same address seems to cause errors.
Fixes the issue behind https://github.com/eclipse/omr/pull/6111
@keithc-ca can you take a look at this PR please?
[Here is the diff from the previous PR.](https://github.com/eclipse/omr/compare/cfed42b96e55fe5469faed7954b90e0e0f3749c8..efa54584e7c086d5d54ab2732b03a9c16ad8888e#diff-2cc72c0aa6d3f2c9e0d641e5d5ed70a8a4974c2dd774715419ff65bc73346b5a)
> Fix unreadable memory segments when writing core

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
The commit changes `TR::ARM64ImmSymInstruction::generateBinaryEncoding` to
call `redoTrampolineReservationIfNecessary()` even if label is not null,
which happens when a direct call is done through a snippet.
> AArch64: Call redoTrampolineReservationIfNecessary() event if label is not null

- cmake/modules/platform/toolcfg/gnu.cmake
- This PR needs to work with openj9 PR https://github.com/eclipse-openj9/openj9/pull/13386
- Generate and archive Code Coverage Files for xlinux, plinux, and zlinux
- Related Issues: https://github.com/eclipse-openj9/openj9/issues/12133
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
> Enable code coverage setting

- compiler/z/codegen/S390Instruction.cpp
- compiler/z/codegen/S390Instruction.hpp
`TR::S390VRRInstruction::generateBinaryEncoding()` has been updated to
generate binary encoding for VRR-g, VRR-h and VRR-i. We can now delegate
the encoding work to the parent class.
Fixes: #5948
> Consolidate binary encoding api for VRR-g,h,i

- compiler/aarch64/codegen/ARM64Instruction.cpp
When assigning registers for `cbz/cbnz` instructions, a real register specified
in the register dependencies can be unintentionally assigned to the source register.
This commit changes `assignRegister` functions to block registers in the register
dependencies before assigning the source register.
> AArch64: Block registers in regdeps when assigning register for branch instructions

- compiler/optimizer/Inliner.hpp
The constants MIN_PROFILED_CALL_FREQUENCY, TWO_CALL_PROFILED_FREQUENCY,
and MAX_FAN_IN are not used in OMR, thus can be removed and redefined
inside OpenJ9 compilation units that use it.
> Remove unused constants from the inliner

- compiler/p/codegen/OMRMemoryReference.cpp
The current code for patching unresolved addresses does not handles
P10's 8byte prefix instructions, this commit adds a check to mapOpCode
to not map memory instruction to prefix-instr in P10 if the reference
is to an unresolved symbol.
Mostly affects cases where the `expandForUnresolvedSnippet()` regenerates the load-instr immediately after the `bl` (i.e. non-indexed 32bit) and when generating a prefix-instr, it ends up with the patch code patching the prefix offset (resulting change in 0xXXXX0000 of the load address) instead of the suffix offset (0x0000XXXX).
~~[WIP] Finishing tests...~~
> Add an unresolved check for mapOpCode() P10 prefix-instr mapping

- compiler/z/codegen/BinaryEvaluator.cpp
This commit limits an optimization in the z codegen that tries to perform a shift + land operation using a single rotate instruction. The optimization skips the evaluation of the land node but evaluates its children. If the reference count of the land node > 1, then this can result in the code generator double decrementing the land node's children. This commit restricts this optimization to when the land node's ref count is equal to 1 so that the above described scenario is no longer possible.
> Restrict rotate instruction optimization for lshl+land nodes

- compiler/optimizer/InductionVariable.cpp
- compiler/optimizer/InductionVariable.hpp
In extreme cases the recursion in getEntryValue() can cause a SOF
when compiling large methods. This change will prevent the SOF by
introducing a depth parameter that will prevent the recursion from
exceeding a maximum depth and therefore preventing a SOF condition.
> Prevent a SOF in TR_InductionVariableAnalysis::getEntryValue()

- compiler/p/codegen/OMRInstOpCode.enum
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
This commit enables lxvh8x vector instruction for PPC.
> Enable lxvh8x instruction for PPC

- gc/base/GCExtensionsBase.hpp
- gc/base/j9mm.tdf
- gc/base/standard/ConfigurationGenerational.cpp
- gc/base/standard/ConfigurationStandard.cpp
- gc/stats/GlobalVLHGCStats.hpp
This commit contains the follow up items from https://github.com/eclipse/omr/pull/5825
This includes:
- making `Trc_MM_MemorySubSpaceTarok_calculateExpandSize_Exit1` and `Trc_MM_MemorySubSpaceTarok_calculateTargetContractSize_Entry` obsolete
- `dnssExpectedTimeRatioMaximum` and `dnssExpectedTimeRatioMinimum` were removed, since they are no longer used. The newer version (dnssExpectedRatioMaximum/Minimum) are more flexible for different GC policies
- `heapExpansionGCTimeThreshold` and `heapContractionGCTimeThreshold` were removed, since they are no longer used. The newer versions (`heapExpansionGCRatioThreshold` and `heapContractionGCRatioThreshold`) are more flexible for different GC policies
Signed-off-by: Cedric Hansen <cedric.hansen@ibm.com>
> Follow up to #5825

- port/osx/omrosdump.c
Core dump utility would previously ignore the directory portions of the path.
Fixes the `testOpenJ9DiagnosticsMXBean` test failures in https://github.com/eclipse-openj9/openj9/issues/13509
fyi: @keithc-ca @pshipton
> Allow core dump on OSX to change directories

- compiler/aarch64/codegen/FPTreeEvaluator.cpp
This commit removes a suffix "d" from a double constant in C++ code.
Suffix "f" is used for a float constant, but double constants do not
take any suffix.
> AArch64: Remove a suffix of a double constant

- include_core/omrport.h
The implementations are found in `omrosdump.c`, not `omrdump.c`.
> Correct references to omrosdump.c

- compiler/riscv/codegen/ControlFlowEvaluator.cpp
- compiler/riscv/codegen/OMRTreeEvaluator.cpp
We cannot simply use lreturn evaluator since areturn *must* use
TR_ObjectReturn as return info even though on RV64 both as 64bits. 
Otherwise, the J9's bytecode interpreter would crash upon return from 
JITed code in really confusing way.
Took me a looong evening to single-step through interpreter to figure this out...
> RISC-V: implement areturn evaluator

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit implements ilbit/llbit evaluators.
> AArch64: Implement ilbit/llbit evaluators

- cmake/modules/platform/toolcfg/msvc.cmake
/safeseh is only a valid linker flag when building an exe or shared lib.
Specifying when building a static library results in a warning.
> CMake: fix /safeseh flag

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Kill placeholder registers used for register dependencies
at arraycopy helper call.
> AArch64: Stop using placeholder register for arraycopy

- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.hpp
Add a variant of `stopUsingDepRegs` method which takes an array of registers to keep alive.
> AArch64: Add a method to kill placeholder registers in registrer dependency

- port/unix/omrsysinfo.c
This change does not fix anything patricular but provides general
cleaning of the code:
- size should have type size_t not int32_t
- memory for local variable in c-stack should be zeroed
- remove unnecessary declaration of two variables with the same name
> Cleaning for OMRPORT_CPU_BOUND

- include_core/omrporterror.h
- port/unix/omrsignal.c
- port/unix/omrsysinfo.c
- port/win32/omrsignal.c
- port/win64amd/omrsignal.c
- port/ztpf/omrsignal.c
Returning -1 does not give any useful information about what failed.
See also https://github.com/eclipse-openj9/openj9/pull/13872
Issue https://github.com/ibmruntimes/Semeru-Runtimes/issues/5#issuecomment-962040999
Issue https://github.com/eclipse-openj9/openj9/issues/12526
> Port library startup should not return -1

- README.md
- compiler/control/OMROptions.cpp
- doc/compiler/runtime/CodeMetaData.md
To reflect the current address of that repo.
> Update github URLs for OpenJ9

- compiler/control/OMROptions.cpp
Enable GCR Patching on aarch64.
Depends on:
https://github.com/eclipse/omr/pull/6227
https://github.com/eclipse-openj9/openj9/pull/13867
> AArch64: Enable GCR Patching

- compiler/compile/OMRSymbolReferenceTable.cpp
- compiler/il/OMRSymbol.hpp
- compiler/il/OMRSymbol_inlines.hpp
- compiler/x/amd64/codegen/OMRMemoryReference.cpp
A new flag AddressWithinMethodBounds indicates that an address
stored in a static symbol is inside method bounds, and can be
accessed using RIP addressing during an out-of-process compilation.
> Add a new symbol flag to mark addresses within method bounds

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/codegen/OMRInstruction.hpp
- compiler/il/LabelSymbol.hpp
- compiler/il/OMRLabelSymbol.cpp
- compiler/il/OMRLabelSymbol.hpp
- compiler/p/codegen/PPCInstruction.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRInstruction.cpp
- compiler/x/codegen/OMRInstruction.hpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/z/codegen/S390Instruction.hpp
* Remove unused LabelSymbol nullCompilationId
* Fix LabelSymbol constructor to always require a CodeGenerator
* Add CodeGenerator parm to LabelSymbol::isPatchBarrier()
> Misc. LabelSymbol improvements

- compiler/control/OMROptions.cpp
Such calls should be updated to call `getTRPID(char*, size_t)` instead, but this allows builds to succeed in the meantime.
> Define getTRPID(char*) for any downstream project that calls it

- port/unix/omrsignal.c
Help to diagnose a rare port library startup issue on OSX.
Issue https://github.com/eclipse-openj9/openj9/issues/12526
> Call perror() when SIGSEM_INIT fails in port library startup

- compiler/compile/OMRCompilation.cpp
- compiler/control/CompileMethod.cpp
- compiler/control/OMROptions.cpp
- compiler/env/CompileTimeProfiler.hpp
- compiler/env/TRPersistentMemory.cpp
- compiler/env/VerboseLog.cpp
- compiler/env/VerboseLog.hpp
- compiler/infra/SimpleRegex.cpp
- compiler/ras/LimitFile.cpp
- compiler/ras/OptionsDebug.cpp
The verbose log can now be locked by declaring a local variable of type `TR_VerboseLog::CriticalSection`, and the lock will be automatically released at the end of the variable's scope. Locking this way is advantageous because it's not possible to forget to release the lock, and because the lock will always be released even if an exception is thrown.
In general, releasing a lock while unexpectedly unwinding for an exception could leave a program in a bad state. If the lock protects an invariant, it's possible to take the lock, temporarily violate the invariant, and then unwind before restoring it. However, in the case of the verbose log lock specifically, the only effect of unlocking on unwind will be to prematurely truncate the output being generated at the time. The output is just …
> Define TR_VerboseLog::CriticalSection as a vlog RAII lock guard

- compiler/control/OMROptions.cpp
I don't believe the former has any remaining downstream callers.
> Delete getTRPID(char*) in favour of getTRPID(char*, size_t)

- compiler/optimizer/VPConstraint.cpp
Discovered via a warning from g++-11 - possibly a copy-paste error?
> Fix potential NULL pointer use

- compiler/il/OMRBlock.cpp
- compiler/il/OMRBlock.hpp
- compiler/il/OMRNode.cpp
- compiler/optimizer/VPHandlers.cpp
A downstream project used overloading of `ArrayStoreCHK` to allow for checking of whether a null reference was being stored to an array whose component type is one that does not allow for null references.  That overloading is no longer used in the downstream project, and the new `nonNullableArrayNullStoreCheck` non-helper symbol can be used to achieve the same effect.  This change removes the now obsolete potential overloading of `ArrayStoreCHK`.
> Remove obsolete overloading of ArrayStoreCHK

- compiler/aarch64/codegen/ConstantDataSnippet.cpp
This commit add support for TR_ConstantPool relocation in
Constant Data Snippet on aarch64.
> AArch64: Support TR_ConstantPool relocation in Constant Data Snippet

- compiler/optimizer/Inliner.cpp
For inlined callee methods that we skip creating HCR guards for,
setting createdHCRGuard to false prevents creating an OSR
transition point to be taken in cases such as a failed
TR_ProfiledGuard.
Issue: eclipse-openj9/openj9#13162
> Prevent OSR transitions from failed guards

- compiler/x/codegen/OMRTreeEvaluator.cpp
Do not rematerialize register for class pointer or method pointer if
it's AOT compilation because it doesn't have node info in register
rematerialization to create relocation record for the class pointer
or the method pointer.
> Do not rematerialize register for class pointer or method pointer

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCode.enum
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
This contribution includes the following changes:
- The seven instruction sequence previously used for vmul for IntVectors has been replaced with a single vmuluwm instruction
- vmul for ShortVectors and ByteVectors have each been implemented with multi-instruction sequences, since there is no single PPC assembly insruction that can perform this operation for these vector types
- Binary encoder unit tests have been added for newly enabled instructions
> Implement vmul for IntVectors, ShortVectors, and ByteVectors of size 128

- example/glue/ConcurrentMarkingDelegate.hpp
- example/glue/MarkingDelegate.cpp
- example/glue/MarkingDelegate.hpp
- gc/base/EnvironmentBase.cpp
- gc/base/MarkingScheme.cpp
- gc/base/TLHAllocationInterface.cpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
- gc/base/standard/ConcurrentGCSATB.cpp
- gc/base/standard/ConcurrentGCSATB.hpp
- gc/base/standard/ConfigurationStandard.cpp
- gc/base/standard/ParallelGlobalGC.cpp
- gc/base/standard/RememberedSetSATB.hpp
- gc/base/standard/StandardWriteBarrier.hpp
Implementation of SATB routines to enable SATB for `optavgpause` _(Limited to Xint+OOL Allocations)_
- Added obj alloc premarking to TLH Allocation interface
- Introduced some ASSERTS in shared ConcurrentGC code to ensure we don't transition to certain concurrent sates and we don't call certain callbacks known to be unreachable by SATB
_Implemented the following methods for SATB collector:_
- `setupForConcurrent` - initial STW to mark roots and set  allocation colour
- `doConcurrentTrace` - trace routine, adapted from incremental approach simplified to remove CARDS and "promote"  Background threads activity
- `completeConcurrentTracing`- final STW to flush barrier packets and complete any remaining tracing before handing off to ParallelGlobalGC
- `setThreadsScanned` - to shade threads …
> Core Standard SATB Routines

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
- fvtest/compilertriltest/VectorTest.cpp
This commit adds support for Int32 and Int64 in AArch64 vnegEvaluator.
> AArch64: Add support for Int32 and Int64 in vnegEvaluator

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
Improve MemoryReference in aarch64 codegen.
- Enable capturing aladd node in `populateMemoryReference` function.
- Enable use of scale and extend code.
- Simplify `consolidateRegisters` and `addToOffset` function.
- Introduce `normalize` function to ensure invalid combination of
base register and index register and offset is not used.
Resolves https://github.com/eclipse/omr/issues/6087 and https://github.com/eclipse/omr/issues/4227
> AArch64: Improve MemoryReference class for array access

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/MemoryReference.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This is a part of a series of PRs to implement https://github.com/eclipse/omr/issues/5173.
Introduce static factory methods for MemoryReference objects into aarch64 codegen.
Replace all direct calls to MemoryReference constructors with corresponding factory methods.
The separate PR will make MemoryReference constructors private.
Depends on https://github.com/eclipse-openj9/openj9/pull/14195
> AArch64: Provide factory methods for MemoryReference objects

- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
- gc/base/standard/ConcurrentGCIncrementalUpdate.cpp
- gc/base/standard/ConcurrentGCIncrementalUpdate.hpp
- gc/base/standard/ConcurrentOverflow.cpp
- gc/base/standard/OverflowStandard.cpp
- gc/base/standard/ParallelGlobalGC.hpp
Standard Overflow handler  must notify the Concurrent Collector when an overflow occurs (e.g to increment overflow stats and set proper flags specific to concurrent collector). This is now required because SATB makes use of this overflow handler, previously this handler was exclusive to non-concurrent collection. This mirrors the Incremental CGC overflow handler (in ConcurrentOverflowHandler). 
- This is done by introducing empty implementation in base class ParallelGlobalGC (since Standard Overflow is used by both concurrent SATB and non-concurrent global)
Furthermore, logic from `clearConcurrentWorkStackOverflow` specific to Concurrent Incremental has been pulled out from base. This resulted in memory corruption discovered when testing with `-Xcheck:memory`
> Proper Overflow Handling For SATB

- compiler/aarch64/codegen/MemoryReference.hpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
This is a part of a series of PRs to implement https://github.com/eclipse/omr/issues/5173.
Make constructors of MemoryReference class private.
Depends on:
https://github.com/eclipse/omr/pull/6279
https://github.com/eclipse-openj9/openj9/pull/14195
https://github.com/eclipse-openj9/openj9/pull/14196
Resolves https://github.com/eclipse/omr/issues/5173.
> AArch64: Privatize constructors of MemoryReference class

- include_core/omrmemcategories.h
The change is to add a new memory category which is
used to allocate memory for the Foreign Linker API.
> Add a memory category for the Foreign Linker API

- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit adds a function getOutgoingArgumentMemRef() to OMRLinkage
for AArch64.
The existing function of the same name assumes the function arguments
are always stored at the 8-byte boundary.  The new one takes an offset
for flexibility.
> AArch64: Add getOutgoingArgumentMemRef() to OMRLinkage

- compiler/infra/Bit.hpp
Use `__builtin_popcount` for `populationCount` function.
The builtin function generates concise implementation using `cnt` instruction,
which makes the size of JIT shared library slightly smaller.
> AArch64: Use builtin functions for populationCount

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
Use mvn (Bitwise NOT) instruction for xor with -1.
> AArch64: Use mvn instruction for xor with -1

- cmake/modules/ddr/DDRSetStub.cmake.in
In a full build of OpenJ9 with DDR, the build.log is about 7000 lines. About 40% of those are messages of the form 'Generating ...annt...' or  'Generating ...stub...' for DDR constant processing, with little actual value. This removes those messages.
> Suppress DDR 'Generating' messages

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit adds support for macOS in ARM64SystemLinkage.
The layout of arguments in the stack is different between AArch64 Linux
and macOS.
> AArch64: Add support for macOS in SystemLinkage

- azure-pipelines.yml
This commit update the macOS version for Azure Pipelines from 10.14 to
10.15.
Fixes: #6296
> Update macOS version for Azure Pipelines

- compiler/control/OMROptions.cpp
This commit fixes the output for two compiler suboptions, scratchSpaceLimit
and scratchSpaceLowerBound.
> Fix output for scratchSpaceLimit and scratchSpaceLowerBound

- compiler/aarch64/runtime/arm64asmdefs.inc
This commit defines a macro LOAD_FUNC_PTR() in arm64asmdefs.inc.
Linux and macOS load function pointers from memory in different ways.
> AArch64: Define LOAD_FUNC_PTR() in arm64asmdefs.inc

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
The new configuration, called "AGGRESSIVE_THROUGHPUT" will enable some
options that are likely to improve throughput of applications. Some of
these options are specific to Java, while others are more generic.
The downstream OpenJ9 project will enable the new configuration with
`-Xtune:throughput`. Individual options under the new configuration
can still be overridden with -Xjit options.
> Create configuration that favors throughput over other metrics

- compiler/x/codegen/OMRCodeGenerator.cpp
The [logic](https://github.com/eclipse/omr/blob/master/compiler/x/codegen/OMRTreeEvaluator.cpp#L4092-L4093) is already implemented, this PR simply enables vadd and vsub for auto-simd.
> Enable vadd and vsub for Byte and Short vectors of size 128

- include_core/omrport.h
- port/common/omrport.c
- port/common/omrstr.c
- port/omrportpriv.h
The omrstr_current_time_zone function computes the offset of local time from UTC in seconds, and also retrieves the current time zone name. It factors out the logic that exists in openj9:
https://github.com/eclipse-openj9/openj9/blob/master/runtime/rasdump/javadump.cpp#L657-L695
so it can be used there and elsewhere.
This relates to eclipse-openj9/openj9#13563. @mpirvu.
> Add a function to compute the current time zone

- include_core/omrmemcategories.h
The change is to add a new macro for categories with 10 children.
> Add OMRMEM_CATEGORY_10_CHILDREN in omrmemcategories.h

- compiler/codegen/OMRRegisterDependency.hpp
- compiler/x/codegen/OMRRegisterDependency.hpp
- compiler/z/codegen/OMRRegisterDependency.hpp
Use a flexible array for `RegisterDependencyGroup._dependencies`, and promote architecture-specific fields so they don't follow that flexible array.
Fixes: eclipse-openj9/openj9#14219.
> Fix problems compiling with gcc 10

- gc/base/MemoryPoolAddressOrderedList.cpp
For Balanced GC, during allocation for collector, free entry might need
to be card aligned, the alignment might cause free entry to be removed
or starting address changed, in these cases if the free entry also is in
the Hint list, we need to remove/update hint to avoid the stale hint
causing the issues, in general case, the memory hole has been set for
removing part of free entry, it would not cause direct crash, but if
there is 8 bytes shift for the starting address due to the alignment,
the size of memory hole would be overwritten by aligned free entry, then
it could cause an assert or crash.
> Update allocateHint during incremental card alignment

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/runtime/VirtualGuardRuntime.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/runtime/OMRCodeCache.cpp
- compiler/runtime/OMRCodeCacheManager.cpp
- port/osx/omrvmem.c
This commit adds calls to pthread_jit_write_protect_np() for AArch64 macOS
in some places.
AArch64 macOS requires JIT compiler to change the memory access permissions
using the API.
- readable and executable (R-X)
- readable and writable (RW-)
> AArch64 macOS: Call pthread_jit_write_protect_np()

- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
Use 16 byte slot when spilling/restoring a vector register.
> AArch64: Fix register assigner for vector register case

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRMachine.hpp
- compiler/aarch64/codegen/OMRRealRegister.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/RealRegisterEnum.hpp
Introduce `spillAllVectorRegs` helper function to OMRMachine class.
Introduce `KillVectorRegs` pseudo real register.
Update the register dependency class to kill all vector registers by  calling `spillAllVectorRegs` helper function
when `KillVectorRegs` is in the dependencies.
> AArch64: Introduce a pseudo real register for killing vector registers

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
- compiler/runtime/OMRCodeCacheConfig.hpp
One way to help relieve the pressure on a code cache with high occupancy
is to increase the initial invocation counts of newly-introduced
methods. New options introduced to support this are:
- OMR::Options::_highCodeCacheOccupancyPercentage, which defines the
threshold at which a code cache is considered to have high occupancy
- OMR::Options::_highOccupancyInitialCount and
OMR::Options::_highOccupancyInitialBCount, which store the initial
invocation counts to be used at high occupancy
Related: https://github.com/eclipse-openj9/openj9/pull/14344
Signed-off-by: Christian Despres <despresc@ibm.com>
Attn @mpirvu. ~None of the options can be changed from their defaults. I still need to look for what I need to change to fix that.~
> Add high code cache occupancy options

- compiler/aarch64/codegen/OMRMachine.cpp
Use `LastAssignableFPR` for terminating condition of loops iterating
real registers rather than using a magic number like `NumRegister - 2`.
> AArch64: Use LastAssignableFPR for loop terminating condition

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit enables live register support for vector registers.
> AArch64: Enable live register support for vector registers

- gc/base/MemoryPool.hpp
- gc/base/MemoryPoolAddressOrderedList.cpp
- gc/base/MemoryPoolAddressOrderedList.hpp
- update incrementDarkMatterBytes(), the methods have atomic
change option to protect thread race condition.
- update method recycleHeapChunk() in MM_MemoryPoolAddressOrderedList
to handle insert and coalesce heap chunk back free list.
> Update method for inserting and coalescing heap chunk back free list

- gc/base/j9mm.tdf
- gc/stats/CompactVLHGCStats.hpp
Introduced a count of regions that were used as destination (hence not
freed up) during sliding compaction, as used in VLHGC.
Also a new trace point was introduced that will report it (along exising
survivor counts used in Copy-Forward)
> VLHGC survivor region count

- compiler/aarch64/codegen/ARM64SystemLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
Preserve vector registers across function calls using system linkage.
Resolves https://github.com/eclipse/omr/issues/6318
> AArch64: Preserve vector registers across calls on system linkage

- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/z/codegen/ConstantDataSnippet.cpp
On x86, the JNI Target relocation puts the incorrect address when
generating a Runtime Assumption. However, the address that the
relocation infra itself needs to patch is correct. Thus, the relo record
has to hold not just the location to patch but also the location to
register the assumption against. This is the same on most platforms, but
different on x86.
https://github.com/eclipse-openj9/openj9/pull/14421 depends on this change; OpenJ9 will be broken without a coordinated merge.
> Update JNI Target relocation record to have offset to the reloLocation.

- buildenv/jenkins/omrbuild.groovy
- cmake/modules/OmrCrossCompile.cmake
- cmake/modules/OmrDDRSupport.cmake
- cmake/modules/OmrPlatform.cmake
- Introduce OMR_CROSSCOMPILING which mirrors CMAKE_CROSSCOMPILING but
ignores the case of building for windows from cygwin
- Automatically attempt to find a version of qemu to launch executables
if required.
> CMake: update cross compilation support

- port/common/omrosbacktrace.c
- port/linux/omrosbacktrace_impl.c
Using `dl_iterate_phdr(3)` we can find the loaded program element containing a given address. When the absolute file name is available, we can then open the `ELF` shared library or executable to find the symbol table section and related string table section to derive a name and offset for that address.
Fixes: eclipse-openj9/openj9#7995.
> Improve native stack traces on Linux

- cmake/modules/OmrCrossCompile.cmake
Old method of detecting cygwin->win32 builds was not reliable. As a stop
gap measure, assume that any build targeting windows is not a cross
compile build.
> CMake: Temporary fix for OMR_CROSSCOMPILING on Windows

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
This option will be used in a downstream project (OpenJ9)
to replace the effect -Xaggressive had on switching hot
compilations to profiling
> Add -Xjit:aggressiveSwitchingToProfiling option

- azure-pipelines.yml
This removes the dependence on Windows 2016 which is scheduled to be removed in a month: see https://github.com/eclipse/omr/issues/6140#issuecomment-1039411405.
> Update job to use Windows 2019

- compiler/ras/OptionsDebug.cpp
This commit fixes the verbose output for options set by
setJitConfigNumericValue() in the openj9 project.
> Fix verbose output for setJitConfigNumericValue

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/OMRValuePropagation.hpp
- compiler/optimizer/VPHandlers.cpp
Move some analysis of `ArrayStoreCHK` and `arraylength` operations out of VPHandlers.cpp so they can be shared with other parts of Value Propagation, particularly in downstream projects.
Some [OpenJ9-specific code in `constrainArrayLength` in VPHandlers.cpp](https://github.com/hzongaro/omr/blob/d95d9718595d098b4a12537f7585fa9465072e83/compiler/optimizer/VPHandlers.cpp#L4870-L4891) will be removed in a follow up pull request after it is transferred to that downstream project.
This is the first planned pull request mentioned in [OpenJ9 issue #14402](https://github.com/eclipse-openj9/openj9/issues/14402#issuecomment-1027104497)
> Relocate Value Propagation analysis of ArrayStoreCHK and arraylength

- compiler/riscv/runtime/CodeSync.hpp
- compiler/riscv/runtime/VirtualGuardRuntime.cpp
This commit introduces new header `CodeSync.hpp` with prototype of
`riscvCodeSync`. This avoids to copy and paste `extern riscvCodeSync...`
on various places.
Also, change parameter types to `void*` and `size_t` to avoid the need
for explicit type casts when calling.
> RISC-V: provide prototype for `riscvCodeSync`

- compiler/riscv/codegen/OMRLinkage.cpp
- compiler/riscv/codegen/OMRLinkage.hpp
Remove `OMR::RV::Linkage::hasToBeOnStack` so that the common
implementation `OMR::Linkage::hasToBeOnStack` is used.
> RISC-V: remove `hasToBeOnStack` from `OMRLinkage`

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Introduced in 2003 and no longer used or maintained.
> Remove unused disableMoreOpts option

- compiler/env/SystemSegmentProvider.cpp
-SystemSegmentProvider destructor should
deallocate its memory segments to prevent
a memory leak in projects that don't use
an alternative segment provider
Issue: #6361
> Deallocate memory segments between compilations

- compiler/control/OMROptions.cpp
> Enable zNext exploitation by default

- compiler/ras/Tree.cpp
Use a simple binary search to count the digits.  This solution is at least 4x
faster (verified with a microbench) than using a logarithm.
The replacement algorithm has also been verified to return the same result as
the original implementation across the entire uint32_t range.
> Improve performance of TR_Debug::getIntLength()

- compiler/aarch64/codegen/OMRLinkage.cpp
- compiler/aarch64/codegen/OMRLinkage.hpp
This commit implements locals compaction on aarch64.
`mapCompactedStack` function is added to OMRLinkage class.
> AArch64: Implement Locals Compaction

- compiler/codegen/CCData_inlines.hpp
- include_core/omrcomp.h
If __cplusplus isn't defined when omrcomp.h is included, it can cause a compiler warning to be emitted:
include_core/omrcomp.h:612:6: error: "__cplusplus" is not defined, evaluates to 0 [-Werror=undef]
612 | #if (__cplusplus >= 201103L)
> Check __cplusplus is defined before checking its value

- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
The bool parameter is not used in these APIs on x86:
* generateJumpInstruction()
* generateConditionalJumpInstruction()
> Remove unused needsVMThreadRegister parameter

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
This commit enables locals compaction on aarch64.
Depends on https://github.com/eclipse-openj9/openj9/pull/14624
> AArch64: Enable Locals Compaction

- compiler/compile/CompilationTypes.hpp
- compiler/cs2/arrayof.h
- compiler/cs2/hashtab.h
- compiler/env/OMRPersistentInfo.hpp
- compiler/env/TRMemory.hpp
- compiler/infra/BitVector.hpp
-Wunused-variable
unused variable
-Wreorder-ctor
field 1 will be initialized after field 2
-Wwritable-strings
ISO C++11 does not allow conversion from string literal to 'char *'
> Correct compilation errors detected by clang on Mac

- fvtest/porttest/omrvmemTest.cpp
Recent compilers, such as clang 13, that include -Wunused-but-set-variable in -Wall emit warnings about the use of totalRegionsSize in fvtest/porttest/omrvmemTest.cpp:
```
/var/build/tools/clang/13.0.0/bin/clang++  -I. -I../../port/common -I../util -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../fvtest/omrGtestGlue -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c -MMD -MP -fno-strict-aliasing -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O0 -fexceptions  -o omrvmemTest.o omrvmemTest.cpp
omrvmemTest.cpp:712:12: error: variable 'totalRegionsSize' set but not used [-Werror,-Wunused-but-set-variable]
uintptr_t totalRegionsSize = 0;
^ …
```
> Remove unused totalRegionsSize from omrvmemTest.cpp

- third_party/gtest-1.8.0/src/gtest-death-test.cc
Using recent compilers, such as gcc 11, where -Wmaybe-uninitialized is part of -Wall, a warning is emitted for gtest-death-test.cc (part of the google test suite):
```
g++  -I. -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../third_party/gtest-1.8.0/src -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c -MMD -MP -fno-strict-aliasing -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O0 -fexceptions  -o omrGtest.o omrGtest.cpp
In file included from ../../third_party/gtest-1.8.0/src/gtest-all.cc:43,
from omrGtest.cpp:39:
../../third_party/gtest-1.8.0/src/gtest-death-test.cc: In function 'bool testing::internal::StackGrowsDown()': …
```
> Initialize dummy in gtest-death-test to prevent compiler warnings

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds support for vector sqrt instructions
> AArch64: Add vector sqrt instructions

- compiler/codegen/OMRCodeGenerator.hpp
- compiler/optimizer/GlobalRegisterAllocator.cpp
- compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/FPCompareAnalyser.cpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/IA32LinkageUtils.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/x/codegen/OMRLinkage.cpp
- compiler/x/codegen/OMRTreeEvaluator.hpp
- compiler/x/i386/codegen/IA32SystemLinkage.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
* Remove x87 coerceFPOperandsToXMMRs()  
* Re-implement x87->xmm coercion specialized for ST0 
* Coerce IA32 floating point return register to xmm0 for system linkage 
* Remove remaining remnants of useSSEFor[Single|Double]Precision
> Prep work to remove x87 register assigner

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/FPTreeEvaluator.cpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
- compiler/ras/Debug.hpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds support for vector `movi`, `movn`, and `fmov` instructions
`ARM64Trg1ImmShiftedInstruction` class is added to support shifted immediate
variant instructions.
> AArch64: Add vector MOVI, MOVN, and FMOV instructions

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds support for vector `abs` and `fabs` instructions
> AArch64: Add vector ABS and FABS instructions

- compiler/p/codegen/PPCSystemLinkage.cpp
- preserving all vector registers is not necessary and causes overflow
in RegisterDependencyConditions
> Preserve only volatile vector registers in PPCSystemLinkage

- compiler/x/codegen/UnaryEvaluator.cpp
> Remove unnecessary register dependencies from vneg evaluator

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector `bic` instruction and
binary encoding unit tests for vector logic binary instructions.
> AArch64: Add vector BIC instruction

- port/linux/omrosdump_helpers.c
If DUMP_DBG is defined on Linux, then five warnings are emitted:
```
./linux/omrosdump_helpers.c:783:6: error: variable 'bytesread' set but not used [-Werror,-Wunused-but-set-variable]
int bytesread = 0;
^
./linux/omrosdump_helpers.c:782:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
int offset = 0;
^
./linux/omrosdump_helpers.c: In function 'printMemoryMap':
./linux/omrosdump_helpers.c:823:14: error: variable 'device' set but not used [-Werror=unused-but-set-variable]
823 |         char device[6];
./linux/omrosdump_helpers.c:827:6: error: variable 'inode' set but not used [-Werror,-Wunused-but-set-variable]
int inode;
^
./linux/omrosdump_helpers.c:825:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
int offset;
```
The use …
> Fix Linux compiler warnings when DUMP_DBG is defined

- fvtest/threadtest/createTest.cpp
- thread/unix/omrthreadattr.c
In newer compilers that include -Wsign-compare as part of -Wall (for example gcc 11) a compiler warning is emitted from fvtest/threadtest/createTest.cpp:
```
g++  -I. -I../../fvtest/util -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../fvtest/omrGtestGlue -I../../thread -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c -MMD -MP -fno-strict-aliasing -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O0 -fexceptions  -o createTest.o createTest.cpp
createTest.cpp: In function 'size_t getOsStacksize(size_t)':
createTest.cpp:497:42: error: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' …
```
> Prevent sign-compare warning from createTest.cpp

- doc/compiler/regular_expression/Regular_Expression.md
Added an escape character before a vertical bar character in a regular expression to prevent the vertical bar from being interpreted as a table column separator.
[skip ci]
> Escape vertical bar character in regular expression

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OMRMachine.cpp
- compiler/aarch64/codegen/OMRRegisterDependency.cpp
- compiler/aarch64/codegen/OpBinary.cpp
This commit removes the vorr2d instruction from AArch64 instruction
table.  It is redundant because vorr16b does the same.
> AArch64: Remove redundant vorr2d instruction

- compiler/codegen/OMRRegisterDependency.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMRNode.hpp
- compiler/ras/Debug.cpp
- compiler/x/codegen/CompareAnalyser.cpp
- compiler/x/codegen/ControlFlowEvaluator.cpp
- compiler/x/codegen/FPTreeEvaluator.cpp
- compiler/x/codegen/OMRMachine.cpp
- compiler/x/codegen/OMRMachine.hpp
- compiler/x/codegen/OMRRegister.cpp
- compiler/x/codegen/OMRRegister.hpp
- compiler/x/codegen/OMRRegisterDependency.cpp
- compiler/x/codegen/OMRRegisterDependency.hpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/x/codegen/RegisterDependency.hpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
* Remove deprecated needToClearFPStack and related functions
* Remove deprecated _mayNeedToPopFPRegisters
* Remove NeedsPrecisionAdjustment Node flag
* Remove mayNeedPrecisionAdjustment register flag
* Remove popRegisters List from RegisterDependency API
> Remove deprecated x87 features

- compiler/control/OMROptions.cpp
This commit corrects the warning message for TR_DisableCCR, removing
redundant "due to".
> Correct warning message for TR_DisableCCR

- compiler/x/amd64/codegen/RealRegisterEnum.hpp
- compiler/x/codegen/OMRInstruction.cpp
- compiler/x/codegen/OMRRegisterDependency.cpp
- compiler/x/codegen/OMRRegisterDependency.hpp
- compiler/x/codegen/OMRRegisterDependencyStruct.hpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/OMRX86Instruction.hpp
- compiler/x/codegen/X86BinaryEncoding.cpp
- compiler/x/codegen/X86Debug.cpp
- compiler/x/i386/codegen/RealRegisterEnum.hpp
Reverts eclipse/omr#6378
Causing 32-bit downstream project failures on Linux.
> Revert "Remove misc. dead x87 code"

- compiler/codegen/NodeEvaluation.cpp
Using INT_MAX as the initial best evaluation priority results in each node receiving a priority of 0 in whichChildToEvaluate, because no childPriority will ever be greater than the INT_MAX value. Using INT_MIN instead ensures that bestPriority corresponds to the deepest child depth in the tree, and updates bestChild and nodePriority accordingly.
> Choose which child to evaluate correctly

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/OMRValuePropagation.hpp
- compiler/optimizer/ValuePropagationCommon.cpp
It is possible in DLT compiles for a store to a parm slot to be missed
by GVP analysis because it appears in a part of the method that occurred
prior to the DLT entry point and hence IL trees were never generated
for it.  It may then be possible for GVP to conclude that the only def
to the parm slot is at method entry and then assume that the characteristics
of the parm slot at entry (such as its type) are how uses of the parm
slot should be constrained.  This is incorrect in DLT compiles and the
analysis needs to be made more conservative and assume parms are variant.
> Consider parm invariance when merging def nodes for GVP

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit vector shift immediate instructions
> AArch64: Add vector shift immediate instructions

- compiler/optimizer/LocalLiveRangeReducer.cpp
If there are store nodes before arraycmp, arraycmp can share
base addresses with them. UseonlyAliases needs to be set up to
prevent the store nodes from being moved beyond arraycmp.
> Add UseOnlyAlias for arraycmp when populating potential deps

- compiler/compile/ResolvedMethod.cpp
- compiler/compile/ResolvedMethod.hpp
This change is needed to facilitate the callers of this method
with the ability to check whether objects found at the specified
CP entry are valid, which can affect how the call for the
ResolvedMethod returned by this method is set up.
Needed for: eclipse-openj9/openj9#14769
> Update ResolvedMethod API for getResolvedDynamic/HandleMethod

- include_core/AtomicSupport.hpp
__compare_and_swaplp is valid only in 64-bit mode according to the AIX documentation whereas compare_and_swaplp is supported by both compilation modes. The functions should behave functionally the same.
resolves #6357
Signed-off-by: David McCann mccannd@uk.ibm.com
> Use documented AIX atomic kernel services

- compiler/ras/Debug.cpp
- compiler/ras/Debug.hpp
- compiler/ras/Tree.cpp
* Introduce appends() function to TR_PrettyPrinterString class 
* Use TR_PrettyPrinterString::appends() where appropriate 
* Rename TR_PrettyPrinterString::append() to appendf() 
* Remove log printing for obsolete symRefWCodeId 
* Remove excessive TR_PrettyPrinterString usage for globalIndexPrefix 
* Reduce calls to TR_PrettyPrinterString.appends() 
* Improve pathlength in TR_Debug::newNode() 
* Improve pathlength in TR_Debug::newLabelSymbol() 
* Improve pathlength in TR_Debug::newRegister() 
* Improve pathlength in TR_Debug::newVariableSizeSymbol() 
* Common break or debug on create functionality in TR_Debug
> Misc. improvements to JIT logging pathlength

- include_core/AtomicSupport.hpp
Pull request #6400 changed the atomic support using xlC to use compare_and_swaplp for 32-bit compilation, to allow compilation on AIX. Unfortunately this API isn't available for xlC on Linux.
The documentation for Linux doesn't state that __compare_and_swaplp is unavailable for 32-bit compilation, so revert to only using compare_and_swaplp on AIX.
Signed-off-by: David McCann mccannd@uk.ibm.com
> Revert back to compare_and_swaplp() for 32-bit compilation for xlC on Linux

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/compile/OSRData.cpp
- compiler/z/codegen/OMRMachine.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
The preprocessor macro does not even exist any longer.
> Remove long disabled TR_ASSERTC macros

- compiler/aarch64/codegen/ConstantDataSnippet.cpp
- compiler/codegen/Relocation.cpp
- compiler/z/codegen/ConstantDataSnippet.cpp
- compiler/z/codegen/S390GenerateInstructions.cpp
- compiler/z/codegen/S390HelperCallSnippet.cpp
- compiler/z/codegen/S390Instruction.cpp
- compiler/z/objectfmt/OMRJitCodeRWXObjectFormat.cpp
The diagnostic information has been disabled in the code base for over 15 years,
and in fact the diagnostic macros are simply stubs.
Remove it to improve code readability.
> Remove long disabled AOT code generator diagnostics

- compiler/codegen/CodeGenGC.cpp
- compiler/codegen/OMRCodeGenPhase.cpp
- compiler/codegen/OMRCodeGenerator.cpp
- compiler/il/OMRBlock.cpp
- compiler/x/codegen/OMRLinkage.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
Allocate `TR::StackMemoryRegion` consistently before each phase.
Remove redundant `TR::StackMemoryRegions` within CodeGenerator phases.
Issue: #6382
> Create TR::StackMemoryRegion for each CodeGenerator phase

- buildenv/jenkins/omrbuild.groovy
- cmake/modules/platform/toolcfg/xlc.cmake
- configure
- configure.ac
- omrmakefiles/rules.zos.mk
* with the z/OS guests being replaced with V2R4 systems the lowest level xlc compiles to that is supported is now V2R3.
> Update z/OS compile to use V2R3

- cmake/modules/ddr/GenerateStub.cmake
on AIX warnings appear like this:
>  "j9pool/pool.stub.c", line 1: 1506-229 (W) File is empty.
on z/OS warnings appear like this:
>  WARNING CCN3229 j9pool/pool.stub.c:1     File is empty.
> DDR: Avoid numerous warnings due to empty 'stub' files

- compiler/p/codegen/FPTreeEvaluator.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCode.enum
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/PPCBinaryEncoding.cpp
- compiler/p/codegen/PPCOpsDefines.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
This contribution includes the following changes: 
- vsplats has been enabled for all vector types
- `xxspltib` instruction has been enabled and a binary encoding routine for its instruction format has been added
- On P9 and up, `xxspltib` is used to broadcast 8-bit immediate values into ByteVectors
- Binary encoder unit test has been added for `xxspltib`
> Use xxspltib when broadcasting immediate value into ByteVector

- compiler/control/OMROptions.cpp
- compiler/optimizer/LocalOpts.cpp
- compiler/optimizer/LocalOpts.hpp
Checkcast and profiled guard coalescer is an optimization pass that looks for `checkcast` followed by a profiled guard, and moves the `checkcast` to the cold side of the guard. Null checks against the same object are permitted between the `checkcast` and the guard (or fused with the `checkcast`), since it's safe to move `checkcast` across them. Similarly, conditional branches are allowed if they simply jump away when the cast object is null.
This commit is a near rewrite of the pass because there were so many bugs in the prior implementation:
- Checkcast could be moved even if the type of receiver accepted by the guard could still fail the `checkcast`.
- Checkcast could be moved even if the cast type was unknown at compile time. I don't believe anything currently generates dynamic …
> Fix checkcast and profiled guard coalescer

- compiler/x/codegen/OMRCodeGenerator.hpp
Allow downstream projects to access/modify CodeGenerator member methods _vfpState and _vfpResetInstruction from project-level class extensions, similar to other CG members such as _returnTypeInfoInstruction and _linkageProperties.
> Make _vfpState and _vfpResetInstruction protected

- port/unix/omrsysinfo.c
Markdown syntax (`) has been removed since it makes it difficult to read
comments.
Surrounding comments have been updated to follow the coding standards:
- Long lines spread across multiple lines; and
- Comments are placed on separate lines.
> Remove markdown syntax (`) from C source file

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
Enable vector bitwise logical operations for vectors whose element
type is an integer.
> AArch64: Enable vector bitwise logical operations for all integer types

- compiler/il/OMRBlock.cpp
- compiler/infra/OMRCfg.cpp
- compiler/infra/OMRCfg.hpp
- compiler/optimizer/GeneralLoopUnroller.cpp
- compiler/optimizer/LoopCanonicalizer.cpp
- compiler/optimizer/LoopVersioner.cpp
- compiler/optimizer/StructuralAnalysis.cpp
- compiler/optimizer/StructuralAnalysis.hpp
- compiler/optimizer/Structure.cpp
- compiler/optimizer/Structure.hpp
- compiler/optimizer/VirtualGuardCoalescer.cpp
The term 'region' is overloaded when building method structure for both a structural component and for the allocator to satisfy memory requests.
In these contexts, rename fields that refer to `TR::Region`s to make it clear that they are memory regions.
> Rename memory TR::Region fields in Structure to improve code clarity

- compiler/optimizer/LocalOpts.cpp
...to instances where the conditional on the passing side of the guard does not evaluate any indirect loads. If the conditional does evaluate an indirect load, the transformation must be abandoned just as though an indirect load were found in an earlier tree.
The failure mode against which this PR protects is theoretical and has not been observed. It's unclear whether it's even possible to cause an indirect load to appear in such a position. Nonetheless, it's prudent to check.
Also elaborate a bit on one of the comments in the pass.
> Restrict checkcast and profiled guard coalescer cold merge special case

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit changes some calls to BeforeBinaryEncodingExternalRelocation
constructor to suppress the following compiler warning:
`warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]`
> AArch64: Suppress warnings in BeforeBinaryEncodingExternalRelocation

- port/osx/omrintrospect.c
- port/osx/omrosbacktrace_impl.c
- Add backtrace and symbol resolution functions
- Output correct current thread
- Backtrace for all threads instead of only current
- Discard signal handler frames
- Add timeout functionality
Issue: #3506
Signed-off-by: Eric Yang eric.yang@ibm.com
> Enable native stack output in osx javacores

- compiler/env/OMRClassEnv.hpp
- compiler/il/OMRBlock.cpp
- compiler/il/OMRBlock.hpp
- compiler/il/OMRNode.cpp
- compiler/optimizer/VPHandlers.cpp
- compiler/optimizer/ValuePropagationTable.hpp
- Add a handler to type propagate fixed class constraint on `newvalue`
- Fix `constrainNew` where `setAllocationCanBeRemoved` should not be true if the class is an abstract class or an interface
> Add VPHandler constrainNewvalue

- compiler/z/codegen/OMRMemoryReference.cpp
The current z codegen behaviour is to place the register returned
by evaluate() in the memref's index register when handling a
shift left tree. In the case of a shift left for a decompression
sequence the result should be placed in the memref's base register
for better performance.
> Decompression sequence results should be placed in memref's base

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commits adds vector reverse elements instructions
> AArch64: Add vector reverse elements instrucitons

- omrtrace/omrtrace_internal.h
- omrtrace/omrtraceapi.cpp
- omrtrace/omrtracelog.cpp
* the feature was "not useful because the exception trace buffers can't be sent to any subscribers"
* improve macros to avoid dangling-else problems
* use parentheses around macro parameter uses
> Remove OMR_ENABLE_EXCEPTION_OUTPUT

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
Add vmulInt64Helper function to do vector multiplication for
vectors with 64-bit integer elements using a sequence of multiple instructions.
> AArch64: Implement vmul for vectors with 64-bit integer elements

- port/osx/omrintrospect.c
- port/osx/omrosbacktrace_impl.c
- Change `clock_gettime()` to `gettimeofday()` as the former is unavailable in earlier versions of OSX
- Disable backtrace functions for AArch64 OSX as they haven't been fully implemented yet
> Fix compile and test errors with OSX omrintrospect

- port/osx/omrosdump.c
This commit adjusts the offsets of segments in the core file when the
segment is unreadable.
> macOS: Adjust segment offset in the core file

- compiler/codegen/Relocation.hpp
No longer referenced or useful in OMR or downstream projects.
> Remove unused AOTcg macros

- compiler/compile/OMRCompilation.cpp
- compiler/compile/OMRCompilation.hpp
those variables are private so not accessible externally
> Remove non-referenced member variables in OMRCompilation

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
Use MOVI and MVNI instructions for broadcasting immediate value
into vector registers.
Fix ARM64Debug.cpp to correctly print 64-bit constant value for `vmovi2d` instruction.
> AArch64: Use MOVI for broadcasting immediate value into vector registers

- example/glue/ObjectModelDelegate.hpp
- gc/base/GlobalCollector.hpp
- gc/base/MarkingScheme.cpp
- gc/base/MarkingScheme.hpp
- gc/base/ObjectModelBase.hpp
- gc/base/ParallelHeapWalker.cpp
- gc/base/TLHAllocationInterface.cpp
- gc/base/TLHAllocationInterface.hpp
- gc/base/TLHAllocationSupport.cpp
- gc/base/TLHAllocationSupport.hpp
- gc/base/segregated/SegregatedMarkingScheme.hpp
- gc/base/standard/CompactScheme.cpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
- gc/base/standard/ConcurrentGCIncrementalUpdate.hpp
- gc/base/standard/ConcurrentGCSATB.cpp
- gc/base/standard/ConcurrentGCSATB.hpp
- gc/base/standard/ParallelSweepScheme.cpp
Objects allocated while CM (SATB) is active must be marked to preserve
the invariant required to guarantee correctness.
Instead of marking each obj individually, we can mark on the TLH level.
However, doing so is non-trivial: we must know the start of the last
object to mark the proper range of the TLH. That is, arbitrary bits at
the end of the TLH can't be marked, and this is problematic for sweep.
To get around this issue we seal the TLH with a bogus/dummy obj at the
end of the TLH. With this, we know the precise addr to mark up to.
However, we must guarantee that we have at least min obj size available
in the TLH.
These changes introduce a mechanism for the collector to reserve bytes
in a TLH. Whenever the TLH is refreshed, it queries the collector to
determine if it should reserve …
> SATB TLH Batch Mark

- port/osx/omrosdump.c
This commit adds code for setting "flavor" and "count" in the thread
commands in the core files on AArch64 macOS.
> Set flavor and count in AArch64 macOS core file

- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
Implements codegen for vectorized FMA of Double and Float Vectors 
Note: This PR should not be merged until the IL opcode for vector FMA is implemented
> Implement vectorized FMA of Double and Float Vectors

- cmake/modules/ddr/DDRSetStub.cmake.in
Using VS 2022, DDR fails to produce the proper content in some files, (e.g. `HeapMap.annt.hpp`) due to errors like:
```
yvals_core.h(23): fatal error C1189: #error:  STL1003: Unexpected compiler, expected C++ compiler.
```
Adding the `/TP` option tells the preprocessor that the source is C++ code, avoiding the error.
> Help Visual Studio understand that .hpp files contain C++ code

- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/S390Evaluator.hpp
`genLoadAddressConstant` only adds instructions from `aconst` and `aloadi` nodes to the `staticPICSites` lists. Profiled class address constants are not found in `aconst` or `aloadi` nodes, but need to be treated as `aconst` nodes. This commit adds the `genLoadProfiledClassAddressConstant` helper to wrap the class address constant value in a dummy `aconst` node before passing it to genLoadAddressConstant.
See the [OpenJ9 PR](https://github.com/eclipse-openj9/openj9/pull/14932) for where this is used
[Related OpenJ9 issue](https://github.com/eclipse-openj9/openj9/issues/14775)
> Add genLoadProfiledClassAddressConstant helper in Z codegen

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds SIMD copy instructions, helper functions for generating
those instructions and binary encoding unit tests.
> AArch64: Add SIMD copy instructions

- azure-pipelines.yml
- fvtest/porttest/CMakeLists.txt
1. Remove the `--gtest_filter=${porttest_filter}` option for porttest
When `${porttest_filter}` is an empty string, no tests from `porttest` are
run. `${porttest_filter}` is never set in OMR so it will always be an
empty string. Also, `--gtest_filter=${porttest_filter}` conflicts with
the `GTEST_FILTER` environment variable used by `omrbuild.groovy`. To avoid
the conflict and correctly run `porttest`, the `--gtest_filter=${porttest_filter}`
option is removed. `porttest` should consistently rely upon the `GTEST_FILTER`
environment variable.
Changed `--gtest_filter="Cuda*"` to `--gtest_filter=*Cuda*`. 0 tests are run.
This allows `cuda_porttest` to work correctly.
2. Disable `*_create_dump_*` tests for the "x86-64 Linux" job in Azure
These tests are disabled because core files cannot be …
> Remove the --gtest_filter=${porttest_filter} option for porttest

- compiler/x/amd64/objectfmt/OMRJitCodeRWXObjectFormat.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.hpp
- compiler/z/codegen/OMRCodeGenerator.hpp
* Correct usage of x86 directCallRequiresTrampoline() API
* Remove unused NEEDS_TRAMPOLINE macros
> Correct usage of x86 directCallRequiresTrampoline() API

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/il/Aliases.cpp
- compiler/il/OMRDataTypes.cpp
- compiler/il/OMRDataTypes.hpp
- compiler/il/OMRDataTypes_inlines.hpp
- compiler/il/OMRIL.cpp
- compiler/il/OMRILOps.hpp
- compiler/il/OMRNode.cpp
- compiler/il/OMROpcodes.enum
- compiler/il/VectorOperations.enum
- compiler/ilgen/OMRIlBuilder.cpp
- compiler/optimizer/OMRSimplifierHandlers.cpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- doc/compiler/tril/TrilLanguageReference.md
- fvtest/compilertriltest/VectorTest.cpp
- fvtest/tril/tril/GenericNodeConverter.cpp
- fvtest/tril/tril/ilgen.hpp
- transform opcodes for which source and result types are the same:
vload/vstore, vloadi/vstorei, vnot, vneg, vsub, vmul, vdiv, vand, vor, vxor, vsplats
> Transform old vector opcodes into new ones

- fvtest/porttest/si.cpp
PortSysinfoTest.sysinfo_test_sysinfo_set_limit_FILE_DESCRIPTORS fails
when running as root. Make sure setrlimit does not lower the hard limit
below the soft limit as this is not allowed, even as root.
> Fix PortSysinfoTest failure when running as root

- include_core/omrutil.h
- port/unix/omrcpu.c
- port/unix_include/omrportpg.h
- util/omrutil/j9memclr.cpp
We need to inform the compiler that our uses of `dcbz` clobber memory, otherwise the optimizer can reasonably assume, e.g. in `omrcpu_startup(),` that `buf[0] == 255` at the beginning of the for loop.
> Fix computation of cache-line size on Power

- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.hpp
- compiler/arm/codegen/OMRTreeEvaluator.cpp
- compiler/arm/codegen/OMRTreeEvaluator.hpp
- compiler/il/OMRILOps.hpp
- compiler/il/VectorOperations.enum
- compiler/optimizer/OMRSimplifierTable.enum
- compiler/optimizer/ValuePropagationTable.hpp
- compiler/p/codegen/OMRCodeGenerator.cpp
- compiler/p/codegen/OMRInstOpCode.enum
- compiler/p/codegen/OMRInstOpCodeProperties.hpp
- compiler/p/codegen/OMRTreeEvaluator.cpp
- compiler/p/codegen/OMRTreeEvaluator.hpp
- compiler/riscv/codegen/OMRTreeEvaluator.cpp
- compiler/riscv/codegen/OMRTreeEvaluator.hpp
- compiler/x/amd64/codegen/OMRTreeEvaluator.cpp
- compiler/x/amd64/codegen/OMRTreeEvaluator.hpp
- compiler/x/i386/codegen/OMRTreeEvaluator.cpp
- compiler/x/i386/codegen/OMRTreeEvaluator.hpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
- compiler/z/codegen/OMRTreeEvaluator.hpp
- fvtest/compilerunittest/p/BinaryEncoder.cpp
This contribution includes the following changes:
- New IL opcodes vabs and vsqrt have been added
- Codegen sequences for vectorized absolute value for all vector types have been implemented on PPC
- Codegen sequences for vectorized square root for floating point types have been implemented on PPC
- Binary encoder unit tests have been added for newly enabled PPC instructions
> Implement vectorized absolute value and square root for all applicable vector types on PPC

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
This commit implements vsqrtEvaluator on aarch64.
> AArch64: Implement vsqrtEvaluator

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- compiler/aarch64/codegen/UnaryEvaluator.cpp
Implement vabsEvaluator on aarch64.
> AArch64: Implement vectorized absolute value evaluator

- port/unix/omrsysinfo.c
Update cgroup iterator functions to retrieve metrics from cgroup v2
files.
Issue: #1281
> Update omrsysinfo_cgroup_subsystem_iterator functions for cgroup v2

- compiler/il/OMRDataTypes.hpp
- compiler/x/codegen/OMRCodeGenerator.cpp
- compiler/x/codegen/SIMDTreeEvaluator.cpp
- fvtest/compilertriltest/VectorTest.cpp
Reverts eclipse/omr#6509
See https://github.com/eclipse/omr/pull/6509#issuecomment-1129396524
> Revert "Implement 256 and 512-bit vload/vstore on x86"

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRCodeGenerator.cpp
This commit enables vectorization of following operations in Vector API
for different species.
1. Vector Load and Store for all species.
2. Binary Operations
1. Add/Subtraction : Enabled for all species
2. Multiplication : Enabled for all species except Long
3. Division : Enabled for Float and Doubles only
4. AND/OR/XOR : Enables for all integral types
3. NEG operation for all species
4. Broadcast operation for all species
> Enable Vectorization for supported ops on Z

- gc/base/MemoryPoolAddressOrderedList.cpp
- gc/base/MemoryPoolAddressOrderedList.hpp
- gc/base/omrmmprivate.hdf
- gc/base/standard/ConcurrentGCSATB.cpp
- gc/base/standard/ConcurrentGCSATB.hpp
Normally, a TLH can span multiple sweep chunks without any issues. However, a batch marked TLH (for SATB) is required to be contained within a single sweep chunk. Otherwise, this is problematic for sweep as sweep must determine the last obj in a chunk. With a batch marked TLH spanning multiple chunks, the TLH in the fist chunk will only be partially contained. As a result, all mark bits will be set to the end of the chunk resulting in the last live obj in chunk being undiscoverable. Hence, we must align the TLHs to sweep chunk boundaries when a pool freeEntry spans multiple chunks during TLH allocation.
To do so, we first determine the chunk boundaries containing the freeEntry baseAddr. If freeEntry topAddr is past the chunk top boundary
(the freeEntry spans multiple chunks) then we clip …
> TLH Alignment for Spanning Sweep Chunks

- compiler/optimizer/RegisterCandidate.cpp
Previous [refactoring](https://github.com/eclipse/omr/commit/6d0fbffa932c3eb1d041bc737177c3fe9ea90469) inadvertently reversed a != and changed the block being checked.
> Fix logic for checking for referenced in nearest loop

- compiler/compile/OMRNonHelperSymbols.enum
- compiler/compile/OMRSymbolReferenceTable.hpp
- compiler/ras/Debug.cpp
`defaultValueSymbol` symbol represents the `defaultValue` field in J9Class.flattenedClassCache.
> Add defaultValueSymbol for value type class

- port/aix/omrosdump_helpers.c
- port/unix/omrosdump.c
On AIX, if the corepath provided to appendCoreName() is blank, then opendir() will fail. However the core may have been written to the current working directory and it will be missed. If corepath is blank, provide "." to opendir().
Also add some extra messages that will come out when DUMP_DEBUG is defined, and fix a typo.
Signed-off-by: David McCann mccannd@uk.ibm.com
> Get opendir to use the cwd if the corepath is blank

- compiler/p/codegen/PPCSystemLinkage.cpp
This fixes an issue with the code generated for containers with
-XX:+PortableSharedCache option. AOT code generated on P8 uses
pTOC and if the same container is used on P10 environment causes
a crash as pTOC is not there on P10. The fix will generate
materialize sequence of instructions when -XX:+PortableSharedCache
option is enabled and not pTOC.
Signed-off-by: Bhavani SN <bhavani.sn@ibm.com>
> Fix usage of pTOC with portableSCC code run in P10 container

- compiler/il/OMRDataTypes.cpp
- compiler/il/OMRDataTypes.hpp
- compiler/il/OMRDataTypes_inlines.hpp
- compiler/il/OMRILOps.cpp
- C++ does not guarantee any order of static initialization of variables
defined in different compilation units
- Make OMR::DataType::Vector128Int32 and similar variables compile time constants
> Fix static init of vector types

- compiler/p/codegen/ControlFlowEvaluator.cpp
Issue was while calling addConstantToInteger a 64 bit value was used
and passed as 32bit in the function call. Code generated to load the 
constant was losing higher bits and thus caused issues.
Fixes #6511
Signed-off-by: Bhavani S N <bhavani.sn@ibm.com>
> Check for bit length of constant before addConstantToInteger

- compiler/optimizer/InductionVariable.cpp
- compiler/optimizer/LoopVersioner.cpp
- compiler/x/env/OMRCPU.cpp
- compiler/x/runtime/X86Runtime.hpp
Calls to feGetEnv are usually cached in static variables. This
PR catches a few instances that were not.
Personal build 29921 passed
> Ensure calls to feGetEnv are cached

- compiler/optimizer/LoopVersioner.cpp
The region structure is expected to be a loop. If it isn't, then versioner may misbehave, e.g. it may crash. And besides, there's no point in trying to version an acyclic region anyway.
HCR guard versioning removes edges from the CFG immediately (unlike versioning of regular conditionals/virtual guards, which leaves a trivially foldable conditional tree in place). The removal of particular edges can change loops into acyclic regions, so skip any region that is no longer a loop.
(OSR guard versioning also removes edges immediately, but the targets of those edges are not within any loop, so their removal can't change loops into acyclic regions.)
Fixes eclipse-openj9/openj9#15061
> Make versioner skip loops that have become acyclic during the pass

- gc/base/standard/ConcurrentGC.hpp
Introduce a temp public wrapper
acquireExclusiveVMAccessAndSignalThreadsToActivateWriteBarrier around
existing protected signalThreadsToActivateWriteBarrier, to help with
downstream project (J9) being able to access the method.
The wrapper will be become a full new method in step2 change after the
downstream project changes are complete.
> Indirect SignalThreadsForWB step1

- example/glue/ConcurrentMarkingDelegate.hpp
- gc/base/standard/ConcurrentGC.cpp
- gc/base/standard/ConcurrentGC.hpp
When starting Concurrent Global Mark we call
MM_ConcurrentGC::signalThreadsForWriteBarrier, that will acquire
exlusive VM access and then iterate over threads to set their enable-WB
flag.
A language specific pre/post processing may be need to performed
before/after exclusive acquire/release, so we will now introduce a level
of indirection so that language specific API is called instead, which
will perform extra processing and meanwhile call back the original OMR's
MM_ConcurrentGC::signalThreadsForWriteBarrier
There is also a rename of some of methods signalThreadsForWriteBarrier
-> acquireExclusiveVMAccessAndSignalThreadsToActivateWriteBarrier to
distinguish them from those that only do the iteration/signalling without
dealing with exclusive VM access.
Signed-off-by: Aleksandar Micic …
> Indirect SignalThreadsForWB step2

- compiler/aarch64/codegen/BinaryEvaluator.cpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Implement evaluators for vmin and vmax opcodes.
The helper functions for 64bit integer elements
are added because smin and smax instructions do not support
64bit integer elements.
> AArch64: Implement vmin/vmax evaluators

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit adds a call to pthread_jit_write_protect_np(0) in
ARM64ImmSymInstruction::generateBinaryEncoding() for AArch64 macOS.
It is needed because methodTrampolineLookup() calls createTrampoline()
when necessary, and that makes the compiler thread lose the permission
for writing to the code buffer.
> AArch64 macOS: Add a call to pthread_jit_write_protect_np()

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector add pairwise instructions
> AArch64: Add vector add pairwise instructions

- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OpBinary.cpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector floating point add pairwise instructions
> AArch64: vector floating point add pairwise instructions

- port/unix/omrtime.c
This commit changes the implementation of omrtime_hires_clock() for
macOS.
> macOS: Use clock_gettime_nsec_np() for omrtime_hires_clock()

- fvtest/porttest/si.cpp
Add test for omrsysinfo_is_running_in_container and fix cgroup tests when
running in a cgroup v1 container.
Issue: #1281
> Add test for omrsysinfo_is_running_in_container

- port/unix/omrtime.c
> Revert "macOS: Use clock_gettime_nsec_np() for omrtime_hires_clock()"

- fvtest/porttest/si.cpp
- port/unix/omrsysinfo.c
* Add testing for omrsysinfo_cgroup_subsystem_iterator_* functions; checks
a few key metrics and that iterating doesn't fail.
* Change default return value from OMRPORT_ERROR_SYSINFO_CGROUP_SUBSYSTEM_UNAVAILABLE
to OMRPORT_ERROR_SYSINFO_CGROUP_UNSUPPORTED_PLATFORM to keep consistency
between Unix and non-Unix.
Issue: https://github.com/eclipse/omr/issues/1281
> Add test for cgroup subsystem iterator functions

- compiler/codegen/OMRCodeGenerator.cpp
- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Previously we had an environment option to disable merging of OSR guards
which was needed to allow VectorAPIExpansion to scalarize or vectorize
Vector API intrinsics on X and Z. Replacing an enviromentment option to
OMR Option to make it easier to set it for automated testing.
> Add OMR Option to disable merging of OSR Guards

- compiler/optimizer/OMRSimplifierHelpers.cpp
in the for loop when DataType greater than Aggregate and still no conversion found, this will avoid assertion failure in [OMRDataTypes](https://github.com/eclipse/omr/blob/master/compiler/il/OMRDataTypes.cpp#L155)
> Skip enum NumOMRTypes in for loop

- compiler/optimizer/LocalDeadStoreElimination.hpp
Replace private access with protected to allow downstream projects to make use of derived classes to extend/specialize the functionality of LocalDeadStoreElimination.
> Make LocalDeadStoreElimination members/methods protected

- compiler/optimizer/SinkStores.hpp
Allow downstream projects to more readily extend the SinkStores classes by making the following TR_SinkStores member functions virtual:
-performStoreSinking()
-lookForSinkableStores()
-doSinking()
-getSinkableSymbol()
-treeIsSinkableStore()
And by making the following member functions protected rather
than private: 
-coalesceSimilarEdgePlacements()
-storeIsSinkingCandidate()
-sinkStorePlacement()
-placeStoresAlongEdges()
-placeStoresInBlock()
> Make Some TR_SinkStores Members Virtual and Protected

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements evaluators for reduce bitwise logical operations.
> AArch64: Implement evaluators for reduce bitwise logical operations.

- compiler/optimizer/LocalOpts.cpp
Blocks could have been removed when the exception edges
of an empty goto block are removed. The removal should
take place before the IN edges are saved in `fixablePreds`.
Fixes: eclipse/openj9#15305
> Move removal of exception edges to before collecting fixable predecessors

- port/unix/omrcpu.c
- util/omrutil/j9memclr.cpp
This allows the compiler to do the widening operation once, rather than repeatedly in loops, fixing a performance regression introduced in #6515.
> Use a wider type for local variables holding the cache line size

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
Implement evaluators for following different opcodes on Z to vectorize
the operation when platform support is available.
1. VFMA
2. VSQRT
3. VABS
> Implement evaluators for different Vector Opcodes

- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRTreeEvaluator.cpp
- fvtest/compilertriltest/VectorTest.cpp
This commit implements vbitselect evaluator and adds a unit test.
> AArch64: Implement vbitselect evaluator

- compiler/z/codegen/S390Instruction.cpp
Internal debug build on z/Linux failed with
```
/.../omr/compiler/z/codegen/S390Instruction.cpp:5380:106: error: format '%d' expects argument of type 'int', but argument 3 has type 'intptr_t {aka long int}' [-Werror=format=]
printf("####> virtual location(est) = %p+%d, label (relocation) = %p\n", cursor, distance, label);
^
```
This patch puts the correct format specifier for `intptr_t`
> Fix format specifier in s390 VGNOP trace

- compiler/x/codegen/OMRInstOpCode.cpp
The rex prefix is illegal in 32-bit mode. However,
some VEX and EVEX encoded instructions use REX.W the bit
as an opcode extension bit. In 32-bit mode, if a SIMD
instruction is encoded as a legacy SSE instruction,
and the W bit is set, a rex prefix may be emitted. This
commit prevents that from happening.
> Don't emit rex prefix on 32-bit

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/OMRCodeGenerator.cpp
- compiler/aarch64/codegen/OMRMemoryReference.cpp
- compiler/aarch64/codegen/OMRMemoryReference.hpp
There are certain cases where the displacement of MemoryReference cannot be determined
until stack mapping is done. Currently, aarch64 codegen cannot perform binary encoding
phase if the displacement becomes too huge as a result of stack mapping.
To address this problem, this commit introduces `expandInstruction` member function
to MemoryReference related instruction classes and MemoryReference class,
and updates MemoryReference to generate necessary instructions in `expandInstruction`
rather than generating binary for multple instructions in `generateBinaryEncoding`.
Unlike power codegen, we do instruction expansion in the loop for estimating byte length
in binary encoding phase.
> AArch64: Expand instructions to address too large displacement of MemoryReference

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
- compiler/aarch64/codegen/ARM64Debug.cpp
- compiler/aarch64/codegen/ARM64Instruction.hpp
- compiler/aarch64/codegen/GenerateInstructions.cpp
- compiler/aarch64/codegen/GenerateInstructions.hpp
- compiler/aarch64/codegen/OMRInstOpCode.enum
- compiler/aarch64/codegen/OMRInstructionKindEnum.hpp
- compiler/aarch64/codegen/OpBinary.cpp
- compiler/ras/Debug.hpp
- fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector and scalar floating point multiplication
by element instructions and binary encoding unit tests.
> AArch64: Add floating point multiplication by element instructions

- compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit stops initializing `cursor` with `instructionStart`.
It is overwritten right after the initialization without use.
> AArch64: Remove redundant assignments in generateBinaryEncoding()

- compiler/p/codegen/UnaryEvaluator.cpp
The s2iEvaluator uses a isLoad() test when deciding between a simple
sign extend or generating a load sequence. The isLoad() test returns
true for both LoadVar and LoadConst cases and therefore we can get
into the load sequence when handling a sconst node child which results
in an assert. This PR will change isLoad() to isLoadVar() so that
the sconst case will use the simple sign extend path.
> Fix an assert in OMR::Power::TreeEvaluator::s2iEvaluator()

- compiler/z/codegen/OMRCodeGenerator.cpp
- compiler/z/codegen/OMRTreeEvaluator.cpp
Check the feature query for VFE1 when checking if opcode is supported
for SIMD or not instead of flags, which are not maintained and would be
cleaned up.
> Check feature instead of Flag for VFE1 facility

- compiler/z/codegen/OMRCodeGenerator.cpp
While constructing a code generator object, check for vector facility
and set appropriate options. This check was done previously in
S390PrivateLinkage in OpenJ9, which would be incorrect place to do so.
Fixes: #6572
> Set Vector Support in OMR

- compiler/optimizer/OMRValuePropagation.cpp
- compiler/optimizer/VPHandlers.cpp
In the process of replacing an `irem`/`lrem` node with its first operand, `removedRedundantRem` used `replaceNode`, which can result in the use/def info held by the `TR::Optimizer` being deleted.  As GlobalValuePropagation has a cached reference to the use/def info, it might continue to use that use/def info after it has been deleted.
This change uses VP's `removeNode` method to ensure deletion of use/def info will be deferred.
This change fixes eclipse-openj9/openj9#15364
> Avoid invalidating use/def info in modifying tree for redundant rem

- gc/base/GCExtensionsBase.hpp
Current softwareRangeCheckReadBarrier flag serves multi purpose.
Clean it be new flag introduction
Add minor comments change
> Introduce softwareRangeCheckReadBarrierForced flag

- include_core/omrport.h
- port/omrportpriv.h
Also remove duplicate declaration.
> Correct definition of omrintrospect_threads_nextDo()

- compiler/optimizer/ValuePropagationCommon.cpp
During globalVP nodes that are added to lists for later processing
may be removed from the trees before doDelayedTransformations is called.
If such nodes are processed the trees can be corrupted and will likely
cause a crash during compilation.
The problem was originally seen with the transformArrayCloneCall, and
has also been demonstrated with transformObjectCloneCall. This PR avoids
the issue for these two functions by testing the reference count of the
call node.
It is likely that other transformations called from doDelayedTransformations
will need similar treatment.
Signed-off-by: James Kingdon <jkingdon@ca.ibm.com>
> Defend removed nodes during delayed transformations

- include_core/omrport.h
- port/aix/omrosbacktrace_impl.c
- port/common/omrosbacktrace.c
- port/common/omrosbacktrace_impl.c
- port/common/omrport.c
- port/linux/omrosbacktrace_impl.c
- port/omrportpriv.h
- port/osx/omrintrospect.c
- port/osx/omrosbacktrace_impl.c
- port/unix/omrintrospect.c
- port/win32/omrintrospect.c
- port/win32/omrosbacktrace_impl.c
- port/zos390/omrosbacktrace_impl.c
- port/ztpf/omrintrospect.c
- port/ztpf/omrosbacktrace_impl.c
Allow separation of symbol resolution from collecting stack traces. Don't call `introspect_backtrace_symbols()` if `OMR_INTROSPECT_NO_SYMBOLS` is specified in `J9ThreadWalkState.options` given to `omrintrospect_threads_*()`.
Add `introspect_backtrace_symbols_ex()` which accepts options, the first of which, `OMR_BACKTRACE_SYMBOLS_BASIC`, controls the cost of symbol resolution. Currently, this is only meaningful on Linux where full symbol resolution can be costly.
> Add options to control the costs of collecting thread stack traces

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
The new verbose option is called `iprofilerPersistence`.
This will be used in a downstream project (openj9)
> Add verbose option for interpreter profiling persistence

- compiler/arm/codegen/OMRInstruction.hpp
- compiler/x/codegen/OMRInstruction.hpp
the member not found in other platforms: aarch64, p, riscv, z
the member is currently at OMR::Instruction level with protected attribution
> Remove duplicate _opcode at arm and x level

- compiler/optimizer/OMRValuePropagation.cpp
This commit fixes a mismatch between the format string and the arguments
for a message in OMR::ValuePropagation::doDelayedTransformations().
> Fix message output in replacing virtual guard

- compiler/control/OMROptions.cpp
- compiler/control/OMROptions.hpp
Add JIT command line option enforceVectorAPIExpansion that would allow
platforms to set the compiler options needed to enforce expansion of
vector API Intrinsics for testing.
> Add Enforce Vector API Expansion Option

- gc/base/standard/ParallelGlobalGC.cpp
With Concurrent Scavenger, we may end up with unflushed Ownabele Sync. buffers which can eventually lead to a heap corruption. Multiple crashes and assertion have been reported as a result of this, for instance:
```
j9mm.141    *   ** ASSERTION FAILED ** at
./OwnableSynchronizerObjectBuffer.cpp:100: ((false))
```
```
** ASSERTION FAILED ** at ./Scavenger.cpp:1659: ((false))
```
```
Corruption in Evacuate at 0000005020E395F8: calculated object size
344152650780 larger then available 3172872, Forwarded Header at
00000050322FE8A8
```
```
*   ** ASSERTION FAILED ** at ../../../gc_glue_java/MarkingDelegate.hpp:123: ((false && ((UDATA)0x99669966 == clazz->eyecatcher)))
```
For Concurrent Scavenger, the Ownable buffers are flushed:
1. At the start of a global cycle when we acquire exclusive …
> Fix: Heap Corruption from Ownable Synchronizers Lists with Concurrent Scavenger 

- compiler/optimizer/DataFlowAnalysis.hpp
Add a perform() method with empty implementation in TR_Liveness to prepare for PR #6612  that splits out analysis from the constructor.
> Add API for performing analysis in Liveness

- compiler/optimizer/VPHandlers.cpp
When applying constraints for a non-overridden call guard, `constrainIfcmpeqne` looks at the guarded call node to see whether the guard can be eliminated.  However, if the call block has more than one predecessor, not all definitions that reach the call block might have been visited on the current walk.  That might result in incorrect constraints being applied to the references on the call because of the incomplete information.
This change adds an additional check of whether the block containing the guarded call has only one predecessor before checking whether the guard can be eliminated.  That is a simple way of ensuring all the predecessors of the guarded call must already have been walked.
This change fixes eclipse-openj9/openj9#14489 and eclipse-openj9/openj9#15311
> Check call has one predecessor before considering eliminating guard

- compiler/codegen/Relocation.cpp
- compiler/il/OMRSymbol.hpp
- compiler/il/OMRSymbol_inlines.hpp
- compiler/ras/Debug.cpp
- compiler/runtime/Runtime.hpp
- compiler/x/codegen/OMRX86Instruction.cpp
- compiler/x/codegen/X86BinaryEncoding.cpp
This relocation record is used to materialize value type default value instance slot address:
`&clazz->flattenedClassCache->defaultValue`
IL:
- Add `StaticDefaultValueInstance` flag to `Symbol` to indicate
if the symbol is for default value instance slot address
X86:
- Add relocation record in AMD64RegImm64SymInstruction for
`TR_StaticDefaultValueInstance` relocation type.
> Add External Relocation Record TR_StaticDefaultValueInstance
