eclipse-omr/omr

compiler/aarch64/codegen/OMRInstruction.hpp, compiler/arm/codegen/OMRInstruction.hpp, compiler/p/codegen/OMRInstruction.hpp, compiler/riscv/codegen/OMRInstruction.hpp, compiler/x/codegen/OMRInstruction.hpp
setOpCodeValue is void since most setters are void
=> Remove duplicate and non-extended methods in Instruction

compiler/env/FrontEnd.hpp, compiler/ilgen/OMRTypeDictionary.cpp, compiler/ilgen/OMRTypeDictionary.hpp, compiler/infra/String.hpp, compiler/infra/Uncopyable.hpp
`TR_Uncopyable` provides highly general functionality that should be available without including FrontEnd.hpp. This commit moves it into its own header, where it will be more widely available.
Additionally:
- It is moved into the `TR` namespace.
- The constructor and destructor are declared `protected` rather than `public`. Only subclasses need access to those.
- The only existing point of use (`TR_FrontEnd`) is changed to use `private` rather than `public` inheritance, since the fact that inheritance is used to get the desired effect is an implementation detail.
- A couple of types are changed to use `TR::Uncopyable`.
=> Make TR_Uncopyable more widely available as TR::Uncopyable

compiler/env/Region.cpp, compiler/env/Region.hpp
The object's type is no longer required to be copy-constructible.
=> Replace TR::Region::create() with registerDestructor()

compiler/optimizer/Inliner.cpp
Now the meaning of the comment matches both the method name and the apparent use of the method.
=> Correct the OMR_InlinerPolicy::suitableForRemat() doc comment

gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/Scavenger.cpp
Relates to https://github.com/eclipse/omr/pull/6633
Currently, we rely on the global collector to flush ownable sync. buffers when completing an external concurrent scavenge cycle during a global collection. This not optimal as it requires all the threads to be iterated and flushed. Furthermore, it is Scavenger's responsibility to flush buffers for the participating GC threads.
=> Flush Ownable Synchronizer Buffers For Each Concurrent Scavenge Phase

fvtest/porttest/omrdumpTest.cpp, fvtest/porttest/testHelpers.cpp, port/aix/omrosdump_helpers.c
omrdump_create has different behaviour depending on whether the core file name contains a path separator, however there is currently no test for the code path where no path separator is found.
This commit introduces such a test.
Signed-off-by: David McCann mccannd@uk.ibm.com
=> Add dump_test_create_dump_with_no_path

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements vector compare evaluators.
These evaluators return a vector register containing the mask result.
The mask result is all ones for the lane where the test passes,
and all zeroes for the lane where the test fails.
=> AArch64: Implement vector compare evaluators

compiler/optimizer/Inliner.cpp, compiler/optimizer/Inliner.hpp
There can be circumstances under which it is technically necessary to generate a run-time test, but where the failure of that run-time test is known in advance to be an exceedingly rare corner case. In such a circumstance, the taken side should be marked cold, which can now be arranged by setting `_forceTakenSideCold` to true.
=> Provide a way to mark cold the taken side of a profiled guard

compiler/il/OMRNode.hpp, compiler/optimizer/LocalOpts.cpp
Also remove an unused flag that would have complicated the description.
=> Correct the comment describing the allocated ranges of node flag bits

compiler/optimizer/LoopVersioner.cpp
The target block is only marked cold when the guard branch is strongly expected to fall through. This might be the case for a profiled guard even when the top profiled receiver type is not overwhelmingly likely, e.g. if the guard uses a method test and all profiled receivers inherit the same method.
It's possible to look specifically for such situations, but for the moment, just don't second-guess the cold marking on the target block.
=> Version profiled guards with cold targets regardless of profiling

compiler/optimizer/VPHandlers.cpp
This is an optional transformation, and when it is performed, tracing should dump trees after the pass even if there were no other transformations.
=> Use performTransformation() for VP VFT load folding

compiler/env/OMRClassEnv.cpp, compiler/env/OMRClassEnv.hpp, compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/optimizer/VPHandlers.cpp, compiler/ras/Debug.cpp
VP would already fold the guard when there was a fixed-type bound for the receiver. Now it will also:
- Fold the guard (to unconditionally go to the cold side) when there is a type bound *C* for the receiver, and instances of *C* cannot possibly be instances of the defining class of the inlined method.
- Fold the guard (to unconditionally go to the hot side) when there is a type bound *C* for the receiver, and *C* has the expected method, and the expected method is final.
- Flag the guard to indicate that its load of the VFT entry is known to be in bounds when there is a type bound *C* for the receiver, and *C* has a large enough VFT. If the guard is not noppable, it might usually require a run-time bounds test, and if it does, this flag will allow that test to be skipped. This is done …
=> Improve VP's handling of guards with method tests

compiler/arm/codegen/OMRInstruction.cpp, compiler/x/codegen/Instruction.hpp
This should be part of #6640 since there were duplicate **_opcode** member at top level and extended platform level, now no need to enforce such TR::InstOpCode::bad at OMR::Instruction level and set it at platform level.
=> Remove dummy opcode value setting in Instruction constructor

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/env/VerboseLog.cpp, compiler/env/VerboseLog.hpp
This PR adds the ability for downstream projects to print checkpoint/restore specific information to the verbose log.
=> Add verbose option and tags for checkpoint restore

compiler/il/OMRILOps.hpp, compiler/il/VectorOperations.enum, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, fvtest/compilertriltest/VectorTest.cpp
Goals:
- Support reduction operations for all supported vertical operations
- Support 128, 256, 512-bit vector lengths
- Support all element types
=> x86: Implement vector reduction opcodes

gc/base/MarkingScheme.cpp, gc/base/MarkingScheme.hpp, gc/base/standard/Scavenger.cpp
fixupForwardedSlot(mrobjectptr_t *slotPtr) has been created for
sharing code between scanMixObject and scan Java stack of continuation
Object in PR6575, we need to pull concurrent scavenger and backout
conditions outside to avoid racing condition to update slot reference
during concurrent marking.
- also update initialize scanCache->_shouldBeRemembered earlier to avoid
overwriting the flag, which could be updated via getObjectScanner()
fix: https://github.com/eclipse-openj9/openj9/issues/15791
=> Fix testHashTableCorrectness issue

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
This contribution includes the following changes: 
- Add all non-static data members to TR::Options default constructor's initializer list
- Ensure _options array is initialized in all TR::Options constructors
- Ensure constructors are used to create new TR::Options objects (rather than memset)
Additionally, this contribution fixes https://github.com/eclipse/omr/issues/6556
=> Fix creation/initialization of TR::Options objects

port/ztpf/omrosdump_helpers.c
To improve performance of system dumps being written out on z/TPF the size
of the chunks before a write is issued was changed from 4k to 1MB.
The change dramatically reduces the number of I/Os when writing system
dumps to the file system.
[skip ci]
=> zTPF: Change system dumps to write out in at least 1MB frames

port/unix/omrintrospect.c
`barrier_block_until_poked()` may signal failure with a value other than -1. In particular, if the controlling thread decides time has run out, it closes the pipe which may cause `poll()` to signal `POLLNVAL` in `revents` for waiting threads, leading them to see `barrier_block_until_poked()` return -2. 
Also general cleanup; use `OMR_ARE_ANY_BITS_SET()`, `OMR_ARE_NO_BITS_SET()`.
=> Don't wait indefinitely to gather stack traces

example/glue/ScavengerDelegate.cpp, example/glue/ScavengerDelegate.hpp, gc/base/MarkingScheme.cpp, gc/base/MarkingScheme.hpp, gc/base/standard/HeapWalker.cpp, gc/base/standard/HeapWalker.hpp, gc/base/standard/Scavenger.cpp
Remove the temporary comments after the dependent downstream project
has merged.
Update Method fixupForwardedSlot return true or false for the condition
to update heap object reference slot(we won't need to update the
reference slot if the reference is not fixed up) in order to avoid
potential reference slot overwriting(concurrent marking) during
Concurrent scavenger back out case.
Share method MM_Scavenger.shouldRememberSlot, remove duplicated logic
for checking if should remember the slot.
related: #6575
=> Uncomment the code have 2 dependency with downstream projects

compiler/aarch64/codegen/OMRCodeGenerator.cpp
`doBinaryEncoding` function dereferences in the previous instruction pointer in the second while loop. However, if the method starts with `proc` pseudo instruction, the prev pointer is NULL. Fix it to avoid a NULL dereference.
=> AArch64: Fix CodeGenerator to support the method starts with `proc` instruction

gc/base/standard/HeapWalker.cpp, gc/base/standard/HeapWalker.hpp
Update HeapWalker.newInstance for initializing the delegate
fix:https://github.com/eclipse-openj9/openj9/issues/15852
=> Update HeapWalker.newInstance for initializing the delegate

gc/base/ParallelHeapWalker.cpp
Missing initializing could cause crashing during heap walking.
fix: https://github.com/eclipse-openj9/openj9/issues/15852
=> Update ParallelHeapWalker.newInstance for initializing the delegate

compiler/env/OMRCPU.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp
The initialization of the static instance of `TR_X86ProcessorInfo` is changed. 
Instead of the instance being a member of `OMR::X86::CodeGenerator`, it is 
changed to be an instance of a method of `OMR::X86::CodeGenerator`. This 
is necessary because prior to this PR, the static instance was never zero initialized.
This PR also adds the ability to reinitialize the static TR_X86ProcessorInfo instance.
=> Add ability to reinitialize TR_X86ProcessorInfo

README.md, omrtrace/CMakeLists.txt
* Fix documentation to ensure `OMR_GC_MODRON_SCAVENGER` is enabled during the build
* Add `-O3` to `omrtrace` component to prevent warning about not compiling with `-O` when `_FORTIFY_SOURCE` is specified.
=> Fix build breaks with gcc 11.3.1

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements vmadd/vmsub/vmand/vmor/vmxor evaluators. They simply do unmasked operations and use bitselect to insert the value of the first operand for unmasked lanes.
=> AArch64: Implement evaluators for masked vector binary operations

compiler/x/codegen/OMRMemoryReference.cpp, fvtest/compilerunittest/x/BinaryEncoder.cpp
An memory corruption issue was discovered to be caused by EVEX encoded store instructions. After investigation, instructions with an overriden EVEX encoding form may not be encoded with EVEX disp8xn displacement. This commit ensures that mem-ref displacement is correctly encoded for instructions with an overridden encoding method.
=> x86: Fix EVEX mem-ref displacement

compiler/il/Aliases.cpp, compiler/il/OMRDataTypes.cpp, compiler/il/OMRDataTypes.hpp
Remove using vectorToScalar query from codebase and use
getVectorElementType() query instead to get the element type of the
vector opcode.
Closes: https://github.com/eclipse/omr/issues/6658
=> Remove vectorToScalar OMRDataType query

compiler/optimizer/VPHandlers.cpp
The value propagation handlers for `iushr` and `lushr` have special handling for the cases where the lower bound (L) of the left operand is non-negative or its upper bound (U) is negative, if the right hand operand's value (S) has a constant constraint.  If L is non-negative, the handler sets the range of the result of the operation to be in the range [L>>S,U>>S]; if U is negative, it sets the range of the result to be [U>>S,L>>S].  However, the latter range has the bounds reversed, as can be seen by considering an example.
For instance, if L is 0x80FFFFFF (-2130706433) and U is 0xFFFFFFFF (-1) and S is 24, [U>>S,L>>S] yields the range [0xFF, 0x80] or [255,128].
Corrected this by computing the result range the same way for both non-negative ranges and negative ranges.
Fixes …
=> Correct constraint range for iushr and lushr with negative operand

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit fixes compilation warning of OMRTreeEvaluator.cpp.
=> AArch64: Fix compilation warning

compiler/aarch64/codegen/BinaryEvaluator.cpp
`generateUBFMForMaskAndShift()` generates incorrect `ubfm` instruction when the sum of  left shift amount and mask width exceeds the size of integer. Some tests in [ShiftAndRotateTest](https://github.com/eclipse/omr/blob/master/fvtest/compilertriltest/ShiftAndRotateTest.cpp) fail due to this problem.
This commit fixes `generateUBFMForMaskAndShift` to validate width value before generating `ubfm` instruction.
=> AArch64: Fix handling of mask and shift operation

fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds binary encoding unit test cases
for vsplats operations.
=> AArch64: Add binary encoding test cases for vsplats

compiler/runtime/Trampoline.cpp, fvtest/compilertest/runtime/TestCodeCacheManager.cpp
This commit updates `TestCodeCacheManager` to allocate the `CodeCacheMemorySegment` object by malloc instead of using a part of the mmaped memory segment on AArch64 Mac. If the `CodeCacheMemorySegment` object is allocated on the mmaped segment, `pthread_jit_write_protect_np` calls are required before/after updating the fields of the object.
Also, `pthread_jit_write_protect_np` calls are added into `arm64CreateHelperTrampolines`.
=> AArch64 Mac: Update TestCodeCacheManager to enable compiler unit tests

compiler/z/codegen/OMRTreeEvaluator.cpp
InlineVectorUnaryOp evaluator was called to generate instruction for VABS for integral type but did not emit VLP instruction to load positive value of the operand for ABS. This commit fixes that and also changes an assert to fatal assert to make sure it is called for the op which is supported.
Fixes: https://github.com/eclipse-openj9/openj9/issues/15918
=> Fix VABS evaluator

port/ztpf/omrvmem.c
The z/TPF OS does not support address range checking when an mmap request
fails.
[skip ci]
=> zTPF: Disable address range search on mmap failure

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstOpCode.enum, compiler/aarch64/codegen/OMRInstructionKindEnum.hpp, compiler/aarch64/codegen/OpBinary.cpp, compiler/ras/Debug.hpp, fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector extract instruction and
binary encoding unit tests.
=> Arch64: Add vector extract instruction

gc/base/j9mm.tdf, gc/base/standard/CompactScheme.cpp, gc/base/standard/CompactScheme.hpp, gc/base/standard/ParallelGlobalGC.cpp, gc/stats/GlobalGCStats.hpp, gc/verbose/VerboseHandlerOutput.cpp, gc/verbose/VerboseHandlerOutput.hpp
Add heap fixup verbose GC logging and J9mm tracepoints
for heap fixups that also include the reason for the heap fixup.
Signed-off-by: Jonathan Oommen jon.oommen@gmail.com
=> Add Heap Fixup GC Logging and J9MM Tracepoints

compiler/il/ILOpCodes.hpp, compiler/il/OMRDataTypes.hpp, compiler/il/OMRDataTypes_inlines.hpp, compiler/il/OMRIL.cpp, compiler/il/OMRILOps.cpp, compiler/il/OMRILOps.hpp, compiler/ilgen/OMRIlType.cpp, compiler/ilgen/OMRIlType.hpp, compiler/optimizer/OMROptimizer.cpp, fvtest/tril/tril/ilgen.hpp
- fix creation of two-type vector opcodes
- allow Mask opcodes to be created using Mask type
- handle Mask type in the opcode mapping methods
- handle Mask opcodes in TRIL
- handle two-type Mask and Vector opcodes in TRIL
=> Apply various fixes for the Mask and Vector types

compiler/infra/OMRCfg.cpp, compiler/infra/OMRCfg.hpp
to be accessible by extended class
=> Make unreachableOrphan a member method

example/glue/ObjectModelDelegate.hpp, gc/base/GCExtensionsBase.hpp, gc/base/standard/ConcurrentCardTable.cpp, gc/base/standard/ConcurrentGC.cpp, gc/base/standard/ConcurrentOverflow.cpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/HeapWalker.cpp, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/Scavenger.hpp, gc/structs/SublistFragment.cpp
There is a number of functions in the GC Extensions Base defined under
the OMR_GC_MODRON_SCAVENGER flag. However, there are many places where
these functions are called unconditionally without checking this flag.
This flag is always enabled in our compilation environment, which
allows the code to compile. If it is disabled, the code fails to
compile. The solution is to always define these functions and wrap
Scavenger related content inside them.
=> Fix discrepancy in GC Extensions Base functions

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/compile/VirtualGuard.cpp, compiler/compile/VirtualGuard.hpp, compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/il/OMRNode_inlines.hpp, compiler/il/OMRResolvedMethodSymbol.cpp, compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/LoopVersioner.hpp, compiler/optimizer/OMROptimization.cpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/VPHandlers.cpp, compiler/optimizer/VirtualGuardCoalescer.cpp, compiler/ras/Debug.cpp, compiler/z/codegen/BinaryCommutativeAnalyser.cpp
Previously, the `TR_VirtualGuard` corresponding to a guard node was identified by a combination of its BCI and its guard kind. The guard kind was partially erased so that some of the guard kinds (e.g. HCR and OSR guards) were considered significant, while most regular virtual guard types were not distinguished from one another. So when given an HCR guard node, `findVirtualGuardInfo()` would look specifically for a `TR_VirtualGuard` with kind `TR_HCRGuard`, but when given, say, a profiled guard, it would turn up the first guard it found with matching BCI and without a 'significant' guard kind, which could be e.g. a nonoverridden guard instead.
This old way of correlating guard nodes each with their corresponding `TR_VirtualGuard` was troublesome because of two possible kinds of …
=> Stop sharing TR_VirtualGuard between multiple guards with the same BCI

fvtest/porttest/CMakeLists.txt, fvtest/porttest/omrmemTest.cpp, fvtest/porttest/omrvmemTest.cpp
This commit fixes the following failures with porttest on AArch64 macOS.
- memTest: You cannot allocate memory with omrmem_allocate_memory32().
Exclude related tests.
- vmemTest: You need to call pthread_jit_write_protect_np().
=> Fixes for porttest on AArch64 macOS

compiler/optimizer/GeneralLoopUnroller.cpp
When `newTo` is different from `newFromNextBlock` in fall into case, goto block needs to be added besides
of the cfg edges because the `newTo` block is not the fall through block.
Fixes: eclipse-openj9/openj9#15764
=> Fix missing goto block when adding edges back to the unrolled header

gc/base/GCExtensionsBase.hpp
Remove unused idle tuning fields
=> Remove unused idle tuning fields

gc/verbose/schema.xsd
Fix heap fixup tracing schema failures due to previously added heap fixup verbose GC logging and J9mm tracepoints found in https://github.com/eclipse/omr/pull/6593.
Signed-off-by: Jonathan Oommen jon.oommen@gmail.com
=> Fix Heap Fixup Tracing Schema Failure

port/unix/omrsysinfo.c
This commit implements omrsysinfo_get_processor_description() for AArch64 macOS.
Closes: #6739
=> AArch64 macOS: Implement omrsysinfo_get_processor_description()

buildenv/jenkins/omrbuild.groovy, doc/GuideForCommitters.md
- With mixed refs, compressed references specific PR builds are no
longer applicable. linux_x86-64_cmprssptrs spec has been removed.
- OMR Jenkins only supports RISC-V cross-compile builds. linux_riscv64
spec has been removed since it is not supported in OMR Jenkins.
- Updated platform list in the documentation.
=> Update build script and documentation

buildenv/jenkins/omrbuild.groovy
There is a problem on zos where the known_hosts
for github.com cannot be verified. It is intermittent
and can come and go on either machine seemingly randomly.
This changes adds a retry wrapper to the clone which will
retry the clone if it fails up to 10 times. It also adds
a delay of 1 minute in between each try.
=> Add retry 10 around clone with 1 minute delays

compiler/x/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/VectorTest.cpp
This commit fixes a binary encoding issue
present on AVX-512 hardware whereby EVEX
instructions would become VEX encoded.
This causes functional issues for instructions
that are not supported pre-AVX512. This
problem is fixed by querying for the best
encodding method.
=> x86: Fix min/max reduction on AVX-512

compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
This patch enables the downstream projects to override numGPRRegsWithheld().
=> Fix a call to numGPRRegsWithheld() to enable project extensions

compiler/env/OMRVMEnv.hpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/VPHandlers.cpp
For all profiled guards (VFT test or method test), when the guard is not folded, replace it with a noppable guard if possible.
Replacing a VFT test with a noppable guard is possible when there is a type bound *C* for the receiver, and *C* is the type expected by the VFT test, and *C* has not been extended. It's as though *C* is final (which would allow folding via a fixed-type constraint), but only until further notice.
Replacing a method test with a noppable guard is possible when there is a type bound *C* for the receiver, and *C* has the expected method, and the expected method is not overridden. It's as though the expected method is final (which would allow folding), but only until further notice.
By default such upgrades are performed only outside of the VM startup phase, since …
=> Rework profiled to nop guard upgrades in VP

fvtest/compilertriltest/MinimalTest.cpp
This commit stops compiler warnings with MinimalTest.cpp.
Fixes: #6757
=> Stop checking OS type in MinimalTest.cpp for Z

compiler/optimizer/ExpressionsSimplification.cpp, compiler/optimizer/ExpressionsSimplification.hpp
This pull request fixes two problem in Expressions Simplification.
1. In considering whether expressions are invariant and can be pulled out of a loop, `TR_ExpressionsSimplification::removeUncertainBlocks` checks whether blocks will be executed exactly once within each iteration of the loop, and if not, it removes them from consideration.  It does this by checking whether the block post-dominates the entry block for the loop.  However, if a block is in another loop nested within the loop, it might post-dominate the entry but still be executed more than once in each iteration of the outer loop.  Such blocks must also be removed from consideration.
2. Expressions Simplification tracks candidates for summation reduction transformation and invariant expression transformation in a list of …
=> Fix problems in handling of summation reduction and invariant expressions in Expressions Simplification

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.hpp, fvtest/compilerunittest/p/BinaryEncoder.cpp
This contribution includes the following changes:
- vneg IL opcodes have been enabled for all vector types on PPC
- Codegen sequences for vectorized negation for all integer-type vectors have been implemented/improved on PPC
- Binary encoder unit tests have been added for newly enabled PPC instructions
=> Implement vectorized negation for Integer vector types on PPC

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements mRegLoad and mRegStore evaluators.
=> AArch64: Implement mRegLoad and mRegStore evaluators

compiler/aarch64/codegen/BinaryEvaluator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit implements vmul/vdiv/vmin/vmax evaluators. `inlineVectorBinaryOp` and `inlineVectorMaskedBinaryOp` are changed to take an optional function pointer argument and call the pointed function if it is not null.
Helper functions for vmul/vdiv/vmin/vmax are changed to take result, first argument and second argument registers as parameters instead of evaluating nodes inside them.
=> AArch64: Implement evaluators for additional masked vector binary operations

compiler/optimizer/VPHandlers.cpp
Allow folding (or for profiled guards, replacement by noppable guards) to proceed even if the guard in question is merged with an HCR or an OSR guard. Guards folded to always go to the cold side need no special handling. Guards folded to always go to the hot side (i.e. to fall through) have any merged HCR and/or OSR guard split out so that the virtual guard can be removed. When a profiled guard is replaced by a noppable guard, the noppable guard has the same merged HCR or OSR guard as the original profiled guard did, if any.
Currently, this only affects guards that can be folded simply based on the value numbers or constraints of the children (e.g. `mustBeEqual()`), or guards that use VFT test or method test. The logic that folds nonoverridden guards has `canFoldNonOverriddenGuard()` …
=> Allow VP to remove/upgrade virtual guards with merged HCR/OSR guards

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.hpp, compiler/il/OMRILOps.hpp, compiler/il/VectorOperations.enum, compiler/optimizer/OMRSimplifierTable.enum, compiler/optimizer/ValuePropagationTable.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.hpp, compiler/riscv/codegen/OMRTreeEvaluator.cpp, compiler/riscv/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp
- the opcodes return true iff at least one element(testAny) or all
elements(testALL) of the vecror mask are true
- both testAny and testAll opcodes have masked and non-masked
versions, so add mTestAny, mTestAll, mmTestAny, mmTestAll
=> Add vector mask testAny, testAll and conversion opcodes

compiler/optimizer/LocalOpts.cpp
Previously, it was possible for the JIT to devirtualize an interface call, and for execution to reach the call (whether inlined or not) with a receiver that is not an instance of the class expected by the implementing method. The callee could then access fields of the receiver as though it were of the expected type.
The conditionals added in this commit still allow (on their own) for an interface call to be devirtualized when preexistence has already proven that the receiver is an instance of some particular class that implements the expected interface. However, preexistence currently fails to devirtualize in that situation. It passes the class to `TR_PersistentCHTable::findSingleInterfaceImplementer()`, which needs the interface. This can be improved in the future by having preexistence …
=> Stop devirtualizing interface calls in preexistence

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements vmabs, vmneg, vmnot, vmsqrt evaluators.
=> AArch64: Implement masked unary operation evaluators

compiler/aarch64/codegen/BinaryEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/ShiftAndRotateTest.cpp
- Add missing bshl/bshr/sshl/sshr/bushr/sushr/band/bor/bxor/sand/sor/sxor evaluators to aarch64 code generator.
- Enable ShiftAndRotate fvtest on aarch64.
Resolves #5892
=> AArch64: Add byte and short shift and logical opcode evaluators

fvtest/porttest/omrmemTest.cpp, port/common/omrmemtag.c
**Commit 1** - Guard against very large allocation sizes which overflow
when memory tagging overhead is added.
**Commit 2** - omrmemtest: check that large allocations don't overflow.
**Commit 3** - Handle reallocation failures: Restore allocation headers in
the case realloc fails.
=> Avoid size overflow when allocating memory

compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit implements s2m, i2m, l2m, v2m, m2s, m2i, m2l and m2v evaluators.
=> AArch64: Implement mask conversion opcode evaluators

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.hpp
Correct the implementation of `canTransformUnsafeCopyToArrayCopy()` to check for the `disableArrayCopyOpts` option in P and AArch64.
=> Check disableArrayCopyOpts in canTransformUnsafeCopyToArrayCopy P/A64

gc/base/GCExtensionsBase.hpp, gc/base/standard/ConfigurationGenerational.cpp
Upgrading inlined code to virtual methods for register scavenger
so that subclasses could override behavior.
=> Upgrading inlined code to virtual methods for register scavenger

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Refactor vector reduction operation evaluators to use a common helper function to reduce boilerplate code. Implement vector masked reduction operation evaluators using the same approach as non-masked ones.
=> AArch64: Implement vector masked reduction evaluators

compiler/z/codegen/OMRInstruction.cpp
Account for vector registers when calculating real register to check if spill is needed after a load multiple instruction. This fixes the behaviour of uneccessarily and incorrectly spilling GPRs when using VLM. An example of the error from my experience trying to accelerate crc32c on Z:
```
[     0x3ff8dcbd580]                          VLM     VRF_0095,VRF_0098,#415 0(&GPR_0033)VRF_0095(0/6)~FPR5 VRF_0098(0/6)~FPR8 
details:                      trying to free GPR_0099 for killed reg GPR6 by loadmultiple 
details:                      BEST FREE REG for GPR_0099 is GPR14 
[     0x3ff8ddb3610]                          LGR     GPR6,GPR14       details:                      trying to free GPR_0050 for killed reg GPR7 by loadmultiple 
details:                      BEST FREE REG for GPR_0050 is …
```
=> Kill correct registers for VLM

compiler/control/OMROptions.cpp
In processOptions(), a call to getDefaultOptions() should use TR::Options rather than OMR::Options so that a version of the method defined in any extension to the Options class will be used.
=> Call most derived getDefaultOptions method

compiler/ras/Debug.hpp, compiler/ras/Tree.cpp
When the necessary env variable is set, verifyTreesPass1() checks the child type of a given Node's IL op, but it fails to check for whether the expectedType is a valid DataType (if the expected child type is "unspecified", for example, then it should not try to match the expectedType to the actual childType). Add this check for a valid child type.
Make nodePrintAllFlags virtual to allow downstream projects to provide project-specific modifications.
=> Make Debug verifyTrees work and allow nodePrintAllFlags override

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/ras/Debug.cpp
Add a new option to limit the trace file size: default is unlimited as before, when any value set, check trace file size and rewind trace file when hit limit.
=> Add option to limit trace file length

compiler/aarch64/codegen/FPTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/CompareTest.cpp
This commit implements unordered fcmp/dcmp evaluators for AArch64, such as fcmpequ and dcmpltu..
Closes: #5895
=> AArch64: Implement unordered fcmp/dcmp evaluators

compiler/p/codegen/OMRCodeGenerator.cpp
There are currently two situations in which vector loads and stores for sub-int types can be used PPC while preseving the order of the elements:
- On P9 and up, using one of the VSX load/store instructions specifically for vectors with byte/halfword-length elements (lxvb16x, stxvb16x, lxvh8x, stxvh8x)
- On big endian systems, where that coupled with the semantics of the VSX load/store instructions for word-length elements (lxvw4x, stxvw4x) mean that element order is preserved regardless of which VSX load/store instruction is used
Thus, vload and vstore have been re-enabled on PPC for those two situations
=> Enable vload/vstore/mload/mstore for Byte and ShortVectors on P9+/big endian power systems

compiler/compile/VirtualGuard.cpp, compiler/optimizer/LoopVersioner.cpp
It used to be that a standalone OSR guard could not target a cold call. However, virtual guards target cold calls even when they are merged with OSR guards. Recently, VP learned to remove the virtual part of a virtual guard despite any merged guards (3d1fec9523d4f9e779dc1b85119a6b0b5c642ced, #6762). The merged HCR or OSR guard is promoted to a standalone HCR or OSR guard, and any standalone OSR guard produced in this way does target a cold call.
It was possible for such an OSR guard to be confused for a virtual guard, and therefore for loop versioner to try to version it as though it were a virtual guard, resulting in an assertion failure:
guardOkForExpr: should not intern OSR guard ...
This happened only very rarely because the OSR guard does not use VFT test or method test, so in order …
=> Avoid analyzing OSR guards as virtual guards in versioner

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp
Disable GRA for vector and mask types.
=> AArch64: Disable GRA for vector types

compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/aarch64/codegen/OMRMemoryReference.hpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
On aarch64, the immediate offset to the memory access must be the multiples of 16 when the size of access is 128-bit. This commit changes commonLoadEvaluator and commonStoreEvaluator to handle those cases manually.
In the longer term, MemoryReference class should take the size parameter and take it into acount when populating.
=> AArch64: Handle unaligned immediate offset memory access case

include_core/omrport.h, port/common/omrportcontrol.c, port/common/omrstr.c, port/unix/omrsysinfo.c, port/unix_include/omrportpg.h, port/zos390/omrportpg.h
Attempt user name retrieval with `sysinfo_get_env()`
To generate platform independent tokens, try `sysinfo_get_username()` if `CRIU` is not enabled or it is a final restoration; if it fails, try `sysinfo_get_username()` instead.
This doesn't take the user name longer than `USERNAME_BUF_LEN`, if the call fails, we just don't add it;
`CRIU` requires `sysinfo_get_env()` if a checkpoint is to be taken and avoid `sysinfo_get_username()` at VM early startup which might call `getpwuid()`, trigger `SSSD` socket connection, and cause a checkpoint failure;
More details are at https://github.com/eclipse-openj9/openj9/issues/15800;
Add `PPG_instantOnFlags` for the state `OMRPORT_INSTANTON_ENABLED` and `OMRPORT_INSTANTON_FINAL_RESTORE`;
Fix a few method signature mismatching.
Signed-off-by: Jason Feng …
=> Attempt user name retrieval with sysinfo_get_env()

include_core/omrport.h, port/common/omrportcontrol.c, port/common/omrstr.c, port/unix/omrsysinfo.c, port/unix_include/omrportpg.h, port/zos390/omrportpg.h
Use CRIU technology term instead of vendor-specific product naming
Replace `instantOn` with `criuSupport`.
Related https://github.com/eclipse/omr/pull/6796#issuecomment-1313996929
=> Use CRIU technology term instead of vendor-specific product naming

compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/VPHandlers.cpp
This facilitates moving the logic to OpenJ9, where it belongs, and also fixing it (to deal with array-of-interface types) in a single place.
----
Also:
- Delete the long-inactive `constrainBaseObjectOfIndirectAccess()`
=> Factor VP interface type signature detection logic into its own method

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp
`findOrFabricateFlattenedArrayElementFieldShadowSymbol` is not used in OMR
=> Remove findOrFabricateFlattenedArrayElementFieldShadowSymbol

compiler/il/OMRILOps.hpp, compiler/il/VectorOperations.enum
Return the correct value for the `getDataType` query when the node has mask reduction opcode.
=> Fix the data type of vector mask reduction node

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Implement mTrueCount, mFirstTrue, mLastTrue, mToLongBits and mLongBitsToMask evaluators.
=> AArch64: Implement mask reduction operation evaluators

compiler/optimizer/OMRValuePropagation.cpp
It has been moved into OpenJ9.
=> Remove Java-specific interface signature logic from VP

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/z/codegen/OMRInstOpCode.enum, compiler/z/codegen/OMRInstOpCodeProperties.hpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp, include_core/omrport.h, port/unix/omrsysinfo.c
=> Replace zNext with z16

compiler/control/OMROptions.cpp
Since we have made improvements to allow marking guards for the Vector JEP method does not kill fear, we no longer need to disable merging of OSR guards to enforce Vector API Expansion. Remove setting that option.
=> We do not need disableOSRGuardsMerging to enforceVectorAPIExpansion

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/il/OMRResolvedMethodSymbol.cpp
Introduces a TR_DisableIlgenOpts option flag that can be set in order to skip optimizations run during ilgen.
=> Add option to skip ilgen optimizations

jitbuilder/release/CMakeLists.txt, jitbuilder/release/cpp/samples/Power.cpp, jitbuilder/release/cpp/samples/Power.hpp
Provide a new JitBuilder sample code that demonstrates how to compute power(a,n) using the DoWhileLoop construct to multiply a by itself n times (n is an integer). This code sample will be included in the set of default code samples that runs when OMR_JITBUILDERTEST is enabled in cmake builds.
=> Add integer exponent code sample to JitBuilder

compiler/p/codegen/OMRCodeGenerator.cpp
Enable `vbitselect` for all vector types. This, as well as https://github.com/eclipse-openj9/openj9/pull/16393 will allow the vectorization of blend() operations to occur.
=> Enable vbitselect IL opcode on PPC

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Enable `vbitselect` for all vector types.
`vbitselect` is a kind of masked operations which takes the third argument as a mask.
We can apply it to vectors with float or double elements in addition to vectors with integer elements.
=> AArch64: Enable vbitselect opcode for all element types

compiler/z/codegen/FPTreeEvaluator.cpp, compiler/z/codegen/OMRLinkage.cpp, compiler/z/codegen/OMRMemoryReference.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/S390GenerateInstructions.cpp, compiler/z/codegen/S390GenerateInstructions.hpp, compiler/z/codegen/S390Instruction.cpp
LE instruction on IBM Z loads single precision floating values into the FPR register. In certain scenarios this operation may perform poorly espcecially in case of Write after Read or Write after Write scenario where hardware may not be able to break the dependency chain. In such scenarios, using LDE instruction to load from memory would help. This commit replaces the use of LE instruction with LDE.
=> Use LDE to load single precision floating point values

compiler/z/codegen/OMRInstruction.cpp, compiler/z/codegen/OMRMachine.cpp, compiler/z/codegen/OMRMachine.hpp
- Add logic in `getRegMaskFromRange` and add `genBitMapOfAssignableVRFs` to account for vector registers when generating register bit masks
- Collect GPR/VRF specific logic to a single if-else statement in `handleLoadWithRegRanges`, cleaning up the `isVector ? ... : ...` idiom
=> Z: Account for vector registers in bit masks for register assignment

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/GCExtensionsBase.hpp, gc/base/ParallelDispatcher.cpp, gc/base/ParallelDispatcher.hpp, gc/base/j9mm.tdf, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp, gc/base/standard/ConfigurationStandard.cpp, gc/base/standard/ConfigurationStandard.hpp, gc/base/standard/Scavenger.hpp
These changes aim to optimize/tune GC threading footprint observed when using CRIU (Checkpoint/Restore) capabilities. Tests have shown excessive number of GC threads to have a significant impact on checkpoint image footprint and restore times. Contracting the GC thread pool during the checkpoint phase and expanding it during restore phase has shown to be a better strategy.
These changes introduce APIs to adjust the size of the GC (dispatcher) thread pool and make adjustments to dependent parties consuming the thread count:
- Introduced `contractThreadPool` (to shutdownThreads for checkpoint) and expandThreadPool (to startupThreads for restore)
- Introduced `checkpointGCthreadCount` in extensions (user adjustable via cmd line opts), consumed to contract thread pool.
- Refactored and …
=> GC Thread Pool Tuning for CRIU

compiler/optimizer/OMRLocalCSE.hpp
Make canBeAvailable, transformBlock, and examineNode virtual to allow downstream projects to override as needed.
=> Make LocalCSE methods virtual

compiler/optimizer/LocalDeadStoreElimination.hpp
Allow projects to override areLhsOfStoresSyntacticallyEquivalent() and adjustStoresInfo() as needed.
=> Make methods in LocalDeadStoreElimination virtual

compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
Allow projects to specialize how they set up interpreter entry instruction during binary encoding.
=> Split generateInterpreterEntryInstruction out of doBinaryEncoding

compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit implements a case in loadRelocatableConstant() in OMRMemoryReference for AArch64.
=> AArch64: Implement a case in loadRelocatableConstant()

compiler/ras/Debug.hpp, compiler/ras/LimitFile.cpp
The option processing framework now includes a limitOption function overload that allows the user to specify a particular compilation filter set.
Fixes: eclipse-openj9/openj9#15399
Signed-off-by: Christian Despres <despresc@ibm.com>
=> Expose a new limitOption for OpenJ9

compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp
Add N bit argument to generateTestImmInstruction
so that 64bit instructions are properly generated.
=> AArch64: Add N bit argument to generateTestImmInstruction

port/unix/omrsock.c
poll() man page explicitly allows for 0 in the events argument
=> port: Allow 0 in events argument for pollfd_init

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/runtime/VirtualGuardRuntime.cpp, compiler/codegen/OMRCodeGenerator.cpp, compiler/runtime/OMRCodeCache.cpp, compiler/runtime/OMRCodeCacheManager.cpp, compiler/runtime/Trampoline.cpp, fvtest/porttest/omrvmemTest.cpp, include_core/thread_api.h
Centralize access to `pthread_jit_write_protect_np()`.
Define `omrthread_jit_write_protect_disable()` and `omrthread_jit_write_protect_enable()` to reduce repetition and simplify porting to platforms where writes are normally disallowed to executable memory. It will also reduce the cost of reacting to changes to already supported platforms (e.g. it should not surprise anyone if the protection that must be managed on Aarch64 becomes a necessity on x86 processors as well).
=> Generalize management of write access to dynamically generated code

buildenv/docker/x86_64/ubuntu20/Dockerfile
Follows Docker best practices. Running as root
is an unnecessary privilege escalation
=> Run container as USER jenkins

.copyrightignore, Notice.html
http links are insecure. This was flagged by an IBM security scan.
=> Use https links in notice file

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/OMRInstOpCode.enum, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OpBinary.cpp, compiler/aarch64/codegen/UnaryEvaluator.cpp, compiler/aarch64/env/OMRCPU.hpp
This commit implements ipopcnt/lpopcnt evaluators for AArch64.
=> AArch64: Implement popcnt evaluators

compiler/optimizer/ExpressionsSimplification.hpp
If the bounds on a loop induction variable differ by about 2^31 or more, the calculation of the iteration count in `LoopInfo::getNumIterations` might overflow.  Changed calculation of number of iterations to use `int64_t` intermediate values and then check whether the result is less than or equal to the maximum `int32_t` value.  If it is greater, a result of zero is returned to indicate that the number of iterations is unknown.
Fixes eclipse-openj9/openj9#16398
=> Avoid overflow calculating number of loop iterations

gc/base/Configuration.hpp, gc/verbose/VerboseManager.cpp, gc/verbose/VerboseManager.hpp, gc/verbose/VerboseManagerBase.hpp, gc/verbose/VerboseWriter.hpp, gc/verbose/VerboseWriterFileLogging.cpp, gc/verbose/VerboseWriterFileLogging.hpp
Files opened by Verbose GC must be excluded from the CRIU dump. Opened logs can be problematic as the restore file validation can fail if the logs change between checkpoint and restore (e.g. file contents/metadata changed or file not available at restore time, which is typical for CRIU use cases). Hence, Verbose GC file writers/streams must be closed prior to creating a check point image and reopened for restore.
- Introduced `openStream` for Verbose Writers
- Used to openFile associated with file writers , only required for buffered and  synchronous file logging, base class `MM_VerboseWriterFileLogging`
- Introduced `openStreams` for Verbose Manager
- To walk the set of verbose writers and open streams  (complementary to existing `closeStreams` routine)
- Introduced …
=> Verbose GC CRIU Support

compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/il/OMRNode_inlines.hpp, compiler/infra/Arith.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPConstraint.hpp
- Make `TR::Node::recreate()` unset the cannotOverflow flag
- Auto-set `X==0`, `X!=0`, `X>=0`, `X<=0` flags correctly for constant nodes
- Make `VPConstraint::{add,sub}WithOverflow()` freestanding functions
- Preserve flags in simplifier transformations
- Stop recreating `iadd`/`isub` as `imul` when distributing in simplifier
Please see the individual commit messages.
=> Fix incorrectly-preserved flags in simplifier

compiler/ras/Debug.cpp
This commit implements TR_Debug::getRealRegisterName() for AArch64.
=> Implement TR_Debug::getRealRegisterName() for AArch64

compiler/riscv/codegen/OMRRealRegister.hpp, compiler/riscv/codegen/RVInstruction.hpp, compiler/riscv/codegen/RVInstructionUtils.hpp, compiler/riscv/runtime/VirtualGuardRuntime.cpp
These variants are useful when generating "hand-written" code such as snippets,
trampolines and thunks.
=> RISC-V: add variant of instruction encoding utilities taking RegNum

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/infra/SimpleRegex.cpp, compiler/infra/SimpleRegex.hpp
This change introduces the `suppressEA` option.  The intent is that a downstream project can use the option to suppress stack allocations at matching locations that might be performed in an Escape Analysis optimization.
The other part of the change defines a new `TR::SimpleRegex::match` method that will match a regular expression against a location in a sequence of inlined method invocations that are described by a `TR_ByteCodeInfo`. The `TR_ByteCodeInfo` is rendered as strings of the form
```   
'#' <outermost-method-sig> '@' <bc-offset> { '#' <inlined-method-sig> '@' <bc-offset> } *
```
and
```
'@' <bc-offset> { '#' <inlined-method-sig> '@' <bc-offset> } *
```
where each &lt;bc-offset> is the bytecode offset from the start of a method, and each &lt;method-sig> is the signature of the …
=> Define suppressEA option and implement regular expression matching based on a location in IL

compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/LoopVersioner.hpp
This fixed-point analysis determines the maximal set of deferred versioning operations that are possible to carry out. It does this by initially tentatively allowing all versioning operations, and then until a fixed-point is reached, analyzing what would remain of the loop after versioning with the current tentative assumptions. If no remaining operations would interfere with the versioning, then a fixed-point has been reached, and the tentative assumptions can be locked in.
Previously, versioner would separately consider each of privatization with HCR guard versioning, privatization without HCR guard versioning, and OSR guard versioning, in that order. While that strategy was fine for correctness, it was possible to miss opportunities in cases where the loop contains an OSR guard that …
=> Implement loop versioner privatization/HCR/OSR fixed-point analysis

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
The `disableWrtBarSrcObjCheck` option is not used anymore and can be removed.
=> Remove disableWrtBarSrcObjCheck option

compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/arm/codegen/OMRLinkage.cpp, compiler/arm/codegen/OMRMemoryReference.cpp, compiler/arm/codegen/UnaryEvaluator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/p/codegen/OMRLinkage.cpp, compiler/p/codegen/OMRMemoryReference.cpp, compiler/p/codegen/PPCTableOfConstants.cpp, compiler/p/codegen/UnaryEvaluator.cpp, compiler/x/amd64/codegen/OMRMemoryReference.cpp, compiler/x/amd64/codegen/OMRMemoryReference.hpp, compiler/x/codegen/ControlFlowEvaluator.cpp, compiler/x/codegen/DataSnippet.cpp, compiler/x/codegen/HelperCallSnippet.cpp, compiler/x/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/ConstantDataSnippet.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp
These were introduced a long time ago to allow a certain change to be toggled. The change was to stop generating runtime assumptions for patching class pointers on class redefinition, and to stop generating slower but more easily patchable instruction sequences to allow for those runtime assumptions. The patching was no longer needed because class redefinition had been made in-place.
As a result, `wantToPatchClassPointer()` and `hcrPatchClassPointers` are no longer necessary. They are removed, and all use sites now behave as though `hcrPatchClassPointers` is not set and `wantToPatchClassPointer()` returns false.
=> Remove wantToPatchClassPointer() and the hcrPatchClassPointers option

compiler/x/codegen/OMRTreeEvaluator.cpp
It was discovered that NaN input values were not handled for masked versions of min/max opcodes. This change fixes that.
Signed-off-by: Bradley Wood <bradley.wood@ibm.com>
=> x86: handle NaN inputs for vmmin/vmmax

gc/base/Configuration.hpp, gc/base/GCExtensionsBase.hpp, gc/base/segregated/ConfigurationSegregated.cpp, gc/base/segregated/ConfigurationSegregated.hpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp, gc/base/standard/ConfigurationStandard.cpp, gc/base/standard/ConfigurationStandard.hpp, gc/base/standard/Scavenger.cpp, gc/base/standard/Scavenger.hpp, gc/startup/omrgcstartup.cpp
Current place of MM_Scavenger instantiation is
MM_ConfigurationGenerational::createDefaultMemorySpace(). It is relatively late in initialization path without any reason. Late creation required to have "Scavenger registration" in the classes created earlier. Moving Scavenger instantiation to
MM_ConfigurationGenerational::createGlobalCollector() makes more sense and resolves registration problem naturally. Method createGlobalCollector() is going to be renamed to createCollectors() to reflect the fact it might create not only Global, but Local collector too if necessary.
This step:
- creates ConfigurationGenerational createCollectors() and createGlobalCollector() as a wrapper
- moves MM_Scavenger::newInstance() to createCollectors()
- removes regionManager paramerer from …
=> Move Scavenger instantiation earlier

gc/base/Configuration.hpp, gc/base/GCExtensionsBase.hpp, gc/base/segregated/ConfigurationSegregated.cpp, gc/base/segregated/ConfigurationSegregated.hpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp, gc/base/standard/ConfigurationStandard.cpp, gc/base/standard/ConfigurationStandard.hpp
- remove GCExtensionsBase::registerScavenger() method
- remove createGlobalCollector() methods (wrappers)
=> Cleanup after Scavenger instantiation refactoring

compiler/il/OMRNode.cpp
In nodePrintAllFlags(), chkNodeCreatedByPRE() is used to check for the presence of the flag, but it will assert (on a debug build) whenever the flags are printed on a node for which isLoadVarDirect() is false. nodePrintAllFlags() should use the form of the query that simply returns false if the query is invalid for that node, which is isNodeCreatedByPRE().
=> Use non-asserting query to print nodeCreatedByPRE

third_party/pugixml-1.5/pugixml.cpp
This commit replaces sprintf() used in pugixml with snprintf().
=> Replace sprintf() in pugixml with snprintf()

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/ParallelDispatcher.cpp, gc/base/ParallelDispatcher.hpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp
Initial set of changes to expand the GC thread pool beyond the dispatcher initialization done at VM startup. This involves reallocating memory for the dispatcher tables, these tables store thread pointers/meta data and are sized based on the initial thread count at startup. Given the restore machine configuration, the thread pool may need to be expanded beyond the initial capacity, hence these tables must be reinited to accommodate a larger thread count.
Some things to note for unbounded expansion considering this capability is still under development:
- By default, the restore thread count is still capped based on startup conditions (i.e this capability is disabled). To enable this, a restore thread count must be explicitly set.
- Only expected to work with the standard collectors.
- …
=> Unbounded GC Thread Pool Expansion for CRIU Restore

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
* Add infrastructure to process options post restore (from a checkpoint)
* Add `_postRestoreOptionSets` field to collect options sets when `processOptionSet` is called on the global options.
* Add the method `processOptionSetPostRestore` which can be called to process options post restore. This first processes the global options (caching away the options sets into `_postRestoreOptionSets`) and then processes the options sets.
* Add the method `mergePostRestoreOptionSets` to merge the options sets in `_postRestoreOptionSets` into `_optionSets` once the former has been processed.
* Add `_numAllocatedCompilationThreads` to distinguish between usable comp threads and allocated comp threads
* When implementing Checkpoint/Restore functionality this new field allows a runtime to change the …
=> Add infrastructure to process compiler options post restore

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/MemorySubSpace.cpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp, gc/base/standard/Scavenger.cpp
- introduce virtual destroyCollectors() for Configuration symmetrical to createCollectors()
- move scavenger->kill() from MM_MemorySubSpace::tearDown() to MM_ConfigurationGenerational::destroyCollectors()
Also do some minor code clean up
- remove MM_ConfigurationGenerational::tearDown() not required any more
- remove unnecessary conversion of MM_EnvironmentBase to MM_EnvironmentStandard in _Scavenger::kill()
=> Move scavenger->kill() to ConfigurationGenerational for symmetry

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstructionKindEnum.hpp, compiler/ras/Debug.hpp
Add `ARM64Trg2MemInstruction` which takes 2 target registers for loading from memory.
=> AArch64: Add ARM64Trg2MemInstruction

compiler/z/codegen/S390GenerateInstructions.cpp, compiler/z/codegen/S390Instruction.cpp, compiler/z/codegen/S390Instruction.hpp
Some RSY type instructions can be used with immediate source field as well where long displacement may be required without memory reference for example for shift or rotate instruction where the second operand is used to provide shift amount. Currently for those instrucions it was constructing RSInstruction object where we lost the information if it contains long displacement field or not. In one case where we tried to generate RLL instruction with negative displacement, generated instruction was incorrectly encoded base register field with displacement value which was resulting in incorrect behaviour. This commit adds those necessary functions S390Instruction and handles case where RSY type instruction is generated without memory reference correctly.
Fixes: eclipse-openj9/openj9#16479
=> Add RSYInstruction generate function for immed

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstructionKindEnum.hpp, compiler/ras/Debug.hpp, fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
- Add `ARM64Src1ImmCondInstruction` and `ARM64Src2CondInstruction` to enable `ccmp` and `ccmn` instructions.
- Add a utility method to generate `cinc` instruction.
- Add BinaryEncoding unit tests for those instructions.
=> AArch64: Add instruction classes for conditional compare instructions

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/OMRInstOpCode.enum, compiler/aarch64/codegen/OpBinary.cpp, fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
This commit adds vector pairwise max/min instructions and binary encoding unit tests.
=> AArch64: Add vector pairwise max/min instructions

compiler/ilgen/OMRThunkBuilder.cpp, compiler/optimizer/OMROptimizer.cpp, jitbuilder/optimizer/JBOptimizer.cpp
Without running some DSE pass, obvious dead stores can make it all the way to code generation.
=> When skipping global DSE for a single block, still run local DSE

gc/base/standard/Scavenger.cpp
completeConcurrentCycle(env) is normally invoked to stop a CS cycle.
However, it can be assumed that there is no activity of mutator threads
in the shutdown path. So, a change to the idle state is sufficient at this
point.
=> Change state of ConcurrentScavenger in collectorShutdown path

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/ras/LimitFile.cpp
There are multiple places that call `addOptionSet`. However, post restore, `addPostRestoreOptionSet` should be called (these sets will eventually get merged into the main linked list). In order to ensure that callers of `addOptionSet` do not need to have to consider whether they need to worry about a checkpoint/restore scenario, this commit introduces a new public API called `saveOptionSet`. `addOptionSet`/`addPostRestoreOptionSet` are made protected. `saveOptionSet` will call the right method based on the value of a new static boolean field `_postRestoreProcessing`.
Additionally, the code that sets options based on `_aggressivenessLevel ` is refactored into its own method.
=> Minor Options Refactoring

gc/base/GCExtensionsBase.hpp, gc/base/SweepHeapSectioning.cpp, gc/base/SweepHeapSectioning.hpp
Reinitialize and update the sweep sectioning data, sweep chuck size and pool, to reflect the adjusted thread count for restore (for background, see https://github.com/eclipse/omr/issues/6888). This requires the chunk pool growth and utilization order to be changed, from LIFO to FIFO style. The pool now grows at the tail and is consumed starting at the head. This is necessary because the baseArray (first inited pool array) is shared with compaction. Compaction looks to the used size of the this baseArray to determine size it can use (getBackingStoreSize()). In a traditional VM run, backing store size will never be 0 (as asserted by compact). However,  if the pool continued to use LIFO style with CRIU, it could result in unused baseArray and backing store size of 0. Specifically, when a …
=> GC Reinitialize Sweep For Restore (CRIU)

gc/base/standard/Scavenger.cpp
Main GC Thread can be destroyed first to prevent potential side effect
=> Change order in MM_Scavenger::collectorShutdown()

compiler/p/codegen/GenerateInstructions.cpp
This fixes the incorrect results which was generated with int2float/float2int conversion with NaNs on Power on JDK20 new testcases. Issue was with `xscvspdp` instruction that converts SNaN(src) to QNaN which sets the 9th bit set in the converted results. Using `xscvspdpn` generates right results.
Closes #https://github.com/eclipse-openj9/openj9/issues/16660
Signed-off-by: Bhavani SN bhavani.sn@ibm.com
=> Fix issue with Binary16NaN conversion on Power

compiler/optimizer/OMRSimplifier.cpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/OMRSimplifierTable.enum, compiler/optimizer/SimplifierHandlers.hpp, compiler/optimizer/SimplifierTable.enum
Allows projects to map a different/project-specific simplifier handler function for common IL opcodes (i.e., for opcodes that are defined in OMR, not just at the project level).
=> Move SimplifierTable opcode macros to table instead of enum file

fvtest/threadextendedtest/threadCpuTimeTest.cpp
This commit disables TestOtherThreadCputime on AArch64 macOS temporarily.
=> Temporarily disable TestOtherThreadCputime on AArch64 macOS

compiler/optimizer/OMRValuePropagation.cpp
The compile time instanceOf checks in BlockVersioner were backwards resulting in a pass rather then a fail in some cases.
=> Fix the order of the instanceOf class parameters in block versioner

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements arraycmp evaluator.
It implements two variants. One of them returns the length of the identical data from the beginning of the arrays.
The other returns 2/0/1 when the first array is greater than/equal to/less than the second array.
The main loop reads a 16-byte chunk from the both array in a single interation. It uses ldp instruction to read 16-byte data into two 64-bit registers. Then, it compares each 64-bit registers to find mismatch. If any mismatch is found in 16-byte chunks, the bit position of the first mismatch is searched by clz instruction for the variant returning the length. If no mismatch is found in 16-byte chunks and there is still remaining data to be compared (which is smaller than 16 bytes),
the secondary loop, which reads a single byte in each …
=> AArch64: Implement arraycmp evaluator

compiler/control/OMROptions.cpp
`OMR::Options::_hasLogFile` is a static that is used by `OMR::Options::requiresDebugObject()` when determining whether a debug object is needed or not. It is set in `OMR::Options::jitPostProcess`; however, optionsets don't get processed till `OMR::Options::latePostProcess`. Therefore, this PR ensures that `_logFile` gets updated when a log file is specified in an option set.
=> Ensure _hasLogFile is set when option set specifies a log file

gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/Scavenger.cpp
Fix a couple of spots where we clear Tenure TLH remainder pointers, but
we miss to clear a corresponding LOA flag.
=> Clear LOA remainder flag

fvtest/compilertest/CMakeLists.txt, jitbuilder/CMakeLists.txt
This commit disables OMR_WARNINGS_AS_ERRORS on macOS for some
components.
=> Disable OMR_WARNINGS_AS_ERRORS on macOS

fvtest/compilertriltest/ArrayTest.cpp, fvtest/compilertriltest/CMakeLists.txt
This suite contains tests for arraycmp evaluator.
One of the tests verifies that arraycmp evaluator works correctly on arrays with the same data.
The other verifies that it properly returns the offset of the mismatched element or expected value for greater than/less than cases when the passed arrays are not equal.
=> Add ArrayTest suite to compilertriltest

gc/base/GCExtensionsBase.hpp, gc/include/omrmm.hdf, gc/verbose/VerboseHandlerOutput.cpp, gc/verbose/VerboseHandlerOutput.hpp, gc/verbose/VerboseManager.hpp, gc/verbose/VerboseManagerBase.hpp, gc/verbose/VerboseWriter.cpp, gc/verbose/VerboseWriterFileLogging.cpp, gc/verbose/VerboseWriterFileLoggingBuffered.cpp, gc/verbose/VerboseWriterFileLoggingSynchronous.cpp
Verbose GC API changes to support CRIU Verbose GC logging: https://github.com/eclipse-openj9/openj9/pull/16845
- Introduced J9HOOK_MM_OMR_REINITIALIZED event. This is required by the verbose handler to print init details upon snapshot restore.
- Added missing tearDown call to MM_VerboseWriterFileLogging::reconfigure to free memory before a reinit.
- GC Extensions Base class reinitializationInProgress introduced, this is to be implemented by downstream J9 derived class. 
- VerboseManagerBase fileOpenMode query introduced, this is to be implemented by downstream J9 derived class.
- Verbose file writers now query the verbose manager (fileOpenMode) to determine if an opened file should be appended to.
Related: https://github.com/eclipse/omr/issues/6888#issuecomment-1458810193
Signed-off-by: …
=> CRIU Verbose Logging Reinit/Reconfig for Restore

compiler/control/OMROptions.hpp
The `_suppressEA` field in `OMR::Options` was not initialized to `NULL` in the `OMR::Options::init` method, which means it could contain garbage that will cause intermittent crashes if the field is dereferenced.
Fixes eclipse-openj9/openj9#16834
=> Ensure _suppressEA option field is initialized to NULL

port/unix_include/omrsock.h
_OE_SOCKETS is not compatible with LP64. OMR_OS_ZOS was not defined
previously. So, _OE_SOCKETS was never defined in the builds.
=> Remove definition of _OE_SOCKETS

compiler/p/codegen/OMRCodeGenerator.cpp
Enable vxor, vor, and vand for all integer vector types (byte, short, int, long), which will allow the vectorization of various integer-only vector operations (such as logical opersations) to occur.
=> Enable vxor, vor, and vand IL opcodes on PPC

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/il/OMRResolvedMethodSymbol.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/OMROptimizations.enum, compiler/optimizer/OMROptimizer.cpp, compiler/optimizer/OMROptimizer.hpp
This commit implements the OMR infrastructure needed for a new optimization pass called `catchBlockProfiler`, which will be used by the exception directed optimization (EDO) mechanism. This optimization will be implemented in OpenJ9 upstream project. Three controlling options are introduced:
-Xjit:edoRecompSizeThreshold=
-Xjit:edoRecompSizeThresholdInStartupMode=
-Xjit:catchBlockCounterThreshold=
There is another option, -Xjit:enableOldEDO that can be used to revert to the old way of doing EDO.
Yet, another option, -Xjit:traceCatchBlockProfiler, allows tracing of the new optimization.
=> Infra for new optimization `catchBlockProfiler`

port/win32/omrsl.c
Prioritize searching for dll dependencies in the same folder as the dll.
=> Modify DLL search order

compiler/il/VectorOperations.enum
- since vector compare opcodes take vectors and return a mask (with possibly different element type) they should be two-type opcodes
- mask element type is Int32 for Float vectors and Int64 for Double vectors
=> Make vector compare opcodes two-type vector opcodes

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/optimizer/OMRSimplifierHandlers.cpp
This commit adds arrayset evaluator to aarch64 codegen.
- For variable length arrays, the main loop writes a 64-byte chunk to the array in a single interation. It uses stp instructions which store 32-byte data using two 128-bit vector registers. If the length of the array is less than 96 bytes, then the secondary loop, which writes 16-byte data in each iteration, is executed. If the length of the array is less than 16 bytes, then the loop which writes a single byte per iteration is executed.
- For constant length arrays, if the length is greater than or equal to 32 bytes, stp instructions with vector registers are used. If the length is larger than certain threshold, then the loop which stores 256 bytes in a single iteration is executed.
=> AArch64: Implement arrayset evaluator

compiler/compile/OMRNonHelperSymbols.enum, compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/il/Aliases.cpp, compiler/ras/Debug.cpp
Add non-helper for array element load and store
The downstream usage of these non-helper calls are in https://github.com/eclipse-openj9/openj9/pull/17072
=> Add non-helper for array element load and store

compiler/optimizer/CompactLocals.cpp, compiler/optimizer/DataFlowAnalysis.hpp, compiler/optimizer/GlobalRegisterAllocator.cpp, compiler/optimizer/LiveOnAllPaths.cpp, compiler/optimizer/LiveVariableInformation.cpp, compiler/optimizer/Liveness.cpp, compiler/optimizer/OSRDefAnalysis.cpp, compiler/optimizer/SinkStores.cpp
Allow downstream projects to extend TR_LiveVariableInformation and TR_Liveness through project-level derived classes by splitting the analysis each performs out of its constructor into a separate function that can be called after all constructors have executed, and by making members of these classes protected.
=> Split analysis from constructor of LiveVariableInfo and Liveness

compiler/optimizer/OMRSimplifier.cpp, compiler/optimizer/OMRSimplifier.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/OMRSimplifierHelpers.cpp, compiler/optimizer/OMRSimplifierHelpers.hpp
The first commit moves some of the static and inline functions in OMRSimplifierHandlers.cpp to the helpers files so that they can be consumed in downstream project extensions by including the OMRSimplifierHelpers header. The second introduces the preSimplification() and postSimplification() methods to the Simplifier class in order to allow downstream projects to add project-specific specializations to individual Simplifier handlers.
=> Allow Simplifier extension for downstream projects

gc/base/MemoryPool.hpp, gc/base/MemoryPoolSplitAddressOrderedList.cpp, gc/base/MemoryPoolSplitAddressOrderedList.hpp, gc/base/MemoryPoolSplitAddressOrderedListBase.cpp, gc/base/MemoryPoolSplitAddressOrderedListBase.hpp
For background, see https://github.com/eclipse/omr/issues/6888
MemoryPoolSplitAddressOrderedList must adjust its free lists to optimize for the GC thread count set at restore time. This is achieved  by pre-allocating all the heap free lists related arrays at VM startup. The number of entries allocated is _maximumFreeListSize, which is set to 8 by default, this allows the pool to be optimized for up to 64 threads (default max gc thread count). Only _heapFreeListCount number of entries are used, hence the lists may grow from _heapFreeListCount to _maximumFreeListSize at restore time. The heap lists will not shrink in case the GC thread count at restore is less than startup thread count.
=> Introduce CRIU reinitializeForRestore For Memory Pool

gc/base/Configuration.hpp, gc/base/ParallelDispatcher.cpp, gc/base/ParallelDispatcher.hpp, gc/base/standard/ConfigurationGenerational.cpp, gc/base/standard/ConfigurationGenerational.hpp
The goal is to remove the following APIs from configuration:
- reinitializeGCThreadCountForRestore
- Currently, this method has 2 distinct responsibilities, to set the GC thread count and expand the thread pool. Its more appropriate to set the thread count earlier in the GC restore phase (in j9gc_reinitializeDefaults) and then expand the thread pool directly through the dispatcher. 
- adjustGCThreadCountForCheckpoint
- This is just an indirection to dispatcher contractThreadPool, the dispatcher should be invoked directly from top level CRIU GC helper.
A single reinitializeForRestore CRIU API is more consistent with other component implementations, this will be used in the future to do specific configuration reinit (e.g  memory pools). 
Follow up changes will remove these 2 APIs after …
=> Refactor Configuration CRIU APIs

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
Add option `disableRecognizeCurrentThread` to disable inlining `Thread.currentThread()`
=> Add options to disable inlining Thread.currentThread

compiler/optimizer/VPHandlers.cpp
The Value Propagation handlers for `newarray` and `anewarray` assume that if a size constraint exists for the array length, and it's not definitely negative and definitely does not exceed the maximum possible array size, the operation must not throw an Exception or Error.  In such cases, they set the `AllocationCanBeRemoved` flag for the node, which allows Dead Trees Elimination to delete the node later if the array is not used.
However, even if the length is not definitely negative or not definitely too great, does not mean that it's definitely non-negative nor definitely not too great - it might have a range that includes "reasonable" non-negative values, but also includes values that are negative or too great.
Fixed this by only setting the `AllocationCanBeRemoved` flag if the lower …
=> Consider array size that might be outside range of valid values

compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/arm/codegen/OMRMemoryReference.cpp, compiler/codegen/Relocation.cpp, compiler/il/OMRSymbol.hpp, compiler/p/codegen/OMRMemoryReference.cpp, compiler/runtime/Runtime.hpp, compiler/x/amd64/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRMemoryReference.cpp, compiler/z/codegen/ConstantDataSnippet.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp
These patches add the necessary support for two new relocations, `TR_CatchBlockCounter` and `TR_StartPC`, to allow EDO to be enabled while compiling AOT code.
- The `TR_CatchBlockCounter` relocation is responsible for relocating the address of the new `_catchBlockCounter` in the `TR_PersistentMethodInfo` (see https://github.com/eclipse-openj9/openj9/pull/16854, which has the new EDO implementation).
- The `TR_StartPC` relocation is responsible for relocating the address of the `startPC` of the method currently being compiled. Although from the documentation it might seem like the `TR_AbsoluteMethodAddress` could do this, it doesn't have the necessary support in openj9 for power; if you look at how the relocation is applied on that platform, you can see that the `loadAddress` method …
=> Infrastructure for enabling EDO with AOT  

gc/base/standard/ConfigurationGenerational.cpp
MM_ConfigurationGenerational is using the wrong base class implementation of reinitializeForRestore. It should invoke MM_ConfigurationStandard rather than MM_Configuration.
=> Fix MM_ConfigurationGenerational reinitializeForRestore

compiler/x/codegen/OMRCodeGenerator.cpp
Opcodes were inserted into the switch table
which checks for platform support of vector
opcodes. This broke the intentional fallthrough
logic for vector abs. This PR fixes the logic
and adds a comment to explain.
Fixes: #6968
=> x86: Fix vabs support test

compiler/optimizer/GeneralLoopUnroller.cpp
Otherwise, it's possible for loops that can't actually be unrolled to use up budget and prevent unrolling in other loops. The two overloads of `TR_LoopUnroller::unroll()` both already indicate whether unrolling was successful, but that result was ignored.
Also trace when GLU skips a loop for being too expensive to unroll.
=> Have GLU consume budget only for successfully unrolled loops

compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/LoopVersioner.hpp
Loop versioner has been versioning virtual guards with merged HCR or OSR guards without taking the merged guards into account.
For example, consider a nonoverridden guard with a merged HCR guard. If the receiver is invariant, then it would be versioned, and the merged HCR guard would effectively be versioned along with it even if HCR guard versioning is not supposed to be possible in the loop, i.e. even if the hot loop will still have HCR invalidation points in it after versioning. So if the protected method were redefined during execution of the resulting hot loop, the loop would continue to run the old definition until it exited.
With this commit, virtual guards with merged HCR guards will now be versioned only when HCR guard versioning is possible, and those with merged OSR guards will …
=> Version guards with merged HCR/OSR guards only when possible

gc/base/standard/CopyScanCacheList.cpp, gc/base/standard/CopyScanCacheList.hpp, gc/base/standard/Scavenger.cpp, gc/base/standard/Scavenger.hpp
Scavenger cache lists must be reinitialized during restore (CRIU) according to the new GC thread count. Specifically, when the thread count is increased, it is necessary to divide the CopyScanCacheLists into smaller sublists. This is required to reduce contention on the cache lists (_scavengeCacheFreeList and
_scavengeCacheScanList) and ultimately improve GC performance for the restore environment. 
The following changes have been made:
- Reinit each inited CopyScanCacheList (2 in total, owned by Scavenger)
- Introduced reinitializeForRestore for Scavenger
- Introduced reinitializeForRestore for CopyScanCacheList
- CopyScanCacheList must allocate a new array of sublists, copy over old sublists and init new sublists
For background, see https://github.com/eclipse/omr/issues/6888 (Compensate …
=> GC CRIU: Reinit Scavenger Caches (Split CopyScanCacheList)

compiler/control/CompilationStrategy.hpp, compiler/control/OMRCompilationStrategy.cpp, compiler/control/OMRCompilationStrategy.hpp
Issue: #6755 - A few files got the old URLs via some refactoring.
=> Reference openjdk.org instead of openjdk.java.net

compiler/x/amd64/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRMemoryReference.hpp
See my comments on the issue [here](https://github.com/eclipse-openj9/openj9/issues/15363#issuecomment-1481820466).
Fixes eclipse-openj9/openj9#15363
=> Fix Large VFP-relative memory-references

compiler/aarch64/codegen/FPTreeEvaluator.cpp, compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/aarch64/codegen/UnaryEvaluator.cpp
Validate immediate offset of memory references so that the alignment requirement of instructions is satisfied.
=> AArch64: Validate immediate offset of memory references

compiler/il/OMRSymbol.cpp, compiler/il/OMRSymbol.hpp, compiler/optimizer/VPHandlers.cpp, compiler/ras/Debug.cpp
...and consult it when constraining `aloadi` in VP.
With this declared class (once it is populated appropriately) VP can determine the type of the result of `aloadi` of fabricated field shadows.
We don't store signatures, but rather get them based on the owning method and the constant pool index, so in particular after fabricating a field shadow we lose track of the signature. Furthermore, even if we had a signature in that case, we wouldn't necessarily have any owning method that would be appropriate to use for looking up the class by name.
While creating a fabricated field shadow, however, the compiler will have access to the definition of the containing type, so it will be able to look up the correct class and remember it.
The `aloadi` VP handler now ignores the signature in favour of …
=> Add declared class to Symbol, like a signature but as a class pointer

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/ARM64HelperCallSnippet.cpp, compiler/aarch64/codegen/ConstantDataSnippet.cpp, compiler/arm/codegen/ARMBinaryEncoding.cpp, compiler/arm/codegen/ConstantDataSnippet.cpp, compiler/codegen/Relocation.cpp, compiler/codegen/Relocation.hpp, compiler/p/codegen/OMRConstantDataSnippet.cpp, compiler/p/codegen/PPCBinaryEncoding.cpp, compiler/ras/DebugCounter.cpp, compiler/riscv/codegen/RVHelperCallSnippet.cpp, compiler/x/amd64/codegen/OMRMemoryReference.cpp, compiler/x/codegen/ControlFlowEvaluator.cpp, compiler/x/codegen/DataSnippet.cpp, compiler/x/codegen/OMRMemoryReference.cpp, compiler/x/codegen/X86BinaryEncoding.cpp, compiler/z/codegen/ConstantDataSnippet.cpp, compiler/z/codegen/S390Instruction.cpp
Provide a factory method for external relocations to simplify the code and reduce code footprint slightly.  Replace all TR::ExternalRelocation allocations throughout with the factory method.
Take this opportunity to clean up the wildly inconsistent source formatting for all these allocation sites as well.
=> Create and use factory method for ExternalRelocations

port/unix/omrsysinfo.c
This commit fixes a subtle bug in cgroup2 initialization, namely in `populateCgroupEntryListV2()`.
Consider a system with only `memory` control group enabled. Then the `cgroup.controllers` for the process's cgroup2 would contain string `memory` followed by newline (`\n`). See Linux kernel source, file `kernel/cgroup/cgroup.c`, function `cgroup_print_ss_mask()` [1].
The code that iterates over cgroups listed only considers space as a separator:
separator = strchr(cursor, ' ');
if (NULL != separator) {
*separator = '\0';
}
So the last (an in our example also the first) cgroup name (pointed to by `cursor`) contains the `\n` as the end, therefore the `strcmp` comparison fails:
...
&& (0 == strcmp(cursor, supportedSubsystems[i].name))
...
(since we're comparing `'memory\n'` with just …
=> Fix Linux cgroup2 initialization

include_core/omrutil.h, port/unix/omrmmap.c
When `OMRPORT_MMAP_FLAG_ZOS_64BIT` is passed in, we set flag
`__MAP_64` on z/OS version 2.4 and up.
Related to https://github.com/eclipse-openj9/openj9/pull/17073
=> Always define __MAP_64

compiler/codegen/OMRCodeGenerator.hpp
Removes definition of `getOptimizationPhaseIsComplete()` in `compiler/codegen/OMRCodeGenerator.hpp`, since its uses in `omr/compiler/optimizer/OMRTransformUtil.cpp` and `omr/compiler/z/codegen/OMRCodeGenPhase.cpp` have already been removed.
Closes: #5402
=> Remove definition of getOptimizationPhaseIsComplete()

compiler/compile/OMRAliasBuilder.cpp, compiler/env/OMRClassEnv.hpp, compiler/il/Aliases.cpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/VPHandlers.cpp, compiler/optimizer/ValuePropagationCommon.cpp
Restore e69fc2b6d06bb13926bd6ccf1290a76357563142, which was reverted in c2ccbcae4ea8552bf7c64789ef252996774252da because it was causing failures in OpenJ9's OMR acceptance build (eclipse-openj9/openj9#17337).
It seems that the problem was that e69fc2b6d06bb13926bd6ccf1290a76357563142 could inadvertently change a volatile access into a non-volatile one. I've included a fix in this PR. I see similar sanity.openjdk failures in personal builds without the fix, and the failures disappear with the fix.
- Revert c2ccbcae4ea8552bf7c64789ef252996774252da
- Respect volatile when refining unsafe shadow *(aforementioned fix)*
- Allow disabling unsafe shadow refinement by environment variable
- Fix typo in performTransformation() messages in refineUnsafeAccess()
=> Restore VP unsafe shadow refinement

compiler/x/codegen/DataSnippet.hpp, compiler/x/codegen/OMRX86Instruction.hpp
* _reloKind in X86MemImmInstruction
* _isClassAddress in DataSnippet
* Remove unnecessary `virtual` from setClassAddress()
=> Add missing getter/setters

compiler/aarch64/codegen/ConstantDataSnippet.cpp, compiler/il/OMRStaticSymbol.hpp, compiler/z/codegen/ConstantDataSnippet.cpp, fvtest/porttest/omrvmemTest.cpp, jitbuilder/lljb/include/lljb/Compiler.hpp, port/ztpf/omrosdump_helpers.c
Fix a few occurrences of "address" being misspelled as "adress"
Closes: #6979
=> Fix various misspellings of "address"

compiler/il/OMRBlock.cpp, compiler/il/OMRBlock.hpp, compiler/ilgen/ByteCodeIterator.hpp, compiler/infra/OMRCfg.cpp
A user experienced a compile time crash in setHandlerInfoWithOutBCInfo() because a bytecode index to a catch handler is above the 2^16th limit that normally applies for Java methods. This limit can be exceeded in rare cases after the JVM expands the method size on load. A good example of this would be when the VM inlines a "jsr" bytecode. Because the handler index is larger then 2^16th the offset is truncated when it is placed into the 16bit integer that we were using to record the offset. This fix will expand the size of variables used to hold bytecode offsets to be 32bits.
=> Expand bytecode offset variables to 32bit

buildenv/docker/riscv64/debian11/Dockerfile, buildenv/jenkins/omrbuild.groovy
A recent loss of the debian 10 system that was used for riscv compiles pushed me into moving this to a container.  Due so memory consumption issues @janvrany has an open PR to address (https://github.com/eclipse/omr/pull/6912), the hosts currently require ~10gb ram.  Once #6912 has been reviewed/changed/merged...the hosts for riscv cross-compiles can be reduced in ram requirement.
Also needs a dependent jiro change. https://github.com/eclipse-cbi/jiro/pull/277
* remove deb10-x64-1 as its dead
* add label "compile:riscv64:cross" to ub20-x64-omr7 and ub20-x64-omr9
** docker container also has a requirement on cgroup.v2 configuration on the host
fyi @babsingh @janvrany @AdamBrousseau
=> Migrate riscv cross-compiles to docker container

compiler/optimizer/OMRSimplifierHandlers.cpp
When simplifying a select of a const 0/1 and a boolean expression, the selectSimplifier currently only checks for whether there is a const initially, and then for whether that const's value is either 0 or something else. This allows consts that are not either 0 or 1 to be used incorrectly in this simplification.
=> Check const values to ensure correct pattern in selectSimplifier

compiler/optimizer/Inliner.cpp, compiler/optimizer/Inliner.hpp
This commit removes callMustBeInlinedRegardlessOfSize and all its uses since it has no overriding implementations.
Closes: #6148
=> Remove callMustBeInlinedRegardlessOfSize

compiler/z/codegen/OMRTreeEvaluator.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/17465.
=> Z: Use IILF for 31-bit inline address constants

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/MemoryPoolSplitAddressOrderedList.cpp, gc/base/PacketList.cpp, gc/base/standard/CopyScanCacheList.cpp
Extend MM_Configuration::initializeGCParameters for restore reinit of GC parameters (split list amounts).
=> Rework Config initializeGCParameters for reinit

compiler/optimizer/OMRSimplifierHandlers.cpp
When a select of two 0/1 constants is simplified to the reverse of its condition node, in the case where the select has a reference count > 1 and the condition first child has a reference count of only 1, the second reference to the select node will be simplified incorrectly to a twice-reversed condition (please see issue #7006 for details). Recreates the select node in order to preserve the simplification done to it for future references, reducing repeated simplification of a previously commoned node and preventing the error in the case described above.
=> Recreate simplified select node

compiler/aarch64/codegen/BinaryEvaluator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp
This commit implements evaluators for vector shift and rotate opcodes. 
Evaluators for the masked version of those opcodes are also added.
=> AArch64: Implement vector shift and rotate evaluators

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/compile/TLSCompilationManager.cpp, compiler/control/CompilationController.cpp, compiler/infra/ThreadLocal.hpp
Capitalize `tlsFree` and sibling macros in the form `TR_TLS_...`
Closes: #6050
=> Rename TLS macros to satisfy the uppercase convention

compiler/aarch64/codegen/ARM64SystemLinkage.cpp, compiler/arm/codegen/ARMSystemLinkage.cpp, compiler/arm/codegen/ARMSystemLinkage.hpp, compiler/arm/codegen/OMRCodeGenerator.hpp, compiler/arm/codegen/OMRLinkage.cpp, compiler/codegen/CodeGenGC.cpp, compiler/codegen/GCStackMap.hpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/codegen/OMRRegisterPair.cpp, compiler/codegen/OMRRegisterPair.hpp, compiler/codegen/Relocation.cpp, compiler/codegen/Relocation.hpp, compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/p/codegen/PPCInstruction.hpp, compiler/riscv/codegen/RVInstruction.hpp, compiler/riscv/codegen/RVSystemLinkage.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/X86FPConversionSnippet.hpp, compiler/z/codegen/OMRLinkage.cpp, compiler/z/codegen/OMRLinkage.hpp, compiler/z/codegen/SystemLinkageLinux.cpp, compiler/z/codegen/SystemLinkagezOS.cpp
Make naming of variables holding the `TR::CodeGenerator` object consistent by renaming variables named `codeGen` to `cg`
Closes: #5594
=> Rename code generator variables

compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
Remove getNanoTimeTemp() from OMR as the final step of migrating it from OMR to OpenJ9
Closes: #5133
=> Remove getNanoTimeTemp() from OMR

gc/base/MemorySubSpaceUniSpace.cpp
Use floats to calculate more accurate result.
Fixes https://github.com/eclipse-openj9/openj9/issues/17534
=> Improvement for calculation of heuristic multipliers

compiler/optimizer/LoopVersioner.cpp
Fix assertion failure in isNodeCreatedByPRE() while PROD_WITH_ASSUMES is enabled by checking its condition first and only calling isNodeCreatedByPRE() if the condition passes.
Issue: [openj9 #17446](https://github.com/eclipse-openj9/openj9/issues/17446)
=> Guard isNodeCreatedByPRE() with canChkNodeCreatedByPRE()

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds vnolz, vmnolz, vnotz and vmnotz evaluators to AArch64 codegen.
=> AArch64: Implement vector number of leading/trailing zeroes evaluators

compiler/il/OMRAutomaticSymbol.cpp, compiler/optimizer/LocalReordering.cpp
This pull request includes changes to consider the possibility that an object allocation is being performed by way of a `TR::newvalue` operation.  One is in the context of `LocalReordering`, which already prevented reordering of other kinds of object allocations.  The second is in the context of `OMR::AutomaticSymbol::createLocalObject` which is used in the process of stack allocating short-lived objects that do not need to be allocated on the heap, allowing downstream projects to stack allocate objects that were created by a `TR::newvalue` operation.
=> Consider possibility of TR::newvalue operation in some optimizations

compiler/aarch64/codegen/OMRSnippetDelegate.cpp, compiler/aarch64/codegen/OMRSnippetDelegate.hpp, compiler/arm/codegen/OMRSnippetDelegate.cpp, compiler/arm/codegen/OMRSnippetDelegate.hpp, compiler/codegen/OMRSnippetDelegate.hpp, compiler/codegen/SnippetDelegate.hpp, compiler/p/codegen/OMRSnippetDelegate.cpp, compiler/p/codegen/OMRSnippetDelegate.hpp, compiler/riscv/codegen/OMRSnippetDelegate.cpp, compiler/riscv/codegen/OMRSnippetDelegate.hpp, compiler/x/codegen/OMRSnippetDelegate.cpp, compiler/x/codegen/OMRSnippetDelegate.hpp, compiler/z/codegen/OMRSnippetDelegate.cpp, compiler/z/codegen/OMRSnippetDelegate.hpp
Fix new files added while #6996 was in flight.
Fixes: #6995.
=> Correct SPDX license identifiers (cont'd)

port/unix/omrtime.c
This commit changes the implementation of omrtime_hires_clock() for Linux.
=> Linux: Use clock_gettime(CLOCK_MONOTONIC_RAW) for omrtime_hires_clock()

port/linuxppc64/omrtime.c
This commit changes the implementation of omrtime_hires_clock() for Linux PPC64, replacing the call to gettimeofday() by clock_gettime().
=> Linux PPC64: Use clock_gettime() for omrtime_hires_clock()

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit adds vector bitswap and byteswap evaluators to AArch64 codegen.
=> AArch64: Implement vector bitswap and byteswap evaluators

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/env/VerboseLog.hpp, compiler/optimizer/CMakeLists.txt, compiler/optimizer/abstractinterpreter/IDT.cpp, compiler/optimizer/abstractinterpreter/IDT.hpp, compiler/optimizer/abstractinterpreter/IDTNode.cpp, compiler/optimizer/abstractinterpreter/IDTNode.hpp, compiler/optimizer/abstractinterpreter/InliningMethodSummary.cpp, compiler/optimizer/abstractinterpreter/InliningMethodSummary.hpp
Issue: https://github.com/eclipse/omr/issues/5488
=> BenefitInliner phase 2/3 Classes for building the IDT.

compiler/env/VerboseLog.cpp
This pull request is to fix eclipse-openj9/openj9#17694 by adding the corresponding string of `TR_Vlog_BI` to `TR_VerboseLog::_vlogTable`.
=> Fix eclipse-openj9/openj9#17694

compiler/env/VerboseLog.cpp, compiler/env/VerboseLog.hpp
If either of `TR_VlogTag` or `_vlogTable` is modified to add or remove an element without making the corresponding change in the other, this will cause a build error.
=> Check that _vlogTable size matches TR_VlogTag with static_assert()

compiler/x/codegen/BinaryEvaluator.cpp
Fixes: eclipse-openj9/openj9#17462
=> x86: Clobber shift of constant 0

compiler/optimizer/OMRSimplifierHandlers.cpp
Simplifier detects the following pattern and rewrites it:
ldiv                                i2l
i2l                                 idiv
<dividend>          ==>             <dividend>
i2l                                   <divisor>
<divisor>
But this is correct only if the resulting `idiv` will never overflow. The original tree always produces the true mathematical result.
To rule out overflow of `idiv`, simplifier now requires that at least one of the operands be nonnegative, since signed division overflows only when dividing the minimum signed value by -1.
=> Prevent ldiv/i2l -> i2l/idiv simplification when idiv could overflow

compiler/p/codegen/BinaryEvaluator.cpp, compiler/p/codegen/PPCInstruction.cpp
Disabling the modulo instructions due to the performance issues.
Signed-off by: bhavani.sn@ibm.com
=> Disable Integer modulo instruction on Power

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit implements `mmAnyTrue` and `mmAllTrue` evaluators on AArch64 codegen.
=> AArch64: Implement mmAnyTrue and mmAllTrue evaluators

gc/base/standard/CopyScanCacheList.cpp
Simplify the logic where we try to resize Copy Scan Cache pool at the end of Scavenge cycle, after we overflowed it and fullfilled it from Java Heap.
This overflow is extremly unlikely, and if does occur it means native memory is depleted and some other problems will soon occur anyway, so trying hard to preemtpively take that memory for our pool is probably just futile.
On the other side, currently we will try to resize at the end of Scavenge, but assert since the increment was previously set to 0, when we artifically set the limit of this pool (with an fvt option). We already have means of preventing further pool growth during GC (from initial growth) from native heap beyond the limit (by recognizing fvt option was set), and we don't even need to set increment to 0.
=> Do not resize Copy Scan Cache pool after overflow

gc/base/standard/Scavenger.cpp
The omrtime_current_time_millis() uses UNIX gettimeofday() function,
and is therefore non-monotonic and error-prone.
We turn to use omrtime_hires_clock() function call
whenever we need the time to be monotonic.
Issue: https://github.com/eclipse/omr/issues/7051
=> Use omrtime_hires_clock() for monotonic time when necessary in gc

port/linuxppc64/omrtime.c, port/unix/omrtime.c
Recently, gettimeofday was replaced with
clock_gettime(CLOCK_MONOTONIC_RAW) in omrtime_hires_clock.
This causes a 2-3% regression in startup time.
vDSO support for clock_gettime(CLOCK_MONOTONIC_RAW) was added in Linux
kernel version 5.3: https://bugzilla.kernel.org/show_bug.cgi?id=198961.
The aforementioned regression is seen on Linux kernel versions < 5.3.
Replacing CLOCK_MONOTONIC_RAW with CLOCK_MONOTONIC since it has vDSO
support for older Linux kernel versions, and it also resolves the above
regression in startup time.
Related:
- #7041
- #7044
- https://github.ibm.com/runtimes/javanext/issues/388
- https://github.ibm.com/runtimes/javanext/issues/389
Also, renamed J9TIME_NANO_CLOCK to OMRTIME_NANO_CLOCK.
=> Use clock_gettime(CLOCK_MONOTONIC) in omrtime_hires_clock

fvtest/threadextendedtest/threadCpuTimeTest.cpp
This commit enables TestOtherThreadCputime on AArch64 macOS again, which was temporarily disabled by #6903.
=> Enable TestOtherThreadCputime on AArch64 macOS again

fvtest/porttest/si.cpp
This commit changes the limit value for setting
OMRPORT_RESOURCE_ADDRESS_SPACE in
sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE for AArch64 macOS.
=> AArch64 macOS: Change the limit value for ADDRESS_SPACE

include_core/AtomicSupport.hpp
This commit implements __yield() for AArch64 in AtomicSupport.hpp.
=> AArch64: Implement __yield()

fvtest/porttest/si.cpp
This commit changes the limit value for setting
OMRPORT_RESOURCE_ADDRESS_SPACE in
sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE for macOS.
=> x86-64 macOS: Change the limit value for ADDRESS_SPACE

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp, compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
The existing `loadAddressConstant` function on AArch64 determines whether it should generate relocatable code by the answer returned by `compileRelocatableCode()` query. However, it does not return the correct answer under a remote compilation.
To support remote compilations, this commit adds an overloaded version of `loadAddressConstant` with a boolean parameter that allows the caller of the api to determine if the relocatable code is generated.
=> AArch64: Add a parameter for generating relocatable code to loadAddressConstant

compiler/aarch64/codegen/OMRMemoryReference.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRMemoryReference.cpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/codegen/Relocation.cpp, compiler/codegen/Relocation.hpp, compiler/il/OMRSymbol.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRMemoryReference.cpp, compiler/runtime/Runtime.hpp, compiler/x/amd64/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRMemoryReference.cpp, compiler/x/codegen/OMRX86Instruction.cpp, compiler/x/codegen/X86BinaryEncoding.cpp, compiler/z/codegen/ConstantDataSnippet.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp
Enter/exit hooks can be guarded by a runtime test to determine whether or not the hook should be invoked. This PR adds relocation support to allow Relocatable Compilations to generate code that can make use of this runtime test.
This PR also includes some refactoring to facilitate the use of a larger set of relocation flags. This is needed to ensure that inlined methods can be validated in case a previously compiled relocatable compiled method cannot support enter/exit hooks.
Should be merged in tandem with https://github.com/eclipse-openj9/openj9/pull/17621
=> Add relocation infrastructure to make enter/exit tracing consistent with default compilation

compiler/runtime/OMRCodeCacheManager.cpp, compiler/runtime/OMRCodeCacheManager.hpp
In `OMR::CodeCacheManager::carveCodeCacheSpaceFromRepository(size_t segmentSize..` calculate available physical memory and perform new code cache allocation if we have the safe amount returned for the memory. 
Depends on OpenJ9 change: Handle code cache allocation when available memory becomes low [[17620](https://github.com/eclipse-openj9/openj9/pull/17620)]
=> Handle code cache allocation for low physical memory

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
This commit adds TR_MethodCallAddress to an instruction generated for method calls.
=> AArch64: Add TR_MethodCallAddress relocation to direct call instructions

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp, compiler/aarch64/codegen/OMRCodeGenerator.hpp
This commit adds `callUsesHelperImplementation` query to code generator. It updates `TR::ARM64ImmSymInstruction::generateBinaryEncoding()` function to add a `TR_Helper` relocation to the branch instruction if that query returns true for the symbol.
=> AArch64: Add callUsesHelperImplementation query to code generator

gc/base/standard/ParallelScavengeTask.cpp, gc/stats/ScavengerStats.hpp
Comparing time intervals measured on different cores might be slightly different. Despite clocks are monotonic they might be out of sync slightly. As a result measuring of intervals with delta smaller than time unit might be off slightly. Such difference can cause false triggering of assertion.
Removing assertions and adjusting time calculation to prevent overrun of unsigned variable.
=> Remove incorrect assertions and adjust stall time calculation

compiler/codegen/Relocation.cpp, compiler/codegen/Relocation.hpp, compiler/p/codegen/OMRCodeGenerator.cpp
The initialization of the `TR::ExternalOrderedPair32BitRelocation` object used for `TR_MethodEnterExitHookAddress` had a couple of issues:
1. It was missing the secondInstruction
2. It assumed that the constructor of `TR::ExternalOrderedPair32BitRelocation` took in two target addrs
this PR fixes both issues by adding the second instruction, as well as adding a new constructor to take in two target addresses.
Fixes https://github.com/eclipse-openj9/openj9/issues/17882
=> Fix Crashes in 32-bit PPC due to incorrect relocation initialization

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
- the option is needed in case a down stream project wants to control whether to inline IntrinsicCandidate methods that are not otherwise recognized methods
=> Add disableInliningUnrecognizedIntrinsics option

compiler/aarch64/codegen/ARM64BinaryEncoding.cpp
OMR #7077 introduced the `callUsesHelperImplementation()` query to add a `TR_Helper` relocation for methods that are actually helper calls. That PR also changes the way the binary encoder finds necessary trampolines. Before OMR #7077, `methodTrampolineLookup()` was used for call targets whose method object returns false for the `isHelper()` query. The behavior was changed to call `findHelperTrampoline()` instead of `methodTrampolineLookup()` if the `callUsesHelperImplementation()` query returns true.
The problem is that the symbol reference for a certain method (which is actually a helper call) does not have a valid helper index as the reference number, thus causing `findHelperTrampoline` to return an incorrect address.
This commit fixes the binary encoder to use `methodTrampolineLookup` …
=> AArch64: Fix helper trampoline lookup fo ARM64Trg1SymImmInstruction

gc/base/MemorySubSpaceSemiSpace.cpp, gc/base/j9mm.tdf
The print statements are replaced with tracepoints in the flip function within MemorySubSpaceSemiSpace.cpp. This will allow them to be enabled via the -Xtrace option instead of a compile time flag.
Note we might also want to remove debugTiltedScavenge flag
in the future.
=> Replace debug printf log with trace

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/arm/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
This commit is motivated by eclipse-openj9/openj9#17861.
A check whether the underlying target supports 64 bit multiplication returning the high word is needed
in order to intrinsify java.lang.Math.multiplyHigh
As a side effect, this has simplified the
SupportsConst(I|L)Div checks as they are transitive to the newly added checks
=> Simplify SupportsConst(I|L)Div to Supports(I|L)MulHigh

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/arm/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
Reverts eclipse/omr#7082
`getSupportsLoweringConstIDiv()` and `getSupportsLoweringConstLDiv()` are used in the downstream project.
=> Revert "Simplify SupportsConst(I|L)Div to Supports(I|L)MulHigh"

compiler/il/OMRNode.cpp
`virtualCallNodeForAGuardedInlinedCall` shares the same value as `dontTransformArrayCopyCall`: `0x00000800`.
Just checking `isCall()` is not enough to determine if it's indeed `virtualCallNodeForAGuardedInlinedCall`.
=> Fix check on virtualCallNodeForAGuardedInlinedCall

compiler/il/OMRDataTypes.cpp, compiler/il/OMRDataTypes.hpp, compiler/il/OMRILOps.hpp, compiler/il/OMRILProps.hpp, compiler/il/VectorOperations.enum
- in some cases, vector opcode type was not calculated correctly: add VectorElementResult flag to indicate that result is a vector element to solve that issue
- add ILOpCode::getVectorDataType() and OMR::DataType::getVectorNumLanes() methods for convenience
=> Improve vector opcodes and data types

include_core/omrport.h, port/common/omrport.tdf, port/unix/omrsl.c, port/win32/omrsl.c
Added a flag `OMRPORT_SLOPEN_NO_LOAD` for `omrsl_open_shared_library()` to test if a library was loaded, and returns its handle if loaded;
`unix/omrsl.c` uses `dlopen()` with `RTLD_NOLOAD` to test if a library is already resident;
win32/omrsl.c uses GetModuleHandleW() to retrieve a handle to a specified module;
There are no such OS APIs for `AIX/zOS` platforms, and `OMRPORT_SLOPEN_NO_LOAD` is not supported.
`AIX` platform could use [loadquery](https://www.ibm.com/docs/en/aix/7.2?topic=l-loadquery-subroutine) to get a list of library files loaded and compare with a target library to determine if it was already loaded. Such functionality seems to fit better in a separate API, or in the upstream caller of `omrsl_open_shared_library()`.
Required by …
=> Add a flag OMRPORT_SLOPEN_NO_LOAD to test if a library was loaded

jitbuilder/release/CMakeLists.txt
While Makefile specifies thunk and matmul targets, CMAKE build system misses the tests. This commit includes the samples in the build, thus helping with demonstrating the JitBuilder features.
@mstoodle , how does this change look to you? The problem and the fix seem straightforward, so I omitted the step of creating an issue.
=> Include missing JitBuilder tests

jitbuilder/release/CMakeLists.txt
One of the tests (thunk), due to Jenkins not checking for Aarch64 and MacOSX was failing when built to run on all platforms. This commit moves this sample to the extended tests section.
This Pull Request addresses [ this comment](https://github.com/eclipse/omr/pull/7091#discussion_r1302172934) , and acts as a temporary solution to #7096 , although additional discussion is pending.
@mstoodle  , how does this look for a fix?
=> Make JitBuilder test optional

compiler/ilgen/OMRIlBuilder.cpp, fvtest/tril/CMakeLists.txt
Two changes, both of which have potential to break builds:
1) the tril project doesn't currently check its dependence on testcompiler so now it will assert if not also enabled (not sure our build scripts currently do this)
2) set the linkage on all JitBuilder method symbols to use TR_System convention (currently uses default which, at least on some platforms, is TR_Private).
=> Misc fixes

compiler/x/codegen/OMRTreeEvaluator.cpp
This commit fixes an issue in the arrayset
evaluator when packing negative integers
into the high bytes of a GPR. The packing
instruction sequence needs to zero-extend
the value being copied. Otherwise, every
other element in the packed result can
be incorrect.
Issue #6944
=> x86: fix packing in arrayset evaluator

compiler/arm/codegen/OMRLinkage.cpp, compiler/p/codegen/OMRLinkage.cpp
Instead, simply evaluate it like we do for other arguments.
These were the only two places where a `TR_RamMethodSequence` relocation could be generated for a method other than the outermost method, which is not expected. All remaining uses of `TR_RamMethodSequence` are for `compiledMethodSymbol`, which always represents the outermost method.
Fixes eclipse-openj9/openj9#17889
=> Stop special-casing unevaluated aconst in Power and ARM linkage

ddr/tools/blob_reader/blob_reader.cpp
A couple instances of `%zu` should be `%u`.
=> Fix printf formats in blob_reader.cpp

compiler/env/ProcessorInfo.hpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRInstOpCode.hpp, compiler/x/env/OMRCPU.cpp
AVX512-CD is required for leading zero bit count
=> x86: Support AVX512-CD

compiler/aarch64/codegen/OMRInstOpCode.enum, compiler/aarch64/codegen/OpBinary.cpp, fvtest/compilerunittest/aarch64/BinaryEncoder.cpp
AArch64 code generator incorrectly encodes `smulh` and `umulh` instructions, and those malformed instructions produce unexpected results. This commit fixes encoding of those instructions and adds binary encoding unit tests.
Issue https://github.com/eclipse-openj9/openj9/issues/18057
=> Fix encoding of smulh/umulh instructions on AArch64

cmake/modules/ddr/GenerateStub.cmake
The use of `return(${rc})` served no purpose; `rc` is always zero or we would have already issued a `FATAL_ERROR` message.
=> Avoid cmake policy CMP0140 warnings

gc/stats/AllocationStats.cpp, gc/stats/AllocationStats.hpp
Provide API to return allocation bytes since the start of VM. Return false if the sum rolls over.
=> Cumulative thread allocation stats

compiler/optimizer/ValuePropagationCommon.cpp
When we transform a clone() of an array object into a newarray and arraycopy, we neglected to add an allocationFence. This change will introduce an allocationFence after the arraycopy to ensure that all threads see the new contents of memory on weak memory coherency machines like POWER and AArch64.
=> Fix for a missing allocationFence in transformArrayCloneCall()

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/OMRCodeGenerator.cpp
Add missing default cases to switch statements which were causing "enumeration values not handled in switch" warnings on [`aarch64_mac` OpenJ9 builds](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/18194/). These additions (along with a few corresponding additions in [OpenJ9](https://github.com/eclipse-openj9/openj9/pull/18174)) fix the warnings without changing the behaviour of the code. This, of course, assumes that there are no switch cases that should be handled but aren't.
This PR contributes to (but does not close) [openj9 issue #14859](https://github.com/eclipse-openj9/openj9/issues/14859).
=> Add missing default cases to switch statements

gc/verbose/VerboseHandlerOutput.cpp
Add softmax stats to verbose:gc between maxHeapSize
and initialHeapSize
Signed-off-by: Frank Kang frank.kang@ibm.com
=> Add VGC output for softmax

compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp, include_core/omrport.h, port/unix/omrsysinfo.c
Previously both constrained and non-constrained transactional memory facility support were indicated with the `OMR_FEATURE_S390_TE` flag. This commit removes the `OMR_FEATURE_S390_TE` flag and adds a separate flag for constrained and non-constrained transactional execution facilities.
=> Z: Split flag for transactional execution facility

gc/base/GCExtensionsBase.cpp, gc/base/GCExtensionsBase.hpp, gc/verbose/VerboseHandlerOutput.cpp
Introduce reinitializeForRestore() method to GCExtBase, so that
during restore we can simply call this method rather than access
the GCExt members. This is done similar to other components which
need to reinit such as Configuration.
Also, add print in verboseGC for number of active cpus.
Signed-off-by: Frank Kang frank.kang@ibm.com
=> Add reinitializeForRestore to GCExtBase

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRMachine.cpp, compiler/p/codegen/OMRPeephole.cpp, compiler/p/codegen/OMRRegisterDependency.cpp, compiler/p/codegen/PPCDebug.cpp
Add missing default cases to switch statements which were causing "enumeration values not handled in switch" warnings on [ppc64_aix OpenJ9 builds](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/18289/). These additions (along with a few corresponding additions in [OpenJ9](https://github.com/eclipse-openj9/openj9/pull/18178)) fix the warnings without changing the behaviour of the code. This, of course, assumes that there are no switch cases that should be handled but aren't.
This PR also fixes the indentation of one of the switch statements to make it consistent with our code indentation standard.
This PR contributes to (but does not close) [openj9 issue #14859](https://github.com/eclipse-openj9/openj9/issues/14859).
=> Add default cases to PPC switch statements

compiler/p/codegen/ControlFlowEvaluator.cpp
Remove code in static function lookupScheme2 dependent on boolean variable isInt64 which was hard-coded to false.
This also removes code that was causing a warning, so this PR also contributes to (but does not close) [openj9 #14859](https://github.com/eclipse-openj9/openj9/issues/14859)
=> Remove dead code in lookupScheme2

compiler/env/TypeLayout.hpp
Add `isNullRestricted` field to `TypeLayoutEntry`
Related to: eclipse-openj9/openj9#18170
=> Add isNullRestricted field to TypeLayoutEntry

compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp
This PR introduces evaluators for the `TR::vnolz` and `TR::vnotz` IL in the z/codegen. Support is only enabled for architectures with vector instruction support.
=> Add TR::vnolz and TR::vnotz evaluators in z/codegen

compiler/aarch64/codegen/BinaryEvaluator.cpp
This commit updates `imulhEvaluator` to use `generateLogicalShiftRightImmInstruction` for generating a `lsrx` instruction rather than calling `generateTrg1Src1ImmInstruction`.
=> AArch64: Fix imulhEvaluator to use helper function to generate a shift instruction

ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
XCode 14.0.3 uses these tags:
* `DW_TAG_reference_type`
* `DW_TAG_unspecified_type`
They must be recognized to be support elements whose type attribute targets them.
Fixes the problem mentioned in https://github.com/eclipse-openj9/openj9/issues/17493#issuecomment-1734447047.
=> Recognize DWARF tags used by XCode 14.0.3+

gc/base/Configuration.cpp, gc/base/GCExtensionsBase.hpp
move defs for packetlistsplit, cachelistsplit, and splitfreelistamount from config to extbase
Signed off by: Frank.Kang@ibm.com
=> Move Forced Flags From Config to Extbase

gc/base/Configuration.hpp
Continue work from #7149, remove the original forced flag definitions from Configuration.
Signed off by: Frank.Kang@ibm.com
=> Remove Forced Flags from Configuration

compiler/runtime/OMRCodeCacheMemorySegment.cpp, compiler/runtime/OMRCodeCacheMemorySegment.hpp, jitbuilder/runtime/JBCodeCacheManager.cpp
This commit updates `JBCodeCacheManager` to allocate the `CodeCacheMemorySegment` object on the mmaped memory. The setter methods in `OMRCodeCacheMemorySegment` are also updated to guard the code updating members by `omrthread_jit_write_protect_disable/enable` calls.
=> Update JBCodeCacheManager to allocate segment objects on mmaped memory

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
This commit introduces a new option whose effect is to reduce initial invocation counts for methods whose class is loaded during startup but not present in the Shared Class Cache.
There are actually two opposite options:
-Xjit:useLowerCountsForNonSCCMethodsDuringStartup
-Xjit:dontUseLowerCountsForNonSCCMethodsDuringStartup
The options are mostly for the benefit of the OpenJ9 project.
The option bit `TR_UseLowerCountsForNonSCCMethodsDuringStartup` is set by default to 1 (`true`), but if aggressive throughput is desired, the option is reset to 0 (`false`). The user can then use the command line options mentioned above to override the default chosen value.
Note that if the user specifies a count value on the command line, (e.g. -Xjit:count=100), …
=> Option to reduce counts when class is not in SCC

gc/stats/AllocationStats.hpp
This PR ensures that the cumulativeAllocationBytes field is initialized.
=> Init allocation stats fields

port/ztpf/omrsignal.c
On z/TPF only, there exists a timing window where a signal monitor may be cleaned up before sig_full_shutdown completes processing.  This may lead to a GPF fault.
The fix is a simple check to make sure the monitor is not 0 before use.
=> Add check for ztpfSigShutdownMonitor before attempting to shut it down

compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/LoopVersioner.hpp
It is incorrect to both version asynch check and fold the conditional in the duplicated loop, or version write barrier and fold the conditional in the duplicated loop.
For asynch check, when the loops are unbiased, do not version asynch check so that the conditional in both loops can be folded away.
For write barriers, the determination of whether or not to version write barriers happens after the duplicated loop has already been added to `FoldConditional`. If the conditional in the duplicated loop will be folded, do not version write barrier.
Fixes eclipse-openj9/openj9#17249
=> Fix issue in folding the conditional in the duplicated loop

gc/base/GCExtensionsBase.cpp, gc/base/GCExtensionsBase.hpp, gc/base/SparseVirtualMemory.cpp, gc/base/SparseVirtualMemory.hpp
Currently Sparse Virtual Memory uses page size Object Heap is allocated with. We want to use small pages for Sparse Heap always regardless. Also Sparse Virtual Memory uses page flags "requested" for Object Heap. This is the bug. Page flags should be paired with the page size.
Please note, that current MM_SparseVirtualMemory implementation can use double mapping instead of off-heap. This is an experimental feature never used in the code and not planned to be used. This feature uses hidden assumption that memory page size/flags should be the same for Object and Sparse heaps. This PR can break it potentially in the case memory page settings in the Object Heap and Sparse heap are different. We are going to be aware about this if we need another round of experimental testing with double …
=> Use small page size/flags for Sparse Virtual Memory

compiler/aarch64/codegen/OMRInstruction.hpp, compiler/arm/codegen/OMRInstruction.hpp, compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/infra/OMRMonitor.cpp, compiler/infra/OMRMonitor.hpp, compiler/infra/OMRMonitorTable.hpp, compiler/p/codegen/OMRInstruction.hpp, compiler/ras/Delimiter.hpp, compiler/riscv/codegen/OMRInstruction.hpp, compiler/x/codegen/OMRInstruction.hpp, compiler/x/codegen/OMRX86Instruction.hpp, compiler/z/codegen/OMRInstruction.hpp, compiler/z/codegen/S390Instruction.hpp
Work towards fixing AIX warnings about converting string literals to non-const char pointers by adding a 'const' qualifier to string fields and parameters in a variety of locations throughout OMR.
Contributes to (but doesn't close) [openj9 #14859](https://github.com/eclipse-openj9/openj9/issues/14859)
=> Add 'const' qualifier to some string fields and parameters

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
For all platforms where `arraycmp` and `arraycmplen` are supported, do not call `setSupportsArrayCmp(Len)` when either
- arraylets can be generated
- the `TR_DisableArrayCmp(Len)` environment variable is set
See https://github.com/eclipse-openj9/openj9/pull/16662#discussion_r1317469710
Relies on https://github.com/eclipse/omr/pull/6983, leaving this as draft until that goes through
=> Enable arraycmp and arraycmplen uniformly

gc/base/GCCode.cpp, gc/base/GCCode.hpp, gc/base/ParallelHeapWalker.cpp, gc/base/ParallelHeapWalker.hpp, gc/base/j9mm.tdf, gc/base/standard/HeapWalker.cpp, gc/base/standard/HeapWalker.hpp, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/ParallelGlobalGC.hpp, gc/verbose/VerboseHandlerOutput.cpp, include_core/omrgcconsts.h
When a checkpoint is taken, the entire contents of the process is
serialized, and someone can inspect the serialized state to capture
some sensitive info.
Solution:
If a data is no longer referenced, the entire memory chunk
is zeroed at snapshot time.
Implementation detail:
After the initial snapshot GC, 2 passes are done to fix-up, identify,
and clear all unused free memory chunks (including both linked and
unlinked multi-slot free entries). The first pass performs a fix-up
to the current heap which converts dark matter to holes, while the
second pass clears all free entries.
Note here this implementation only works for standard GC but not
balanced GC and metronome.
Signed off by: Frank.Kang@ibm.com
=> Clear Inactive Objects at Checkpoint

fvtest/porttest/omrstrTest.cpp, util/a2e/atoe_utils.c
Std vsnprintf accepts null buffer and returns an estimate Our implementation does not support that
Updated the atoe_vsnprintf implementation
Signed-off-by: ehsan kiani far <ehsan.kianifar@gmail.com>
=> Z: Prioritize buffer size over buffer pointer in atoe_vsnprintf to better match std vsnprintf

gc/base/AllocateInitialization.hpp
_requestedSizeInBytes field in not used (and even not initialized properly for arrays). This field is a duplicate for _allocateDescription->_requestedBytes. The correspondent helper getRequestedSizeInBytes() is not used and can be removed as well.
=> Remove unused duplicated field from MM_AllocateInitialization

compiler/p/codegen/ControlFlowEvaluator.cpp
Fix plinux warning concerning a conversion from NULL to intptr_t by removing the initial assignment of variable `address` to NULL. Since `address` is bound to a value immediately afterwards in both control flow paths through the if-else block which directly follows the variable definition, it's safe to not give it an initial value here.
The other instance of this warning will be fixed in [openj9 #18244](https://github.com/eclipse-openj9/openj9/pull/18244)
This PR contributes to (but does not close) [openj9 #14859](https://github.com/eclipse-openj9/openj9/issues/14859)
=> Remove binding of NULL to non-pointer variable

compiler/ras/Debug.cpp
Fix AIX warnings concerning incorrect format specifiers for variables with type `pid_t` by casting them to `int64_t` since `pid_t` is not guaranteed to be a long integer on every platform.
This PR contributes to (but does not close) [openj9 #14859](https://github.com/eclipse-openj9/openj9/issues/14859)
=> Cast pid_t to int64_t for use in format specifiers

compiler/optimizer/OMRSimplifierHandlers.cpp
Creates ifxcmpne helper methods in the simplifier (taken from and now called by the body of the corresponding ifxcmpneSimplifier() function) and calls them after calling simplifyISelectCompare() from an ifxcmpxx simplifier when the iselect compare simplification causes the IL op of the ifxcmpxx node to become an ifxcmpne, making the rest of the handler's logic potentially incorrect due to the assumption that the op being simplified is still the same ifxcmpxx as it had been.
Corrects reversed logic observed in cases where an ifxcmpxx simplifier continued simplifying after simplifyISelectCompare() had caused the node to become an ifxcmpne. For example, an ificmpeq was simplified and transformed into an ificmpne during simplifyISelectCompare(), and then when the ificmpeqSimplifier() …
=> Use correct simplifications after creating ifxcmpne

compiler/optimizer/OMROptimization.cpp, compiler/optimizer/OMRSimplifier.cpp, compiler/optimizer/OMRSimplifier.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/OMRSimplifierHelpers.cpp
The `divchkSimplifier` was first simplifying its child node and then checking whether the `DIVCHK` is still needed after having simplified its child.  It did that by checking whether the simplification of its child results in a node that is not the original child, or the simplified child is not a division or remainder operation.
However, it might be that the simplified child is still a division or remainder operation that needs to be checked for division by zero, but is not the original child node.  The existing logic leads `divchkSimplifier` to replace the `DIVCHK` with a `treetop` operation incorrectly.
This change revises the division and remainder simplifiers so that they only directly replace the child of the parent `DIVCHK` (if any) with a different division or remainder node that …
=> Ensure simplifier keeps required DIVCHK operations

omr_static_lib/makefile
The behavior of GNU make seems to have changed between versions 4.2.1 and 4.3.
The latter appears to prioritize `MAKEFLAGS=` over (at least some) command-line options, with the effect being that `--no-print-directory` is ignored and included in the output of `show-objects`.
If invoked as part of a larger build where the make job server is enabled, there are also warnings that make unwanted contributions to the output of `show-objects`.
This fixes that, and removes the useless "echo" rule for the already existing objects.
=> Fix collection of object files for omr_static_lib

compiler/z/codegen/OMRTreeEvaluator.cpp
If the iRegStoreEvaluator generates an LGFR to sign extend, it is
incorrect to assume that the iRegStore's child is clobberable. We must
preserve the original value when sign extending. This commit fixes
this issue by using the gprClobberEvaluate routine so that the sign
extension is performed in a different register, and we don't potentially
overwrite the upper-half data in the original register.
=> Make globalReg clobberable in Z iRegStoreEvaluator

util/a2e/atoe.c
The libwrappers atoe_enableFileTagging() function has always taken the ccsid, but it hasn't been passed. Move the code calling libwrappers to atoe_setFileTaggingCcsid() and pass the ccsid.
=> Call libwrappers atoe_enableFileTagging() with ccsid

compiler/il/OMRMethodSymbol.hpp, compiler/il/OMRResolvedMethodSymbol.cpp, compiler/il/OMRResolvedMethodSymbol.hpp
Add `CanSkipNonNullableArrayNullStoreCheck` for recognized method.
This change is used by the change in:
=> Add can skip null value store check

compiler/env/ProcessorInfo.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRInstOpCode.hpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp, compiler/x/runtime/X86Runtime.hpp, include_core/omrport.h, port/common/omrsysinfo_helpers.c
- Process Structured Extended Feature Flags (from ECX) Enumeration Leaf (Initial EAX Value = 07H, ECX = 0)
- Enable AVX512-VBMI2, AVX512-BITALG, AVX512-VPOPCNTDQ
=> x86: Extend CPUID support

port/unix/omrsharedhelper.c, tools/tracegen/Port.cpp
The code fails to compile on zlinux with gcc 11.2 without fixes.
```
Port.cpp: In static member function 'static RCType
Port::omrfile_stat(const char*, unsigned int, J9FileStat*)':
Port.cpp:691:14: error: narrowing conversion of '4283649346' from
'unsigned int' to 'int'
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wnarrowing]
691 |         case 0xFF534D42: /* CIFS_MAGIC_NUMBER */
|              ^~~~~~~~~~
```
This one fails to compile on 32-bit.
```
In file included from /usr/include/string.h:637,
from ./unix/omrsharedhelper.c:34:
./unix/omrsharedhelper.c: In function 'omr_unlinkControlFile':
./unix/omrsharedhelper.c:419:9: error: '__builtin_strncpy' specified
bound depends on the length of the source argument
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index …
```
=> Update Port.cpp and omrsharedhelper.c to fix gcc11 compilation

compiler/z/codegen/ControlFlowEvaluator.cpp
This PR addresses the use of vector instructions to handle short format in the **select** evaluator.
Previously, the use of vector instructions for short format in the select evaluator was disabled, even though on z14 and newer platforms it is supported. The issue was caused by not correctly converting the condition code from GPR to FPR for short format. Changes for enabling vector instructions for short format:
- Use of LLGFR instruction for long format for zero-extending a 32 bit conditionReg to 64 bits
- Use of separate SLLG instruction for short format to preserve the float representation of the first 32 bits as it is later moved into FPR
- Addition of mask values in the VFCE instruction to get the element size mask for floats and doubles respectively
Closes: #5002 
Signed-off-by: …
=> Z : Enable Vector instructions for handling float data types

compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp
Currently the `OMR::Z::CPU::setSupports*(bool value)` methods return the input `value`. The return value from these setters is not used anywhere, so there is no need to have a return value.
=> Z: Change CPU support flag setters to return void

compiler/optimizer/LoopVersioner.cpp
This logic has been inadvertently folding the versioning test instead of the original guard since ce45970e6f92be1148c88c8bfd1b4afb8ae09cb1, which is effectively the same as not versioning the guards. This can be expected to have resulted in slower code than intended. Worse, if there are HCR guards in the loop, then once the fixed-point analysis has determined that it is possible to version them, they must be versioned for correctness. This is because other transformations may rely on the cold side being eliminated from the hot loop. In particular, by failing to version HCR guards, we could privatize mutable fields even though they could be modified by a cold call while the loop is still running.
=> Correct branch folding for HCR guard versioning

gc/verbose/VerboseHandlerOutput.cpp
Add two booleans to the VGC's output
1. addressable Physical Memory
2. If the JVM is running inside a container, and its memory limit is set
Signed-off-by: Frank Kang frank.kang@ibm.com
=> Add VGC output for Container

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/control/CompileMethod.cpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/control/OptionsUtil.hpp, compiler/il/OMRResolvedMethodSymbol.cpp, compiler/infra/InterferenceGraph.cpp, compiler/infra/InterferenceGraph.hpp, compiler/infra/SimpleRegex.cpp, compiler/infra/SimpleRegex.hpp, compiler/infra/Statistics.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/ValuePropagationCommon.cpp, compiler/ras/Debug.cpp, compiler/ras/Debug.hpp, compiler/ras/ILValidationRules.cpp, compiler/ras/LimitFile.cpp, compiler/ras/OptionsDebug.cpp, compiler/ras/Tree.cpp, compiler/runtime/OMRCodeCache.cpp, compiler/runtime/OMRCodeCache.hpp, compiler/runtime/OMRRuntimeAssumptions.hpp
Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to (char *)) in compile, runtime, control, ras, and infra.
This PR contributes to (but does not close) https://github.com/eclipse-openj9/openj9/issues/14859
**This PR depends on:**
- **Step 1:**
- https://github.com/eclipse-openj9/openj9/pull/18083
- https://github.com/eclipse-openj9/openj9/pull/18455
- **Step 2:**
- https://github.com/eclipse-openj9/openj9/pull/18467
- https://github.com/eclipse/omr/pull/7186
**and must be merged in coordination with https://github.com/eclipse-openj9/openj9/pull/18470**
=> Fix string literal conversion warnings in compile, runtime, control, ras, infra

compiler/codegen/CodeGenRA.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/codegen/Relocation.cpp, compiler/codegen/Relocation.hpp, compiler/codegen/StorageInfo.cpp, compiler/codegen/StorageInfo.hpp, compiler/il/OMRBlock.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/Inliner.hpp, compiler/optimizer/LocalOpts.cpp, compiler/optimizer/LocalOpts.hpp, compiler/optimizer/LoopReplicator.cpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OrderBlocks.cpp, compiler/optimizer/OrderBlocks.hpp, compiler/optimizer/ValuePropagationCommon.cpp, compiler/p/codegen/PPCHelperCallSnippet.cpp
Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to `(char *)`) in codegen, p, il, and optimizer.
This PR contributes to (but does not close) https://github.com/eclipse-openj9/openj9/issues/14859
=> Fix string literal conversion warnings in codegen, p, il, infra, optimizer

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
Class unload pics must be added to class constants so that constants can be invalidated when they are unloaded. aconstEvaluator does add them on AArch64. However, ificmpHelper does not evaluate aconst node if the constant value can be encoded into the immediate field of the cmp instruction. This commit updates ificmpHelper to evaluate aconst node if class unload pic is required.
Related issue: https://github.com/eclipse-openj9/openj9/issues/18195
=> AArch64: Add class unload pic to class constant under ifacmp node

gc/base/Configuration.cpp, gc/base/Configuration.hpp, gc/base/GCExtensionsBase.hpp, gc/base/ParallelDispatcher.cpp, gc/base/j9mm.tdf
This flag is to be used along existing gcThreadCountForced. Specified
flag will be used to distinguish between GC thread count calculated by
default or specified by a command line option. Forced flag
will to be used for a subset of options that force a fixed number of
threads.
Currently Forced is used as Specified, but we need both to distinguish
among 3 posibilities, specifically in Java: default, Xgcthreads and
Xgcmaxthreads.
Changes that will make that behavior effective will follow up later,
once downstream projects properly adjust command line parsing and
setting these flags.
=> Introduce flag gcThreadsCountSpecified

include_core/ute_dataformat.h, omrtrace/omrtracelog.cpp
This commit adds AArch64 to UtArchitecture and Armv8-A to UtSubtype.
=> Add AArch64 to UtProcessorInfo

gc/base/Configuration.cpp, gc/base/ParallelDispatcher.cpp
Make use of newly introduced gcThreadCountSpecified flag so that when command line options (such as Java's -Xgcthreads or -Xgcmaxthreads) are specified, GC thread count overrides the default count calculation.
Old gcThreadCountForced flag is still used, butin ParallelDispatcher to distinguish between force/fixed or adaptive count of threads, bufore deciding how many threads to use for a ParallelTask.
Another change is that during the snapshot VM creation when thread count is reduced to checkpointGCthreadCount, we don't adjust GCExtensions gcThreadCount anymore (only ParallelDispatcher is affected). This is to be able to carry over the original count (from snapshot VM) to restore VM, so that options that specify that count can be obeyed even on restore side.
=> Use gcThreadCountSpecified

azure-pipelines.yml
These tests pass on the Jenkins MacOSX machines, but intermittently
fail on Azure MacOSX due to machine/network issues.
Related: #6516
=> Disable PortSockTest tests that fail on Azure MacOSX

compiler/control/OMROptions.hpp, compiler/optimizer/OMROptimizer.cpp, compiler/optimizer/OMROptimizer.hpp
This commit adds a new option bit called TR_NotCompileTimeSensitive which will be turned on by an upstream project (OpenJ9) in situations where we favor throughput over compile time.
The commit also adds a new optimization qualifier, `IfLoopsAndNotCompileTimeSensitive`. An optimization pass flagged as such will be performed only if the method being compiled has loops and the `TR_NotCompileTimeSensitive` bit is turned on.
=> Add flag to indicate compile time is not that important

compiler/optimizer/OMRLocalCSE.cpp
An `l2a` operation might be used to convert the result of a compressed reference sequence to an address, but it is also used in other circumstances - for instance, if an `Int64` value holds the address of a `j9class` or a `j9method`.  The `l2aEvaluators`[1,2,3,4] assume that `l2a` is used for compressed references or accessing arraylets.  If the node is not accessing an arraylet and compressed references are enabled, the evaluator will mark the source register as containing a collected reference under the assumption that it's working with a compressed reference.  However, if the `l2a` is being used for a `j9class`, `j9method`, etc., the register that holds it should not be marked as a collected reference.
As an interim fix, this change will prevent commoning of `l2a` operations. The …
=> Prevent commoning of l2a operations in localCSE

compiler/optimizer/OMRLocalCSE.cpp
`OMR::LocalCSE::canBeAvailable` was restricting `l2a` operations from being commoned to reduce the likelihood that a register holding the result of such an operation would be marked as a collected reference and kept live across a GC point by l2aEvaluator.  To be safest, all conversion to address types should be similarly prevented from being commoned.
This change generalizes the change delivered under pull request #7217.
=> Prevent commoning conversion to address operations in LocalCSE

port/common/omrport.tdf, port/unix/omrsysinfo.c, port/win32/omrsysinfo.c
Adjust omrsysinfo_get_process_start_time traces to avoid 
casting.
Issue: https://github.com/eclipse/omr/issues/7201
Signed-off-by: Amarpreet Singh <Amarpreet.A.Singh@ibm.com>
=> Adjust omrsysinfo_get_process_start_time traces

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/optimizer/GlobalRegisterAllocator.cpp, compiler/optimizer/GlobalRegisterAllocator.hpp, compiler/optimizer/OMRRegisterCandidate.cpp
The commit introduces a new option -Xjit:graFreqThresholdAtWarm=<NNN> that can be used to control the JIT overhead for compilations performed at warm optimization level or below. The default value of the threshold is 500. A larger value leads to lower JIT overhead but also to potentially lower quality of the generated code. For hot compilations or in situations where we think we can afford more JIT overhead, the threshold is automatically set to 0.
=> GRA changes to reduce JIT overhead at warm opt levels

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/X86OpcodeTable.hpp
- disable vector shift and rotate opcodes until they comply with the JVM Specification
=> Disable vector shift and rotate opcodes

compiler/optimizer/OMRSimplifierHandlers.cpp
Do not simplify `lsub` trees if its grandchild can overflow
=> Do not simplify lsub trees if its grandchild can overflow

compiler/optimizer/LoopVersioner.cpp
Previously this versioning test would do either a strict or non-strict comparison depending on a few factors:
- `isLoopDrivingInductionVariable`,
- `isIndexChildMultiplied`, and
- the opcode of `_loopTestTree` (without consulting `reverseBranch`).
To deal with all of this variation there were multiple ad hoc adjustments of +1 or -1 at different points in the determination of `maxValue` (which is really supposed to be the last value).
This state of affairs led to bugs, notably when using a non-strict loop test together with an index expression that contains a multiplication, but also in other scenarios that I have not precisely characterized.
Now this versioning test is always `(ifiucmpge maxValue arrayLength)` for increasing index expressions and `(ificmplt maxValue 0)` for decreasing …
=> Fix versioning test against final index value for BNDCHK

port/aix/omrtime.c, port/linuxppc64/omrtime.c, port/linuxs390/omrtime.c, port/unix/omrtime.c, port/win32/omrtime.c
Reuse OMRPORT_TIME_DELTA_IN_NANOSECONDS in omrtime.c 
instead of OMRTIME_NANOSECONDS_PER_SECOND for consistency 
across the different platforms.
Issue: https://github.com/eclipse/omr/issues/7219
Signed-off-by: Amarpreet Singh <Amarpreet.A.Singh@ibm.com>
=> Reuse OMRPORT_TIME_DELTA_IN_NANOSECONDS in omrtime.c

compiler/z/codegen/OpMemToMem.cpp
This change targets memory compare implementation. If the Array cmp asks for a signed response (-1/0/1), the memCmp implementation would be called.
=> Z: Short circuit mem cmp sign macro op

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/il/OMRSymbol.hpp, compiler/il/OMRSymbol_inlines.hpp, compiler/ras/Debug.cpp
Add ContiguousArrayDataAddrFieldShadowSymRef along with needed getter and setter. This is minimum set of off heap changes needed for https://github.com/eclipse-openj9/openj9/pull/18303.
=> Add contiguous array dataAddr field shadow symbol reference for off heap technology

compiler/z/codegen/OMRTreeEvaluator.cpp
This PR targets array cmp len implementation. If the Array cmp asks for the position of the first mismatch, this implementation would be called. It returns the index of the fists mismatch or the length of the array if there is no mismatch.
=> Z: short circuit ArrayCmpLen if addresses are equal

doc/compiler/osr/OSR.md
- introduce new concepts
- provide detailed desciption of OSR mechanism based on involuntary OSR
- map new concepts into existing API
=> Create more detailed OSR documentation

compiler/z/codegen/OMRTreeEvaluator.cpp
This PR targets array cmp helper implementation when the length is variable. the arraycmpEvaluator calls arraycmpHelper when the length is variable or larger than 4k and requested response is unsigned.
=> Z: Short circuit variable length array cmp helper

example/glue/ConfigurationDelegate.hpp, gc/base/Configuration.cpp
CheckpointGCthreadCount is expected to be no larger than
the number of gc threads.
We have two cases here:
1. If the user doesn't set the checkpointGCthreadCount,
the amount is adjusted to match the number of gc threads
2. If the user sets the checkpointGCthreadCount, a warning
is generated and the checkpointGCthreadCount is ignored
Signed off by: Frank.Kang@ibm.com
=> CheckpointGCthreadCount conflicts with gcThread Warning

gc/verbose/VerboseHandlerOutput.cpp, gc/verbose/schema.xsd
Report existing cummulative discarded bytes in allocation stats section of VGC (reported as a part of GC-start increment).
At the present they are only TLH discards, although in theory there could be small discards from non-TLH allocations when remainder is less then min free entry, but we don't gather those stats. It's not specifically reported as TLH ones, since in future we might add non-TLH ones, too.
This is useful to report/check if TLH sizing is changed (via for example tlhMaximumSize paramter), to see if there is any negative sideeffect (increase of discards, which may potentially increase frequency of GCs).
=> Discarded bytes in Verbose GC

compiler/optimizer/LoopVersioner.cpp
For an increasing loop-driving IV, the loop test must impose an upper bound, e.g. `while (i < n)`, whereas for a decreasing loop-driving IV, the loop test must impose a lower bound instead, e.g. `while (i >= n)`. Otherwise, the predicted maximum iteration count will be wrong, which could allow a bound check to be incorrectly skipped.
Loop versioner will now check to ensure that the direction of the loop test agrees with the sign of the step of the loop-driving IV.
Fixes eclipse-openj9/openj9#18803
=> Don't version BNDCHK based on an IV if the loop test is backwards

buildenv/docker/riscv64/debian11/Dockerfile
This commit fixes Dockerfile creating image for RISC-V CI builds. The problem was that URL libfakeroot and libfakechroot was no longer valid. It pointed to Debian ports archive, but meanwhile RISC-V architecture became "officially" supported (will be once Trixie is out).
It is not clear to me why Dockerfile downloaded and extracted RISC-V versions of libfakeroot and libfakechroot at all. However, I had been successfully building sysroots for OMR and/or OpenJ9 compilations using
mmdebstrap --mode=fakeroot --variant=extract
without need of RISC-V libfakeroot and libfakechroot. So this commit removes download and manual installation of them and uses --variant=extract to build sysroot. In addition it uses new ("official") Debian archives to build the sysroot. This way the aforementioned …
=> RISC-V: fix docker image creation for CI cross-builds

CODE_OF_CONDUCT.md
Add a copy of the Eclipse Code of Conduct to the project files, as recommended by the Eclipse Foundation.
Note that this is not a new Code of Conduct for the project.  It is the same Code of Conduct already referenced in the README file by URL but in Markdown format.
=> Add Eclipse suggested CODE_OF_CONDUCT.md

compiler/ras/OptionsDebug.cpp
The `writeLine("")` that is removed by this commit appears to be redundant - the most recent thing written to the log before the compressed refs message will either come from this:
https://github.com/eclipse/omr/blob/a74c0935b40f9e40b4be65004a8d0e711e16e6f2/compiler/ras/OptionsDebug.cpp#L335
or this, in the loop that prints the options:
https://github.com/eclipse/omr/blob/a74c0935b40f9e40b4be65004a8d0e711e16e6f2/compiler/ras/OptionsDebug.cpp#L509
In both cases the extra line is redundant.
Before this change:
```
#INFO:  _______________________________________
#INFO:  JIT 
#INFO:  options specified:
#INFO:       verbose={compilePerformance|JITServer},vlog=clientvlog.txt
#INFO:  
#INFO:  options in effect:
#INFO:       verbose={options|compilePerformance|JITServer}
#INFO: …
```
=> Remove redundant newline in verbose log

gc/base/ObjectAllocationInterface.hpp, gc/base/TLHAllocationInterface.cpp, gc/base/TLHAllocationInterface.hpp
Expose remaining and refresh size APIs for ObjectAllocationInterface,
and implement it for TLHAllocationInterface.
While this values are functionally needed only internally within the
class, they will be used for stats reporting purposes outisde the class,
hence need to be public.
=> Expose alloc cache size API

compiler/z/codegen/ControlFlowEvaluator.cpp, fvtest/compilertriltest/MaxMinTest.cpp
This PR adds support to the S390 MaxMin evaluator to handle NaN operands for [fd]min/max opcodes.
- Add NaN checks and set return register to NaN if either operands are NaN
- Enable MaxMin tests for Float/Double on LoZ, and disable them on z/OS
Closes: #5157
Signed-off-by: Sarwat Shaheen sarwat.shaheen@yahoo.com
=> Z: Support NaN values w.r.t fmax/fmin/dmax/dmin on S390

gc/base/EnvironmentBase.cpp, gc/base/EnvironmentBase.hpp, gc/base/MemorySubSpaceFlat.cpp, gc/base/MemorySubSpaceGenerational.cpp, gc/base/MemorySubSpaceSemiSpace.cpp, gc/base/standard/ConcurrentGC.cpp, gc/base/standard/ConcurrentGC.hpp, gc/base/standard/ConcurrentGCIncrementalUpdate.hpp, gc/base/standard/ConcurrentGCSATB.hpp, gc/base/standard/Scavenger.cpp
flushCachesForGC is mostly called close/prior to start-gc point for each particual GC operation/STW-increment, so that we often end up doing it twice, the first one being early during acquireExclusiveVMAccessForGC negotiation.
This change removes the one from acquireExclusiveVMAccessForGC, but also adds a couple of flushCachesForGC in GC specific operation that relied on acquireExclusiveVMAccessForGC to do it.
=> Remove flushCachesForGC from acquireExclusiveForGC path

compiler/control/OMROptions.cpp
This commit disables Dual TLH on AArch64 by default.
=> AArch64: Disable Dual TLH by default

compiler/z/codegen/OMRTreeEvaluator.cpp
This PR targets array cmp SIMD implementation. ArrayCmpSIMDHelper returns zero or length of the array when arrays are equal. if the compare type is "len" it returns length if it is "-1/0/1 or 1/0/2" it returns zero. It also can jump to a provided label instead of returning any register.
=> Short circuit array cmp simd helper

compiler/optimizer/ValuePropagationCommon.cpp
`StringCoding.implEncodeAsciiArray` is nearly identical in implementation and use case to the old `US_ASCII/Encoder.encodeASCII` method. This PR adds support in VP for transforming `StringCoding.implEncodeAsciiArray` into an `arraytranslate` that can then be take advantage of pre-existing acceleration for this workload.
=> Transform new converter call to arraytranslate node

ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
* generalize `getConstValue()` and use it in more places
* add (implicit) support for `DW_FORM_implicit_const`
This change, together with a modification of OpenJ9 to stop avoiding DWARF version 5, allowed me to build OpenJ9 for Linux on s390x and x86_64.
This may fix https://github.com/eclipse/omr/issues/6135.
=> DDR: support DWARF version 5

example/glue/ConfigurationDelegate.hpp, example/glue/EnvironmentDelegate.hpp, gc/base/Configuration.cpp, gc/base/EnvironmentBase.hpp
Integrate with downstream delegate restore reinit APIs:
- Thread Local (env) Obj Buffers
- Region Extensions Object Lists
Continue Salman's work, after fixing https://github.com/eclipse-openj9/openj9/issues/17731
Also fix some comments.
Signed-off-by: frank.kang@ibm.com
=> Integrate GC Restore With Delegate Reinit APIs

compiler/compile/OMRCompilation.cpp
Transforming `Unsafe.copyMemory()` or `Unsafe.setMemory()` are considered Unsafe related transformation and should check `TR_DisableUnsafe` before performing the transformation.
=> Check TR_DisableUnsafe before transforming Unsafe copyMemory & setMemory

compiler/z/codegen/OMRTreeEvaluator.cpp
In case of constant length array copy code, a length of bytes to be copied would be loaded into register in case we need to perform a test to check for destructive region copies and perform destructive array copy. We need to make sure that byteLength node is evaluated before the internal control flow starts. We found an issue where downstream consumer of primitive arraycopy sequnece generator needed byteLenReg and as the constant value was loaded only in case we fail absolute test for forward copy check, we ended up in scenario where it reads a value from array using length which consists of garbage. This commit fixes the issue and in case, we do not know the direction for array copy, it evaluates bytelength node before internal control flow starts.
=> Evaluate constant byteLenNode of arrayCopyChild

compiler/env/ProcessorInfo.hpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/X86Ops.ins, compiler/x/env/OMRCPU.cpp, fvtest/compilerunittest/x/BinaryEncoder.cpp
This commit adds the `clwb` instruction motivated
by the writeback0 intrinsic available in the Unsafe Java library.
The intrinsic permits users to write back a cache line if cache line writeback is enabled by the underlying VM. This instruction maps 1-1 with the intrinsic method.
The CPUID feature flag OMR_FEATURE_X86_CLWB is already implemented and should be used to check whether the instruction is supported in the underlying hardware.
=> Add Cache Line Writeback Instruction

compiler/optimizer/DeadTreesElimination.cpp
Volatile nodes should always be anchored under a treetop to avoid any interference with other optimization passes (e.g. PRE).
Fixes eclipse-openj9/openj9#18777
=> Do not swing down volatile nodes

compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/il/AnyConst.hpp, compiler/infra/map.hpp, compiler/infra/set.hpp, compiler/optimizer/CallInfo.hpp, compiler/optimizer/DeferredOSRAssumption.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/abstractinterpreter/OMRIDTBuilder.cpp
If inlining uses constant folding to help determine call targets, then it's important for the corresponding IL (if any is generated) to be consistent with what the inliner saw.
This commit equips `TR_CallTarget` with a collection of observed constants that must be folded consistently in IL. This collection can be populated by an inliner and later consulted by an IL generator to ensure that the operations are folded as needed.
This repeated folding is important whenever a value might be allowed to be folded despite the possibility of a later change. It also allows constants to be speculative by specifying the assumptions that are necessary in order for the folding to be correct, and by informing the IL generator of the locations where such assumptions have been made.
---------- …
=> Facilitate recording of constants observed in call target selection

cmake/modules/ddr/DDRSetStub.cmake.in
Prior to this change, numerous warnings are issued by cmake:
```
CMake Warning:
Ignoring empty string ("") provided on the command line.
```
For example, see https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_mac_Nightly/205.
=> CMake: fix empty string warnings

thread/common/thrprof.c
OpenXL complains:
```
ISO C99 and later do not support implicit function declarations
```
=> Add missing declaration of _CPUTIME()

omrsigcompat/CMakeLists.txt
This was overlooked in #972 which removed all instances of sigvec.
Fixes the below LLVM toolchain error:
error: version script assignment of 'global' to symbol 'sigvec'
failed: symbol not defined error when using LLVM toolchain
=> Remove sigvec reference in CMakeLists.txt

gc/base/standard/ConcurrentGCSATB.cpp, gc/verbose/VerboseWriterFileLoggingBuffered.cpp, gc/verbose/VerboseWriterFileLoggingSynchronous.cpp, include_core/omrportsocktypes.h, include_core/thread_api.h
They are problematic on z/OS where conversion to EBCDIC will fail.
=> Don't use non-ASCII characters in text files

cmake/modules/ddr/DDRSetStub.cmake.in
This reverts commit 4ae6b18d6bdc42a4884645739251e5e309ef20d5.
=> Revert "CMake: fix empty string warnings" #7283

port/unix/omrintrospect.c
On AIX, this typo disables code that prevents upcall_handler from
collecting thread data when upcall_handler is unregistered. Collecting
data after upcall_handler is unregistered might cause corrupt memory
to be passed through siginfo and lead to crashes.
**More context:**
On AIX, a signal can can be unavailable to sigpending/sigwait but
not yet have been delivered to a thread. As a result, it is not
guaranteed that SIG_SUSPEND won't be delivered after upcall_handler
is unregistered.
=> Fix typo AIXPPCX -> AIXPPC

compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/OMRSimplifierHelpers.hpp
This commit cleans up the BINARY_IDENTITY_OP and
BIANRY_IDENTITY_OR_ZERO macros and replaces them
with inline equivalents by implementing a struct to replace template
instantions of the functions tryAndSimplifyBinaryOp*.
This change limits the number of template instantiations
potential call sites have to create as well as abstracts
some captured variables inside the struct to minimize
the number of arguments passed to actual calls.
A closure is emulated by the struct.
Through escape analysis, scalar replacement and inlining,
the overhead of creating this struct should be minimal
on -O3
Related: https://github.com/eclipse/omr/issues/7166
Signed-off-by: James You <james.you@protonmail.com>
=> Refactor Binary Identity Simplification Macro

CONTRIBUTING.md
Make ECA requirements more prominent in the contribution guidelines.
Includes minor edits to miscellaneous text for readability.
This was feedback from a recent OMR release review.
=> Improve ECA documentation in CONTRIBUTING.md

compiler/optimizer/VirtualGuardHeadMerger.cpp
`changeBranchDestination` tries to remove unreachable blocks after the
removal of the old edge from guard2 to cold2. Rarely, a previous
transformation in this pass could have made guard2Block unreachable
without removing it, in which case it might have been removed just now.
Normally, if all relevant blocks are removed, later `moveBlockAfterDest`
will not cause any issue since it will be just moving around all
unreachable blocks. However, in an even more rare case, if some of the
blocks are removed and some of them are not (eg, guard2Block and the
previous block of guard2Block are removed but the next block of
guard2Block is still valid), `moveBlockAfterDest` could end up joining
an invalid/removed block with a valid block. Therefore, if guard2Block
is no longer valid, it should not …
=> Do not continue to merge back cold path if guard2 block has been removed

doc/compiler/CompilerOptions.md
The documentation incorrectly lists "disableLoopUnroller" as the option to disable loop unroller. This option does not exist and will result in an unrecognized option error.
The correct Xjit option name is "disableGLU" and the documentation has been updated to reflect this.
The "disableGLU" option is defined here:
https://github.com/eclipse/omr/blob/0e07ad19c1f3a7ce41cebd121fde5756fa32fd0c/compiler/control/OMROptions.cpp#L343
=> Fixes documentation of disableGLU Xjit option

compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/env/VerboseLog.cpp, compiler/env/VerboseLog.hpp, compiler/infra/OMRCfg.cpp, compiler/infra/OMRCfg.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
- introduce new verbose tag: "#METHOD STATS"
- print "key=value" pairs for each method where "key" is an arbitrary string
- values can be agrregated across all methods by a parsing script
- this format can be used for an arbitrary info about a compiled method
- in particular, introduce a function that prints various footprint
stats for a method
=> Implement METHOD STATS verbose output

compiler/optimizer/InductionVariable.cpp
`differenceInAdditiveConstants` is expected to be a 64 bit integer. `examineOpCodesForInductionVariableUse` takes care of casting it into `int32_t` if it does not use aladd and the adjustment or the replacing node is not a 64-bit value.
Fixes: eclipse-openj9/openj9#19220
=> Update differenceInAdditiveConstants as int64_t

compiler/aarch64/codegen/OMRCodeGenerator.hpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit changes addConstant32() and addConstant64() for AArch64 so that they don't generate instructions when the value to be added is 0.
=> AArch64: Stop generating instruction for adding 0

fvtest/porttest/omrtimeTest.cpp, fvtest/porttest/si.cpp
Remove unused local variable in fvtest which will cause build error
In **omrtimeTest.cpp**
In **si.cpp**
Changes
- omrtimeTest.cpp, replace for loop with while loop as variable 'j' isn't used
- si.cpp, remove l that not use as any purpose
=> Fix build error caused by unused variable in OSX

gc/base/Configuration.cpp
For Flat heap GCs, use OMRPORT_CPU_TARGET (rather than OMRPORT_CPU_ONLINE). It really is the number of h/w threads available to JVM process, if configured in a container or by some other OS specific means.
Same TARGET is used for other (and indirectly related) GC thread count caculation.
=> Use OMRPORT_CPU_TARGET for split list calculation

compiler/optimizer/DeadTreesElimination.cpp, compiler/optimizer/DeadTreesElimination.hpp
If the [`findOrCreateTreeInfo`](https://github.com/eclipse/omr/blob/8037ccd0406c017f6a8043a8d04e19ac68f626f2/compiler/optimizer/DeadTreesElimination.cpp#L66) function fails to find a `TreeInfo` object that refers to a particular `TR::TreeTop` in the `targetTrees` `List`, it allocates a new `TreeTop` instance using `trStackMemory`.  However, `findOrCreateTreeInfo` is called within a call tree from [`DeadTreesElimination::process`](https://github.com/eclipse/omr/blob/8037ccd0406c017f6a8043a8d04e19ac68f626f2/compiler/optimizer/DeadTreesElimination.cpp#L759).  The `process` method [creates a new `TR::StackMemoryRegion`](https://github.com/eclipse/omr/blob/8037ccd0406c017f6a8043a8d04e19ac68f626f2/compiler/optimizer/DeadTreesElimination.cpp#L761) on entry to the method, but the `targetTrees` …
=> Allocate TreeInfo objects using TR::Region of containing List

compiler/z/codegen/OMRTreeEvaluator.cpp
https://github.com/eclipse/omr/pull/6596 changed Z codegen to use `LLILF`+`IIHF` pairs (or some similar instruction sequence) in `genLoadAddressConstant` for all addresses in non-AOT compiles, on the basis that values in `LLILF`+`IIHF` pairs can be patched (see https://github.com/eclipse-openj9/openj9/pull/15705). For cases where we know the address does not need to be patched, we can take advantage of the shorter instruction sequences generated by `genLoadLongConstant` and `generateLoad32BitConstant`.
=> Z: Use general constant loads for addresses that don't need to be patched

compiler/optimizer/GlobalRegisterAllocator.cpp
Set live local index bit vector only when register candidate is created
Fixes: eclipse-openj9/openj9#19329
=> Set live local index bit vector only when register candidate is created

fvtest/porttest/si.cpp, thread/zos390/rasthrsup.c
The omrthread_get_ras_tid() function in rasthrsup.c was causing a segmentation fault with Open XL as pthread_t is structured in a different manner. This fixes that while keeping support with XLC. The header grp.h used in si.cpp also has a macro collision with the native locale header from Open XL. The reordering of headers is a workaround for the core problem. A issue has also been created in order to use a better macro name __grp.
(This is one part of the multiple changes added for supporting Open XL compilation on OMR)
=> Open XL segfault fix and workaround for si.cpp macro collision

compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/codegen/OMRInstruction.hpp, compiler/codegen/OMRInstructionFlagEnum.hpp, compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/il/OMRBlock.hpp, compiler/x/codegen/OMRCodeGenerator.cpp
OMR already provides warm and cold code cache and some platforms already
place some code into the cold cache, but not cold blocks. The goal is to
provide a capability of placing cold blocks into the cold cache. This can
help with the future footprint reduction work:
- find last warm block during tree lowering
- identify last warm instruction during instruction selection (currently, only in openj9)
- switch to the cold code cache after last warm instruction during binary encoding (currently, only on x platform)
- the code is only enabled if -Xjit:splitWarmAndColdBlocks option is on
=> Split warm and cold blocks

compiler/optimizer/OMRSimplifierHandlers.cpp, port/common/omrfilestream.c
* fix a use-after-free problem in `omrfilestream.c`
* fix a stringop-overflow error in `OMRSimplifierHandlers.cpp`
=> Fix build errors using gcc 13

compiler/compile/OMRNonHelperSymbols.enum, compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/VPHandlers.cpp, compiler/ras/Debug.cpp
Code in OMR supports the JIT compiler in generating IL to access the `J9Class` field `classDepthAndFlags` in the downstream OpenJ9 project. In many cases, that compiler code incorrectly refers to the field as `classAndDepthFlags`.
This commit adds new duplicate definitions of the methods and enum values to use the correct name.  Once the downstream project removes references to the obsolete methods, the obsolete definitions will be removed.
=> Correct typos mentioning classDepthAndFlags field

port/common/omrfilestream.c, port/common/omrport.tdf, port/win32/omrfilestream.c
It turns out that #7325 was ineffective: compilers see straight through that attempt to hide the use-after-close. The trace-point doesn't provide any information that isn't already available by other trace-points at the same level.
=> Remove trace-point that requires use-after-close reference

gc/base/MemoryManager.cpp, gc/base/MemoryManager.hpp
Fix code formatting according Coding Standards.
This change is non-functional intentially.
=> Fix formatting for MM_MemoryManager class

compiler/optimizer/Inliner.cpp
Set nodeCountThreshold to 16k for hot or above method compilations.
=> Set nodeCountThreshold to 16k for >= hot compilations

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/runtime/ARM64arrayCopy.spp
This commit improves the performance of arraycopy helpers for AArch64 by omitting alignment checks.
=> AArch64: Improve arraycopy helpers

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit improves the inlined code of arraycopy for AArch64, by using ldp/stp instructions with a pair of SIMD registers, which can load/store 32 bytes at a time.
=> AArch64: Improve arraycopy inlining

compiler/x/codegen/BinaryEvaluator.cpp, compiler/x/codegen/FPTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp
swept through x/codegen and replaced XORRegReg(64 bit) with XOR4RegReg(32 bit) when used to zero a register.
Closes: 7295
=> Use 32-bit XORRegReg to zero registers on x64

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/control/OMROptions.cpp, compiler/optimizer/OMRTransformUtil.cpp, compiler/optimizer/OMRTransformUtil.hpp, compiler/optimizer/ValuePropagationCommon.cpp, compiler/z/codegen/OMRCodeGenerator.cpp
A number of off-heap commits and a fix to lower trees bug on Z
Commit https://github.com/eclipse/omr/pull/7296/commits/5fea9955d0bc8286df5604b2fe774cb71f0d5078 copy the implementation of array access APIs from Openj9. Will be removed from OpenJ9 later.
=> Off Heap Changes and lowering trees bug

compiler/aarch64/codegen/BinaryEvaluator.cpp
This code fixes shiftHelper() in AArch64 codegen.
It generates a mov instruction when the shift amount is 0 and the reference count of the first child of a shift node is larger than 1.
=> AArch64: Handle shift amount 0

compiler/codegen/ScratchRegisterManager.cpp
The ScratchRegisterManager quietly returns NULL if it is unable to provide a scratch register.  This is actually a serious problem and the logic should assert fatally rather than return NULL.
=> Assert if ScratchRegisterManager is unable to provide a register

jitbuilder/CMakeLists.txt
The Azure CI macOS nodes on x86 have a version of Python later than 3.1
installed where the `assertRegexpMatches` function has been deprecated (and
replaced) in favour of `assertRegex`.
Ideally, this API would be replaced with the newer version.  However, some
nodes on the OMR CI farm have older versions of Python installed that need to
be upgraded first.
Until that happens, since x86 macOS is the only platform affected, the
JitBuilder API tests will be disabled  on that platform only.  There should be
adequate test coverage on the other x86 platforms.
Other alternatives considered were to sprinkle Python version checks throughout
the code to guard each API usage (which is messy), or downgrading the Python
version on the Azure builds.  However, I believe the right path forward is to …
=> Disable JitBuilder API generator tests on macOS on x86

gc/base/MemoryManager.cpp
Current heap allocation direction for zLinux is bottom-up. The motivation for this is on Z platforms shift operation executes faster for smaller shift value. However with bottom-up direction object heap takes all available memory below 4G bar. This does not allow Suballocator to expand if necessary and might lead to OOM below 4G bar. The intention for this fix is to improve this situation. Switching to top-down increases chances that less memory below 4G bar is going to be used (but worst case scenario still be the same as now). In order to keep smaller shift performance benefit an allocation shift scheme should stay 0-1-2-3-4. All other platforms still use 0-3-4. The behaviour for all other platforms has not been changed.
=> Use top-down direction for heap allocation on zLinux

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp
Implement an enhancement for byte array and char array System.arraycopy on x86-64.
Also add JIT options that disable array copy enhancement:
- `disableArrayCopyEnhancementByteArray`: Disable array copy enhancement for 8 bit primitive array
- `disableArrayCopyEnhancementCharArray`: Disable array copy enhancement for 16 bit primitive array
=> x86-64: Implement an enhancement for byte array and char array System.arraycopy

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/optimizer/GlobalRegisterAllocator.cpp, compiler/optimizer/GlobalRegisterAllocator.hpp, compiler/optimizer/OMRRegisterCandidate.cpp
PR #7303 added changes to improve the overhead of the global register allocator and PR #7328 fixed a bug in the newly introduced code.
Performance experiments have shown that while these changes reduce the CPU consumed by the JIT compilation threads by ~7.5%, they also cause throughput regressions on Daytrader (~1%), AcmeAIREE8 (~2%) and Ilog (~1%) benchmarks.
=> Revert GRA changes from PRs 7303 and 7328

compiler/il/AliasSetInterface.hpp
Replace some uses of TR_ASSERT_FATAL with static_assert in AliasSetInterface.hpp
Closes: [#4933](https://github.com/eclipse/omr/issues/4933)
=> Change TR_ASSERT_FATAL to static_assert in TR_AliasSetInterface

gc/base/standard/Scavenger.cpp, include_core/omrgcconsts.h
- define new unsuccessful state via high bit(31bit) of cycleType (bit31=1 cycle end unsuccessfully(abort), bit31=0 cycle end successfully)
- only passing the state to GC cycle end event via cycleType
- GC cycle end hooks can identify cycle abort case via the unsuccessful state.
=> Passing unsuccessful state to GC cycle end event

gc/base/j9mm.tdf
Adding a new tracepoint to provide extra details about Anonymous classes unloading process. Also added missed "Group" parameter to Trc_MM_clearheap tracepoint.
=> Add tracepoint for MM_cleanUpSegmentsInAnonymousClassLoader stats

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
This commit improves the instruction sequence for *select nodes with a *cmpeq node as the first child.
=> AArch64: Improve *cmpeq-*select instruction sequence

doc/CodingStandard.md
Issue: https://github.com/eclipse-openj9/openj9/issues/19261
Co-authored-by: Jason Feng <fengj@ca.ibm.com>
Co-authored-by: Keith W. Campbell <keithc@ca.ibm.com>
Signed-off-by: Amarpreet Singh <Amarpreet.A.Singh@ibm.com>
=> Update the coding standard

omr_static_lib/makefile
If make decides to build `OMR_VM.o` for `omr_static_lib`, it will not be able to find `mminitcore.h` because `$(top_srcdir)/gc/startup` is not on the include path (like it is in `omr/makefile`).
=> UMA: add missing include path

doc/SupportedC++Features.md
This patch updates the GCC version in the documentation and moves the corresponding C++11 features from the unsupported list to the supported list.
Issues: https://github.com/eclipse/omr/issues/7359
Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>
=> Update GCC version in C++ supported features documentation

omr_static_lib/makefile
Instead, it should assume that `omr/makefile` ensured all object files are up to date.
This reverts #7366 (which is unnecessary) and restores a rule for `$(OBJECTS)` (removed in #7177) that tolerates clock skew on build systems (it wasn't "useless" after all).
=> omr_static_lib/makefile should not compile anything

port/zos390/omrgenerate_ieat_dump.s
During Open XL bring up of OMR, a segmentation fault was seen while running the `omrporttest` target.
One of the load register instructions was meant to be loading the 64-bit address over which was not apparent while compiling with XLC. The problem manifested itself as a segmentation fault with Open XL, and this addresses that issue while keeping XLC working the same way.
=> Fix omrgenerate_ieat_dump.s assembly instruction to load 64 bit

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/il/OMROpcodes.enum, compiler/optimizer/LoopReducer.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/ArrayTest.cpp
Previously the arraycmp IL opcode's length child  was specified as 32 bits but was inconsistent in its use. This commit changes the specification of the length child to 64 bits, and normalizes the use to 64 bits.
Closes: #6992
=> Change arraycmp length child to 64 bits

compiler/x/codegen/OMRTreeEvaluator.cpp
This change applies to byte and char array System.arraycopy sequence. 
It avoids using vector instructions for copy size between 32 bytes to 64 bytes due to an observed regression.
=> x86-64: Use rep movs instructions if array copy size greater than 32 bytes

include_core/omrsig.h
The last uses are removed by https://github.com/eclipse-openj9/openj9/pull/19726.
=> Remove unused macro: sig_handler_t

compiler/optimizer/ValuePropagationCommon.cpp
The code populates the `TR::Node* array` variable if a non-zero offset exist.
The variable is passed to `generateArrayElementAddressTrees` which depends on if the variable is null to indicate a zero offset.
Given that the variable is not initialized to null a value may be passed causing wrong generated trees.
=> Initialize the array variable in generateArrayAddressTree to null

compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/VPHandlers.cpp
Since applying a shift or rotation to 0 simply produces 0 again, the optimizer can replace any shift or rotation for which the first child is a const 0 with a const 0.
Issue: [openj9 #19576](https://github.com/eclipse-openj9/openj9/issues/19576)
=> Replace redundant shifts and rotations of const 0 with const 0

gc/verbose/schema.xsd
new element "vgc:continuation-objects" is added in vgc:mem-info, 
the element with two integer addributes "total" and "started"
Signed-off-by: hulin <linhu@ca.ibm.com>
=> New element is added in vgc:mem-info

compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/VPHandlers.cpp
Changes to support OffHeap
* Add pinning array support for OffHeap by storing the pinning array in node extension.
* Add OffHeap support in constrainAnyIntLoad for valuePropagation
* Update LoopVersioner code to support OffHeap
=> OffHeap Changes

compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/ValuePropagationCommon.cpp
The transformation of Unsafe.copyMemory for OffHeap requires control flow changes which needs to be done in VP's DelayedTransformations list.
=> Add offHeapCopyMemory in VP DelayedTransformations

compiler/il/OMRNode.cpp, compiler/optimizer/InductionVariable.cpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/LocalAnalysis.cpp, compiler/optimizer/OMRLocalCSE.cpp, compiler/optimizer/OMROptimizer.cpp
Code disables localCSE for offheap and updates `createStoreForVar` to only store the baseArray (not the dataAddressPointer). Code to store pinningArray for offheap is in https://github.com/eclipse/omr/pull/7345 but not tested with commoning enabled yet.
Also changes to teach InductionVariable code on OffHeap tree structure.
=> Commoning and InductionVariable changes for OffHeap

compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/ValuePropagationCommon.cpp
Given that transformation is specific to OpenJ9 moving code to OpenJ9
https://github.com/eclipse-openj9/openj9/pull/19634 includes the OpenJ9 code.
https://github.com/eclipse-openj9/openj9/pull/19634#discussion_r1653189424
=> Move _offHeapCopyMemory delayedTransformation to OpenJ9

compiler/control/OMROptions.cpp
TR_UseHigherUserCounts now sets the intial scount to the value of initial count after the initial count has been set, to avoid the initial scount being set to -1
Measurements: when running acmeairee8 on OpenJ9 with
`-Xjit:useHigherMethodCounts -Xaot:useHigherMethodCounts`, there is a 2% throughput improvement with 2.3% start-up time increase
=> Option useHigherMethodCounts Now Correctly Sets the scount

compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/VPHandlers.cpp
It turns out the calls to `replaceNode` for the Value Propagation portion of this change are causing use/def info. to become invalidated and deleted.  However, the use/def info. is cached by Value Propagation and continues to be used until a point at which the memory that was associated with the use/def info. is reused.  That results in a crash due to memory corruption.
Reverts eclipse/omr#7364
Fixes eclipse-openj9/openj9#19782
=> Revert "Replace redundant shifts and rotations of const 0 with const 0"

compiler/il/OMRSymbol.cpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPHandlers.cpp
Remove reference to `Q` signature prefix in the JIT
Similar change as https://github.com/eclipse-openj9/openj9/pull/19799
Related to: eclipse/openj9#18157
=> ValueTypes: Remove reference to 'Q' signature prefix

compiler/infra/Bit.hpp
There are `isPowerOf2` methods defined in `Bit.hpp` for `int32_t` and `int64_t` values.  This change defines new `isPowerOf2` methods for values of type `uint32_t` and `uint64_t`.
Also added Doxygen comments for the various `isPowerOf2` methods.
This change doesn't introduce any uses of these methods in OMR, but I will be able to take advantage of them in a downstream project.
=> Define isPowerOf2 utility methods for unsigned

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/il/OMROpcodes.enum, compiler/optimizer/LoopReducer.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp, fvtest/compilertriltest/ArrayTest.cpp
Reapplies https://github.com/eclipse/omr/pull/7313.
Note for OpenJ9 that https://github.com/eclipse-openj9/openj9/pull/19332 must be merged together with this change.
=> Reapply "Change arraycmp length child to 64 bits"

compiler/runtime/OMRCodeCache.cpp
OMR::CodeCache::printOccupancyStats() prints to stderr various information about the code cache usage such as:
- Whether it's full or not
- The values for the warmCodeAlloc and coldCodeAlloc pointers
- How much space is available in the hole between warmCodeAlloc and coldCodeAlloc
- The list of freed blocks that are available for reuse
This commit adds a new line of output that shows the sizes of warm and cold sections of the code cache.
=> Adding more info to CodeCache::printOccupancyStats()

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/ras/DebugCounter.cpp, compiler/ras/DebugCounter.hpp, compiler/runtime/CMakeLists.txt, compiler/runtime/OMRCodeCache.cpp, compiler/runtime/OMRCodeCache.hpp, compiler/runtime/OMRRSSReport.cpp, compiler/runtime/OMRRSSReport.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp, doc/compiler/debug/RSSReport.md
- Implement a class that can monitor RSS status of any number of arbitry memory regions
- In addition to start address and size, region can have name, as well as a list of items describing its content
=> Implement RSSReport class

fvtest/compilertest/build/files/common.mk, jitbuilder/build/files/common.mk
https://github.com/eclipse/omr/pull/7349 added the new file OMRRSSReport.cpp. However, it did not add this to the jitbuilder and compilertest UMA build file list. This PR adds it to ensure that UMA builds of OMR are not broken.
=> Add OMRRSSReport.cpp to UMA build configs

compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/VPHandlers.cpp
Since applying a shift or rotation to 0 simply produces 0 again, the optimizer can replace any shift or rotation for which the first child is a constant 0 with that constant 0.
=> Replace shifts and rotations of constant 0 with constant 0

gc/CMakeLists.txt, gc/base/GCExtensionsBase.hpp, gc/base/j9mm.tdf, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/Scavenger.cpp, gc/stats/CPUUtilStats.cpp, gc/stats/CPUUtilStats.hpp, gc/stats/CollectionStatistics.hpp, gc/verbose/VerboseHandlerOutput.cpp, gc/verbose/schema.xsd
They are measured between GC STW points, excluding GC STW points
themselves. It is reported at GC start point in Verbose GC, but there
are also plans to use it for some future heuristics.
A sample report line, showing how and where it's reported:
```
<gc-start id="190" type="scavenge" contextid="189" timestamp="2024-07-22T09:17:33.286">
<cpu-util id="191" total="80.44" process="68.95" />
<mem-info id="192" free="1438506168" total="10737418240" percent="13">
```
=> CPU and process util stats

include_core/omrhookable.h, util/hookable/hookable.cpp
Add `J9HookInterface.J9HookUnreserve()` to clear flag `J9HOOK_FLAG_RESERVED`
`J9HookRegister()` sets flags `J9HOOK_FLAG_HOOKED | J9HOOK_FLAG_RESERVED`, `J9HookUnregister()` only clears `J9HOOK_FLAG_HOOKED`, add `J9HookUnreserve()` to clear `J9HOOK_FLAG_RESERVED`.
This supports an event to be `registered`, `unregistered`/`unreserved`, and `disabled`. Otherwise, an `unregistered` event can't be disabled by `J9HookDisable()` because of the presence of `J9HOOK_FLAG_RESERVED`.
Note: existing `J9HookUnregister()` only clears `J9HOOK_FLAG_HOOKED`, if it clears `J9HOOK_FLAG_RESERVED` as well, some tests such as [cmdLineTester_decompilationTests](https://github.com/eclipse-openj9/openj9/blob/5e3816d311ca2d4daeb315c8687d6d1d87e6234f/test/functional/cmdLineTests/jvmtitests/playlist.xml#L661) hangs. …
=> Add J9HookInterface.J9HookUnreserve() to clear flag J9HOOK_FLAG_RESERVED

compiler/z/codegen/S390Debug.cpp
Some of the unused methods from S390Debug.cpp have builtin function calls that are unsupported by Open XL and require inline assembly. As per recommendation, removing these unused/dead code methods as there are no other references to it outside.
=> Remove dead code from S390Debug.cpp

gc/verbose/schema.xsd
The `<sequence>` element may not be repeated, otherwise schema validation fails:
```
>> 2024 Wed Jul 24 15:55:21 20240724 15:55:19- org.xml.sax.SAXParseException: s4s-elt-invalid-content.1: The content of 'gc-start' is invalid.  Element 'sequence' is invalid, misplaced, or occurs too often.
>> 2024 Wed Jul 24 15:55:21 	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
>> 2024 Wed Jul 24 15:55:21 	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
>> 2024 Wed Jul 24 15:55:21 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
>> 2024 Wed Jul 24 15:55:21 	at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
>> 2024 Wed Jul 24 15:55:21 	at …
```
=> Fix definition of gc-start element

compiler/compile/OMRCompilation.hpp
This method reports the failed compilation and then unconditionally throws an Exception(), and hence never returns.
=> Annotate failCompilation with OMR_NORETURN

compiler/optimizer/Inliner.cpp
- Create debug counters correctly for removed call sites
- Specify the current compilation in failed call site debug counter names
=> Fix and improve debug counters for failed call sites

compiler/optimizer/VPConstraint.cpp
This will allow reference comparisons to be folded to "not equal" more often. Previously `VPClass::mustBeNotEqual()` would return true only when the constraints could be distinguished by:
- known null vs. known non-null,
- known object index (when both are known to be non-null), or
- fixed-class class pointer (when both are known to be non-null).
Now most of the cases where it returns true require only one of the two constraints to forbid null. Additionally, the constraints can now also be distinguished by:
- location (heap, stack, class object),
- array element size,
- array length,
- class object type bound (non-fixed), and
- instance type bound (fixed or not).
=> Improve VPClass::mustBeNotEqual()

compiler/optimizer/VPConstraint.cpp
In 5aba990c724f7bd7 the improved `VPClass::mustBeNotEqual()` mistakenly returned false instead of true for arrays with different lengths. This commit corrects that case to return true as intended. This was not a functional problem because false is a conservative result.
=> Make a minor correction to improved VPClass::mustBeNotEqual()

fvtest/porttest/omrmemTest.cpp, gc/base/GCExtensionsBase.hpp, gc/base/MemoryManager.cpp, include_core/omrgcconsts.h, include_core/omrport.h, port/common/omrmem32helpers.c, port/common/omrmem32struct.h, port/common/omrport.c, port/common/omrportcontrol.c, port/omrportpriv.h
1. Use VMEM_ALLOC_QUICK by default for allocateRegion in
allocate_memory32
2. Adds -Xgc:suballocatorQuickAllocDisable option that
disables the default VMEM_ALLOC_QUICK
3. Adds -Xgc:suballocatorIncrementSize option that replaces the
HEAP_SIZE_BYTES macro and controls the heap increment size
4. Adds an omrport_copy_suballocator_globals procedure that correctly
initializes the PPG suballoctor globals for memCheckPortLib when
-Xcheck is provided
5. Updates related documentation
Addresses: https://github.com/eclipse/omr/issues/7190
Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>
=> Add Xgc options for suballocator heap size and quick allocation

compiler/optimizer/VPConstraint.cpp
This is the code from before 5aba990c724f7bd7.
=> Reinstate original VPClass::mustBeNotEqual() logic temporarily

fvtest/porttest/omrmemTest.cpp, gc/base/GCExtensionsBase.hpp, gc/base/MemoryManager.cpp, include_core/omrgcconsts.h, include_core/omrport.h, port/common/omrmem32helpers.c, port/common/omrmem32struct.h, port/common/omrport.c, port/common/omrportcontrol.c, port/omrportpriv.h
Reverts eclipse/omr#7414
See https://github.com/eclipse/omr/pull/7414#issuecomment-2265837658
=> Revert "Add Xgc options for suballocator heap size and quick allocation"

compiler/il/OMRBlock.cpp, compiler/il/OMRNode.cpp
Include dataAddr pointer check with ArrayRef check when unocmmoning
a node.
Previously, only aiadd or aladd could be used for array access but with
offHeap, dataAddr pointer nodes (aloadi) can also be used for array access.
Hence we must check for dataAddr pointer and ArrayRef when uncommoning a node.
=> Update node uncommoning for offHeap

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
- during code cache disclaim, it's beneficial to move OOL code into warm code cache
=> Move out-of-line instructions to warm cache

compiler/x/codegen/OMRTreeEvaluator.cpp
Use `rep movsw` to copy multiple of 2 bytes for copy size greater than the threshold (32 bytes), which performs better than `rep movsd` for CascadeLake and later CPUs.
Setting env variable `TR_UseREPMOVSWFor16BitPrimitiveArrayCopy` forces to use `rep movsw`.
Setting env variable `TR_UseREPMOVSDFor16BitPrimitiveArrayCopy` forces to use `rep movsd`.
=> x86-64: Select REP MOVS instruction based on CPU for char arraycopy

compiler/codegen/OMRCodeGenPhase.cpp, compiler/codegen/OMRCodeGenerator.cpp, compiler/codegen/OMRCodeGenerator.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/x/codegen/OMRCodeGenerator.cpp
- during code cache disclaim, it's beneficial to move snippets into warm code cache
- controlled by -Xjit:moveSnippetsToWarmCode option
=> Move snippets to warm code

compiler/p/codegen/OMRTreeEvaluator.cpp
Add runtime array check to generated assembly code for Unsafe.setMemory() on PPC and, when offheap/balanced GC policy is in use, generate assembly code to perform an arrayCHK and, if the object _is_ an array, adjust the arguments as follows:
- Load and pass in the dataAddr pointer as the base address of the object being operated on
- ~Subtract the array header size from the offset~ _no longer necessary due to this change_: https://github.com/eclipse-openj9/openj9/pull/19326
In addition, as a performance improvement for both the offheap and gencon cases on P8 and up, use vector instructions (`stxvd2x` and, on P10 only, `stxvl`) to reduce loop iterations when setting bytes in memory to specified value.
Depends on: https://github.com/eclipse-openj9/openj9/pull/18288
=> Adjust arguments to Unsafe.setMemory() on PPC when offheap is enabled

compiler/compile/OMRSymbolReferenceTable.cpp, compiler/compile/ResolvedMethod.cpp, compiler/compile/ResolvedMethod.hpp
=> Remove unused cpIndex parameter of vTableSlot(), virtualCallSelector()

compiler/z/codegen/OMRPeephole.cpp, compiler/z/codegen/OMRPeephole.hpp
A 32 bit load instruction followed by a zero/sign extend instruction can be replaced with an equivalent load and zero/sign extend instruction.
Here are all the replacements done by this peephole:
| opcode         | `LGFR  R1,R1`  | `LLGFR  R1,R1`   |
| -------------- | -------------- | ---------------- |
| `L     R1,M1`* | `LGF   R1,M1`* | `LLGF   R1,M1`*  |
| `LH    R1,M1`* | `LGH   R1,M1`* | *N/A*            |
| `LLH   R1,M1`* | *N/A*          | `LLGH   R1,M1`*  |
| `LB    R1,M1`* | `LGB   R1,M1`* | *N/A*            |
| `LLC   R1,M1`* | *N/A*          | `LLGC   R1,M1`*  |
| `XR    R1,R1`  | `XGR   R1,R1`  | `XGR    R1,R1`   |
| `IILF  R1,I1`  | `LGFI  R1,I1`  | `LLILF  R1,I1`   |
| `LHI   R1,I1`  | `LGHI  R1,I1`  | `LLILF  R1,I2`** |
| `LR    R1,R2`  | `LGFR  R1,R2`  | `LLGFR  R1,R2` …
=> Z peephole: Remove unnecessary L(L)GFR

third_party/pugixml-1.8/makefile
Some downstream projects building with OMR do not use CMake.  When pugixml was updated to version 1.8 the makefile was omitted (it was actually a file ignored by git).  The 1.5 makefile builds 1.8 correctly.
This PR re-introduces that makefile for such downstream projects.
=> Re-introduce makefile for pugixml-1.8

compiler/optimizer/VPHandlers.cpp
To this point, VP has constrained the length of an array in `constrainAload` to be between 0 and `TR::getMaxSigned<TR::Int32>() / elementSize` elements long. This was likely a due to a historical limitation. Since arrays can be longer than `TR::getMaxSigned<TR::Int32>()` bytes, if such an array were copied, it would fail the `ArrayCopyBNDCHK`, causing erroneous removal of trees that would prevent the copy from being performed. I discussed my findings during my investigation of this issue in a series of comments in [openj9 #19247](https://github.com/eclipse-openj9/openj9/issues/19247#issuecomment-2134018832).
This PR increases the high bound of the constraint on the length of an array in `constrainAload` by using `J9::ObjectModel::maxArraySizeInElements()` instead, which produces a better …
=> Fix underestimation of array length in constrainAload

omrsigcompat/makefile
@keithc-ca moved the `omrsigcompat/makefile` change/fix to its own separate PR.
=> Update omrsigcompat makefile artifact type to cxx_shared

compiler/z/codegen/OMRCodeGenerator.hpp
warning: shifting a negative signed value is undefined [-Wshift-negative-value]
return ((-1ll) << 31) - 1;}   // min 32bit signed integer minus 1
Changes here attempt to resolve this to a more correct approach.
@keithc-ca Not sure if we settled on something specific for this item, but creating a placeholder PR for it from what I had retained with and to continue discussions/suggestions here.
=> Fix -Wshift-negative-value Open XL warning in OMRCodeGenerator.hpp

cmake/modules/platform/os/zos.cmake, port/zos390/omrtty.c, util/a2e/atoe.c, util/a2e/headers/_Ccsid.h, util/a2e/headers/arpa/inet.h, util/a2e/headers/atoe.h, util/a2e/headers/ctype.h, util/a2e/headers/dirent.h, util/a2e/headers/dll.h, util/a2e/headers/fcntl.h, util/a2e/headers/grp.h, util/a2e/headers/langinfo.h, util/a2e/headers/locale.h, util/a2e/headers/netdb.h, util/a2e/headers/old-stdio.h, util/a2e/headers/old-stdlib.h, util/a2e/headers/pwd.h, util/a2e/headers/spawn.h, util/a2e/headers/stdio.h, util/a2e/headers/stdlib.h, util/a2e/headers/string.h, util/a2e/headers/strings.h, util/a2e/headers/sys/ipc.h, util/a2e/headers/sys/stat.h, util/a2e/headers/sys/time.h, util/a2e/headers/sys/utsname.h, util/a2e/headers/time.h, util/a2e/headers/unistd.h
When compiling with omr_ascii option, there is an alternative notation to pass in the a2e header wrappers with Open XL using the -isystem option. While making this work, it was also suggested to cleanup the PREFIXPATH(header) notation to simply use #include_next which supports and works with both XLC and Open XL on z/OS.
=> Tweak a2e header wrappers for Open XL compliance

gc/base/SparseAddressOrderedFixedSizeDataPool.cpp, gc/base/SparseAddressOrderedFixedSizeDataPool.hpp, gc/include/RootScannerTypes.h, gc/verbose/schema.xsd
- Remove double mapping related entities.
- Record allocObjectCount in Sparse Heap.
- Update verbosegc schema for new off heap related elements \
New sub element\<offheap-objects objects=nnn allocatedBytes=nnn\> in \<mem-info\> .
New element \<offheap candidates=nnn cleared=nnn\> in group \<gc-op-copy-forward\> and group  \<gc-op-mark\>.
=> Off-Heap related update

compiler/optimizer/LocalOpts.cpp, compiler/optimizer/OMRSimplifierHelpers.cpp, compiler/optimizer/OMRSimplifierHelpers.hpp
This PR contains the following 2 commits:
1 - Teach Simplifier to detect conditional branches that have fallthrough
blocks that are goto blocks to the same target.
For example:
```
n223n     BBStart <block_18> (freq 1) (cold)
n210n     ifacmpeq --> block_17 BBStart at n219n ()
n208n       aload  <temp slot 5>[#529  Auto] [flags 0x7 0x0 ]
n209n       aconst NULL (X==0 X>=0 X<=0 )
n224n     BBEnd </block_18> (cold) =====
n227n     BBStart <block_19> (freq 1) (cold)
n226n     goto --> block_17 BBStart at n219n ()
n228n     BBEnd </block_19> (cold) =====
```
This complements the symmetrical case where the conditional branch
goes to the fallthrough block, which is already detected and removed by
Simplifier.
2 - Make conditional branches with a fallthrough goto block to the branch
target …
=> Optimize trivial branches obscured by goto blocks on the fall-through path

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
Added an option that makes the client request a list of cached methods from the server on bootstrap, and set the count for those methods as scount to improve rampup
=> Client Request Cached Methods List from JIT Server

omrsigcompat/makefile
Reverts changes from https://github.com/eclipse/omr/pull/7435
=> Reverts omrsigcompat artifact type to c_shared

compiler/x/codegen/OMRTreeEvaluator.cpp
Optimize arraycopy sequence if copy size is constant and less than or equal to 64 bytes. This feature can be disabled by env variable `TR_DisableArrayCopyInlineSmallSizeConstantCopySize`.
Create `generateMemoryCopyInstructions` that loads and stores memory based on specified register size. This method is used by multiple arraycopy inline methods to reduce the repetition of the same code.
Update `generateArrayElement{Load|Store}` to include vector registers and instructions.
=> x86: Optimize arraycopy with constant copy size

compiler/aarch64/codegen/ARM64Debug.cpp, compiler/aarch64/codegen/ARM64Instruction.hpp, compiler/aarch64/codegen/GenerateInstructions.cpp, compiler/aarch64/codegen/GenerateInstructions.hpp, compiler/aarch64/codegen/OMRInstOpCode.hpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/ras/Debug.hpp
This commit replaces the use of magic numbers for the limitation immediate for `dmb` instructions with an enum, and adds a debug printer for synchronization instructions to print out the limitation mnemonic rather than the literal hex constant.
=> AArch64: Use enum for dmb limitations

compiler/optimizer/OMRSimplifierHandlers.cpp
The `fmaxminSimplifier` and `dmaxminSimplifier` methods were returning the wrong value when given (+0, -0). This change handles +-0 edge case to return the 0 with the correct sign (+0 is strictly greater than -0). 
Supports change in https://github.com/eclipse/omr/pull/7464 and https://github.com/eclipse-openj9/openj9/pull/20185  (needed for [20185](https://github.com/eclipse-openj9/openj9/pull/20185) to pass)
@r30shah
=> Fix fmin/fmax/dmin/dmax node simplifier for const  0s

compiler/optimizer/RedundantAsyncCheckRemoval.cpp, compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, fvtest/compilerunittest/p/BinaryEncoder.cpp
Adds lbarx, lharx, stbcx_r and sthcx_r instruction support for Power. These instructions are not currently in use but will be needed for future enhancements targetting CAS on byte and short length data.
Updates willBeEvaluatedAsCallByCodeGen to reflect the new acceleration of Unsafe compareAndExchange methods on X.
Edit:
X changes are dependent on this OpenJ9 PR:
https://github.com/eclipse-openj9/openj9/pull/19991
Behavior of `inlineCompareAndSwapNative` and `inlineCompareAndSwapObjectNative` in `J9TreeEvaluator.cpp` must match behavior in `willBeEvaluatedAsCallByCodeGen` in `OMRCodeGenerator.cpp`
=> Accelerate Unsafe CAS Intrinsics on Power and X

compiler/optimizer/ValuePropagationCommon.cpp
Guarantee that `newarray`s generated from transformations of array clone calls will always be zero initialized, ensuring array allocation is done inline, whether `TR_disableSkipZeroInitInVP` is enabled or not.
While investigation and development into a fix for a bug caused by corruption of a TLH pointer forcing out of line array allocation when we skip zero initialization is ongoing, this PR will provide a temporary performance boost at the (rare and minor) expense of occasional zero initialization of arrays that don't need to be zero initialized.
=> Guarantee new array will be zero initialized in transformArrayCloneCall

compiler/optimizer/ValuePropagationCommon.cpp
The utility method `checkArrayCompClassPrimitiveValueType` has been renamed `testIsArrayClassNullRestrictedType`, to reflect more recent terminology, and it no longer expects an "if" OpCode argument. Instead, it generates IL that yields a zero or non-zero result to indicate whether the array is null-restricted.  This change updates uses of that method to branch appropriately based on the result of the IL produced by `testIsArrayClassNullRestrictedType`.
This change is in OpenJ9-specific code.
=> Update uses of checkArrayCompClassPrimitiveValueType

compiler/x/codegen/OMRMemoryReference.cpp
The assert on IS_32BIT_SIGNED for displacement in estimateBinaryLength() no longer accurately reflects expected behavior. When using a debug build, coming from the caller in [OMR::X86::AMD64::MemoryReference::estimateBinaryLength()](https://github.com/eclipse/omr/blob/13d47ea4def377422793a23813b6b25c76bbd56d/compiler/x/amd64/codegen/OMRMemoryReference.cpp#L382), it is possible to hit this assert with a non-null _addressRegister and a displacement that is > 0x7FFFFFFF (for example, displacement=0x80000000, which is not a valid signed 32-bit int) since the control flow changed in https://github.com/eclipse/omr/pull/6937. The code appears to function correctly, except for hitting the assert (and, indeed, with the assert disabled or in a non-debug build there is no problem). The scenario …
=> Remove no longer valid assert in OMRMemoryReference

doc/SupportedC++Features.md
Also add missing platforms (Arm Linux and macOS).
Removed XLC for Linux as Eclipse OMR does not have a means of evaluating
the latest compiler versions as part of its CI builds.
Issue #7359
=> [skip ci] Update minimum supported compiler levels and fix documentation links

compiler/p/codegen/OMRConstantDataSnippet.cpp
POWER patches class unload constants by `value |= 1` of a 32bit value given it might be an instruction, to correctly invalidate the constant we offset the `acursor` differently for LE and BE to overwrite the least-significant bit in the constant.
Closes eclipse-openj9/openj9#20263
Maybe eclipse-openj9/openj9#20261
Maybe eclipse-openj9/openj9#19884
=> Add the correct address as ClassUnloading PicSite in POWER LE

compiler/control/OMROptions.hpp
The old value (`0x006F0000`) included `0x00020000` and `0x00200000` which are currently unused.
The value should have been `0x004D0000` which is now expressed by or-ing the included sub-options, with a comment noting that `TR_TraceAliases` is intentionally omitted.
=> Correct the definition of TR_TraceAll

port/linux/omrvmem.c
Even if the ftruncate() system call succeeds, this does not guarantee that the underlying filesystem has enough free blocks to support whatever increase in file size that was requested. This can cause SIGBUS errors if writes are attempted in the file.
The fallocate() call does guarantee that there is enough space available.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20239
=> Use fallocate instead of ftruncate

doc/SupportedC++Features.md
Some features were moved from the unsupported list to the supported list because they were previously specified to be blocked by an older GCC version. They are actually blocked by the XLC version, and need to be re-added to the unsupported list.
Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>
=> Specify unsupported features blocked by XLC v2r1

compiler/env/FrontEnd.cpp, compiler/env/FrontEnd.hpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/ValuePropagationCommon.cpp
(1) Add front end `getNullRestrictedArrayClassFromComponentClass`  to retrieve null restricted array class
(2) Rename `isArrayCompTypePrimitiveValueType` to `isArrayNullRestricted` to reflect the updated logic
(3) Fix array load in `transformNullRestrictedArrayCopy`
**Depends on** 
**Related:** https://github.com/eclipse-openj9/openj9/issues/19914, https://github.com/eclipse-openj9/openj9/issues/19913
=> Fix null restricted array related issues for value types

compiler/il/Aliases.cpp, compiler/optimizer/RedundantAsyncCheckRemoval.cpp, compiler/z/codegen/ControlFlowEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp
- Enables inlining of fmin/fmax/dmin/dmax nodes
- Implements IEEE-754 standard for the evaluators:
- if the first arg is a NaN, returns the corresponding quiet NaN, same for if only the second arg is a NaN
-  Refactors `xmaxxminhelper` to infer correct compare/branch/move instructions based on datatype; helper does not change NaNs, so can be used in other min/max evaluators which can extend the behaviour on NaNs as they see fit
- Uses vector operations when available, defaults to branching if not
- Supports inlining for https://github.com/eclipse-openj9/openj9/pull/20185
Depends on OMR Simplifier change https://github.com/eclipse/omr/pull/7471 (needed for https://github.com/eclipse-openj9/openj9/pull/20185 to pass)
https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34283/
=> Support IEEE-754 for fmin/fmax/dmin/dmax nodes

compiler/optimizer/RedundantAsyncCheckRemoval.cpp
Support for acceleration of `compareAndExchange[Int|Long|Reference]` has been extended to Z. As a result, the check in
`callDoesAnImplicitAsyncCheck` needs to be updated as well.
Edit:
Should be checked in before: https://github.com/eclipse-openj9/openj9/pull/20308
Ideally merged as a pair.
=> Accelerate Unsafe CAS Intrinsics on Z

compiler/ras/CallStack.cpp
When building Open J9, Open XL throws an error building CallStack.cpp as extern builtins unsupported. This adds the appropriate alternative that works with Open XL and allows compilation.
=> Fix builtin __gdsa function call for Open XL

compiler/optimizer/ValuePropagationCommon.cpp, include_core/unix/zos/edcwccwi.h, util/a2e/atoe.c, util/a2e/headers/stdio.h
Changes along with the diagnostic flags:
compiler/optimizer/ValuePropagationCommon.cpp [-Wsometimes-uninitialized]
include_core/unix/zos/edcwccwi.h [-Wtrigraphs]
util/a2e/atoe.c [-Wwritable-strings]
util/a2e/headers/stdio.h [-Wwritable-strings]
=> Fix Open XL compiler warnings

compiler/codegen/NodeEvaluation.cpp, compiler/il/OMRNode.cpp
Set up an assertion to ensure OMR::Node::setEvaluationPriority is only called for nodes not at treetops, and guard against any calls made for nodes at treetops; prevent the assertion failure if the node is also a guard.
=> Set Evaluation Priority Only For non-Treetop Nodes

fvtest/threadextendedtest/processTimeTest.cpp, include_core/thread_api.h, thread/common/thrprof.c
This function returns the user and system cpu time of the calling thread.
This new function is needed so we can get both user time and
system time using only one system call.
Related: https://github.com/eclipse-openj9/openj9/pull/20186
=> Add omrthread_get_thread_times()

example/glue/ArrayletObjectModel.hpp, gc/verbose/VerboseHandlerOutput.cpp, gc/verbose/schema.xsd
- Report offheap bytes in <allocated-bytes> for off-heap enabled case vs arrayletleaf bytes for off-heap disabled case.
- Remove unuse function fixupDataAddr in example/glue
=> Update verbosegc allocation stats for off-heap

compiler/x/codegen/OMRInstOpCode.cpp, compiler/x/codegen/OMRInstOpCode.hpp, compiler/x/codegen/OMRX86Instruction.cpp
We discovered an issue when trying to add BMI2 instructions which are non-vector instructions using the VEX prefix. BMI2 instructions could not be correctly generated if AVX is unavailable.
=> x86: Support BMI2 instructions

compiler/ras/Debug.cpp
While looking into the JIT compilation log, I bumped into the case where bunch of jProfiling Value place holder calls were printed as unknown in the log, as it was missing from the Debug.cpp. Commit in this PR adds it.
=> Add jProfilingValue symbols to list of in Debug.cpp for tracing

port/unix/omrsysinfo.c
`retrieveLinuxCgroupMemoryStats()` used to return an error failure if `swappiness` cannot be determined. However, `swappiness` is not available for Cgroup v2. Moreover, `swappiness` is not a critical factor, while knowing the memory limits for your container typically is.
This commit changes `retrieveLinuxCgroupMemoryStats()` to return a success code if the only information that could not be retrieved is the `swappiness`. The value of the returned `swappiness` is set to `OMRPORT_MEMINFO_NOT_AVAILABLE` in this case.
Fixes: https://github.com/eclipse/omr/issues/7453
=> Do not fail retrieveLinuxCgroupMemoryStats if swappiness is unavailable

compiler/optimizer/OMRCFGSimplifier.cpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/ras/Debug.cpp, compiler/z/codegen/BinaryEvaluator.cpp, compiler/z/codegen/ControlFlowEvaluator.cpp, compiler/z/codegen/OMRMachine.cpp
Suppresses warnings when building on OpenXL
Warnings:
- uninitialized variables
- enum values not handled in switch
- Assignment inside if statement condition
https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34234/
=> Fix OpenXL Warnings

compiler/compile/OMRMethod.cpp, compiler/compile/OMRMethod.hpp, compiler/compile/ResolvedMethod.cpp, compiler/optimizer/RedundantAsyncCheckRemoval.cpp
Support for acceleration of `compareAndExchange[Int|Long|Reference]` has been extended to Arm. As a result, the check in
`callDoesAnImplicitAsyncCheck` needs to be updated as well.
Cleans up `isUnsafeCAS` and `isUnsafeWithObjectArg` to remove unused comp parameter.
Needs to be check in with:
https://github.com/eclipse-openj9/openj9/pull/20432
Due to the changes to the parameters of `isUnsafeCAS` and `isUnsafeWithObjectArg`.
=> Accelerate Unsafe CAS Intrinsics on Aarch64

compiler/ilgen/OMRIlBuilder.cpp, compiler/ilgen/OMRIlBuilder.hpp, compiler/optimizer/DebuggingCounters.cpp, compiler/x/codegen/DataSnippet.cpp
Fixes up some of the JitBuilder logging output for consistency and completeness.
Also resolves 2 compiler warnings around shifting of negative constant values, and iterating with a signed variable with an unsigned trip count. It also combines two printf calls in a row (second one just printed "\n").
=> Fix jb logging and a few compiler warnings

port/win32/omrsysinfo.c, thread/common/thrprof.c
Fixes: https://github.com/eclipse-omr/omr/issues/7504
=> Use ULARGE_INTEGER to get time value from FILETIME on Windows

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
This option will be used by a new feature in OpenJ9 and will, at some point, be inverted to disable the functionality rather than enable.
=> Add JIT option to enable SCC disclaiming

compiler/aarch64/codegen/ControlFlowEvaluator.cpp
While testing jb2 on my macbook, I ran into a crash in JIT asking an ifcmp node if it was a method pointer constant, which should only be asked of aconsts or loadaddrs. There was an obvious typo asking this question of "node" rather than "secondChild" so this fixes that typo.
=> Aarch64: Fix isMethodPointerConstant call on wrong node

compiler/x/codegen/DataSnippet.cpp
Shifting a negative signed value as was done here produces a clang warning about undefined behaviour.
=> Avoid shifting negative signed value

compiler/aarch64/codegen/UnaryEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/codegen/NodeEvaluation.cpp, compiler/codegen/OMRCodeGenerator.cpp, compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp, compiler/infra/TreeServices.cpp, compiler/optimizer/CopyPropagation.cpp, compiler/optimizer/GeneralLoopUnroller.cpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/LocalOpts.cpp, compiler/optimizer/LoopReducer.cpp, compiler/optimizer/LoopVersioner.cpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/StripMiner.cpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPHandlers.cpp, compiler/optimizer/ValuePropagationCommon.cpp, compiler/p/codegen/OMRMemoryReference.cpp, compiler/p/codegen/UnaryEvaluator.cpp, compiler/x/amd64/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/UnaryEvaluator.cpp, compiler/x/i386/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/BinaryCommutativeAnalyser.cpp, compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRMemoryReference.cpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/UnaryEvaluator.cpp
The old opcodes had the letter i as a prefix if the operation was indirect. Those opcodes were renamed to use the letter as a suffix instead.
This commit cleans up the references to the old opcodes, iiload/iistore ilload/ilstore iaload/iastore ibload/ibstore, to iloadi/istorei lloadi/lstorei aloadi/astorei bloadi/bstorei in the code comments and trace messages.
Related: eclipse-openj9/openj9#19489
=> Clean up references to old opcodes

compiler/p/env/OMRCPU.cpp, port/unix/omrsysinfo.c
POWER11 recognition macro is defined before it is officially available from AIX system header files. A catch-all macro for future processors is defined as well.
=> Recognize POWER11 and future coverage on AIX

compiler/optimizer/InductionVariable.cpp, compiler/optimizer/OMRTransformUtil.cpp, compiler/optimizer/OMRTransformUtil.hpp
To prevent double hoisting of dataAddr pointer, limit reassociation and hoisting criteria to include only those that have dataAddr pointer as their first child.
The offset node doesn't rely on array header size when using dataAddr pointer to get to data elements so no need for reassociation; we can use the original offset node with newly hoisted array load node.
=> Fix loop strider reassociation and hoisting logic for off-heap

port/unix/omrsysinfo.c
"power11" patch for Linux kernel was upstreamed a couple months ago. the
recognition mechanism involves comparing it with AT_PLATFORM.
=> Recognize POWER11 on Linux

thread/exports.cmake
This is missed in https://github.com/eclipse-omr/omr/pull/7491
=> Export omrthread_get_thread_times()

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp
- pack Mask into a long
- at least in the current VectorAPI implementation, bits are packed
in reverse order
- for a mask [true, false, false, .... false] returns 0x01
- for a mask  [false, false, ... false,  true] returns 0x8000
=> Implement mToLongBits evaluator on Power for Byte type

compiler/il/OMRNode.cpp
To avoid having to handle cases of pinning array movement, disable commoning of the dataAddr internal pointer.
(Addendum to https://github.com/eclipse/omr/commit/c86da7e3aae883dd226d3a23c1010e01cb4d2dbc)
=> Disable commoning of dataAddr Pointer in createStoresForVar()

compiler/control/OMROptions.cpp
As documented in https://github.com/eclipse-openj9/openj9/issues/9712, initial attempt to fix the SplitPostGRA to work with RegDepCopyRemoval resulted in 5% regression in performance throughput on x86 which required us to disable the RegDepCopyRemoval when value types are enabled. Later on the performance issue was addressed and fixed. This PR reverts the change that disabled RegDepCopyRemoval when value types are enabled.
=> Re-enable RegDepCopyRemoval for value types

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp
- Returns the index of the first mask lane that is set.
- Returns vector length if none of them are set.
=> Implement mFirstTrue evaluator on Power for Byte type

doc/compiler/memory/MemoryManager.md, doc/compiler/optimizer/BenefitInliner.md, doc/compiler/optimizer/DataFlowEngine.md, doc/compiler/optimizer/IntroLoopOptimizations.md, doc/compiler/optimizer/IntroReadLogFile.md, doc/compiler/optimizer/ValuePropagation.md, doc/compiler/riscv/Building.md, doc/port/sockets.md
The copyright date was set to the date of the initial contribution.
=> Add missing copyright headers to .md files

compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp
- create a helper for a common but not trivial code sequence
=> Create OMR::Node::storeToAddressField() helper

compiler/control/OMROptions.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp
This commit increases arraycopyRepMovs*ArrayThreshold:
- Byte and char arraycopy: from 32 bytes to 64 bytes
- Int and long arraycopy: from 32 bytes to 64 bytes or 128 bytes if AVX-512 is supported
=> x86: Increase inline arraycopy threshold

compiler/compile/OMRCompilation.cpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/ras/Debug.cpp, compiler/ras/Debug.hpp, compiler/ras/Tree.cpp, compiler/x/codegen/X86Debug.cpp, compiler/z/codegen/S390Debug.cpp, doc/compiler/CompilerOptions.md
"Address masking" was an attempt to make compiler log files easier to compare by preventing addresses (that are likely to change between compilations) from being printed raw in a compilation log.  It worked by intercepting the "printf" family of IO functions and checking whether any addresses were being printed with the `%p` format specifier, and instead of printing the address a "Masked Address" string was substituted instead.
This feature was introduced at a time when text file comparison tools were not as robust as they are today and many addresses are output to the log without using `%p` making this feature less effective.  Since it adds overhead and complexity to the logging path, has incomplete coverage, and is not widely used (if at all), remove it from the code base.
Removing …
=> Remove compiler ras address masking

compiler/optimizer/OMRTransformUtil.hpp
The parameter was added in https://github.com/eclipse-omr/omr/pull/7509/files but I forgot to add it to the Doxygen method comment.
=> Add missing parameter to method comment

gc/base/SparseVirtualMemory.cpp
Commit on all existing platforms will implicitly (and likely lazily) zero the address range, since we are currently creating Offheap with anonymous small pages.
Hence we are removing our explicit zero call (which was already the case of xLinux).
=> Don't zero Offheap after commit

gc/base/SparseVirtualMemory.cpp
For some reason OSX does not seem to zero memory on commit, unless it's
the first commit. For now, till we understand if there is a way to force
zero on subsequent re-commits, we will zero it explicitly.
Including zPTF as well, since we don't know how it will behave, even
if/when it adds support for commit/decommit/virtual-memory.
=> Zero offheap on commit on OSX

compiler/env/FEBase.cpp, compiler/ras/Debug.cpp, compiler/ras/Debug.hpp
Codependent on https://github.com/eclipse-openj9/openj9/pull/20667
=> Pass indent size rather than buffer to TR_Debug::printByteCodeStack

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
These options are required for https://github.com/eclipse-openj9/openj9/pull/20712.
=> Add AOT dependency tracking verbose options

compiler/control/OMROptions.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp
This reverts commit e934391bcc27c5db207431ec6601a5e9788feb7d, reversing changes made to 5ff6dd7c8ed2dae194ade8f31d276b538133ffb6.
This reverts PR #7534 and reduces the thresholds for arraycopy REP MOVS instructions back to 32 bytes.
This addresses the performance regression reported in the internal issue 482.
=> Revert "Merge pull request #7534"

compiler/x/codegen/OMRTreeEvaluator.cpp
If XMM is declared as TR_FPR, only the lower 64 bits of XMM registers are preserved when register SPILL happens.
=> x86: Use TR_VRF type for XMM temp registers in arraycopy 

compiler/optimizer/InductionVariable.cpp
First commit fixes creating invariant initialization trees with array address calculation to insert loading the dataAddrPtr
```
BEFORE
n690n     astore  <internal pointer temp slot 8>[#450  Auto] [flags 0x40007 0x0 ]             [0x7815e188c760] bci=[-1,5,35] rc=0 vc=0 vn=- li=-1 udi=- nc=1
n689n       aladd (internalPtr )                                                              [0x7815e188c710] bci=[-1,5,35] rc=1 vc=0 vn=- li=- udi=- nc=2 flg=0x8000
n688n         aload  <pinning array temp slot 6>[#448  Auto] [flags 0x10000007 0x0 ]          [0x7815e188c6c0] bci=[-1,5,35] rc=1 vc=0 vn=- li=- udi=- nc=0
n687n         lconst 4 (highWordZero X!=0 X>=0 )                                              [0x7815e188c670] bci=[-1,5,35] rc=1 vc=0 vn=- li=- udi=- nc=0 flg=0x4104
AFTER
n692n …
```
=> Offheap LoopStrider Fix and disable storing dataAddr in temps

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
For OffHeap, the arraycopy transformations uses the correct base object as the dstObj node, instead of the dataAddrPtr load. 
To ensure correctness this PR adds an asserts that checks that the dstObj is not a dataAddrPtr.
```
Valid:
n60n        arraycopy  java/lang/System.arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V[#405  unresolved notAccessed static Method] [flags 0x400 0x0 ] (Unsigned forwardArrayCopy noArra>
n58n          aload  <parm 0 [Ljava/lang/Object;>[#403  Parm]                          
n59n          aload  <parm 1 [Ljava/lang/Object;>[#404  Parm]                            
n54n          aloadi  <contiguousArrayDataAddrFieldSymbol>[#352  final Shadow +8] [flags 0x20604 0x0 ] (internalPtr )  [    0x78f0fb0e00a0] bci=[-1,0,20] rc=1 vc=33 vn=- li=- udi=- nc=1 fl>
n55n …
```
=> Assert dstObj in arraycopyEval is not a dataAddrPtr in P/AArch64

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRInstOpCode.cpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/X86BinaryEncoding.cpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp, compiler/x/runtime/X86Runtime.hpp
Reverts eclipse-omr/omr#7510
Causes a Windows build break building x/env/OMRCPU.cpp.
=> Revert "x86: Add disableAVX2/512 options and check XCR0 for OS support"

gc/verbose/schema.xsd
Match the order of elements in Verbose GC Schema with the order of actual prints in VGC code.
=> Schema re-order for Offheap

buildenv/jenkins/omrbuild.groovy
This PR adds a RISC-V native build spec in order to (re) enable OMR CI for RISC-V using RISC-V hardware.
For details see #7530.
=> RISC-V: add native build spec

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
The command line option -Xjit:dltOptLevel=... existed, but it was inspected in the OpenJ9 downstream project only when the `TR_DebugDLT` env var was set. The reason is that we have to account for the possibility of specifying the option in a subset and retrieving options from subsets is relatively expensive and not something that we may want to do too often.
This commit remembers whether `dltOptLevel=` is specified in any subset by setting a flag in the JIT command line options. Then, in OpenJ9 we can first check if this flag is set and only then proceed to find the correct subset for the method in question. This should eliminate the overhead when -Xjit:dltOptLevel= is not specified in a subset, which is the common case.
=> Remember whether dltOptLevel= is specified in a subset

compiler/optimizer/OMRValuePropagation.cpp, compiler/optimizer/OMRValuePropagation.hpp, compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPHandlers.cpp
There are cases where two different array classes could share the same signature in downstream projects. In such cases, the class retrieved from signature cannot be trusted as a fixed class.
Related: eclipse-openj9/openj9#20522
=> Check if an array class can be trusted as a fixed class

jitbuilder/apigen/test/cppgentests.py
This PR is another stab on using `assertRegex` instead of `assertRegexpMatches` (previous attempts: #7279, #7496)
What prompted me to get back to this again is recent work on reviving RISC-V build using Eclipse-provided native build agents (#7530, #7556).
This PR contains @0xdaryl's original commit changing `assertRegexpMatches` to `assertRegex`. The second commit monkey-patches class to provide the latter when not available (i.e., on Python < 3.2).
=> Use assertRegex instead of deprecated assertRegexpMatches v2

compiler/optimizer/Inliner.cpp
Several inlining parameters can be tuned via command line options or env vars. Recently, I needed to tune some inlining parameters that could not be controlled without changing the source. This PR fixes the cases that I observed by adding env vars.
=> Tune more inlining parameters without changing the source

compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp, fvtest/compilerunittest/p/BinaryEncoder.cpp
WIP implementation for modifying P8/P9 arraycmp to use vector operations.
=> Vector implementation for arraycmp on P8/P9

port/common/omrfiletext.c, port/unix/omrfiletext.c, port/win32/omrfiletext.c
* avoid use of `free`'d memory
* avoid unnecessary (repeated) calls to `strlen()`
* update for coding standard
=> Fix several issues in omrfiletext.c

compiler/env/OMRKnownObjectTable.cpp, compiler/env/OMRKnownObjectTable.hpp
Remove updateKnownObjectTableAtServer in the OMR since it is only used in OpenJ9.
=> Remove updateKnownObjectTableAtServer in OMR::KnownObjectTable

compiler/optimizer/CMakeLists.txt, compiler/optimizer/IsolatedStoreElimination.cpp, compiler/optimizer/SinkStores.cpp, compiler/optimizer/SinkStores.hpp, compiler/optimizer/UnsafeSubexpressionRemover.cpp, compiler/optimizer/UnsafeSubexpressionRemover.hpp
In the process of moving stores whose results are not needed on all paths, the General Store Sinking optimization will decide whether the tree representing the store should be copied or simply moved.  A tree might be copied if nodes in its subtrees are commoned &mdash; leaving the part of the tree that represents the value anchored beneath a `TR::treetop` node ensures the order of evaluation is maintained.
However, it is possible for a tree that was left in place like this to contain a load of some symbol whose store had preceded the current tree, but that earlier store was also sunk past the current tree.  This usually doesn't pose a problem, as the load must have been unneeded at that point, and a subsequent pass of Dead Trees Elimination would ordinarily remove the unneeded uses of the …
=> Remove unsafe expressions after store sinking

compiler/optimizer/LocalReordering.cpp
Reordering should not move a node above where its children are checked.
@hzongaro
=> Prevent reordering node above its check node

compiler/il/ILOpCodesEnum.hpp, compiler/il/OMRResolvedMethodSymbol.cpp, compiler/optimizer/OMRSimplifier.cpp
Three small (1-3 lines each) fixes:
1) Initialize an uninitialized (but used) field in OMRSimplifier
2) Remove some dubious conditional code in OMRResolvedMethodSymbol that runs at the same time that a field it depends upon is not yet initialized
3) Correct what looks like an overly prescriptive extensible class #include
=> Assorted small fixes

compiler/ras/Debug.cpp
This commit fixes a typo in the name of an arraytranslate helper for p. The name is used in compiler trace files.
=> Fix arraytranslate helper name for p

gc/structs/ForwardedHeader.hpp, include_core/omrgcconsts.h
The latter (a C++ header file) cannot be included in the former (which must be usable in C source files), and it's not reasonable to assume that the latter is always included before the former.
`ForwardedHeader.hpp` is included in `ForwardedHeader.cpp` (and other compilation units) so the check is guaranteed to be done.
Add missing parentheses.
=> Move mask overlap check from omrgcconsts.h to ForwardedHeader.hpp

compiler/optimizer/RedundantAsyncCheckRemoval.cpp, compiler/optimizer/ValuePropagationTable.hpp, compiler/z/codegen/ControlFlowEvaluator.cpp, compiler/z/codegen/InstOpCode.cpp, compiler/z/codegen/OMRCodeGenerator.cpp, compiler/z/codegen/OMRCodeGenerator.hpp, compiler/z/codegen/OMRInstOpCode.enum, compiler/z/codegen/OMRInstOpCode.hpp, compiler/z/codegen/OMRInstOpCodeProperties.hpp, compiler/z/codegen/OMRInstruction.cpp, compiler/z/codegen/OMRInstruction.hpp, compiler/z/codegen/OMRInstructionKindEnum.hpp, compiler/z/codegen/OMRMemoryReference.cpp, compiler/z/codegen/OMRMemoryReference.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp, compiler/z/codegen/S390Debug.cpp, compiler/z/codegen/S390GenerateInstructions.cpp, compiler/z/codegen/S390GenerateInstructions.hpp, compiler/z/codegen/S390Instruction.cpp, compiler/z/codegen/S390Instruction.hpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp, include_core/omrport.h, port/unix/omrsysinfo.c
Changes in this PR adds following supporting changes for zNext processor and its
exploitation.
1. Add processor recognition and facility checks for zNext
2. Add zNext instructions
3. Supporting changes for emulating zNext instructions on older IBM Z hardware.
4. Use load indexed address instructions on zNext for aladd and aiadd
-Adds support for generating load indexed address instructions for the
add tree in axaddEvaluator when the tree has the correct shape.
5. Add use of Count leading and trailing zeros instruction on zNext
- For inotz/lnotz/inolz/lnolz nodes, use these new zNext instruction.
6. Supporting changes to accelerate ExternalDecimal.checkExternalDecimal in
OpenJ9.
=>  Add zNext support

compiler/ras/Debug.cpp, compiler/ras/Debug.hpp
Snippets are printed instead using the `TR::list` version of this method, which is defined just prior to it.
=> Delete unused snippet list printing method from TR_Debug

gc/base/ParallelDispatcher.cpp
In a rare scenario, if a user specifies max GC thread count above h/w
available thread count, adaptive threading math would incorrectly
disregard the current h/w thread count.
This fix makes adaptive threading math apply its logic on top of
taskActiveThreadCount rather than _threadCount. It is more correct since
the former not already accounts for the latter (_threadCount, what is
currently spawned count of GC threads) but also
accounts for _activeThreadCount which in turn has been adjusted to
account of the number of h/w available threads.
=> gcthreads adaptive fix with overloaded max count

gc/base/SparseAddressOrderedFixedSizeDataPool.cpp, gc/base/SparseAddressOrderedFixedSizeDataPool.hpp, gc/base/SparseVirtualMemory.cpp, gc/base/SparseVirtualMemory.hpp
new APIs
isValidDataPtr(),
unmapSparseDataPtrFromHeapProxyObjectPtr(),
updateSparseDataEntryAfterObjectHasMoved() before update/remove entry from
SparseAddressOrderedFixedSizeDataPool, check if dataPtr is consistent with related size and associated proxy object.
keep unadjusted original array size instead of aligned size in MM_SparseDataTableEntry.
findFreeListEntry/returnFreeListEntry/decommitMemory/ decommitMemory need to use adjustedSize.
mapSparseDataPtrToHeapProxyObjectPtr
and unmapSparseDataPtrFromHeapProxyObjectPtr use unadjusted original array size.
=> New update/remove APIs for SparseAddressOrderedFixedSizeDataPool

compiler/optimizer/CallInfo.hpp
It doesn't make sense to copy call sites, and the copy constructor is completely unused.
=> Make TR_CallSite uncopyable

compiler/optimizer/CallInfo.hpp, compiler/optimizer/abstractinterpreter/OMRIDTBuilder.cpp
These defaults are barely used anywhere, and soon I intend to add another parameter after them anyway.
=> Remove depth and allConsts defaults from TR_CallSite constructor

compiler/il/Aliases.cpp
JProfiling helper methods should not have conservative aliasing, because they cannot write to arbitrary global variables. This commit treats JProfiling helpers like other helpers used for profiling (e.g. in the old implementation of JIT profiling).
=> Improve aliasing for JProfiling helpers

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRCodeGenerator.cpp
This commit fixes the condition for supporting arraytranslate and arrayset operations. They work only with contiguous arrays.
=> Fix supportsArrayTranslate and supportsArraySet

compiler/control/OMROptions.cpp, compiler/optimizer/LocalOpts.cpp
...rather than all invalidations regardless of the reason.
It makes sense to avoid making preexistence assumptions if we've seen that those made in earlier compilations of the same method were invalidated, but invalidations unrelated to preexistence give us no reason to suspect that preexistence assumptions will not hold.
=> Inhibit preexistence based on the number of preexistence invalidations

compiler/compile/ResolvedMethod.cpp, compiler/compile/ResolvedMethod.hpp
The isStable() query will be used in a downstream project.
=> Add isStable() query to the TR_ResolvedMethod interface

compiler/optimizer/LocalAnticipatability.cpp, compiler/optimizer/LocalTransparency.cpp
Data address pointers are internal pointers and need special handling in the PRE optimization. Like aladd/aiadd, they are skipped over in the analysis and optimization itself, but we are aiming to allow parent nodes that contain such a node as a child to participate in the analysis and get optimized. This commit changes the local analyses in PRE to treat data address pointer analogously to how aladd/aiadd.
=> PRE fix to handle data address pointer correctly

compiler/il/OMRNode.cpp
BlockSplitter uses BlockCloner to split blocks along hot paths, with the duplicated blocks forming the new hot path (that can then be straightened) and the original blocks being pushed out to cold paths.
BlockCloner clones nodes using one of TR::Node's copy constructors, which sets the doNotProfile on the clone's bytecode info. The copy constructors are used all over the place, not just to create copies of the original node but to also create new nodes. Setting the doNotProfile flag avoids inadvertantly proflining semantically unrelated nodes that happen to share the same bytecode, thereby polluting the profiling data.
Because of the above, when BlockSplitter runs, nothing on the hot path will be profiled, and in cases where the cold paths are never executed, we will completely miss out …
=> Propagate doNotProfile state when cloning nodes

compiler/control/OMROptions.cpp
The JIT will crash if a log file is not provided for this tracing option.
=> Require a JIT log file for TR_TraceAliases

gc/base/SparseAddressOrderedFixedSizeDataPool.cpp, gc/base/SparseAddressOrderedFixedSizeDataPool.hpp, gc/base/SparseVirtualMemory.cpp, gc/base/SparseVirtualMemory.hpp
caller has been updated to use new signature of
the below APIs, remove the old unused APIs.
class MM_SparseVirtualMemory
updateSparseDataEntryAfterObjectHasMoved()
freeSparseRegionAndUnmapFromHeapObject()
class MM_SparseAddressOrderedFixedSizeDataPool
isValidDataPtr()
unmapSparseDataPtrFromHeapProxyObjectPtr()
updateSparseDataEntryAfterObjectHasMoved()
=> Remove unused off heap related APIs

compiler/control/OMROptions.cpp, compiler/ilgen/BytecodeBuilder.hpp, compiler/ilgen/OMRBytecodeBuilder.cpp, compiler/ilgen/OMRBytecodeBuilder.hpp, compiler/ilgen/OMRIlBuilder.cpp, compiler/ilgen/OMRIlBuilder.hpp, compiler/ilgen/OMRMethodBuilder.cpp, compiler/ilgen/OMRMethodBuilder.hpp, compiler/ilgen/OMRTypeDictionary.cpp, compiler/ilgen/OMRTypeDictionary.hpp, jitbuilder/CMakeLists.txt, jitbuilder/apigen/jitbuilder.api.json
A collection of (mostly) relatively small changes to the jitbuilder code discovered during the development of jb2 (so not likely to have been bothering anyone else, it seems).
Two things that may impact users (first possibly negative, second possibly positive) :
1) The "name" parameter for BytecodeBuilder has been promoted to const char * from char *. Hopefully that shouldn't bother anyone, but code that asks for the name of a bytecode builder may not be expecting a const char * back.
2) I've improved the handling of short integer width operands for IfCmp statements for AArch64. These don't work very well on some code generators (I'm looking at you, AArch64!) but JitBuilder allows it. JitBuilder will now automatically insert additional conversions to promote the operands to platform …
=> Misc jb changes

compiler/p/codegen/ControlFlowEvaluator.cpp, compiler/p/codegen/OMRInstOpCodeProperties.hpp
Re-enable the fast pathing of Math.min/max for floating points with the behaviour of +/-0.0 and NaN values correctly addressed.
=> Fast Path Math.min/max_F/D

gc/base/GCExtensionsBase.hpp, gc/base/MemorySubSpaceSemiSpace.cpp
In Concurrent Scavenger tilt calculation, increase the boost factor that we apply on allocation rate (and it's deviations). This will help with noisy applications and occasional spikes in allocation to reduce the probablity of premature concurrent phase termination, which cause longer last STW increment (and also failed flips that polute/fragment Tenure).
A negative side effect of this change is that tilting is decreased, which means that Scavenges will run more frequently, what will effectively reduce maximum throughput metrics. However, the guarantied throughput (while CS cycle is active) will be unaffected - what is more important for applications that care about response time.
The old behavior can be restored by decreasing the boost factors back to their original values via command …
=> Increase default CS headroom

compiler/optimizer/VPHandlers.cpp
Adding constraints to "known objects" during remote compilations (at JITServer) results in many messages exchanged between client and server.
This commit rejects the addition of constraints during remote compilations, unless the -Xjit:enableVectorAPIExpansion is present on the command line (these constraints are needed for the VectorAPIExpansion optimization in OpenJ9 project).
=> Don't use known object constraints for remote compilations

util/a2e/atoe.c, util/a2e/atoe_utils.c
Some of the atoe methods were using a constant length buffer for string conversion. If the input format string and arguments are larger than the buffer size, buffer overflow would happen. This bug was fixed by running atoe_vsnprintf with NULL buffer to get the required buffer size then create the buffer and write in it.
=> ZOS: Fix const length buffer used in atoe methods

compiler/control/OMROptions.cpp, compiler/env/FrontEnd.cpp, compiler/env/FrontEnd.hpp, fvtest/compilertest/control/TestJit.cpp, jitbuilder/control/Jit.cpp
Adds a query to TR_FrontEnd (which defaults to "no") to answer whether Options::shutdown() should free the command-line options objects. For compilers like JitBuilder and the Test compiler, not freeing the options represents a memory leak and there is no reason not to free the options objects, so these compilers arrange for the objects to be freed.
Other FrontEnds (but notably OpenJ9) by default will not free the options objects, because e.g. OpenJ9 cannot guarantee that the options objects will not be later read in one of its many event handlers that continue to operate throughout the shutdown process. Other front ends can opt in by adding the same line of code in their startup to tell their TR_FrontEnd object that it's safe to free the options object.
This change addresses crashes in …
=> Only free options objects in Options::shutdown if safe for FrontEnd

util/a2e/atoe.c, util/a2e/headers/atoe.h
Avoid calling strlen on NULL.
Also update atoe_perror() to call perror("") when the string argument is NULL.
=> Have a2e_string and e2a_string return NULL when str or malloc is NULL

compiler/optimizer/LocalOpts.cpp
Null check compaction was incorrectly replacing array object with dataAddr
pointer, resulting in the pointer being alive across GC point.
=> Prevent null check compaction for dataAddr nodes

compiler/env/FrontEnd.cpp, compiler/env/FrontEnd.hpp
A `String` object that might consist of up to 2<sup>31</sup>-1 chars could require up to three times as many bytes as chars to be encoded in UTF-8.  The current return type of `getUTF8StringLength` - `intptr_t` - is unable to correctly represent all valid lengths in 32-bit mode.
This change makes the return type of the existing `TR_FrontEnd::getStringUTF8Length` method `int32_t`.  It must only be used in situations where it is known that the UTF-8 encoded length of the String will not exceed 2<sup>31</sup>-1 bytes.
This change also introduces a new `getUTF8StringUnabbreviatedLength` method whose return type of `uint64_t` is able to represent all possible UTF-8 encoded string lengths.
=> Change return type of TR_FrontEnd::getStringUTF8Length to int32_t

util/hashtable/hashtable.c
There is a null check in each of hashTableFindNode() and hashTableFindNodeSpaceOpt(), between these two null checks a new node could be added resulting a wrong class being returned.
Related: https://github.com/eclipse-openj9/openj9/issues/20444
=> Fix hashClassTableAt() returning wrong class in fast hash

cmake/modules/OmrMetalC.cmake
Open XL z/OS does not yet support metal-c. These files are always compiled with xlc. As such, the conditional -m64 flag is invalid when running with a full Open XL build. This change reverts it to the original logic so that it compiles properly.
=> Revert Open XL MetalC flag changes

port/zos390/omrzfs.c
Some functions containing the native call BPX4PCT are causing
a crash with Open XL, when they are called back to back in omrzfs. Instead
of lowering optimization level to O0 entirely, specifying
no inlining for these functions seems to mitigate this problem.
This will be used as a workaround until a permanent fix is
released.
Related: https://github.com/eclipse-omr/omr/issues/7653
=> Lower optimization level workaround for omrzfs.c

compiler/p/codegen/OMRTreeEvaluator.cpp
This commit removes the code generation for checking length == 0 in arraytranslateEvaluator for Power.
The helper functions for arraytranslate are responsible for checking the case of length == 0.
=> Improve arraytranslateEvaluator for Power

compiler/control/OMROptions.hpp
Replace `other.words` with `other._words`
=> Fix syntax error in OptionFlagArray class definition

compiler/z/codegen/OMRCodeGenerator.cpp
This commit stops enabling the arrayset optimization on Z when arraylets are enabled.
=> Z: Disable arrayset opt when arraylets are enabled

compiler/x/codegen/OMRTreeEvaluator.hpp
It can be useful to call this static function outside of the TreeEvaluator hierarchy, so make it public access.
=> Change access protection for performHelperCall on x86

compiler/codegen/OMRCodeGenPhase.cpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
The codegen typically overestimates the code cache space needed for a compiled method body. However, after the jitted code is generated, the codegen "trims" the initial code cache allocation to the right size.
This commit introduces an option to disable such code cache allocation trimming. By default, code cache allocation trimming is enabled, preserving the current behavior.
=> Add -Xjit:disableCodeAllocationTrimming option

include_core/omrcomp.h
For unoptimized builds with GCC, we only need to avoid the `always_inline` attribute. The mere presence of the inline keyword won't cause any actual inlining (since the build is unoptimized).
As for `DEBUG`, even if it's defined, many `VMINLINE` functions are likely to be inlined in optimized builds anyway, because they're implicitly declared inline by virtue of being defined within a class declaration. If a developer wants to prevent inlining for debugging purposes, they can edit their build flags to disable it (or disable optimization more generally), or they can inhibit inlining of particular functions in the source code, e.g. with `__attribute__((noinline))`.
`VMINLINE` will now always be defined as `VMINLINE_ALWAYS` because there is no prior definition.
This change avoids unused …
=> Don't #define VMINLINE to be empty for unoptimized/debug builds

compiler/env/OMRCPU.cpp, compiler/env/OMRCPU.hpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp
Issue: eclipse-openj9/openj9#19408
=> x86: Call TR::CPU::customize in CPU detection logic

compiler/control/OMROptions.cpp
Print `noResumableTrapHandler` and `disableTraps` options in verbose logs if they are set. With https://github.com/eclipse-openj9/openj9/pull/21154, `noResumableTrapHandler` could be set implicitly by the JVM.
=> Print noResumableTrapHandler and disableTraps options if set

gc/base/SparseAddressOrderedFixedSizeDataPool.cpp
Memory Pool can not be killed before it's elements
=> Change order in MM_SparseAddressOrderedFixedSizeDataPool::tearDown()

fvtest/porttest/si.cpp
macOS test set_limit uses get_limit return value - 1
This accommodates the value required by macOS 15 `setrlimit()`.
=> macOS test set_limit uses get_limit return value - 1

compiler/optimizer/Inliner.cpp
With `fixupCommoning`, any node commoned across the split point is stored into a temp, and occurrences after the split are replaced with a load.
If this happened with a `PassThrough` node, we would generate `BadILOp` because `PassThrough` claims to have type `NoType`. In particular, the store would be `BadILOp`, and it would appear that a conversion is needed at the load, and the conversion would also be `BadILOp`.
While determining which nodes are commoned across the split point, any `PassThrough` node encountered with refcount greater than 1 will now be replaced with a fresh `PassThrough` node with refcount 1. This way, no `PassThrough` node will be found to commoned across the split point.
=> Avoid storing PassThrough nodes to temps when splitting blocks

include_core/AtomicSupport.hpp
When Open XL AIX support was merged earlier, it seems to have caused problems with Open XL z/OS builds. The __open_xl__ conditionals meant for AIX are taking priority over the J9ZOS390 clauses, causing problems for z/OS. Was recommended to reorder these so that the more granular J9ZOS390 conditional is encountered and entered first.
=> Reorder J9ZOS390 conditionals in AtomicSupport.hpp for Open XL z/OS

cmake/modules/OmrDetectSystemInformation.cmake, cmake/modules/ddr/DDRSetStub.cmake.in, cmake/modules/platform/toolcfg/openxl.cmake
Adds the initial set of changes to support compilation with Open XL on z/OS. This will define the alternative flags and configuration that needs to be used by the wyvern compiler while running on z/OS.
(This is one part of the multiple changes added for supporting Open XL compilation on OMR)
=> Add Open XL toolchain and config changes for z/OS

compiler/control/OMROptions.cpp
This commit increases the default value of `_bigCalleeThreshold` from 400 to 500 on x86 and the default value of
`_bigCalleeThresholdForColdCallsAtWarm` from 400 to 500 for all platforms. These changes were found to increase the throughput of some benchmarks slightly (1-2%) with a minimal increase in compilation time (2-3%).
=> Increase a couple of inliner thresholds

compiler/optimizer/VPConstraint.cpp
Code in [`VPClassType::isJavaLangClassObject()`](https://github.com/eclipse-omr/omr/blob/edad43fbfc6393de2ff260f35227fe197e7d0c29/compiler/optimizer/VPConstraint.cpp#L606-L620) tests whether the `VPClassType` object refers to an instance of one of the interfaces that are known to be implemented by `java/lang/Class`.  The set of interfaces that were considered was incomplete, as it was missing interfaces that were added in JDK 12:
```
java.lang.constant.Constable
java.lang.invoke.TypeDescriptor
java.lang.invoke.TypeDescriptor$OfField
```
That resulted in `VPClassType::isJavaLangClassObject()` returning `TR_no` for any reference that is known to be an instance of one of those interface classes rather than `TR_maybe`.
Fixes:  eclipse-openj9/openj9#21031
=> Check for all interfaces implemented by java/lang/Class in VP

include_core/omrcfg.h.in
Those lines disappear when producing `omrfcf.h` even if DDR is enabled. Cmake generates makefiles which define those macros as necessary.
=> Remove useless #undef DWARF lines

compiler/z/codegen/OMRTreeEvaluator.cpp
The result of `arraycmplen` is 64 bits even in 31-bit mode, so we need to ensure that the upper 32 bits of the result do not contain any garbage.
Fixes https://github.com/eclipse-openj9/openj9/issues/21166
=> Z: Ensure clean upper bits of arraycmplen result

util/a2e/atoe.c
Open XL on z/OS throws undeclared function errors when a function is used before it has been declared or defined. The changes here reorder the function definitions so that these errors are addressed.
i.e. The function definitions are moved above, so that their definitions are available before their respective usages.
```bash
/omr/util/a2e/atoe.c:1343:8: error: call to undeclared function 'atoe_vfprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]                                                                                                              
1343 |         len = atoe_vfprintf(file, ascii_chars, args);
|               ^
omr/util/a2e/atoe.c:1362:8: error: call to undeclared function 'atoe_vfprintf'; ISO C99 and later do not …
```
=> Add function declarations in atoe.c for Open XL

compiler/optimizer/ValuePropagationCommon.cpp
Arraycopy transformation in value propagation should check if checks can be skipped on the right owning method symbol. Previously, it was checking the method being compiled, whereas it should be checking the owning method on the arraycopy call node.
=> Use right owning method symbol for arraycopies

buildenv/docker/x86_64/ubuntu/Dockerfile, buildenv/jenkins/omrbuild.groovy
Pull from Nvidia registry to avoid any DockerHub restrictions.
Bump cuda level from 9.0 to 12.2.0 which matches level used by OpenJ9.
Change from Ubuntu16 to ubi8 to match OpenJ9 as well as provide
support for plinux if needed in the future.
Bump from ub20 to ub22 for base image.
Also pull from Amazon registry to avoid any DockerHub restrictions
Issue automation 72
=> Update to an in support cuda container

compiler/optimizer/VPConstraint.cpp, compiler/optimizer/VPConstraint.hpp, compiler/optimizer/VPHandlers.cpp
...and therefore at most `INT32_MAX` / `elementSize` elements. This could result in incorrect transformations, e.g. incorrect comparison folding.
These are (hopefully all of the) additional instances of the bug fixed in #7461.
Furthermore, there are two clean-up commits that delete dead code containing what would otherwise be additional instances of this bug:
- Delete unused signature-based overload of `VPArrayInfo::create()`.
- Clean up code in `constrainBndChkWithSpineChk()`
Review resulted in one more commit:
- VP: Propagate index lower bound to array length for `BNDCHKwithSpineCHK`
=> Stop VP from assuming that arrays are limited to INT32_MAX bytes

ddr/lib/ddr-scanner/CMakeLists.txt, ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp, include_core/omr.h
Previously, when OpenJ9 builds on AIX were done with xlC16 as the C/C++ compiler, debugging information was generated in the stabstring format. However, with the switch to OpenXL17, stabstrings are no longer supported, and debug info can only be generated in DWARF format. Since libdwarf, the library used to parse DWARF format debug info on other platforms, is not available on AIX, we cannot read this information directly. Instead, we must parse the output given by dwarfdump, as is currently being done on macOS.
=> Changes to generate DDR with OpenXL on AIX

compiler/il/OMRBlock.cpp
We've been looking for `GlRegDeps` as the last child of `node`, which is the top-level switch node, when we should have instead been looking at the last child of `branch`, i.e. the last child of the child of `node`.
This caused `splitPostGRA()` to completely ignore `GlRegDeps` beneath switch nodes, which could result in failure to generate a register store. Without a register store, the `GlRegDeps` could end up with a `PassThrough` whose child doesn't occur in any prior tree.
Fixes eclipse-openj9/openj9#21148
=> In splitPostGRA(), find the GlRegDeps for switch children correctly

compiler/optimizer/Inliner.cpp, compiler/optimizer/Inliner.hpp
Some targets are meant to be handled by `tryToInlineTrivialMethod()` and cannot be inlined by generating IL in the usual way. So far the implementation of `tryToInlineTrivialMethod()` has been required to return true for such targets even in cases where the call is not transformed.
This new method provides a way to tell the inliner that a given target should have been handled by `tryToInlineTrivialMethod()` and that IL generation should not be attempted. If the inliner is informed in this way, then it will be possible for `tryToInlineTrivialMethod()` to return false when it fails.
=> Define trivialInliningOnly() in TR_InlinerBase and OMR_InlinerPolicy

port/zos390/omrsl.c
Update `j9sl_lookup_name` to work for both function and variable lookup.
These changes address the failure of testcase on z/os: [java/foreign/TestClassLoaderFindNative.java](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/TestClassLoaderFindNative.java)
- Added call to `dllqueryvar` for variable lookup
=> Fix for test failure: java/foreign/TestClassLoaderFindNative.java

gc/base/MemoryHandle.hpp
Currently methods of MM_MemoryHandle are protected. It is not necessary to be so strict and it adds more flexibility to make them public.
=> Make MM_MemoryHandle methods be public

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
Added -Xjit:verbose={JITServerSharedProfile} and
-Xjit:verbose={JITServerSharedProfileDetails} options to be used in an downstream project.
=> Add verbose options for shared profile cache

gc/base/GCExtensionsBase.hpp, gc/base/SparseVirtualMemory.cpp, gc/verbose/VerboseHandlerOutput.cpp
Allow to change the default offheap size.
Also some adjustments in Verbose GC reporting:
- report the Offheap size, which will be reported only if offheap
is enabled. Hence, no need to report explicitly if enabled or not,
anymore.
- report arraylet related info, only if offheap disabled (Balanced with
arraylets or Metronome)
=> Offheap size

compiler/optimizer/OMRSimplifierHandlers.cpp
When the compare op is an unsigned compare, unless the select op's DataType is TR::Address, simplifyISelectCompare() will recreate the compare op with a BadILOp because compareOpCode() will not find a valid comparison op of type TR_cmpNE. This will cause problems in the comparison op simplifier afterward. Guards against this simplification in these cases.
=> Ensure simplification of compare op is valid

compiler/compile/OMRCompilation.cpp
The comment declares that the function computes the same hash as Java `String.hashCode()` - this updates the multiplier from 33 to 31 so that assertion is true.
=> Make hash computation consistent with comment

include_core/omrport.h, port/aix/omrsl.c, port/common/omrport.c, port/common/omrport.tdf, port/common/omrsl.c, port/omrportpriv.h, port/unix/omrsl.c, port/win32/omrsl.c, port/zos390/omrsl.c
Use /proc file system to capture the dependent libraries.
Invoke the callback on each library.
=> Add an API for native libraries

gc/base/SparseVirtualMemory.cpp, gc/base/SparseVirtualMemory.hpp, gc/base/j9mm.tdf
While it may little to no effects on offheap fragmentation it is certainly easier to keep track of dataAddr during debugging, if they are region based rounded.
=> Force offheap region size alignment and granularity

compiler/env/TRMemory.cpp, compiler/env/TRMemory.hpp
This new type will be used for accounting memory used by the JITServer profiling infrastructure.
=> Add new object memory type: JITServerProfileCache

include_core/omrport.h, port/common/omrport.c, port/common/omrport.tdf, port/common/omrsysinfo.c, port/omrportpriv.h, port/unix/omrsysinfo.c, port/win32/omrsysinfo.c
Use /proc filesystem to extract command line. 
Use cmdline for user space processes and comm for others.
=> Add an API for system processes

compiler/compile/OMRCompilation.cpp
A native linkage adapter must not be considered to be making a recursive call, or else the code generator could encode the call instruction as a recursive call to the JIT body instead of the intended call to the native implementation.
So far we've been avoiding that situation by having `isSameMethod()` return false for native methods, which is confusing. By rejecting native methods explicitly here, it will now be possible to correct this problem in `isSameMethod()`.
=> Reject native methods in isRecursiveMethodTarget()

compiler/optimizer/CallInfo.hpp, compiler/optimizer/Inliner.cpp
Previously a `TR_CallTarget` could be mutated to represent a different target method if during physical inlining the corresponding call node was found to be a direct call to a method other than the one originally represented by the `TR_CallTarget`.
Now a `TR_CallTarget` will never be mutated in such a way. If that situation arises, then instead the target will be removed from its call site, and a new target will be added as though for a direct call site.
Additionally, physical inlining gets the actual method not directly from the target's `_calleeMethod`, but rather from its `_calleeSymbol`, which could be set to the call site's `_initialCalleeSymbol` even when it represents a different method from the call target. This would be fixed up afterward by `getSymbolAndFindInlineTargets()`, …
=> Ensure each TR_CallTarget represents one unambiguous target method

compiler/aarch64/runtime/ARM64ArrayTranslate.spp
This commit improves the performance of the short array case (less than 16 elements) of arraytranslateTROTNoBreak helper function for AArch64.
=> AArch64: Improve arraytranslateTROTNoBreak helper function

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.hpp, compiler/il/VectorOperations.enum, compiler/optimizer/OMRSimplifierTable.enum, compiler/optimizer/ValuePropagationTable.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.hpp, compiler/riscv/codegen/OMRTreeEvaluator.cpp, compiler/riscv/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp
- similar to vbitselect but works on lanes and under control of the mask (third child)
- if lane is not set in the mask the value from the first vector is chosen
- the lane from the second vector is chosen otherwise
=> Add vblend vector operation

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
- TR::v2m opcode converts boolean vector into mask
- least-significant bit of each byte element should be left-extended
- mload/mloadi opcodes don't have to extend the bit since they load correct
mask representation stored by mstore/mstorei
=> Support v2m opcode on Power

gc/base/Collector.cpp, gc/base/Collector.hpp, gc/base/standard/ParallelGlobalGC.cpp, gc/base/standard/ParallelGlobalGC.hpp, gc/base/standard/Scavenger.cpp, gc/base/standard/Scavenger.hpp
More generally, invoke pre/postCollect around the last CS increment when terminating CS cycle to transition to the final STW of the ConcurrentGC.
postCollect will then invoke calcGCStats, what will help with more correct Scavenger tenuring rate estimates and in turn more correct concurrent global kickoff logic.
For now, we are just calling internalPre(Post)Collect, but probably we should call full blown pre/postCollect that would account for excessive GC stats/calculation, as well. But that's a separate issue and a riskier change.
=> Calculate Scavenge stats on CS-to-Global transition

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/z/codegen/OMRInstOpCode.enum, compiler/z/codegen/OMRInstOpCode.hpp, compiler/z/codegen/OMRInstOpCodeProperties.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/env/OMRCPU.cpp, compiler/z/env/OMRCPU.hpp, include_core/omrport.h, port/unix/omrsysinfo.c
This PR replaces the literal "zNext" with "z17" in OMR.
=> Replace "zNext" with "z17" in OMR

compiler/x/codegen/X86Ops.ins
Ensure that the code generator knows what size the target register should be for the `pmovmskb` instruction. From the Intel manual:
> Creates a mask made up of the most significant bit of each byte of the source operand (second operand) and stores
the result in the low byte or word of the destination operand (first operand).
The byte mask is 8 bits for 64-bit source operand, 16 bits for 128-bit source operand and 32 bits for 256-bit source
operand. The destination operand is a general-purpose register.
If the output is smaller than 32 bits, the rest of the register is zero extended, so a target GPR of 32 bits is always safe.
=> Specify a 32 bit target for PMOVMSKB4RegReg

gc/base/standard/Scavenger.cpp
In a relatively uncommon case were scan phase of Concurrent Scavenge is not completed fully concurrently, but a part of it is done in the final STW increment, we would prematurely clear the stats of that phase, so that GC end hook for that final increment would report incorrect (too low) copy data. It would report only the copy data from the complete phase (only copying during clearable phase, which is typically very minimal), while there could be signficant amount of tenuring (due to failed fipping)
Such clearing is already done at the beginning of each STW increment - so it's just removed from the end of STW scan phase.
Also no need to merge those stats to the global Scavenge stats structure, since it's already done at the end of any STW increment.
The change is supposed to be a …
=> Do not clear stats on STW scan phase end

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
- on Power and AARch64, vblend behaves the same way as vbitselect
=> Implement vblend on Power and Aarch64

gc/base/SparseAddressOrderedFixedSizeDataPool.hpp
new API to retrieve objectToSparseDataTable from
SparseAddressOrderedFixedSizeDataPool.
=> New API expose hashTable from SparseAddressOrderedPool

compiler/optimizer/InductionVariable.cpp, compiler/optimizer/InductionVariable.hpp
LoopStrider currently performs on non-arrays and that's was not the intended design for it. This sets non-array nodes as pinning-array and the access as an array access.
This didn't cause an issue previously until OffHeap was introduced. Given that OffHeap array accesses requires loading the `dataAddrPtr`, after inserting the load to a non-array access, it ends up loading/storing to a different memory location.
The fix limits loopStrider to the first-level children of the array-shadow symbol nodes.
An extra check against unsafe-shadow symbols is added as unsafe-shadow symbols also have array-shadow symbol flag set.
Before the fix:
```
n25090n   astore  <temp slot 68>[#3108  Auto] [flags 0x7 0x0 ]                                [0x788beb709240] bci=[102,3,251] rc=0 vc=4560 vn=19 li=287 …
```
=> Limit loopStrider to children of array-shadow symbol nodes

compiler/env/TRMemory.cpp, compiler/env/TRMemory.hpp
This commit adds a new type of memory object, called "TR_IPBCDataDirectCall". 
This is used for tracking persistent memory allocations made by the interpreter profiler in a downstream project.
=> Add "TR_IPBCDataDirectCall" memory object type

compiler/x/codegen/OMRTreeEvaluator.cpp
When converting boolean array to lanewise bitmask a subtraction op is used to set all bits to 0 or 1. The sub opcode must be integral even when the mask element type is floating-point.
=> x86: Fix (b/s/i/l/v)2m opcodes fp masks

compiler/x/env/OMRCPU.cpp, include_core/omrport.h, port/common/omrsysinfo_helpers.c, port/common/omrsysinfo_helpers.h
First attempt at adding OS support checks for x86 stored in extended control register 0 (xcr0).
We add support for the following:
- xsave XMM 
- xsave YMM
- xsave ZMM (includes check for k0-k7, might want to separate into its own flag)
- xsave EGPR (APX)
Control register flags are documented in the intel [manual](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html).
=> x86: Implement OS checks in port library

cmake/modules/platform/os/zos.cmake, compiler/control/OMROptions.cpp, compiler/ras/LimitFile.cpp, ddr/include/ddr/std/sstream.hpp, ddr/include/ddr/std/string.hpp, ddr/include/ddr/std/unordered_map.hpp, fvtest/omrGtestGlue/omrGtest.cpp, fvtest/omrGtestGlue/omrTest.h, include_core/omrcomp.h, util/a2e/headers/ctype.h
Changes here remove the redefinition of isdigit() in
the a2e ctype.h headers. In order to fully make this
work functionally, the references/usages of isdigit()
are replaced with OMR_ISDIGIT to properly recognize
ascii digit literals. This is done by conditionally
using __isdigit_a() on z/OS platforms.
---
This is the cleaned-up changes from https://github.com/eclipse-omr/omr/pull/7413 (for historical related comments)
=> Remove isdigit macro redefs, replace with OMR_ISDIGIT

compiler/il/OMRNode.cpp
When `createStoresForVar` is called on array references, the reference is stored into a temp and the temp is passed back (using reference passed argument). 
The base-array of the reference is also stored into a new temp, and the original usage of the base-array is swapped with a load of the new base-array temp if the `refCount==1` (line 3816), for OffHeap the original base-array change was without checking the refConut causing https://github.com/eclipse-openj9/openj9/issues/21378. 
Basically changing a child of a commoned tree to use a newly inserted temp might affect an earlier tree (before temp definition) to use that temp before it's defined/populated. 
This PR guards the orginial base-array change using a refCount check.
Original issue showed up in a 1/20 grinder, with fix it didn't …
=> Change original base-array when createStoresForVar only if refCount==1

compiler/codegen/OMRCodeGenerator.hpp, compiler/env/OMRCPU.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/env/OMRCPU.cpp, compiler/p/env/OMRCPU.hpp, compiler/x/amd64/codegen/OMRCodeGenerator.cpp, compiler/x/env/OMRCPU.cpp, compiler/x/env/OMRCPU.hpp, compiler/x/i386/codegen/OMRCodeGenerator.cpp
- Remove the `getSupportsHardware(32|64)bit(Compress|Expand)` methods from the `OMR::CPU` class and their overrides in child classes
- Add `(get|set)Supports(32|64)Bit(Compress|Expand)` methods to the `OMR::CodeGenerator` class
- Call `setSupports(32|64)Bit(Compress|Expand)` in `OMR::X86::AMD64::CodeGenerator::initialize`, `OMR::X86::I386::CodeGenerator::initialize`, and `OMR::Power::CodeGenerator::initialize` as appropriate
- Use `TR_disableBitwiseCompress` and `TR_disableBitwiseExpand` to skip calling corresponding `setSupport*` methods in the `initialize` methods
=> Move bitwise compress/expand support flags from OMR::CPU to OMR::CodeGenerator

compiler/x/codegen/X86Ops.ins
Calling [getSIMDEncoding](https://github.com/BradleyWood/omr/blob/f18f7171095968c85a17b115ddf97afe53d90a7e/compiler/x/codegen/OMRInstOpCode.hpp#L599) for this instruction leads to assertion failure because cpuid flags are missing.
=> x86: add cpuid feature flags to pcmpeqw

compiler/codegen/OMRCodeGenerator.hpp, compiler/optimizer/OMRSimplifierHandlers.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
=> Multiply simplifier should ask CG before decomposition

compiler/il/OMRNode.cpp, compiler/il/OMRNode.hpp
No uses in OMR or any downstream project.
=> Remove obsolete AlignTLHAlloc TR::Node flag

gc/base/GCExtensionsBase.hpp, gc/base/standard/ConfigurationGenerational.cpp
Scavenge Abort is a rather expensive operation. Give some more tenuring headroom with CS, to decrease probability of an abort, even if that means slightly more frequent Global GC.
=> Increase CS tenuring headroom

gc/base/standard/Scavenger.cpp, gc/stats/ScavengerStats.hpp
Make the type consistent with general byte counters used by GC threads.
=> Use uintptr_t for RB byte counter

compiler/optimizer/InductionVariable.cpp
This is a follow from https://github.com/eclipse-omr/omr/commit/c7f89a0e96106fbd52a9c65b640d2d923cac9386 where disabling storing dataAddr in temps in loopStrider for offheap was committed but change wasn't complete.
The prior change disables recognizing array access with dataAddrPtr of the form Array+X, but for Array+X+C where `C == header-size`, it triggers a different path for non-offheap accesses that wasn't specifically checked against offheap by the prior commit. This change adds that check.
Closes: https://github.com/eclipse-openj9/openj9/issues/21352
The test rarity of `C == 24 == header-size` caused this issue to be hardly reproducible and in this case only with `noCompressedRefs`.
Will be ported to 0.53
WIP: Testing
=> Disable reassociate for dataAddr access arrays for OffHeap

include_core/omrport.h, port/common/omrsysinfo_helpers.c, port/common/omrsysinfo_helpers.h
x86: Expand cpuid support in port library
This commit adds CPUD queries to check for new CPU features, specifically APX and AVX 10. The following CPUD queries are introduced:
- `CPUID.(0x7.0x1).EAX`
- `CPUID.(0x7.0x1).EDX`
- `CPUID.(0x24.0x0).EBX[7:0]` - AVX 10 sub-version
- `CPUID.(0x24.0x0).EBX[16-18]` - AVX 10 VL support
New AVX 10 feature flags are added:
- `OMR_FEATURE_X86_AVX10_1`: AVX 10.1
- `OMR_FEATURE_X86_AVX10_2`: AVX 10.2
- `OMR_FEATURE_X86_AVX10_128`: AVX 10 128-bit support
- `OMR_FEATURE_X86_AVX10_256`: AVX 10 256-bit support
- `OMR_FEATURE_X86_AVX10_512`: AVX 10 512-bit support
=> x86: Expand cpuid support in port library

compiler/optimizer/DebuggingCounters.cpp
This API is going away in the downstream repo that defines it.
=> Remove usage of getIProfilerCallCount()

compiler/codegen/OMRCodeGenerator.cpp, compiler/compile/OMRCompilation.cpp, compiler/compile/OMRCompilation.hpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/control/OptionsUtil.hpp, compiler/runtime/OMRCodeCache.cpp, compiler/runtime/OMRCodeCache.hpp, compiler/runtime/OMRCodeCacheManager.cpp, compiler/runtime/OMRCodeCacheManager.hpp
Add infrastructure to allow the compiler component to distinguish between different code caches. This infrastructure can be used to facilitate features such as file-backed code caches.
See https://github.com/eclipse-omr/omr/issues/7779
Needs to be merged in tandem with https://github.com/eclipse-openj9/openj9/pull/22045
=> Infrastructure to segregate code caches

compiler/compile/VirtualGuard.cpp, compiler/compile/VirtualGuard.hpp, compiler/optimizer/Inliner.cpp, compiler/optimizer/Inliner.hpp
...instead of based on reference location.
=> Identify `MutableCallSite` for guards based on known object index

compiler/optimizer/VirtualGuardHeadMerger.cpp
In some cases the VGHM opt was moving code above a runtime guard allowing a privatized argument load to read past the end of the object bounds. This privatized temp slot was marked collectible causing the GC to assert when the loaded value was not a valid object reference. The issue the assert is reporting would not cause any runtime behaviour issues as the guard would have prevented any of the inlined code from executing and therefore the temp would never have been used, but allowing the invalid load to happen could cause a SEGV if the load offset caused an access passed the end of the heap. This fix looks for shadow symrefs between the two guards and aborts guard movement when one is found.
=> Prevent VGHM from moving guards in the presence of shadow symrefs

compiler/optimizer/VirtualGuardHeadMerger.cpp
Also, add missing punctuation.
=> Correct spelling of 'avoids'

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/runtime/OMRCodeCacheManager.cpp, compiler/runtime/OMRCodeCacheManager.hpp
If `TR_RetryCodeCacheAllocAndIgnoreKind` is set, retry reserving the code cache ignoring the kind. However, on the retry, skip trying to allocate a new code cache. On the first attempt, if a reservation attempt fails, the manager tries to allocate a new code cache; if the allocation also fails, there is only value in trying to reserve a code cache ignoring the kind.
Closes https://github.com/eclipse-omr/omr/issues/7779
=> Conditionally retry code cache reservation ignoring the kind

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp
This contribution includes the following changes:
- Masked logical vector operations (`vmxor`, `vmand`, `vmor`) have been enabled on PPC and their evaluators redirected to the corresponding non-masked implementations.
- For logical vector operations performed on LongVectors, the VMX instruction (i.e.: `vxor`/`vand`/`vor`) is used instead of the VSX one (i.e.: `xxlxor`/`xxland`/`xxlor`)
=> Modifications to logical vector operations on PPC

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
This commit fixes mFirstTrueEvaluator() and mLastTrueEvaluator() for
AArch64.
- mFirstTrue: A "break" statement was missing for the Int16 case
- mLastTrue: The code for Int64/Double was not working correctly
=> AArch64: Fix mFirstTrueEvaluator() and mLastTrueEvaluator()

cmake/config.cmake, cmake/modules/platform/toolcfg/gnu.cmake
Currently just for the gnu toolchain.
=> cmake: add option to enable link-time optimization

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/control/OptionsUtil.hpp
Enabling this option overrides all other code cache disclaiming options.
This is because this option is used to indicate that a code cache must
be backed by a file for the purpose of disclaiming the entire code cache
(and not just part of it, or having it disclaimed to swap).
=> Add Enable File Backed Code Cache Disclaiming Option

port/aix/omrvmem.c, port/linux/omrvmem.c
Instead of only accepting 64K and 16M as valid page sizes, accept any page size matching the valid size list from the OS.
Except for 32-bit archs where 16M will only be enabled along with consolidatedCodeCache to save on address space.
=> Remove Hard-Coded Restrictions to CodeCache Page Sizes on P

compiler/env/Region.cpp, compiler/env/Region.hpp
In a Quarkus app I've been studying, Region::allocate() is consistently the hottest method in the JIT compiler with a bunch of ticks landing inside and in the call to the very simple private Region::round() function that is not being inlined into Region::allocate(). Since it's only called from one place and the code is pretty obvious, we can remove the overhead of the call/return here and potentially improve JIT compile time a bit.
=> Inline single call to Region::round() private function

include_core/omrsig.h, omrsigcompat/omrsig.cpp
For C++ contexts, they must declare that they don't throw exceptions.
Define and use `OMRSIG_NO_THROW` instead of `__THROW`.
=> Correct declarations of signal-related functions

compiler/codegen/ELFGenerator.cpp
The _totalELFSymbolNamesLength is a dynamic quantity, and creating an array of that length in C++ causes a warning-as-error with Clang 18.
=> Fix variable-length array warning in clang

compiler/aarch64/codegen/OMRTreeEvaluator.cpp, compiler/aarch64/codegen/OMRTreeEvaluator.hpp, compiler/arm/codegen/OMRTreeEvaluator.cpp, compiler/arm/codegen/OMRTreeEvaluator.hpp, compiler/il/VectorOperations.enum, compiler/optimizer/OMRSimplifierTable.enum, compiler/optimizer/ValuePropagationTable.hpp, compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRTreeEvaluator.cpp, compiler/p/codegen/OMRTreeEvaluator.hpp, compiler/riscv/codegen/OMRTreeEvaluator.cpp, compiler/riscv/codegen/OMRTreeEvaluator.hpp, compiler/x/codegen/OMRTreeEvaluator.cpp, compiler/x/codegen/OMRTreeEvaluator.hpp, compiler/z/codegen/OMRTreeEvaluator.cpp, compiler/z/codegen/OMRTreeEvaluator.hpp
- msplats opcode takes 'true' or 'false' value and splats it into all lanes of the mask
- 'true' must be represented as -1 and 'false' as 0 of type TR::Int8
- operation is undefined for any other value
- implement Power evaluator
=> Add msplats Vector operation

port/aix/omrvmem.c, port/linux/omrvmem.c
This commit corrects formatting and condition structure to comply
with the OMR coding standard:
https://github.com/eclipse-omr/omr/blob/master/doc/CodingStandard.md
Related: #7795
Related: #7796
=> Apply OMR coding standard fixes for PRs #7795 and #7796

compiler/optimizer/OMROptimizer.cpp, compiler/optimizer/OMROptimizer.hpp, compiler/optimizer/OMROptimizerAnalysisPhases.enum, compiler/optimizer/OMROptimizerAnalysisPhasesEnum.hpp, compiler/optimizer/OptimizerAnalysisPhases.enum, compiler/optimizer/OptimizerAnalysisPhasesEnum.hpp
This change moves the definition of the `Optimizer::AnalysisPhases enum` values into a new file, `OMROptimizerAnalysisPhases.enum`.
The values are used in a macro `OPTIMIZER_ANALYSIS_PHASES_MACRO` which allows files that ultimately include `OMROptimizerAnalysisPhases.enum` to define the enum type, `Optimizer::AnalysisPhases`, using those values and to define a new method, `Optimizer::getOptimizationAnalysisPhaseName` that, given one of the enum values, will return the analysis phase name for debugging purposes.
This change also allows for the possibility that a downstream project might need to define additional optimizer analysis phases.
=> Make optimization analysis phase enum extensible

port/common/omrport.tdf, port/unix/omrsysinfo.c
Use proc_listpids to extract pids on macOS
Use proc_pidpath to extract executable paths.
=> Extend SystemProcesses API implementation to macOS

fvtest/compilertriltest/CMakeLists.txt, fvtest/compilerunittest/CMakeLists.txt, fvtest/tril/examples/incordec/CMakeLists.txt, fvtest/tril/examples/mandelbrot/CMakeLists.txt, fvtest/tril/test/CMakeLists.txt
Policy settings are inherited from parent folders.
=> Remove redundant uses of cmake_minimum_required()

compiler/optimizer/LoopVersioner.cpp
The original node was passed directly to `createLoopEntryPrep()`, which could cause incorrect increases to the reference counts of some of its descendants if speculative evaluation required additional versioning tests to ensure that safety preconditions would hold.
=> Duplicate unmentioned receiver to privatize when versioning a guard

gc/base/Configuration.cpp
If one of the initialization stages fails, the process should not
proceed to the next stage. Instead, it should immediately clean up
any created structures and return NULL.
=> Fix failure code path for object heap creation

compiler/optimizer/LocalOpts.cpp, compiler/optimizer/VPHandlers.cpp, compiler/ras/Debug.cpp
All resolved fixed object refs now also have known object indices, so the clauses deleted here are currently dead anyway.
=> Stop loading fixed refs without known object indices at compile time

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp
This is supposed to replace the existing `-Xjit:disclaimMemoryOnSwap` option. 
The replacement will be done in stages to avoid omr/openj9 build breaks.
=> Create option -Xjit:preferSwapForMemoryDisclaim

port/common/omrport.tdf, port/win32/omrsysinfo.c
Use EnumProcesses and QueryFullProcessImageName to extract PID and executable paths on Windows.
=> Extend SystemProcess API Implementation to Windows

port/common/omrgetsysname.h, port/unix/omrshmem.c, port/unix/omrshsem_deprecated.c, port/zos390/omrgetthent.h, port/zos390/omrsimap.h, thread/common/thrprof.c, thread/zos390/omrgetthent.h, util/omrutil/gettimebase.c
Includes all the initial work done a while ago made in order to support compiling with Open XL in context of z/OS.
(This is one part of the multiple changes added for supporting Open XL compilation on OMR)
=> Initial changes for Open XL z/OS support

compiler/p/codegen/OMRCodeGenerator.cpp, compiler/p/codegen/OMRInstOpCode.enum, compiler/p/codegen/OMRInstOpCodeProperties.hpp, compiler/p/codegen/OMRTreeEvaluator.cpp
Implement PPC codegen for `mAllTrue` and `mmAllTrue` for Byte, Short, Int, and LongVectors on P8+
=> Implement mAllTrue and mmAllTrue on PPC

compiler/codegen/RegisterConstants.hpp, compiler/ras/Debug.cpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRRegisterDependency.cpp, compiler/x/codegen/OMRX86Instruction.cpp
X87 registers are no longer allocated.
Reimplementation of https://github.com/eclipse-omr/omr/pull/6380/commits/379ced3f0f671d3d0f8a40dc427d383e7cbd9b8d
=> Remove TR_X87_Mask guarded code

include_core/omrsig.h
Apply throw() for signal functions with Open XL
https://github.com/eclipse-omr/omr/pull/7807 introduced OMRSIG_NO_THROW,
which is non-empty for C++ contexts, with exceptions for AIX, macOS and
z/OS.
Open XL on z/OS still requires these methods declare that they do not throw
exceptions, this rectifies the conditional to do so
-----------------
Related/Original issue: https://github.com/eclipse-omr/omr/pull/7320
@keithc-ca I have separated out the remaining problem from the original PR, and created a draft PR while I investigate the changes here closer.
Here I have removed all the `throw()` references, and will attempt to recompile and go through the errors.
=> Apply throw() for signal functions with Open XL

compiler/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp
This commit introduces `getMaxPreferredVectorLength()` for detecting the optimal vector length for compiler intrinsics. The preferred VL may be more restrictive than what the CPU supports. Its purpose is to prevent vectorization related performance issues. New intrinsics that support vectorization should consult this function. A default implementation is provided on x86.
=> Introduce getMaxPreferredVectorLength()

include_core/omrport.h, port/common/omrsysinfo.c, port/common/omrsysinfo_helpers.c, port/common/omrsysinfo_helpers.h, port/linuxs390/omrsysinfo_helpers.h, port/unix/omrsysinfo.c, port/win32/omrsysinfo.c
This change adds three new fields to J9SysinfoCPUTime: userTime,
systemTime, and idleTime. These fields support a more accurate
CPU load computation across platforms.
On Linux, the CPU load calculation now includes time spent servicing
hardware (irq) and software (softirq) interrupts as part of total
system usage. These components were previously omitted, which could
lead to underreporting CPU load. The update reflects improvements
in Linux kernel 5.x and later, where interrupt time tracking is more
accurate and consistently reported.
On z/OS, the dual timestamp logic is removed. The system provides
aggregate CPU time and entitlement capacity directly, allowing load
to be computed from a single snapshot. This simplifies the
implementation while preserving correctness.
The new calculation …
=> Add fields to J9SysinfoCPUTime and improve CPU load calculation

util/a2e/atoe.c
Replace uses of `,` where `&&` was intended.
=> Fix loop conditions

cmake/modules/platform/toolcfg/openxl.cmake, util/omrutil/j9memclr.cpp
Some miscellaneous changes and updates required in support of compilation with the latest version of Open XL on z/OS.
---
- Target Level needs to be z/OS V2R5. Seem to be having errors unless this is updated even with Open XL 2.1.0.3 after all my cleanup and rebasing of repos.
- Pragma map error, cpp team has recommended encompassing the pragma map method within `extern C` , this is required due to ambiguous resolution of the parameter (int or void)
@keithc-ca
=> Update zos target level + fixes for Open XL z/OS

compiler/control/OMROptions.cpp
Reverts eclipse-omr/omr#7704
Causes a downstream project build break.
=> Revert "Re-enable allocation/initialization opt"

port/zos390/omrzfs.c
The noinline restrictions for getZFSClientCacheSize and getZFSUserCacheUsed are no longer required with Open XL 2.1.0.3+ on z/OS as the root issue has been fixed.
@babsingh @keithc-ca This is a revisit to our issue created a while back: https://github.com/eclipse-omr/omr/issues/7653
These optimizations are no longer needed and the root cause has been fixed.
=> Restore optimization for functions in omrzfs.c

compiler/il/OMRDataTypes_inlines.hpp
- we have a convention of presenting Mask elements as integral types
- the easiest way to enforce that convention is to convert the element type at the time of Mask type creation
=> Always use integral type for Mask elements

compiler/optimizer/ValuePropagationCommon.cpp
This commit accelerates a new converter method in
Java 11+ - SingleByte$Encoder.encodeFromLatin1Impl. The new method is analagous to an existing Java 8 converter method so the previous acceleration work in VP is leveraged to accelerate the new routine as well.
=> Accelerate new converter method SingleByte$Encoder.encodeFromLatin1Impl

compiler/ras/Debug.cpp, compiler/ras/Debug.hpp, compiler/x/codegen/OMRCodeGenerator.cpp, compiler/x/codegen/OMRCodeGenerator.hpp, compiler/x/codegen/OMRInstruction.cpp, compiler/x/codegen/OMRX86Instruction.cpp
Since forward register assignment was removed, the logic for checking register assignment direction is redundant.
=> x86: Remove register assignment direction checks

port/unix/omrsysinfo.c
=> Accommodate the long-future Power processors gracefully

gc/base/CycleState.hpp
This change adds a new value and variable to cycle state to be used later on for jfr logging.
=> Add GC reason for use in JFR

compiler/aarch64/codegen/OMRMemoryReference.cpp
This commit enables an assertion for memory access with offset.
=> AArch64: Enable an assertion for 16-byte-wide memory access

compiler/infra/OMRCfg.hpp
LOW_FREQ is used to indicate the lower bound for the frequency of a block. However, in cases where a method may have a small number of absolute samples, this can cause blocks that aren't actually low frequency to be interpreted as such.
Changing the value to 1 ensures that the compiler considers more blocks than it used to in the past.
=> Change LOW_FREQ to 1

compiler/infra/Checklist.cpp
There was a rare scenario in which a memory allocation failed and as part of handling the OOM the destructor for `Checklist` was called. Calling `BitVectorPool.release()` required a memory allocation which failed due to being out of memory. This throw inside a destructor resulted in the program terminating. This is similar to the scenario described in issue #3083. 
Wrapped the call to `BitVectorPool.release()` in `if (!std::uncaught_exception())` to avoid this double throw scenario.
=> Avoid uncaught exception in `Checklist` destructor

compiler/cs2/sparsrbit.h
- Handle allocation failure in CS2 sparse bit vector assignment operator
- Consolidate CS2 sparse bit vector copying logic
- Extract common logic for adding a segment to a CS2 sparse bit vector
- Handle allocation failure adding a segment to CS2 sparse bit vector
- Handle alloc failure when removing a CS2 sparse bit vector segment
The problem in `operator=()` could cause a crash when allocation fails during an assignment `lhs=rhs`, where `rhs` is an `ASparseBitVector` with at least one segment. Typically it would crash while destroying `lhs` during unwinding.
As for the problem in `{Add,Remove}Segment()` (and the duplicated add segment logic in `SparseBitRef::Set()`), I think it's most likely unobservable at the moment. To hit an actual symptom, we'd need to catch the exception and then …
=> Fix a few exception safety bugs in CS2 sparse bit vector

compiler/aarch64/codegen/OMRCodeGenerator.cpp, compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/p/codegen/OMRCodeGenerator.cpp
This option is primarily useful for diagnostic investigations and provides a means to prevent the use of mechanisms (such as allocation fences) to enforce store ordering.
This option should NOT be enabled in any production environments by default.
=> Provide compiler option to disregard CPU store ordering requirements

compiler/control/OMROptions.cpp, compiler/control/OMROptions.hpp, compiler/control/OptionsUtil.hpp
Adjust the CodeCacheKind enum to add support for OpenJ9 code cache segregation.
=> Add support for downstream Code Cache segregation

compiler/x/codegen/OMRCodeGenerator.hpp
BMI1 and BMI2 only use GPRs and thus do not depend on XSAVE.
=> Remove XSAVE check for BMI support

compiler/aarch64/codegen/OMRTreeEvaluator.cpp
Forward arraycopies are expected to be the common case, and investigation on other platforms suggests that arraycopies <=63 bytes are important in a number of workloads and will benefit from being specialized inline.
This optimization can be disabled by setting the environment variable `TR_DisableInlinePrimitiveForwardArraycopy`
=> Inline short, primitive, forward arraycopies on AArch64

compiler/codegen/OMRCodeGenPhase.cpp, compiler/codegen/OMRCodeGenerator.hpp
This commit introduces two new hook functions that the execute immediately before and after binary encoding.
=> Introduce hooks before and after binary encoding

compiler/codegen/OMRTreeEvaluator.cpp
`preEvaluateEscapingNodesForSpineCheck` gets called to pre-evaluate a future used commoned node before branching out of mainline code. It restricts pre-evaluating conversions with array-access children for correctness of access. But if array-access is already evaluated this restriction is non-beneficial and might prevent a needed pre-evaluation into the mainline code for a future used commoned node.
For example, in a tree like below, the restriction does not allow early evaluation of the `n764n aloadi` as expected, but should allow early evaluating `n769n i2l` given that the array access child `n779n iloadi` is already evaluated.
```
n763n    (  0)  BNDCHKwithSpineCHK [#1] (Unsigned spineCHKWithArrayElementChild )                    [0xa0001005009de30] bci=[-1,37,2119] rc=0 vc=3348 vn=- …
```
=> Allow pre-eval escaping conversion nodes of evaluated array-access

compiler/p/codegen/OMRMachine.cpp, compiler/p/codegen/OMRRegisterDependency.cpp, compiler/p/codegen/PPCDebug.cpp
- While allocating a free vector register it might require a spill
and, therefore, a temporary GPR as an index register (due to the alignment issues)
- To avoid all GPRs being blocked, allocate vector registers first
=> Allocate Vector registers before GPRs

compiler/optimizer/Inliner.cpp
This change reduces compilation overhead and allows methods to reach higher opt levels sooner.
=> Set node count thresh to 8k for Xtune:throughput

compiler/codegen/OMRCodeGenerator.hpp, compiler/codegen/OMRInstruction.hpp, compiler/codegen/OMRLinkage.hpp, compiler/codegen/OMRMachine.hpp, compiler/compile/OMRCompilation.hpp, compiler/compile/OMRSymbolReferenceTable.hpp, compiler/il/OMRBlock.hpp, compiler/infra/Annotations.hpp, doc/compiler/extensible_classes/Extensible_Classes.md
This PR introduces an `OMR_FINAL` attribute that can be used in the compiler component to decorate member functions in C++ extensible classes to indicate they will not be overridden by a subclass. This attribute is not enforced by the compiler at build time and serves primarily as documentation. However, its intended semantics in the code can be verified using third-party linting tools, such as those built with Clang.
The introduction of this attribute is motivated by the desire to improve code readability by eliminating the requirement for `self()` calls when dispatching trivial member functions (such as getters and setters) in extensible classes.
This PR includes a commit that demonstrates how and where `OMR_FINAL` can be used in a number of extensible classes. This is not an exhaustive …
=> Introduce OMR_FINAL attribute for extensible classes

compiler/optimizer/VPHandlers.cpp
With the array-shadow symref replacing the unsafe shadow symref, the existing alias sets may no longer be valid. This fixes a problem observed during DeadTreesElimination where the incorrect alias sets resulted in an invalid transformation.
=> Invalidate alias sets upon refinement of unsafe shadows during VP
