eclipse-omr/omr

compiler/optimizer/RedundantAsyncCheckRemoval.cpp

Added a test to avoid unnecessary async checks being added to code
that isn't going to be recompiled because it's already at scorching.

Avoid unnecessary async checks at scorching

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

Updates the implementation of the following evaluators on z to support the
float data type:
vadd, vsub, vmul, vdiv, vneg
vsplats, getvelem, vsetelem
Many of those evaluators made calls to inlineVectorUnaryOp and
inlineVectorBinaryOp. Those functions were also updated to handle the
float data case. They now set the proper bits in a vector instruction when
a float version is used.
In most of the modified functions, a check for zNext was added since it is
necessary for the float versions of the vector instructions to be used.
getSupportsOpCodeForAutoSIMD was updated to reflect the new support for
floats on zNext.
Issue: #950

Expand AutoSIMD support on z to floats

---

compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

Relocation was not provided for contant child of compare equality node
if that node is not profile guarded. This commit will fix
this issue by calling evaluate() on constant child for
it is a method pointer or a class pointer constant and
relocation is required.

Evaluate relocatable constant child of compare equality node

---

include_core/omrsig.h
omrsigcompat/makefile
omrsigcompat/omrsig.cpp

Glibc 2.21 removes reference to sigvec and calls out the fact that its
an ancient unused interface.  Rather than hacking around to support it
on old compilers, let's just remove it.
There are no known upstream consumers of this function.

Remove all references to deprecated 'sigvec'

---

port/port_objects.mk

By only providing a default we allow the environment to tell us where the CUDA toolkit is installed.

Provide only a default for CUDA_HOME

---

compiler/p/codegen/OMRMachine.cpp
compiler/p/codegen/OMRMachine.hpp
compiler/p/codegen/OMRRegisterDependency.cpp
compiler/p/codegen/PPCInstruction.cpp

Prior attempt at improving the way we handle register spills during out of line register assignment (#908) was not sufficient to deal with the case where a register is spilled between the branch and merge of an out of line section, is also spilled out of line, is subsequently unspilled out of line, and therefore must be re-spilled at the end of out of line RA in order to restore the register file to its expected state. Under these conditions we have to make sure that the unspill of the register does not free the spill slot for re-use, since we will need to forcefully re-spill the register.
This PR reverts #908 and attempts to address this problem by only unlocking the free spill list in out of line code sections in specific, safe circumstances and by freeing spill slots after out of line …

Free out of line spills on Power

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp

When OSR transitions are implemented using OSR guards, the taken
side of the guard manages several book keeping aspects of the
transition. For example, it will contain stores to dead symbol
references and will remat symbol references required for the
transition. This block can be ignored by several optimizations.
To allow for this, this change adds a check for such a block.

Add check for OSR induce block

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

OSR points are surrounded by pending push stores, to ensure
the stack is recreated after the transition, and treetops of
pending push loads, to avoid the side effects of the prior mentioned
stores. This adds functionality to determine if a node is one of
these and to extract the transition point for an OSR point based
on the current mode.
Moreover, it corrects an issue with OSR analysis as liveness and
use/def information should be calculated at the transition or
analysis point, not the OSR point.

Add common functions to OSR API concerning PPS

---

compiler/control/OMROptions.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LocalOpts.hpp

Goto elimination will attempt to remove blocks that contain
a series of asyncchecks followed by a goto. To ensure the asynccheck
is still present, it is currently moved to all of its predecessors.
However, these may have other successors, some of which may not
correctly manage the addition of a yield point. To correct this,
the asynccheck is shifted to the start of the goto's destination block
which should contain anything needed to account for the yield.

Prevent gotoElim from skipping asynccheck in OSR

---

compiler/compile/VirtualGuard.cpp
compiler/compile/VirtualGuard.hpp
compiler/ras/Debug.cpp

Existing guards may be reused to implement OSR transitions. These
guards should be marked appropriately so that they can be
patched when necessary, similar to OSR guards. This change adds
a property to signify this, similar to the existing mergedWithHCR flag.

Add property to merge guards with OSR guards

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp

Catch event could make JIT yield to vm in involuntary OSR mode and
the inserted async check is used as an indication of an OSR point
for the start of the catch block. This change is to prevent the
syncchk from being removed.

Add async check for exception handlers for fsd

---

compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp
compiler/x/codegen/SIMDTreeEvaluator.cpp
compiler/x/i386/codegen/TreeEvaluatorTable.hpp
fvtest/compilertest/build/files/target/x.mk
jitbuilder/build/files/target/x.mk

Initial supported evaluators:
vadd
vmul
vsplats
vload
vloadi
vstore
vstorei
vbRegLoad
vsRegLoad
viRegLoad
vlRegLoad
vfRegLoad
vdRegLoad
vbRegStore
vsRegStore
viRegStore
vlRegStore
vfRegStore
vdRegStore
Issue #997 

Introduce SIMD evaluators on X86

---

compiler/p/codegen/ControlFlowEvaluator.cpp
compiler/p/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/S390Instruction.cpp

OSR guards are NOP patch sites, which are patched at a GC point
into an unconditional branch, much like HCR guards. This change
updates Z and Power codegen to treat them appropriately.

Treat OSR Guards appropriately in codegen

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp

When requesting the ByteCodeInfo for an OSR point that is the
child of a treetop, it is necessary to get the child's ByteCodeInfo.
This is required as the treetop may have a different value, confusing
the OSR infrastructure which relies on this value to determine the
transition point.
The API's function to fetch this value would accidentally modify
the treetop's BCI to match that of its child in the described case.
This would limit profiling later on as it relies on these values
to remain consistent.

Fix accidental modification of BCI

---

compiler/optimizer/RegisterCandidate.cpp

OSR induce blocks will contain loads and stores of symbol references
to remat those that are live at the transition. As these blocks will
typically never be visited and, in the event that they are, performance
is expected to be bad, they should be ignored when determining the
weight for register candidates. This allows other symbol references,
used in the main line execution, to have registers allocated to them
and reduces spilling.

Ignore OSR induce blocks in GRA

---

compiler/control/OMROptions.hpp

FSD has been using mimic interpreter frame shape to facilitate
the transition from JITted code to interpreter which largely
limit the optimizations can be applied. By disaliasing FSD and
mimic interpreter frame shape, fsd uses OSR instead
and therefore allows more optimizations to happen.

Disalias mimic interpreter frame shape and FSD

---

fvtest/algotest/hooktest.c
gc/base/MemoryPoolLargeObjects.cpp
gc/base/OMRVMInterface.cpp
gc/base/standard/ConcurrentCardTable.cpp
gc/base/standard/ConcurrentGC.cpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/Scavenger.cpp
gc/verbose/VerboseHandlerOutput.cpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
include_core/omrhookable.h
omr/omrtrcinit.c
tools/hookgen/HookGen.cpp
util/hookable/hookable.cpp
util/hookable/hookable.exportlist
util/hookable/hookable_include.mk
util/hookable/j9hook.tdf

- "time threshold" = 100 milliseconds
- new function J9HookRegisterWithCallSite(), pass CALLSITE to
J9HookRecord via J9HookRegisterWithCallSite()
- use portLib to calculate elapsed time for callback function
- add tracepoint in J9Hookable
- collect hook information for hook dump section

Trigger a tracepoint for VM hooks that exceed a threshold

---

compiler/runtime/OMRCodeCache.cpp
compiler/runtime/OMRCodeCache.hpp

Remove unused `setupSegment()` from CodeCache

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/MethodBuilder.hpp
jitbuilder/release/src/Switch.cpp
jitbuilder/release/src/Switch.hpp

Currently if JitBuilder clients want to Call a function using either
Call or ComputedCall, that function must have been described to
JitBuilder via the DefineFunction call on the MethodBuilder object.
All Calls lookup the function name provided and will fail to call it
if DefineFunction has not yet been called. The only way to make sure
the function has been defined is to make sure you call it yourself
before that function name is called.
This commit adds one check inside the Call services so that, if the
first lookup fails, it will call a virtual instance on MethodBuilder
called RequestFunction. Clients can implement this instance function
in their subclass of MethodBuilder to locate and call DefineFunction
for the requested function name. When RequestFunction() comes back,
the Call …

Enable on-demand method lookup for JitBuilder

---

example/glue/ScavengerRootScanner.hpp
gc/base/GCExtensionsBase.hpp
gc/base/MemorySubSpaceGenerational.cpp
gc/base/MemorySubSpaceSemiSpace.cpp
gc/base/SlotObject.hpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/PhysicalSubArenaVirtualMemorySemiSpace.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Use the flag to decide in runtime whether some part of Scavenger code
runs or not, depending if CS is requested or not. 
This will allow running both plain Scavenger and Concurrent Scavenger
under same build (as long as compile time CONCURRENT_SCAVENGER flag is
enabled in the build).

Runtime concurrentScavenger flag

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/Inliner.cpp

This adds an option to disable OSR call site remat, as there is a
significant risk it could present problems and will assist in
debugging.

Add option to disable OSR call site remat

---

compiler/z/codegen/UnaryEvaluator.cpp

When running with compressed refs shift > 0, we are not evaluating shift
child since guarded load does both load and shift. We need to decrement
ref count on the right node. This code will get removed once we will
deliver proper fix for not anchoring l2a nodes for concurrent scavenge.
Signed-off-by: evgeniab@ca.ibm.com <evgeniab@ca.ibm.com>

Fix live registers issue for concurrent scavenge

---

tools/ddrgen/src/blob_generation/java/genBinaryBlob.cpp
tools/ddrgen/src/blob_generation/java/genSuperset.cpp
tools/ddrgen/src/blob_generation/java/genSuperset.hpp
tools/ddrgen/src/cmdline_tool/main.cpp
tools/ddrgen/src/intermediate_representation/ClassUDT.cpp
tools/ddrgen/src/intermediate_representation/ClassUDT.hpp
tools/ddrgen/src/intermediate_representation/EnumUDT.cpp
tools/ddrgen/src/intermediate_representation/EnumUDT.hpp
tools/ddrgen/src/intermediate_representation/NamespaceUDT.cpp
tools/ddrgen/src/intermediate_representation/NamespaceUDT.hpp
tools/ddrgen/src/intermediate_representation/Symbol_IR.cpp
tools/ddrgen/src/intermediate_representation/Symbol_IR.hpp
tools/ddrgen/src/intermediate_representation/Type.cpp
tools/ddrgen/src/intermediate_representation/Type.hpp
tools/ddrgen/src/intermediate_representation/TypedefUDT.cpp
tools/ddrgen/src/intermediate_representation/TypedefUDT.hpp
tools/ddrgen/src/intermediate_representation/UnionUDT.cpp
tools/ddrgen/src/intermediate_representation/UnionUDT.hpp
tools/ddrgen/src/scanners/dwarf/AixSymbolTableParser.cpp
tools/ddrgen/src/scanners/dwarf/DwarfScanner.cpp

The old removeDuplicates() algorithm has been replaced entirely with a new one which simply checks that only one structure with a given full name is printed in the superset and blob, significantly improving performance.
As a side-effect of this change, several missing structures in the generated superset have been fixed. In addition, minor tweaks to the DwarfScanner have fixed additional missing structures.
Some missing JVM structures (around ~200) caused by bugs in the AIX parser are also fixed.
Signed-off-by: Tony Wang <twlogger@gmail.com>

Move remove duplicates to gen superset

---

gc/base/MemoryPool.hpp
gc/base/MemoryPoolLargeObjects.cpp
gc/base/MemoryPoolLargeObjects.hpp
gc/base/standard/ConcurrentSweepScheme.cpp
gc/base/standard/ConcurrentSweepScheme.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/ParallelSweepScheme.hpp
gc/stats/CollectionStatisticsVLHGC.hpp
gc/verbose/schema.xsd

- update concurrent sweepStates after heap resize at end of global gc
to avoid losting free memory and wrong memory usgage reporting
- update verbosegc schema to allow warning in <mem-info>

correct concurrent sweepStates after heap resize

---

compiler/control/OMROptions.cpp

It has been empirically tested that because z/Architecture lacks a call
return stack we tend to incur a higher penalty for calling methods. As
such inlining slightly more helps overall performance.
Increasing the big callee threshold has been found to causea marginal
increase in compile time at the benefit of very observable throughput on
the platform. As such making this increase the default.

Adjust big callee threshold on z Systems

---

compiler/optimizer/LoopReplicator.cpp

AsyncCHKs are OSR points and VM relies on correct bytecode info
to transfer to the next bytecode execution. When inserting an
asyncCHK node, we need to make sure it has the same bytecode info
as the node right before or after. The original code makes the
inserted AsynChk have bytecode info of the next **treetop** which is
incorrect beause it might skip children of the node hanging under
that treetop and make VM believe the bytecode represented by the
children have already been executed and resume execution from the
wrong place.

Fix bcInfo of asyncCHK node

---

port/common/omrcuda.cpp

Corrects the preprocessor conditions controlling runtime support for CUDA runtime versions based on the CUDA version used at compile. time.
fixes #1030

Correct CUDA runtime forward compatibility

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/include/omrmm.hdf
gc/verbose/VerboseHandlerOutput.cpp

Concurrent Scavenger: Introduce an additional 'requested' flag that will be set during parsing
of the CS command line option. There might be platform/language specific
requirements after we parsing is done that will dictate whether the
request is obeyed or not.
Add a line in 'initialized' verbose GC stanza to report if we actually
run CS or not.

Allow late decision whether to obey CS request

---

compiler/control/OMROptions.cpp

We found 256KB to be the right size for most of the workloads we looked at,
including Liberty/Hadoop/Spark. We have seen significant performance benefit
from this change.

Increase the default pseudo-TOC size

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/TypeDictionary.cpp
compiler/ilgen/TypeDictionary.hpp

Add a pNoType definition to TypeDictionary.  This turns various indexing
and derefering oprations into potentially dangerous operations.  To help
prevent forest fires, add asserts to those operations to catch
inadvertent [and nonsensical] dereferences of untyped pointers.
Resolves #511.

Provide an untyped pointer type in TypeDictionary

---

compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp

Currently the z Systems codegen is generating a load-store loop for
forward reference arraycopy because of a historic bug that is now moot.
This commit enables generation of the same MVC sequence for reference
arraycopy that we use for primitive arraycopy.
We take this time to reorganize, simplify, and document all arraycopy
evaluators on z Systems. We now have a consolidated path for primitive
and reference arraycopy with maximal code reusage.

Add MVC support for reference array copy

---

gc/base/EnvironmentBase.cpp

The tryAcquireExclusiveVMAccess path in the GC will wait for another
thread if the other thread is already acquiring exclusive VM access.  It backs off
using releaseCriticalHeapAccess and reacquireCriticalHeapAccess.  The
acquireExclusiveVMAccess path uses releaseVMAccess(bool) and acquireVMAccess.
Change acquireExclusiveVMAccess to be consistent with
tryAcquireExclusiveVMAccess so the delegate may more easily detect the
exclusive backoff case.

Use consistent exclusive access backoff

---

compiler/optimizer/Inliner.cpp

comp->isJProfilingCompilation() was recently changed to always return false
on the account that there is a similar query in CompilationInfo.
However, comp->isJProfilingCompilation() is used in the inliner.
This query will be replaced by  comp->getOption(TR_EnableJProfiling) which is
correct as long as the JIT doesn't change its mind while optimizing the
method in hand. Currently the JIT never changes its mind once it decided it
is going to generate a JProfiling body. Even if the JIT will turn off
JProfiling midway while optimizing a method, the resulting code is still
correct with no runtime performance penalty. The only downside is a small
compilation time increase.

JProfiling bug fix

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

Concurrent scavenge requires GC support, hardware checks, OS level
checks, and guarded storage block initialization to be properly done.
The infrastructure for such plumbing work should be done at a downstream
OMR project level. As such we are defaulting concurrent scavenge to be
disabled by default unless a downstream project extends the
CodeGenerator class and overrides the value.

Default isConcurrentScavengeEnabled to false

---

doc/BuildingWithCMake.md

This is just a little tutorial on how to build OMR using CMake.
This doesn't document our usage of CMake.
Cc: @dnakamura 
Issue: #993

Add documentation for the experimental CMake build

---

compiler/compile/OMRCompilation.cpp

Partial inlining will copy the inlined call into the inlined body, to use
as the recovery in the event execution leaves the inlined portion of
the call. As this call is copied, it does not maintain the required
infrastructure for OSR.

Disable PartialInlining under OSR

---

compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp

These functions are J9 project specific:
* CodeCacheManager::addFaintCacheBlock
* CodeCacheManager::freeFaintCacheBlock

Remove project-specific CodeCacheManager functions

---

compiler/optimizer/OMROptimizationManager.hpp
compiler/optimizer/OMROptimizer.cpp

Currently, frequencies will be calculated and set before an
optimization when all necessary information is present. It is then
maintained across modifications to the CFG. This necessary information
includes structure analysis.
This change allows an optimization to explicitly prevent frequencies
from being set before itself. This is useful for early opts that require
structure, but not frequency, and may significantly alter the structure
to the point where the frequency data would not have been adequately
maintained.

Add flag to skip setting frequency

---

.travis.yml
scripts/build-on-travis.sh

- Shallow git clone
- Make --job parallelism
- CMake: Use the Ninja generator
It's difficult to time, when caching behaviour seems to be a little
unpredictable, but these changes seems to help.
A one-off measurement (with ccache populated):
- Make:  17m -> 15m
- CMake: 17m -> 09m
- Lint:  06m -> 02m
I've also started timing major build steps, to help evaluate build
system changes.

Make the travis builds faster

---

gc/base/MemoryPool.hpp
gc/base/MemoryPoolLargeObjects.cpp
gc/base/MemoryPoolLargeObjects.hpp
gc/base/standard/ConcurrentSweepScheme.cpp
gc/base/standard/ConcurrentSweepScheme.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/ParallelSweepScheme.hpp
gc/stats/CollectionStatisticsVLHGC.hpp
gc/verbose/schema.xsd

Reverts eclipse/omr#1019
This change is causing issues when concurrent sweep is happening.  I am reverting the PR until the concurrent sweep issues can be resolved

Revert "correct concurrent sweepStates after heap resize"

---

fvtest/threadtest/abortTest.cpp

In the original test, the sleeper could enter and notify on enterSync
before main hits wait.  This could result in the main thread waiting
for a notify that never comes.
The new test also replaces a hardcoded sleep in main with a notify. In
an ideal world, it would be safe to call abort as soon as
omrthread_create returns.
This probably fixes issue #1050, where this test was hanging. It now
takes ~1second on my laptop.

Fix a race in ThreadAbortTest.Sleeping

---

gc/base/ObjectScanner.hpp

Fix -Werror=unused-but-set-variable error in OpenJ9 compile.

Extract MM_MarkingDelegate from CLI

---

compiler/il/OMRNode.cpp
compiler/optimizer/ValuePropagationCommon.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

Reference arraycopies are important when concurrent scavenge is enabled.
We need to determine at code generation time that a particular arraycopy
is indeed a reference arraycopy such that we can generate read barriers
for every array element access. As such it is important that all
arraycopy nodes that are in fact reference array copies specify the data
type of the array elements is a TR::Address.
We will use this fact in the code generator to determine whether we need
to generate read barriers for array reference loads.

Enforce reference arraycopy has type TR::Address

---

compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/X86Debug.cpp
compiler/x/codegen/X86Ops.hpp
compiler/x/codegen/X86Ops.ins
compiler/x/codegen/X86Ops_inlines.hpp

1. Remove unused property - CannotBeAssembled
2. Repurpose little-used property - PseudoOp - for all dummy/pseudo instructions

Code cleanup related to pseudo instruction on X86

---

fvtest/threadtest/abortTest.cpp

Just return 0, the RC is unused.
Cc: @ktbriggs

Don't convert intptr_t to int

---

compiler/x/codegen/OMRInstruction.hpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/codegen/X86Ops.hpp
compiler/x/codegen/X86Ops_inlines.hpp
doc/compiler/x/OpCodeEncoding.md

Initial support for AVX/AVX2/FMA instructions that uses VEX prefixes.

Experimental AVX Support on X86

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/optimizer/Inliner.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

OSR guards now support guard merging, under the same conditions
as HCR guards. This renames checks required to merge these
guards to not specify HCR.

Rename guard merging checks to not specify HCR

---

gc/base/HeapVirtualMemory.cpp

* Remove 8-bytes tail padding for ZOS platforms. It was used to support JIT optimization on old HW - not necessary any more
* Simplify Aggressive GC rules for tail padding to:
"Skip extra physical page tail padding if size of it is 1GB or larger"
Remove all exceptional cases for it: was excluded for all zLinux and ZOS platforms - there is no any more reason to keep this exception; was limited to Compressed Refs platforms only - might be extended for all platforms now

Clean up object heap tail padding rules

---

compiler/z/codegen/OMRMachine.cpp

When assigning register pairs we need to consider two cases of either
the even or odd register in the register pair being spilled. In such a
case we must reverse the spill state of the respective register, however
we must be careful here not to cause changes to the register state of
the other register in the register pair.
For example if we are attempting to assign a pair of registers (A,B)
where A has been spilled onto the stack and B is currently in a register
we must be careful to not evict B from the register state when reversing
the spill state of A.
To avoid such issues we block register B until the spill state of
register A has been reversed. We must also unblock register B following
this action.
This commit addresses a problem in which we do not correctly unblock
register B, and …

Correctly block/unblock even/odd register pairs

---

compiler/z/codegen/OMRTreeEvaluator.cpp

VMSL instruction is used to improve ECC performance on Z-system.
Setting TR_disableVMSL environment variable can disable this optimization (for debugging purposes).
Signed-off-by: Hadi Jooybar <hjooybar@ca.ibm.com>

Add an option to disallow using vector multiply sum

---

compiler/optimizer/ValuePropagationCommon.cpp

Compressed and decompressed array copies are also primitive array copies
and as such we must set the type and element size of these special array
copies after setting the type and element size as derived from the fact
that they are primitive array copies as well.
This is done to enforce the fact that for the specially recognized
decompressed array copies we have type set to TR::Int16 and element size
derived from the respective type.

Set arraycopy type in correct order

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/env/FEBase.cpp

Provide specialized functions for option processing functions that need
to operate on JitConfig. The JitConfig is actually cached in a static
field in OMR::Options::_feBase, so it is readily available.
This change paves the way to splitting the option flags into OMR generic
ones and option flags that are only used by subprojects.
Issue: #1055

Specialized 'fe' option processing routines

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OpMemToMem.cpp
compiler/z/codegen/OpMemToMem.hpp

This commit enables the previously disabled (under concurrent scavenge)
transformation of the array copy call into the arraycopy node.
In order to handle a current scavenge cycle, the compiler generates code
to check a runtime flag. Execution conditionally branches to an Out Of Line
sequence which contains the necessary guarded load, shift, and store
instructions. This code is only active under `#ifdef J9_PROJECT_SPECIFIC`.

Enable Array Copy under Concurrent Scavenge

---

compiler/p/codegen/OMRTreeEvaluator.cpp

When the array length is not known at compile time, a sequence of close
to 300 instructions is needed to cover all cases of the array copy.
Inlining this is very costly in terms of performance for small arrays.
Given that most of the arrays seen are a few dozen bytes, it is not
worth inlining. When the length of the array is known at compile time,
inlining can still occur.
Signed-off-by: Ryan Santhirarajan <rsanth@ca.ibm.com>

Disabling Inlined Array Copy on Power

---

compiler/env/ProcessorInfo.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

1. Detect Skylake based Intel X86 CPU;
2. Inline logic querying old Intel CPUs.

Detect new Intel X86 microarchitecture

---

compiler/compile/OMRCompilation.cpp

In involuntaryOSR, exception points could yield to VM and should
be treated as potential OSR points.

Add exception points as potential OSR point in involuntaryOSR

---

compiler/p/codegen/OMRMemoryReference.cpp

When executing on 64bit platforms we must use ld/std rather then lwz/stw to spill registers.
Kevin Langman <langman@ca.ibm.com>

Use 64bit std/ld instructions on a rare spill path

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/optimizer/OSRDefAnalysis.cpp

isPotentialOSRPoint will now account for monents anchored under
treetops. It will also find the OSR node within the tree. This
is used throughout the rest of the API to determine what type
of OSR point is being handled. Failure cases have been
added to the other API calls if the OSR point is not known.

Extend isPotentialOSRPoint to find OSR node

---

compiler/ilgen/IlInjector.cpp

Fix shiftLeftBy to return resulting node pointer
instead of uninitialized value

Fix uninitialized return in IlInjector::shiftLeftBy

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

This commit fixes a bug introduced by PR #1007.
The new implementation of setVerboseBitsInJitPrivateConfig() is able to find
the JitConfig without looking at the value of parameter 'base'. However,
when trying to set the verbose flags in PrivateJitConfig for the trj9
subproject it uses setVerboseBits() which, similarly, was changed to
ignore the parameter 'base' and retrieve the OMR JitConfig from _feBase.
This is wrong.
The solution is to factor out the commong code that sets verbose bits
and call it from two different places:
1) setVerboseBitsInJitPrivateConfig() used by trj9 subproject
2) setVerboseBits() used by OMR generic code
Issue: #1085

Fix processing of verbose options

---

compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
compiler/x/codegen/X86SystemLinkage.cpp
fvtest/compilertest/tests/OpCodesTest.cpp
fvtest/compilertest/tests/X86OpCodesTest.cpp
fvtest/compilertest/tests/X86OpCodesTest.hpp

This commit contains the following change:
- Use correct slot size of address type on 32-bit X86.
- Add evaluators for ifacmp* and acmp* on 64-bit X86.
- Fix a wrong data type in opcode test.
- Enable opcode tests for ifacmp* and acmp* on X86.
Issue: #1087

Enable opcode tests for ifacmp* and acmp* on X86

---

gc/base/Collector.cpp
gc/base/Collector.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

In configuration, where Concurrent Scavenger is compile time enabled,
but run time disabled, we have to check run time flag before accessing
any CS functionality.
Fixing a specific spot in Global GC, that calls Scavenger to complete
any active concurrent cycle.

Check runtime flag if CS code should be run

---

compiler/optimizer/ValuePropagationCommon.cpp

VP may not have the type information of the source or destination arrays
we are copying. However for the specialized String compression array
copies we can be certain that both the source and destination arrays are
primitive arrays. As such it is always safe to set the primitive array
copy flags in VP for such recognized methods.
Failure to set these flags can get us in an invalid state in which we
fail to properly generate array store checks or misinterpret the special
String compression array copies as reference array copies, both of which
are incorrect.

Set array copy flags in VP for recognized methods

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

Updated getSupportsOpCodeForAutoSIMD in x/codegen/OMRCodeGenerator.cpp to
reflect the recently implemented vector evaluators. Instead of returning
false in all cases, getSupportsOpCodeForAutoSIMD will now return true for
loads, stores and vector splats for int32, int64, float and double data
and also double type add and multiply. All of these operations are
supported in the new vector evaluators.
A call to setSupportsAutoSIMD is now made inside initialize in
OMRCodeGenerator.cpp to indicate that autoSIMD is now supported. This call
is behind a check for SSE2 support.
The function isFPRUsedAsVRF and any references to it were removed. It was
added to prepareRegistersForAssignment in error. It is not needed for
AutoSIMD and sometimes caused registers to not be assigned properly. It
was only …

Enable AutoSIMD support on x86

---

compiler/optimizer/Inliner.cpp

In any OSR mode, blocks containing OSR points should have exception
edges to the method's OSRCatchBlock. However, when inlining and
splitting a block in the caller, the callee's final block
and the second half of the split block may be merged, preventing
the addition of an edge to the OSRCatchBlock. This was fixed
under FSD by always splitting the block, however, it should also
be applied to other OSR modes as long as OSR exception edges
are expected to be found.

Split block containing the call under OSR

---

port/unix/omrmmap.c
port/win32/omrmmap.c
port/zos390/omrmmap.c

The code was calculating the unneeded memory in units of pointers, not bytes.
Fixes #1098
Signed-off-by: Peter Bain pdbain@ca.ibm.com

Fix calculation of unneeded memory

---

include_core/omrcomp.h

Get rid of READSVMTHREAD, WRITESVMTHREAD and REQUIRESSTACKFRAME

Remove obsolete function tags

---

CONTRIBUTING.md

Remove the suggestion that commit messages be written in markdown. This 
suggestion can confuse, as GitHub will not render messages as markdown, 
and will produce worse commit messages overall.                         
For example, we don't want people writing `[inline link](foo.example) `  
style.

Remove commit message markdown suggestion

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

This change allows for pre and post OSR to both be enabled
in one compliation. This is necessary for NextGenHCR and
OSRG. This change also cleans up the resolved method symbol's API
to determine if a BCI cannot perform OSR.
This change includes:
- Allow for preExecutionOSR and postExecutionOSR to both be set
- Separate API into cannotAttemptOSRAt and cannotAttemptOSRDuring
- Fix check to verify OSR blocks for all callers exist and
perform unreachable block cleanup
- Don't generate OSR infrastructure if this call site cannot
transition
- Remove unused shouldNotOSR bitvector

Allow for pre and post OSR in one comp

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/UnaryEvaluator.cpp

These commits remove the need for the compiler to generate the decompression sequence trees.

Do not generate decompression sequence under CS

---

omr/OMR_TI.cpp

On some newer HW the current value is too high. This ends up causing
test failures. In the future the code should be investigated to see if
we could remove this value altogether but for now I am just trying to
stabilize testing.
In the future this code should also be investigated to remove the
NO_HISTORY option. This could likely be removed by caching the CPU times
on startup of the library.
Fixes #852

Reduce the minimum CPU interval

---

example/glue/EnvironmentDelegate.cpp
example/glue/EnvironmentDelegate.hpp
gc/base/EnvironmentBase.cpp
gc/base/EnvironmentBase.hpp
gc/base/MemorySubSpaceFlat.cpp
gc/base/MemorySubSpaceGenerational.cpp
gc/base/MemorySubSpaceSemiSpace.cpp
gc/base/standard/ConcurrentCardTableForWC.cpp
gc/base/standard/ConcurrentGC.cpp

There is a lot of duplicated code and makes modifications very
difficult. I am removing all of the APIs except 1 to keep things as
simple as possible.
The GC ExclusiveVMAccess APIs were not properly handling the case where
a system collect was called by a thread that already has
ExclusiveVMAccess outside of the GC. This could easily lead to a dead
lock because of the way the GC handles getting ExclusiveVMAccess. The
change also fixes the potential hang.

Cleanup and fix GC ExclusiveVMAccess APIs

---

gc/base/MemoryPoolLargeObjects.cpp
gc/base/MemoryPoolLargeObjects.hpp
gc/base/standard/ConcurrentSweepScheme.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/ParallelSweepScheme.hpp

- Do not resize LOA if concurrent sweep is active(require complete stw
sweep for LOA resize to avoid potential concurrent sweep issue)
- Move resizeLOA from GlobalGCComlete hook to postCollect
- Remove GlobalGCComlete hook

Avoid heap resize in middle of concurrent sweep

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/AsyncCheckInsertion.cpp
compiler/optimizer/AsyncCheckInsertion.hpp
compiler/optimizer/RedundantAsyncCheckRemoval.cpp

The compiler makes an effort to insert asyncchecks before returns in
methods that might otherwise fail to collect samples. However, some
methods could sometimes still get stuck at a low optimization level.
This change brings asynccheck insertion's heuristic more in line with
the one used in redundant asynccheck removal, by having it detect when
asyncchecks have been versioned out.
Furthermore, both asynccheck insertion and redundant asynccheck removal
are now allowed to run under voluntary OSR, since it's still safe to
insert asyncchecks immediately before returns.
Signed-off-by: Devin Papineau <devinmp@ca.ibm.com>

Insert more asyncchecks for sampling before return

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/ilgen/ByteCodeIteratorWithState.hpp

Under OSR, it will not be possible to transition correctly
if we allocate more pending push slots than the VM expects. To ensure
this never occurs, the JIT will perform a fatal assertion if it
detects a requested slot beyond the limit.

Check the number of pending pushes on a method

---

gc/base/MemoryPoolAddressOrderedListBase.cpp

While calculating the no. of pages to be released from a heap free
entry, it failed to recognize the entries which are lesser than page
size.  Variables used in the calculation is of type uintptr_t, while
subtraction the negative value treated as positive value because of
unsigned.
```
MM_MemoryPoolAddressOrderedListBase::releaseFreeEntryMemoryPages(...)
{
...
uintptr_t totalFreePagesCount = (currentFreeEntry->getSize() - (addressBase - (uintptr_t)currentFreeEntry)) / pageSize;
...
}
```
Issue: #1113
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

Corrects heap-resize tag conflict in idle case

---

gc/base/standard/Scavenger.cpp

When iterating objects in Scavenger backout, in a rare case when RS was
overflown, we would advance by an incorrect size of the object, if
object moved (has grown).
The logic tried to accommodate for this moved object scenario correctly,
but the API it was relying on (getSizeInBytesWithHeader()) changed the
behavior in last ObjectModel restructuring .

Fix Evac iteration in backout/RS-overflow combo

---

compiler/z/codegen/OMRTreeEvaluator.cpp

VMSL instruction is used to improve ECC performance.
Like other vector instructions, this instruction can only be used on machines with proper hardware and OS support for vector instructions.
This PR prevents using VMSL instruction when hardware or OS do not have support for vector instructions.
Signed-off-by: Hadi Jooybar <hjooybar@ca.ibm.com>

Fix support query of vector multiply sum instruction on Z

---

compiler/codegen/CodeGenRA.cpp
compiler/env/OMRIO.hpp
compiler/il/NodeExtension.hpp
compiler/il/OMRNode.cpp
compiler/ilgen/IlBuilder.cpp
compiler/optimizer/GeneralLoopUnroller.cpp
compiler/ras/CallStack.cpp
compiler/ras/Debug.cpp
compiler/x/codegen/X86Ops.hpp

Sundry small improvements to messages, log files, and compiler warnings. Only 2 could be considered functional issues: 1) an assertion testing the size of something assuming it was a 32-bit integer when it was, in fact, a 16-bit integer, and 2) a "unrecognized" method test using -1 when TR::unknownMethod exists and is zero, not -1.

Improve some compiler messages, logs, warnings

---

compiler/compile/OMRCompilation.cpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp

Enable NextGenHCR, HCR implemented with on-stack replacement, by
default. This will result in OSR and HCR being enabled by default,
as this feature requires them.
These defaults are performed after OSR may be disabled in
`OMR::Compilation`, as defaulting before this point could result
in situations that do not require HCR having the older implementation
enabled instead.

Enable NextGenHCR by default

---

compiler/x/amd64/runtime/AMD64AsmUtil.inc
compiler/x/i386/runtime/IA32AsmUtil.inc

1. Created IA32AsmUtil.inc file to hold assembly routines for x86-32 platform.
2. Removed assembly routines _patchingFence24, _patchingFenceCPUID, and atomicIncrement4 on x86 platforms since they are not used anymore.
3. Removed deprecated macros tr_mfence, tr_clflush, tr_clflush16, tr_clflush24, and clearFPStack on x86-32 platform.

Refactor x86 assembly code

---

compiler/ilgen/MethodBuilder.cpp
compiler/ilgen/MethodBuilder.hpp

Contains the following:
- An int overload, `DefineLine(int)`, for `OMR::MethodBuilder::DefineLine`
- Minor changes (in order to accommodate the above) to the `DefineLine(const char *)` method, and the way defining line number is stored inside MethodBuilder object
Signed-off-by: Sajid Ahmed <Syed.Sajid.Ahmed23@ibm.com>

Add int overload for DefineLine

---

compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRRegisterDependency.cpp
compiler/x/codegen/OMRRegisterIterator.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/X86Debug.cpp

Modified initialize inside OMRCodeGenerator.cpp to indicate the first and
last real registers that can hold vector values. This information is used
by GRA to perform GRA.
GRA can lead to the creation of register dependencies so the register
dependency code inside OMRRegisterDependency.cpp was updated to handle
TR_VRF registers. This change also updates several other register related
functions to handle TR_VRF registers. In most cases, this results in
perform actions similar to the TR_FPR case but slightly modified for the
TR_VRF case.
Issue: #1126

Support for GRA for vector registers on x

---

compiler/control/OMROptions.cpp

The option flags are not initialized in the jitPreProcess function. As
such any logic querying an option flag will return its default value set
at initialization. This is an undesired effect. This logic is now moved
to jitPostProcess where we are guaranteed to have initialized option
bits.

Move logic querying getOption from jitPreProcess

---

compiler/z/codegen/UnaryEvaluator.cpp

Previously we used to evaluate the shift left child when
l2a node contains compression sequence under Concurrent
Scavenge mode. As this part of code was refactored, we
do not need to decrement reference count of the shift left
child of the tree as we don't evaluate it in this function.

Do not decrease the ref count of compress sequence of l2aEvaluator

---

compiler/env/ExceptionTable.cpp
compiler/env/TRMemory.hpp
compiler/il/OMRBlock.hpp
compiler/infra/OMRCfg.cpp
compiler/infra/OMRCfg.hpp
compiler/infra/TRCfgNode.hpp
compiler/infra/forward_list.hpp
compiler/optimizer/BackwardBitVectorAnalysis.cpp
compiler/optimizer/BitVectorAnalysis.cpp
compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/Dominators.cpp
compiler/optimizer/Dominators.hpp
compiler/optimizer/DominatorsChk.cpp
compiler/optimizer/DominatorsChk.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/InductionVariable.cpp
compiler/optimizer/InductionVariable.hpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopReducer.cpp
compiler/optimizer/LoopReducer.hpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRValuePropagation.cpp
compiler/optimizer/OrderBlocks.cpp
compiler/optimizer/SinkStores.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp

Restore compiler CPU usage that was regressed when changing the implementation of the container used by CFG nodes to keep track of incoming and outgoing edges.

Fix compiler CPU usage regression

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlBuilder.hpp
compiler/ilgen/IlValue.cpp
compiler/ilgen/IlValue.hpp
compiler/ilgen/MethodBuilder.cpp
compiler/ilgen/MethodBuilder.hpp
compiler/ilgen/VirtualMachineOperandStack.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
fvtest/compilertest/build/files/common.mk
jitbuilder/build/files/common.mk
jitbuilder/build/rules/common.mk

enable Java "float" semantics for X86 code generator if using SSE for floats
Fix for #834 : first stage more efficient IL generation for JitBuilder
Added descriptions for fields of IlBuilder class

Improve JitBuilder's initial IL quality

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

Add an option that should to disable the cleanup of memory allocated for profile information, in case an issue arises with profile data cleanup

Add option disableProfilingDataReclamation

---

port/win32/omrintrospect.c

Code checked GetLastError() against a handle value instead of
an error code value
Fixes #1029

Fix bogus check in port library

---

compiler/optimizer/OSRDefAnalysis.cpp

OSR liveness and reaching definitions analysis 
should not be performed if OSR is not possible 
during this compilation. They will waste compile
time and the expected infrastructure will not
be present.

Disable OSR opts when OSR is not supported

---

compiler/x/codegen/OMRTreeEvaluator.cpp

Disable optimization for constant length array copy by default,
but leave two environment variables to turn it on either fully or
partially.

Turn-off default optimization for constant length array copy

---

.appveyor.yml
CMakeLists.txt

Warn user that CMake support is currently experimental.

Add warning for CMake builds

---

gc/base/standard/Scavenger.cpp

On platforms where Concurrent Scavenger (CS) is compile-time enabled,
but CS not running, during backout, explicitly request inclusion of
forwarded objects when iterating Evacuate space to find
tenured-remembered objects (to un-remember them).

Include f/w-ed obj. when iterating Evac in backout

---

fvtest/porttest/si.cpp
include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsysinfo.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

A new struct, OMROSDesc, added to hold operating system (OS)
features.
omrsysinfo_get_os_description function determines OS features and 
holds this information in the new struct, OMROSDesc.
omrsysinfo_os_has_feature function queries the new struct, OMROSDesc,
to determine if a OS feature is available.
At this point, only one feature has been added -
OMRPORT_ZOS_FEATURE_RMODE64.
OMRPORT_ZOS_FEATURE_RMODE64 - detects whether OS supports RMODE64
feature on zOS. Detection of RMODE64 feature is crucial for 
determining what size of code cache to allocate on zOS.
omrsysinfo_get_os_description function only works for zOS at this 
point i.e. it will return 0. For other operating systems, it will 
return -1. Minimal templates have been added to support other 
operating systems.
Signed-off-by: …

Add API to check OS features

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/z/codegen/OMRSnippet.cpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390HelperCallSnippet.cpp
compiler/z/codegen/S390Instruction.cpp

Because of the nature of executable memory allocation on z/OS, unless
RMODE64 is enabled we can only allocate executable memory below the 2GB
bar. The relative immediate instructions used for linkage dispatch can
address 32-bits worth of half-words in a signed format, meaning we can
branch -4GB to +4GB from the branch instruction. This region exceeds the
2GB limit and hence when RMODE64 is disabled we never need to generate
trampolines on z/OS.
When RMODE64 is enabled however, the executable memory may be allocated
anywhere within the 64-bit virtual address space, and hence we may
exceed the reachable addressability of the linkage branch instructions.
In such cases we always need to generate trampolines which makes the
enableZOSTrampolines synonymous with enableRMODE64.
Signed-off-by: …

Fold enableZOSTrampolines into enableRMODE64

---

gc/base/MemorySubSpaceSemiSpace.cpp

Some compilers enforce return even in the 'unreachable' path.

Fix compile err in MSSS::getActiveMemorySize

---

compiler/z/codegen/ArchInstOpCodeProperties.hpp

“VECTOR LOAD GR FROM VR ELEMENT” (VLGV instruction) loads an element of a vector register in a scalar register.
However, regardless of the element size, the remaining of 64-bit output GR fills with zeros.
This indicates that the instruction clobbers all 64 bits of its output register and has to be marked as a 64bit instruction.
Signed-off-by: Hadi Jooybar <hjooybar@ca.ibm.com>

Fix properties of VLGV instruction on Z architecture

---

.appveyor.yml

Xaramin MSBuild configuration files are corrupted in VS2015.
This results in MSBuild spamming various warning messages.
Solution is to simply delete the files as we don't need xaramin

Cut down on bogus warnings in appveyor build

---

compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRSimplifierHelpers.cpp
compiler/optimizer/OMRSimplifierHelpers.hpp

Having an if node with its branch target the same as its immediate fall
through block results in an illy formed cfg that will confuse other
optimizations. Removing such node is supported in most comparison
simplifiers but is missing in ifacmpne and ifacmpeq, and in generic
simplifiers that handles if nodes such as dftSimplifier. This commit
adds code to try to remove such if node in the simplifier.

Try removing if node in all compare simplifiers

---

GNUmakefile

Updated the GNUmakefile
Changes are:
-Changed operator assignment for HOOK_DEFINITION_SENTINEL and HOOK_DEFINITION_FILE in GNUmakefile from := to =, for expansion of the variable only during usage
Task #1172
Signed-off-by: Jingxian Liu jingxliu0814@gmail.com

Change assignment operator in GNUmakefile

---

gc/base/GCExtensionsBase.hpp
gc/base/MemorySubSpaceSemiSpace.cpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

More robust variant of https://github.com/eclipse/omr/pull/1169
This is supposed to cover (at least) one other even more rare case when
we abort in Concurrent Scavenger with single object allocation. Bottom
line, we will not rely on setting Percolate Reason on various allocation
paths (and possibly miss some) to let Global GC and SemiSpace know that
special treatment is needed for CS abort, but they will query Aborted
Flag directly. 
Aborted flag and its API is moved to GCExtensions. This is not
functional nor mandatory change. The motivation was simply: 1) minimize
#include dependency on Scavenger and 2) it's more consistent with RS
overflow flag/API which is already in the GCExtensions.

Aborted CS single allocate object handling

---

CMakeLists.txt
cmake/CheckSourceTree.cmake

Autoconf generated headers in the source tree cause unexpected errors.
Abort the cmake build if these are detected.

CMAKE: fail if autoconf headers detected

---

compiler/z/codegen/OMRTreeEvaluator.cpp

Force memory reference to use SS format limits right after
they are generated when we get success to reduce store node
to direct memory-memory copy and use MVC instruction to perform
operation. This avoids scenario when index child of source and
target memory reference shares common nodes and we clobber evaluate
that node before it is used.

Fold memory reference to SS format for MVC instr

---

compiler/optimizer/RedundantAsyncCheckRemoval.cpp

in RedundantAsyncCheckRemoval.cpp, that is.
It is found out that 100s of asyncCheck are inserted hurting the performance.

Disable markAncestors

---

port/unix/omrosdump.c

Adjusting the limit on core file sizes before forking ensures the parent and child interpret '%c' in /proc/sys/kernel/core_pattern consistently.
fixes #1195

Unlimit core file size before call to fork()

---

compiler/p/codegen/OMRMachine.cpp

The register enums in p/codegen/RealRegisterEnum.hpp are listed in this
order: GPR, FPR, VRF, CCR. createCondForLiveAndSpilledGPRs in
p/codegen/OMRMachine.cpp tries to iterate over those four types of
registers by setting a loop range to go from FirstGPR to LastCCR. It does
this to generate a register dependency. This logic is correct so there are
no problems so far.
createCondForLiveAndSpilledGPRs then checks to see if there are any live
VRF registers. If so, it changes the end of the loop range to LastVRF.
This is a problem. The range from FirstGPR to LastVRF only covers GPR, FPR
and VRF registers. The existence of a live VRF register causes CCR
registers to be excluded from consideration to be added to the register
dependency.
This fix removes the check for live VRF registers. It is …

Fix for bad register dependency creation on Power

---

compiler/z/codegen/OMRTreeEvaluator.cpp

generateFusedMultiplyAddIfPossible tries to check if it is working on
floating point data before generating fused instructions. The problem is
caused by the fact that a call to isFloatingPoint on a type returns false
for VectorDouble and VectorFloat types. To address this issue, a specific
check for VectorDouble and VectorFloat was added to the function
generateFusedMultiplyAddIfPossible.
Issue: #1160

Fix for unsafe generation of VFMA and VFMS on z

---

port/ztpf/omrosdump.c
port/ztpf/omrosdump_helpers.c
port/ztpf/omrosdump_helpers.h
port/ztpf/omrvmem.c

Description:
This pull represents a learning effort of committing omr changes for the z/TPF platform.   These four files are new copies (based on the other platforms) and reside in the new port/ztpf folder and will not affect any other platforms.  A successful personal build was done in the IBM environment (build_id=348248), as would be expected because only the z/TPF platform has the capability of building its unique environment.
The files were randomly chosen and deal with dump processing and virtual memory.  A larger pull request is in the works for a later date.

First zTPF Pull to OMR

---

jitbuilder/runtime/JBCodeCacheManager.hpp

- Fatal assertion to enforce singleton property in JitBuilder::CodeCacheManager
- Fatal assertion to ensure that JitBuilder::CodeCacheManager::instance() never returns a null pointer
Signed-off-by: Sajid Ahmed <Syed.Sajid.Ahmed23@ibm.com>

Enforce singleton property in JitBuilder::CodeCacheManager

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/LocalOpts.cpp
compiler/x/amd64/codegen/AMD64SystemLinkage.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/X86SystemLinkage.cpp
compiler/x/i386/codegen/IA32SystemLinkage.cpp
jitbuilder/control/Jit.cpp
jitbuilder/optimizer/JBOptimizer.cpp

A sequence of small performance improvements for JitBuilder, mostly focused on prolog/epilog corner cases for small methods, but there is also a change to the JitBuilder optimization strategy now that the initial IL quality has been improved via #1110.

JitBuilder small performance improvements

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/env/OMRObjectModel.hpp
compiler/optimizer/VPHandlers.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

Instead, expose a query on the Object Model class querying whether we
need read barriers for field loads. The compiler shouldn't technically
be querying the codegen to ask if concurrent scavenge is enabled, that
should be something that the Object Model should answer.
Issue: #1185
Signed-off-by: Alexey Zhikhartsev <alexey.zhikhartsev@ibm.com>

Deprecate isConcurrentScavengeEnabled codegen query

---

compiler/ilgen/IlBuilder.cpp

IlBuilder::genCall() was only generating call nodes under their
own treetop if the call node did not return a value. Unfortunately,
the way IlValue works, it could cause the call node to swing down
to places it should never go. Resolve that by anchoring the call
node under its own treetop explicitly in genCall().

Ensure JitBuilder creates calls under treetops

---

compiler/compile/OMRCompilation.cpp

Under NextGenHCR, the OSR transition occurs after
the yield point. In sync methods, transitions
can occur at the monent in the method entry. However,
as this monent does not exist, transitioning with
an offset will result in the first bytecode being
skipped.

Zero offset OSR induction for sync method monent

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

Under NextGenHCR, the OSR transition occurs after
the yield point. In sync methods, transitions
can occur at the monent in the method entry. However,
as this monent does not exist, transitioning with
an offset will result in the first bytecode being
skipped.

Stash call arguments against BCI for OSR induce

---

compiler/optimizer/Inliner.cpp

An OSR point may have related trees, such as
pending push stores, immediately after it.
It is not acceptable to insert other trees in
this region. As block splitter may try to
uncommon, it must skip the entire OSR region
when creating the store.

Skip OSR related trees when splitting block

---

compiler/z/codegen/ArchInstOpCodeProperties.hpp

“VECTOR LOAD VR ELEMENT FROM GR” (VLVG instruction) stores a general register in a vector register.
For double-word element size (mask = 3) this instruction uses all 64 bits of its source register. Therefore, it has to be marked as a 64bit instruction.
The same logic applies to VLVGP instruction as well.
Signed-off-by: Hadi Jooybar <hjooybar@ca.ibm.com>

Fix properties of VLVG instruction (z Systems)

---

compiler/arm/codegen/ARMBinaryEncoding.cpp
compiler/arm/codegen/ARMSystemLinkage.cpp
compiler/arm/codegen/BinaryEvaluator.cpp
compiler/arm/codegen/Instruction.hpp
compiler/arm/codegen/OMRCodeGenerator.cpp
compiler/arm/codegen/OMRCodeGenerator.hpp
compiler/arm/codegen/OMRTreeEvaluator.cpp
compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/ilgen/IlBuilder.cpp
fvtest/jitbuildertest/Makefile
fvtest/jitbuildertest/SystemLinkageTest.cpp
jitbuilder/release/Makefile

This series of commits improve/fix the ARM code generator in the OMR compiler. The main goal of this change is to complete the system linkage implementation. System linkage is the part of the code generator responsible for generating the instruction sequences at function call boundaries to satisfy the platform ABI.
These commits can be roughly grouped into 3 sections:
1. The first 6 commits do some necessary clean up to enable the other commits.
2. The next 4 commits constitute the main changes. These generalize parts of the ARM binary encoding and add missing functionality to the system linkage implementation.
3. The last 2 commits add a test case for the ARM system linkage and some trace in the code generator that was useful when debugging the previous changes. The test case is intended …

ARM system linkage improvements

---

gc/base/GCExtensionsBase.hpp
gc/base/MemorySubSpace.cpp

Modifies code to perform global GC with assured compaction if systemGarbageCollect is called with GC code "EXPLICIT_GC_IDLE_GC" and compactOnIdle is set to true.  If gcOnIdle is set along with
compactOnIdle then "releases free heap pages" too.  
For example, if the runtime wants to use the idle CPU cycles to clean up the managed heap and make heap ready for the next active period. In such cases, the runtime wants to execute "systemGarbageCollect" with "J9MMCONSTANT_EXPLICIT_GC_IDLE_GC" and invoke compaction only. 
This PR modifies the code to separate out gcOnIdle and compactOnIdle as two independent actions and can be set & invoked separately.
Issue: #1213 
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

Separate out compactonidle from gconidle

---

gc/base/omrmmprivate.hdf
include_core/omrhookable.h
tools/hookgen/HookGen.cpp
tools/hookgen/HookGen.hpp
util/hookable/hookable.cpp

Disable/Sampling Hook trace for frequent events
- disable/sampling hook tracepoint and hook dump via new tag <trace-sampling intervals="N" /> in hdf for high-frequency events to reduce performance impacts of tracking hooks
- new invocation count in hook dump structure to trace event frequency
- atomic operation for updating hook dump information to keep data
consistent in race condition

 Disable/Sampling Hook trace for frequent events

---

gc/base/omrmmprivate.hdf
include_core/omrhookable.h
tools/hookgen/HookGen.cpp
tools/hookgen/HookGen.hpp
util/hookable/hookable.cpp

This reverts commit 463227e01189b482e5fc3763103041ff1e0246e1 to avoid z390 and ppc crush.

Revert "Disable/Sampling Hook trace for frequent events"

---

fvtest/porttest/si.cpp
include_core/omrport.h
port/common/omrport.c
port/common/omrsysinfo.c
port/linuxppc64/omrtime.c
port/omrportpriv.h
port/unix/omrsysinfo.c
port/win32/omrsysinfo.c

omrsysinfo_os_kernel_info has been added to the port library in
order to retrieve kernel information. Only Linux kernel is supported at
this point; Linux kernel version is retrieved.

Add public API to get OS kernel info

---

compiler/optimizer/LoopVersioner.cpp

Insure that all loop versioning tests that use duplicated nodes from inside the loop do so safely by making sure that the duplicated nodes' flags are cleared, since the flags may no longer be accurate outside the loop.
This is a follow up fix to 72f1d48904936cc352e52516e81ea7bb5353a8e5, which addressed one guard test that was known to be the cause of a downstream bug. This patch addresses all the remaining guard tests, including another test (that checks the induction variable against the loop lower bound) that is causing another bug for downstream.
The tests modified by this patch were identified by looking for
* nodes being duplicated via `duplicateTree()` and
* being consumed directly or indirectly by `if*cmp*` nodes that are
* inserted prior to the loop, and guarded with a …

Safely dup trees for loop versioning tests

---

compiler/x/codegen/OMRTreeEvaluator.cpp

Recent changes to the register dependencies for `arraytranslate` on x86 rely on the new helpers. These changes are reverted in order to allow the previous helpers to run again. However, the addition of `xmm3` is retained because it is a necessary fix.

Revert x86 arraytranslate register dependencies

---

gc/verbose/VerboseHandlerOutput.cpp

Previously, heap-resize operation is subtask of gc-cycle. So, it was
not required to flush verbose GC buffer immediately. But, as part of
the EXPLICIT_GC_IDLE_GC, heap-resize type="release free pages" may be
executed outside the gc-cycle. For those cases, the immediate buffer
flush required for the tag appear in the verbose output.
Issue: #1233 
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

Flush verbose GC every-time heap-resize executed

---

gc/base/MarkingScheme.cpp
gc/base/MarkingScheme.hpp
gc/base/standard/Scavenger.cpp

Concurrent Scavenger. Abort scenario. 
Fixup of Nursery references used to be done by walking Nursery during
abort handling within Scavenger. It was not safe in general case - for
example if Aborted Scvenger was preceded by sweep. 
Now Nursery fixup is done during marking within Percolate Global GC 
Nursery is made walkable after the sweep (for now in Language specific
code), iterating via Marked Object Iterator.
Fixup of the roots still done inside Scavenger abort handling.

Aborted CS heap fixup in percolate global

---

gc/base/omrmmprivate.hdf
include_core/omrhookable.h
tools/hookgen/HookGen.cpp
tools/hookgen/HookGen.hpp
util/hookable/hookable.cpp

- disable/sampling hook tracepoint and hook dump via new tag
<trace-sampling intervals="N" /> in hdf for high-frequency events to
reduce performance impacts of tracking hooks
- new invocation count in hook dump structure to trace event frequency

Disable/Sampling Hook trace for frequent events

---

compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopCanonicalizer.hpp

FieldPrivatizer does not privatize fields that have any aliases.
Improve this by checking if any of the field's aliases are actually used inside the loop:
- collect all symbol references used in the loop in _allSymRefs
- AND getUseDefAliases with _allSymRefs when checking if field can be privatized
Signed-off-by: Gita Koblents <koblents@ca.ibm.com>

Improve alias info in FieldPrivatizer

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator_inlines.hpp

Fix an "undefined symbol" runtime error on zLinux
The template method `loadAndStoreMayOverlap` in `OMR::Z::CodeGenerator`
was implemented in the implementation file rather than the header file,
and, hence, was violating the C++ standard. GCC 4.8.5 is inlining the
template straight into the overload candidate and not emitting the
template instantiation. The result was an "undefined symbol" error
during runtime on zLinux.
Issue: #1183
Signed-off-by: Alexey Zhikhartsev <alexey.zhikhartsev@ibm.com>

 Fix an "undefined symbol" runtime error on zLinux

---

gc/base/CollectorLanguageInterface.hpp
gc/base/standard/Scavenger.cpp

When fixing up references in root/RS scanning in Aborted Concurrent
Scavenger, also handle indirect references (references to Nursery from
off heap structures associated with the object). Language specific code
will actually do the fixup (for example, in Java it will fixup class
structure)

Aborted CS: Handle indirect refs

---

.gitignore

omr.rc is a generated file introduced by commit 8ce8861 / a40dfc7.  Add
it to .gitignore to stop it from showing up in untracked changes.

Ignore generated file omr.rc

---

compiler/x/amd64/codegen/AMD64SystemLinkage.hpp
compiler/x/codegen/X86SystemLinkage.cpp
compiler/x/codegen/X86SystemLinkage.hpp
compiler/x/i386/codegen/IA32SystemLinkage.hpp

This change introduces the helper function `getSingleWordFrameAllocationRegister()` that returns an appropriate register for allocating/deallocating the stack on a given platform. Now, instead of pushing/popping rbx on x86, r11 is used on x86-64 and ecx is used on x86-32.
Fixes #1243
Signed-off-by: Leonardo Banderali <leob@linux.vnet.ibm.com>

Fix usage of rbx to allocate a stack frame

---

compiler/env/OMRCompilerEnv.hpp
compiler/env/OMRVMMethodEnv.hpp
compiler/env/VMMethodEnv.hpp
compiler/runtime/OMRCodeCache.cpp

Begin to eliminate `OMR::CodeCacheManager` dependence on deprecated FrontEnd functionality by either eliminating it outright or refactoring the FrontEnd functionality into it's own class.

Begin to remove FrontEnd dependence on CCM

---

compiler/optimizer/ValuePropagationCommon.cpp

The OSR transition failed because of an asyncchk inserted
by arraytranslate. The asyncchk is only needed if asyncchk
removal might have removed an original asynchk in the containing
loop. Asyncchk removal is disabled if we are in either one of 
involuntaryOSR or nextGenHCR modes, and therefore the inserted
asyncchk should be avoided under these 2 modes.

Avoid insert asyncchk in arraytranslate opt

---

compiler/optimizer/Inliner.cpp
compiler/optimizer/LoopReducer.cpp
compiler/optimizer/OMROptimizationManager.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp

Initialize optimization manager enabled field based on its related
options flag and start using the manager field to query from then on.

Fix optimization manager enabled field

---

compiler/cs2/timer.h

Otherwise you're returning a pointer to a string constant which may
abort at runtime should you write to it.

Add const to const-returning function

---

compiler/env/jittypes.h
compiler/optimizer/RegisterCandidate.cpp
compiler/p/runtime/PPCCodeSync.inc

Changes to enable building with recent versions of XLC on PPCLE Linux.

Allow building with recent XLC versions

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

To simplify analysis, optimizations may ask if
there are any OSR points that cannot transition.
This adds a helper to determine if OSR is always
safe, excluding checks to the OSR infrastructure.

Add helper method to check all points can OSR

---

gc/structs/ForwardedHeader.cpp
gc/structs/ForwardedHeader.hpp

Expose getNonStrictForwardedObject() for usage even outside of
Concurrent Scavenger code. This is to simplify call sites to avoid using
(for code clarity) ifdef to distinguish between plain
getForwardedObject() and getNonStrictForwardedObject().
getNonStrictForwardedObject() behaves identically as
getForwardedObject() in non CS world.

Expose non-strict API

---

compiler/env/OMRCompilerEnv.hpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/RedundantAsyncCheckRemoval.cpp
compiler/runtime/OMRCodeCache.cpp

* Start using the VMMethodEnv equivalents
* Rename the `CompilerEnv` field `mth` to the more appropriate
abbreviation `mtd`

Replace FE functions with VMMethodEnv equivalents

---

compiler/compile/OMRCompilation.cpp

When searching for virtual guards, the actual guard
should be used, rather than one with a matching
BCI.

Find the actual virtual guard for OSR guards

---

compiler/optimizer/LocalOpts.cpp

Changes were made to redundantGotoElim to allow it
to perform under NextGenHCR without placing an
asynccheck where it may invalidate an assumption
without being protected by an OSR guard.
Incorrect changes were made when adding the possibility
of both pre and post execution in one compile.
Moreover, the modification to the optimization is
specific to how assumptions are made, not the OSR
mode.

Fix redundantGotoElim asynccheck insert for OSR

---

CONTRIBUTING.md

Some contributors have run into issues where a seemingly correct signoff
line gets rejected. It has since been discovered that the
'ip-validation' check is case sensitive on the email address.
This calls that behaviour out in CONTRIBUTING.md to try to minimize the
pain.
[ci skip] as documentation only change.

Point out case sensitivity in IP Validation

---

gc/base/NonVirtualMemory.cpp
gc/base/NonVirtualMemory.hpp
include_core/omrcomp.h
include_core/omrport.h
port/common/omrmem32helpers.c
port/unix/omrfile.c
port/unix/omrfiletext.c
port/unix/omrmem.c
port/unix/omrsl.c
port/unix_include/omriconvhelpers.h
port/ztpf/omrgetstfle.s
port/ztpf/omrintrospect.c
port/ztpf/omrloadfpc.s
port/ztpf/omrmmap.c
port/ztpf/omrosbacktrace_impl.c
port/ztpf/omrrttime.s
port/ztpf/omrsignal.c
port/ztpf/omrsignal.h
port/ztpf/omrsignal_context.c
port/ztpf/omrsignal_context.h
thread/unix/thrdsup.c
util/omrutil/unix/linux/s390/archinfo.c

Description:
This pull request is the second in a series of committing omr changes
for the z/TPF platform. This pull request is a follow-on to PR #1147.
A successful personal build was done in the IBM environment
(build_id=351866), there were two or three compilation failures that
were fixed.  Unlike PR #1147 there are a small amount of platform
common files which were updated.
It's expected there will be two more pull requests after this one of
smaller sizes then followed by pull requests for specific fixes as part
of z/TPF builds and runtime fixes.
The current z/TPF build procedures are still a work-in-progress.
Most of the formatting was pre-existing.  Some of the files maybe
removed once our build is finalized.  So no need to overly analyze this
pull requests as we still have passes …

zTPF_OMR_Port_Pull2

---

compiler/il/OMRNode_inlines.hpp

Update the assertions for getFirstChild(), getSecondChild() and
getThirdChild() for a Node to make them more consistent and complete.
Signed-Off-By: Dhruv Chopra <dhruv.c.chopra@ibm.com>

Update assertions for getChildren functions

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/OMRSimplifier.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/ValuePropagationCommon.cpp

OSRInduceBlocks will be filled with dead stores
and remat trees, resulting in a significant
compile time overhead if not ignored.
This change:
- Adds a flag to identify OSRInduceBlocks
- Check the flag in several opts
- Remove the prior expensive version of the check

Add OSRInduceBlock flag and skip opts

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

With the addition of argument stashing for OSR
infrastructure, pre and post OSR points no longer
require a distinction between their dead stores.

Remove liveness diff between post and pre OSR

---

gc/base/EnvironmentBase.hpp
gc/base/MarkingScheme.hpp
gc/base/standard/Scavenger.cpp

During Concurrent Mark (CM) and overlapping Aborted Concurrent Scavenger
(CS) it is ok to encounter a self-forwarded object, but we must not fix
it up at that point, yet. We have to complete CS Cycle first (during
which self-forwarded pointers serve important role of preventing
duplicate objects). Only during the final (STW) phase of CM the fixup
work will be done, while scanning Nursery.

Aborted CS overlapping with CM

---

CONTRIBUTING.md

This drops the project description (which belongs, and exists in,
README.md), tries to make the invite to contribution more friendly
and documents the existing practice with pull-requests and issues.

Enhance CONTRIBUTING.md 

---

compiler/compile/OMRCompilation.cpp

NextGenHCR currently forces HCR by default. However,
support for HCR should be requested, defaulting to the
NextGenHCR implementation instead.

Do not enable HCR by default

---

compiler/arm/runtime/VirtualGuardRuntime.cpp
compiler/env/FEBase.cpp
compiler/p/runtime/VirtualGuardRuntime.spp
compiler/runtime/OMRRuntimeAssumptions.cpp
compiler/runtime/OMRRuntimeAssumptions.hpp
compiler/x/runtime/VirtualGuardRuntime.cpp
compiler/z/runtime/VirtualGuardRuntime.cpp

PatchNOPedGuardSite is a location redirection runtime assumption. It can
patch at a particular location to unconditionally jump to a destination. Provided 
interface and implementation for patching virtual guards in OMR.

Create PatchNOPedGuardSite class in OMR

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

To reduce the compile time overhead of OSR, it is possible
to calculate which slots are being used at an OSR
point based on the set of live symrefs during
OSRLiveRangeAnalysis, rather than having to perform both
it and OSRDefAnalysis.

Calculate OSRDef during OSRLiveRangeAnalysis

---

gc/base/MemorySubSpaceSemiSpace.cpp

Aborted Concurrent Scavenger handling: In really tight condition,
Nursery can be completely full even after percolate global GC (and
compact within). Check the last free entry pointer (set by compact) is
non-null before fetching the free entry size.

Nursery 0 free after percolate compact

---

tools/tracegen/TraceHeaderWriter.cpp

Also fix leaked memory where we fail to free two strings.
Fixes #1215

Fix invalid free's of non-heap objects

---

compiler/optimizer/VPHandlers.cpp

Without this, global VP (value propagation) would look for a fallthrough edge from a block ending with `tstart` to the textually following block, which may not be a branch target of the `tstart` node. Failure to find the edge results in dereferencing a past-the-end iterator.

Tell VP that tstart has no fallthrough

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/TreeEvaluatorTable.hpp

- add vl2vdEvaluator that uses VCDG instruction
- enable vl2vd opcode in OMR::Z::CodeGenerator::getSupportsOpCodeForAutoSIMD
Signed-off-by: Gita Koblents <koblents@ca.ibm.com>

Support long/double auto-SIMD operations on Z

---

compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRTreeEvaluator.cpp
compiler/p/codegen/OMRTreeEvaluator.hpp
compiler/p/codegen/TreeEvaluatorTable.hpp
fvtest/compilertest/tests/PPCOpCodesTest.cpp

This is change adds the evaluator and codegen query on Power. The ibyteswap unit test is also enabled on Power as well.
This is a follow-up to #936

Adding Ibyteswap evaluator on Power

---

compiler/optimizer/Inliner.cpp

Under OSR, its necessary to ensure the last block
of the callee and the caller's block immediately
after must be separated for distinct OSR exception
edges. However, this splitting was not taking into
account whether the return value was commoned across.
This was working in the past because the callee
always had an OSR catch block, resulting in
the inliner generating a temporary for the result.

Check return temp exists splitting in inlining

---

compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMRLocalCSE.hpp

C++ standard library containers will frequently create ephemeral
instances of type coercions of the the containers allocator type,
expecting any allocator instantiation within the same container instance
to be equivalent for allocations and deallocations, with one instance
being able to deallocate memory provided by another instance. Implied by
this requirement is that memory allocations must be able to outlive the
allocator instances from which they were allocated.
Given the above, when using TR::Regions and TR::typed_allocator as the
allocator for C++ containers, one needs to ensure that the instances of
typed_allocator use references to an externally defined Region. A Region
whose lifetime is under explicit control of its user.
This change corrects region use in LocalCSE's uses of …

typed_allocator should take references to Regions

---

gc/base/Dispatcher.cpp
gc/base/Dispatcher.hpp
gc/base/GCExtensionsBase.hpp
gc/base/ParallelDispatcher.cpp
gc/base/ParallelDispatcher.hpp
gc/base/standard/Scavenger.cpp

Concurrent phase of Concurrent Scavenger has its own (background) thread
count. Typically reduced, relative to STW operation. A reasonable
default is 1/2 of STW thread count. However, the default and an option
to override it, will be in language dependent part.

CS background thread count

---

CONTRIBUTING.md

We've been using the WIP workflow for a while, but the way that
CONTRIBUTING.md was written, it seemingly explicitly discourages that
workflow.

Call out the WIP workflow in CONTRIBUTING.md

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

Improve insertPad API to return the cursor position of the last inserted
padding instruction. We take this opportunity to fully document the API
as well.

Improve insertPad to return the cursor position

---

compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390GenerateInstructions.hpp

Add two new APIs:
- generateS390BranchInstruction overload targeting RR instructions
- generateDataConstantInstruction
The former is an overload to generate RR instruction formats such as
BCR, and the latter is a new API to generate data constant
pseudo-instructions in the instruction stream.

Add two new generateInstruction APIs

---

gc/base/GCExtensionsBase.hpp
gc/base/MarkingScheme.cpp
gc/base/MarkingScheme.hpp
gc/base/MemorySubSpaceSemiSpace.cpp
gc/base/MemorySubSpaceSemiSpace.hpp

In Concurrent Scavenger, in calculation for Survivor size, account of
bytes allocated by mutator during the concurrent cycle.
Also re-enabling paying alloc taxes for SemiSpace. This is just a
forgotten todo - it was disabled in the early CS development to avoid
interaction with Concurrent Marking.

Dynamic Nursery tilting in CS

---

compiler/codegen/OMRCodeGenPhase.cpp

OSR slot sharing information is intended to be
compressed after the map from instruction to slot
information has been generated. However, it is
being compressed before the slot sharing information
for snippets has been added. This can result in
a transition failing if a snippet's instruction PC
is within a range of compressed PCs and has different
slot sharing information.

Compress OSR infra after all OSR points are added

---

compiler/optimizer/LocalOpts.cpp
compiler/optimizer/VirtualGuardCoalescer.cpp

OSRCode and OSRInduce blocks should not be
candidates for BlockSplitter, as they are
specialized blocks for OSR transitions.

Ignore OSR blocks in optimizations

---

gc/base/GCExtensionsBase.hpp

moving definition of loaFreeHistorySize from under OMR_GC_MODRON_SCAVENGER to under OMR_GC_LARGE_OBJECT_AREA
Issue:#1313
Signed-off-by: LinaSerry <linaserry@cmail.carleton.ca>

Fix loaFreeHistorySize isn't guarded completely

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

To reduce OSR overhead, the dead stores for an entire call
site can be placed in its OSR code block, rather than
every OSR induce block. This is done during IlGen for the
callee, as OSR live range analysis would have already been
performed for the caller.

Add dead stores to OSR code block

---

fvtest/compilertriltest/.gitignore
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/OpCodeTest.cpp
fvtest/compilertriltest/OpCodeTest.hpp
fvtest/compilertriltest/TreeVerifierTest.cpp
fvtest/compilertriltest/main.cpp

These changes add some compiler tests that use Tril to generate input IL. These include Tree Verifier tests and some initial opcode tests. The opcode tests are intended to show how tests that could eventually replace the existing opcode tests (in the test compiler) can be written.
It should be noted that some of the Tree Verifier tests currently fail because the Tree verifier has historically been poorly maintained and is not behaving as expected.
[ci skip] because Tril is not part of continuous integration

Add some compiler tests using Tril

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/Inliner.cpp

OSR is used for certain guarded callees. In the past
a specialized function was used to generate and insert
the trees for these. With simplification of OSR
infrastructure, this difference is no longer necessary
and the common function can be used.

Remove special OSR Induce API for guards

---

compiler/arm/codegen/ControlFlowEvaluator.cpp
compiler/codegen/OMRAheadOfTimeCompile.cpp
compiler/compile/OMRCompilation.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/compile/VirtualGuard.cpp
compiler/compile/VirtualGuard.hpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/Inliner.hpp
compiler/optimizer/LoopVersioner.cpp
compiler/ras/Debug.cpp

This changeset is part of the code to add breakpoint guards to support
inlining in FSD mode.The breakpoint guard reads a bit from
a field of the callee method which is set when any breakpoints
are set for that particular method.
This changeset create the actual breakpoint guard and add it to each
callee under FSD mode.

Add breakpoint guard to support inlining in FSD

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

This codegen query is not used in OMR.  It will be moved to
its downstream project.

Remove enableAESInHardwareTransformations()

---

tools/tracegen/TDFParser.cpp
tools/tracegen/TraceHeaderWriter.cpp

Tracepoints/TraceAssert normally have a default parameter which is
the current thread.  There is an option NoEnv to remove the default
current thread parameter.  The template for generating the TraceAssert
was not taking the envParam into consideration.  This means that
TraceAsserts which did not use NoEnv were generating incorrect data.
The fix is to take it into consideration and generate the correct code
for these asserts.
Header file creation now throws an error if the Trace point is not
properly formatted rather than being generated and then later causing
a compilation error.
Signed-off-by: LinaSerry <linaserry@cmail.carleton.ca>

Tracegen tool fixes

---

compiler/il/ILProps.hpp

Add suffix ULL to constants in omr/compiler/il/ILProps.hpp to fix compiler warnings "integer constant is too large for 'long' type".

Add ULL to constants 

---

tools/tracegen/TDFParser.cpp

casting strlen in forloop to be an int to fix
possible loss of data error on windows plateform
Signed-off-by: LinaSerry <linaserry@cmail.carleton.ca>

Fix casting error on windows

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

In original lmmd code, when propagating monitor state from one block
to its sucessors the blocks that are already visited are skipped
and it's assumed that the monitor state for one block should be the
same no matter which predecessor it's propagated from.
This code detect the cases where the monitor state for one block can vary
when propagating from different predecessor blocks. In those cases,
lmmd should resort to the most conservative solution.

Fix live monitor meta data to detect invalid cases

---

CONTRIBUTING.md
scripts/commit-msg

1. Add a commit message script that can be installed in a local repository
under .git/hooks to validate commit messages against OMR contributing
guidelines.
2. Add installation instructions for the script in the guidelines.
[ci skip] git hook script only

Add a git commit message hook script

---

tools/compiler/scripts/masm2gas.pl

When LLVM assmbler support was added, an incorrect clause was added
on a path that wasn't being exercised.
This removes the new clause (which is superflous for LLVM anyhow, as
when $llvmVersion is > 0, $gasVersion is set to 3), restoring the old
behaviour.

Fix bug in masm2gas

---

compiler/codegen/GCStackMap.hpp
compiler/compile/VirtualGuard.cpp
compiler/compile/VirtualGuard.hpp
compiler/env/ExceptionTable.cpp
compiler/env/TRMemory.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/infra/BitVector.cpp
compiler/infra/BitVector.hpp
compiler/infra/List.hpp
compiler/optimizer/SinkStores.cpp
compiler/optimizer/SinkStores.hpp
compiler/optimizer/StripMiner.cpp

The current implementations of TR_BitVector and TR_List allocate memory
using trMemory(). This is problematic for growable data structures using
stack memory since new stack marks may cause the lifetime of internal
data structures to be inconsistent. In addition, the lack of a
TR::Region based API prohibits modelling memory lifetimes which do not
follow the existing stack mark or heap.
This change modifies the data structures to store a region to do their
memory management and to always use the same region for their
allocation. The trMemory based APIs derrive the appropriate default
region to minimize impact on the code.
To facilitate allocation from region overrides of the pacement new and
delete operators taking TR:Region are supplied to mirror those for
trMemory and friends. …

[Mem1] Allocate using regions in TR_List and TR_BitVector

---

compiler/control/CompileMethod.cpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/env/FEBase.cpp
compiler/env/SystemSegmentProvider.cpp
compiler/env/SystemSegmentProvider.hpp
compiler/ras/LimitFile.cpp
fvtest/compilertest/tests/OptionSetTest.cpp

Standardize the format of verbose log messages indicating that a
compilation was successful. For the compileEnd verbose option, provide
a log entry in the format "([hotness]) [method name] @ [start address]-
[end address]". For the compilePerformance verbose option, extend the
prior format to also include " time=[time elapsed compiling] mem=[memory
allocated for scratch usage in KiB]"

Harmonize OMR JIT verbose logs

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp
compiler/optimizer/Inliner.cpp

OSR induce calls are added during inlining for
OSROnGuardFailure. The OSR Induce API currently
assumes that the outermost CFG should be used
when manipulating blocks to add an induce call.
This is not valid when inlining a call whose
caller is not the outermost method. To correct
this, the API has been extended with an optional
CFG argument that defaults to the outermost.

Extend OSR Induce API to accept optional CFG

---

compiler/optimizer/InductionVariable.cpp

In analyzeExitEdges() we need to ensure we are only considering blocks
for the target loop and not any inner loops

Fix a crash in analyzeExitEdges()

---

compiler/il/OMRNode.hpp
compiler/infra/TRlist.hpp
compiler/infra/deque.hpp
compiler/infra/vector.hpp
compiler/optimizer/BackwardBitVectorAnalysis.cpp
compiler/optimizer/BitVectorAnalysis.cpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/Dominators.cpp
compiler/optimizer/Dominators.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

Currently a Dominators analysis has a number of data structures scoped
to the lifetime of the analysis. These structures are currently CS2
containers allocated using the CS2 allocator. This change refactors
Dominators to have an embedded region and switches the data structures
to all allocate from that region. The TableOf in the current
implementation was especially bad at leaking memory.

[Mem5] Clean Dominators memory management

---

compiler/il/OMRNode.hpp
compiler/infra/TRlist.hpp
compiler/infra/deque.hpp
compiler/infra/vector.hpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

Currently the UseDef analysis has an auxiliary structure used to hold
data only live during usedef analysis. This structure, while allocated o
the stack, is making heavy use of the CS2 allocator. Much of the heap
memory used is not reclaimed and is leading to large footprint
overheads.
These changes refactor the AuxiliaryData structure and UseDefInfo
itself to allocate from their own regions using non-CS2 data strucutres
to facilitate freeing memory efficiently.

[Mem2] UseDef memory allocation cleanup

---

compiler/il/OMRNode.hpp
compiler/infra/TRlist.hpp
compiler/infra/deque.hpp
compiler/infra/vector.hpp
compiler/optimizer/BackwardBitVectorAnalysis.cpp
compiler/optimizer/BitVectorAnalysis.cpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

The DataFlow engine was designed to operate with stack memory and the
associated stack marks and releases. The BitVectors were previously
changed to use CS2 dense BitVectors allocated out of a CS2::TableOf
pool. The pool is leaking large amounts of memory and the CS2 dense
BitVectors are not compatible with region allocation. This change swaps
the BitVectors back to region allocated TR_BitVectors and removes the
CS2::TableOf pool for significant memory savings.

[Mem3] Remove CS2 BitVectors from DataFlow

---

compiler/il/OMRNode.hpp
compiler/infra/TRlist.hpp
compiler/infra/deque.hpp
compiler/infra/vector.hpp
compiler/optimizer/BackwardBitVectorAnalysis.cpp
compiler/optimizer/BitVectorAnalysis.cpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

The RegisterCandidates data structure has several CS2::TableOf data structures which are leaking a  lot of memory. This change removes the TableOf structures, introduces a memory allocation region, allocates the candidates from the region, and efficiently cleans up candidates when freed. The top two commits are in this pull request - Mem1 - Mem3 are the base.

[Mem4] Clean RegisterCandidates memory management

---

cmake/platform.cmake
fvtest/omrGtestGlue/CMakeLists.txt

We were previously consuming pthread in an ad-hoc way.
This now propagates -pthread through anything linking against
j9thrstatic (that's nearly everything).
`-pthread` has the same effect as `-lpthread` and `-D_REENTRANT`. Now,
we don't need to define `_REENTRANT` ourselves.

Link and compile with -pthread

---

compiler/z/codegen/ConstantDataSnippet.hpp
compiler/z/codegen/OMRCodeGenerator.hpp

On z Systems, constant data snippet size was limited to
16 bytes. This commit increases that to 64 bytes.

Increase the limit of constant data snippet

---

compiler/optimizer/OMRValuePropagation.cpp
compiler/optimizer/ValuePropagationCommon.cpp
compiler/z/codegen/OMRMachine.cpp

The colon character cannot be used as part of a name in an export due to
its special treatment to separate exported directories. We must revert
back to using underscores.
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

Remove the use of colons in feGetEnv

---

compiler/il/OMRNode.hpp
compiler/infra/TRlist.hpp
compiler/infra/deque.hpp
compiler/infra/vector.hpp
compiler/optimizer/BackwardBitVectorAnalysis.cpp
compiler/optimizer/BitVectorAnalysis.cpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/Dominators.cpp
compiler/optimizer/Dominators.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/LocalDeadStoreElimination.cpp
compiler/optimizer/LocalDeadStoreElimination.hpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

Currently LocalDSE allocates a CS2::TableOf that is never used. Thiscommit removes that table entirely and switches other data structures to be allocated in the stack scope of the optimization so that they are properly cleaned up.

[Mem6] Clean memory management in LocalDSE

---

compiler/optimizer/StructuralAnalysis.cpp
compiler/optimizer/StructuralAnalysis.hpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp
compiler/ras/Tree.cpp

Use dense BitVectors, rather than sparse, to
implement region analysis. This reduces the
compile overhead, as allocations for the sparse
BitVectors are costly.

Use dense BitVectors in region analysis

---

port/common/j9nls.c
port/common/omrerror.c
port/common/omrfile.c
port/common/omrfilestreamtext.c
port/common/omrstr.c
port/include/omrportptb.h
port/unix/omrfile.c
port/unix_include/omrportptb.h
port/win32/omrfile.c
port/win32_include/omrportptb.h

Port library method str_vprintf() requires a uintptr_t value for buffer
length and returns uintptr_t, return value was being assigned to
uint32_t value that is later assigned to a uint32_t-valued
field. 
Buffer length arg for str_vprintf() is not used when buffer pointer is
NULL. Replaced value for buffer length arg with 0 (was (unit32_t)-1).
Method will now reuse existing buffer if reallocation fails or
allocation size is >= 2^32. Error message will be truncated and null
terminated if too long to fit in current buffer.
Additional related fixes to use uintptr_t consistently for buffer sizes
and to fix inconsistent use of str_vprintf() args and return value.
Unexpected problem found in Port.cpp. OSX needs sys/statfs.h. I don't
know how it ever got into master without including it. …

Fix integer cast in omrerror.c

---

fvtest/porttest/omrstrTest.cpp

Test for `str_ftime()` fails when run in Singapore time zone.
The test expects all time zone offsets to UTC at Unix timestamp `0` to
be full hours. In Singapore at Unix timestamp `0` the offset was 7
hours and 30 minutes.
The change simply makes it so the test ignores differences in minutes
between UTC and local time in addition to ignoring differences in
hours.
Signed-off-by: Paavo Parkkinen <pparkkin@gmail.com>

Fix test for `str_ftime()` in Singapore time zone

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

enableAggressiveLoopVersioning is a new jit option that will be used to
guard a number of changes to the behaviour of LoopVersioner.

Add new Xjit option enableAggressiveLoopVersioning

---

compiler/il/NodePool.cpp
compiler/il/NodePool.hpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/optimizer/DeadTreesElimination.cpp
compiler/optimizer/LoopVersioner.cpp

This change removes the node pool functionality to look up a node by its
pool index. This feature is rarely used in the compiler and not allowing
lookup by index allows for future changes to the node allocation
algorithms that do not permit such lookup.

[Mem7] Remove Node lookup by index from NodePool

---

.appveyor.yml

This test is not testing anything particularily useful, and takes up
a significant ammount of time in the appveyor builds (~20 min)

Appveyor: Disable TestOtherThreadCputime

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlBuilder.hpp
compiler/ilgen/VirtualMachineOperandArray.cpp
compiler/ilgen/VirtualMachineOperandArray.hpp
jitbuilder/build/files/common.mk
jitbuilder/build/rules/common.mk
jitbuilder/release/Makefile
jitbuilder/release/src/OperandArrayTests.cpp
jitbuilder/release/src/OperandArrayTests.hpp

Not all Virtual Machines have an Operand Stack. Another common construct
is to have a fixed sized array of "registers". The new
VirtualMachineOperandArray is very similar to the VMOS but it does not
allow for growth and it has to deal with NULL entries as not all entries
may have a value.
The VirtualMachineOperandArray::Move API requires that a copy of the
IlValue stored at srcIndex be stored at dstIndex. To accomplish this I
added a new API to IlBuilder call CopyValue.
I have added tests to verify the all of the functionality.

Add support for VirtualMachineOperandArray

---

compiler/infra/ILTraverser.cpp
compiler/infra/ILTraverser.hpp
compiler/infra/TrilDumper.cpp
compiler/infra/TrilDumper.hpp

These commits add two new convenience classes to the OMR compiler:
* `TR::ILTraverser`: abstracts away traversing Testarossa IL using the Observer pattern
* `TR::TrilDumper`: a class for printint Testarossa IL as Tril code
Currently, neither of these classes are actually being used. This pull requests simply contributes them so they can be used in later work. I have tested the changes locally by "artificially" connecting the new classes to a downstream project and ensuring that the printed Tril code reproduces the behavior of the original source code when compiled and executed.
[ci skip] because these classes are not being used by anything and can't be tested directly

Add ILTraverser and TrilDumper to compiler

---

compiler/control/OMROptions.cpp

Add options to disable and trace OSRGuardRemoval,
an optimization in a downstream project.

Add options for OSRGuardRemoval

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/il/Node.hpp
compiler/il/NodePool.cpp
compiler/il/NodePool.hpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/il/OMRNode_inlines.hpp
compiler/ras/Tree.cpp

OptAttributes hold information about a Node, such
as its reference count and local index. They are held separate
so that the OptAttributes can be freed when no longer needed.
Currently this is limited to before codegen on certain platforms.
However, they are already allocated into the heap region
using a CS2 TableOf and only have a limited chance of their memory
being reused by another CS2 data structure.
Moving these fields into the Node itself with proper ordering
results in only an 8 byte increase to its size and improves
locality, as they are frequently accessed.

Merge OptAttributes into Node

---

compiler/il/OMRDataTypes.hpp
compiler/optimizer/OMRValuePropagation.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

The macro 'null' was defined to be '{0}' a zeroed struct. It was only
used to initialize pointer variables, in which case it is no different
from 0 or NULL. Removing the definition and usage of 'null' makes it
easier to use omr alongside code that defines or uses 'null' in a
different manner.

Remove macro definition 'null'

---

cmake/platform.cmake

The file is dominantly a tabs file, so the spaces led to indentation
issues.

Remove indenting spaces in platform.cmake

---

compiler/x/codegen/OMRCodeGenerator.cpp

VFPSubstitution trace header was not properly printed
on PROD mode. Fixing it.

Fix for missing VFPSubstitution trace header

---

gc/CMakeLists.txt

This matches the behaviour in the makefiles, and allows more modern
versions of GCC and clang to pass the GC tests.

[CMAKE] Use -fno-strict-aliasing for GC

---

compiler/optimizer/LocalDeadStoreElimination.cpp
compiler/optimizer/LocalDeadStoreElimination.hpp

LocalDSE is currently using a shared bit vector for internal liveness
tracking. These bit vectors leak into the heap and consume large amounts
of memory. This change converts the optimization to use a stack
allocated TR_BitVector to save space.

[Mem8] Use TR_BitVector in LocalDSE

---

omrmakefiles/rules.mk

Shared libraries must come after static libraries on the link command.
This is to satisfy missing symbols in static libraries. The old code
actually documented this requirement, but did not implement it.
This patch fixes a link error in ddrgen.

Fix link order

---

fvtest/porttest/omrstrTest.cpp
fvtest/porttest/testHelpers.cpp
jitbuilder/release/src/OperandStackTests.cpp
port/common/j9nls.c
port/common/omrerror.c
port/common/omrfile.c
port/common/omrfilestreamtext.c
port/common/omrstr.c
port/unix/omrfile.c
port/win32/omrfile.c

Usage of this method is incorrect in several port methods. This commit
fixes usage and simplifies affected methods somewhat.

Fix str_vprintf() usage in port library

---

compiler/control/OMROptions.cpp

Add dontSuspendCompThreadsEarly option to allow for disabling compilation
thread early suspension. Some platforms may have suspendEarly option
turned on by default.

Add dontSuspendCompThreadsEarly option

---

compiler/optimizer/LoopVersioner.cpp

The current default threshold of 5000 for lvBlockFreqCutoff was
found to be too high for some use-cases. A lower threshold of
500 was introduced, currently subject to
-Xjit:enableAggressiveLoopVersioning
being set until the change is tested across more
applications. The env var TR_LoopVersionerFreqCutoff remains
available to over-ride the default setting.

Reduce the default lvBlockFreqCutoff value

---

compiler/optimizer/LoopVersioner.cpp

It was found that the test for unimportant blocks based on block
frequency in TR_LoopVersioner::detectChecksToBeEliminated was
detrimental to performance at higher optimisation levels. An
additional test was added to restrict the code path to optlevels
warm and lower. The new behaviour is gated by the Xjit option
enableAggressiveLoopVersioning added by PR #1369

Only run the unimportant block test at <=warm

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

If one chooses to disable z10 architecture level, traps should be disabled
so that the optimizations and codegen can avoid generating trap-related IL
nodes and instructions.
Move project specific random z architecture level disabling code out of
OMR and into the relevant project.

Disable traps when z10 architecture is disabled

---

compiler/compile/OSRData.cpp
compiler/optimizer/LocalOpts.cpp

Setting the frequencies on blocks during IlGen
can prevent the JitProfiler from properly applying
its raw frequencies. OSR blocks, which can be created
during IlGen, have always received a frequency of 0.
This modifies them to receive a frequency of -1, 
which is later set to 0 during ColdBlockMarker.

Set OSR block freq during ColdBlockMarker

---

tools/compiler/scripts/guess-platform.sh

use [ instead of [[
fixes #1449

Make compiler configuration more portable

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.hpp
include_core/omrport.h
port/linuxs390/omrrttime.s
port/linuxs390/omrtime.c
port/linuxs39064/omrrttime.s
port/zos390/omrrttime.s
port/zos390/omrtime.c

Previously, the high-resolution timer was truncated to 1/8 of a microsec and then multiplied by a constant to e.g. obtain the current time in nanoseconds.
Now, we obtain high-resolution timer that has the precision of approximately 0.5 of a nanosecond and adjusts it to produce e.g. the current time in nanoseconds without losing precision.

Z nanotime precision

---

gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Concurrent Scavenger might be called earlier then GC Master Thread
initialization is complete. So pre-initialization required.
Add preMasterGCThreadInitialize() implementation to the Scavenger.
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Partial GC initialization for Concurrent Scavenger

---

compiler/compile/VirtualGuard.hpp

This change extends VirtualGuard so that guards
can be labelled as unmerged and canBeRemoved can
now be asked to ignore whether guards have been
merged.

Improve VirtualGuard canBeRemoved and merged API

---

thread/CMakeLists.txt

IF OMR_THR_JLM is enabled, compile omrthreadjlm.c as part of
thread library

CMake: Compile omrthreadjlm.c

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/infra/OMRCfg.cpp
compiler/infra/OMRCfg.hpp
compiler/infra/TRCfgEdge.hpp
compiler/infra/TRCfgNode.hpp
compiler/optimizer/GeneralLoopUnroller.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/StructuralAnalysis.cpp
compiler/optimizer/StructuralAnalysis.hpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VirtualGuardCoalescer.cpp
compiler/ras/Debug.cpp
compiler/ras/Tree.cpp

Currently structure nodes are allocated on the heap. The structure information is regularly invalidated during compilation and rebuilt. Each invalidates structure graph currently leaks until the end of the compilation and can amount to a non-trivial amount of memory. This change creates a TR::Region in the CFG to hold structure so that we can invalidate it.
This change is based on the [Mem8] change so the 'Use TR_BitVector in LocalDSE' change is from that PR.

[Mem9] Create a memory region to hold structure

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/infra/OMRCfg.cpp
compiler/infra/OMRCfg.hpp
compiler/infra/TRCfgEdge.hpp
compiler/infra/TRCfgNode.hpp
compiler/optimizer/GeneralLoopUnroller.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMRLocalCSE.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/StructuralAnalysis.cpp
compiler/optimizer/StructuralAnalysis.hpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VirtualGuardCoalescer.cpp
compiler/ras/Debug.cpp
compiler/ras/Tree.cpp

This commit changes the data storage of LocalCSE from using CS heap allocated structures to using region allocated structures so that we can release the memory consumed during the execution of LocalCSE. Without this improved memory management the optimization can leak hundereds of MB of memory during some large compilations.
This change is based on [Mem 9] and so commits from 'Convert LocalCSE CS2 TableOf into std::map' onward should be considered. This should be merged after Mem8 and Mem9

[Mem10] Reduce memory leakage from LocalCSE

---

fvtest/porttest/testProcessHelpers.cpp

This comment refers back to a time when J9's source code was stored in
ENVY Smalltalk's cdev environment.  Removing it now as it's no longer
accurate.
[skip ci]

Remove reference to ENVY Cdev limitations

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/infra/OMRCfg.cpp
compiler/infra/OMRCfg.hpp
compiler/infra/TRCfgEdge.hpp
compiler/infra/TRCfgNode.hpp
compiler/optimizer/GeneralLoopUnroller.cpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMRLocalCSE.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/StructuralAnalysis.cpp
compiler/optimizer/StructuralAnalysis.hpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VirtualGuardCoalescer.cpp
compiler/ras/Debug.cpp
compiler/ras/Tree.cpp

The CFG findLoopingBlocks creates a CS2 TableOf as part of its algorithm. This use of a TableOf wastes a lot of memory and and leaks memory for the remainder of the compilation. This change cleans up this code and converts it to use structures compatible with a region allocator that can be cleaned up when the method returns.
This commit is based on Mem9 and Mem10 - the delta for this change is one commit.

[Mem11] Clean CFG TableOf

---

compiler/compile/OMRSymbolReferenceTable.hpp
compiler/ras/Debug.cpp

bcdCheckSymbol is no longer used either in OMR or in any upstream
projects. It is slated to be deprecated.

Deprecate unused bcdCheckSymbol

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/infra/OMRCfg.cpp
compiler/infra/OMRCfg.hpp
compiler/infra/TRCfgEdge.hpp
compiler/infra/TRCfgNode.hpp
compiler/optimizer/GeneralLoopUnroller.cpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMRLocalCSE.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/StructuralAnalysis.cpp
compiler/optimizer/StructuralAnalysis.hpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/VirtualGuardCoalescer.cpp
compiler/ras/Debug.cpp
compiler/ras/Tree.cpp

The TableOf data structure is used to store monitor information during codegen which results in increased memory usage. This commit replaces the TableOf with an std::map for efficiency.
This change is based on top of Mem9, 10, and 11. It consists of one commit.

[Mem12] Clean up TableOf from code generator

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/LoopVersioner.cpp

The new option disableLoopTransfer replaces the
use of environment variable TR_disableLoopTransfer. The option
is applied at both the original location and two further points
to more completely suppress the artifacts related to loop
transfer.

New option disableLoopTransfer

---

fvtest/gctest/CMakeLists.txt

Quotation marks are unnecissary in the gtest_filter arg, and cause
the filter to be parsed incorrectly by gtest. This resulted in
gc tests not being run.

CMake: Fix error in gctest CMakeLists

---

compiler/optimizer/Inliner.cpp

OSR book keeping is represented in the IL. Therefore,
it can significantly increase the number of nodes needed.
To retain the prior inlining performance, the limit based
on node count must be increased under OSR.

Increase inlining node count for OSR

---

CMakeLists.txt
cmake/Assert.cmake

Add a barebones assert function for checking assumptions in cmake.
/cc @dnakamura @mgaudet 

CMake: Add omr_assert utility

---

compiler/x/codegen/X86BinaryEncoding.cpp

There are cases where a X86ImmInstruction contains method/class
address and relocation records with correct type are needed.

Add more aot relocation types to X86ImmInstruction

---

compiler/optimizer/InductionVariable.cpp
compiler/optimizer/InductionVariable.hpp

Exit edges to OSR blocks can be ignored under
induction variable analysis as they do not
depend on the induction variable and will
not modify it. They are mostly ignored already
unless the exit edge is from an inner region.

Ignore OSR exit edges for induction variables

---

cmake/compiler_support.cmake
fvtest/CMakeLists.txt
fvtest/compilertriltest/CMakeLists.txt
fvtest/tril/CMakeLists.txt
fvtest/tril/examples/CMakeLists.txt
fvtest/tril/examples/incordec/CMakeLists.txt
fvtest/tril/examples/mandelbrot/CMakeLists.txt
fvtest/tril/test/CMakeLists.txt
fvtest/tril/test/main.cpp
fvtest/tril/tril/CMakeLists.txt
fvtest/tril/tril/jitbuilder_compiler.cpp
jitbuilder/CMakeLists.txt

This change set does some clean up to Tril and its cmake files to allow better integrate with the other OMR cmake files. It also adds the Tril tests and Tril-based compiler tests to the Travis builds.

Add Tril tests to Travis builds

---

compiler/z/runtime/VirtualGuardRuntime.cpp

_patchVirtualGuard is a sensitive function which carries out runtime
patching. It is essential this function is properly documented and that
its semantics are enforced to prevent potential runtime patching bugs in
the future.

Document and enforce assertion in _patchVirtualGuard

---

README.md

I was looking at what files were missing copyrights, and noticed that most markdown files are guilty. As a demo, this commit adds a copyright header as a comment. It won't show in the GitHub rendering. I've also added a shorter copyright footer, which is displayed.  To be honest, I'm not sure this is wanted, but here it is.
You can check out the render here: https://github.com/rwy0717/omr/tree/copyright

Add copyright to README.md

---

example/glue/EnvironmentDelegate.cpp
example/glue/EnvironmentDelegate.hpp
gc/base/EnvironmentBase.cpp
gc/base/EnvironmentBase.hpp
gc/base/MasterGCThread.cpp

During Concurrent phase of Concurrent Scavenger (CS) cycle, GC should
keep VM access (since it's indeed accessing heap and furthermore
mutating it), to prevent/delay other parties (for example RAS) from
obtaining exclusive VM access.
It's sufficient that only Master GC thread holds the access. 
In existing handshaking when Master GC thread release exclusive access
(and passes it to the mutator thread that triggered GC), normally,
Master GC thread would release VM access. This change will make it to
defer this action if it's known that the current STW phase is
immediately followed by concurrent phase. Only when the concurrent phase
is complete, master GC thread will release VM access.
Language specific code may disobey the request to defer release VM
access. If so, it will notify the …

VM access during Concurrent Scavenger

---

fvtest/jitbuildertest/CMakeLists.txt

This change enables building and running the JitBuilder tests in
`<omr_root>/fvtest/jitbuildertest` using CMake.
Signed-off-by: Sajid Ahmed <Syed.Sajid.Ahmed23@ibm.com>

Add JitBuilder tests in CMake builds

---

cmake/modules/OmrDetectSystemInformation.cmake

The z/os configuration is wrong, but at least we'll try something.
/cc @dnakamura @mgaudet @charliegracie 

CMake: Set the tool configuration for osx, z/os.

---

fvtest/omrtest.mk
jitbuilder/optimizer/JBOptimizer.cpp
jitbuilder/release/src/OperandArrayTests.cpp

Three small corrections:
1. Reverse order of induction variable analysis and loop canonicalization in JitBuilder opt strategy, plus add a block ordering pass beforehand to clean up the blocks.
2. Workaround fix for an assertion in the OperandArrayTests code sample. The correct fix will be a broader change so I want to get this test working and into our pull request testing first.
3. For JitBuilder testing, run "make testall" on linux_x86 and osx platforms, but "test" elsewhere.

JitBuilder cleanup

---

CMakeLists.txt

Using CMAKE_SOURCE_DIR will result in a bogus module path when there is
a parent cmake project vendoring OMR. IE CMAKE_SOURCE_DIR will not point
at the root of OMR.

CMake: Set the module path relative to the current dir

---

CMakeLists.txt
cmake/config.cmake
fvtest/CMakeLists.txt

This flag is already enabled in CI, but was never used properly.

CMake: Add OMR_FVTEST

---

CMakeLists.txt
example/glue/CMakeLists.txt

Instead of taking cache variable OMR_GLUE which points to directory
with glue, now take OMR_GLUE_TARGET which contains name of glue target
Old system was limited to having glue reside in a subdirectory of
omr, which is not particularily useful.

CMake: Change glue to be interface library

---

port/CMakeLists.txt
thread/CMakeLists.txt
util/omrutil/CMakeLists.txt

Build omrutil, j9thrstatic, and omrport as object libraries so that consumers can extend them if they wish.  The normal static libraries are still built from the object libs for internal use

CMake: Build object libraries

---

port/common/omrcuda.cpp

Support for compute 1.x devices is removed in CUDA 9.
JIT targets don't need to be remapped in CUDA 6 and later.

Support CUDA 9

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlBuilder.hpp

After the new IL validator showed up, it exposed some weaknesses in
how operands of shift operations were being handled by JitBuilder.
In particular, shift operands are validated using the same mechanism
as for other binary operations, and that mechanism is entirely
inappropriate for shifts. In fact, it only really works for 32-bit
shift operands
This commit separates out the handling of shift operations from the
generic binaryOp* handling and makes the operand testing a bit more
relevant: the left operand must be integer typed, if the left operand
is narrower than 32-bits then it will be automatically widened to
32-bits, the right operand will be automatically converted to a
32-bit integer. If no conversion exists for either operand,
ConvertTo should assert.
Signed-off-by: Mark Stoodley …

Improve JitBuilder handling of shift operands

---

compiler/z/runtime/VirtualGuardRuntime.cpp

When patching happens synchronously we are effectively patching in a
jump with a guarantee no processor will be executing the patch location.
Thus there is no race condition. This means we will be overwriting
existing instructions. If it so happens that the instruction at the
patch location has opcode 0xA7 or 0xC0 as the first byte we may
encounter a false positive and incorrectly assert. Such an example can
be seen if an LHI R8,0 (0xA7880000) instruction is after the VGNOP.
This fix strengthens the condition of when one byte patching happens,
i.e. if and only if we are certain a BRC or BRCL is present.

Fix _patchVirtualGuard to not assert on false positives

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/Region.hpp
compiler/il/Aliases.cpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/Structure.cpp

The current aliasing infrastructure allocates bit vectors to return to
callers of the aliasing interface. These bit vectors are heap allocated
and leak to the end of the compile. This change introduces a region to
hold these bit vectors and an API on the compilation to signal when it
is safe to invalidate the region and release the memory. The change adds
a call in LocalCSE to this API as well as calling it between
optimizations to reduce memory usage.

[Mem14] Create a region to hold alias set BitVectors

---

compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/Structure.cpp

We are seeing problems where GRA is running away with its memory usage. This commit compacts a number of data structures and reduces duplication to significantly reduce GRA's peak memory usage.
This is built on top of Mem14 and Mem15.

[Mem16] Reduce GRA memory usage

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/Region.hpp
compiler/il/Aliases.cpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/InductionVariable.cpp
compiler/optimizer/InductionVariable.hpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/Structure.cpp

Currently the loop strider allocates large amounts memory during it recursive analysis routines and this memory leaks during the analysis. This memory leaks until the optimization has finished running which has caused some massive growth in memory consumption. Further, some data structures are pre-sized to the number of symbol references when the actual number of live entries is very small. To reduce this wasted space, several key data structures are transformed from arrays to maps keyed by symref index.
This commit is based on top of Mem 9, 10, 11, 12 and 13 and so should be merged after these other changes. The delta in this commit is 2 commits beyond those in Mem 13.

[Mem15] Reduce LoopStrider memory usage

---

CONTRIBUTING.md

Fixes some grammatical errors, and make an example commit a little
clearer (so that it actually complies with the commit guidelines)
[ci skip] documentation change

Tweak phrasing of CONTRIBUTING.md

---

port/linuxs390/omrtime.c

Signed-off-by: Alexey Zhikhartsev <alexey.zhikhartsev@ibm.com>

Use hardware clock in omrtime_nano_time on zLinux

---

cmake/compiler_support.cmake

This patch turns the JIT platform detection into a function, and starts
to separate some pieces into variables. A side effect of this patch is
that it adds support for building compiler components with OS/X.

[CMake] Refactor JIT platform detection

---

fvtest/compilertest/control/TestJit.cpp
fvtest/compilertest/tests/BuilderTest.cpp
fvtest/compilertest/tests/BuilderTest.hpp
fvtest/jitbuildertest/IfThenElseTest.cpp
fvtest/jitbuildertest/Makefile

This PR includes:
- A change to enable "paranoidOpCheck" option every time when test compiler runs.
- A change to replace the SubIfThenElseMethod test, with three test cases. The original test has no return value, resulting in failing the CFG checker. So three new test cases are added to completely replace it. 
```
Fixes #1317

Enable the tree verifier and replace a test case

---

compiler/p/codegen/FPTreeEvaluator.cpp
compiler/p/codegen/OMRTreeEvaluator.cpp

Evaluators that call generateMvFprGprInstructions()
on Power with the gpr2fprHost32 or fpr2gprHost32
options need to check if the current CPU is '>= p8'
rather than just '== p8' so they can pass the required
temp register to generateMvFprGprInstructions().
Fixes #1415.

Make evaluators agree with codegen on CPU checks

---

compiler/ilgen/IlInjector.cpp
compiler/ras/ILValidator.cpp
fvtest/compilertriltest/ArithmeticTest.cpp
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/ILValidatorTest.cpp
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/OpCodeTest.hpp
fvtest/tril/test/ASTTest.cpp
fvtest/tril/tril/ast.c
fvtest/tril/tril/ast.h
fvtest/tril/tril/ilgen.cpp

Various improvements to Tril-based tests:
- remove some compiler warnings
- rename some tests
- improve availability of some testing utilities
- add tests and test input values
- run ILValidator immediately IlGen in IlInjector

Tril test improvements

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/Region.hpp
compiler/il/Aliases.cpp
compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/CopyPropagation.hpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/InductionVariable.cpp
compiler/optimizer/InductionVariable.hpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/Structure.cpp

Performance analysis of the compile time of the OMR compiler has shown that copy propagation is consuming a very large amount of time when compiling methods with 1000s of symbol references and 1000s of blocks. The inner loop of the optimization was found to be iterating over all def indices and all use indicies for each block. This set of commits improves the performance of this inner loop to provide significant compile time savings.
This commit depends on Mem14-Mem16.

[Comp17] Reduce runtime complexity of copy propagation

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/env/Region.hpp
compiler/il/Aliases.cpp
compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/CopyPropagation.hpp
compiler/optimizer/FieldPrivatizer.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/InductionVariable.cpp
compiler/optimizer/InductionVariable.hpp
compiler/optimizer/IsolatedStoreElimination.cpp
compiler/optimizer/IsolatedStoreElimination.hpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp
compiler/optimizer/Structure.cpp

Global dead store elimination has an inner loop which scales based on the highest symbol reference number in a method. This is very wasteful since only a small fraction of symrefs participate in global dead store elimination. This commit rewrites this inner loop to scale better as the number of symbol references grows.
This commit depend on Mem14 - Comp17

[Comp18] Improve performance of global dead store elimination

---

compiler/ilgen/MethodBuilder.cpp

Systems with older compilers have trouble with the
"= default" notation from C++11, particularly in
combination with the array fields in MethodBuilder.
Nothing currently requires this constructor, so just
remove it.

Remove default constructor for MethodBuilder

---

compiler/compile/OMRCompilation.cpp
compiler/control/OMROptions.hpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/LoopVersioner.cpp

Ensure OSR related tracing is properly guarded
by the TraceOSR option and disable it by default.

Reduce OSR logging and disable by default

---

.travis.yml
scripts/build-on-travis.sh

Delete the old osx build, because they are slow and keeping both will
bog down our CI.

CMake: Build with CMake on Travis OSX

---

cmake/platform/os/linux.cmake

Check if clock_gettime/settime family of functions are included in libc
or if we need to explicitly link against librt

CMake: Check if we need librt

---

tools/compiler/OMRChecker/README.md

Updated OMRChecker README.md with the prerequisit packages specific for Ubuntu
Signed-off-by: Samer AL Masri <almasri@ualberta.ca>

OMRChecker Doc Update

---

compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

UseDef will give up if there are too many
uses and defs. The number of defs can increase
dramatically under voluntary OSR, due to the
use of irrelevant stores at each transition
point. This change counts these stores and
prevents them from being considered in the
UseDef control logic.

Ignore irrelevant stores in UseDef control

---

compiler/infra/TrilDumper.cpp
fvtest/compilertriltest/ILValidatorTest.cpp
fvtest/tril/examples/mandelbrot/mandelbrot.tril
fvtest/tril/test/ASTTest.cpp
fvtest/tril/test/ParserTest.cpp
fvtest/tril/tril/CMakeLists.txt
fvtest/tril/tril/ast.cpp
fvtest/tril/tril/ast.h
fvtest/tril/tril/ast.hpp
fvtest/tril/tril/ilgen.cpp
fvtest/tril/tril/ilgen.hpp
fvtest/tril/tril/method_info.hpp
fvtest/tril/tril/tril.l
fvtest/tril/tril/tril.y

This batch of changes makes several improvements to Tril, including:
* A better API for the AST
* Support for hex literals
* Deprecate `@common` syntax in favor of `@id` (issue #1508)
* More documentation 
* More tests
Fixes #1508

Yet another batch of Tril improvements

---

compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/InstOpCode.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/S390Instruction.hpp

Modified getMaskForBranchCondition to return expected hex values
instead of expected hex values bit shifted by 4. Modified function
calls that were compensating for this bit shift.

Modified getMaskForBranchCondition(...)

---

CMakeLists.txt
omr/CMakeLists.txt
port/CMakeLists.txt
scripts/build-on-travis.sh
thread/CMakeLists.txt
util/avl/CMakeLists.txt
util/hashtable/CMakeLists.txt
util/hookable/CMakeLists.txt
util/omrutil/CMakeLists.txt
util/pool/CMakeLists.txt

* Propagate include directories to the CMakeLists.txt that need them
* Throttle Travis builds. I'm seeing timeouts  that I can't reproduce locally.

Don't set CMAKE_INCLUDE_CURRENT_DIR

---

util/hashtable/hashtable.c

Silence unused value warnings created by building the hashtable without
debug enabled.

Make no-op hashtable printf into a function

---

compiler/il/OMRNode.cpp

Modify OMR::Node::exceptionsRaised to indicate the fact that Node
with zerochk opcode can throw exception

Add exception throwing case for ZEROCHK

---

compiler/optimizer/OMRSimplifier.cpp
compiler/optimizer/OMRSimplifier.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp

Fix lowering methodExitHook simplifier
With inlining in debugging mode, there might be multiple method
enter/exit hooks in one extended basic block and the old way of
lowering them is wrong. This PR collect enter/exit treetops and nodes
into a list and process them after finishing all other nodes in
the same extended basic blocks to avoid spliting a block while in
the process of analyzing the block.

Fix lowering methodExitHook simplifier

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/optimizer/LoopVersioner.cpp

isPotentialOSRPoint will check if OSR infrastructure
has been removed, preventing yield points from appearing
as though they require special consideration after OSR
transitions can no longer be added. However, loop versioner
was using the call to identify any yield point, irregardless
of the infrastructure state.

Correct LoopVersioners use of isPotentialOSRPoint

---

util/hookable/CMakeLists.txt

Build j9hook_obj library which is used to build j9hookstatic.
This allows consumers to extend the library as desired.

CMake: Build j9hookstatic as object library

---

compiler/z/codegen/OMRMemoryReference.cpp

RSL instructions (such as TP) do not have an index register. As such we
must treat them specially when generating long displacement logic.
Similar logic already exists for various other kinds of instructions
with memory references that do not have an index register.
To prevent future problems in this area we also take the opportunity to
add a fatal assert if this issue arises in the future.

Fix long displacement for RSL instructions

---

gc/base/Collector.hpp
gc/base/MasterGCThread.cpp
gc/base/omrmmprivate.hdf
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/stats/ConcurrentPhaseStatsBase.hpp
gc/verbose/VerboseHandlerOutput.cpp
gc/verbose/VerboseHandlerOutput.hpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.hpp

Verbose GC improvements for Concurrent Scavenger. Now reporting gc-op
for each of 3 phases of CS (2xSTW and one concurrent). Also introducing
a wrapper stanza (concurrent-end) for concurrent scavenge gc-op:
<concurrent-end id="12169" type="scavenge" contextid="12159" timestamp="2017-08-18T14:28:44.329">
<gc-op id="12170" type="scavenge" timems="19.722" contextid="12159" timestamp="2017-08-18T14:28:44.329">
<memory-copied type="nursery" objects="9888" bytes="450472" bytesdiscarded="7816" />
<memory-copied type="tenure" objects="64" bytes="2256" bytesdiscarded="4112" />
</gc-op>
</concurrent-end>
In future, this wrapper may report some concurrent specific data of
scavenge (that gc-op does not report), like read barrier counts.

VGC improvements for CS

---

port/unix/omrsignal.c

Executables are able to override global symbols defined in a shared lib.
Thus if a program ever defines a symbol signalMap, and consumes the
port library as a shared library, it will cause incorrect behaviour

Port: Mark signalMap static

---

compiler/z/runtime/VirtualGuardRuntime.cpp

It does not appear for there to be a safe way to tell whether we are
patching synchronously or asynchronously without false positives. The
asserts placed in this function are firing off on upstream projects
because runtime virtual guards that are placed as NOP guards could have
arbitrary code after them, even other NOP branches. 
As such for a synchronous virtual guard we will be clobbering the block
it is guarding and we cannot be certain what is at the location we will
be patching. It could in fact be another NOP branch which may confuse us
when trying to distinguish whether we are patching a NOP BRC / BRCL.
All assertions have been removed from this function. Furthermore the
patching order has been re-ordered to be as safe as possible with the
information we have at hand. It will be up …

Remove assertions in _patchVirtualGuard

---

CMakeLists.txt
cmake/config.cmake
fvtest/gctest/CMakeLists.txt
fvtest/sigtest/CMakeLists.txt
fvtest/threadextendedtest/CMakeLists.txt
fvtest/threadtest/CMakeLists.txt
gc/CMakeLists.txt
omr/CMakeLists.txt
omrsigcompat/CMakeLists.txt
omrtrace/CMakeLists.txt
port/CMakeLists.txt
thread/CMakeLists.txt
util/hookable/CMakeLists.txt

Refactor linking in order to better represent dependencies.
In addition provide new cache variables to allow consumer to
override the use of trace, hook, port, thread, and gc libs

CMake: Refactor linking

---

jitbuilder/CMakeLists.txt
jitbuilder/release/CMakeLists.txt

Also add the missed virtual machine modelling files to the CMake source lists.

Add missing JitBuilder examples to CMake 

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Fix the order of writes vs write fence when setting Scavenger backout
flag/index, on weak memory model CPUs.
Also declare the index as volatile. There is no proven problem atm, but
it indeed is being modified/consumed by/from multiple threads.

Scavenger backout flag on weak memory CPUs

---

fvtest/tril/tril/CMakeLists.txt
fvtest/tril/tril/compiler.cpp

- tril_dumper takes a tril program on stdin or as a file argument,
parses it and then dumps the AST to stdout.
- tril_compiler does the same, then compiles the code. It does nothing
with the compiled code, but this can be useful for checking validation
errors quickly.

Add two prototype Tril utilities

---

compiler/optimizer/LoopVersioner.cpp

LoopVersioner will search for profiled nodes,
to build versions of loops where the profiling
is disabled. If a node beneath a nopable guard
shares BCI with a profiled value, LoopVersioner may
mistake the guard's child as being profiled. This
change prevents the method from analysing the children
for a nopable guard.

Prevent LoopVersioner from checking guards

---

CONTRIBUTING.md

After the discussion and vote in Issue 1501, the committers have
decided to increase the limit on commit message titles to 70
characters and loosen to "where reasonable" rather than use a
hard limit.
[ci skip]
Fixes 1501.
Issue: 1501

Adjust CONTRIBUTING.md guidelines to allow longer commit titles

---

fvtest/omrtest.mk

OSX and Linux x86 are the only platforms which can run testall. The
conditional for the test makefile was checking the wrong values. This
change fixes the conditionals so the correct tests run on each platform.

Correct the jit builder test platform coverage

---

compiler/compile/Method.cpp
compiler/compile/ResolvedMethod.hpp

isDebugable is no longer used by any language implementation.

Delete unused isDebugable

---

compiler/control/OMROptions.cpp

A letter 't' was missing for Option "disableTraps".
By fixing it, compilation warning "unknown escape sequence \d"
is eliminated.
Issue: #1451

Fix for a typo in JIT Options

---

compiler/env/Region.hpp

Currently, resolution of TR::Region::allocate for integers that are not
of type size_t resolves to the function template used to instantiate
managed instances of objects. This is dangerous.
To fix this, change the name of the function template to 'create' so
that it is no longer a homonym of the standard allocate function.

Fix resolution of allocate for non-size_t integers

---

cmake/compiler_support.cmake
cmake/modules/platform/arch/ppc.cmake
cmake/modules/platform/arch/s390.cmake
cmake/modules/platform/arch/x86.cmake
cmake/modules/platform/os/aix.cmake
cmake/modules/platform/os/linux.cmake
cmake/modules/platform/os/osx.cmake
cmake/modules/platform/toolcfg/gnu.cmake
cmake/modules/platform/toolcfg/xlc.cmake

Remove `tr_detect_system_information` and integrate the compiler build variables into the broader OMR platform system.

Distribute Testarossa Platform Support. 

---

.travis.yml
fvtest/porttest/omrfileTest.cpp
fvtest/porttest/omrheapTest.cpp
fvtest/porttest/omrtimeTest.cpp
fvtest/threadextendedtest/timeBaseTest.cpp
fvtest/threadtest/rwMutexTest.cpp
fvtest/threadtest/sanityTest.cpp
fvtest/threadtest/sanityTestHelper.cpp
scripts/build-on-travis.sh

A lot of the OMR tests take a very long time to complete. This change
reduces a number of these tests to a more managable time.  The
reductions were the result of fewer loops and smaller sleep/timout
times.

Test improvements

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/stats/ScavengerStats.cpp
gc/stats/ScavengerStats.hpp
gc/verbose/handler_standard/VerboseHandlerOutputStandard.cpp

In Concurrent Scavenger gather per phase/increment Scavenger stats.
These are typically used for reported purposes. Than at the end of a
cycle merge those stats. Those are typically used for various heuristics
(like tilting) that are performed at the end of a cycle. Currently,
since we clear per increment stats and do not merge them, the heuristics
rely only on last increment, which is vary small data subset.
Standard Scavenger is not meant to be affected, although a lot of code
is shared with CS. There is still a notion of an increment, but there is
only one. We still merge that one with the cycle stats, so there are
identical.

Merge stats across CS phases

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Two small changes:
1) set initial count of Concurrent Scavenger background threads to 1.
Remove special path initialization of background thread count, that was
used in rare scenarios when GC was triggered before MasterGCThread was
in place - in those cases we will just default to count 1 (same as
before).
2) Added a 'forced' flag that give us ability to explicitely set
background thread count (for example through command line option). This
way, the full blown count initialization at a later point (when Parallel
Dispatcher is in place) can distinguish between count 1 being default
(which could be overriden) and count 1 being explicitely set (which must
not be overridden).

CS background threads

---

.travis.yml

- Install CCACHE on OSX via homebrew
- Use clang as the compiler for OSX. It was getting used since gcc/g++
are symlinks to clang but we should be explicit 

Use CCACHE on OSX

---

compiler/optimizer/FieldPrivatizer.cpp

Field privatizer can turn wrtbars that store to a static into a wrtbar
that stores to an auto. However, stores to autos do not need a wrtbar.
This change causes field privatizer to instead convert the wrtbar to an
aStore.
The second child of the original wrtbar is not needed by the new aStore so
it get anchored. This change set also fixes the issue with privatizing
indirect loads and stores where the children that were not being used were
not being anchored. Those children will now be anchored as well.
Particular care was taken to ensure that the nodes are anchored in the
same order they would have normally have been evaluatated in.
Issue: #1426

Change privatized wrtbar into an aStore

---

CMakeLists.txt
cmake/config.cmake
cmake/modules/OmrHookgen.cmake
cmake/modules/OmrTracegen.cmake

This patch lets us compile and use the tools when cross compiling for
x86 on an x86-64 machine.
I've simplified the tools directory, moving the add_tracegen and
add_hookgen macros to seperate modules. This lets them be used outside
of OMR more easily. Now, we can completely skip the tools directory when
importing.
Do not skip the tools directory when cross compiling. Instead, emit a
message that the tools will be cross compiled.
The OMR_TOOLS flag is now respected. If you have the hookgen or tracegen
tools installed on your system, you should be able to disable building
the bundled tools completely. Imported tools will always be used,
regardless of the OMR_TOOLS state.

cmake: Support tools cross compilation

---

compiler/env/TRMemory.hpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/OMROptimization.hpp
compiler/optimizer/OMROptimizationManager.hpp
compiler/optimizer/OptimizationData.hpp
compiler/optimizer/OptimizationPolicy.hpp
compiler/optimizer/OptimizationUtil.hpp
compiler/optimizer/SinkStores.hpp
compiler/optimizer/UseDefInfo.hpp
compiler/optimizer/ValueNumberInfo.hpp
compiler/z/codegen/OMRInstruction.hpp

Removed inheritance from classes using Allocatable due to
infrequent and inconsistent usage of the class. Functionality
required from Allocatable has been copied directly into the
classes that require it.

Removing Allocatable class and inheritance

---

cmake/modules/OmrFindFiles.cmake

Modify omr_find_files to issue a error rather than a warning if it cant
find a file.

CMake: make omr_find_file issue error on unfound file

---

omr.rc.in

Comments in RC files are regular C comments. Switch the copyright header
to the proper format to resolve compilation issues.
This was missed on the AppVeyor builds since consuming the rc files have
not been implemented in CMake yet.

Fix compilation issue on Windows

---

omrmakefiles/rules.ztpf.mk
port/ztpf/omrosdump_helpers.c

Removes origin ld specification which caused a link failure.
Fix osdump_helpers casting compilation errors.  Compilation
was enabled as part of misconfiguration discovered during
runtime.

z/TPF OMR updates for clean JVM Initialization II

---

compiler/runtime/Helpers.inc

m4 on zOS can not handle C/C++ style comments. This file is included in
a C++ header and a few m4 files so the copyright header needs to work
for both. Remove the copyright header while a solution is being found.
zOS assembler can not handle lines with more than 71 characters even in
comments. When a solution is found ensure that the length of each line
in the copyright header is a maximum of 71 characters.
[ci skip] since this is just removing a copyright header

Fix compilation issues on zOS

---

cmake/modules/OmrPlatform.cmake
cmake/modules/platform/os/zos.cmake
fvtest/porttest/CMakeLists.txt
omrsigcompat/CMakeLists.txt
util/a2e/CMakeLists.txt

OmrPlatform is meant to be re-includable. However, when we define
omr_shared in this module, this is no longer the case.
omr_shared was used to pass compile options needed to create shared
libraries. Any shared library in OMR would link privately against this
lib.
Instead, we introduce a new platform variable
OMR_PLATFORM_SHARED_COMPILE_OPTIONS
This variable contains the same set of compile options normally
inherited through omr_shared. All usages of omr_shared have been replace
with target_add_compile_options and this new variable.
Besides making OmrPlatform reincludable, this also makes shared compile
options more conventional.
/cc @dnakamura @mgaudet @charliegracie

Remove omr_shared

---

glue/configure_includes/configure_linux_ztpf_390.mk

Shut-off OMR_RTTI Configuration.  Mistmatch in z/TPF compilation lead
to an unresolve looking for an RTTI object.

Shut-off OMR_RTTI Configuration

---

fvtest/algotest/algoTest.cpp
fvtest/algotest/algorithm_test_internal.h
fvtest/algotest/avltest.c
fvtest/algotest/hashtabletest.c
fvtest/algotest/main.cpp
fvtest/algotest/pooltest.c
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/main.cpp
fvtest/gctest/main.cpp
fvtest/omrGtestGlue/omrTest.h
fvtest/porttest/main.cpp
fvtest/rastest/main.cpp
fvtest/sigtest/main.cpp
fvtest/threadextendedtest/threadExtendedTestMain.cpp
fvtest/threadtest/main.cpp
fvtest/tril/test/CMakeLists.txt
fvtest/tril/test/main.cpp
fvtest/utiltest/main.cpp
fvtest/vmtest/main.cpp

Cleanup hashtable, avl and pool testing to remove extra output
Add a new listener which prints less data
- Create a new TestEventListener which does not output as much data by
default as the default TestEventListener.  Make this new
TestEventListener the listener used by OMR testing.

Test output cleanup

---

cmake/modules/OmrMsvcRuntime.cmake
omrsigcompat/CMakeLists.txt

Move msvc runtime processing out into a new module.
Use the new module to set the CPP define in OMR sig.
This PR contains the omrsig/msvc patches originally in PR #1563. I'm moving this patch to a seperate PR because there are still issues with the compile options patches (which rely on this PR).
/cc @charliegracie @dnakamura 

Support more MSVC runtime versions

---

fvtest/algotest/pooltest.c

Older versions of msvc run with c89 support by default. The AppVeyor
builds run with c99 by default so this was not caught in the CI testing

Fix Windows compile issue

---

cmake/modules/OmrMsvcRuntime.cmake

The new file introduced by https://github.com/eclipse/omr/pull/1616 included the old license notice.

Update to current license notice

---

CMakeLists.txt
cmake/compiler_support.cmake
fvtest/CMakeLists.txt
fvtest/compilertest/CMakeLists.txt
fvtest/compilertriltest/CMakeLists.txt
fvtest/tril/README.md
fvtest/tril/examples/CMakeLists.txt
fvtest/tril/examples/incordec/CMakeLists.txt
fvtest/tril/examples/mandelbrot/CMakeLists.txt
fvtest/tril/test/CMakeLists.txt
fvtest/tril/tril/CMakeLists.txt
jitbuilder/CMakeLists.txt

This moves much of the include path requirements into the CMake
scoped variables system.
One of the side effects is the modification of make_compiler_target to
allow specifying a different scope.

Cleanup tril builds

---

fvtest/sigtest/sigTest.cpp

When compiling Linux 390 the size of sa_flags changes based which version of the C library you are using.  This causes some ugly code so instead I just always store the value into an int64_t and print that. This way there is not weird checks to decide the printf specifier.

Fix compiler warning in sigtest on Linux 390

---

README.md

Now that OpenJ9 is out, we should link to it in the README.

Link to OpenJ9 in the README

---

compiler/control/CompileMethod.cpp
compiler/ilgen/OMRIlGeneratorMethodDetails.hpp
compiler/ras/IlVerifier.hpp
compiler/ras/IlVerifierHelpers.hpp
fvtest/compilertest/ilgen/TestIlGeneratorMethodDetails.cpp
fvtest/compilertest/ilgen/TestIlGeneratorMethodDetails.hpp
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/SimplifierFoldAndTest.cpp
fvtest/tril/test/CompileTest.cpp
fvtest/tril/tril/jitbuilder_compiler.cpp
fvtest/tril/tril/jitbuilder_compiler.hpp
jitbuilder/ilgen/JBIlGeneratorMethodDetails.cpp
jitbuilder/ilgen/JBIlGeneratorMethodDetails.hpp

Enable other projects to use the IlVerifiers, and port one test case from compiler test to tril. 
This is WIP for review, and to allow a fix that requires the test to be disabled to land.

Hoist IlVerifier

---

fvtest/tril/test/ParserTest.cpp
fvtest/tril/tril/tril.l

There was an error in tril when trying to parse a large hex value (such as  0xFFFFFFFF00000000). This corrects that, and makes the parser test more robust.

Fix incorrect parsing of Int values

---

compiler/runtime/CodeMetaData.hpp
compiler/runtime/OMRCodeMetaData.cpp
compiler/runtime/OMRCodeMetaData.hpp

Create CodeMetaData class in OMR to keep track of runtime metadata 
related to a method, such as the code cache starting address and size, 
the interpreter entry PC, the compiled entry PC, the compiled end PC, 
and the compilation hotness level.

Create code metadata support

---

compiler/codegen/CodeGenRA.cpp
compiler/il/Aliases.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/ilgen/IlBuilder.cpp
compiler/optimizer/ExpressionsSimplification.hpp
compiler/optimizer/IsolatedStoreElimination.cpp
compiler/optimizer/LoadExtensions.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRLocalCSE.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OrderBlocks.cpp
compiler/optimizer/PrefetchInsertion.cpp
compiler/optimizer/RedundantAsyncCheckRemoval.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/SinkStores.cpp
compiler/ras/ILValidator.cpp
compiler/x/codegen/BinaryCommutativeAnalyser.cpp
compiler/x/codegen/BinaryEvaluator.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRMemoryReference.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp

This PR resolves a lot of the warnings of the following types:
`-Wpointer-arith compile warnings`
`-Wtautological-constant-out-of-range-compare`
`-Wlogical-op-parentheses`

Resolve more compiler warnings

---

gc/base/standard/Scavenger.cpp

Pick the cycle end TS at an earlier point, before Nursery resizing logic
is performed.

Scavenger end timestamp

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/x/codegen/OMRX86Instruction.cpp

feGetEnv is a common debug tool to disable or enable
behaviour based on environment variables. To avoid
significant compile time overhead, the result of the
call should be stored in a static.

Store feGetEnv results in statics

---

fvtest/compilertriltest/ShiftAndRotateTest.cpp

Correct type of sprintf for a tril test

---

gc/base/MemoryManager.cpp
gc/base/ModronAssertions.cpp
gc/base/ModronAssertions.h
gc/base/VirtualMemory.cpp

- The top heap address calculation should use aligned start address.
Otherwise a region aligned heap size might be shorter by region.
- Concurrent Scavenger code in Memory Manager should not step back by
tail padding as far as top address does not include it. tailpadding info
has been removed from Modron Assertion message
- Modron Assertions has been improved to work in startup time in case if
OMR VM Thread is not initialized. Tracepoint output should be skip in
this case.  
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Fixing heap top address calculation

---

compiler/control/OMROptions.cpp

`TR_HOST_Power` is arguably a typo for the correct host macro `TR_HOST_POWER`.
As nothing in Eclipse OMR nor any known downstream projects sets this incorrect
macro, replace it with the correct macro.
However, because the "wrong" path has been taken for such a long time I question
the value of providing a separate value just for Power and folded the setting of
this option into a single store for all architectures.

Remove unused TR_HOST_Power macro

---

fvtest/compilertriltest/SimplifierFoldAndTest.cpp

This test was disabled due to a parser error that has since been resolved in #1665

Enable the Tril SimplifierFoldAndTest

---

CONTRIBUTING.md

This matches the wording using the OpenJ9 project.
[skip ci]

Update commit message guidance to mention skipping ci

---

compiler/optimizer/PartialRedundancy.hpp

Fixes a warning from GCC
In file included from ../compiler/optimizer/Optimization.hpp:25:
../compiler/optimizer/OMROptimization.hpp:123:31: warning: inline function 'OMR::Optimization::trace' is not defined [-Wundefined-inline]
inline bool                trace();
^
../compiler/optimizer/PartialRedundancy.hpp:207:46: note: used here
bool trace() { return _partialRedundancy->trace(); }
^

Add missed _inlines header to PartialRedundancy.hpp

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/tril/tril/CMakeLists.txt

- Make tril find_package REQUIRED
- Fix -pthread warning while linking compiletest

CMake compiler fixes

---

omr/CMakeLists.txt
omr/OMR_VM.cpp

This fixes some issues in base9, where we want to use only jitbuilder, but OMR can't compile with the GC disabled.
/cc @dnakamura @youngar

GC: Don't use the GC in omrcore when OMR_GC is OFF

---

gc/base/VirtualMemory.cpp

Use unaligned address for heap start and tolerate the fact that heap
might be shorter by region in case of unfortunate alignment. Shorter by
region heap is allowed by logic.
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Revert back heap top calculation

---

gc/base/standard/ConcurrentCardTable.cpp

Corrects a type error flagged by AppleClang 9
Related issue is #1707.

Correct type error in GC

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/compile/VirtualGuard.cpp
compiler/compile/VirtualGuard.hpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/il/OMRNode.cpp
compiler/runtime/OMRRuntimeAssumptions.cpp
compiler/runtime/OMRRuntimeAssumptions.hpp
compiler/x/codegen/ControlFlowEvaluator.cpp

To lower the overhead for the breakpoint guard instruction sequence,
the guard is nopped when compiling a method and patched
only when a breakpoint is set for that method. This changeset contains
the code for adding a new runtime assumption for breakpoint guard

Add support for nopable breakpoint guard

---

compiler/optimizer/LocalOpts.cpp

When block splitter copies a merge block, it distributes some of the frequency of the original block to the copy, based on the proportion of the predecessors' total frequency belonging to the hot predecessor. A subsequent check raises the resulting frequency if necessary to ensure that it's no less than that of the predecessor, with a static debug counter suggesting that otherwise the frequencies would be inconsistent. However, when the predecessor branches, it's expected for the new block to be less frequent.
In particular, if the predecessor is in a loop not containing the merge block, the duplicate's frequency would be raised to match frequencies within the loop, interfering with proper layout of the loop.
This commit restricts the frequency adjustment to cases in which the predecessor …

Avoid inflating frequencies in block splitter

---

compiler/optimizer/LocalDeadStoreElimination.cpp

Local DSE will build up a list of stores to check
as it progresses through the block. Due to the
large number of dead stores in OSR blocks, this
can result in a significant compile time increase.

Ignore irrelevant stores in local DSE

---

compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.hpp

When adding an OSR guard, it is necessary to append
OSR blocks to the end of the CFG. The final treetop
is necessary for this, found by walking the entire
IL. Therefore, it is cheaper to maintain a pointer
to the last treetop through repeated OSR guard
insertions.

Cache CFG end for repeated OSR induce calls

---

compiler/optimizer/CompactLocals.cpp
compiler/optimizer/CompactLocals.hpp

CompactLocals frequently has to find the entry
in its interference graph for a live local index.
This was done with the interference graph's built
in hash table, however, this is expensive.
CompactLocals also had an array of symbols, indexed
by live local indices.
This change replaces the array with a vector of
interference graph nodes, allowing CompactLocals
to cheaply look up the interference graph node
for a live local index.

Use vector rather than hash table in CompactLocals

---

include_core/omrport.h

Important bits of OSX's pthread library are disabled when this symbol is
defined. This seems to be new behaviour as of xcode 9. This fixes many
compilation errors in the C++ standard library.
This fixes one of the compilation issues in #1707.

Do not define _XOPEN_SOURCE globally

---

port/linuxs390/omrrttime.s
port/linuxs39064/omrrttime.s
port/zos390/omrrttime.s
port/ztpf/omrrttime.s

The maxprec() routine that obtains current time on Z-plaforms
triggers fixed-point overflows if the PSW Fixed Point Oveflow mask
happens to be turned on. The reason for the overflow is that a subtract
operation used for calculating the current time mistakenly uses signed
rather than unsigned subtraction. The time value of the TOD-clock
(returned via STCK/STCKF instruction) will always be unsigned, so a
subtract logical instruction should be used instead of subtract - this 
would avoid Fixed-point Overflows.
The fix applies to z/OS, z/Linux and z/TPF platforms.
Signed-off-by: Deepthi Sebastian <deesebas@in.ibm.com>

Fix maxprec() call to avoid fixed-point overflows on Z

---

fvtest/sigtest/sigTest.cpp

This resolves issues with compiling on RHEL 6 and ensures that the format macros are available.
The single format macro used in this file is known not to exist on older version of visual studio so it is defined in this file.  I updated the check to only define the macro for Windows and zOS and cause an error on other platforms so that we can find platforms that do not provide these specifiers.

Fix compile failure related to PRId64

---

compiler/env/FEBase.hpp
compiler/runtime/CodeCacheManager.hpp
compiler/runtime/OMRCodeCacheManager.cpp
compiler/runtime/OMRCodeCacheManager.hpp
fvtest/compilertest/runtime/CodeCacheManager.hpp
fvtest/compilertest/runtime/TestCodeCacheManager.cpp
fvtest/compilertest/runtime/TestCodeCacheManager.hpp
jitbuilder/runtime/CodeCacheManager.hpp
jitbuilder/runtime/JBCodeCacheManager.cpp
jitbuilder/runtime/JBCodeCacheManager.hpp

- Modifies the CodeCacheManager constructor, adding a TR::RawAllocator
parameter and removing the TR_FrontEnd parameter.
- Uses the newly provided TR::RawAllocator when allocating and freeing
memory, moving the implementation to the OMR Layer.
- Removes the _fe field and the fe and pyfe methods
- Removes the static JitConfig field, as well as its getter method in
the test compiler and JitBuilder environments.
Resolves #1191 (JBCodeCacheManager should not define "pyfe()")

Refactor and clean up CodeCacheManager

---

compiler/control/OMROptions.cpp

We are changing the TOC size from 256KB back to the original 64KB in -Xquickstart mode in an effort to decrease footprint.
The default TOC size was changed from 64KB to 256KB in commit bdc1efa to help with performance in Liberty/Hadoop/Spark. However, since throughput is not very important in -Xquickstart mode, we can afford to revert back to 64KB in this mode. 
This change will decrease footprint.

Change TOC size from 256KB to 64KB in -Xquickstart mode

---

compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/codegen/X86Ops.hpp
compiler/x/codegen/X86Ops_inlines.hpp

X86 CodeGen now generates AVX instructions unless the machine does
not support AVX or environment variable TR_DisableAVX is set.

Enable AVX support on X86

---

compiler/x/runtime/VirtualGuardRuntime.cpp
compiler/x/runtime/X86Runtime.hpp

Migrated assembly utilities CompareAndSwap and PatchFence16 to intrinsics.

Convert CompareAndSwap and PatchFence to Intrinsics

---

compiler/codegen/StaticRelocation.hpp

The use of inttypes.h in StaticRelocation.hpp is not compatible with
many older versions of the Microsoft Visual C/C++ compiler. This commit
changes this to stdint.h which should be more portable without affecting
the implementation.

Fix compilation issue with older MSVC compilers

---

doc/compiler/runtime/CodeMetaData.md

Added documentation on the following:
1. Explains what CodeMetaData is and how it is used;
2. Discusses how CodeMetaDataManager manages the storage and lookup
of code metadata pointers efficiently with its underlying data
structures. Also talks about steps required to insert a metadata
pointer as an example and any nuances with locking in the existing
implementation.
[skip ci] documentation changes

Add documentation for runtime code metadata

---

jitbuilder/release/Makefile

Move the make dependencies for the ELF tests from ALL_TESTS to explicit
dependencies of experimental_goal.
This is required because entries in ALL_TESTS get built on all
platforms, even if they can't run on all platforms. However, the
distinction between 'building' and 'running' the ELF tests if fuzzy
enough that if a platform doesn't support running the test, it doesn't
support building it either.
Fixes #1748

Move ELF test make dependencies

---

compiler/z/codegen/OMRCodeGenerator.cpp

Modified function allowSplitWarmAndColdBlocks() to return true which sets the 
cold code length to 0. This ensures that the cold code paths are never taken. 
After testing with this change, it has been verified that everything works without 
the cold code paths. The cold code paths were then removed and  
allowSplitWarmAndColdBlocks() was reverted back to return false (such that any 
dependencies in openj9 may continue to use it normally, for now). 
[ci skip]

Remove cold code paths

---

compiler/optimizer/Inliner.cpp

HCR guards were not merged with other guards
in the OSR implementation of HCR to simplify the
analysis. This change enables the merging, to reduce
compile time overhead, as the analysis should now
support it.

Merge HCR guards in all HCR modes

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/ilgen/MethodBuilder.hpp
compiler/ilgen/TypeDictionary.hpp
compiler/infra/OMRCfg.cpp
compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/CopyPropagation.hpp
compiler/optimizer/DeadTreesElimination.cpp
compiler/optimizer/GlobalRegisterAllocator.hpp
compiler/optimizer/InductionVariable.hpp
compiler/optimizer/OMRLocalCSE.hpp
compiler/optimizer/RegisterCandidate.hpp

The allocator types were missing consts, however, only recently did
compilers start checking this (see #1707 for details).

Correct allocator types

---

gc/base/EnvironmentBase.hpp
gc/base/OMRVMThreadInterface.cpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/EnvironmentStandard.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Push any open GC copy caches to scan queue, and abandon unused parts:
1) for mutator threads (that created copy caches while copying in read
barrier), when requested heap walk in a middle of a CS cycle. 
2) at the end of first STW phase of CS
This will help with scan work created by GC threads that were involved
in this phase, but not involved in following concurrent phase (which
generally uses less GC threads). That work will be then completed during
concurrent phase, instead of waiting for those GC threads to be
re-activated at the final STW phase. 
This will also help with heap walkability (in a middle of a GC cycle).

Flush GC caches in Concurrent Scavenger

---

GNUmakefile

Convert unix to windows hook tool resources paths.
Issue: #1732 
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

Fix hook tool path for windows

---

compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/LoopVersioner.hpp

In order to identify appropriate expressions of induction variables (IVs) under `BNDCHK` nodes, loop versioner looks through loads of autos to their definitions (when there are unique definitions).  In this way a `BNDCHK` may be versioned even if no load of its IV feeds directly into the index.  For instance, the following `BNDCHK` can be versioned as long as `n` and `array` are invariant.
BBStart <loop0>
istore derived
isub
iload n
iload i
if... --> exit
BBEnd </loop0>
BBStart <loop1>
BNDCHK
arraylength
aload array
iload derived
...
istore i
isub
iload i
iconst -1
ificmple --> loop0
==>isub
iload n
BBEnd </loop1>
This commit fixes some problems with the versioning tests generated in cases like this one:
1. Substitution into the third test sometimes used the IV instead of the substituted …

Fix BNDCHK versioning tests under substitution

---

CMakeLists.txt
omrsigcompat/CMakeLists.txt
tools/hookgen/CMakeLists.txt
tools/tracegen/CMakeLists.txt
tools/tracemerge/CMakeLists.txt

At the moment only installs tooling and omrsig (only the minimum required
for building openJ9).

CMake: Add basic support for installing targets

---

compiler/env/DebugSegmentProvider.cpp
include_core/omrport.h
port/unix/omrsysinfo.c
port/ztpf/omrsignal_context.c
port/ztpf/safe_storage.h
thread/unix/omrthreadattr.c

z/TPF fixes during initial sniff testing.  Fixes unresolved functions.
Fixes High Resolution Timer defines.  Modified setstacksize to match 
z/TPF architecture.

z/TPF Fixes during initial sniff testing.

---

compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/RegisterCandidate.cpp
compiler/optimizer/RegisterCandidate.hpp

These changes reduce the compile time overhead of GlobalRegisterAllocator.
It includes the removal of a check that was no longer being used and a fix to
GRAs behaviour when identifying overlapping allocations.
The most significant change converts loops in GRA's setup into BitVector
operations. This was enabled by recent memory improvements, which allow
a RegisterCandidate's BlockInfo to specify interested blocks with a weight
of 0 using a BitVector, rather than adding new map entries. With this,
all concerns could be represented as BitVectors of block numbers, except
for GlobalSet, which had to be pivoted from BitVectors of symbol reference
numbers to match the others.

Improvements to GRA compile time

---

compiler/env/FEBase.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/env/OMRCPU.cpp
compiler/x/env/OMRCPU.hpp

1. X86 CodeGen now properly checks testOSForSSESupport() from target.cpu.
2. Unused redundant helpers related to SSE check are deleted.

Cleanup logics related to SSE availability check 

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRMachine.hpp
compiler/z/codegen/OMRRegisterDependency.cpp
compiler/z/codegen/OMRRegisterDependency.hpp

The previous implementation of codegen checkDependencyGroup() performs
unnecessary checks. This change simplifies the original one but still
keeps the O(n^2) algorithm.

Simplify checkDependencyGroup to reduce compile time

---

gc/CMakeLists.txt
util/omrutil/CMakeLists.txt

A couple of small fixes.
- Remove `project(libomrgc ....)`
- Remove typo in `omrutil`

CMake: small fixes

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp
compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

This is a set of changes to reduce OSRLiveRangeAnalysis overhead, mostly focused on skipping the analysis where possible. It consists of:
- When calculating liveness at a treetop level, skip blocks that contain no OSR points
- Remove allocations, left over from disabled sections of the analysis
- Add a missing option to disable the analysis
- Skip the analysis for bodies that don't contain OSR points at all
- Skip the analysis for bodies that don't have symbols that require it
- Add the option to solve pending push liveness in IlGen

Reduce OSRLiveRangeAnalysis overhead

---

compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

Once OSR infrastructure has been removed, OSR
transitions can no longer be added. Therefore, it
is simple to identify stack slots that are dead
at all transition points, reducing the number of
loads and dead stores, cutting compile time.

Zero OSR loads that are dead on all paths

---

compiler/optimizer/OMRSimplifierHandlers.cpp

Opcode butest is not supported on X and P, thus optimizer should not
generate butest node on these two platforms.
issue: #1789

Stop generating butest node on X and P

---

omrsigcompat/omrsig_internal.hpp
port/ztpf/omrsignal_context.h

Signal Number validation fails for z/TPF because NSIG has
a slightly different use in z/TPF.

z/TPF update to NSIG for validSignalNum

---

compiler/il/AliasSetInterface.hpp
compiler/optimizer/DataFlowAnalysis.hpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/ReachingDefinitions.cpp
compiler/optimizer/UseDefInfo.cpp
compiler/optimizer/UseDefInfo.hpp

This contains a series of changes to reduce the compile time overhead of UseDef and the AliasSetInterface.
- Replace use of TR_BitContainer with TR_BitVector, as only the Node interface used the extra functionality
- Add TR_BitVector calls to the AliasSetInterface, matching existing CS2 BitVector functionality
- Replace CS2 BitVectors with TR_BitVector in ReachingDefinitions, OSRDefInfo and UseDefInfo's `_defsForSymbol`
- Add a reusable checklist to UseDefInfo
- Remove `nodesByGlobalIndex` for UseDefInfo, as it is no longer needed
- Replace the use of a HashTable to express several calls to the AliasSetInterface with the individual calls
- Rearrange and cache `isTrivialUseDefNode`, as its results are constant throughout the analysis

UseDef and AliasSet Compile Time Improvements

---

compiler/optimizer/OMROptimizer.cpp
jitbuilder/optimizer/JBOptimizer.cpp

1. Created a (trivial) inliner entry in the optimization table.
2. Added inlining in the JitBuilder's warm strategy.

Enable trivial inliner in OMR

---

gc/base/Forge.cpp
gc/base/Forge.hpp
gc/base/GCExtensionsBase.cpp

* Do not take an environment in initialize/shutdown. The forge is
typically initialized before any environments are attached.
* Wrap the forge in the OMR namespace. Provide a backwards compatible
typedef. Do not put MemoryStatistic or AllocationCategory inside the
OMR namespace just yet, they are used in C code.
* Provide a set of new/delete operators for wrapping forge allocations.
Now you can pass the forge as a parameter of the new operator. This
should simplify the newInstance idiom used throughout the GC.
/cc @youngar @charliegracie @ktbriggs

GC: Update the GC Forge Allocator API

---

fvtest/compilertriltest/ShiftAndRotateTest.cpp

Shifting a 32 bit integer by more than 31 bits is undefined behaviour in
the C++ spec. Currently the OMR compiler  masks the shift value by 0x1F.
This means a shift of 32 or larger on a 32 bit integer effectively
returns the same value. To ensure the C++ version matches the compiled
version of the test the C++ version needs to also mask the shift value.

Fix comptest failures on Linux 390

---

.travis.yml

Brew is not very smart. When we install ccache, brew will auto update
first, installing ruby 2.3. Unfortunately, the install will require the
new ruby, but will run with the old ruby brew used to upgrade. So now,
we need to update brew before running any other commands. This is a new
issue with brew.
This patch will fix all the brew-related osx travis failures we are
seeing across the board.

Upgrade brew before using it

---

fvtest/compilertriltest/ShiftAndRotateTest.cpp

Until Issue #1804 is resolved this test needs to be disabled. Disabling
the test right now allows the rest of the comptest to be run ensuring we
do not regress any other subtests while the Issue is being investigated.

Disable Int16ShiftAndRotate/UsingLoadParam on Power

---

gc/base/ParallelHeapWalker.cpp
gc/base/ParallelHeapWalker.hpp
gc/base/standard/Scavenger.cpp

Handle a special case of aborted Concurrent Scavenger when Remembered
Set is in overflow. This is not much different from handling it when RS
is not overflowed - we just clear RS. All heap fixup (restoring
references to forwarded objects and self-forwarded objects) occurs in
the following global GC and fixup hook.
Also, fixign a bug in Parallel Heap Walker that was ignoring walk flags.

Aborted CS and RS overflow

---

compiler/compile/CompilationException.hpp
compiler/compile/OMRCompilation.cpp
compiler/infra/Assert.cpp
compiler/runtime/CodeCacheExceptions.hpp

Addresses https://github.com/eclipse/omr/issues/1726. This PR also includes some minor cleanup, namely using the `TR::Compilation::failCompilation` method instead of explicitly throwing an exception.

Document Exception Semantics

---

jitbuilder/CMakeLists.txt

JitBuilder requires 2 defines which were not being set and the
compilation was missing a file for Linux P.

Improve CMake JitBuilder support for Linux P

---

CMakeLists.txt

CMake support is no longer in the experimental stage, so remove warning.

CMake: Remove experimental warning

---

fvtest/compilertest/CMakeLists.txt

This commit makes it possible to have a cmake based build
for the Test Compiler on zLinux_s390x.

Support for building Test Compiler on s390x using CMake

---

jitbuilder/release/src/LinkedList.cpp

Currently this test outputs a lot of information to the console when it
works correctly. Only print information when there is a failure. Also a
DEBUG_OUTPUT compile time flag as added to re-enable some of the more
verbose output to aid in debugging. 

Quiet output from LinkedList test

---

compiler/x/runtime/X86Runtime.hpp

A memory fence need be applied when applying patching fence.

Fix for missing memory fence

---

example/glue/CMakeLists.txt
example/glue/CollectorLanguageInterfaceImpl.cpp
example/glue/CollectorLanguageInterfaceImpl.hpp
example/glue/ConcurrentMarkingDelegate.cpp
example/glue/ConcurrentMarkingDelegate.hpp
gc/base/Collector.hpp
gc/base/CollectorLanguageInterface.hpp
gc/base/ConcurrentSafepointCallback.hpp
gc/base/GlobalCollector.hpp
gc/base/MarkingScheme.cpp
gc/base/MarkingScheme.hpp
gc/base/segregated/ConfigurationSegregated.cpp
gc/base/segregated/SegregatedGC.cpp
gc/base/segregated/SegregatedGC.hpp
gc/base/standard/ConcurrentCardTable.cpp
gc/base/standard/ConcurrentCardTable.hpp
gc/base/standard/ConcurrentCardTableForWC.cpp
gc/base/standard/ConcurrentGC.cpp
gc/base/standard/ConcurrentGC.hpp
gc/base/standard/ConcurrentSafepointCallback.cpp
gc/base/standard/ConcurrentSweepScheme.cpp
gc/base/standard/ConfigurationGenerational.cpp
gc/base/standard/ConfigurationStandard.cpp
gc/base/standard/EnvironmentStandard.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/ParallelGlobalGC.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
glue/CollectorLanguageInterfaceImpl.cpp
glue/CollectorLanguageInterfaceImpl.hpp

Extract concurrent collector marking delegate
(MM_ConcurrentMarkingDelegate)
from deprecated collector language interface 
(MM_CollectorLanguageInterface*).
Structures and methods extracted:
(MM_CollectorLanguageInterface -> MM_ConcurrentGC)
```
_concurrentStats -> _stats
```
(MM_CollectorLanguageInterface -> MM_ConcurrentMarkingDelegate)
```
concurrentGC_processItem()
-> processItem()
concurrentGC_createSafepointCallback()
-> createSafepointCallback()
concurrentGC_getProtectedSignalHandler()
-> getProtectedSignalHandler()
concurrentGC_concurrentInitializationComplete()
-> concurrentInitializationComplete()
concurrentGC_forceConcurrentKickoff()
-> *canForceConcurrentKickoff()*
concurrentGC_getNextTracingMode()
-> getNextTracingMode()
concurrentGC_collectRoots()
-> collectRoots() …
```

Extract concurrent GC delegate from CLI

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlValue.cpp

We added more strenuous assertions when looking up symbol names
by slot number and that exposed a number of problems logging
JitBuilder compiles because there are a few places where we
did not register the symbol name after creating a new local slot.
Apparently, we never tested the new assertions while logging.
Spots fixed by this commit:
1) CreateLocalArray
2) CreateLocalStruct
3) Copy
4) IlValue when it stores a value needed in another block

Fix slot assertions logging JitBuilder compiles

---

.travis.yml

Simplify the yml file and speed up the OS X builds slightly but not
using the Ninja generator.

Switch OS X to use Unix Makefiles

---

gc/base/standard/ConcurrentCardTableForWC.cpp
gc/base/standard/ConcurrentCardTableForWC.hpp

Fix OSX compilation issue. Replace MM_EnvironmentStandard with
MM_EnvironmentBase everywhere in MM_ConcurrentCardTableForWC as for
base class MM_ConcurrentCardTable.

Extract concurrent GC delegate from CLI (fix osx compile)

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp

As part of the work to relocate the management of the `TR::Instruction`
pointers from the Compilation object to the CodeGenerator, introduce
the same functions in the code generator that simply call their
counterparts in the Compilation object.
This is only to help stage the transition effort in OMR and all
known downstream projects.  The appropriate instruction fields
will be moved into the CodeGenerator once all callsites have been
updated.

Bridge work to move instruction pointers to CodeGenerator

---

compiler/arm/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenPhase.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/runtime/OMRCodeMetaData.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

* Remove deprecated estimated cold code functions
* Remove deprecated cold code start functions
* Remove and fold deprecated getColdCodeLength
* Rename deprecated EstimatedWarmLength functions
* Rename deprecated WarmCodeEnd functions
* Rename deprecated WarmCodeLength functions
* Remove unused IsInWarmCodeCache CodeGenerator flag and functions

Remove CodeGenerator notion of warm/cold areas of a method

---

port/ztpf/omrintrospect.c
thread/unix/thrdsup.c

Prevent suspending native stack walk threads for z/TPF.
In addition, call special z/TPF thread initialization routines.

Prevent suspending native stack walk threads for z/TPF.

---

compiler/il/OMRNode_inlines.hpp

This avoids the peculiar double-negative construction of
if (not has no data type)

Reverse logic in getDataType

---

fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/JitTestUtilitiesTest.cpp
fvtest/tril/examples/mandelbrot/main.cpp
fvtest/tril/test/ASTTest.cpp
fvtest/tril/test/CompileTest.cpp
fvtest/tril/test/IlGenTest.cpp
fvtest/tril/test/MethodInfoTest.cpp
fvtest/tril/test/ParserTest.cpp
fvtest/tril/tril/ast.cpp
fvtest/tril/tril/ast.hpp
fvtest/tril/tril/enable_if.hpp
fvtest/tril/tril/ilgen.cpp
fvtest/tril/tril/ilgen.hpp
fvtest/tril/tril/jitbuilder_compiler.cpp
fvtest/tril/tril/method_compiler.hpp
fvtest/tril/tril/method_info.hpp

There was some desire to use Tril in contexts where the compiler may not have full C++11 support.
This adds that support to tril and it's accompanying examples, while still retaining some of the C++11 only code (by guarding them with appropriate macros).

Downgrade Tril's minimum compiler version

---

compiler/ilgen/MethodBuilder.cpp

There are cases when the code generate manufactures a symbol reference
and cannot assign an appropriate cpIndex (e.g. converting an indirect
access to a stack allocated array or object into a "more" direct access
via the stack pointer). In these cases, if the JIT is logging its
output, the JIT will ask MethodBuilder for the name of a symbol at
slot -1 which naturally causes an assertion. This commit returns
the name "Unknown" for slot -1 because this assertion only occurs
during JIT logging and it's usually better to allow the logging
to continue than to abort prematurely just because such a symbol
was created and logged.

Fix abort during JitBuilder compile logging

---

compiler/il/ILOpCodeProperties.hpp
compiler/ras/ILValidator.cpp
fvtest/compilertriltest/ILValidatorTest.cpp

~This has a knock on effect, requiring the addition of extra conversions
in some test cases, as well as some new tests for the validator.~
Validate the child types of ireturn

Validate ireturn child types

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/VectorTest.cpp
fvtest/tril/tril/compiler_util.hpp
fvtest/tril/tril/ilgen.cpp
fvtest/tril/tril/method_info.hpp

Allow writing tests using some vector constructs in Tril
The changes allow one to write a tril test case such as 
(method return="NoType" args=[Address,Address,Address] 
(block 
(vstorei type=VectorDouble offset=0 
(aload parm=0) 
(vadd 
(vloadi type=VectorDouble (aload parm=0))
(vloadi type=VectorDouble (aload parm=1))))
(return)))

Add Vector test support to Tril

---

compiler/x/i386/codegen/TreeEvaluatorTable.hpp

TreeEvaluatorTable.hpp was updated to include SIMDRegLoad and SIMDRegStore
evaluators. The evaluators already existed for use with amd64. The
evaluators were already compatible with i386 so they only needed to be
added to TreeEvaluatorTable so they would be used.
Issue: #1917

Added SIMD Evaluators to i386 TreeEvaluatorTable

---

CMakeLists.txt
cmake/modules/OmrCompilerSupport.cmake
fvtest/compilertest/CMakeLists.txt
jitbuilder/CMakeLists.txt

Variable is not needed as cmake gives us omr_SOURCE_DIR with the same
contents.

Remove OMR_ROOT

---

fvtest/compilertest/CMakeLists.txt
fvtest/compilertest/Jit.hpp
fvtest/compilertriltest/ArithmeticTest.cpp
fvtest/compilertriltest/ILValidatorTest.cpp
fvtest/compilertriltest/IfxcmpgeReductionTest.cpp
fvtest/compilertriltest/ShiftAndRotateTest.cpp
fvtest/compilertriltest/SimplifierFoldAndTest.cpp
fvtest/compilertriltest/VectorTest.cpp
fvtest/tril/examples/incordec/main.cpp
fvtest/tril/examples/mandelbrot/main.cpp
fvtest/tril/test/CompileTest.cpp
fvtest/tril/test/JitTest.hpp
fvtest/tril/tril/CMakeLists.txt
fvtest/tril/tril/default_compiler.hpp
fvtest/tril/tril/simple_compiler.cpp
fvtest/tril/tril/simple_compiler.hpp

An implementation for #1688 
Notes I'd like to call out: 
* ~This adds a header to the root of the compiler directory, called `Jit.hpp`, that mirrors the one in `jitbuilder/release/include`. This is a **controversial decision** as we've no had headers at that level before. The header exports a simple interface that I think most compilers might be able to meet, _but_ OpenJ9 may be a challenge.~
* Changes from `JitBuilderCompiler`, to `DefaultCompiler`, but interestingly, since both the test compiler and JitBuilder can meet the `Jit.hpp` interface, this allows us to create a concrete backend that's shared called `SimpleCompiler.` To use Tril with another backend one could connect up that backend by modifying Default.hpp.

Use Test Compiler as a Tril Backend

---

compiler/compile/OMRCompilation.cpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/RegDepCopyRemoval.cpp
compiler/optimizer/RegisterCandidate.cpp

A node should be responsible for answering whether it requires a register
pair or not.
Move the functionality to the Node class, rename the function to
`requiresRegisterPair`, and add some documentation.
Redirect the Compilation query to the Node query to allow downstream
projects to complete refactoring.  The Compilation shim will be removed
when this has been completed in all known downstream projects.

Migrate nodeNeeds2Regs from Compilation to Node

---

compiler/optimizer/RedundantAsyncCheckRemoval.cpp
compiler/x/codegen/OMRCodeGenerator.cpp

In Java9 sun.misc.Unsafe JNI methods are moved to jdk.internal and
replaced with simple wrappers. This leads to a few places in the
code where we do the wrong thing by assuming that the recognized
Unsafe method is a JNI method.
This commit adds explicit tests to differentiate between the JNI
methods and the non-JNI wrappers.

Allow for non-JNI Unsafe methods

---

compiler/compile/OMRSymbolReferenceTable.hpp

lloadi opcodes are also supported now so this is reflected in the
documentation.
[ci-skip] Documentation only.

Improve synchronizedFieldLoadSymbol documentation

---

fvtest/compilertriltest/ArithmeticTest.cpp
fvtest/compilertriltest/IfxcmpgeReductionTest.cpp
fvtest/compilertriltest/JitTest.hpp
fvtest/compilertriltest/JitTestUtilitiesTest.cpp
fvtest/compilertriltest/OpCodeTest.hpp
fvtest/compilertriltest/ShiftAndRotateTest.cpp
fvtest/compilertriltest/SimplifierFoldAndTest.cpp
fvtest/tril/tril/compiler_util.hpp

This commit lowers the minimum compiler version required to
run the compiler tests built using Tril, to at least as far
as GCC 4.4.6. Essentially not requiring full C++11 support.
Related to PR #1718 
Fixes #1697

Downgrade minimum compiler version for Compiler Tril Tests

---

include_core/omrcomp.h
util/hookable/hookable.cpp

J9CONST_TABLE is defined in OMR to be 'const' and only exists for
historical reasons. This makes the code clearer and move obvious
about what is occuring.
This is a mechanical conversion from J9CONST_TABLE -> const.

Replace 'J9CONST_TABLE' with 'const'

---

example/glue/CollectorLanguageInterfaceImpl.cpp
example/glue/CollectorLanguageInterfaceImpl.hpp
example/glue/CompactDelegate.hpp
gc/base/CollectorLanguageInterface.hpp
gc/base/standard/CompactScheme.cpp
gc/base/standard/CompactScheme.hpp
glue/CollectorLanguageInterfaceImpl.cpp
glue/CollectorLanguageInterfaceImpl.hpp

Refactor MM_CollectorLanguageInterface (CLI) methods into a new
MM_CompactingDelegate (CD) class.
Reviewer: @ktbriggs

Add CompactScheme delegate to Example/glue

---

compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/Structure.cpp
compiler/optimizer/Structure.hpp

Upon entry into a loop, a very low frequency check may not run at all before control exits the loop. If a check isn't going to run, the loop can complete normally even if that check would fail. As a result, versioning the check is likely to spuriously send execution to the cold loop. Furthermore, there is little benefit to be had from removing a check that seldom runs. For these reasons, versioner tries to avoid versioning "unimportant" checks.
Unimportant checks have so far been identified based on the frequency ratio between the check and the header of the loop under consideration. But this can cause an inconsistency when an outer loop contains an inner loop that contains a check, and the check is invariant w.r.t. to the outer loop.
If the inner loop iterates more frequently than the …

Stop versioning unimportant checks in outer loops

---

fvtest/tril/tril/ast.cpp
fvtest/tril/tril/ast.h

- Correct defaulting to stdout in some places.
- Add printTreesToStdErr to support calling in a
debugger that may not have a good definition for
stderr or stdout

Small fixes and additions to Tril printing routines

---

fvtest/compilertriltest/ILValidatorTest.cpp
fvtest/tril/tril/tril.l

* Correct parsing function so that it will work on a 32 bit platform that has `unsigned long` be 32 bits.
* Correct typo in test case name.

Small corrections to Tril

---

compiler/control/OMROptions.cpp

Full speed debug compilations, implemented
using MimicInterpreterFrameShape, must use
the no-opt optimization level. Therefore,
they do not support recompilations.
This change disables recompilations for
any methods compiled in such a configuration.

Disable recomp in MimicInterpreterFrameShape

---

gc/include/omrgc.h
gc/startup/omrgcalloc.cpp

C interface as presented included a C++ artifact in a function parameter
list. The C++ function is now wrapped in a method that has an acceptable
C parameter list.
omrgc.h is a C header file and should not have included the forward
class declaration or included it in a function parameter list (my bad). 
However, I have left it in the omrgc.h header file, enclosed with `#ifdef 
__cplusplus` for backwards compatibility. AFAIK only GCConfigTest.cpp
uses the C++ interface for this method, within OMR.
Issue: #1957

Fix C interface issues in omrgc.h

---

fvtest/compilertriltest/CMakeLists.txt

Somehow the CMAKE_ prefix was lost on the CMAKE_CXX_EXTENSIONS variable,
and subsequently CMake defaulted to extensions on, rather than off.
Thanks to @dnakamura for spotting this.

Restore CMAKE_ prefix on CXX_EXTENSIONS support var

---

gc/include/omrgc.h

Remove default value for `objectAllocationFlags` in `OMR_GC_AllocateObject`.
Default values for function parameters are a C++ feature and don't exist
in C.
Signed-off-by: Paavo Parkkinen <pparkkin@gmail.com>

Remove default value for `objectAllocationFlags`

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/CallTest.cpp
fvtest/tril/tril/compiler_util.hpp
fvtest/tril/tril/ilgen.cpp
fvtest/tril/tril/method_info.hpp

This adds support for creating calls from Tril code to externally defined functions. 
~Currently WIP because the patch as presented is dependent on #1858 being merged first, as it's the PR that contains 0ae512e~

Preliminary Call Support in Tril

---

scripts/commit-msg

Commit Guidelines state that first line of the commit can have
70 characters but commit-msg script only allows 50.
Fixed the commit-msg script to use 70 char limit.
[skip ci]

Update commit-msg script to use 70 chars as the limit for first line

---

.travis.yml
scripts/build-on-travis.sh

These tests take up to 10s of minutes when running on the OS X CI
machines which causes the tests to fail. When running locally
these tests on take seconds. This disables the tests from the
OS X CI until we can resolve the issue.

Disable *Death*Tests for OS X CI testing

---

compiler/optimizer/OMRSimplifierHandlers.cpp

As noted in Issue #1856, this ENABLE_STRUCTS code was part of a now
removed experiment, and can in turn be removed
Issue: #1856
Signed-off-by: William Smith <will.smith@uk.ibm.com>

Remove unused code from obselete ENABLE_STRUCTS experiment

---

compiler/codegen/OMRCodeGenerator.hpp

Removed unused and non-implemented declared function armAllocate
from CodeGenerator.
Closes: #1884
Signed-off-by: Kabir Islam <kaislam1@in.ibm.com>

Removed unused function armAllocate

---

fvtest/omrGtestGlue/omrTest.h

Sometimes when debugging a test case it's extremely valuable to see
the complete Google Test output. This change allows restoring that
behaviour under an environment variable OMR_VERBOSE_TEST.

Allow restoring default Google Test output

---

cmake/modules/OmrHookgen.cmake
fvtest/algotest/CMakeLists.txt
gc/CMakeLists.txt

Modify the hookgen handling to allow generating files outside of the
source tree. This is not trivial since the output files are specified
as a relative path in the .hdf file (which are relative to the .hdf).
To work arround this omr_add_hookgen, reads in the .hdf file, identifies
the output header names, rewrites them as relative path (relative to
the current binary dir), and then outputs the modified hdf into
CMAKE_CURRENT_BINARY_DIR, and runs hookgen on that. This allows us to
generate the hookgen files in the build tree, without making any changes
which would likely break the existing autconf/makefile builds.
Signed-off-by: Devin Nakamura <dnakamura@ca.ibm.com>

CMake: Allow out-of-tree hookgen

---

compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/FPTreeEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OpMemToMem.cpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/S390GenerateInstructions.hpp
compiler/z/codegen/S390Instruction.hpp

Splitting the generateRILInstruction() API to handle the different
types of immediates that RIL instructions can take separately.
One kind is a pure immediate which is used for say an ADD
instruction. The other is when the immediate is used as a relative
offset for address calculation like LARL or BRASL instructions.
This allows calls to the API to have more sensible casting.
They are modified for this change and unsafe casting is switched
to static casting and some code has its style improved.
Signed-off-by: Simon Hirst <shirst@ca.ibm.com>

Fix casting issues in generateRILInstruction() API

---

compiler/optimizer/VPHandlers.cpp

VPHandlers.cpp - rename swap() to VPHswap() as z/TPF already has an
opensource swap() function in our libstdc++ library.
TypedAllocator.hpp - compiler couldn't find a matching matching function
for call to "construct()".
Signed-off-by: pete lemieszewski <lemie@us.ibm.com>

OMR updates to address z/TPF build errors

---

compiler/infra/ILWalk.cpp
compiler/infra/ILWalk.hpp

Implement an iterator which traverses extended basic blocks in a
treetop ordering, where treetop order means the order in which the
extended basic blocks appear in a trace log file.

Implement a treetop order extended block iterator

---

CONTRIBUTING.md

Modify the Contribution Guidelines to encourage the use of a Closing tag
when merging the final commit that completely addresses an issue.  This
will cause the issue to automatically close.
[ci skip]

Encourage the use of issue closing tags

---

compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/S390Instruction.cpp
compiler/z/codegen/S390Instruction.hpp
fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/LongAndAsRotateTest.cpp

-Rename the function to tryToReplaceLongAndWithRotateInstruction
as this is more descriptive
-Clean up the function to avoid skipping the evaluation of i2l
and iu2l nodes. This should be handled by the simplifier (and
it currently is). Also, insert a static debug counter to catch
potential opportunities in the future.
-Add asserts during binary encoding and instruction construction
to make sure the reserved bits in the instruction's operands are
not being set. This is a source of printing errors in trace logs.
-Test the function using tril + google tests

Clean up genericLongAndAsRotateHelper

---

compiler/z/codegen/S390Instruction.hpp

A call to getOpCode().getMnemonicName() was recently added but
it is not implemented in z codegen. This is causing problems
building omr on z. This commit fixes this by calling the
correct API.
Signed-off-by: Simon Hirst <shirst@ca.ibm.com>

Make correct call to getOpCodeName in z codegen

---

gc/base/MemoryPoolAddressOrderedList.cpp
gc/base/MemoryPoolSplitAddressOrderedListBase.cpp

On Global GCs reset _lastFreeEntry (to point to NULL) when AOL pool is
reset. The only user of this info is aborted GC handling in Concurrent
Scavenger, which will always be set this through compaction step that is
done as a part of Percolate GGC (in CS world). Still, for cleanness and
for future changes (if/when compaction is made an optional part of
Percolate GGC), this is correct to reset.

Reset lastFreeEntry

---

compiler/optimizer/CopyPropagation.cpp

Copy propagation is exclusively enabled by default in the warm strategy
on IBM Z targets. It is quite a compile time hungry optimization. One
of the reasons as to why can be attributed to its use of use-def
analysis.
The optimization calls `getUsesFromDef` quite frequently which ends up
boiling down to a call to `TR_UseDefInfo::getUsesFromDef_ref`. In this
function we would always take the `else` path because the use-def
information has not been computed. This is an expensive task.
An optimization we can make here is the pre-compute the use-def info
ahead of time and avoid the expensive on-demand computation.

Improve compile time performance of copy propagation

---

compiler/il/ILOpCodeProperties.hpp
compiler/il/OMRILOpCodesEnum.hpp

These commits allow the ILValidator to correctly check `branch` opcodes.
Fixes #1553

Make ILvalidator handle tstart correctly

---

fvtest/compilertriltest/CMakeLists.txt

Use the fact that linking against tril is going to set the correct flags
instead.

Correct CompilerTrilTest build flags

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/MockStrategyTest.cpp
fvtest/compilertriltest/SharedVerifiers.hpp
jitbuilder/optimizer/JBOptimizer.cpp
jitbuilder/optimizer/JBOptimizer.hpp

Previously by providing it's own optimizer strategy selection, JitBuilder ended up bypassing the mock optimizer support. 
This PR changes the way the JitBuilder chooses it's strategies, and adds a test for Mock optimization strategy support.

Correct JitBuilder's optimizer strategy selection

---

compiler/z/codegen/BinaryEvaluator.cpp

Correct spelling of "division".

Corrective division

---

compiler/codegen/ELFObjectFileGenerator.cpp

Minor update to assist z/TPF platorm in compiling 
ELFObjectFileGenerator.cpp 

Fix z/TPF unique build error for ELFObjectFileGenerator.cpp

---

compiler/compile/OMRAliasBuilder.cpp
compiler/compile/OMRAliasBuilder.hpp
compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/env/OMRClassEnv.cpp
compiler/env/OMRClassEnv.hpp
compiler/env/OMRKnownObjectTable.cpp
compiler/env/OMRKnownObjectTable.hpp
compiler/env/OMRObjectModel.cpp
compiler/env/OMRObjectModel.hpp
compiler/il/Aliases.cpp
compiler/optimizer/VPConstraint.cpp
compiler/optimizer/VPConstraint.hpp
compiler/optimizer/VPHandlers.cpp
compiler/ras/Debug.cpp

If we know an array is not going to be changed nor is its content, we
can fold the load of its element. This is done by adding a bit in
KnownObjectTable to indicate whether a known object is an array with
immutable content. When VP sees an array shadow load from such array,
it will improve the array shadow to an ImmutableArrayShadow, a new
symbol added for this optimzation, and ask transformIndirectLoadChain
to fold it. ImmutableArrayShadow is also served as an indicator to
transformIndirectLoadChain that it is safe to fold an array shadow with
such symbol.

Support folding immutable array shadows

---

compiler/optimizer/DeadTreesElimination.cpp
compiler/optimizer/Structure.cpp

Update two places where we're creating an allocator that allocates the wrong type. On recent mac OS versions, this fixes a compilation failure.

The std::map value pairs have const keys

---

compiler/z/codegen/OMRTreeEvaluator.cpp

Unsigned comparison nodes such as ifbucmpgt can be
evaluated incorrectly if the data type of the second
child is LoadConstant and 8 or 16 bits. We generate a
signed comparison instruction instead of an unsigned
instruction. This commit fixes that by correctly generating
an unsigned comparison instruction if the comparison node
is also unsigned.
Closes: #1943

Fix Compare and Branch helper for unsigned comparisons

---

fvtest/compilertriltest/ShiftAndRotateTest.cpp

These tests fail on s390x due to the missing conversions before `ireturn`.
The choice of doing a `signed` vs `unsigned` widening is based off of how the oracle is set up right now. From where our IL stands today, `ireturn` has no way of deciphering whether the left child of the `*shr` OpCode (which conventionally would dictate the signedness of the resulting shift) was signed or unsigned to begin with. So the “right choice” here, is to mimic how the oracle interprets the resulting bits while producing its result.
Something to keep mind, in this instance (and for future tests similar to this), the goal is to validate whether the associated Opcode (`*shr` in this case) behaves as expected. `ireturn` and the said conversion before it, are just part of "extracting the computed result”. So the …

Correct ireturn child types in ShiftAndRotate tests

---

compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp

Migrate the function from the FrontEnd to the x86 CodeGenerator and
simplify its API.
Also, modify the one use of `reserveNTrampolines` to use the CodeGenerator
version.

Move reserveNTrampolines to x86 CodeGenerator

---

compiler/env/TRMemory.cpp
compiler/env/TRMemory.hpp
compiler/runtime/OMRRuntimeAssumptions.cpp
compiler/runtime/OMRRuntimeAssumptions.hpp

Runtime assumptions incur a persistent memory
and runtime overhead. It is possible for assumptions
to require several patch sites in a method for the same
event. It is also possible for several events to require
the same set of patch sites.
This adds a runtime assumption capable of representing
such a situation with reduced overhead, by creating
a shared collection of patch sites.

Add runtime assumption with multiple patch sites

---

compiler/optimizer/OSRDefAnalysis.cpp

When finding the killing or gening symbols, the maintainLiveness
function should get the parm symbols in addition to auto symbols.

Fix OSR liveness to include parms

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/LogicalTest.cpp
fvtest/compilertriltest/OpCodeTest.hpp

New test cases for unary opcodes `iabs` and `ineg`.

Adding new Test cases to Tril

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp

This function was deprecated by e6d4b6e3c4d4d1d6e7fd5c4e708c195b24026212 and
cleaned up in all known downstream projects.

Remove deprecated OMR::Compilation::nodeNeeds2Regs()

---

jitbuilder/linter.mk
jitbuilder/runtime/CodeCacheManager.hpp
jitbuilder/runtime/JBCodeCacheManager.cpp

This commit adds the makefile required to run the linter on JitBuilder.

Support running the linter on JitBuilder

---

fvtest/compilertriltest/CMakeLists.txt
fvtest/compilertriltest/LinkageTest.cpp
fvtest/tril/tril/compiler_util.hpp
fvtest/tril/tril/ilgen.cpp

~_Note: Only 8e87394 is new, as this PR builds on top of #1910_~
This PR is a feedback request for specifying linkage on a call. The hope is that this kind of functionality can be used to test a PR similar to #1899. 
This PR only covers the setting the linkage on calls. However, a very similar mechanism should be usable to set the linkage on the Tril described method itself, so that it receives parameters based on the specified linkage.
I also explored the use of Type Parameterized tests in google test, coming to the conclusion I didn't really like them for this, as it makes the test cases awkward.

Support doing linkage definition on call sites in Tril

---

CMakeLists.txt
cmake/config.cmake
cmake/modules/OmrSanitizerSupport.cmake
doc/BuildingWithCMake.md

Some compiler systems (gcc and clang) support the notion of Runtime
Sanitizers. These are builds that are instrumented to flag bugs at
runtime. Sanitizers are nice because they typically have a very low
false positive rate, and as such, when an issue is flagged, it typically
can be relied on.

Support building OMR with Runtime Sanitizers

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp

Subsumed by the CodeGenerator implementation.

Remove FrontEnd implementation of reserveNTrampolines

---

compiler/optimizer/Inliner.cpp
compiler/optimizer/Inliner.hpp

Add an extension point in InlinerUtil to answer whether targeted
inlining is needed for a method after it is inlined.

Add a query for targeted inlining

---

compiler/runtime/CodeCacheExceptions.hpp

Relocate the Trampoline exceptions from the OpenJ9 project to OMR.
Move them to the `TR` namespace and add some basic documentation.

Introduce Trampoline exceptions

---

compiler/optimizer/LocalOpts.cpp

Removed the dead code following 'continue' statement within the 'if'
block. Retained the comment. Thank you.
Fixes: #1321
Signed-off-by: Kabir Islam <kaislam1@in.ibm.com>

Removed dead code in TR_HoistBlocks

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/optimizer/IsolatedStoreElimination.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

Eliminates and folds the query allowDSEOfVolatiles that always returned true.

Eliminate and fold allowDSEOfVolatiles

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OMRSimplifierHandlers.hpp

Remove integer arithmetics in integer comparisons to reduce the number of add/sub
instructions emitted.
e.g. an addition can be avoided if x-1>0 is transformed into x>1.

Simplify byte, short, int, and long comparisons

---

omrmakefiles/rules.zos.mk

Currently the OMR zOS makefiles require that a user sets a few 
evnironment variables that control the placement of compile
options. This change uses the default placement of compile options
so that the environment variables are not required.
Remove the LIST option since we do not need to generate the 
assembly listing to stdout.
This change also removes the -g9 option that was added for
generating debug information since it is not valid.
[ci skip] - on zOS changes

Modify makefile rules for zOS

---

thread/common/threadhelpers.cpp

Currently, there is a limit (spin_thread_limit) on how many threads can
spin at a time on a monitor/lock. Over this spin_thread_limit, threads
don't spin but try to acquire the lock once before waiting. This can
cause high CPU utilization if there are large number of threads that try
to acquire a monitor/lock.
Now onwards, threads over the spin_thread_limit will immediately wait
instead of trying to acquire the monitor/lock once. This will help avoid
high CPU utilization.

Improve locking

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRMemoryReference.cpp

Remove instruction selection phase tracking in OMR::Z::CodeGenerator and use getCodeGeneratorPhase() instead
Closes #2065

Remove tracking of instruction selection phase from OMR::Z::CodeGenerator

---

compiler/codegen/OMRLinkage.hpp

Member function `isPointerToPrivateStaticAddress` is not overridden or used
in any known project.

Remove unused Linkage function

---

compiler/codegen/OMRMemoryReference.hpp

The function is not used and doesn't belong in the base class.

Remove asARMMemoryReference virtual from MemoryReference

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRCodeGenerator.hpp

`OMR::CodeGenerator` function `getMinimumNumberOfNodesBetweenMonitorsForTLE`
has been relocated to the OpenJ9 project.  Delete it from OMR.
Closes: #2061 

Remove OpenJ9-specific CodeGenerator function

---

omrmakefiles/rules.linux.mk

configure_linux_arm.mk and rules.linux.mk are updated to make
use of the environment variables provided by the docker file
(https://github.com/eclipse/openj9/pull/622).
This allows the names of the toolchain executables to be passed
from the docker file and also avoids the need to hard-code the
location of the global include files.
Signed-off-by: James Kingdon <jkingdon@ca.ibm.com>

Updates for docker based ARM build

---

compiler/x/i386/codegen/OMRTreeEvaluator.cpp

minmaxEvaluator on X86-32 should use unsigned
comparison for low word instead of signed one.
Fixing it.
Closes #2099 

Fix for X86-32 minmaxEvaluator Issue

---

CONTRIBUTING.md

Remind contributors to update the latest copyright date in
the copyright header when making changes to a file.

Require copyright updates in Contribution Guidelines

---

gc/base/MemoryPoolAddressOrderedList.cpp
gc/base/MemoryPoolLargeObjects.cpp
gc/base/MemoryPoolSplitAddressOrderedListBase.cpp
gc/base/MemorySubSpaceSemiSpace.cpp

use max(tlhMaximumSize, scavengerScanCacheMaximumSize) for 
calculating tlh sizeClass to avoid the sizeClass overflow. 
Issue: #2089

smaller tlhMaximumSize setting can cause GC assert

---

fvtest/porttest/omrvmemTest.cpp

In some cases, the store to establish the dynamically synthesized
function (i.e. create the return instruction) can still be within the
CPU core store queue. So, a stale instruction can be fetched and
executed from the iCache. This can cause an IOT/Abort trap. __lwsync()
and __isync() are used to synchronize the iCache. This prevents the
IOT/Abort trap. 

Fix code synchronization issue

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp

Add this API to query whether there is information about slots sharing or dead slots stored in OSRMethodData

Add hasSlotSharingOrDeadSlotsInfo to OSRMethodData

---

CMakeLists.txt
cmake/modules/OmrTracegen.cmake
fvtest/algotest/CMakeLists.txt
fvtest/compilertest/CMakeLists.txt
fvtest/compilertriltest/CMakeLists.txt
fvtest/gctest/CMakeLists.txt
fvtest/jitbuildertest/CMakeLists.txt
fvtest/omrGtestGlue/CMakeLists.txt
fvtest/porttest/CMakeLists.txt
fvtest/sigtest/CMakeLists.txt
fvtest/threadextendedtest/CMakeLists.txt
fvtest/threadtest/CMakeLists.txt
fvtest/tril/examples/incordec/CMakeLists.txt
fvtest/tril/examples/mandelbrot/CMakeLists.txt
fvtest/tril/test/CMakeLists.txt
fvtest/tril/tril/CMakeLists.txt
fvtest/util/CMakeLists.txt
fvtest/utiltest/CMakeLists.txt
fvtest/vmtest/CMakeLists.txt
gc/CMakeLists.txt
tools/hookgen/CMakeLists.txt
tools/tracegen/CMakeLists.txt
tools/tracemerge/CMakeLists.txt
util/a2e/CMakeLists.txt
util/avl/CMakeLists.txt
util/hashtable/CMakeLists.txt
util/hookable/CMakeLists.txt
util/omrutil/CMakeLists.txt
util/pool/CMakeLists.txt

Organize the various targets into folders when using a generator with
folder support.
See
https://cmake.org/cmake/help/v3.2/prop_gbl/USE_FOLDERS.html
https://cmake.org/cmake/help/v3.2/prop_tgt/FOLDER.html

CMake: Organize targets into folders

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/optimizer/FieldPrivatizer.cpp

- Corrected the spelling of `createCoDependententTemporary` to `createCoDependentTemporary` in `compile/OMRSymbolReferenceTable.cpp`,  and in all references of this function (2 references) .
Closes : #2104
Signed-off-by: Arwin Neil Baichoo <arwinneil@gmail.com>

 Correct spelling of createCoDependententTemporary 

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp

- Removed unused functions `inlinePackedLongConversion` and `supportsNamedVirtualRegisters` from `compiler/z/codegen/OMRCodeGenerator.cpp` and `compiler/z/codegen/OMRCodeGenerator.hpp`
Closes: #2062, #2059
Signed-off-by: Arwin Neil Baichoo <arwinneil@gmail.com>

Remove unused functions from Z CodeGenerator

---

compiler/optimizer/OMRValuePropagation.hpp

This function in `OMRValuePropagation` only applies to OpenJ9 (non-J9
runtimes return almost immediately).  Prepare to relocate this code to
OpenJ9 by first marking it virtual.

Make getParmValues virtual

---

compiler/optimizer/DataFlowAnalysis.enum

The data flow analysis kinds enum in `compiler/optimizer/DataFlowAnalysis.enum`
is out of sync with the names table in `compiler/optimizer/DataFlowAnalysis.cpp`.
Fix the enum numbering.

Resynchronize data flow kinds enum with names table

---

compiler/codegen/OMRInstruction.hpp
compiler/codegen/OMRInstructionFlagEnum.hpp
compiler/il/OMRBlock.hpp
compiler/z/codegen/OMRMemoryReference.cpp

* Remove LastWarmInstruction property from `OMR::Instruction`
* Remove LastWarmBlock property from `OMR::Block`
Both are deprecated and no longer used.
Closes: #2119

Remove deprecated warm instruction and block properties

---

compiler/compile/OMRCompilation.cpp
compiler/compile/OMRCompilation.hpp

The bulk of this `OMR::Compilation` function applies to OpenJ9.  Move
the functionality to the OpenJ9 project and replace the OMR version
with a sensible default (returning `false`).

Relocate notYetRunMeansCold to OpenJ9

---

compiler/z/codegen/ArchInstOpCodeEncoding.hpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRInstOpCode.hpp
compiler/z/codegen/OMRInstruction.cpp

Often times when implementing a new feature we make use of instructions
which have been introduced in a specific processor. To make use of such
instructions we have to guard the block of code which will emit the
respective instruction with an architecture guard. If such a guard is
omitted we end may end up executing at runtime an unsupported
instruction, depending on the environment in which the compiler is
executing.
To prevent this from happening in the future we add a minimum
architecture level set (ALS) for each instruction and add a soft assert
in the constructor of each instruction to validate that we will never
crash with a SIGILL due to a missed architecture guard.

Add minimum ALS for each instruction in Z codegen

---

compiler/z/codegen/S390Instruction.hpp

This field is no longer used in the OMR::Z CodeGenerator or any known
downstream projects.  Delete it.

Remove unused warmToColdTrampolineSnippet field

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRLinkage.hpp
compiler/codegen/StorageInfo.cpp
compiler/il/OMRNode.cpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/OMROptimization.cpp
compiler/optimizer/UseDefInfo.cpp

Remove the function definition and uses and fold surrounding code
assuming it always returns false.

Remove deprecated isAddressOfStaticSymRef from Linkage

---

compiler/codegen/Analyser.cpp
compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/il/symbol/OMRAutomaticSymbol.cpp
compiler/il/symbol/OMRAutomaticSymbol.hpp
compiler/il/symbol/OMRSymbol.hpp
compiler/il/symbol/OMRSymbol_inlines.hpp
compiler/optimizer/LoadExtensions.cpp
compiler/ras/Debug.cpp
compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/CompareAnalyser.cpp
compiler/z/codegen/FPTreeEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRMemoryReference.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

`TR::RegisterSymbol`s are a remnant from an old register allocator and
do not have relevance in the OMR project.  These symbols are unused by
any known downstream project.
Remove references to `TR::RegisterSymbol`s and fold code around symbol
identity checks assuming register symbols never exist.

Remove obsolete RegisterSymbols

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/optimizer/OSRDefAnalysis.cpp

OSRUses under prepareForOSR prolong the live range of autos and
pending push temps. Especially, those fake uses can cause many
autos and temps appear to be alive at the method entry and requires
zero initialization in the method prologue which is big overhead.
A way to solve this problem is to find out the `real` uses
of those autos and pending push temps at each OSRPoint and use them
during liveness analysis. The `real` uses can be found by figuring
out which symbols are needed to calculate the auto or temps at each
prepareForOSRCall and combining this with the liveness information
for the autos and temps from original bytecode.
This changeset builds the map, named definingMap, to map each auto
and temp to the symbols needed to calculate them at any OSRPoint.
Signed-off-by: Yi Zhang …

Build definingMap for OSRUses symbols

---

port/ztpf/omrosdump_helpers.c

Update to change valid programs to write out into dumps.  Removed
explicitly translating pathconf function call parameter as that function
was added into z/TPF a2e library support.

z/TPF minor updates for omrosdump_helpers.c

---

compiler/z/codegen/OMRInstruction.cpp

There are a couple of Assertions in OMRInstruction.cpp
which make calls to `OMR::InstOpCode::getMnemonicName`.
However, `getMnemonicName` is yet to be implemented on `Z`
and therefore these calls generate compile time failures.
This commit replaces the said calls by using an alternate API.
Closes: #2144
Signed-off-by: Rwitaban (Ray) Banerjee rayb@ca.ibm.com

Remove calls to `getMnemonicName` in `z` codegen

---

compiler/control/OMROptions.hpp

JProfiling added a new option in a prior commit,
replacing a value marked as available in the
options enum. However, this value was already
taken. This change removes the collision.

Fix option enum collision

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

JProfiling includes an optional thread to
manage its value profiling during execution.
This change adds options to disable it.

Add options to control JProfiler thread

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/compile/OMRCompilation.cpp
compiler/env/RegionProfiler.hpp
compiler/optimizer/OMROptimizer.cpp

This change simplifies use of the memory region
profiler and extends its use to codegen and the
general compilation strategy.

Extend memory region profiler

---

compiler/z/codegen/ArchInstOpCodeProperties.hpp
compiler/z/codegen/OMRInstOpCode.hpp
compiler/z/codegen/OMRInstruction.hpp

Some instruction properties in the Z codegen are not used and are
slated for deprecation. We currently do not envision any of the removed
properties to be used by any downstream projects now or in the future
thus eliminating stale properties allows us to minimize the size of the
instruction opcode tables and consolidate properties and properties2
static fields.

Deprecate unused instruction properties in Z codegen

---

include_core/omrport.h
port/linux/omrvmem.c

On the OMR side: add a new Virtual Memory Option called OMRPORT_VMEM_ADDRESS_HINT
Change the method getMemoryInRangeForDefaultPages() to do the following:
- when OMRPORT_VMEM_ADDRESS_HINT is used, instead of trying page by page to allocate in the desired region, we stop after the first attempt and return whatever default_pageSize_reserve_memory() gives us
- when doing OMRPORT_VMEM_ALLOC_QUICK, do not try the slow search with mmap if the fast search with smaps failed
- when doing OMRPORT_VMEM_ALLOC_QUICK, avoid doing the range check when OMRPORT_VMEM_ADDRESS_STRICT is not set
On the OpenJ9 side: change the JIT to do the following during code cache allocation
- try to allocate memory providing a desired address and setting OMRPORT_VMEM_ADDRESS_HINT
- if the address returned by the OS is not …

Improve the code cache allocation process on Linux

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlBuilder.hpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRTreeEvaluator.hpp

Helpers related to atomic memory update now only have one
standardized shape: 1 parameter for address and 1 parameter
for value.

Standardized Atomic Memory Update Helpers

---

compiler/optimizer/AsyncCheckInsertion.cpp
compiler/optimizer/Inliner.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LoopReplicator.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OMROptimizer.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/optimizer/OrderBlocks.cpp
compiler/optimizer/PartialRedundancy.cpp
compiler/optimizer/RedundantAsyncCheckRemoval.cpp
compiler/optimizer/ShrinkWrapping.cpp

This change enables various optimizations
that were disabled under JitProfiling due
to issues with the duplication it performed,
such as the increased node count or its
limitations on asyncchecks.

Enable optimizations with JProfiling

---

compiler/compile/OMRCompilation.cpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/env/CompileTimeProfiler.hpp

This adds a utility to generate a performance profile
for a specific compilation. This is useful when attempting
to cut compile time overhead, particularly when there are
a handful of expensive compiles (>10s in duration) but
they are drowned out others.

Add perf record utility for compilation thread

---

compiler/env/OMRObjectModel.hpp
compiler/env/OMRVMEnv.hpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
gc/base/GCExtensionsBase.hpp

Add ability to run concurrent scavenger with JIT enabled on s390
hardware that doesn't support guarded storage.
Signed-off-by: Evgenia Badyanova evgeniab@ca.ibm.com

Implement software read barrier for concurrent scavenger testing

---

fvtest/compilertriltest/VectorTest.cpp

Z12 and lower architectures don't have vector support. This causes
illegal instruction failures on Z. Since we cannot currently
determine at runtime which Z architecture the test is running on, the
tril test for VectorTest is disabled on Z altogether. We can re-enable
once we are able to check at runtime.

Disable VectorTest on Z

---

LICENSE
longabout.html

The initial OMR contribution included a library called "auxv" as part of
the port library (port/unix/auxv.[ch]). This library was written by IBM
and incorporated into the OMR code base (then the J9 JVM) long before
this code was separately released as an open source library called
libauxv. The code in OMR is, in fact, unrelated to that open source
library.
A mistake was made referencing libauxv in our license materials, however:
our LICENSE and longabout.html files reference libauxv as if it has a
different license than the rest of OMR and even mention the open source
project. This commit removes these references because they are wrong.
[ci skip] since this update does not affect the code

Remove references to libaux library

---

include_core/omrcomp.h

Later versions of mingw define the __thiscall macro.
Disable the dummy definition to avoid compile errors.

Don't #define __thiscall if it is already defined

---

port/ztpf/omrosdump_helpers.c

z/TPF dumps out program static data areas for OMR and
OPENJ9 programs.  This PR extends the list to include
JCL programs as well.  This update enhances RAS for
z/TPF system cores.

Add JCL programs to static data dump list for z/TPF.

---

compiler/compile/OSRData.hpp

std::map uses require a const key or else recent version of XCode (more
recent than used on our build machines apparently) will not match the
template classes properly. This commit simply makes the key const.
Fixes: #2192

Give DefiningMap a const key

---

compiler/optimizer/LoadExtensions.cpp
compiler/optimizer/LoadExtensions.hpp

Load Extensions is a local optimization is that it is unaware of and
does not respect global sign extension decisions. GRA in particular can
set the NeedsSignExt flag on iRegStores signifying that a sign
extension should be emitted during the evaluation of the global
register store. This directly conflicts with the Load Extensions
optimization.
We introduce an excluded nodes list and prevent the local optimization
on any load that feeds into a store marked with the NeedsSignExt flag.
Closes: #2187

Exclude nodes marked with NeedsSignExt flag in Load Extensions

---

compiler/ilgen/IlBuilder.cpp
jitbuilder/release/Makefile

There is one last piece of code in IlBuilder.cpp and in
the JitBuilder makefile to finish removing the early replay
support.
Fixes: #1818

Eliminate last bits of early jitbuilder replay support

---

compiler/ilgen/IlBuilder.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp

Two small unrelated and noncritical fixes:
1) to eliminate a warning in OMRSimplifierHandlers.cpp, I added some cases to a switch as well as a default handler
2) I removed an unimplemented service from JitBuilder called "ConstzeroForValue"

Small fixes

---

cmake/modules/OmrDetectSystemInformation.cmake
cmake/modules/platform/toolcfg/msvc.cmake
omrsigcompat/omrsig.cpp
omrtrace/omrtrace_internal.h
port/common/omrfile_blockingasync.c
port/common/omrstr.c
port/win32/j9nlshelpers.c
port/win32/omrfile.c
port/win32/omrfile_blockingasync.c
port/win32/omrfilestream.c
port/win32/omrintrospect.c
port/win32/omrosbacktrace_impl.c
port/win32/omrosdump.c
port/win32/omrsysinfo.c
port/win32/omrtty.c
port/win32/omrvmem.c
port/win64amd/omrsignal.c
tools/tracegen/TraceHeaderWriter.cpp
util/hookable/CMakeLists.txt

Closing #2191 as it has several unnecessary merge commits.
This is cmake-based config only.
Changes I made:
Modified cmake scripts
Removed unused variables
Fixed some type casts
Removed some {{0}} initializers, clang doesn't like it sometimes. Replaced with memset().
Made several function definitions consistent with it's declarations.

Initial changes to be able to compile OMR with Clang 5.0 under Windows

---

gc/base/MemoryPoolAddressOrderedList.cpp
gc/base/MemoryPoolLargeObjects.cpp
gc/base/MemoryPoolSplitAddressOrderedListBase.cpp

Originally, we always used the tlhMaximumSize from the extensions.
This was recently changed to use the scavenger cache size, but this only
compiles if the scavenger is enabled.
I've added an ifdef that resorts to the original behaviour if the
scavenger is off, fixing a compilation error.

GC: Don't use scavenger cache size to pick TLH size when scavenger is off

---

omrmakefiles/rules.ztpf.mk

Introduce makefile variables to hold project and system root
variables which specify include base directories for OMR
compilations.

Enable project root and system root variables for z/TPF Platform

---

compiler/compile/OSRData.hpp

TR::typed_allocator requires a const key type or else recent version of XCode
(more recent than used on our build machines apparently) will not match the
template classes properly. This commit simply makes the key type const.
I tested on all platforms to verify builds, since an earlier version of
this fix broke builds on some platforms.
Fixes: #2192

Give DefiningMapAllocator a const key type

---

compiler/infra/Checklist.hpp
compiler/optimizer/RegisterCandidate.cpp
compiler/runtime/CodeCacheTypes.hpp
gc/base/PacketList.hpp

z/TPF builds runtimes with an intermediary character
translation library which uses intercepting headers
to redefine system functions which require translation
from ascii to ebcdic. However, for some scenarios
translations is not desired. The 'remove' member function
is one of those instances where we don't want to
redefine to do translations.

Disable redefinition of 'remove' for z/TPF Platform

---

fvtest/compilertriltest/LinkageTest.cpp

Tril tests inside LinkageTest.cpp use function pointers to template functions. This is incompatible with gcc 4.4.7. This commit implements a workaroud so that we can successfully compile and run LinkageTest using gcc 4.4.7.
Closes: #2152

Remove incompatible compiler features in LinkageTest

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp
compiler/ras/DebugCounter.cpp

- Removed `_genericCallHash` and all references from OMR::SymbolReferenceTable.
Closes: #2129
Signed-off-by: Arwin Neil Baichoo <arwinneil@gmail.com>

Remove genericCallHash from OMRSymbolReferenceTable

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

With the removal of obsolete function
OMR::Z::CodeGenerator::inlinePackedLongConversion(), the TR::Option
TR_DisablePackedLongConversion was no longer used.
Closes: #2123

Removed deprecated TR::Option TR_DisablePackedLongConversion

---

compiler/x/codegen/X86BinaryEncoding.cpp

There were 4 instances of TR::comp() being called in OMR::Instruction member functions in compiler/x/codegen/X86BinaryEncoding.cpp. They were replaced by cg()->comp().
Closes: #2184
Signed-off-by: Nazim Uddin Bhuiyan <nazim.uddin.bhuiyan@ibm.com>

Replace uses of TR::comp() in x86 binary encoding

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp

The following data structures:
- _aggregateShadowSymbolMap
- _aggregateShadowSymbolReferenceMap
were present in OMR::SymbolReferenceTable, but were no longer used.
They have been removed.
Closes: #2124

Removed unused aggregateShadowSymbol data structures

---

compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/codegen/X86Ops.hpp
compiler/x/codegen/X86Ops_inlines.hpp
compiler/x/runtime/X86Runtime.hpp

OSXSAVE flag tells if OS enables XSAVE instruction,
which is a strong indication that AVX is enabled by
the OS.

Check OSXSAVE when detecting AVX support

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/optimizer/LoadExtensions.cpp
compiler/optimizer/LoadExtensions.hpp
compiler/optimizer/OMRSimplifierHandlers.cpp
compiler/ras/Debug.cpp
compiler/z/codegen/OMRCodeGenPhase.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/S390GenerateInstructions.cpp
compiler/z/codegen/UnaryEvaluator.cpp

- Remove PLX stale case which makes assumptions on unqueried
isUsing32BitEvaluator
- Remove case for conversion of AND operations as this is caught by the
simplifier
- Remove boolean compare case and right shift cases as these are caught
by the simplifier
- Remove the conversion and reverse conversion case as this is caught
by the simplifier
- Intorduce new node flags to represent sign/zero extensions
- Remove super hacky SignExtensionFlagsIndex and SupportedType
- Fix bugs related to load counting not to bias signed extensions
- Fully document the optimization and all flags used
- Add static debug counters to track use cases
- Add more tracing to the optimization for debugging

Improve and document Load Extensions optimization

---

compiler/optimizer/CopyPropagation.cpp
compiler/optimizer/GlobalRegisterAllocator.cpp
compiler/optimizer/InductionVariable.cpp
compiler/optimizer/IsolatedStoreElimination.cpp
compiler/optimizer/LoadExtensions.cpp
compiler/optimizer/LoopCanonicalizer.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRValuePropagation.cpp
compiler/optimizer/VPHandlers.cpp
compiler/optimizer/ValueNumberInfo.cpp

As mentioned in issue #2175 the result of getUseDef
has already been checked for zero (the return value
of getUseDef is false if zero). So there is no need
to check IsZero again and this is the change in this commit.
Issue: #2175
Signed-off-by: Vijay Sundaresan <vijaysun@ca.ibm.com>

Avoid IsZero overhead after calling getUseDef

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LoopVersioner.cpp
compiler/optimizer/OMRValuePropagation.cpp

Place appropriate guards around trace messages to prevent unwanted
messages in the compiler log file.

Suppress unguarded trace messages in compiler log

---

compiler/compile/OSRData.cpp
compiler/compile/OSRData.hpp
compiler/control/OMROptions.cpp
compiler/il/symbol/OMRResolvedMethodSymbol.cpp
compiler/optimizer/OMROptimizer.cpp
compiler/optimizer/OSRDefAnalysis.cpp
compiler/optimizer/OSRDefAnalysis.hpp

In debugging mode, the debugger may dereference an object slot even
after it's gone dead and we must make sure such dead slots are zeroed
out at OSR transition to avoid program crashing.
VoluntaryOSR could zero out the dead slots at induceOSR in trees
because there is one induceOSR for each osrPoint. However, under
involuntarOSR, which debbuging mode runs with, multiple osrPoints
would transit to the same code block and therefore the zero stores
can not be expressed in trees shared between all the different
osrPoints.
This changeset adds the infrastructure to bookkeep deadslots while
compiling the Java code. At OSR transition at runtime, the prepareForOSR
helper reads the data and decide which slots to zero out.

Zero out dead slots at OSR transition for FSD

---

.gitignore
compiler/env/defines.h
ddr_artifacts.mk
fvtest/omrtest.mk
gc/base/segregated/RegionPoolSegregated.hpp
include_core/omrcfg.h.in
include_core/omrhashtable.h
omrcfg.CMakeTemplate.h
util/hashtable/hashtable.c

Preparations for use of ddrgen in support of openj9#378
* correct references to getmacros script
* add missing ddr_namespace annotations
* use J9HASH_TABLE_AVL_TREE_TAG_BIT instead of hard-coded constant
* ignore objs directory

Preparations for use of ddrgen

---

compiler/ilgen/IlBuilder.cpp
compiler/ilgen/IlBuilder.hpp

Currently, there is no way to emit IL for getting the remainder of an
integer division using IlBuilder's services. This commit adds a new Rem
service on IlBuilder to allow this using existing support in
TR::ILOpCode for generating remainder opcodes.
Signed-off-by: Benjamin Thomas <ben@benthomas.ca>

Add Rem service to IlBuilder

---

tools/compiler/OMRChecker/test.py

Currently, the test script always uses "clang++" to call Clang for
testing OMRChecker. This causes problems, when "clang++" calls an
unsupported clang version by default. There are a number of problems
that can arise from this, such as when using different Linux distros.
The increased flexibility was achieved by 1 change:
- The constructor of class OMRChecker has been modified to pull and use
Clang calling info from the environment, by looking for the env
variable 'CLANG'. If no such env variable exists, then the default
'clang++' is used.
This change is a requirement for addressing [issue 729](https://github.com/eclipse/openj9/issues/729) in eclipse/openj9.

Enable OMRChecker testing script to read CLANG environment variable

---

compiler/codegen/OMRCodeGenerator.cpp

trfprintf calls inside of doInstructionSelection do not do a null check on the file handle before writing. This can cause crashes when the file handle is null (which is a possibility when we run out of file handles (ulimit -n)). These calls should be replaced with traceMsg, which does a null check before trying to print.

Replace trfprintf calls with traceMsg

---

compiler/p/codegen/OMRCodeGenerator.cpp

This is a change targeting Power. The runtime check is64BitProcessor now
checks to see if it is a 64 bit build. If so, it just returns true since
a 64 bit build must be running on a 64 bit processor. If not, the function
will check the CPU properties as before.
Issue: #2232

64 bit builds should assume a 64 bit processor on Power

---

compiler/optimizer/LoadExtensions.hpp

Some compilers require (via static_assert) that the type of the value
match the type of the allocator value. In this case it does not matter
whether either are const so we make the map value_type as such.

Fix std::map::value_type to match the type of the allocator

---

compiler/arm/codegen/ARMOps.hpp
compiler/arm/codegen/OMRTreeEvaluator.cpp
compiler/arm/codegen/OMRTreeEvaluator.hpp
compiler/arm/codegen/OpBinary.cpp
compiler/arm/codegen/OpProperties.cpp

This commit adds code generation of ARM's sxtb/sxth instructions
and uxtb/uxth instructions for improving the instruction sequences
of sign extension and of zero extension, respectively.

Generate sxtb/sxth and uxtb/uxth instructions for ARM

---

compiler/arm/codegen/ARMDebug.cpp

This commit adds 4 instruction names in opCodeToNameMap[] in
ARMDebug.cpp.  The new instructions were added by PR #2239.

Add support for sxtb/sxth/uxtb/uxth instructions to ARMDebug.cpp

---

gc/base/EnvironmentBase.hpp
gc/base/OMRVMThreadInterface.cpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/EnvironmentStandard.hpp

Flushing Scavenger Remembered Set fragment within thread GC Environments
for all threads (including GC once), prior the second/last STW phase
within Concurrent Scavenger cycle, while concurrent phase is still in
progress is not correct - it interferes with GC background threads that
are still using this RS fragments.
Only RS fragments for mutators (that generate remembered objects through
Write Barrier) should be flushed.
Also doing minor re-org (moving RS aware code into Environment, rather
in VMInternface), and simplifying (removing redundant Enviroment
parameters).

Flush RS prior STW Scavenge just for Mutators

---

gc/base/ObjectModelBase.hpp
gc/base/SlotObject.hpp
gc/base/standard/Scavenger.cpp
gc/structs/ForwardedHeader.cpp
gc/structs/ForwardedHeader.hpp

For large objects, before trying to win forwarding, setup destination
header object to indicate that object is in progress. Then threads that
see the object is forwarded, but still being copied, will wait instead
of trying to create its own copy.
Further, while waiting, those threads will try to participate in
copying. Destination object header, beside the being-copied bit will
contantin progress info: amount of bytes yet to copy and count of
threads already participating. Threads atomically try to win a section
of object to copy. Once, everything is taken to copy (0 bytes yet to
copy), and all threads are done with the last section and decrement the
participation count, the winning threads will do the final steps of
fixup and replace the progress info with the valid object header. …

Co-operative copy of large objects in CS

---

compiler/x/amd64/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/i386/codegen/OMRCodeGenerator.cpp

In preparation for removing the vmThread reclamation logic, it must first
be disabled on the 32-bit platforms where it is enabled to aid with its
surgical removal:
* force `allowVMThreadRematerialization` to always return `false`.  While
this affects both Windows and Linux 32-bit, in practice this will have no
effect on Linux 32-bit because querying this setting is always coupled with
one of the other reclamation options below that mask its effect.  This
function always returns `false` on 64-bit platforms.
* force `supportsFS0VMThreadRematerialization` to always return `false`.
This affects Win32 only.
* remove calls to `setSupportsVMThreadGRA`, thereby causing queries to
`getSupportsVMThreadGRA` to always return `false`.  This affects Win32
only.
Signed-off-by: Daryl Maier …

Disable vmThread reclamation on 32-bit Windows

---

compiler/codegen/CodeGenRA.cpp
compiler/z/codegen/BinaryEvaluator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp

This pull request is for the removal of the following fields and functions:
```plaintext
setCurrentlyClobberedRestrictedRegister
clearCurrentlyClobberedRestrictedRegister
getCurrentlyClobberedRestrictedRegister
setKilledRestrictedRegisters
getKilledRestrictedRegisters
setCurrentlyRestrictedRegisters
getCurrentlyRestrictedRegisters
```
These fields and functions are not used in OMR or any other downstream projects.
Issue: #2063

Remove RestrictedRegister fields and functions from OMR::Z::CodeGenerator

---

compiler/z/codegen/S390GenerateInstructions.cpp

Removing generateRegRegInstruction, which is not used anywhere in z/codegen.
Closes: #2243 

Remove generateRegRegInstruction from z/codegen

---

compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/UnaryEvaluator.cpp

Remove evaluateNodeInRegPair and fold as it returns false.
Closes: #2060 

Remove setEvaluateNodeInRegPair in Z CodeGenerator

---

compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp

This commit introduces a new option -Xjit:dontDowngradeToColdDuringGracePeriod
which will be used to turn off a new compilation heuristic in openj9
which allows compilations to be downgraded from 'warm' to 'cold' during
the "grace period" (first second of run)

New option for downgrading optimization level to cold

---

port/unix/omrintrospect.c

Processes have been reported to hang in omrintrospect_threads_nextDo() on Linux systems with kernel version 3.10. This changes the assumption of reliability of sigqueue() from `(version >= 3)` to `(version >= 3.11)`.
See #106.

Refine minimum Linux kernel version with reliable sigqueue

---

compiler/x/codegen/X86Ops.ins

This instruction zero extends each of the lower dword's 4 packed integers (1 byte) to signed dword integers (4 bytes).
Signed-off-by: Mansoor Saqib <Mansoor.Saqib@ibm.com>

Adds x86 instruction PMOVZXBD

---

compiler/arm/codegen/ARMDebug.cpp
compiler/ras/Debug.cpp
compiler/ras/Debug.hpp

This commit removes some debug functions for ARM that are no longer
used: printAsmDumpHeader() and printARM().

Remove unused debug functions for ARM

---

compiler/arm/codegen/OMRTreeEvaluator.cpp

OMR::ARM::TreeEvaluator::arraycopyEvaluator() asserts when passed
a non-simple arraycopy node.
This implements new functions genWrtbarForArrayCopy() and
VMCardCheckEvaluator() for handling non-simple arraycopy nodes.
Closes: #1996

Implement write barriers for arraycopy for ARM

---

fvtest/compilertest/CMakeLists.txt

testcompiler already exports the required include paths etc.
Since compilertest links against testcompiler it gets these for free

CMake: Remove superfluous call to make_compiler_target

---

compiler/arm/codegen/OMRCodeGenerator.cpp

Call setSupportsReferenceArrayCopy() in the ARM JIT.
Write barrier for arraycopy was enabled for ARM by #2186.

Enable generation of ReferenceArrayCopy for ARM

---

cmake/modules/platform/toolcfg/gnu.cmake

With the move to CMake some assembly files get assembled using
GCC instead of AS. On Linux 390 some of the instructions used in
the port library assembly files are only supported on newer
architectures so we should set `-march=z9-190`. The compiler
technology is already setting this value for assembler files.

On linux 390 make sure to target z9-190 as the architecture

---

compiler/compile/OMRSymbolReferenceTable.cpp
compiler/compile/OMRSymbolReferenceTable.hpp

To be relocated to OpenJ9
Closes: #2125 
OpenJ9 PR: eclipse/openj9#1039

Remove currentThreadDebugEventData structures

---

compiler/x/runtime/X86Runtime.hpp

TR_DisableAVX was malfunctional since the mask to unset XSAVE bits were incorrect.
Fixing it.

Fix for malfunctional env var TR_DisableAVX on X86

---

gc/base/GCExtensionsBase.hpp
gc/base/omrmmprivate.hdf
gc/base/standard/ConcurrentGC.cpp
gc/base/standard/ConcurrentGC.hpp
gc/base/standard/Scavenger.cpp

Bypass hook API tp reduce overhead, mostly by avoiding the hook internal
stats counter (which is using an atomic increment).

Direct old-to-old-reference callback

---

compiler/codegen/CodeGenRA.cpp
compiler/codegen/OMRCodeGenerator.cpp
compiler/compile/OMRCompilation.cpp
compiler/control/OMROptions.cpp
compiler/control/OMROptions.hpp
compiler/x/codegen/CompareAnalyser.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/FPTreeEvaluator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRRegisterDependency.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/OutlinedInstructions.cpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/i386/codegen/OMRCodeGenerator.cpp
compiler/x/i386/codegen/OMRTreeEvaluator.cpp

* Disable late edge splitting
* Do not add VMThread pre/post conditions on x86
* Do not override initial register state of EBP on Win32
* Remove vmThread rematerialization logic from OutlinedInstructions
* Remove uses of getSupportsVMThreadGRA()
Issue: #2256

Remove more VMThread reclamation logic from the x86 CodeGenerator

---

compiler/optimizer/DataFlowAnalysis.hpp

...another map without a const key that doesn't compile with
latest clang.

Fix TR_BCLiveSymbolsMap key const-ness

---

include_core/omrutilbase.h
util/omrutil/AtomicFunctions.cpp

C wrapper, setAtomic has been added for VM_AtomicSupport::set operation.

Added a C wrapper for VM_AtomicSupport::set operation

---

compiler/z/codegen/OMRTreeEvaluator.cpp

inlineStringHashCode if/else blocks negating isCompressed are
replaced with positive queries.
Signed-off-by: Mansoor Saqib <Mansoor.Saqib@ibm.com>

Remove negation in Z codegen inlineStringHashCode

---

compiler/il/OMRNode.hpp

The unneededConv flag used by TR::x2y nodes overlaps with the simpleDivCheck flag. During node recreation, flags are copied from the original node to the new node without checking if the flag will be valid for the new node being created. This can cause invalid instructions to be generated if the optimizer transforms an ldiv node of two i2l children to i2l of idiv during treeSimplification. To avoid this, this commit changes the unneededConv node's value so that it doesn't overlap with the simpleDivCheck flag.
Closes: #2297
Signed-off-by: Dhruv Chopra <dhruv.c.chopra@ibm.com>

Change the value of the unneededConv flag

---

CMakeLists.txt
cmake/modules/OmrCompilerSupport.cmake
compiler/CMakeLists.txt

Currently a list of core jit sources are built up every time a compiler
library is built (test compiler, jitbuilder, tril). With this patch the
list is built only once.

CMake: refactor jit sources processing

---

compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/ras/DebugCounter.cpp

A quick search through the codebase reveals this flag is not actually
used by anyone so it has no reason to exist.
Fixes: #2299

Deprecate nodeIsDebug node flag

---

compiler/x/codegen/OMRCodeGenerator.cpp

Vector Reg GRA can cause a problem that leads to the generation of an
incorrect result. GRA for vector registers is temporarily being disabled
on x86 until this issue is resolved.
The removal of GRA may cause a performance problem in autosimd reductions
so reductions have also been disabled. This was done by temporarily
disabling the use of getvelem in autosimd on x86 which is needed
for reduction.
Issue: #2280

Disable vector reg GRA and reduction on x86

---

omrmakefiles/rules.linux.mk

This is required for DDR support: #378 and makes ppc64le consistent with x86-64.

Use GNU debug symbols on PPC platforms

---

compiler/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.cpp

ArraySetToZero has been deprecated for a while, removing it.

Remove deprecated flag of to ArraySetToZero

---

ddr/tools/getmacros

Without this filtering, macroList for openj9 would be nearly 400MB; with it, it is about 250kB.

Filter duplicate information from macroList

---

thread/common/omrthread.c

If the aborted thread has to block on it's monitor during a
monitor enter call the call to monitor enter will incorrectly
fail. The code moved 2 pieces of cleanup into 1 larger if
statement which means the second bit of cleanup is not properly
guarded.  To resolve the issue the second piece of cleanup code
needed to be guarded with the isAbortable check.
Fixes #2113

Fix occasional hang in abortTest::ThreadAbortTest::Waiting

---

gc/base/GCExtensionsBase.cpp
gc/base/standard/EnvironmentStandard.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
include_core/omrgcconsts.h

Move the Remembered Set (as roots) scan, partially to the concurrent
phase of Concurrent Scavenger. 
The RS in Scavenger for the most part remembers object Tenure to Nursery
references (direct ones). But it can also remember off-heap structures
that have Nursery references, where the off-heap structure has a proxy
heap object in Tenure (indirect ones). An example being a class object
in Tenure and a matching off-heap class structure in upstream OpenJ9
project.
This change will break the RS scan into two passes. The one where we
scan Indirect references will stay in the STW phase where the rest of
the roots are processed. The pass where scan Direct references is moved
to the concurrent phase. 
Iteration (and popping-up) of RS puddles should still be safe operation,
even though new puddles …

Scan RS concurrently

---

fvtest/rastest/traceRecordHelpers.cpp

Fixes issue #2115. Trace points wrapping into the next record by 1 character were skipped by the trace point iterator. It was failing about 1 in 3 times on z/os and now passed 300 consecutive runs.

Fix intermittent TraceLogTest.stressTraceBufferManagement failure

---

ddr/include/ddr/blobgen/java/genBinaryBlob.hpp
ddr/include/ddr/ir/ClassType.hpp
ddr/include/ddr/ir/Field.hpp
ddr/include/ddr/ir/NamespaceUDT.hpp
ddr/include/ddr/ir/Symbol_IR.hpp
ddr/include/ddr/ir/Type.hpp
ddr/include/ddr/scanner/dwarf/DwarfFunctions.hpp
ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
ddr/lib/ddr-ir/ClassType.cpp
ddr/lib/ddr-ir/Field.cpp
ddr/lib/ddr-ir/NamespaceUDT.cpp
ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-ir/UnionUDT.cpp
ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/tools/ddrgen/ddrgen.cpp

* rely on DWARF offsets which consider alignment requirements
* correct offsets of synthetic fields
* remove unused Field._sizeOf
Issue: eclipse/openj9#378

Fix field offset discovery

---

compiler/x/runtime/X86Runtime.hpp
fvtest/compilertest/build/toolcfg/gnu/common.mk
jitbuilder/build/toolcfg/gnu/common.mk

Memory fences and cache line flushes are missing in
patchFence16() on X86-32. Fixing it.
Closes #2323

Apply MFENCE and CLFLUSH in patchFence16 on X86-32

---

ddr/lib/ddr-ir/Macro.cpp

Adds a recursive descent parser in order to parse macros that contain
constant expressions which evaluate down to integers.
The final constant value is returned as a `long long` in order to keep
compatibility with the rest of the ddr components.
Closes #2100

DDRgen macro constant expression evaluation

---

ddr/lib/ddr-ir/Macro.cpp

Return value should not depend on whether 'ret' is null; otherwise we get this failure:
```
Error: java/genBinaryBlob.cpp:770 addBlobConst - Adding more constants than enumerated
```

Fix use of Macro::getNumeric as test

---

compiler/codegen/OMRCodeGenerator.cpp
compiler/codegen/OMRCodeGenerator.hpp
compiler/il/symbol/OMRLabelSymbol.cpp
compiler/il/symbol/OMRLabelSymbol.hpp
compiler/il/symbol/OMRSymbol.hpp
compiler/il/symbol/OMRSymbol_inlines.hpp
compiler/ras/Debug.hpp
compiler/x/codegen/BinaryEvaluator.cpp
compiler/x/codegen/ControlFlowEvaluator.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/OMRInstructionKindEnum.hpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMemoryReference.cpp
compiler/x/codegen/OMRTreeEvaluator.cpp
compiler/x/codegen/OMRX86Instruction.cpp
compiler/x/codegen/OMRX86Instruction.hpp
compiler/x/codegen/X86BinaryEncoding.cpp
compiler/x/codegen/X86Debug.cpp
compiler/x/i386/codegen/OMRTreeEvaluator.cpp

* Remove calls to setVMThreadRequired from x86
* Remove OMR::Symbol isVMThreadLive flag
* Remove vmThreadLiveCount from OMR::CodeGenerator
* Remove obsolete OMR::X86::Instruction RestoreVMThreadInstruction
* Remove deferred edge splitting vmThread optimization from x86
* Remove VMThreadRestoringLabel field from LabelSymbol
* Remove specialty VMThread assignment logic from x86 register assigner

Remove more VMThread reclamation logic

---

ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp

A field
```
int bit : 1;
```
should be described in the blob as having type `int:1` instead of just `int`; this change corrects that.
Issue: eclipse/openj9#378

Fix blob types for bit fields

---

ddr/lib/ddr-ir/Symbol_IR.cpp

DWARF information corresponding to a forward declaration does not include a size (nor can it).
This change merges the size of a subsequent definition (if found) so the generated blob will have the proper size information.
Issue: eclipse/openj9#378

Merge type size of a forward declaration with a later definition

---

fvtest/threadtest/abortTest.cpp

On oldder versions of GCC abortTest.cpp was failing due to 'error:
comparison between signed and unsigned integer expressions'. The
compiler was treating the constant '0' as an int in the comparison.
The fix is to change the constant to '0u' to tell the compiler to
treat it as unsigned.

Fix compilation issue on older versions of GCC

---

doc/BuildingWithCMake.md

Add updated description of how the glue libraries are handled in CMake

Docs: Update CMake documentation [ci skip]

---

ddr/tools/ddrgen/Makefile
omrmakefiles/rules.linux.mk

Issue: eclipse/openj9#378
* ddrgen needs to link with libelf.so
* produce both .so and .so.dbg files

Support for DDR on Linux s390 platforms

---

port/common/omrport.c
port/common/omrsysinfo.c
port/unix/omrsysinfo.c

Add support in port library for detecting if we are running in
docker container or not.
This is required for cgroup related APIs in port library,
such as `omrsysinfo_cgroup_get_memlimit`, to work properly.
This is because when running in a docker container,
the cgroups listed in `/proc/self/cgroup` do not match the cgroups
of the process in the container. `/proc/self/cgroup` actually
shows the cgroups as seen from the host.
Eg if a process is running in a docker container,
its `/proc/PID/cgroup` on docker will show something like:
```
$ cat /proc/8364/cgroup
11:cpuset:/docker/<container id>
10:perf_event:/docker/<container id>
9:memory:/dockera/<container id>
...
```
but the actual cgroup of the process would be "/".
Once we figure out that we are running in docker container,
then cgroup …

Add support for detecting docker container

---

port/unix/omrsignal.c

AIX machines are not available for OMR external builds. AIX machines use XLC compiler. The compile failure happened with XLC compiler. Specific compile failure: 
`"./unix/omrsignal.c", line 1066.37: 1506-043 (W) The operand of the sizeof operator is not valid.`

Fix XLC compiler issues on Linux and AIX PPC

---

gc/base/EnvironmentBase.cpp
gc/base/EnvironmentBase.hpp
gc/base/GCExtensionsBase.cpp
gc/base/GCExtensionsBase.hpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp
gc/stats/ScavengerHotFieldStats.cpp
gc/stats/ScavengerHotFieldStats.hpp

Refactor MM_ScavengerHotFieldStats to be dynamically allocated rather
than inlined inside MM_EnvironmentBase (for thread local copy) as well
as in MM_GCExtensionsBase (for master copy).
Closes: #2288
Signed-off-by: Jon Oommen <jon.oommen@gmail.com>

Refactor MM_ScavengerHotFieldStats to be dynamically allocated

---

compiler/p/codegen/OMRRealRegister.cpp
compiler/p/codegen/OMRRealRegister.hpp

Prior, instructions that required CR registers were not correctly processed. An offset is needed to handle CR registers. This commit includes enabling handling for 1 Target, 2 Source Register Immediate instructions to be correctly formulated.
The implementation of the function needs to be moved from the corresponding .hpp file to the .cpp. This was necessary to determine that the register used to construct the instruction is a CR.
Signed-off-by: Alen Badel <Alen.Badel@ibm.com>

Fixing CR instruction handling on PPC

---

ddr/tools/getmacros

* fix regular expression for flag definitions so the following is properly recognized
```
#define FLAG // comment
```
* generate *_DEFINED constants with buildflags option
* manage separate flag and constant namespaces
* put {flag} in the 'Constants' namespace and {flag}_DEFINED in the 'Flags' namespace

Fix handling of 'flag' macros

---

CONTRIBUTING.md

Add a requirement to the Contributor Guidelines for compiler pull
requests involving IL or fundamental compiler architecture changes
that they be discussed at a Compiler Architecture Meeting (#2316).

Update Contributor Guidelines for compiler architecture reviews

---

port/common/omrport.tdf
port/unix/omrsysinfo.c

Added trace points on error conditions and entry and exit
tracepoints for port library APIs related to cgroups.

Add trace points to portlib APIs related to cgroups

---

gc/include/omrmodroncore.h

ddrgen associates literals of anonymous enums with the
enclosing scope. As there is no such scope in the case of
CARD_SIZE & CARD_SIZE_SHIFT these literals are not captured.
As macros they will be included in the superset & blob.
In support of https://github.com/eclipse/openj9/issues/378.

Replace CARD_SIZE & CARD_SIZE_SHIFT with macros

---

fvtest/porttest/CMakeLists.txt

Enable missing AIX port test in CMake

---

ddr/include/ddr/blobgen/java/genSuperset.hpp
ddr/include/ddr/ir/ClassType.hpp
ddr/include/ddr/ir/ClassUDT.hpp
ddr/include/ddr/ir/EnumUDT.hpp
ddr/include/ddr/ir/NamespaceUDT.hpp
ddr/include/ddr/ir/Type.hpp
ddr/include/ddr/ir/TypePrinter.hpp
ddr/include/ddr/ir/TypedefUDT.hpp
ddr/include/ddr/ir/UnionUDT.hpp
ddr/include/ddr/scanner/dwarf/DwarfScanner.hpp
ddr/lib/ddr-blobgen/java/genSuperset.cpp
ddr/lib/ddr-ir/ClassType.cpp
ddr/lib/ddr-ir/ClassUDT.cpp
ddr/lib/ddr-ir/EnumUDT.cpp
ddr/lib/ddr-ir/Makefile
ddr/lib/ddr-ir/Members.cpp
ddr/lib/ddr-ir/NamespaceUDT.cpp
ddr/lib/ddr-ir/Symbol_IR.cpp
ddr/lib/ddr-ir/Type.cpp
ddr/lib/ddr-ir/TypePrinter.cpp
ddr/lib/ddr-ir/TypedefUDT.cpp
ddr/lib/ddr-ir/UnionUDT.cpp
ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp
ddr/tools/ddrgen/ddrgen.cpp

Fix
* promote _enumMembers from ClassType to NamespaceUDT
* collect literals of a nested anonymous enum in enclosing namespace
Cleanup
* change signature of Type::getSymbolKindName()
* check that IO operations are successful
* remove unnecessary #include directives
* remove useless method TypedefUDT::insertUnique()
* manage printing type header in JavaSupersetGenerator
* extract common code for visiting class and union types
Addition
* add TypePrinter for debugging (currently disabled)
This should be the final OMR change required to enable https://github.com/eclipse/openj9/issues/378 on Linux.

Fix handling of literals of anonymous enum types

---

omrmakefiles/rules.mk

Reducing the footprint of *.i files eliminates writing useless content and also avoids later, unnecessary reads by getmacros. In OMR alone, the reduction is from over 230MB to about 36MB.

Reduce size of generated *.i files

---

.gitignore
port/win32/omrsysinfo.c

While the project is being built using CLang as the compiler on Windows, the following error appears:
```
C:\omr\port\win32\omrsysinfo.c(184,52):  error: '/*' within block comment [-Werror,-Wcomment]
#define _WIN32_WINNT_WIN10                  0x0A00 /* ABRACADABRA_THRESHOLD * /
```
It seems the compilator just ignores the `-Wno-comment` flag as well as the `-Wno-error=comment` one.
The following version of the toolchain is used:
```bash
clang-cl --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\llvm\bin
```

Fix  error: '/*' within block comment for CLang 6.0.0 for Windows

---

omrmakefiles/rules.mk

Unlike grep, sed won't fail if there are no matching lines. Even though make is ignoring such failures, build logs are cluttered with noise like this:
```
../../omrmakefiles/rules.mk:400: recipe for target 'BaseVirtual.i' failed
make[9]: [BaseVirtual.i] Error 1 (ignored)
```
Improves upon https://github.com/eclipse/omr/pull/2366.

Use sed instead of grep

---

fvtest/porttest/omrfilestreamTest.cpp

When `clang` is used for compilation `fvtest`, the following error occurs:
```bash
..\fvtest\porttest\omrfilestreamTest.cpp(1001,12):  error: ordered
comparison between pointer and zero ('OMRFileStream *' (aka '_iobuf *')
and 'int')
if (file < 0) {
```
It seems the code of `..\fvtest\porttest\omrfilestreamTest.cpp(1001,12)`
contains a typo:
```c
fd = omrfile_open(filePathName, EsOpenRead, 0444);
if (file < 0) { // !!!the typo is here!!!
outputErrorMessage(PORTTEST_ERROR_ARGS, "omrfile_open() returned error,
expected valid file handle\n", -1);
goto unlinkFile;
}
```
The construction `if (file < 0) {` changed to the `if (fd < 0) {` one to
match the 'open the file and check the file descriptor' pattern.

fvtest: Fix comparison between pointers and zero error

---

cmake/modules/platform/toolcfg/gnu.cmake
cmake/modules/platform/toolcfg/msvc.cmake
cmake/modules/platform/toolcfg/verify.cmake
cmake/modules/platform/toolcfg/xlc.cmake
thread/CMakeLists.txt

When `clang-cl` is used as a C/C++ compiler on Windows to build OMR, CMake attempts to link `DDR` with the `pthread` library and the following error appears:
```bash
lld-link: error: could not open pthread.lib: no such file or directory
```
This commit fixes the error.
In order to improve code readability, a refactoring of system information detection was applied: a new CMake variable is introduced: `OMR_PLATFORM_THREAD_LIBRARY`. A corresponding value is assigned to the variable in a `cmake/modules/platform/toolcfg/${OMR_TOOLCONFIG}` file. This refactoring allows developers just to include the platform dependent thread library to a `target_link_libraries` invocation if the developed component should be linked with the thread library.
**Warning:** The following code is put to `gnu.cmake`: …

CMake: Fix DDR on Windows building using Clang

---

doc/BuildingWithCMake.md

It's not clear enough how to build OMR on Microsoft Windows. The
following questions appear:
* Which toolchain to use: there are as least three wide used
toolchains on the market: MinGW, Visual Studio Build Tools and
LLVM/Clang so a new developer might be confused a bit why some
source files won't be compiled by using the picked toolchain.
* How to get the common prerequisite on the Windows platform, perl,
that is required to configure and build OMR using CMake.
* How to specify the picked compiler, linker and generator for CMake
and more important why does CMake usually can't find the required
tools ('rc', for example) and standard libraries (kernel32.lib and
so on).
* How to let CMake find the path to the DIA SDK that is required to
build the DDR component.
The answers to these …

[skip ci] Document how to build OMR on Windows using CMake

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/S390Debug.cpp
compiler/z/codegen/S390Instruction.hpp

The getSourceImmediate() API is being used incorrectly inside `TR_Debug::print(TR::FILE*,TR::S390RSInstruction*)`. The purpose of the query here is to check if _sourceImmediate is set. However, if it is set to 0, then the query evaluates as false. This can cause errors and crashes due to printing. This commit adds a new query to check if `_sourceImmediate` has been set, and cleans up the print function to correctly use the `hasMask()` query as well.

Fix checks when printing RS Instructions

---

gc/base/MemoryPoolLargeObjects.cpp

Run with memory check detected malloc'ed memory violation. It relates to
write to _loaFreeRatioHistory[] out-of-bound. This problem was
reproduced locally and it is confirmed that fix solved the issue.
Closed #2381

Fix index out-of-bound for _loaFreeRatioHistory[]

---

compiler/x/codegen/OMRTreeEvaluator.cpp

AtomicFetchAndAdd returns incorrect result, fixing it.

Fix incorrect return value from AtomicFetchAndAdd

---

compiler/z/codegen/S390GenerateInstructions.cpp

In memory reference constructor, if the load/store is a packed decimal
load/store and when vector VSI instructions are used, the index register
need to be handled separately by an intermediate LA instruction because
VSI instructions don't support index registers.

Make memory reference separate index register for PackedDecimal

---

gc/base/GCExtensionsBase.hpp
gc/base/standard/ParallelGlobalGC.cpp
gc/base/standard/Scavenger.cpp
gc/base/standard/Scavenger.hpp

Changes to preserve TLH remainders (scavenger copy cache) for reserved memory which can be reused for subsequent GCs. That is, references to the base and top of allocated TLH are saved (where appropriate) upon abandon.
This effectively reduces the tenure heap consumption, savings depend on 2 factors:
- Thread count
- Tenuring rate
For this reason, savings vary from negligible to magnitude of order lower tenure consumption rate. For instance, high tenuring (from non-generational workload) and low GC thread count results in lower savings, and opposite, very generational workload (low tenuring rate) with high GC thread count results in high savings.
For concurrent scavenger, we obtain additional savings from mutator threads as they create copy caches through a read barrier.
Additionally, …

Tenure Heap Recycling

---

fvtest/rastest/CMakeLists.txt
fvtest/rastest/cpuLoadAgent.c

A matrix in the method `static void matrixSquare(void)` is allocated on
the stack:
```c
uintptr_t matrix[MATRIX_SIZE][MATRIX_SIZE]
```
Because the constant `MATRIX_SIZE` is defined as `1000`, the amount of
memory needed to allocate `matrix` equals to `8000000`. This value is more
than the default stack size for the major C/C++ toolchains. In order to
protect the test from the Stack Overflow error, the `matrix` should be
allocated on the heap as discussed in #2386.
Closes: #2386

Allocate a matrix in the rastest on the heap

---

compiler/il/OMRNode.cpp
compiler/il/OMRNode.hpp
compiler/ras/IlVerifierHelpers.hpp
compiler/z/codegen/ControlFlowEvaluator.cpp
compiler/z/codegen/OMRLinkage.hpp
fvtest/compilertest/tests/OptTestDriver.cpp

Remove OMR::Node::getReturnCode(...) and OMR::Node::getReturnReason(...)
Remove checkEpilogKillsReturnCodeReason() from z/codegen/OMRLinkage.hpp
Closes: #2314 

Eliminate return, reason codes from Return IL nodes

---

compiler/codegen/FrontEnd.cpp
compiler/codegen/FrontEnd.hpp
compiler/codegen/OMRCodeGenPhase.cpp
compiler/optimizer/VPConstraint.cpp
compiler/optimizer/VPHandlers.cpp
compiler/ras/Debug.cpp
compiler/z/codegen/OMRTreeEvaluator.cpp

The compiler must use read barriers when dereferencing collected references.

Read Barrier on collected reference dereference

---

run_configure.mk

The path list separator should be : not ; when running
under a Unix-like environment, otherwise this particular
path that's being added to the start of the list ends up
being prepended to the first path on the list and
invalidating both.
Also change back-slashes to forward-slashes to be
more consistent.

Fix existing PATH hack for Windows

---

thread/common/omrthread.c

Adjusted code to do the ASSERT() before dereferencing the
variable.  This way the assert will fire before the code
will crash.

ASSERT before dereferencing asserted variable

---

compiler/arm/codegen/BinaryCommutativeAnalyser.cpp
compiler/arm/codegen/BinaryCommutativeAnalyser.hpp

BinaryCommutativeAnalyser.hpp and .cpp for ARM are not currently used
from anywhere.  This commit adds comments to those files instead of
removing them entirely from the repository.

Add comments to JIT BinaryCommutativeAnalyser files for ARM

---

compiler/compile/Method.cpp
compiler/compile/ResolvedMethod.hpp

Disable peeking under HCR and introduce
genMethodILForPeekingEvenUnderHCR for optimizations that have protection
when HCR happens.

Disable peeking under HCR

---

compiler/codegen/OMRCodeGenPhase.cpp
compiler/ras/Debug.cpp
compiler/ras/Debug.hpp
compiler/x/codegen/DataSnippet.cpp
compiler/x/codegen/OMRCodeGenerator.cpp
compiler/x/codegen/OMRCodeGenerator.hpp
compiler/x/codegen/X86Debug.cpp

Data snippet was not properly printed in trace
log, fixing it.

Fix for missing data snippet in trace log

---

compiler/optimizer/Inliner.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/PreExistence.cpp
compiler/optimizer/PreExistence.hpp

KnowledgeLevel returns FIXED_CLASS if getFixedClass, which returns
_fixedClass, is not null. This wrong because _fixedClass and
getFixedClass() in TR_PrexArgument are used to store and get the class
of the argument regardless of its kind. This change will fix
KnowledgeLevel and use _class and getClass() to avoid misleading.

Fix bug in KnowledgeLevel

---

include_core/omrport.h
port/common/omrport.c
port/common/omrsignal.c
port/omrportpriv.h
port/unix/omrsignal.c
port/win32/omrsignal.c
port/win64amd/omrsignal.c
port/ztpf/omrsignal.c

Stubs have been added for the following new `omrsig` functions:
1) `omrsig_set_single_async_signal_handler`
2) `omrsig_map_os_signal_to_portlib_signal`
3) `omrsig_map_portlib_signal_to_os_signal`
File `omrsig.c` doesn't exist. Instead, functions are defined in 
`omrsignal.c`. Update comments to use `omrsignal.c` instead of 
`omrsig.c`.
OMR Issue: https://github.com/eclipse/omr/issues/2332

Add stubs for new omrsig functions

---

.travis.yml

Currently, the OMRChecker lint job on Travis CI runs
in Precise. It is in the process of being decommisoned,
and the tentative official end of support for Precise
by Travis CI was April 1st 2018. This patch upgrades the
environment to Trusty, and also makes use of clang-3.8
instead of clang-3.4.
[Travis CI Blog post regarding this matter](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status)

Upgrade lint job environment on Travis CI to Trusty

---

ddr/include/ddr/scanner/pdb/PdbScanner.hpp
ddr/lib/ddr-blobgen/java/genBinaryBlob.cpp
ddr/lib/ddr-blobgen/java/genSuperset.cpp
ddr/lib/ddr-ir/TypePrinter.cpp
ddr/lib/ddr-scanner/pdb/PdbScanner.cpp
ddr/tools/getmacros
gc/base/HeapRegionDescriptor.hpp
gc/base/MemorySubSpace.hpp
gc/include/omrmm.hdf
omrmakefiles/rules.mk
thread/win32/dllmain.c

Most of the changes here are to `PdbSCanner`, the Windows-specific debug information extraction code:
* avoid premature typedef expansion
* fix handling of blacklisted types and namespaces
* add explicit cases for char and wchar_t (treat char as unsigned like other platforms)
* capture values of literals
* fix handling of anonymous types and namespaces
* fix postponed type resolution
* fix handling of nested blacklisted types
* fix nested anonymous enum types (promote literals of anonymous enum to enclosing scope)
* removed duplicate, unused getName() function
* removed redundant getUDTname() function
* removed renameAnonymousTypes() functions which are no longer useful
* add MSDIA120 to the list of supported libraries
* remove broken progress reporting
* general cleanup surrounding error …

Enable DDR on Windows

---

omrmakefiles/rules.linux.mk
omrmakefiles/rules.ztpf.mk

In the makefiles, the command to link the stripped library to the debug
info has arguments in the wrong order.
Also, call objectcopy to create the debug file with only debug symbols
instead of copying the entire .so file.
FYI: @jjohnst-us

Fix objcopy invocation for creating shared libraries debug info

---

compiler/z/codegen/OMRCodeGenerator.cpp
compiler/z/codegen/OMRCodeGenerator.hpp
compiler/z/codegen/OMRTreeEvaluator.cpp
compiler/z/codegen/OMRTreeEvaluator.hpp
compiler/z/codegen/TreeEvaluatorTable.hpp
fvtest/compilertriltest/BitPermuteTest.cpp

Implement the bitPermute Evaluator for z/codegen

Add the bitPermute Evaluator for Z

---

omrmakefiles/rules.aix.mk

The xlc compiler may replace certain library calls with optimized
versions from the xlopt library. If the xlc executable is used to
link shared libraries/executables everything works. If ld is used
to link the libraries/executable you need to specify the xlopt
library on the link line.

Resolve link issue when using ld

---

port/unix/omrsignal.c

Two issues are being addressed in this pull request:
1. **Fix issue with re-registering master handlers**. `OMRSIG_SIGACTION` can be called outside of `omrsignal.c` functions. A call to `OMRSIG_SIGACTION` will override the master handlers set by either `omrsig_protect` or `omrsig_set_async_signal_handler`. Setting a master handler once sets a bit in `signalsWithMasterHandlers`. If the master handler is overridden by an external call to `OMRSIG_SIGACTION`, then the bit in `signalsWithMasterHandlers` will not be un-set. Since the bit in `signalsWithMasterHandlers` isn't un-set once the master handler has been overridden, then subsequent calls to `omrsig_protect` and `omrsig_set_async_signal_handler` will not re-register the master handler. In subsequent calls, it will look as if the master …

Fix signal issues unix

---

compiler/optimizer/ValuePropagationTable.hpp
compiler/ras/Tree.cpp

Remove the obsolete pdremSelect opCode from the code base.

Remove the obsolete pdremSelect opCode

---

gc/base/MarkingScheme.hpp

Print relevant info for the assert in Concurrent Scavenger, when a
forwarded object is encounter in Concurrent Marking when CS is not in
progress.

Extend CS assert with a print

---

fvtest/rastest/cpuLoadAgent.mk
omrmakefiles/rules.aix.mk

* change makes assumptions on library path that does not exist for all xlc versions
* lower optimization on cpuLoadAgent test to work with xlc13 without above change

Reverse #2463 'Resolve link issue when using ld'

---

compiler/arm/codegen/OMRInstruction.hpp
compiler/arm/codegen/OMRMachine.hpp
compiler/codegen/ELFRelocationResolver.hpp
compiler/codegen/Machine.hpp
compiler/codegen/OMRInstruction.hpp
compiler/codegen/OMRMachine.hpp
compiler/compile/OMRCompilation.hpp
compiler/p/codegen/Instruction.hpp
compiler/p/codegen/OMRCodeGenerator.hpp
compiler/p/codegen/OMRInstruction.hpp
compiler/p/codegen/OMRMachine.hpp
compiler/p/runtime/OMRCodeCacheConfig.hpp
compiler/runtime/CodeCacheManager.hpp
compiler/runtime/CodeCacheMemorySegment.hpp
compiler/runtime/OMRCodeCache.hpp
compiler/runtime/OMRCodeCacheConfig.hpp
compiler/runtime/OMRCodeCacheMemorySegment.hpp
compiler/x/amd64/codegen/OMRMachine.hpp
compiler/x/codegen/Instruction.hpp
compiler/x/codegen/OMRInstruction.hpp
compiler/x/codegen/OMRMachine.hpp
compiler/x/env/OMRCPU.hpp
compiler/x/i386/codegen/OMRMachine.hpp
compiler/z/codegen/Instruction.hpp
compiler/z/codegen/OMRInstruction.hpp
compiler/z/codegen/OMRLinkage.hpp
compiler/z/codegen/OMRMachine.hpp
jitbuilder/codegen/CodeGenerator.hpp

* Fix concrete extensible class macro names
* Fix extensible class connector macros (remove COMPOSED)
* Fix extensible class connector macros (remove BASE)

Make extensible class macro naming more consistent and correct

---

compiler/aarch64/CMakeLists.txt
compiler/aarch64/codegen/OMRCodeGenerator.cpp
compiler/aarch64/codegen/OMRCodeGenerator.hpp
compiler/aarch64/codegen/OMRMachine.cpp
compiler/aarch64/codegen/OMRMachine.hpp
compiler/aarch64/codegen/OMRRealRegister.hpp
compiler/arm/codegen/OMRMachine.hpp
compiler/codegen/Machine.hpp
compiler/codegen/OMRMachine.hpp
compiler/p/codegen/OMRMachine.hpp
compiler/x/amd64/codegen/OMRMachine.hpp
compiler/x/codegen/OMRMachine.hpp
compiler/x/i386/codegen/OMRMachine.hpp
compiler/z/codegen/OMRMachine.hpp

* Stub out some initial AArch64 code generator extensible classes
* Rename Machine class connector macro
Issue: #2348

AArch64: Provide some core extensible class stubs

---

compiler/z/codegen/OMRMemoryReference.cpp
compiler/z/codegen/S390GenerateInstructions.cpp

This pull request contains two commits:
1. The VRSb instruction format does not support index fields.
Fix the generateVRSbInstruction() API so it separates the memory
references index register. 
2.  Add an assert check to make sure the right node is used to generate memory reference. 
The generateS390MemoryReference(TR::Node*, TR::CodeGenerator*,bool)
API uses a constructor that handles load and store nodes with symbol
references. If the node has a no symbol reference, the compiler can crash in binary encoding.

VRSb instruction memory reference needs separate index register

---

compiler/aarch64/codegen/OMRRealRegister.cpp
compiler/aarch64/codegen/OMRRealRegister.hpp
compiler/aarch64/codegen/RealRegister.hpp
compiler/aarch64/codegen/RealRegisterEnum.hpp
compiler/aarch64/codegen/RealRegisterMaskEnum.hpp

This commit implements the initial version of RealRegister-related
files for aarch64.
This is a part of #2465.

AArch64: Initial version of RealRegister-related files

---

compiler/p/codegen/FPTreeEvaluator.cpp
compiler/p/codegen/OMRInstOpCode.hpp
compiler/p/codegen/OMRInstruction.hpp
compiler/p/codegen/PPCBinaryEncoding.cpp
compiler/p/codegen/PPCInstruction.cpp

dcmplt and dcmpgt (Along with fcmpgt and fcmplt) use setbool in order to compare and set the required bit results.
Prior, the sequence setbool expansion was implemented incorrectly. 
-fcmpu compares input arguments, the result is stored in the conditional register (Bits LT,GT,EQ, and SO). 
-setb reads the condition register and set the bit result based on the LT and GT fields.
-setb checks bit set in the LT field will result to the output -1 (or 0xfff) if it's high. 
Therefore, in some situations the result was incorrect. Since when the LT bit is high, the result bit is not set correctly. No matter if dcmplt or dcmpgt is called. 
With this change:
-only with dcmplt and fcmplt , we move LT bit of the condition register to the GT bit. 
-When running dcmpgt and fcmpgt, moving is not needed …

Fixing dcmplt and dcmpgt Instruction handling on PPC

---

compiler/optimizer/Inliner.cpp

Starting in ade5a1cc, isNotCollected() returns true for primitives,
which causes this conditional to assign them all fresh temporaries.

Share result temps for primitive return values

---

compiler/x/codegen/X86Debug.cpp

Data snippet label name is missing in tracelog on X86, adding it.

Print data snippet label name log in tracelog

---

compiler/il/OMRBlock.cpp
compiler/il/OMRBlock.hpp
compiler/optimizer/DeadTreesElimination.cpp
compiler/optimizer/LocalOpts.cpp
compiler/optimizer/LocalOpts.hpp

Some very late passes of global dead store elimination and dead trees
elimination in openj9 can create opportunities for redundant goto
elimination after GRA (global register allocation). This series updates
redundant goto elimination so that it works on blocks that have register
dependencies, and then makes dead trees elimination request it on
promising blocks. This way it's possible to add an "if enabled" pass of
redundant goto elimination that only looks at blocks where these
opportunities are likely to have been created.

Prepare redundant goto elim for post-GRA requests

---

gc/base/GCExtensionsBase.cpp
gc/base/GCExtensionsBase.hpp

Added a new field 'usablePhysicalMemory' in GC_ExtensionsBase to
store the value returned by omrsysinfo_get_addressable_physical_memory().

Store addressable physical memory in GC_ExtensionsBase

---

gc/base/GCExtensionsBase.cpp
gc/base/GCExtensionsBase.hpp

GC_ExtensionsBase::usablePhysicalMemory should be of same type as the value
returned by omrsysinfo_get_addressable_physical_memory() which is uint64_t.

Fix data type of GC_ExtensionsBase::usablePhysicalMemory

---

configure
configure.ac
ddr/Makefile
ddr/tools/ddrgen/Makefile
omrmakefiles/configure.mk.in

Location of DIA-SDK can be:
- specified explicitly via OMR_DIASDK_HOME configuration variable
- or found relative to cl.exe.
Relocate addition of DIASDK_HOME to include path so it is available for all code of ddr tools.
Simplify compound configure tests.

Configure location of DIA-SDK needed by PdbScanner

---

ddr/tools/getmacros

* reduce number of processes created
* extract work per file so only a single redirection is needed
* use BASH_REMATCH to extract macro names
* run make with '--jobs=8'
* add timestamps to progress messages

Streamline getmacros script to extract constants for DDR

---

cmake/modules/platform/toolcfg/msvc.cmake
include_core/OMR_Agent.hpp
omr/OMR_Agent.cpp

Clang/LLVM isn't able to compile the compilator's code when exception handling
is not enabled:
```
error: cannot use 'throw' with exceptions disabled
throw Exception();
```
Warning C4291:
```
..\omr\OMR_Agent.cpp(145): warning C4291: 'void *OMR_Agent::operator
new(::size_t,void *)': no matching operator delete found; memory will
not be freed if initialization throws an exception
omr\include_core\OMR_Agent.hpp(136): note: see declaration of
'OMR_Agent::operator new'
```
has also been fixed.

CMake: Enable exception handling

---

gc/base/Configuration.cpp
gc/base/EnvironmentBase.hpp
gc/base/standard/ConfigurationGenerational.cpp
gc/base/standard/ConfigurationGenerational.hpp
gc/base/standard/EnvironmentStandard.cpp
gc/startup/omrgcstartup.cpp

Fixing two issues with Concurrent Scavenger:
1. Modified shutdown sequence to do Scavenger tear down later in the
sequence; after all of the mutator threads are done. 
2. Added a new case in flushGCCaches to clear a GC Slave thread
copy cache when starting up with many GC
threads and GC slave thread is brought up during active scavenger cycle
but doesn't do any actual work and so is actually acting like a mutator
thread until the next cycle.
Signed-off-by: Evgenia Badyanova <evgeniab@ca.ibm.com>

 Modify shutdown sequence to fix CS issue

---

.gitignore

The entry right now says "build/" but this will match any directory
called "build" including anything below, say, jitbuilder/build . Given
the latter directory is revision controlled, it's not correct for it
to be ignored.
Fix is to use /build/ as the entry (leading slash makes it only apply
to the top level directory in the repo).

Correct .gitignore entry for build/ directory

---

gc/base/Configuration.cpp

A recent change requires Configure.cpp to know the full shape
of a MemorySpace object, but Configure.cpp only #include's
MemorySpace.hpp via some other header file. Worse, it may
not include MemorySpace.hpp under some configuration settings.
So let's just explicitly #include it.
Signed-off-buy: Mark Stoodley <mstoodle@ca.ibm.com>

Include MemorySpace.hpp in gc/base/Configure.cpp

---

.travis.yml
port/unix/omrintrospect.c
scripts/build-on-travis.sh

Travis builds will now test the following:
1. OSX 64 bit using CMake with Unix Makefiles
2. Linux 32 bit using CMake with Ninja
3. Linux 64 bit compressed references using autotools
4. Linux 64 bit Lint build

Cleanup travis builds

---

compiler/aarch64/codegen/OMRMachine.cpp
compiler/aarch64/codegen/OMRMachine.hpp
compiler/arm/codegen/OMRMachine.cpp
compiler/arm/codegen/OMRMachine.hpp
compiler/codegen/OMRMachine.hpp
compiler/p/codegen/OMRMachine.cpp
compiler/p/codegen/OMRMachine.hpp
compiler/x/codegen/OMRMachine.cpp
compiler/x/codegen/OMRMachine.hpp
compiler/z/codegen/OMRMachine.cpp
compiler/z/codegen/OMRMachine.hpp

Move CodeGenerator object from architecture specializations of OMR::<ARCH>::Machine to base OMR::Machine class.
Closes: #2485 

Move CodeGenerator object from architecture specific to base OMR::Machine

---

gc/base/GCExtensionsBase.hpp
gc/base/HeapVirtualMemory.cpp

This variable is not used and can be deleted

Remove unused heaptailpadding from GC Extensions

---

compiler/codegen/OMRRegister.cpp
compiler/codegen/OMRRegister.hpp
compiler/z/codegen/OMRMachine.cpp

Removing getColouredRegister and setColouredRegister from base CodeGen and their references.
Closes: #2467 

Remove unused coloured register APIs

---

fvtest/porttest/omrsignalTest.cpp
include_core/omrport.h
port/common/omrport.c
port/common/omrport.tdf
port/common/omrsignal.c
port/omrportpriv.h
port/unix/omrsignal.c
port/win32/omrsignal.c
port/win64amd/omrsignal.c
port/ztpf/omrsignal.c

9 new commits have been added to support OMR Signal API extension/improvement.
1) **Add new OMR Signal API: omrsig_register_os_handler**
omrsig_register_os_handler will register a handler with the OS. Stubs
have been added for omrsig_register_os_handler.
On Unix variants, we cache the original OS handler in oldActions while
registering the first handler with the OS. The original OS handler is
restored during shutdown.
If OMRSIG_SIGACTION is called outside OMR, then the original OS handler
will be overwritten without being cached in oldActions. Subsequently,
the oldActions may cache a user handler instead of the original OS
handler. During shutdown, we may not restore the original OS handler
incorrectly.
The new API, omrsig_register_os_handler, will let a user register a
handler with the …

Extend OMR Signal API [Part 2]

---

include_core/AtomicSupport.hpp

fixes the missing semi colon in include_core atomic operation that would prevent successful build for AArch64
Signed-off-by: jeanlego <jeanphilippe.legault@unb.ca>

AArch64: fix missing semi colon in atomic operations

---

compiler/il/OMRBlock.cpp
compiler/optimizer/LocalOpts.cpp

OMR::Block::changeBranchDestination() deletes the outgoing edge from the
control flow graph (CFG) when the branch already targets newDestination.
This means that an unnecessary call to changeBranchDestination() can
corrupt the CFG.
Redundant goto elimination can make such calls since eb94ed52.
Now changeBranchDestination() will safely ignore these calls, and
redundant goto elimination will avoid making them.

Avoid breaking CFG in redundant goto elimination

---

gc/base/standard/ConcurrentGC.cpp
gc/base/standard/ConcurrentGC.hpp
gc/base/standard/ConcurrentOverflow.cpp

_initRanges is a table that drives parallel setting/reseting of Mark Map
in Tenure/Nursery at the begining of Concurrent Marking CM)
cycle/begining STW phase.
In presence of Concurrent Scavenger (CS), that can over lap with CM, and
if Tenure heap expansion occurs (due to failed tenuring), the table will
be updated. 
This change will make the heap expanding thread simply skip the table
update if it senses that init in is progress. The table update is left
for a later, safer point .
BTW, if initializaiton is already in progress, the thread doing heap
expansion will do Mark Map work for the expaned part of the heap (this
part, and deferral of the table update is actually already handled for
standard Scavenger), so it does not really matter if update of
_initRanges occurs just after Mark Map …

Fix _initRanges race with CM and CS

---

compiler/z/codegen/OMRLinkage.hpp
compiler/z/codegen/S390BranchCondNames.cpp
compiler/z/codegen/S390Debug.cpp
compiler/z/codegen/S390Evaluator.hpp

- Remove BranchConditionToNameMap_ForListing 
- Remove TR_S390RelocXPLinkOffsetToEntryPtMarker 
- Remove unimplemented evaluators 
- Remove S390Debug deprecated #defines and APIs 

Dead code cleanup in Z codegen
